# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Подешавања рада ван мреже
autodetect-connection-label =
    .label = Самостално пребаци режиме када се пронађе интернет веза
    .accesskey = ц
offline-startup-label = При отварању { -brand-short-name }-а:
status-radio-last-used =
    .label = Употреби последњи коришћени режим везе
    .accesskey = б
status-radio-ask-connect =
    .label = Питај да ли да се повеже на мрежу
    .accesskey = ј
status-radio-start-online =
    .label = Покрени на мрежи
    .accesskey = о
status-radio-start-offline =
    .label = Покрени ван мреже
    .accesskey = в
going-online-prompt = Пошаљи поруке које чекају у вашем одлазном сандучету
going-online-send =
    .label = Пошаљи самостално
    .accesskey = и
going-online-keep =
    .label = Задржи у „За слање“
    .accesskey = д
going-online-ask-send =
    .label = Питај пре слања
    .accesskey = с
going-offline-prompt = Желите ли да преузмете поруке како бисте их читали ван мреже?
going-offline-download =
    .label = Преузми самостално
    .accesskey = м
going-offline-keep =
    .label = Не преузимај омоте
    .accesskey = о
going-offline-ask-download =
    .label = Питај пре преузимања
    .accesskey = т
autodetect-online-label =
    .label = Самостално прати пронађено стање рада на мрежи
    .accesskey = т
offline-preference-startup-label = Ручно стање приликом покретања:
status-radio-remember =
    .label = Запамти претходно стање рада на мрежи
    .accesskey = З
status-radio-ask =
    .label = Питај ме за стање рада на мрежи
    .accesskey = ј
status-radio-always-online =
    .label = На мрежи
    .accesskey = Н
status-radio-always-offline =
    .label = Ван мреже
    .accesskey = В
going-online-label = Послати непослате поруке након повезивања на мрежу?
going-online-auto =
    .label = Да
    .accesskey = Д
going-online-not =
    .label = Не
    .accesskey = Н
going-online-ask =
    .label = Питај ме
    .accesskey = ј
going-offline-label = Преузети поруке за употребу ван мреже пре одласка у рад ван мреже?
going-offline-auto =
    .label = Да
    .accesskey = а
going-offline-not =
    .label = Не
    .accesskey = е
going-offline-ask =
    .label = Питај ме
    .accesskey = т
