# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Nombre para mostrar
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tipo
vcard-entry-type-home = Casa
vcard-entry-type-work = Trabajo
vcard-entry-type-none = Ninguno
vcard-entry-type-custom = Personalizado
vcard-name-header = Nombre
vcard-n-prefix = Prefijo
vcard-n-add-prefix =
    .title = Añadir prefijo
vcard-n-firstname = Nombre
vcard-n-add-firstname =
    .title = Añadir nombre
vcard-n-middlename = Segundo nombre
vcard-n-add-middlename =
    .title = Añadir segundo nombre
vcard-n-lastname = Apellido
vcard-n-add-lastname =
    .title = Añadir apellido
vcard-n-suffix = Sufijo
vcard-n-add-suffix =
    .title = Añadir sufijo
vcard-nickname = Apodo
vcard-email-header = Direcciones de correo electrónico
vcard-email-add = Añadir dirección de correo electrónico
vcard-email-label = Dirección de correo electrónico
vcard-primary-email-label = Predeterminado
vcard-url-header = Páginas web
vcard-url-add = Añadir página web
vcard-url-label = Página web
vcard-tel-header = Números de teléfono
vcard-tel-add = Añadir número de teléfono
vcard-tel-label = Número de teléfono
# Or "Mobile"
vcard-entry-type-cell = Móvil
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Buscapersonas
vcard-tz-header = Zona horaria
vcard-tz-add = Añadir zona horaria
vcard-impp2-header = Mensajería instantánea
vcard-impp-add = Añadir cuenta de chat
vcard-impp-label = Cuenta de chat
vcard-impp-select = Protocolo
vcard-impp-option-other = Otros
vcard-impp-input-label = URI
vcard-impp-input-title = URI para mensajería instantánea
vcard-bday-anniversary-header = Fechas especiales
vcard-bday-anniversary-add = Añadir fecha especial
vcard-bday-label = Cumpleaños
vcard-anniversary-label = Aniversario
vcard-date-day = Día
vcard-date-month = Mes
vcard-date-year = Año
vcard-adr-header = Direcciones
vcard-adr-add = Añadir dirección
vcard-adr-label = Dirección
vcard-adr-delivery-label = Etiqueta de entrega
vcard-adr-street = Dirección postal
# Or "Locality"
vcard-adr-locality = Ciudad
# Or "Region"
vcard-adr-region = Provincia/Estado
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Código postal/ZIP
vcard-adr-country = País
vcard-note-header = Notas
vcard-note-add = Añadir nota
vcard-org-header = Propiedades de la organización
vcard-org-add = Añadir propiedades de la organización
vcard-org-title = Cargo
vcard-org-title-input =
    .placeholder = Puesto de trabajo
    .title = Cargo o trabajo
vcard-org-role = Rol
vcard-org-role-input =
    .placeholder = Rol en un proyecto
    .title = Función o cargo desempeñado en un puesto concreto
vcard-org-org = Organización
vcard-org-org-input =
    .placeholder = Nombre de la empresa
    .title = Nombre de la organización
vcard-org-org-unit = Departamento
vcard-org-org-unit-input =
    .placeholder = Departamento
    .title = Nombre de la unidad organizativa
vcard-custom-header = Propiedades personalizadas
vcard-custom-add = Añadir propiedades personalizadas
vcard-remove-button-title =
    .title = Eliminar
vcard-remove-button = Eliminar
