# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (start.prefix):
# datetimes with these in front are extracted as start times
# can be a list of values, separate variants by |
start.prefix =
# LOCALIZATION NOTE (start.suffix):
# datetimes followed by these are extracted as start times
start.suffix = om | fan | op | - | start | begjin | begjint | fan ôf
# LOCALIZATION NOTE (end.prefix):
# datetimes with these in front are extracted as end times
end.prefix = om | oant | ta | - | tot | en | ein | einde
# LOCALIZATION NOTE (end.suffix):
# datetimes followed by these are extracted as end times
# can be a list of values, separate variants by |
end.suffix =
# LOCALIZATION NOTE (no.datetime.prefix):
# datetimes with these in front won't be used
# specify full words here
no.datetime.prefix = lêste wike | fersstjoerd | email | e-mail | yn stee fan | > | spitigernôch | yn | net
# LOCALIZATION NOTE (no.datetime.suffix):
# datetimes followed by these won't be used
no.datetime.suffix = email | e-mail | > | % | euro | euros
# LOCALIZATION NOTE (from.today):
# must not be empty!
from.today = hjoed
from.tomorrow = moarn
# LOCALIZATION NOTE (until.*):
# can be a list of values, separate variants by |
until.tomorrow =
# LOCALIZATION NOTE (from.ordinal.date):
##1 = matches numbers 1-31 and number.x
# should not have "#1" as this would match any single number in email to a time
from.ordinal.date = #1e | #1e | #1e | #1e
# LOCALIZATION NOTE (until.ordinal.date):
##1 = matches numbers 1-31 and number.x
until.ordinal.date =
from.noon = middei
until.noon =
# LOCALIZATION NOTE (from.hour):
##1 = matches numbers 0-23 and number.0-number.23
# should not have "#1" as this would match any single number in email to a time
from.hour = om #1 | rûn #1 | #1 - | #1 oant
# LOCALIZATION NOTE (until.hour):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour = - #1 | oant #1 | oant #1 | om #1
# LOCALIZATION NOTE (from.hour.am):
##1 = matches numbers 0-23 and number.0-number.23
from.hour.am = #1 am | #1 a.m
# LOCALIZATION NOTE (until.hour.am):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour.am =
# LOCALIZATION NOTE (from.hour.pm):
##1 = matches numbers 0-23 and number.0-number.23
from.hour.pm = #1 pm | #1 p.m | #1 p
# LOCALIZATION NOTE (until.hour.pm):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour.pm =
# LOCALIZATION NOTE (from.half.hour.before):
# denotes times 30 minutes before next full hour
from.half.hour.before = half #1
# LOCALIZATION NOTE (until.half.hour.before):
# denotes times 30 minutes before next full hour
until.half.hour.before =
# LOCALIZATION NOTE (from.half.hour.after):
# denotes times 30 minutes after last full hour
from.half.hour.after = heal oer nei #1
# LOCALIZATION NOTE (until.half.hour.after):
# denotes times 30 minutes after last full hour
until.half.hour.after =
# LOCALIZATION NOTE (from.hour.minutes):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes = #1:#2 | om #1#2
# LOCALIZATION NOTE (until.hour.minutes):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes =
# LOCALIZATION NOTE (from.hour.minutes.am):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes.am = #1:#2 am | #1:#2 a.m
# LOCALIZATION NOTE (until.hour.minutes.am):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes.am =
# LOCALIZATION NOTE (from.hour.minutes.pm):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes.pm = #1:#2 pm | #1:#2 p.m | #1:#2 p
# LOCALIZATION NOTE (until.hour.minutes.pm):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes.pm =
# LOCALIZATION NOTE (from.monthname.day):
##1 = matches numbers 1-31 and number.x
##2 = matches monthname
from.monthname.day = #1 #2 | #1 #2 | #1e #2 | #1e #2 | #1e #2 | #1e #2 | #1e fan #2 | #1e fan #2 | #1e fan #2 | #1e fan #2
# LOCALIZATION NOTE (until.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
until.monthname.day =
# LOCALIZATION NOTE (from.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
from.month.day = #1-#2
# LOCALIZATION NOTE (until.month.day):
##1 = matches numbers 1-31 and number.x
##2 = matches numbers 1-12
until.month.day =
# LOCALIZATION NOTE (from.year.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
##3 = matches 2/4 numbers
from.year.month.day = #1/#2/#3 | #1/#2/#3 | #1-#2-#3
# LOCALIZATION NOTE (until.year.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
##3 = matches 2/4 numbers
until.year.month.day =
# LOCALIZATION NOTE (from.year.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
##3 = matches 2/4 numbers
from.year.monthname.day = #1 #2 #3 | #1e #2 #3 | #1e #2 #3 | #1e #2 #3 | #1e #2 #3 | #1 #2 #3 | #1-#2-#3
# LOCALIZATION NOTE (until.year.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
##3 = matches 2/4 numbers
until.year.monthname.day =
# LOCALIZATION NOTE (duration.minutes):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.minutes = #1 minuten | #1 min | #1 min
# LOCALIZATION NOTE (duration.hours):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.hours = #1 oere | #1 oeren
# LOCALIZATION NOTE (duration.days):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.days = #1 dagen
# LOCALIZATION NOTE (month.*):
# can be a list of values, separate variants by |
month.1 = jannewaris | jan | jan.
month.2 = febrewaris | feb | feb.
month.3 = maart | mar | mar.
month.4 = april | apr | apr.
month.5 = maaie | maa | maa.
month.6 = juny | jun | jun.
month.7 = july | jul | jul.
month.8 = augustus | aug | aug.
month.9 = septimber | sep | sep. | sept.
month.10 = oktober | okt | okt.
month.11 = novimber | nov | nov.
month.12 = desimber | des | des.
# LOCALIZATION NOTE (from.weekday.*):
# used to derive start date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (from.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
from.weekday.0 = snein | sneins
from.weekday.1 = moandei | moandeis
from.weekday.2 = tiisdei | tiisdeis
from.weekday.3 = woansdei | woansdeis
from.weekday.4 = tongersdei | tongersdeis
from.weekday.5 = freed | freeds
from.weekday.6 = sneon | sneons
# LOCALIZATION NOTE (until.weekday.*):
# used to derive end date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (until.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
until.weekday.0 =
until.weekday.1 =
until.weekday.2 =
until.weekday.3 =
until.weekday.4 =
until.weekday.5 =
until.weekday.6 =
# LOCALIZATION NOTE (number.*):
# used within other patterns to understand dates where day of month isn't written with digits
# can be a list of values, separate variants by |
number.0 = nu
number.1 = ien | earste
number.2 = twa | twadde
number.3 = tije | tredde
number.4 = fjouwer | fjirde
number.5 = fiif | fiifde
number.6 = seis | sechsde
number.7 = sân | sânde
number.8 = acht | achtste
number.9 = njoggen | njoggende
number.10 = tsien | tsiende
number.11 = âlve | âlfde
number.12 = tôlve | tôlfde
number.13 = trettjin | trettjinde
number.14 = fjirtjin | fjirtjinde
number.15 = fiiftjin | fiiftjinde
number.16 = sechtjin | sechtjinde
number.17 = santjin | santjinde
number.18 = achtjin | achtjinde
number.19 = njoggentjin | njoggentjinde
number.20 = tweintich | tweintichste
number.21 = ienentweintich | ienentweintichste
number.22 = twaentweintich | twaentweintichste
number.23 = trijentweintich | trijentweintichste
number.24 = fjouwerentweintich | fjouwerentweintichste
number.25 = fiifentweintich | fiifentweintichste
number.26 = seisentweintich | seisentweintichste
number.27 = sânentweintich | sânentweintichste
number.28 = achtentweintich | achtentweintichste
number.29 = njoggenentweintich | njoggenentweintichste
number.30 = tritich | tritichste
number.31 = ienentritich | ienentritichste
# LOCALIZATION NOTE (alphabet):
# list all lower and uppercase letters if your language has an alphabet
# otherwise leave it empty
alphabet = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
