# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Hledání…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Nalezen #1 výskyt;Nalezeny #1 výskyty;Nalezeno #1 výskytů
noMatchesFound = Nic nebylo nalezeno
labelForStopButton = Zastavit
labelForSearchButton = Hledat
labelForStopButton.accesskey = Z
labelForSearchButton.accesskey = H
moreButtonTooltipText = Přidat pravidlo
lessButtonTooltipText = Odebrat pravidlo
