# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espai flexible
search-bar-label = Cerca
toolbar-write-message-label = Redacta
toolbar-write-message =
    .title = Crea un missatge nou
toolbar-move-to-label = Mou a
toolbar-move-to =
    .title = Mou el missatge seleccionat
toolbar-unifinder-label = Cerca cites
toolbar-unifinder =
    .title = Mostra/amaga la subfinestra de cerca de cites
toolbar-folder-location-label = Ubicació de la carpeta
toolbar-folder-location =
    .title = Canvia a la carpeta
toolbar-edit-event-label = Edita
toolbar-edit-event =
    .title = Edita la cita o la tasca seleccionada
toolbar-get-messages-label = Recupera
toolbar-get-messages =
    .title = Recupera els missatges nous de tots els comptes
toolbar-reply-label = Respon
toolbar-reply =
    .title = Respon el missatge
toolbar-reply-all-label = Respon a tots
toolbar-reply-all =
    .title = Respon al remitent i a tots els destinataris
toolbar-reply-to-list-label = Respon a la llista
toolbar-reply-to-list =
    .title = Respon a la llista de correu
toolbar-redirect-label = Redirigeix
toolbar-redirect =
    .title = Redirigeix el missatge seleccionat
toolbar-archive-label = Arxiva
toolbar-archive =
    .title = Arxiva els missatges seleccionats
toolbar-conversation-label = Conversa
toolbar-conversation =
    .title = Mostra la conversa del missatge seleccionat
toolbar-previous-unread-label = Anterior per llegir
toolbar-previous-unread =
    .title = Vés a l'anterior missatge per llegir
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Vés al missatge anterior
toolbar-next-unread-label = Següent per llegir
toolbar-next-unread =
    .title = Vés al següent missatge per llegir
toolbar-next-label = Següent
toolbar-next =
    .title = Vés al missatge següent
toolbar-junk-label = Correu brossa
toolbar-junk =
    .title = Marca els missatges seleccionats com a correu brossa
toolbar-delete-label = Suprimeix
toolbar-delete-title =
    .title = Suprimeix els missatges seleccionats
toolbar-undelete-label = Desfés la supressió
toolbar-undelete =
    .title = Recupera els missatges eliminats seleccionats
toolbar-compact-label = Compacta
toolbar-compact =
    .title = Elimina els missatges suprimits de la carpeta seleccionada
toolbar-add-as-event-label = Afegeix com a cita
toolbar-add-as-event =
    .title = Extreu la informació temporal del missatge i l'afegeix al calendari com a cita
toolbar-add-as-task-label = Afegeix com a tasca
toolbar-add-as-task =
    .title = Extreu la informació temporal del missatge i l'afegeix al calendari com a tasca
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Etiqueta els missatges
toolbar-forward-inline-label = Reenvia
toolbar-forward-inline =
    .title = Reenvia el missatge seleccionat com text en el cos
toolbar-forward-attachment-label = Reenvia com a adjunció
toolbar-forward-attachment =
    .title = Reenvia el missatge seleccionat com adjunció
toolbar-mark-as-label = Marca
toolbar-mark-as =
    .title = Marca els missatges
toolbar-view-picker-label = Visualitza
toolbar-view-picker =
    .title = Personalitza la vista de la carpeta actual
toolbar-address-book-label = Llibreta d'adreces
toolbar-address-book =
    .title = Vés a la llibreta d'adreces
toolbar-chat-label = Xat
toolbar-chat =
    .title = Mostra la pestanya de xat
toolbar-add-ons-and-themes-label = Complements i temes
toolbar-add-ons-and-themes =
    .title = Gestiona els complements
toolbar-calendar-label = Calendari
toolbar-calendar =
    .title = Mostra la pestanya del calendari
toolbar-tasks-label = Tasques
toolbar-tasks =
    .title = Mostra la pestanya de les tasques
toolbar-mail-label = Correu
toolbar-mail =
    .title = Canvia a la pestanya del correu
toolbar-print-label = Imprimeix
toolbar-print =
    .title = Imprimeix aquest missatge
toolbar-quick-filter-bar-label = Filtre ràpid
toolbar-quick-filter-bar =
    .title = Filtra missatges
toolbar-synchronize-label = Sincronitza
toolbar-synchronize =
    .title = Torna a carregar els calendaris i sincronitza els canvis
toolbar-delete-event-label = Suprimeix
toolbar-delete-event =
    .title = Suprimeix les cites o les tasques seleccionades
toolbar-go-to-today-label = Vés a avui
toolbar-go-to-today =
    .title = Vés a avui
toolbar-print-event-label = Imprimeix
toolbar-print-event =
    .title = Imprimeix cites o tasques
toolbar-new-event-label = Cita
toolbar-new-event =
    .title = Crea una cita nova
toolbar-new-task-label = Tasca
toolbar-new-task =
    .title = Crea una tasca nova
toolbar-go-back-label = Enrere
toolbar-go-back =
    .title = Vés enrere un missatge
toolbar-go-forward-label = Endavant
toolbar-go-forward =
    .title = Vés endavant un missatge
toolbar-stop-label = Atura
toolbar-stop =
    .title = Atura la transferència actual
toolbar-throbber-label = Indicador d'activitat
toolbar-throbber =
    .title = Indicador d'activitat
toolbar-create-contact-label = Contacte nou
toolbar-create-contact =
    .title = Crea un contacte nou
toolbar-create-address-book-label = Llibreta d'adreces nova
toolbar-create-address-book =
    .title = Crea una llibreta d'adreces nova
toolbar-create-list-label = Llista nova
toolbar-create-list =
    .title = Crea una llista de correu nova
toolbar-import-contacts-label = Importa
toolbar-import-contacts =
    .title = Importa contactes d'un fitxer

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Afegeix una llibreta d'adreces local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Afegeix una llibreta d'adreces CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Afegeix una llibreta d'adreces LDAP
