# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Показвано име
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Вид
vcard-entry-type-home = Начало
vcard-entry-type-work = Служебен
vcard-entry-type-none = Няма
vcard-entry-type-custom = По избор
vcard-name-header = Име
vcard-n-prefix = Представка
vcard-n-add-prefix =
    .title = Добавяне на представка
vcard-n-firstname = Име
vcard-n-add-firstname =
    .title = Добавяне на име
vcard-n-middlename = Презиме
vcard-n-add-middlename =
    .title = Добавяне на презиме
vcard-n-lastname = Фамилия
vcard-n-add-lastname =
    .title = Добавяне на фамилия
vcard-n-suffix = Наставка
vcard-n-add-suffix =
    .title = Добавяне на наставка
vcard-nickname = Псевдоним
vcard-email-header = Адреси за е-поща
vcard-email-add = Добавяне на адрес за е-поща
vcard-email-label = Адреси за е-поща
vcard-primary-email-label = Стандартно
vcard-url-header = Уебсайтове
vcard-url-add = Добавяне на уебсайт
vcard-url-label = Уебсайт
vcard-tel-header = Телефонни номера
vcard-tel-add = Добавяне на телефонен номер
vcard-tel-label = Телефонен номер
# Or "Mobile"
vcard-entry-type-cell = Мобилен номер
vcard-entry-type-fax = Факс
vcard-entry-type-pager = Пейджър
vcard-tz-header = Часови пояс
vcard-tz-add = Добавяне на часови пояс
vcard-impp2-header = Незабавни съобщения
vcard-impp-add = Добавяне на профил за разговор…
vcard-impp-label = Профил за разговори…
vcard-impp-select = Протокол
vcard-impp-option-other = Друго
vcard-impp-input-label = URI
vcard-impp-input-title = URI за незабавни съобщения
vcard-bday-anniversary-header = Специални дати
vcard-bday-anniversary-add = Добавяне на специална дата
vcard-bday-label = Рожден ден
vcard-anniversary-label = Годишнина
vcard-date-day = Ден
vcard-date-month = Месец
vcard-date-year = Година
vcard-adr-header = Адреси
vcard-adr-add = Добавяне на адрес
vcard-adr-label = Адрес
vcard-adr-delivery-label = Етикет за доставка
vcard-adr-street = Улица
# Or "Locality"
vcard-adr-locality = Град
# Or "Region"
vcard-adr-region = Област/Община:
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Пощенски код:
vcard-adr-country = Държава
vcard-note-header = Бележки
vcard-note-add = Добавяне на бележка
vcard-org-header = Организационни свойства
vcard-org-add = Добавяне на организационни свойства
vcard-org-title = Заглавие
vcard-org-title-input =
    .placeholder = длъжност
    .title = Позиция или месторабота
vcard-org-role = Роля
vcard-org-role-input =
    .placeholder = Длъжност в проекта
    .title = Функция или роля в конкретна ситуация
vcard-org-org = Организация
vcard-org-org-input =
    .placeholder = Име на фирмата
    .title = Име на организацията
vcard-org-org-unit = Отдел
vcard-org-org-unit-input =
    .placeholder = Отрдел
    .title = Отдел
vcard-custom-header = Други данни
vcard-custom-add = Добвяне на други данни
vcard-remove-button-title =
    .title = Премахване
vcard-remove-button = Премахване
