# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = فراغ مرن
toolbar-write-message-label = اكتب
toolbar-write-message =
    .title = أنشئ رسالة جديدة
toolbar-unifinder-label = اعثر على أحداث
toolbar-unifinder =
    .title = بدّل عرض لوحة البحث عن الأحداث
toolbar-folder-location-label = موقع المجلد
toolbar-edit-event-label = حرر
toolbar-edit-event =
    .title = حرّر الحدث أو المهمة المحدّدة
toolbar-get-messages-label = اجلب الرسائل
toolbar-reply-label = رُد
toolbar-reply =
    .title = رُد على الرسالة
toolbar-reply-all-label = رُد على الكل
toolbar-reply-all =
    .title = رُد على المُرسِل وكل المُستلمين
toolbar-reply-to-list-label = رُد على القائمة
toolbar-reply-to-list =
    .title = رُد على القائمة البريدية
toolbar-archive-label = أرشِف
toolbar-archive =
    .title = أرشِف الرسائل المختارة
toolbar-conversation-label = محادثة
toolbar-conversation =
    .title = اعرض المحادثة التي تحتوي الرسالة المختارة
toolbar-previous-unread-label = غير المقروءة السابقة
toolbar-previous-unread =
    .title = الرسالة غير المقروءة السابقة
toolbar-previous-label = السابق
toolbar-previous =
    .title = انتقل للرسالة السابقة
toolbar-next-unread-label = غير المقروءة التالية
toolbar-next-unread =
    .title = الرسالة غير المقروءة التالية
toolbar-next-label = التالية
toolbar-next =
    .title = انتقل للرسالة التالية
toolbar-compact-label = ضغط
toolbar-compact =
    .title = أزِل الرسائل المحذوفة من المجلد المحدد
toolbar-add-as-event-label = أضفها كحدث
toolbar-add-as-event =
    .title = استخرج معلومات التقويم من الرسالة وأضفها إلى تقويمي كحدث
toolbar-add-as-task-label = أضفها كمهمة
toolbar-add-as-task =
    .title = استخرج معلومات التقويم من الرسالة وأضفها إلى تقويمي كمهمة
toolbar-tag-message-label = وسم
toolbar-tag-message =
    .title = سِمْ الرسائل
toolbar-forward-inline-label = مرّر
toolbar-forward-inline =
    .title = مرر الرسالة المحددة ضمن المتن
toolbar-forward-attachment-label = مرِّر مرفقة
toolbar-forward-attachment =
    .title = مرر الرسالة المحددة مرفقة
toolbar-mark-as-label = أشِّر
toolbar-mark-as =
    .title = أشِّر الرسائل
toolbar-address-book =
    .title = دفتر العناوين
toolbar-chat-label = الدردشة
toolbar-chat =
    .title = أظهر لسان الدردشة
toolbar-calendar-label = تقويم
toolbar-calendar =
    .title = انتقل إلى لسان التقويم
toolbar-tasks-label = مهام
toolbar-tasks =
    .title = انتقل إلى لسان المهام
toolbar-print-label = اطبع
toolbar-print =
    .title = اطبع هذه الرسالة
toolbar-synchronize-label = زامِن
toolbar-synchronize =
    .title = أعِد تحميل التقويمات وزامِن التغييرات
toolbar-delete-event-label = احذف
toolbar-delete-event =
    .title = احذف الأحداث أو المهام المحددة
toolbar-go-to-today-label = اذهب الى اليوم
toolbar-go-to-today =
    .title = اذهب الى اليوم
toolbar-print-event-label = اطبع
toolbar-print-event =
    .title = اطبع الأحداث أو المهام
toolbar-new-event-label = حدث
toolbar-new-event =
    .title = أنشئ حدثا جديدا
toolbar-new-task-label = مهمَّة
toolbar-new-task =
    .title = أنشئ مهمة جديدة
toolbar-go-back-label = إلى الخلف
toolbar-go-back =
    .title = ارجع رسالة واحدة
toolbar-go-forward-label = إلى الأمام
toolbar-go-forward =
    .title = تقدم رسالة واحدة
toolbar-stop-label = قف
toolbar-stop =
    .title = أوقف النقل الحالي
toolbar-throbber-label = مبيّن النشاط
toolbar-throbber =
    .title = مبيّن النشاط
