# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# readFromXML.js
no_emailProvider.error = Die opstellingslêer se XML bevat nie 'n e-posrekeningopstelling nie.
outgoing_not_smtp.error = Die uitgaande bediener moet 'n SMTP-tipe wees
# verifyConfig.js
cannot_login.error = Kon nie by die bediener aanmeld nie. Waarskynlik verkeerde opstelling, gebruikernaam of wagwoord.
# guessConfig.js
cannot_find_server.error = Kon nie bediener vind nie
