# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Адаптивен интервал
toolbar-write-message-label = Писане
toolbar-write-message =
    .title = Създаване на ново писмо
toolbar-unifinder-label = Намиране на събития
toolbar-unifinder =
    .title = Превключване на панела за търсене на събития
toolbar-folder-location-label = Местоположение на папката
toolbar-edit-event-label = Редактиране
toolbar-edit-event =
    .title = Редактиране на избраното събитие или задача
toolbar-get-messages-label = Изтегляне на писма
toolbar-reply-label = Отговор
toolbar-reply =
    .title = Отговор на писмото
toolbar-reply-all-label = Отговор до всички
toolbar-reply-all =
    .title = Отговор до подателя и всички получатели
toolbar-reply-to-list-label = Отговор до списък
toolbar-reply-to-list =
    .title = Отговор до пощенски списък
toolbar-archive-label = Архивиране
toolbar-archive =
    .title = Архивиране на избраните съобщения
toolbar-conversation-label = Разговор
toolbar-conversation =
    .title = Показване на разговора на избраното съобщение
toolbar-previous-unread-label = Предишно непрочетено
toolbar-previous-unread =
    .title = Назад към предишното непрочетено писмо
toolbar-previous-label = Предишно
toolbar-previous =
    .title = Назад към предишното непрочетено писмо
toolbar-next-unread-label = Следващо непрочетено
toolbar-next-unread =
    .title = Напред към следващото непрочетено писмо
toolbar-next-label = Следващо
toolbar-next =
    .title = Напред към следващото непрочетено писмо
toolbar-compact-label = Уплътняване
toolbar-compact =
    .title = Премахване на изтритите писма от избраната папка
toolbar-add-as-event-label = Добавяне на събитие
toolbar-add-as-event =
    .title = Извличане на календарната информация от съобщението и добавянето ѝ към вашия календар като събитие
toolbar-add-as-task-label = Добавяне на задача
toolbar-add-as-task =
    .title = Извличане на календарната информация от съобщението и добавянето ѝ към вашия календар като задача
toolbar-tag-message-label = Етикет
toolbar-tag-message =
    .title = Поставяне на етикети
toolbar-forward-inline-label = Препращане
toolbar-forward-inline =
    .title = Препращане на избраното съобщение като вложен текст
toolbar-forward-attachment-label = Препращане като притурки
toolbar-forward-attachment =
    .title = Препращане на избраното съобщение като притурка
toolbar-mark-as-label = Отбелязване
toolbar-mark-as =
    .title = Отбелязване на писмата
toolbar-address-book =
    .title = Отваряне на адресника
toolbar-chat-label = Разговори
toolbar-chat =
    .title = Показване на раздела за разговори
toolbar-calendar-label = Календар
toolbar-calendar =
    .title = Превключване към раздела с календара
toolbar-tasks-label = Задачи
toolbar-tasks =
    .title = Превключване към раздела със задачи
toolbar-print-label = Отпечатване
toolbar-print =
    .title = Отпечатване на писмото
toolbar-synchronize-label = Синхронизиране
toolbar-synchronize =
    .title = Презареждане на календарите и синхронизиране на промените
toolbar-delete-event-label = Изтриване
toolbar-delete-event =
    .title = Изтриване на избраните събития или задачи
toolbar-go-to-today-label = Отваряне на днешния ден
toolbar-go-to-today =
    .title = Отваряне на днешния ден
toolbar-print-event-label = Отпечатване
toolbar-print-event =
    .title = Отпечатване на събития или задачи
toolbar-new-event-label = Събитие
toolbar-new-event =
    .title = Създаване на ново събитие
toolbar-new-task-label = Задача
toolbar-new-task =
    .title = Създаване на нова задача
toolbar-go-back-label = Назад
toolbar-go-back =
    .title = Назад едно писмо
toolbar-go-forward-label = Препращане
toolbar-go-forward =
    .title = Напред едно писмо
toolbar-stop-label = Стоп
toolbar-stop =
    .title = Прекратяване на текущия трансфер
