# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Інтервал змінної довжини
search-bar-label = Пошук
toolbar-write-message-label = Створити
toolbar-write-message =
    .title = Написати повідомлення
toolbar-move-to-label = Перемістити
toolbar-move-to =
    .title = Перемістити вибране повідомлення
toolbar-unifinder-label = Знайти події
toolbar-unifinder =
    .title = Перемкнути панель знаходження подій
toolbar-folder-location-label = Знаходження теки
toolbar-folder-location =
    .title = Перейти до теки
toolbar-edit-event-label = Змінити
toolbar-edit-event =
    .title = Змінити вибрану подію чи завдання
toolbar-get-messages-label = Отримати
toolbar-get-messages =
    .title = Отримати нові повідомлення для всіх облікових записів
toolbar-reply-label = Відповісти
toolbar-reply =
    .title = Відповісти на повідомлення
toolbar-reply-all-label = Відповісти всім
toolbar-reply-all =
    .title = Відповісти відправнику та всім адресатам
toolbar-reply-to-list-label = Відповісти списку
toolbar-reply-to-list =
    .title = Відповісти списку розсилки
toolbar-redirect-label = Переслати
toolbar-redirect =
    .title = Переслати вибране повідомлення
toolbar-archive-label = Архівувати
toolbar-archive =
    .title = Архівувати вибрані повідомлення
toolbar-conversation-label = Розмова
toolbar-conversation =
    .title = Показати розмову для обраного повідомлення
toolbar-previous-unread-label = Попередній нечитаний
toolbar-previous-unread =
    .title = Перейти до попереднього непрочитаного повідомлення
toolbar-previous-label = Попередній
toolbar-previous =
    .title = Перейти до попереднього повідомлення
toolbar-next-unread-label = Наступний нечитаний
toolbar-next-unread =
    .title = Перейти до наступного непрочитаного повідомлення
toolbar-next-label = Наступний
toolbar-next =
    .title = Перейти до наступного повідомлення
toolbar-junk-label = Небажане
toolbar-junk =
    .title = Позначте вибрані повідомлення небажаними
toolbar-delete-label = Видалити
toolbar-delete-title =
    .title = Видалити вибрані повідомлення
toolbar-undelete-label = Відновити
toolbar-undelete =
    .title = Відновити виділені повідомлення
toolbar-compact-label = Стиснути
toolbar-compact =
    .title = Вилучити видалені повідомлення з вибраної теки
toolbar-add-as-event-label = Додати як подію
toolbar-add-as-event =
    .title = Витягнути інформацію календаря з повідомлення й додати її в свій календар як подію
toolbar-add-as-task-label = Додати як завдання
toolbar-add-as-task =
    .title = Витягнути інформацію календаря з повідомлення й додати її в свій календар як завдання
toolbar-tag-message-label = Мітка
toolbar-tag-message =
    .title = Позначити повідомлення міткою
toolbar-forward-inline-label = Переслати
toolbar-forward-inline =
    .title = Переслати вибране повідомлення у вигляді вбудованого тексту
toolbar-forward-attachment-label = Переслати у вигляді вкладення
toolbar-forward-attachment =
    .title = Переслати вибране повідомлення у вигляді вкладення
toolbar-mark-as-label = Позначити
toolbar-mark-as =
    .title = Позначити повідомлення
toolbar-view-picker-label = Вигляд
toolbar-view-picker =
    .title = Налаштувати вигляд поточної теки
toolbar-address-book-label = Адресна книга
toolbar-address-book =
    .title = Відкрити адресну книгу
toolbar-chat-label = Чат
toolbar-chat =
    .title = Показати вкладку чату
toolbar-add-ons-and-themes-label = Додатки й теми
toolbar-add-ons-and-themes =
    .title = Керувати додатками
toolbar-calendar-label = Календар
toolbar-calendar =
    .title = Перемкнутись на вкладку календаря
toolbar-tasks-label = Завдання
toolbar-tasks =
    .title = Перемкнутись на вкладку завдань
toolbar-mail-label = Пошта
toolbar-mail =
    .title = Перемкнутись на вкладку пошти
toolbar-print-label = Друк
toolbar-print =
    .title = Надрукувати це повідомлення
toolbar-quick-filter-bar-label = Швидкий фільтр
toolbar-quick-filter-bar =
    .title = Фільтр повідомлень
toolbar-synchronize-label = Синхронізувати
toolbar-synchronize =
    .title = Перезавантажити календарі та синхронізувати зміни
toolbar-delete-event-label = Видалити
toolbar-delete-event =
    .title = Видалити вибрані події чи завдання
toolbar-go-to-today-label = Перейти на сьогодні
toolbar-go-to-today =
    .title = Перейти на сьогодні
toolbar-print-event-label = Друкувати
toolbar-print-event =
    .title = Друк подій чи завдань
toolbar-new-event-label = Подія
toolbar-new-event =
    .title = Створити нову подію
toolbar-new-task-label = Завдання
toolbar-new-task =
    .title = Створити нове завдання
toolbar-go-back-label = Назад
toolbar-go-back =
    .title = Назад на одне повідомлення
toolbar-go-forward-label = Вперед
toolbar-go-forward =
    .title = Вперед на одне повідомлення
toolbar-stop-label = Стоп
toolbar-stop =
    .title = Зупинити поточну передачу даних
toolbar-throbber-label = Індикатор активності
toolbar-throbber =
    .title = Індикатор активності
toolbar-create-contact-label = Новий контакт
toolbar-create-contact =
    .title = Створити новий контакт
toolbar-create-address-book-label = Нова адресна книга
toolbar-create-address-book =
    .title = Створити нову адресну книгу
toolbar-create-list-label = Новий список
toolbar-create-list =
    .title = Створити новий список розсилки
toolbar-import-contacts-label = Імпорт
toolbar-import-contacts =
    .title = Імпортувати контакти з файлу

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Додати локальну адресну книгу
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Додати адресну книгу CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Додати адресну книгу LDAP
