# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Seleccionar todo
select-none-calendars = No seleccionar ninguno
calendar-creation-wizard-title = Crear nuevo calendario
calendar-creation-initial-description = Su calendario puede guardarse en su ordenador o en un servidor, permitiendo así acceder a él remotamente o compartirlo con sus amigos o compañeros de trabajo.
calendar-creation-initial-computer =
    .label = En mi ordenador
calendar-creation-initial-network =
    .label = En la red
calendar-creation-username =
    .value = Nombre de usuario:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Buscar calendarios
    .buttonaccesskeyaccept = B
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Suscribirse
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-type =
    .value = Tipo de calendario:
calendar-creation-location =
    .value = Dirección:
calendar-creation-location-placeholder =
    .placeholder = URL o nombre del servidor del calendario
    .default-placeholder = URL o nombre del servidor del calendario
calendar-creation-network-nocredentials =
    .label = Esta dirección no requiere credenciales
calendar-creation-network-loading = Espere mientras se buscan sus calendarios.
calendar-creation-network-notfound = No se han podido encontrar calendarios en esta dirección. Revise su configuración.
calendar-creation-network-authfail = Las credenciales que ha introducido no han sido aceptadas. Revise su configuración.
calendar-creation-network-certerror = No se han encontrado calendarios en esta dirección debido a un problema con el certificado.
calendar-creation-network-subscribe-single = Seleccione los calendarios a los que quiere suscribirse.
calendar-creation-network-subscribe-multiple = Hay disponibles varios tipos de calendarios en esta dirección. Seleccione el tipo de calendario y luego marque los calendarios a los que quiere suscribirse.
