# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Растегљив простор
search-bar-label = Претрага
toolbar-write-message-label = Пиши
toolbar-write-message =
    .title = Направи нову поруку
toolbar-unifinder-label = Нађи догађаје
toolbar-unifinder =
    .title = Укључи или искључи површ за проналажење догађаја
toolbar-folder-location-label = Путања фасцикле
toolbar-edit-event-label = Уреди
toolbar-edit-event =
    .title = Уреди изабрани догађај или задатак
toolbar-get-messages-label = Добави поруке
toolbar-get-messages =
    .title = Добави нове поруке за све налоге
toolbar-reply-label = Одговори
toolbar-reply =
    .title = Одговори на поруку
toolbar-reply-all-label = Одговори свима
toolbar-reply-all =
    .title = Одговори пошиљаоцу и свим примаоцима
toolbar-reply-to-list-label = Одговори на листу
toolbar-reply-to-list =
    .title = Одговори дописној листи
toolbar-redirect-label = Преусмерење
toolbar-redirect =
    .title = Преусмери изабрану поруку
toolbar-archive-label = Архивирај
toolbar-archive =
    .title = Архивирај изабране поруке
toolbar-conversation-label = Разговор
toolbar-conversation =
    .title = Прикажи разговор изабране поруке
toolbar-previous-unread-label = Претходна непрочитана
toolbar-previous-unread =
    .title = Иди на претходну непрочитану поруку
toolbar-previous-label = Претходна
toolbar-previous =
    .title = Иди на претходну поруку
toolbar-next-unread-label = Следећа непрочитана
toolbar-next-unread =
    .title = Иди на следећу непрочитану поруку
toolbar-next-label = Следећа
toolbar-next =
    .title = Иди на следећу поруку
toolbar-compact-label = Сажми
toolbar-compact =
    .title = Уклони обрисане поруке из изабране фасцикле
toolbar-add-as-event-label = Додај као догађај
toolbar-add-as-event =
    .title = Извуците календарске податке из поруке и додајте их као догађај у ваш календар
toolbar-add-as-task-label = Додај као задатак
toolbar-add-as-task =
    .title = Извуците календарске податке из поруке и додајте их као задатак у ваш календар
toolbar-tag-message-label = Означи
toolbar-tag-message =
    .title = Означи поруке
toolbar-forward-inline-label = Проследи
toolbar-forward-inline =
    .title = Проследи изабрану поруку као текст унутар друге поруке
toolbar-forward-attachment-label = Проследи као прилог
toolbar-forward-attachment =
    .title = Проследи изабрану поруку као прилог
toolbar-mark-as-label = Обележи
toolbar-mark-as =
    .title = Обележи поруке
toolbar-address-book =
    .title = Иди у именик
toolbar-chat-label = Ћаскај
toolbar-chat =
    .title = Прикажи језичак ћаскања
toolbar-add-ons-and-themes-label = Додаци и теме
toolbar-add-ons-and-themes =
    .title = Управљајте вашим додацима
toolbar-calendar-label = Календар
toolbar-calendar =
    .title = Пребаци се на календарски језичак
toolbar-tasks-label = Задаци
toolbar-tasks =
    .title = Пребаци се на језичак са задацима
toolbar-print-label = Одштампај
toolbar-print =
    .title = Одштампај ову поруку
toolbar-quick-filter-bar-label = Брзо филтрирање
toolbar-quick-filter-bar =
    .title = Филтрира поруке
toolbar-synchronize-label = Синхронизуј
toolbar-synchronize =
    .title = Поново учитај календаре и синхронизуј измене
toolbar-delete-event-label = Обриши
toolbar-delete-event =
    .title = Обриши изабране догађаје или задатке
toolbar-go-to-today-label = Иди на данас
toolbar-go-to-today =
    .title = Иди на данас
toolbar-print-event-label = Штампај
toolbar-print-event =
    .title = Штампај догађаје или задатке
toolbar-new-event-label = Догађај
toolbar-new-event =
    .title = Направи нови догађај
toolbar-new-task-label = Задатак
toolbar-new-task =
    .title = Направи нови задатак
