# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Որոնում…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 գտնված համընկնում;#1 գտնված համընկումներ
noMatchesFound = Չի գտնվել
labelForStopButton = Կանգնեցնել
labelForSearchButton = Որոնում
labelForStopButton.accesskey = Կ
labelForSearchButton.accesskey = Փ
moreButtonTooltipText = Ավելացնել նոր կանոն
lessButtonTooltipText = Ջնջել կանոնը
