# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentar
calendar-item-summary-title = Naslov:
calendar-item-summary-calendar = Kalendar:
calendar-item-summary-task-start = Datum početka:
calendar-item-summary-event-start = Datum početka:
calendar-item-summary-task-due = Dospjeće:
calendar-item-summary-event-end = Datum završetka:
calendar-item-summary-repeat = Ponavljanje:
calendar-item-summary-location = Lokacija:
calendar-item-summary-category = Kategorija:
calendar-item-summary-organizer = Organizator:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Podsjetnik:
calendar-item-summary-attachments = Privici:
calendar-item-summary-status-tentative = Privremeno
calendar-item-summary-status-confirmed = Potvrđeno
calendar-item-summary-event-status-cancelled = Otkazano
calendar-item-summary-todo-status-cancelled = Otkazano
calendar-item-summary-status-needs-action = Potrebno djelovati
calendar-item-summary-status-in-process = U tijeku
calendar-item-summary-status-completed = Završeno na
calendar-item-summary-reminder-none =
    .label = Bez podsjetnika
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuta prije
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuta prije
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuta prije
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuta prije
calendar-item-summary-reminder-1-hour-before =
    .label = 1 sat prije
calendar-item-summary-reminder-2-hours-before =
    .label = 2 sata prije
calendar-item-summary-reminder-12-hours-before =
    .label = 12 sati prije
calendar-item-summary-reminder-1-day-before =
    .label = 1 dan prije
calendar-item-summary-reminder-2-days-before =
    .label = 2 dana prije
calendar-item-summary-reminder-1-week-before =
    .label = 1 tjedan prije
calendar-item-summary-reminder-custom =
    .label = Prilagodi…
calendar-item-summary-reminder-multiple =
    .value = Višestruki podsjetnici…
calendar-item-summary-general =
    .value = Općenito
calendar-item-summary-attendees =
    .value = Sudionici
calendar-item-summary-description =
    .value = Opis
calendar-item-summary-link =
    .value = Povezana poveznica
