# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Označi sve
select-none-calendars = Nemoj odabrati ništa
calendar-creation-wizard-title = Stvori novi kalendar
calendar-creation-initial-description = Kalendar može biti spremljen na vašem računalu ili na poslužitelju kako biste mu mogli pristupiti od bilo kuda ili ga dijeliti sa svojim prijateljima ili suradnicima.
calendar-creation-initial-computer =
    .label = Na mom računalu
calendar-creation-initial-network =
    .label = Na mreži
calendar-creation-username =
    .value = Korisničko ime:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Stvori kalendar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Natrag
    .buttonaccesskeyextra2 = N
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Stvori kalendar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Natrag
    .buttonaccesskeyextra2 = N
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Pronađi kalendare
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Natrag
    .buttonaccesskeyextra2 = N
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Pretplati se
    .buttonaccesskeyaccept = s
    .buttonlabelextra2 = Natrag
    .buttonaccesskeyextra2 = N
calendar-creation-type =
    .value = Tip kalendara:
calendar-creation-location =
    .value = Lokacija:
calendar-creation-location-placeholder =
    .placeholder = URL ili adresa kalendarskog poslužitelja
    .default-placeholder = URL ili adresa kalendarskog poslužitelja
calendar-creation-network-nocredentials =
    .label = Ova lokacija ne zahtjeva prijavu
calendar-creation-network-loading = Pričekajte dok otkrivamo dostupne kalendare.
calendar-creation-network-notfound = Nije moguće pronaći kalendare na ovoj lokaciji. Provjerite postavke.
calendar-creation-network-authfail = Podaci za prijavu koje ste unijeli nisu prihvaćeni. Provjerite postavke.
calendar-creation-network-certerror = Nije moguće pronaći kalendare na ovoj lokaciji zbog problema s certifikatom.
calendar-creation-network-subscribe-single = Odaberite kalendare na koje se želite pretplatiti.
calendar-creation-network-subscribe-multiple = Više tipova kalendara je dostupno na ovoj lokaciji. Odaberite tip kalendara i onda označite kalendare na koje se želite pretplatiti.
