# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = je ponavljajući događaj
header-isrepeating-task =
    .label = je ponavljajući zadatak
header-containsrepeating-event =
    .label = sadrži ponavljajuće događaje
header-containsrepeating-task =
    .label = sadrži ponavljajuće zadatke
header-containsrepeating-mixed =
    .label = sadrži ponavljajuće stavke različitog tipa
windowtitle-event-copy = Kopiraj ponavljajuće događaje
windowtitle-task-copy = Kopiraj ponavljajuće zadatke
windowtitle-mixed-copy = Kopiraj ponavljajuće stavke
windowtitle-event-cut = Izreži ponavljajuće događaje
windowtitle-task-cut = Izreži ponavljajuće zadatke
windowtitle-mixed-cut = Izreži ponavljajuće stavke
windowtitle-event-delete = Obriši ponavljajući događaj
windowtitle-task-delete = Obriši ponavljajući zadatak
windowtitle-mixed-delete = Obriši ponavljajuće stavke
windowtitle-event-edit = Uredi ponavljajući događaj
windowtitle-task-edit = Uredi ponavljajući zadatak
windowtitle-mixed-edit = Uredi ponavljajuće stavke
windowtitle-multipleitems =
    .value = Odabrane stavke
button-single-occurrence-copy =
    .label = Kopiraj samo ovaj događaj
    .accesskey = p
button-single-occurrence-cut =
    .label = Izreži samo ovaj događaj
    .accesskey = p
button-single-occurrence-delete =
    .label = Obriši samo ovaj događaj
    .accesskey = p
button-single-occurrence-edit =
    .label = Uredi samo ovaj događaj
    .accesskey = p
button-multiple-occurrence-copy =
    .label = Kopiraj samo odabrana ponavljanja
    .accesskey = p
button-multiple-occurrence-cut =
    .label = Izreži samo odabrana ponavljanja
    .accesskey = p
button-multiple-occurrence-delete =
    .label = Obriši samo odabrana ponavljanja
    .accesskey = p
button-multiple-occurrence-edit =
    .label = Uredi samo odabrana ponavljanja
    .accesskey = p
button-single-allfollowing-copy =
    .label = Kopiraj ovo i sva buduća ponavljanja
    .accesskey = b
button-single-allfollowing-cut =
    .label = Izreži ovo i sva buduća ponavljanja
    .accesskey = b
button-single-allfollowing-delete =
    .label = Obriši ovo i sva buduća ponavljanja
    .accesskey = b
button-single-allfollowing-edit =
    .label = Uredi ovo i sva buduća ponavljanja
    .accesskey = b
button-multiple-allfollowing-copy =
    .label = Kopiraj odabrana i sva buduća ponavljanja
    .accesskey = b
button-multiple-allfollowing-cut =
    .label = Izreži odabrana i sva buduća ponavljanja
    .accesskey = b
button-multiple-allfollowing-delete =
    .label = Obriši odabrana i sva buduća ponavljanja
    .accesskey = b
button-multiple-allfollowing-edit =
    .label = Uredi odabrana i sva buduća ponavljanja
    .accesskey = b
button-single-parent-copy =
    .label = Kopiraj sva ponavljanja
    .accesskey = s
button-single-parent-cut =
    .label = Izreži sva ponavljanja
    .accesskey = s
button-single-parent-delete =
    .label = Obriši sva ponavljanja
    .accesskey = s
button-single-parent-edit =
    .label = Uredi sva ponavljanja
    .accesskey = s
button-multiple-parent-copy =
    .label = Kopiraj sva ponavljanja odabranih stavki
    .accesskey = s
button-multiple-parent-cut =
    .label = Izreži sva ponavljanja odabranih stavki
    .accesskey = s
button-multiple-parent-delete =
    .label = Obriši sva ponavljanja odabranih stavki
    .accesskey = s
button-multiple-parent-edit =
    .label = Uredi sva ponavljanja odabranih stavki
    .accesskey = s
buttons-single-occurrence-copy =
    .label = Kopiraj samo ovaj događaj
buttons-single-occurrence-cut =
    .label = Izreži samo ovaj događaj
buttons-single-occurrence-delete =
    .label = Obriši samo ovaj događaj
buttons-single-occurrence-edit =
    .label = Uredi samo ovaj događaj
buttons-multiple-occurrence-copy =
    .label = Kopiraj samo odabrana ponavljanja
buttons-multiple-occurrence-cut =
    .label = Izreži samo odabrana ponavljanja
buttons-multiple-occurrence-delete =
    .label = Obriši samo odabrana ponavljanja
buttons-multiple-occurrence-edit =
    .label = Uredi samo odabrana ponavljanja
buttons-single-allfollowing-copy =
    .label = Kopiraj ovo i sva buduća ponavljanja
buttons-single-allfollowing-cut =
    .label = Izreži ovo i sva buduća ponavljanja
buttons-single-allfollowing-delete =
    .label = Obriši ovo i sva buduća ponavljanja
buttons-single-allfollowing-edit =
    .label = Uredi ovo i sva buduća ponavljanja
buttons-multiple-allfollowing-copy =
    .label = Kopiraj odabrana i sva buduća ponavljanja
buttons-multiple-allfollowing-cut =
    .label = Izreži odabrana i sva buduća ponavljanja
buttons-multiple-allfollowing-delete =
    .label = Obriši odabrana i sva buduća ponavljanja
buttons-multiple-allfollowing-edit =
    .label = Uredi odabrana i sva buduća ponavljanja
buttons-single-parent-copy =
    .label = Kopiraj sva ponavljanja
buttons-single-parent-cut =
    .label = Izreži sva ponavljanja
buttons-single-parent-delete =
    .label = Obriši sva ponavljanja
buttons-single-parent-edit =
    .label = Uredi sva ponavljanja
buttons-multiple-parent-copy =
    .label = Kopiraj sva ponavljanja odabranih stavki
buttons-multiple-parent-cut =
    .label = Izreži sva ponavljanja odabranih stavki
buttons-multiple-parent-delete =
    .label = Obriši sva ponavljanja odabranih stavki
buttons-multiple-parent-edit =
    .label = Uredi sva ponavljanja odabranih stavki
