# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = қайталанатын оқиға болып тұр
header-isrepeating-task =
    .label = қайталанатын тапсырма болып тұр
header-containsrepeating-event =
    .label = қайталанатын оқиғалары бар
header-containsrepeating-task =
    .label = қайталанатын тапсырмалары бар
header-containsrepeating-mixed =
    .label = әр түрлі, қайталанатын элементтерді сақтайды
windowtitle-event-copy = Қайталанатын оқиғаны көшіріп алу
windowtitle-task-copy = Қайталанатын тапсырманы көшіріп алу
windowtitle-mixed-copy = Қайталанатын элементтерді көшіріп алу
windowtitle-event-cut = Қайталанатын оқиғаны қиып алу
windowtitle-task-cut = Қайталанатын тапсырманы қиып алу
windowtitle-mixed-cut = Қайталанатын элементтерді қиып алу
windowtitle-event-delete = Қайталанатын оқиғаны өшіру
windowtitle-task-delete = Қайталанатын тапсырманы өшіру
windowtitle-mixed-delete = Қайталанатын элементтерді өшіру
windowtitle-event-edit = Қайталанатын оқиғаны түзету
windowtitle-task-edit = Қайталанатын тапсырманы түзету
windowtitle-mixed-edit = Қайталанатын элементтерді түзету
windowtitle-multipleitems =
    .value = Таңдалған элементтер
button-single-occurrence-copy =
    .label = Тек бұл қайталануды көшіріп алу
    .accesskey = т
button-single-occurrence-cut =
    .label = Тек бұл қайталануды қиып алу
    .accesskey = т
button-single-occurrence-delete =
    .label = Тек бұл қайталануды өшіру
    .accesskey = т
button-single-occurrence-edit =
    .label = Тек бұл қайталануды түзету
    .accesskey = т
button-multiple-occurrence-copy =
    .label = Тек таңдалған қайталануларды көшіріп алу
    .accesskey = т
button-multiple-occurrence-cut =
    .label = Тек таңдалған қайталануларды қиып алу
    .accesskey = т
button-multiple-occurrence-delete =
    .label = Тек таңдалған қайталануларды өшіру
    .accesskey = т
button-multiple-occurrence-edit =
    .label = Тек таңдалған қайталануларды түзету
    .accesskey = т
button-single-allfollowing-copy =
    .label = Бұл және барлық болашақ қайталануларын көшіріп алу
    .accesskey = f
button-single-allfollowing-cut =
    .label = Бұл және барлық болашақ қайталануларын қиып алу
    .accesskey = f
button-single-allfollowing-delete =
    .label = Бұл және барлық болашақ қайталануларын өшіру
    .accesskey = f
button-single-allfollowing-edit =
    .label = Бұл және барлық болашақ қайталануларын түзету
    .accesskey = f
button-multiple-allfollowing-copy =
    .label = Таңдалған және барлық болашақ қайталануларын көшіріп алу
    .accesskey = f
button-multiple-allfollowing-cut =
    .label = Таңдалған және барлық болашақ қайталануларын қиып алу
    .accesskey = f
button-multiple-allfollowing-delete =
    .label = Таңдалған және барлық болашақ қайталануларын өшіру
    .accesskey = f
button-multiple-allfollowing-edit =
    .label = Таңдалған және барлық болашақ қайталануларын түзету
    .accesskey = f
button-single-parent-copy =
    .label = Барлық қайталануларын көшіріп алу
    .accesskey = а
button-single-parent-cut =
    .label = Барлық қайталануларын қиып алу
    .accesskey = а
button-single-parent-delete =
    .label = Барлық қайталануларын өшіру
    .accesskey = а
button-single-parent-edit =
    .label = Барлық қайталануларын түзету
    .accesskey = а
button-multiple-parent-copy =
    .label = Таңдалған элементтердің барлық қайталануларын көшіріп алу
    .accesskey = а
button-multiple-parent-cut =
    .label = Таңдалған элементтердің барлық қайталануларын қиып алу
    .accesskey = а
button-multiple-parent-delete =
    .label = Таңдалған элементтердің барлық қайталануларын өшіру
    .accesskey = а
button-multiple-parent-edit =
    .label = Таңдалған элементтердің барлық қайталануларын түзету
    .accesskey = а
buttons-single-occurrence-copy =
    .label = Тек бұл қайталануды көшіріп алу
buttons-single-occurrence-cut =
    .label = Тек бұл қайталануды қиып алу
buttons-single-occurrence-delete =
    .label = Тек бұл қайталануды өшіру
buttons-single-occurrence-edit =
    .label = Тек бұл қайталануды түзету
buttons-multiple-occurrence-copy =
    .label = Тек таңдалған қайталануларды көшіріп алу
buttons-multiple-occurrence-cut =
    .label = Тек таңдалған қайталануларды қиып алу
buttons-multiple-occurrence-delete =
    .label = Тек таңдалған қайталануларды өшіру
buttons-multiple-occurrence-edit =
    .label = Тек таңдалған қайталануларды түзету
buttons-single-allfollowing-copy =
    .label = Бұл және барлық болашақ қайталануларын көшіріп алу
buttons-single-allfollowing-cut =
    .label = Бұл және барлық болашақ қайталануларын қиып алу
buttons-single-allfollowing-delete =
    .label = Бұл және барлық болашақ қайталануларын өшіру
buttons-single-allfollowing-edit =
    .label = Бұл және барлық болашақ қайталануларын түзету
buttons-multiple-allfollowing-copy =
    .label = Таңдалған және барлық болашақ қайталануларын көшіріп алу
buttons-multiple-allfollowing-cut =
    .label = Таңдалған және барлық болашақ қайталануларын қиып алу
buttons-multiple-allfollowing-delete =
    .label = Таңдалған және барлық болашақ қайталануларын өшіру
buttons-multiple-allfollowing-edit =
    .label = Таңдалған және барлық болашақ қайталануларын түзету
buttons-single-parent-copy =
    .label = Барлық қайталануларын көшіріп алу
buttons-single-parent-cut =
    .label = Барлық қайталануларын қиып алу
buttons-single-parent-delete =
    .label = Барлық қайталануларын өшіру
buttons-single-parent-edit =
    .label = Барлық қайталануларын түзету
buttons-multiple-parent-copy =
    .label = Таңдалған элементтердің барлық қайталануларын көшіріп алу
buttons-multiple-parent-cut =
    .label = Таңдалған элементтердің барлық қайталануларын қиып алу
buttons-multiple-parent-delete =
    .label = Таңдалған элементтердің барлық қайталануларын өшіру
buttons-multiple-parent-edit =
    .label = Таңдалған элементтердің барлық қайталануларын түзету
