# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Түсіндірме
calendar-item-summary-title = Тақырыбы:
calendar-item-summary-calendar = Күнтізбе:
calendar-item-summary-task-start = Бастапқы күн:
calendar-item-summary-event-start = Бастапқы күн:
calendar-item-summary-task-due = Бітіру күні:
calendar-item-summary-event-end = Аяқталу күні:
calendar-item-summary-repeat = Қайталау:
calendar-item-summary-location = Орналасуы:
calendar-item-summary-category = Санаты:
calendar-item-summary-organizer = Ұйымдастырушы:
calendar-item-summary-status = Қалып-күйі:
calendar-item-summary-reminder = Еске салу:
calendar-item-summary-attachments = Салынымдар:
calendar-item-summary-status-tentative = Мүмкін деп
calendar-item-summary-status-confirmed = Расталған
calendar-item-summary-event-status-cancelled = Бас тартылған
calendar-item-summary-todo-status-cancelled = Бас тартылған
calendar-item-summary-status-needs-action = Әрекет қажет етіледі
calendar-item-summary-status-in-process = Орындалуда
calendar-item-summary-status-completed = Аяқталған уақыты
calendar-item-summary-reminder-none =
    .label = Еске салу жоқ
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 минут бұрын
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 минут бұрын
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 минут дейін
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 минут бұрын
calendar-item-summary-reminder-1-hour-before =
    .label = 1 сағат бұрын
calendar-item-summary-reminder-2-hours-before =
    .label = 2 сағат бұрын
calendar-item-summary-reminder-12-hours-before =
    .label = 12 сағат бұрын
calendar-item-summary-reminder-1-day-before =
    .label = 1 күн бұрын
calendar-item-summary-reminder-2-days-before =
    .label = 2 күн бұрын
calendar-item-summary-reminder-1-week-before =
    .label = 1 апта бұрын
calendar-item-summary-reminder-custom =
    .label = Таңдауыңызша…
calendar-item-summary-reminder-multiple =
    .value = Бірнеше еске салулар…
calendar-item-summary-general =
    .value = Жалпы
calendar-item-summary-attendees =
    .value = Қатысушылар
calendar-item-summary-description =
    .value = Анықтамасы
calendar-item-summary-link =
    .value = Қатысты сілтеме
