# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Po kërkohet…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = U gjet #1 përputhje;U gjetën #1 përputhje
noMatchesFound = S’u gjetën përputhje
labelForStopButton = Ndale
labelForSearchButton = Kërko
labelForStopButton.accesskey = N
labelForSearchButton.accesskey = K
moreButtonTooltipText = Shtoni rregull të ri
lessButtonTooltipText = Hiqeni këtë rregull
