# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Birtingarnafn
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tegund
vcard-entry-type-home = Heima
vcard-entry-type-work = Vinna
vcard-entry-type-none = Ekkert
vcard-entry-type-custom = Sérsniðið
vcard-name-header = Nafn
vcard-n-prefix = Forskeyti
vcard-n-add-prefix =
    .title = Bæta við forskeyti
vcard-n-firstname = Skírnarnafn
vcard-n-add-firstname =
    .title = Bæta við skírnarnafni
vcard-n-middlename = Millinafn
vcard-n-add-middlename =
    .title = Bæta við millinafni
vcard-n-lastname = Eftirnafn
vcard-n-add-lastname =
    .title = Bæta við eftirnafni
vcard-n-suffix = Viðskeyti
vcard-n-add-suffix =
    .title = Bæta við viðskeyti
vcard-nickname = Gælunafn
vcard-email-header = Tölvupóstföng
vcard-email-add = Bæta við tölvupóstfangi
vcard-email-label = Tölvupóstfang
vcard-primary-email-label = Sjálfgefið
vcard-url-header = Vefsvæði
vcard-url-add = Bæta við vefsvæði
vcard-url-label = Vefsvæði
vcard-tel-header = Símanúmer
vcard-tel-add = Bæta við símanúmeri
vcard-tel-label = Símanúmer
# Or "Mobile"
vcard-entry-type-cell = Farsími
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Símboði
vcard-tz-header = Tímabelti
vcard-tz-add = Bæta við tímabelti
vcard-impp2-header = Snarskilaboð
vcard-impp-add = Bæta við spjallreikningi
vcard-impp-label = Spjallreikningur
vcard-impp-select = Samskiptamáti
vcard-impp-option-other = Annað
vcard-impp-input-label = URI-slóð
vcard-impp-input-title = URI-slóð fyrir snarskilaboð
vcard-bday-anniversary-header = Sérstakar dagsetningar
vcard-bday-anniversary-add = Bæta við sérstakri dagsetningu
vcard-bday-label = Fæðingardagur
vcard-anniversary-label = Afmæli
vcard-date-day = Dagur
vcard-date-month = Mánuður
vcard-date-year = Ár
vcard-adr-header = Póstföng
vcard-adr-add = Bæta við póstfangi
vcard-adr-label = Póstfang
vcard-adr-delivery-label = Afhendingarmerking
vcard-adr-street = Heimilisfang
# Or "Locality"
vcard-adr-locality = Borg
# Or "Region"
vcard-adr-region = Ríki/Hérað
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Póstnúmer
vcard-adr-country = Land
vcard-note-header = Athugasemdir
vcard-note-add = Bæta við athugasemd
vcard-org-header = Skipulagslegir eignleikar
vcard-org-add = Bæta við skipulagslegum eignleikum
vcard-org-title = Titill
vcard-org-title-input =
    .placeholder = Starfstitill
    .title = Staða eða starf
vcard-org-role = Hlutverk
vcard-org-role-input =
    .placeholder = Hlutverk í verkefni
    .title = Hlutverk eða þátttaka í tilteknum aðstæðum
vcard-org-org = Fyrirtæki/Stofnun
vcard-org-org-input =
    .placeholder = Nafn á fyrirtæki/stofnun/félagi
    .title = Heiti skipulagsheildar
vcard-org-org-unit = Deild
vcard-org-org-unit-input =
    .placeholder = Deild
    .title = Heiti skipulagseiningar
vcard-custom-header = Sérsniðnir eiginleikar
vcard-custom-add = Bæta við sérsniðnum eiginleikum
vcard-remove-button-title =
    .title = Fjarlægja
vcard-remove-button = Fjarlægja
