# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Alles auswählen
select-none-calendars = Nichts auswählen
calendar-creation-wizard-title = Neuen Kalender erstellen
calendar-creation-initial-description = Ihr Kalender kann auf Ihrem Computer oder auf einem Server gespeichert werden, sodass Sie von anderen Orten darauf zugreifen bzw. ihn mit Freunden oder Arbeitskollegen gemeinsam verwenden können.
calendar-creation-initial-computer =
    .label = Auf meinem Computer
calendar-creation-initial-network =
    .label = Im Netzwerk
calendar-creation-username =
    .value = Benutzername:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Kalender erstellen
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Zurück
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Kalender erstellen
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Zurück
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Kalender suchen
    .buttonaccesskeyaccept = i
    .buttonlabelextra2 = Zurück
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonnieren
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Zurück
    .buttonaccesskeyextra2 = Z
calendar-creation-type =
    .value = Kalendertyp:
calendar-creation-location =
    .value = Adresse:
calendar-creation-location-placeholder =
    .placeholder = Adresse oder Host-Name des Kalender-Servers
    .default-placeholder = Adresse oder Host-Name des Kalender-Servers
calendar-creation-network-nocredentials =
    .label = Diese Adresse verlangt keine Zugangsdaten.
calendar-creation-network-loading = Bitte warten, es wird nach Kalendern gesucht.
calendar-creation-network-notfound = Keine Kalender unter dieser Adresse gefunden. Bitte die Einstellungen überprüfen.
calendar-creation-network-authfail = Die eingegebenen Zugangsdaten wurden abgelehnt. Bitte die Einstellungen überprüfen.
calendar-creation-network-certerror = An dieser Adresse wurden aufgrund eines Zertifikatsproblems keine Kalender gefunden.
calendar-creation-network-subscribe-single = Bitte die zu abonnierenden Kalender auswählen.
calendar-creation-network-subscribe-multiple = Unter dieser Adresse stehen verschiedene Kalendertypen zur Auswahl. Wählen Sie zuerst den Kalendertyp und anschließend die zu abonnierenden Kalender.
