# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Kommentar
calendar-item-summary-title = Titel:
calendar-item-summary-calendar = Kalender:
calendar-item-summary-task-start = Beginn:
calendar-item-summary-event-start = Beginn:
calendar-item-summary-task-due = Fällig:
calendar-item-summary-event-end = Ende:
calendar-item-summary-repeat = Wiederholen:
calendar-item-summary-location = Ort:
calendar-item-summary-category = Kategorie:
calendar-item-summary-organizer = Organisator:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Erinnerung:
calendar-item-summary-attachments = Anhänge:
calendar-item-summary-status-tentative = Vorläufig
calendar-item-summary-status-confirmed = Bestätigt
calendar-item-summary-event-status-cancelled = Abgesagt
calendar-item-summary-todo-status-cancelled = Abgebrochen
calendar-item-summary-status-needs-action = Benötigt Eingriff
calendar-item-summary-status-in-process = In Arbeit
calendar-item-summary-status-completed = Abgeschlossen am
calendar-item-summary-reminder-none =
    .label = Keine Erinnerung
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 Minuten vorher
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 Minuten vorher
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 Minuten vorher
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 Minuten vorher
calendar-item-summary-reminder-1-hour-before =
    .label = 1 Stunde vorher
calendar-item-summary-reminder-2-hours-before =
    .label = 2 Stunden vorher
calendar-item-summary-reminder-12-hours-before =
    .label = 12 Stunden vorher
calendar-item-summary-reminder-1-day-before =
    .label = 1 Tag vorher
calendar-item-summary-reminder-2-days-before =
    .label = 2 Tage vorher
calendar-item-summary-reminder-1-week-before =
    .label = 1 Woche vorher
calendar-item-summary-reminder-custom =
    .label = Benutzerdefiniert…
calendar-item-summary-reminder-multiple =
    .value = Mehrere Erinnerungen…
calendar-item-summary-general =
    .value = Allgemein
calendar-item-summary-attendees =
    .value = Teilnehmer
calendar-item-summary-description =
    .value = Beschreibung
calendar-item-summary-link =
    .value = Zugehöriger Link
