# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Configuración de spam
dialog-header-title =
    .value = Configuración de spam
training-description-spam = Si se habilita, primero debe entrenar a { -brand-short-name } para identificar el spam usando el botón Spam de la barra de herramientas para marcar los mensajes como spam o no. Necesita identificar tanto los mensajes de spam como los que no lo sean. Después de eso, { -brand-short-name } podrá marcar spam automáticamente.
spam-level-checkbox =
    .label = Habilitar controles adaptivos de spam para esta cuenta
    .accesskey = e
move-spam-message-menuitem =
    .label = Mover nuevos mensajes de spam a:
    .accesskey = M
set-spam-folder-menuitem =
    .label = Carpeta “Spam” en:
    .accesskey = S
move-message-other =
    .label = Otro:
    .accesskey = r
automatic-spam-purge-checkbox =
    .label = Eliminar automáticamente el spam de más de
    .accesskey = u
automatic-spam-purge-label =
    .value = días
trust-addresses-header-label =
    .value = Confiar en las direcciones de correo electrónico de estas libretas de direcciones:
    .accesskey = C
allowlist-header-label =
    .value = No marcar automáticamente el correo como spam si el remitente está en:
    .accesskey = N
isp-headers-checkbox =
    .label = Confiar en los encabezados de spam establecidos por:
    .accesskey = t
isp-warning-description = Si se habilita, { -brand-short-name } considerará automáticamente los mensajes marcados por este clasificador externo como spam.
spam-detecting-legend = Detectando spam
spam-storage-deletion-legend = Almacenamiento y borrado
spam-classification-legend = Selección
spam-actions-legend = Destino y retención
global-spam-preferences-button =
    .label = Configuración global de spam…
    .accesskey = g
manage-spam-title = Administrar spam
manage-spam-header =
    .value = Administrar spam
training-description-learns = Cuando está activado, { -brand-short-name } aprende de los mensajes que se marcan como spam o no spam. Cuanto más lo entrenes, mejor será { -brand-short-name } detectando spam.
spam-auto-detection-checkbox =
    .label = Habilitar la detección automática de spam para esta cuenta
    .accesskey = H
