# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Opciones sin conexión
autodetect-connection-label =
    .label = Cambiar modos automáticamente cuando se encuentre una conexión a Internet
    .accesskey = d
offline-startup-label = Al abrir { -brand-short-name }:
status-radio-last-used =
    .label = Usar el último modo de conexión usado
    .accesskey = U
status-radio-ask-connect =
    .label = Preguntar si conectarse en línea
    .accesskey = g
status-radio-start-online =
    .label = Iniciar en línea
    .accesskey = l
status-radio-start-offline =
    .label = Iniciar sin conexión
    .accesskey = I
going-online-prompt = Enviar mensajes esperando en la bandeja de salida
going-online-send =
    .label = Sí, enviar automáticamente
    .accesskey = v
going-online-keep =
    .label = No, mantener en la bandeja de salida
    .accesskey = N
going-online-ask-send =
    .label = Preguntar antes de enviar
    .accesskey = s
going-offline-prompt = ¿Quiere descargar mensajes para leerlos sin conexión?
going-offline-download =
    .label = Sí, descargar automáticamente
    .accesskey = e
going-offline-keep =
    .label = No, no descargar
    .accesskey = o
going-offline-ask-download =
    .label = Preguntar antes de descargar
    .accesskey = a
autodetect-online-label =
    .label = Seguir automáticamente el estado de conexión detectado
    .accesskey = d
offline-preference-startup-label = Estado manual al iniciar:
status-radio-remember =
    .label = Recordar el estado anterior de la conexión
    .accesskey = R
status-radio-ask =
    .label = Perguntarme el estado de conexión
    .accesskey = x
status-radio-always-online =
    .label = En línea
    .accesskey = l
status-radio-always-offline =
    .label = Fuera de línea
    .accesskey = F
going-online-label = ¿Enviar mensajes pendientes al conectarse?
going-online-auto =
    .label = Si
    .accesskey = S
going-online-not =
    .label = No
    .accesskey = N
going-online-ask =
    .label = Preguntarme
    .accesskey = P
going-offline-label = Al desconectarse, ¿descargar mensajes para usar sin conexión?
going-offline-auto =
    .label = Si
    .accesskey = i
going-offline-not =
    .label = No
    .accesskey = o
going-offline-ask =
    .label = Preguntarme
    .accesskey = a
