# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Offline-Einstellungen
autodetect-connection-label =
    .label = Bei erkannter Internetverbindung automatisch den Modus wechseln
    .accesskey = d
offline-startup-label = Beim Start von { -brand-short-name }:
status-radio-last-used =
    .label = Zuletzt genutzten Verbindungsmodus verwenden
    .accesskey = u
status-radio-ask-connect =
    .label = Nachfragen, ob eine Onlineverbindung hergestellt werden soll
    .accesskey = b
status-radio-start-online =
    .label = Online starten
    .accesskey = l
status-radio-start-offline =
    .label = Offline starten
    .accesskey = f
going-online-prompt = Ausstehende Nachrichten aus dem Postausgang senden
going-online-send =
    .label = Ja, automatisch versenden
    .accesskey = J
going-online-keep =
    .label = Nein, im Postausgang behalten
    .accesskey = N
going-online-ask-send =
    .label = Vor dem Senden fragen
    .accesskey = V
autodetect-online-label =
    .label = Automatisch erkannten Online-/Offline-Status verwenden
    .accesskey = u
offline-preference-startup-label = Benutzerdefinierter Zustand beim Programmstart:
status-radio-remember =
    .label = Vorherigen Online-/Offline-Status merken
    .accesskey = V
status-radio-ask =
    .label = Fragen, ob man online arbeiten möchte
    .accesskey = F
status-radio-always-online =
    .label = Immer online starten
    .accesskey = l
status-radio-always-offline =
    .label = Immer offline starten
    .accesskey = m
going-online-label = Postausgang senden, sobald man im Online-Modus ist:
going-online-auto =
    .label = Ja
    .accesskey = J
going-online-not =
    .label = Nein
    .accesskey = N
going-online-ask =
    .label = Fragen
    .accesskey = r
going-offline-label = Beim Wechsel in den Offline-Modus Nachrichten zum Offline-Lesen herunterladen:
going-offline-auto =
    .label = Ja
    .accesskey = a
going-offline-not =
    .label = Nein
    .accesskey = e
going-offline-ask =
    .label = Fragen
    .accesskey = g
