# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Seleccionar todo
select-none-calendars = No seleccionar ninguna
calendar-creation-wizard-title = Crear un nuevo calendario
calendar-creation-initial-description = El calendario puede guardarse en la computadora o en un servidor para que pueda accederse remotamente o compartirse con amigos y compañeros de trabajo.
calendar-creation-initial-computer =
    .label = En mi computadora
calendar-creation-initial-network =
    .label = En la red
calendar-creation-username =
    .value = Nombre de usuario:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = t
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = t
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Buscar calendarios
    .buttonaccesskeyaccept = B
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = t
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Suscribirse
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = t
calendar-creation-type =
    .value = Tipo de calendario:
calendar-creation-location =
    .value = Ubicación:
calendar-creation-location-placeholder =
    .placeholder = URL o nombre de host del servidor de calendario
    .default-placeholder = URL o nombre de host del servidor de calendario
calendar-creation-network-nocredentials =
    .label = Esta ubicación no requiere credenciales
calendar-creation-network-loading = Espere mientras sus calendarios se descubren.
calendar-creation-network-notfound = No se pudieron encontrar calendarios en esta ubicación. Revise su configuración.
calendar-creation-network-authfail = Las credenciales que ingresó no fueron aceptadas. Revise su configuración.
calendar-creation-network-certerror = No se pudieron encontrar calendarios en esta ubicación por un problema con el certificado.
calendar-creation-network-subscribe-single = Seleccione los calendarios a los que desee suscribirse.
calendar-creation-network-subscribe-multiple = Para esta ubicación están disponibles muchos tipos de calendarios. Seleccione el tipo de calendario y luego marque los calendarios a los que le gustaría suscribirse.
