# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Esnek boşluk
search-bar-label = Arama
toolbar-write-message-label = Yeni ileti
toolbar-write-message =
    .title = Yeni ileti yaz
toolbar-move-to-label = Taşı
toolbar-move-to =
    .title = Seçili iletiyi taşı
toolbar-unifinder-label = Etkinlikleri bul
toolbar-unifinder =
    .title = Etkinlik bulma bölmesini açar/kapatır
toolbar-folder-location-label = Klasör konumu
toolbar-folder-location =
    .title = Klasöre geç
toolbar-edit-event-label = Düzenle
toolbar-edit-event =
    .title = Seçilen etkinliği veya görevi sil
toolbar-get-messages-label = İletileri indir
toolbar-get-messages =
    .title = Tüm hesaplar için yeni iletileri indir
toolbar-reply-label = Yanıtla
toolbar-reply =
    .title = İletiyi yanıtla
toolbar-reply-all-label = Tümünü yanıtla
toolbar-reply-all =
    .title = Göndereni ve tüm alıcıları yanıtla
toolbar-reply-to-list-label = Listeyi yanıtla
toolbar-reply-to-list =
    .title = E-posta listesini yanıtla
toolbar-redirect-label = Yönlendir
toolbar-redirect =
    .title = Seçilen iletiyi yönlendir
toolbar-archive-label = Arşivle
toolbar-archive =
    .title = Seçilen iletileri arşivle
toolbar-conversation-label = Yazışma
toolbar-conversation =
    .title = Seçili iletinin yazışmasını göster
toolbar-previous-unread-label = Önceki okunmamış
toolbar-previous-unread =
    .title = Önceki okunmamış iletiye git
toolbar-previous-label = Önceki
toolbar-previous =
    .title = Önceki iletiye git
toolbar-next-unread-label = Sonraki okunmamış
toolbar-next-unread =
    .title = Sonraki okunmamış iletiye git
toolbar-next-label = Sonraki
toolbar-next =
    .title = Sonraki iletiye git
toolbar-junk-label = Gereksiz
toolbar-junk =
    .title = Seçili iletileri gereksiz olarak işaretle
toolbar-delete-label = Sil
toolbar-delete-title =
    .title = Seçilen iletileri sil
toolbar-undelete-label = Silmeyi geri al
toolbar-undelete =
    .title = Seçilen iletileri geri getir
toolbar-compact-label = Sıkıştır
toolbar-compact =
    .title = Seçilen klasörden silinmiş iletileri kaldır
toolbar-add-as-event-label = Etkinlik olarak ekle
toolbar-add-as-event =
    .title = Takvim bilgisini iletiden ayıklar ve takviminize etkinlik olarak ekler
toolbar-add-as-task-label = Görev olarak ekle
toolbar-add-as-task =
    .title = Takvim bilgisini iletiden ayıklar ve takviminize görev olarak ekler
toolbar-tag-message-label = Etiketle
toolbar-tag-message =
    .title = İletileri etiketle
toolbar-forward-inline-label = İlet
toolbar-forward-inline =
    .title = Seçilen iletiyi satır içi metin olarak ilet
toolbar-forward-attachment-label = Ek olarak ilet
toolbar-forward-attachment =
    .title = Seçilen iletiyi ek olarak ilet
toolbar-mark-as-label = İşaretle
toolbar-mark-as =
    .title = İletileri işaretle
toolbar-view-picker-label = Görüntüle
toolbar-view-picker =
    .title = Geçerli klasörün görünümünü özelleştir
toolbar-address-book-label = Adres defteri
toolbar-address-book =
    .title = Adres defterine git
toolbar-chat-label = Sohbet
toolbar-chat =
    .title = Sohbet sekmesini göster
toolbar-add-ons-and-themes-label = Eklentiler ve temalar
toolbar-add-ons-and-themes =
    .title = Eklentilerinizi yönetin
toolbar-calendar-label = Takvim
toolbar-calendar =
    .title = Takvim sekmesine geç
toolbar-tasks-label = Görevler
toolbar-tasks =
    .title = Görevler sekmesine geç
toolbar-mail-label = E-posta
toolbar-mail =
    .title = E-posta sekmesine geç
toolbar-print-label = Yazdır
toolbar-print =
    .title = Bu iletiyi yazdır
toolbar-quick-filter-bar-label = Hızlı süzgeç
toolbar-quick-filter-bar =
    .title = İletileri süz
toolbar-synchronize-label = Eşitle
toolbar-synchronize =
    .title = Takvimleri yeniden yükle ve değişiklikleri eşitle
toolbar-delete-event-label = Sil
toolbar-delete-event =
    .title = Seçilen etkinlikleri veya görevleri sil
toolbar-go-to-today-label = Bugüne git
toolbar-go-to-today =
    .title = Bugüne git
toolbar-print-event-label = Yazdır
toolbar-print-event =
    .title = Etkinlikleri veya görevleri yazdır
toolbar-new-event-label = Etkinlik
toolbar-new-event =
    .title = Yeni etkinlik oluştur
toolbar-new-task-label = Görev
toolbar-new-task =
    .title = Yeni görev oluştur
toolbar-go-back-label = Geri
toolbar-go-back =
    .title = Bir önceki iletiye gider
toolbar-go-forward-label = İleri
toolbar-go-forward =
    .title = Bir sonraki iletiye gider
toolbar-stop-label = Durdur
toolbar-stop =
    .title = Şu anki aktarımı durdur
toolbar-throbber-label = Etkinlik göstergesi
toolbar-throbber =
    .title = Etkinlik göstergesi
toolbar-create-contact-label = Yeni kişi
toolbar-create-contact =
    .title = Yeni kişi oluştur
toolbar-create-address-book-label = Yeni adres defteri
toolbar-create-address-book =
    .title = Yeni adres defteri oluştur
toolbar-create-list-label = Yeni liste
toolbar-create-list =
    .title = Yeni e-posta listesi oluştur
toolbar-import-contacts-label = İçe aktar
toolbar-import-contacts =
    .title = Kişileri dosyadan içe aktar

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Yerel adres defteri ekle
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV adres defteri ekle
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP adres defteri ekle
