# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Selectează tot
select-none-calendars = Nu selecta nimic
calendar-creation-wizard-title = Creează calendar nou
calendar-creation-initial-description = Calendarul poate fi stocat local, pe calculator sau pe un server pentru acces de la distanță sau partajarea cu prietenii sau colegii.
calendar-creation-initial-computer =
    .label = Pe calculatorul meu
calendar-creation-initial-network =
    .label = În rețea
calendar-creation-username =
    .value = Nume de utilizator:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Creează calendar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Înapoi
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Creează calendar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Înapoi
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Caută calendare
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Înapoi
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonează-te
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Înapoi
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = Tip calendar:
calendar-creation-location =
    .value = Locație:
calendar-creation-location-placeholder =
    .placeholder = URL sau denumirea serverului-gazdă pe care se află calendarul
    .default-placeholder = URL sau denumirea serverului-gazdă pe care se află calendarul
calendar-creation-network-nocredentials =
    .label = Locația nu necesită date de autentificare
calendar-creation-network-loading = Te rugăm să aștepți cât timp se descoperă calendarele.
calendar-creation-network-notfound = Nu au fost găsite calendare la această locație. Te rugăm să verifici setările.
calendar-creation-network-authfail = Datele de autentificare introduse nu au fost acceptate. Te rugăm să verifici setările.
calendar-creation-network-certerror = Nu s-au găsit calendare în această locație din cauza unei probleme cu certificatul.
calendar-creation-network-subscribe-single = Te rugăm să selectezi calendarele la care dorești să te abonezi.
calendar-creation-network-subscribe-multiple = În această locație sunt disponibile mai multe calendare. Alege tipul de calendar, apoi marchează calendarele la care dorești să te abonezi.
