# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Titlu:
calendar-item-summary-calendar = Calendar:
calendar-item-summary-task-start = Dată de început:
calendar-item-summary-event-start = Dată de început:
calendar-item-summary-task-due = Termen-limită:
calendar-item-summary-event-end = Dată de sfârșit:
calendar-item-summary-repeat = Repetă:
calendar-item-summary-location = Locație:
calendar-item-summary-category = Categorie:
calendar-item-summary-organizer = Organizator:
calendar-item-summary-status = Stare:
calendar-item-summary-reminder = Memento:
calendar-item-summary-attachments = Atașamente:
calendar-item-summary-status-tentative = Provizoriu
calendar-item-summary-status-confirmed = Confirmat
calendar-item-summary-event-status-cancelled = Anulat
calendar-item-summary-todo-status-cancelled = Anulată
calendar-item-summary-status-needs-action = Necesită acțiune
calendar-item-summary-status-in-process = În desfășurare
calendar-item-summary-status-completed = Finalizat la data de
calendar-item-summary-reminder-none =
    .label = Fără memento
calendar-item-summary-reminder-0-minutes-before =
    .label = cu 0 minute înainte
calendar-item-summary-reminder-5-minutes-before =
    .label = cu 5 minute înainte
calendar-item-summary-reminder-15-minutes-before =
    .label = cu 15 minute înainte
calendar-item-summary-reminder-30-minutes-before =
    .label = cu 30 de minute înainte
calendar-item-summary-reminder-1-hour-before =
    .label = cu 1 oră înainte
calendar-item-summary-reminder-2-hours-before =
    .label = cu 2 ore înainte
calendar-item-summary-reminder-12-hours-before =
    .label = cu 12 ore înainte
calendar-item-summary-reminder-1-day-before =
    .label = cu 1 zi înainte
calendar-item-summary-reminder-2-days-before =
    .label = cu 2 zile înainte
calendar-item-summary-reminder-1-week-before =
    .label = cu 1 săptămână înainte
calendar-item-summary-reminder-custom =
    .label = Personalizat…
calendar-item-summary-reminder-multiple =
    .value = Mementouri multiple…
calendar-item-summary-general =
    .value = General
calendar-item-summary-attendees =
    .value = Participanți
calendar-item-summary-description =
    .value = Descriere
calendar-item-summary-link =
    .value = Link asociat
