# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = e un eveniment recurent
header-isrepeating-task =
    .label = e o sarcină recurentă
header-containsrepeating-event =
    .label = conține evenimente recurente
header-containsrepeating-task =
    .label = conține sarcini recurente
header-containsrepeating-mixed =
    .label = conține elemente recurente de diferite tipuri
windowtitle-event-copy = Copiază eveniment recurent
windowtitle-task-copy = Copiază sarcină recurentă
windowtitle-mixed-copy = Copiază elementele recurente
windowtitle-event-cut = Taie eveniment recurent
windowtitle-task-cut = Taie sarcină recurentă
windowtitle-mixed-cut = Taie elementele recurente
windowtitle-event-delete = Ștergere eveniment recurent
windowtitle-task-delete = Ștergere sarcină recurentă
windowtitle-mixed-delete = Șterge elementele recurente
windowtitle-event-edit = Editare eveniment recurent
windowtitle-task-edit = Editează sarcină recurentă
windowtitle-mixed-edit = Editează elementele recurente
windowtitle-multipleitems =
    .value = Elementele selectate
button-single-occurrence-copy =
    .label = Copiază doar această apariție
    .accesskey = t
button-single-occurrence-cut =
    .label = Taie doar această apariție
    .accesskey = t
button-single-occurrence-delete =
    .label = Șterge doar această apariție
    .accesskey = t
button-single-occurrence-edit =
    .label = Editează doar această apariție
    .accesskey = t
button-multiple-occurrence-copy =
    .label = Copiază doar aparițiile selectate
    .accesskey = t
button-multiple-occurrence-cut =
    .label = Taie doar aparițiile selectate
    .accesskey = t
button-multiple-occurrence-delete =
    .label = Șterge doar aparițiile selectate
    .accesskey = t
button-multiple-occurrence-edit =
    .label = Editează doar aparițiile selectate
    .accesskey = t
button-single-allfollowing-copy =
    .label = Copiază această apariție și pe toate cele viitoare
    .accesskey = a
button-single-allfollowing-cut =
    .label = Taie această apariție și pe toate cele viitoare
    .accesskey = a
button-single-allfollowing-delete =
    .label = Șterge această apariție și pe toate cele viitoare
    .accesskey = a
button-single-allfollowing-edit =
    .label = Editează această apariție și pe toate cele viitoare
    .accesskey = a
button-multiple-allfollowing-copy =
    .label = Copiază apariția selectată și pe toate cele viitoare
    .accesskey = a
button-multiple-allfollowing-cut =
    .label = Taie apariția selectată și pe toate cele viitoare
    .accesskey = a
button-multiple-allfollowing-delete =
    .label = Șterge apariția selectată și pe toate cele viitoare
    .accesskey = a
button-multiple-allfollowing-edit =
    .label = Editează apariția selectată și pe toate cele viitoare
    .accesskey = a
button-single-parent-copy =
    .label = Copiază toate aparițiile
    .accesskey = a
button-single-parent-cut =
    .label = Taie toate aparițiile
    .accesskey = a
button-single-parent-delete =
    .label = Șterge toate aparițiile
    .accesskey = a
button-single-parent-edit =
    .label = Editează toate aparițiile
    .accesskey = a
button-multiple-parent-copy =
    .label = Copiază toate aparițiile elementelor selectate
    .accesskey = a
button-multiple-parent-cut =
    .label = Taie toate aparițiile elementelor selectate
    .accesskey = a
button-multiple-parent-delete =
    .label = Șterge toate aparițiile elementelor selectate
    .accesskey = a
button-multiple-parent-edit =
    .label = Editează toate aparițiile elementelor selectate
    .accesskey = a
buttons-single-occurrence-copy =
    .label = Copiază doar această apariție
buttons-single-occurrence-cut =
    .label = Taie doar această apariție
buttons-single-occurrence-delete =
    .label = Șterge doar această apariție
buttons-single-occurrence-edit =
    .label = Editează doar această apariție
buttons-multiple-occurrence-copy =
    .label = Copiază doar aparițiile selectate
buttons-multiple-occurrence-cut =
    .label = Taie doar aparițiile selectate
buttons-multiple-occurrence-delete =
    .label = Șterge doar aparițiile selectate
buttons-multiple-occurrence-edit =
    .label = Editează doar aparițiile selectate
buttons-single-allfollowing-copy =
    .label = Copiază această apariție și pe toate cele viitoare
buttons-single-allfollowing-cut =
    .label = Taie această apariție și pe toate cele viitoare
buttons-single-allfollowing-delete =
    .label = Șterge această apariție și pe toate cele viitoare
buttons-single-allfollowing-edit =
    .label = Editează această apariție și pe toate cele viitoare
buttons-multiple-allfollowing-copy =
    .label = Copiază apariția selectată și pe toate cele viitoare
buttons-multiple-allfollowing-cut =
    .label = Taie apariția selectată și pe toate cele viitoare
buttons-multiple-allfollowing-delete =
    .label = Șterge apariția selectată și pe toate cele viitoare
buttons-multiple-allfollowing-edit =
    .label = Editează apariția selectată și pe toate cele viitoare
buttons-single-parent-copy =
    .label = Copiază toate aparițiile
buttons-single-parent-cut =
    .label = Taie toate aparițiile
buttons-single-parent-delete =
    .label = Șterge toate aparițiile
buttons-single-parent-edit =
    .label = Editează toate aparițiile
buttons-multiple-parent-copy =
    .label = Copiază toate aparițiile elementelor selectate
buttons-multiple-parent-cut =
    .label = Taie toate aparițiile elementelor selectate
buttons-multiple-parent-delete =
    .label = Șterge toate aparițiile elementelor selectate
buttons-multiple-parent-edit =
    .label = Editează toate aparițiile elementelor selectate
