# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Име за приказ
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Врста
vcard-entry-type-home = Кућа
vcard-entry-type-work = Посао
vcard-entry-type-none = Ништа
vcard-entry-type-custom = Произвољно
vcard-name-header = Име
vcard-n-prefix = Префикс
vcard-n-add-prefix =
    .title = Додај префикс
vcard-n-firstname = Име
vcard-n-add-firstname =
    .title = Додајте име
vcard-n-middlename = Средње име
vcard-n-add-middlename =
    .title = Додај средње име
vcard-n-lastname = Презиме
vcard-n-add-lastname =
    .title = Додајте презиме
vcard-n-suffix = Суфикс
vcard-n-add-suffix =
    .title = Додај суфикс
vcard-nickname = Надимак
vcard-email-header = Адресе е-поште
vcard-email-add = Додај адресу е-поште
vcard-email-label = Адреса е-поште
vcard-primary-email-label = Подразумевано
vcard-url-header = Веб странице
vcard-url-add = Додај веб страницу
vcard-url-label = Веб страница
vcard-tel-header = Бројеви телефона
vcard-tel-add = Додај број телефона
vcard-tel-label = Број телефона
# Or "Mobile"
vcard-entry-type-cell = Мобилни
vcard-entry-type-fax = Факс
vcard-entry-type-pager = Пејџер
vcard-tz-header = Временска зона
vcard-tz-add = Додај временску зону
vcard-impp2-header = Тренутне поруке
vcard-impp-add = Додај налог за ћаскање
vcard-impp-label = Налог за ћаскање
vcard-impp-select = Протокол
vcard-impp-option-other = Друго
vcard-impp-input-label = УРИ
vcard-impp-input-title = УРИ за тренутне поруке
vcard-bday-anniversary-header = Посебни датуми
vcard-bday-anniversary-add = Додај посебан датум
vcard-bday-label = Рођендан
vcard-anniversary-label = Годишњица
vcard-date-day = Дан
vcard-date-month = Месец
vcard-date-year = Година
vcard-adr-header = Адресе
vcard-adr-add = Додај адресу
vcard-adr-label = Адреса
vcard-adr-delivery-label = Натпис за доставу
vcard-adr-street = Улица и број
# Or "Locality"
vcard-adr-locality = Град
# Or "Region"
vcard-adr-region = Држава/покрајина
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Поштански број
vcard-adr-country = Држава
vcard-note-header = Белешке
vcard-note-add = Додај белешку
vcard-org-header = Организациона својства
vcard-org-add = Додај организациона својства
vcard-org-title = Наслов
vcard-org-title-input =
    .placeholder = Звање на послу
    .title = Положај или посао
vcard-org-role = Улога
vcard-org-role-input =
    .placeholder = Улога у пројекту
    .title = Функција или улога у одређеној ситуацији
vcard-org-org = Организација
vcard-org-org-input =
    .placeholder = Назив предузећа
    .title = Назив организације
vcard-org-org-unit = Одељење
vcard-org-org-unit-input =
    .placeholder = Одељење
    .title = Назив организационе јединице
vcard-custom-header = Произвољна својства
vcard-custom-add = Додај произвољна својства
vcard-remove-button-title =
    .title = Уклони
vcard-remove-button = Уклони
