# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Pyta se…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 wótpowědnik namakany;#1 wótpowědnika namakanej;#1 wótpowědniki namakane;#1 wótpowědnikow namakane
noMatchesFound = Žedne wótpowědniki namakane
labelForStopButton = Stoj
labelForSearchButton = Pytaś
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = P
moreButtonTooltipText = Nowe pšawidło pśidaś
lessButtonTooltipText = Toś to pšawidło wótpóraś
