# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Pružná mezera
search-bar-label = Vyhledávací pole
toolbar-write-message-label = Napsat
toolbar-write-message =
    .title = Vytvoří novou zprávu
toolbar-move-to-label = Přesunout do
toolbar-move-to =
    .title = Přesunout vybrané zprávy
toolbar-unifinder-label = Najít události
toolbar-unifinder =
    .title = Přepnout panel vyhledávání událostí
toolbar-folder-location-label = Umístění složky
toolbar-folder-location =
    .title = Přepnout do složky
toolbar-edit-event-label = Upravit
toolbar-edit-event =
    .title = Upraví vybranou událost nebo úkol
toolbar-get-messages-label = Přijmout zprávy
toolbar-get-messages =
    .title = Stáhnout nové zprávy pro všechny účty
toolbar-reply-label = Odpovědět
toolbar-reply =
    .title = Odpoví na zprávu
toolbar-reply-all-label = Odp. všem
toolbar-reply-all =
    .title = Odpoví na zprávu odesílateli a všem příjemcům
toolbar-reply-to-list-label = Odp. do konf.
toolbar-reply-to-list =
    .title = Odpoví na zprávu do skupiny
toolbar-redirect-label = Přesměrovat
toolbar-redirect =
    .title = Přesměruje vybranou zprávu
toolbar-archive-label = Archivovat
toolbar-archive =
    .title = Archivovat označené zprávy
toolbar-conversation-label = Konverzace
toolbar-conversation =
    .title = Zobrazit konverzaci k vybrané zprávě
toolbar-previous-unread-label = Předchozí nepřečtená
toolbar-previous-unread =
    .title = Přejde na předcházející nepřečtenou zprávu
toolbar-previous-label = Předchozí
toolbar-previous =
    .title = Přejde na předcházející zprávu
toolbar-next-unread-label = Další nepřečtená
toolbar-next-unread =
    .title = Přejde na další nepřečtenou zprávu
toolbar-next-label = Další
toolbar-next =
    .title = Přejde na další zprávu
toolbar-junk-label = Nevyžádaná pošta
toolbar-junk =
    .title = Označí vybrané zprávy jako nevyžádanou poštu
toolbar-delete-label = Smazat
toolbar-delete-title =
    .title = Smazat vybrané zprávy
toolbar-undelete-label = Zrušit smazání
toolbar-undelete =
    .title = Zrušit smazání vybraných zpráv
toolbar-compact-label = Provést údržbu
toolbar-compact =
    .title = Ze zvolené složky odstraní smazané zprávy
toolbar-add-as-event-label = Přidat jako událost
toolbar-add-as-event =
    .title = Vezme kalendářní informace ze zprávy a přidá je do vašeho kalendáře jako událost
toolbar-add-as-task-label = Přidat jako úkol
toolbar-add-as-task =
    .title = Vezme kalendářní informace ze zprávy a přidá je do vašeho kalendáře jako úkol
toolbar-tag-message-label = Štítek
toolbar-tag-message =
    .title = Přidá štítek
toolbar-forward-inline-label = Přeposlat
toolbar-forward-inline =
    .title = Přepošle označenou zprávu jako vložený text
toolbar-forward-attachment-label = Přeposlat jako přílohu
toolbar-forward-attachment =
    .title = Přepošle označenou zprávu jako přílohu
toolbar-mark-as-label = Označit
toolbar-mark-as =
    .title = Označí zprávu
toolbar-view-picker-label = Zobrazit
toolbar-view-picker =
    .title = Přizpůsobit zobrazení aktuální složky
toolbar-address-book-label = Kontakty
toolbar-address-book =
    .title = Přejde do Kontaktů
toolbar-chat-label = Chat
toolbar-chat =
    .title = Zobrazí panel chatu
toolbar-add-ons-and-themes-label = Doplňky a vzhledy
toolbar-add-ons-and-themes =
    .title = Správa doplňků
toolbar-calendar-label = Kalendář
toolbar-calendar =
    .title = Přepne na panel kalendáře
toolbar-tasks-label = Úkoly
toolbar-tasks =
    .title = Přepne na panel úkolů
toolbar-mail-label = Pošta
toolbar-mail =
    .title = Přepnout na panel s poštou
toolbar-print-label = Tisk
toolbar-print =
    .title = Vytiskne zprávu
toolbar-quick-filter-bar-label = Rychlý filtr
toolbar-quick-filter-bar =
    .title = Filtrování zpráv
toolbar-synchronize-label = Synchronizovat
toolbar-synchronize =
    .title = Obnoví kalendáře a synchronizuje změny
toolbar-delete-event-label = Smazat
toolbar-delete-event =
    .title = Smaže vybrané události nebo úkoly
toolbar-go-to-today-label = Přejít na dnešní den
toolbar-go-to-today =
    .title = Přejde na dnešní den
toolbar-print-event-label = Tisk
toolbar-print-event =
    .title = Vytiskne události nebo úkoly
toolbar-new-event-label = Událost
toolbar-new-event =
    .title = Vytvoří novou událost
toolbar-new-task-label = Úkol
toolbar-new-task =
    .title = Vytvoří nový úkol
toolbar-go-back-label = Zpět
toolbar-go-back =
    .title = Přejde o jednu zprávu vzad
toolbar-go-forward-label = Vpřed
toolbar-go-forward =
    .title = Přejde o jednu zprávu vpřed
toolbar-stop-label = Zastavit
toolbar-stop =
    .title = Ukončí probíhající spojení
toolbar-throbber-label = Indikátor aktivity
toolbar-throbber =
    .title = Indikátor aktivity
toolbar-create-contact-label = Nový kontakt
toolbar-create-contact =
    .title = Vytvoření nového kontaktu
toolbar-create-address-book-label = Nová složka kontaktů
toolbar-create-address-book =
    .title = Vytvoření nové složky kontaktů
toolbar-create-list-label = Nová skupina
toolbar-create-list =
    .title = Vytvořit novou skupinu
toolbar-import-contacts-label = Importovat
toolbar-import-contacts =
    .title = Importovat kontakty ze souboru

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Přidat místní složku kontaktů
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Přidat složku kontaktů CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Přidat složku kontaktů LDAP
