# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Առաձգական Տարածք
toolbar-write-message-label = Գրել
toolbar-write-message =
    .title = Ստեղծել նոր նամակ
toolbar-unifinder-label = Գտնել միջոցառումներ
toolbar-unifinder =
    .title = Փոխարկել գտնված միջոցառումների փեղկը
toolbar-folder-location-label = Թղթապանակի տեղը՝
toolbar-edit-event-label = Խմբագրել
toolbar-edit-event =
    .title = Խմբագրել ընտրված իրադարձությունը կամ առաջադրանքը
toolbar-get-messages-label = Ստանալ նամակները
toolbar-reply-label = Պատասխանել
toolbar-reply =
    .title = Պատասխանել նամակին
toolbar-reply-all-label = Պատասխանել բոլորին
toolbar-reply-all =
    .title = Պատ. ուղարկողին և մյուսներին
toolbar-reply-to-list-label = Պատասխանել ցանկով
toolbar-reply-to-list =
    .title = Պատաս. ցանկին
toolbar-archive-label = Արխիվ
toolbar-archive =
    .title = Արխիվացնել ընտրված նամակները
toolbar-conversation-label = Զրույց
toolbar-conversation =
    .title = Ցուցադրել ընտրված հաղորդագրության զրույցը
toolbar-previous-unread-label = Նախորդ չկարդացածը
toolbar-previous-unread =
    .title = Տեղափ. նախորդ չընթերցված նամակը
toolbar-previous-label = Նախորդ
toolbar-previous =
    .title = Նախորդ գրությունը
toolbar-next-unread-label = Հաջորդ չընթերցվածը
toolbar-next-unread =
    .title = Տեղափ. հաջորդ չընթերցված նամակը
toolbar-next-label = Հաջորդը
toolbar-next =
    .title = Հաջորդ գրությունը
toolbar-compact-label = Սեղմել
toolbar-compact =
    .title = Հեռացնել ջնջված նամակները ընտրված թղթ-ից
toolbar-add-as-event-label = Ավելացնել որպես իրադարձություն
toolbar-add-as-event =
    .title = Հանե՛ք օրացույցի տեղեկությունը հաղորդագրությունից և ավելացրե՛ք այն ձեր օրացույցում որպես առաջադրանք
toolbar-add-as-task-label = Ավելացնել որպես առաջադրանք
toolbar-add-as-task =
    .title = Հանե՛ք օրացույցի տեղեկությունը հաղորդագրությունից և ավելացրե՛ք այն ձեր օրացույցում որպես առաջադրանք
toolbar-tag-message-label = Պիտակ
toolbar-tag-message =
    .title = Կցագրել նամակները
toolbar-forward-inline-label = Փոխանցել
toolbar-forward-inline =
    .title = Փոխանցել ընտրված նամակները որպես ներտող տեքստ
toolbar-forward-attachment-label = Փոխանցել որպես կցորդ
toolbar-forward-attachment =
    .title = Forward selected message as an attachment
toolbar-mark-as-label = Նշել
toolbar-mark-as =
    .title = Նշել նամակներ
toolbar-address-book =
    .title = Անցնել Հասցեագրքին
toolbar-chat-label = Զրույց
toolbar-chat =
    .title = Ցուցադրել Զրույցի էջը
toolbar-calendar-label = Օրացույց
toolbar-calendar =
    .title = Բացել օրացույցի ներդիրը
toolbar-tasks-label = Առաջադրանքներ
toolbar-tasks =
    .title = Բացել առաջադրանքների ներդիրը
toolbar-print-label = Տպել
toolbar-print =
    .title = Տպել այս նամակը
