# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Keresés…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 találat van;#1 találat van
noMatchesFound = Nincs találat
labelForStopButton = Leállítás
labelForSearchButton = Keresés
labelForStopButton.accesskey = L
labelForSearchButton.accesskey = K
moreButtonTooltipText = Új szabály hozzáadása
lessButtonTooltipText = Szabály eltávolítása
