# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = є повторюваною подією
header-isrepeating-task =
    .label = є повторюваним завданням
header-containsrepeating-event =
    .label = містить повторювані події
header-containsrepeating-task =
    .label = містить повторювані завдання
header-containsrepeating-mixed =
    .label = містить повторювані елементи різного типу
windowtitle-event-copy = Копіювати повторювану подію
windowtitle-task-copy = Копіювати повторюване завдання
windowtitle-mixed-copy = Копіювати повторювані елементи
windowtitle-event-cut = Вирізати повторювану подію
windowtitle-task-cut = Вирізати повторюване завдання
windowtitle-mixed-cut = Вирізати повторювані елементи
windowtitle-event-delete = Видалити повторювану подію
windowtitle-task-delete = Видалити повторюване завдання
windowtitle-mixed-delete = Видалити повторювані елементи
windowtitle-event-edit = Редагувати повторювану подію
windowtitle-task-edit = Редагувати повторюване завдання
windowtitle-mixed-edit = Редагувати повторювані елементи
windowtitle-multipleitems =
    .value = Вибрані елементи
button-single-occurrence-copy =
    .label = Копіювати тільки це повторювання
    .accesskey = п
button-single-occurrence-cut =
    .label = Вирізати тільки це повторювання
    .accesskey = п
button-single-occurrence-delete =
    .label = Видалити тільки це повторювання
    .accesskey = п
button-single-occurrence-edit =
    .label = Редагувати тільки це повторювання
    .accesskey = п
button-multiple-occurrence-copy =
    .label = Копіювати тільки вибране повторювання
    .accesskey = п
button-multiple-occurrence-cut =
    .label = Вирізати тільки вибране повторювання
    .accesskey = п
button-multiple-occurrence-delete =
    .label = Видалити тільки вибране повторювання
    .accesskey = п
button-multiple-occurrence-edit =
    .label = Редагувати тільки вибране повторювання
    .accesskey = п
button-single-allfollowing-copy =
    .label = Копіювати це і всі майбутні повторювання
    .accesskey = н
button-single-allfollowing-cut =
    .label = Вирізати це і всі майбутні повторювання
    .accesskey = н
button-single-allfollowing-delete =
    .label = Видалити це і всі майбутні повторювання
    .accesskey = н
button-single-allfollowing-edit =
    .label = Редагувати це і всі майбутні повторювання
    .accesskey = н
button-multiple-allfollowing-copy =
    .label = Копіювати вибране та всі майбутні повторювання
    .accesskey = н
button-multiple-allfollowing-cut =
    .label = Вирізати вибране та всі майбутні повторювання
    .accesskey = н
button-multiple-allfollowing-delete =
    .label = Видалити вибране та всі майбутні повторювання
    .accesskey = н
button-multiple-allfollowing-edit =
    .label = Редагувати вибране та всі майбутні повторювання
    .accesskey = н
button-single-parent-copy =
    .label = Копіювати всі повторювання
    .accesskey = с
button-single-parent-cut =
    .label = Вирізати всі повторювання
    .accesskey = с
button-single-parent-delete =
    .label = Видалити всі повторювання
    .accesskey = с
button-single-parent-edit =
    .label = Редагувати всі повторювання
    .accesskey = с
button-multiple-parent-copy =
    .label = Копіювати всі повторювання для вибраних елементів
    .accesskey = с
button-multiple-parent-cut =
    .label = Вирізати всі повторювання для вибраних елементів
    .accesskey = с
button-multiple-parent-delete =
    .label = Видалити всі повторювання для вибраних елементів
    .accesskey = с
button-multiple-parent-edit =
    .label = Редагувати всі повторювання для вибраних елементів
    .accesskey = с
buttons-single-occurrence-copy =
    .label = Копіювати тільки це повторювання
buttons-single-occurrence-cut =
    .label = Вирізати тільки це повторювання
buttons-single-occurrence-delete =
    .label = Видалити тільки це повторювання
buttons-single-occurrence-edit =
    .label = Редагувати тільки це повторювання
buttons-multiple-occurrence-copy =
    .label = Копіювати тільки вибране повторювання
buttons-multiple-occurrence-cut =
    .label = Вирізати тільки вибране повторювання
buttons-multiple-occurrence-delete =
    .label = Видалити тільки вибране повторювання
buttons-multiple-occurrence-edit =
    .label = Редагувати тільки вибране повторювання
buttons-single-allfollowing-copy =
    .label = Копіювати це і всі майбутні повторювання
buttons-single-allfollowing-cut =
    .label = Вирізати це і всі майбутні повторювання
buttons-single-allfollowing-delete =
    .label = Видалити це і всі майбутні повторювання
buttons-single-allfollowing-edit =
    .label = Редагувати це і всі майбутні повторювання
buttons-multiple-allfollowing-copy =
    .label = Копіювати вибране та всі майбутні повторювання
buttons-multiple-allfollowing-cut =
    .label = Вирізати вибране та всі майбутні повторювання
buttons-multiple-allfollowing-delete =
    .label = Видалити вибране та всі майбутні повторювання
buttons-multiple-allfollowing-edit =
    .label = Редагувати вибране та всі майбутні повторювання
buttons-single-parent-copy =
    .label = Копіювати всі повторювання
buttons-single-parent-cut =
    .label = Вирізати всі повторювання
buttons-single-parent-delete =
    .label = Видалити всі повторювання
buttons-single-parent-edit =
    .label = Редагувати всі повторювання
buttons-multiple-parent-copy =
    .label = Копіювати всі повторювання для вибраних елементів
buttons-multiple-parent-cut =
    .label = Вирізати всі повторювання для вибраних елементів
buttons-multiple-parent-delete =
    .label = Видалити всі повторювання для вибраних елементів
buttons-multiple-parent-edit =
    .label = Редагувати всі повторювання для вибраних елементів
