# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Назва:
calendar-item-summary-calendar = Календар:
calendar-item-summary-task-start = Дата початку:
calendar-item-summary-event-start = Дата початку:
calendar-item-summary-task-due = Дата завершення:
calendar-item-summary-event-end = Дата завершення:
calendar-item-summary-repeat = Повторюється:
calendar-item-summary-location = Місце:
calendar-item-summary-category = Категорія:
calendar-item-summary-organizer = Організатор:
calendar-item-summary-status = Стан:
calendar-item-summary-reminder = Нагадування:
calendar-item-summary-attachments = Вкладення:
calendar-item-summary-status-tentative = Сумнівно
calendar-item-summary-status-confirmed = Підтверджено
calendar-item-summary-event-status-cancelled = Скасовано
calendar-item-summary-todo-status-cancelled = Скасовано
calendar-item-summary-status-needs-action = Вимагає дії
calendar-item-summary-status-in-process = В процесі
calendar-item-summary-status-completed = Завершено:
calendar-item-summary-reminder-none =
    .label = Не нагадувати
calendar-item-summary-reminder-0-minutes-before =
    .label = за 0 хвилин
calendar-item-summary-reminder-5-minutes-before =
    .label = за 5 хвилин
calendar-item-summary-reminder-15-minutes-before =
    .label = за 15 хвилин
calendar-item-summary-reminder-30-minutes-before =
    .label = за 30 хвилин
calendar-item-summary-reminder-1-hour-before =
    .label = за 1 годину
calendar-item-summary-reminder-2-hours-before =
    .label = за 2 години
calendar-item-summary-reminder-12-hours-before =
    .label = за 12 годин
calendar-item-summary-reminder-1-day-before =
    .label = за 1 день
calendar-item-summary-reminder-2-days-before =
    .label = за 2 дні
calendar-item-summary-reminder-1-week-before =
    .label = за 1 тиждень
calendar-item-summary-reminder-custom =
    .label = Налаштувати…
calendar-item-summary-reminder-multiple =
    .value = Багаторазові нагадування…
calendar-item-summary-general =
    .value = Загальне
calendar-item-summary-attendees =
    .value = Учасники
calendar-item-summary-description =
    .value = Опис
calendar-item-summary-link =
    .value = Посилання
