# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Nikanöx…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 nuk'äm ri', ri xilitäj;#1 nikik'äm ki', ri xe'ilitäj
noMatchesFound = Majun taq rujunamil ye'ilitäj
labelForStopButton = Tiq'at
labelForSearchButton = Tikanöx
labelForStopButton.accesskey = T
labelForSearchButton.accesskey = T
moreButtonTooltipText = Titz'aqatisäx jun k'ak'a' b'eyal
lessButtonTooltipText = Tiyuj re b'eyal re'
