# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = је поновни догађај
header-isrepeating-task =
    .label = је поновни задатак
header-containsrepeating-event =
    .label = садржи понављајуће догађаје
header-containsrepeating-task =
    .label = садржи понављајуће задатке
header-containsrepeating-mixed =
    .label = садржи понављајуће ставке различитих врста
windowtitle-event-copy = Копирај понављајући догађај
windowtitle-task-copy = Копирај понављајући задатак
windowtitle-mixed-copy = Копирај понављајуће ставке
windowtitle-event-cut = Исеци понављајући догађај
windowtitle-task-cut = Исеци понављајући задатак
windowtitle-mixed-cut = Исеци понављајуће ставке
windowtitle-event-delete = Обриши поновни догађај
windowtitle-task-delete = Обриши поновни задатак
windowtitle-mixed-delete = Обриши понављајуће ставке
windowtitle-event-edit = Уреди поновни догађај
windowtitle-task-edit = Уреди поновни задатак
windowtitle-mixed-edit = Уреди понављајуће ставке
windowtitle-multipleitems =
    .value = Изабране ставке
button-single-occurrence-copy =
    .label = Копирај само ово понављање
    .accesskey = о
button-single-occurrence-cut =
    .label = Исеци само ово понављање
    .accesskey = о
button-single-occurrence-delete =
    .label = Обриши само ово понављање
    .accesskey = о
button-single-occurrence-edit =
    .label = Уреди само ово понављање
    .accesskey = о
button-multiple-occurrence-copy =
    .label = Копирај само изабрана понављања
    .accesskey = о
button-multiple-occurrence-cut =
    .label = Исеци само изабрана понављања
    .accesskey = о
button-multiple-occurrence-delete =
    .label = Обриши само изабрана понављања
    .accesskey = о
button-multiple-occurrence-edit =
    .label = Уреди само изабрана понављања
    .accesskey = о
button-single-allfollowing-copy =
    .label = Копирај ово и сва будућа понављања
    .accesskey = а
button-single-allfollowing-cut =
    .label = Исеци ово и сва будућа понављања
    .accesskey = а
button-single-allfollowing-delete =
    .label = Обриши ово и сва будућа понављања
    .accesskey = а
button-single-allfollowing-edit =
    .label = Уреди ово и сва будућа понављања
    .accesskey = а
button-multiple-allfollowing-copy =
    .label = Копирај изабрано и сва будућа понављања
    .accesskey = а
button-multiple-allfollowing-cut =
    .label = Исеци изабрано и сва будућа понављања
    .accesskey = а
button-multiple-allfollowing-delete =
    .label = Обриши изабрано и сва будућа понављања
    .accesskey = а
button-multiple-allfollowing-edit =
    .label = Уреди изабрано и сва будућа понављања
    .accesskey = а
button-single-parent-copy =
    .label = Копирај сва понављања
    .accesskey = р
button-single-parent-cut =
    .label = Исеци сва понављања
    .accesskey = р
button-single-parent-delete =
    .label = Обриши сва понављања
    .accesskey = р
button-single-parent-edit =
    .label = Уреди сва понављања
    .accesskey = р
button-multiple-parent-copy =
    .label = Копирај сва понављања изабраних ставки
    .accesskey = р
button-multiple-parent-cut =
    .label = Исеци сва понављања изабраних ставки
    .accesskey = р
button-multiple-parent-delete =
    .label = Обриши сва понављања изабраних ставки
    .accesskey = р
button-multiple-parent-edit =
    .label = Уреди сва понављања изабраних ставки
    .accesskey = р
buttons-single-occurrence-copy =
    .label = Копирај само ово понављање
buttons-single-occurrence-cut =
    .label = Исеци само ово понављање
buttons-single-occurrence-delete =
    .label = Обриши само ово понављање
buttons-single-occurrence-edit =
    .label = Уреди само ово понављање
buttons-multiple-occurrence-copy =
    .label = Копирај само изабрана понављања
buttons-multiple-occurrence-cut =
    .label = Исеци само изабрана понављања
buttons-multiple-occurrence-delete =
    .label = Обриши само изабрана понављања
buttons-multiple-occurrence-edit =
    .label = Уреди само изабрана понављања
buttons-single-allfollowing-copy =
    .label = Копирај ово и сва будућа понављања
buttons-single-allfollowing-cut =
    .label = Исеци ово и сва будућа понављања
buttons-single-allfollowing-delete =
    .label = Обриши ово и сва будућа понављања
buttons-single-allfollowing-edit =
    .label = Уреди ово и сва будућа понављања
buttons-multiple-allfollowing-copy =
    .label = Копирај изабрано и сва будућа понављања
buttons-multiple-allfollowing-cut =
    .label = Исеци изабрано и сва будућа понављања
buttons-multiple-allfollowing-delete =
    .label = Обриши изабрано и сва будућа понављања
buttons-multiple-allfollowing-edit =
    .label = Уреди изабрано и сва будућа понављања
buttons-single-parent-copy =
    .label = Копирај сва понављања
buttons-single-parent-cut =
    .label = Исеци сва понављања
buttons-single-parent-delete =
    .label = Обриши сва понављања
buttons-single-parent-edit =
    .label = Уреди сва понављања
buttons-multiple-parent-copy =
    .label = Копирај сва понављања изабраних ставки
buttons-multiple-parent-cut =
    .label = Исеци сва понављања изабраних ставки
buttons-multiple-parent-delete =
    .label = Обриши сва понављања изабраних ставки
buttons-multiple-parent-edit =
    .label = Уреди сва понављања изабраних ставки
