# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Selecionar todas
select-none-calendars = Não selecionar nenhuma
calendar-creation-wizard-title = Criar nova agenda
calendar-creation-initial-description = Sua agenda pode ser armazenada no seu computador, ou em um servidor para poder acessar remotamente e compartilhar com seus colegas ou amigos.
calendar-creation-initial-computer =
    .label = No meu computador
calendar-creation-initial-network =
    .label = Na rede
calendar-creation-username =
    .value = Nome de usuário:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Criar agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Voltar
    .buttonaccesskeyextra2 = V
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Criar agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Voltar
    .buttonaccesskeyextra2 = V
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Procurar agendas
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Voltar
    .buttonaccesskeyextra2 = V
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Inscrever
    .buttonaccesskeyaccept = I
    .buttonlabelextra2 = Voltar
    .buttonaccesskeyextra2 = V
calendar-creation-type =
    .value = Tipo de agenda:
calendar-creation-location =
    .value = Local:
calendar-creation-location-placeholder =
    .placeholder = URL ou nome de host do servidor da agenda
    .default-placeholder = URL ou nome de host do servidor da agenda
calendar-creation-network-nocredentials =
    .label = Este local não requer credenciais
calendar-creation-network-loading = Aguarde enquanto suas agendas estão sendo descobertas.
calendar-creation-network-notfound = Não foi possível encontrar agendas neste local. Verifique suas configurações.
calendar-creation-network-authfail = As credenciais que você inseriu não foram aceitas. Verifique suas configurações.
calendar-creation-network-certerror = Não foi possível encontrar agendas neste local devido a um problema de certificado.
calendar-creation-network-subscribe-single = Selecione as agendas em que quer se inscrever.
calendar-creation-network-subscribe-multiple = Vários tipos de agenda estão disponíveis neste local. Selecione um tipo, depois marque as agendas em que quer se inscrever.
