# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (dailyEveryNth):
# Edit recurrence window -> Recurrence pattern -> Daily repeat rules
##1 - number
# e.g. "every 4 days"
dailyEveryNth = katru #1. dienu;katru dienu;katru #1. dienu
repeatDetailsRuleDaily4 = katru darba dienu
repeatDetailsDay2 = Pirmdiena
# LOCALIZATION NOTE (repeatDetailsAnd)
# Used to show a number of weekdays in a list
# i.e. "Sunday, Monday, Tuesday " + and + " Wednesday"
repeatDetailsAnd = un
repeatDetailsMonth1 = Janvāris
repeatDetailsMonth2 = Februāris
repeatDetailsMonth3 = Marts
repeatDetailsMonth4 = Aprīlis
repeatDetailsMonth5 = Maijs
repeatDetailsMonth6 = Jūnijs
repeatDetailsMonth7 = Jūlijs
repeatDetailsMonth8 = Augusts
repeatDetailsMonth9 = Septembris
repeatDetailsMonth10 = Oktobris
repeatDetailsMonth11 = Novembris
repeatDetailsMonth12 = Decembris
# LOCALIZATION NOTE (repeatDetailsInfiniteAllDay):
# Edit recurrence window -> Recurrence details link on Event/Task dialog window
# %1%$ - A rule string (see above). This is the first line of the link
# %2%$ - event start date (e.g. mm/gg/yyyy)
# e.g. with monthlyDaysOfNth and all day event:
# "Occurs day 3 of every 5 month
#  effective 1/1/2009"
repeatDetailsInfiniteAllDay = Notiek %1$S\nspēkā no %2$S.
# LOCALIZATION NOTE (monthlyLastDay):
# Edit recurrence window -> Recurrence details link on Event/Task dialog window
# A monthly rule with one or more days of the month (monthlyDaysOfNth) and the
# string "the last day" of the month.
# e.g.: "Occurs day 15, 20, 25 and the last day of every 3 months"
monthlyLastDay = pēdējā diena
# LOCALIZATION NOTE (ruleTooComplex):
# This string is shown in the repeat details area if our code can't handle the
# complexity of the recurrence rule yet.
ruleTooComplex = Klikšķināt šeit, lai iegūtu papildu informāciju
# LOCALIZATION NOTE (ruleTooComplexSummary):
# This string is shown in the event summary dialog if our code can't handle the
# complexity of the recurrence rule yet.
ruleTooComplexSummary = Atkārtošanās informācija nav zināma
# differences between the dialog for an Event or a Task
newEvent = Jauns notikums
newTask = Jauns uzdevums
itemMenuLabelEvent = Notikums
itemMenuLabelTask = Uzdevums
removeCalendarsTitle = Noņemt pielikumus
# LOCALIZATION NOTE (eventRecurrenceMonthlyLastDayLabel):
# Edit dialog recurrence -> Monthly Recurrence pattern -> Monthly daypicker
# The label on the monthly daypicker's last button that allows to select
# the last day of the month inside a BYMONTHDAY rule.
eventRecurrenceMonthlyLastDayLabel = Pēdējā diena
# LOCALIZATION NOTE (saveandsendMenuLabel) - this is a runtime replacement for
# event.menu.item.save.label in the event dialog/tab toolbar if attendees
# will be notified on saving
saveandsendMenuLabel = Saglabāt un nosūtīt
# LOCALIZATION NOTE (sendandcloseMenuLabel) - this is a runtime replacement for
# event.menu.item.saveandclose.label in the event dialog/tab toolbar if attendees
# will be notified on saving
sendandcloseMenuLabel = Nosūtīt un aizvērt
# LOCALIZATION NOTE (attendeesTabLabel) - this is a runtime replacement for
# event.attendees.label defined in calendar-event-dialog.dtd and used in the
# event dialog/tab as attendee tab label if an event has at least one attendee
# %1$S - the number of attendee (1-n)
attendeesTabLabel = Dalībnieki (%1$S):
# LOCALIZATION NOTE (attachmentsTabLabel) - this is a runtime replacement for
# event.attachments.label defined in calendar-event-dialog.dtd and used in the
# event dialog/tab as attendee tab label if an event has at least one attachment
# %1$S - the number of attachments (1-n)
attachmentsTabLabel = Pielikumi (%1$S):
