# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header.isrepeating.event.label = ir notikums, kas atkārtojas
header.isrepeating.task.label = ir uzdevums, kas atkārtojas
header.containsrepeating.event.label = satur notikumus, kas atkārtojas
header.containsrepeating.task.label = satur uzdevumus, kas atkārtojas
header.containsrepeating.mixed.label = satur dažāda veida vienumus, kas atkārtojas
windowtitle.multipleitems = Atlasītie vienumi
