# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (dailyEveryNth):
# Edit recurrence window -> Recurrence pattern -> Daily repeat rules
##1 - number
# e.g. "every 4 days"
dailyEveryNth = katru #1. dienu;katru dienu;katru #1. dienu
repeatDetailsRuleDaily4 = katru darba dienu
repeatDetailsDay2 = Pirmdiena
# LOCALIZATION NOTE (repeatDetailsAnd)
# Used to show a number of weekdays in a list
# i.e. "Sunday, Monday, Tuesday " + and + " Wednesday"
repeatDetailsAnd = un
# LOCALIZATION NOTE (ordinalWeekdayOrder):
# Edit recurrence window -> Recurrence pattern -> Monthly repeat rules
# This string allows to change the order of the elements "ordinal" and
# "weekday" (or to insert a word between them) for the argument %1$S of the
# string monthlyRuleNthOfEveryNounclass...
# Without changing this string, the order is that one required from most
# languages: ordinal + weekday (e.g. "'the first' 'Monday' of every 2 months").
# %1$S - ordinal with article
# %2$S - weekday noun
# e.g. "'the first' 'Monday'"
# DONT_TRANSLATE: Make sure there are no extra words in this property, just variables.
ordinalWeekdayOrder = %1$S %2$S
# LOCALIZATION NOTE (repeatOrdinal...Nounclass...):
# Ordinal numbers nouns for every noun class (grammatical genders) of weekdays
# considered in 'repeatDetailsDayxNounclass' strings. For languages that need
# localization according to genders or noun classes.
# Nounclass1 <-> Masculine gender; Nounclass2 <-> Feminine gender.
# Add 'repeatOrdinal...Nounclass' strings with suffix 3, 4 and so on for
# languages with more than two noun classes for weekdays. In this case
# must be added corresponding rule strings with 'Nounclass...' suffix and
# corresponding values "nounclass..." must be written in
# 'repeatDetailsDayxNounclass' strings.
repeatOrdinal1Nounclass1 = pirmais
repeatOrdinal2Nounclass1 = otrais
repeatOrdinal3Nounclass1 = trešais
repeatOrdinal4Nounclass1 = ceturtais
repeatOrdinal5Nounclass1 = piektais
repeatOrdinal-1Nounclass1 = pēdējais
repeatOrdinal1Nounclass2 = pirmā
repeatOrdinal2Nounclass2 = otrā
repeatOrdinal3Nounclass2 = trešā
repeatOrdinal4Nounclass2 = ceturtā
repeatOrdinal5Nounclass2 = piektā
repeatOrdinal-1Nounclass2 = pēdējā
repeatDetailsMonth1 = Janvāris
repeatDetailsMonth2 = Februāris
repeatDetailsMonth3 = Marts
repeatDetailsMonth4 = Aprīlis
repeatDetailsMonth5 = Maijs
repeatDetailsMonth6 = Jūnijs
repeatDetailsMonth7 = Jūlijs
repeatDetailsMonth8 = Augusts
repeatDetailsMonth9 = Septembris
repeatDetailsMonth10 = Oktobris
repeatDetailsMonth11 = Novembris
repeatDetailsMonth12 = Decembris
# LOCALIZATION NOTE (repeatDetailsInfiniteAllDay):
# Edit recurrence window -> Recurrence details link on Event/Task dialog window
# %1%$ - A rule string (see above). This is the first line of the link
# %2%$ - event start date (e.g. mm/gg/yyyy)
# e.g. with monthlyDaysOfNth and all day event:
# "Occurs day 3 of every 5 month
#  effective 1/1/2009"
repeatDetailsInfiniteAllDay = Notiek %1$S\nspēkā no %2$S.
# LOCALIZATION NOTE (monthlyLastDay):
# Edit recurrence window -> Recurrence details link on Event/Task dialog window
# A monthly rule with one or more days of the month (monthlyDaysOfNth) and the
# string "the last day" of the month.
# e.g.: "Occurs day 15, 20, 25 and the last day of every 3 months"
monthlyLastDay = pēdējā diena
# LOCALIZATION NOTE (ruleTooComplex):
# This string is shown in the repeat details area if our code can't handle the
# complexity of the recurrence rule yet.
ruleTooComplex = Klikšķināt šeit, lai iegūtu papildu informāciju
# LOCALIZATION NOTE (ruleTooComplexSummary):
# This string is shown in the event summary dialog if our code can't handle the
# complexity of the recurrence rule yet.
ruleTooComplexSummary = Atkārtošanās informācija nav zināma
# differences between the dialog for an Event or a Task
newEvent = Jauns notikums
newTask = Jauns uzdevums
itemMenuLabelEvent = Notikums
itemMenuLabelTask = Uzdevums
emailSubjectReply = Atb.: %1$S
# Link Location Dialog
specifyLinkLocation = Lūgums norādīt saites atrašanās vietu
enterLinkLocation = Jāievada tīmekļa lapas vai dokumenta atrašanās vieta.
selectAFile = Lūgums atlasīt datni(es), ko pievienot
removeCalendarsTitle = Noņemt pielikumus
# Recurrence Dialog Widget Order
# LOCALIZATION NOTE: You can change the order of below params
# Edit recurrence window -> Recurrence pattern -> Repeat monthly
# %1$S - ordinal with article, %2$S - weekday
# e.g. "the First Saturday"
# DONT_TRANSLATE: Make sure there are no extra words in this property, just variables.
monthlyOrder = %1$S %2$S
# LOCALIZATION NOTE (eventRecurrenceMonthlyLastDayLabel):
# Edit dialog recurrence -> Monthly Recurrence pattern -> Monthly daypicker
# The label on the monthly daypicker's last button that allows to select
# the last day of the month inside a BYMONTHDAY rule.
eventRecurrenceMonthlyLastDayLabel = Pēdējā diena
# LOCALIZATION NOTE (saveandsendButtonLabel) - this is a runtime replacement for
# event.toolbar.save.label2 in the event dialog/tab toolbar if attendees
# will be notified on saving
saveandsendButtonLabel = Saglabāt un nosūtīt
# LOCALIZATION NOTE (saveandsendButtonTooltip) - this is a runtime replacement
# for event.toolbar.save.tooltip2 in the event dialog/tab toolbar if attendees
# will be notified on saving
saveandsendButtonTooltip = Saglabāt un paziņot dalībniekiem
# LOCALIZATION NOTE (saveandsendMenuLabel) - this is a runtime replacement for
# event.menu.item.save.label in the event dialog/tab toolbar if attendees
# will be notified on saving
saveandsendMenuLabel = Saglabāt un nosūtīt
# LOCALIZATION NOTE (sendandcloseMenuLabel) - this is a runtime replacement for
# event.menu.item.saveandclose.label in the event dialog/tab toolbar if attendees
# will be notified on saving
sendandcloseMenuLabel = Nosūtīt un aizvērt
# LOCALIZATION NOTE (attendeesTabLabel) - this is a runtime replacement for
# event.attendees.label defined in calendar-event-dialog.dtd and used in the
# event dialog/tab as attendee tab label if an event has at least one attendee
# %1$S - the number of attendee (1-n)
attendeesTabLabel = Dalībnieki (%1$S):
# LOCALIZATION NOTE (attachmentsTabLabel) - this is a runtime replacement for
# event.attachments.label defined in calendar-event-dialog.dtd and used in the
# event dialog/tab as attendee tab label if an event has at least one attachment
# %1$S - the number of attachments (1-n)
attachmentsTabLabel = Pielikumi (%1$S):
