# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

repeatDetailsDay2 = Pirmdiena
# LOCALIZATION NOTE (repeatDetailsAnd)
# Used to show a number of weekdays in a list
# i.e. "Sunday, Monday, Tuesday " + and + " Wednesday"
repeatDetailsAnd = un
repeatDetailsMonth1 = Janvāris
repeatDetailsMonth2 = Februāris
repeatDetailsMonth3 = Marts
repeatDetailsMonth4 = Aprīlis
repeatDetailsMonth5 = Maijs
repeatDetailsMonth6 = Jūnijs
repeatDetailsMonth7 = Jūlijs
repeatDetailsMonth8 = Augusts
repeatDetailsMonth9 = Septembris
# LOCALIZATION NOTE (repeatDetailsInfiniteAllDay):
# Edit recurrence window -> Recurrence details link on Event/Task dialog window
# %1%$ - A rule string (see above). This is the first line of the link
# %2%$ - event start date (e.g. mm/gg/yyyy)
# e.g. with monthlyDaysOfNth and all day event:
# "Occurs day 3 of every 5 month
#  effective 1/1/2009"
repeatDetailsInfiniteAllDay = Notiek %1$S\nspēkā no %2$S.
# LOCALIZATION NOTE (ruleTooComplex):
# This string is shown in the repeat details area if our code can't handle the
# complexity of the recurrence rule yet.
ruleTooComplex = Klikšķināt šeit, lai iegūtu papildu informāciju
# differences between the dialog for an Event or a Task
newEvent = Jauns notikums
newTask = Jauns uzdevums
itemMenuLabelEvent = Notikums
