# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

month.10.name = Oktobris
month.11.name = Novembris
month.12.name = Decembris
# LOCALIZATION NOTE (month.*.genitive):
# Some languages require different declensions of month names.
# These values will be used if *.monthFormat is set to "genitive"
# If your language doesn't use different declensions, just set the same
# values as for month.*.name.
month.1.genitive = Janvāris
month.2.genitive = Februāris
month.3.genitive = Marts
month.4.genitive = Aprīlis
month.5.genitive = Maijs
month.6.genitive = Jūnijs
month.7.genitive = Jūlijs
month.8.genitive = Augusts
month.9.genitive = Septembris
month.10.genitive = Oktobris
month.11.genitive = Novembris
month.12.genitive = Decembris
midnight = Pusnakts
