# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Spam Settings
dialog-header-title =
    .value = Spam Settings
training-description-spam = If enabled, you must first train { -brand-short-name } to identify spam by using the Spam toolbar button to mark messages as spam or not. You need to identify both spam and non spam messages. After that { -brand-short-name } will be able to mark spam automatically.
spam-level-checkbox =
    .label = Enable adaptive spam controls for this account
    .accesskey = E
move-spam-message-menuitem =
    .label = Move new spam messages to:
    .accesskey = M
set-spam-folder-menuitem =
    .label = “Spam” folder on:
    .accesskey = S
move-message-other =
    .label = Other:
    .accesskey = O
automatic-spam-purge-checkbox =
    .label = Automatically delete spam older than
    .accesskey = u
automatic-spam-purge-label =
    .value = days
trust-addresses-header-label =
    .value = Trust email addresses in these address books:
    .accesskey = d
allowlist-header-label =
    .value = Do not automatically mark mail as spam if the sender is in:
    .accesskey = D
isp-headers-checkbox =
    .label = Trust spam headers set by:
    .accesskey = T
isp-warning-description = If enabled, { -brand-short-name } will automatically consider messages marked by this external classifier as spam.
spam-detecting-legend = Detecting spam
spam-storage-deletion-legend = Storage and deletion
spam-classification-legend = Selection
spam-actions-legend = Destination and Retention
global-spam-preferences-button =
    .label = Global Spam Settings…
    .accesskey = G
manage-spam-title = Manage spam
manage-spam-header =
    .value = Manage spam
training-description-learns = When turned on, { -brand-short-name } learns from the messages you mark as spam or not spam. The more you train it, the better { -brand-short-name } gets at detecting spam.
spam-auto-detection-checkbox =
    .label = Turn on automatic spam detection for this account
    .accesskey = e
