# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Offline Settings
autodetect-connection-label =
    .label = Automatically switch modes when an internet connection is found
    .accesskey = d
offline-startup-label = When opening { -brand-short-name }:
status-radio-last-used =
    .label = Use the last-used connection mode
    .accesskey = U
status-radio-ask-connect =
    .label = Ask whether to connect online
    .accesskey = k
status-radio-start-online =
    .label = Start online
    .accesskey = l
status-radio-start-offline =
    .label = Start offline
    .accesskey = f
going-online-prompt = Send messages waiting in your Outbox
going-online-send =
    .label = Yes, send automatically
    .accesskey = Y
going-online-keep =
    .label = No, keep in Outbox
    .accesskey = N
going-online-ask-send =
    .label = Ask before sending
    .accesskey = s
going-offline-prompt = Do you want to download messages to read offline?
going-offline-download =
    .label = Yes, download automatically
    .accesskey = e
going-offline-keep =
    .label = No, do not download
    .accesskey = o
going-offline-ask-download =
    .label = Ask before downloading
    .accesskey = A
autodetect-online-label =
    .label = Automatically follow detected online state
    .accesskey = d
offline-preference-startup-label = Manual state when starting up:
status-radio-remember =
    .label = Remember previous online state
    .accesskey = R
status-radio-ask =
    .label = Ask me for online state
    .accesskey = k
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Send unsent messages when going online?
going-online-auto =
    .label = Yes
    .accesskey = Y
going-online-not =
    .label = No
    .accesskey = N
going-online-ask =
    .label = Ask me
    .accesskey = s
going-offline-label = Download messages for offline use when going offline?
going-offline-auto =
    .label = Yes
    .accesskey = e
going-offline-not =
    .label = No
    .accesskey = o
going-offline-ask =
    .label = Ask me
    .accesskey = A
