# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Return Receipts
return-receipt-checkbox-control =
    .label = When sending messages, always request a return receipt
    .accesskey = W
receipt-arrive-label = When a receipt arrives:
receipt-leave-inbox-control =
    .label = Leave in Inbox
    .accesskey = i
receipt-move-sent-control =
    .label = Move to Sent folder
    .accesskey = M
receipt-sender-request-label = When a sender requests a return receipt:
receipt-leave-radio-control =
    .label = Leave it in my Inbox
    .accesskey = i
receipt-move-radio-control =
    .label = Move it to my “Sent” folder
    .accesskey = m
receipt-request-label = When I receive a request for a return receipt:
receipt-return-never-radio-control =
    .label = Never send a return receipt
    .accesskey = n
receipt-return-some-radio-control =
    .label = Allow return receipts for some messages
    .accesskey = r
receipt-not-listed-cc-label =
    .value = If not listed in To or CC field:
    .accesskey = f
receipt-not-to-cc-label =
    .value = If I’m not in the To or Cc of the message:
    .accesskey = f
receipt-send-never-label =
    .label = Never send
receipt-send-always-label =
    .label = Always send
receipt-send-ask-label =
    .label = Ask me
sender-outside-company-label =
    .value = If sender is outside company or domain:
    .accesskey = t
sender-outside-domain-label =
    .value = If the sender is outside my domain:
    .accesskey = t
other-cases-text-label =
    .value = In all other cases:
    .accesskey = a
read-receipts-dialog-title = Read receipts
return-receipt-request-control =
    .label = Always request a return receipt when sending emails
    .accesskey = w
