# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Ευέλικτο διάστημα
search-bar-label = Αναζήτηση
toolbar-write-message-label = Σύνταξη
toolbar-write-message =
    .title = Δημιουργία νέου μηνύματος
toolbar-move-to =
    .title = Μετακίνηση επιλεγμένου μηνύματος
toolbar-unifinder-label = Εύρεση εκδηλώσεων
toolbar-unifinder =
    .title = Εναλλαγή παραθύρου εύρεσης εκδηλώσεων
toolbar-folder-location-label = Τοποθεσία φακέλου
toolbar-edit-event-label = Επεξεργασία
toolbar-edit-event =
    .title = Επεξεργασία επιλεγμένης εκδήλωσης ή εργασίας
toolbar-get-messages-label = Λήψη μηνυμάτων
toolbar-get-messages =
    .title = Λήψη νέων μηνυμάτων για όλους τους λογαριασμούς
toolbar-reply-label = Απάντηση
toolbar-reply =
    .title = Απάντηση στο μήνυμα
toolbar-reply-all-label = Απάντηση σε όλους
toolbar-reply-all =
    .title = Απάντηση στον αποστολέα και σε όλους τους παραλήπτες
toolbar-reply-to-list-label = Απάντηση στη λίστα
toolbar-reply-to-list =
    .title = Απάντηση στη λίστα αλληλογραφίας
toolbar-redirect-label = Ανακατεύθυνση
toolbar-redirect =
    .title = Ανακατεύθυνση επιλεγμένου μηνύματος
toolbar-archive-label = Αρχειοθέτηση
toolbar-archive =
    .title = Αρχειοθέτηση επιλεγμένων μηνυμάτων
toolbar-conversation-label = Συζήτηση
toolbar-conversation =
    .title = Εμφάνιση συζήτησης για το επιλεγμένο μήνυμα
toolbar-previous-unread-label = Προηγούμενο μη αναγνωσμένο
toolbar-previous-unread =
    .title = Μετάβαση στο προηγούμενο μη αναγνωσμένο
toolbar-previous-label = Προηγούμενο
toolbar-previous =
    .title = Μετάβαση στο προηγούμενο μήνυμα
toolbar-next-unread-label = Επόμενο μη αναγνωσμένο
toolbar-next-unread =
    .title = Μετάβαση στο επόμενο μη αναγνωσμένο μήνυμα
toolbar-next-label = Επόμενο
toolbar-next =
    .title = Μετάβαση στο επόμενο μήνυμα
toolbar-junk-label = Ανεπιθύμητα
toolbar-junk =
    .title = Επισήμανση επιλεγμένων μηνυμάτων ως ανεπιθύμητων
toolbar-delete-label = Διαγραφή
toolbar-delete =
    .title = Διαγραφή επιλεγμένων μηνυμάτων ή φακέλου
toolbar-compact-label = Σύμπτυξη
toolbar-compact =
    .title = Αφαίρεση διαγραμμένων μηνυμάτων από τον επιλεγμένο φάκελο
toolbar-add-as-event-label = Προσθήκη ως εκδήλωση
toolbar-add-as-event =
    .title = Εξαγωγή ημερολογιακών πληροφοριών από το μήνυμα και προσθήκη τους στο ημερολόγιό σας ως εκδήλωση
toolbar-add-as-task-label = Προσθήκη ως εργασία
toolbar-add-as-task =
    .title = Εξαγωγή ημερολογιακών πληροφοριών από το μήνυμα και προσθήκη τους στο ημερολόγιό σας ως εργασία
toolbar-tag-message-label = Ετικέτα
toolbar-tag-message =
    .title = Ετικέτα σε μηνύματα
toolbar-forward-inline-label = Προώθηση
toolbar-forward-inline =
    .title = Προώθηση επιλεγμένου μηνύματος ως ενσωματωμένου κειμένου
toolbar-forward-attachment-label = Προώθηση ως συνημμένο
toolbar-forward-attachment =
    .title = Προώθηση επιλεγμένου μηνύματος ως συνημμένου
toolbar-mark-as-label = Επισήμανση
toolbar-mark-as =
    .title = Επισήμανση μηνυμάτων
toolbar-view-picker-label = Προβολή
toolbar-address-book =
    .title = Μετάβαση στο ευρετήριο
toolbar-chat-label = Συνομιλία
toolbar-chat =
    .title = Εμφάνιση καρτέλας «Συνομιλία»
toolbar-add-ons-and-themes-label = Πρόσθετα και θέματα
toolbar-add-ons-and-themes =
    .title = Διαχείριση των προσθέτων σας
toolbar-calendar-label = Ημερολόγιο
toolbar-calendar =
    .title = Μετάβαση στην καρτέλα ημερολογίου
toolbar-tasks-label = Εργασίες
toolbar-tasks =
    .title = Μετάβαση στην καρτέλα εργασιών
toolbar-mail-label = Αλληλογραφία
toolbar-print-label = Εκτύπωση
toolbar-print =
    .title = Εκτύπωση μηνύματος
toolbar-quick-filter-bar-label = Γρήγορο φιλτράρισμα
toolbar-quick-filter-bar =
    .title = Φιλτράρισμα μηνυμάτων
