# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Ευέλικτο διάστημα
search-bar-label = Αναζήτηση
toolbar-write-message-label = Σύνταξη
toolbar-write-message =
    .title = Δημιουργία νέου μηνύματος
toolbar-move-to-label = Μετακίνηση σε
toolbar-move-to =
    .title = Μετακίνηση επιλεγμένου μηνύματος
toolbar-unifinder-label = Εύρεση εκδηλώσεων
toolbar-unifinder =
    .title = Εναλλαγή παραθύρου εύρεσης εκδηλώσεων
toolbar-folder-location-label = Τοποθεσία φακέλου
toolbar-folder-location =
    .title = Εναλλαγή στον φάκελο
toolbar-edit-event-label = Επεξεργασία
toolbar-edit-event =
    .title = Επεξεργασία επιλεγμένης εκδήλωσης ή εργασίας
toolbar-get-messages-label = Λήψη μηνυμάτων
toolbar-get-messages =
    .title = Λήψη νέων μηνυμάτων για όλους τους λογαριασμούς
toolbar-reply-label = Απάντηση
toolbar-reply =
    .title = Απάντηση στο μήνυμα
toolbar-reply-all-label = Απάντηση σε όλους
toolbar-reply-all =
    .title = Απάντηση στον αποστολέα και σε όλους τους παραλήπτες
toolbar-reply-to-list-label = Απάντηση στη λίστα
toolbar-reply-to-list =
    .title = Απάντηση στη λίστα αλληλογραφίας
toolbar-redirect-label = Ανακατεύθυνση
toolbar-redirect =
    .title = Ανακατεύθυνση επιλεγμένου μηνύματος
toolbar-archive-label = Αρχειοθέτηση
toolbar-archive =
    .title = Αρχειοθέτηση επιλεγμένων μηνυμάτων
toolbar-conversation-label = Συζήτηση
toolbar-conversation =
    .title = Εμφάνιση συζήτησης για το επιλεγμένο μήνυμα
toolbar-previous-unread-label = Προηγούμενο μη αναγνωσμένο
toolbar-previous-unread =
    .title = Μετάβαση στο προηγούμενο μη αναγνωσμένο
toolbar-previous-label = Προηγούμενο
toolbar-previous =
    .title = Μετάβαση στο προηγούμενο μήνυμα
toolbar-next-unread-label = Επόμενο μη αναγνωσμένο
toolbar-next-unread =
    .title = Μετάβαση στο επόμενο μη αναγνωσμένο μήνυμα
toolbar-next-label = Επόμενο
toolbar-next =
    .title = Μετάβαση στο επόμενο μήνυμα
toolbar-junk-label = Ανεπιθύμητα
toolbar-junk =
    .title = Επισήμανση επιλεγμένων μηνυμάτων ως ανεπιθύμητων
toolbar-delete-label = Διαγραφή
toolbar-delete-title =
    .title = Διαγραφή επιλεγμένων μηνυμάτων
toolbar-undelete-label = Αναίρεση διαγραφής
toolbar-undelete =
    .title = Επαναφορά επιλεγμένων μηνυμάτων
toolbar-compact-label = Σύμπτυξη
toolbar-compact =
    .title = Αφαίρεση διαγραμμένων μηνυμάτων από τον επιλεγμένο φάκελο
toolbar-add-as-event-label = Προσθήκη ως εκδήλωση
toolbar-add-as-event =
    .title = Εξαγωγή ημερολογιακών πληροφοριών από το μήνυμα και προσθήκη τους στο ημερολόγιό σας ως εκδήλωση
toolbar-add-as-task-label = Προσθήκη ως εργασία
toolbar-add-as-task =
    .title = Εξαγωγή ημερολογιακών πληροφοριών από το μήνυμα και προσθήκη τους στο ημερολόγιό σας ως εργασία
toolbar-tag-message-label = Ετικέτα
toolbar-tag-message =
    .title = Ετικέτα σε μηνύματα
toolbar-forward-inline-label = Προώθηση
toolbar-forward-inline =
    .title = Προώθηση επιλεγμένου μηνύματος ως ενσωματωμένου κειμένου
toolbar-forward-attachment-label = Προώθηση ως συνημμένο
toolbar-forward-attachment =
    .title = Προώθηση επιλεγμένου μηνύματος ως συνημμένου
toolbar-mark-as-label = Επισήμανση
toolbar-mark-as =
    .title = Επισήμανση μηνυμάτων
toolbar-view-picker-label = Προβολή
toolbar-view-picker =
    .title = Προσαρμογή προβολής τρέχοντος φακέλου
toolbar-address-book-label = Ευρετήριο
toolbar-address-book =
    .title = Μετάβαση στο ευρετήριο
toolbar-chat-label = Συνομιλία
toolbar-chat =
    .title = Εμφάνιση καρτέλας «Συνομιλία»
toolbar-add-ons-and-themes-label = Πρόσθετα και θέματα
toolbar-add-ons-and-themes =
    .title = Διαχείριση των προσθέτων σας
toolbar-calendar-label = Ημερολόγιο
toolbar-calendar =
    .title = Μετάβαση στην καρτέλα ημερολογίου
toolbar-tasks-label = Εργασίες
toolbar-tasks =
    .title = Μετάβαση στην καρτέλα εργασιών
toolbar-mail-label = Αλληλογραφία
toolbar-mail =
    .title = Εναλλαγή στην καρτέλα αλληλογραφίας
toolbar-print-label = Εκτύπωση
toolbar-print =
    .title = Εκτύπωση μηνύματος
toolbar-quick-filter-bar-label = Γρήγορο φιλτράρισμα
toolbar-quick-filter-bar =
    .title = Φιλτράρισμα μηνυμάτων
toolbar-synchronize-label = Συγχρονισμός
toolbar-synchronize =
    .title = Ανανέωση ημερολογίων και συγχρονισμός αλλαγών
toolbar-delete-event-label = Διαγραφή
toolbar-delete-event =
    .title = Διαγραφή επιλεγμένων εκδηλώσεων ή εργασιών
toolbar-go-to-today-label = Μετάβαση στο σήμερα
toolbar-go-to-today =
    .title = Μετάβαση στο σήμερα
toolbar-print-event-label = Εκτύπωση
toolbar-print-event =
    .title = Εκτύπωση εκδηλώσεων ή εργασιών
toolbar-new-event-label = Εκδήλωση
toolbar-new-event =
    .title = Δημιουργία νέας εκδήλωσης
toolbar-new-task-label = Εργασία
toolbar-new-task =
    .title = Δημιουργία νέας εργασίας
toolbar-go-back-label = Πίσω
toolbar-go-back =
    .title = Μετάβαση πίσω κατά ένα μήνυμα
toolbar-go-forward-label = Μπροστά
toolbar-go-forward =
    .title = Μετάβαση μπροστά ένα μήνυμα
toolbar-stop-label = Διακοπή
toolbar-stop =
    .title = Διακοπή της τρέχουσας μεταφοράς
toolbar-throbber-label = Επισήμανση ενέργειας
toolbar-throbber =
    .title = Επισήμανση ενέργειας
toolbar-create-contact-label = Νέα επαφή
toolbar-create-contact =
    .title = Δημιουργία νέας επαφής
toolbar-create-address-book-label = Νέο ευρετήριο
toolbar-create-address-book =
    .title = Δημιουργία νέου ευρετηρίου
toolbar-create-list-label = Νέα λίστα
toolbar-create-list =
    .title = Δημιουργία νέας λίστας αλληλογραφίας
toolbar-import-contacts-label = Εισαγωγή
toolbar-import-contacts =
    .title = Εισαγωγή επαφών από αρχείο

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Προσθήκη τοπικού ευρετηρίου
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Προσθήκη ευρετηρίου CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Προσθήκη ευρετηρίου LDAP
