# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Ustawienia niechcianej poczty
dialog-header-title =
    .value = Ustawienia niechcianej poczty
training-description-spam = Po włączeniu filtru należy nauczyć program { -brand-short-name } rozpoznawania pożądanych i niepożądanych wiadomości za pomocą przycisku „Niechciana” na pasku narzędzi. Należy odpowiednio oznaczać wiadomości pożądane i niepożądane, dopóki skuteczność automatycznego filtrowania niechcianej poczty nie będzie satysfakcjonująca.
spam-level-checkbox =
    .label = Włącz filtr niechcianej poczty dla bieżącego konta
    .accesskey = W
move-spam-message-menuitem =
    .label = Przenoś otrzymane wiadomości, które zostały oznaczone jako niechciane, do:
    .accesskey = P
set-spam-folder-menuitem =
    .label = folderu „Niechciane” konta:
    .accesskey = N
move-message-other =
    .label = innego folderu:
    .accesskey = f
automatic-spam-purge-checkbox =
    .label = Niechciane wiadomości usuwaj automatycznie po upływie
    .accesskey = u
automatic-spam-purge-label =
    .value = dni
trust-addresses-header-label =
    .value = Zaufaj adresom e-mail w tych książkach adresowych:
    .accesskey = d
allowlist-header-label =
    .value = Nie oznaczaj wiadomości automatycznie jako niechcianej, jeżeli adres nadawcy znajduje się w:
    .accesskey = o
isp-headers-checkbox =
    .label = Ufaj nagłówkom niechcianej poczty ustawionym przez:
    .accesskey = t
isp-warning-description = Gdy zaznaczone, program { -brand-short-name } będzie automatycznie uznawał wiadomości za niechciane na podstawie danych od zewnętrznego dostawcy.
spam-detecting-legend = Wykrywanie niechcianej poczty
spam-storage-deletion-legend = Przechowywanie i usuwanie
spam-classification-legend = Filtrowanie i klasyfikacja
spam-actions-legend = Przenoszenie i przechowywanie
global-spam-preferences-button =
    .label = Globalne ustawienia niechcianej poczty…
    .accesskey = G
manage-spam-title = Zarządzaj niechcianą pocztą
manage-spam-header =
    .value = Zarządzaj niechcianą pocztą
training-description-learns = Gdy opcja jest włączona, program { -brand-short-name } uczy się na podstawie wiadomości, które oznaczasz jako niechcianą pocztę lub nie. Im bardziej go szkolisz, tym lepiej program { -brand-short-name } radzi sobie z niechcianą pocztą.
spam-auto-detection-checkbox =
    .label = Włącz automatyczne wykrywanie niechcianej poczty na tym koncie
    .accesskey = e
