# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Ustawienia trybu offline
autodetect-connection-label =
    .label = Automatycznie przełączaj tryby po wykryciu połączenia internetowego
    .accesskey = r
offline-startup-label = Podczas otwierania programu { -brand-short-name }:
status-radio-last-used =
    .label = użyj ostatnio używanego trybu połączenia
    .accesskey = U
status-radio-ask-connect =
    .label = zapytaj, czy chcesz połączyć się online
    .accesskey = t
status-radio-start-online =
    .label = rozpocznij w trybie online
    .accesskey = e
status-radio-start-offline =
    .label = rozpocznij w trybie offline
    .accesskey = f
going-online-prompt = Wyślij wiadomości ze skrzynki nadawczej
going-online-send =
    .label = Tak, wyślij automatycznie
    .accesskey = T
going-online-keep =
    .label = Nie, zachowaj w skrzynce nadawczej
    .accesskey = N
going-online-ask-send =
    .label = Pytaj przed wysłaniem
    .accesskey = P
going-offline-prompt = Czy chcesz pobrać wiadomości, aby przeczytać je w trybie offline?
going-offline-download =
    .label = Tak, pobierz automatycznie
    .accesskey = a
going-offline-keep =
    .label = Nie, nie pobieraj
    .accesskey = b
going-offline-ask-download =
    .label = Pytaj przed pobraniem
    .accesskey = a
autodetect-online-label =
    .label = Automatycznie wykrywanie stanu połączenia
    .accesskey = A
offline-preference-startup-label = Podczas uruchamiania:
status-radio-remember =
    .label = powracaj do wcześniejszego stanu połączenia
    .accesskey = w
status-radio-ask =
    .label = pytaj, czy łączyć
    .accesskey = c
status-radio-always-online =
    .label = zawsze próbuj połączyć
    .accesskey = z
status-radio-always-offline =
    .label = nie łącz
    .accesskey = n
going-online-label = Czy wysyłać niewysłane wiadomości przy łączeniu?
going-online-auto =
    .label = Tak
    .accesskey = T
going-online-not =
    .label = Nie
    .accesskey = N
going-online-ask =
    .label = Pytaj
    .accesskey = P
going-offline-label = Czy pobierać wiadomości do późniejszego wykorzystania przed rozłączeniem?
going-offline-auto =
    .label = Tak
    .accesskey = k
going-offline-not =
    .label = Nie
    .accesskey = e
going-offline-ask =
    .label = Pytaj
    .accesskey = j
