# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Potwierdzenie doręczenia wiadomości
return-receipt-checkbox-control =
    .label = Zawsze żądaj potwierdzeń doręczenia wysyłanych wiadomości
    .accesskey = Z
receipt-arrive-label = Otrzymane potwierdzenia doręczenia wiadomości:
receipt-leave-inbox-control =
    .label = Zostaw w skrzynce odbiorczej
    .accesskey = i
receipt-move-sent-control =
    .label = Przenieś do folderu Wysłane
    .accesskey = r
receipt-sender-request-label = Gdy nadawca żąda potwierdzenia odbioru:
receipt-leave-radio-control =
    .label = pozostawiaj w folderze Odebrane
    .accesskey = f
receipt-move-radio-control =
    .label = przenoś do folderu Wysłane
    .accesskey = W
receipt-request-label = Po otrzymaniu żądania potwierdzenia doręczenia wiadomości:
receipt-return-never-radio-control =
    .label = Nigdy nie wysyłaj potwierdzeń doręczenia wiadomości
    .accesskey = N
receipt-return-some-radio-control =
    .label = Wysyłaj potwierdzenia doręczenia wiadomości tylko w poniższych przypadkach:
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Jeśli nie jest wymieniony w polu Do lub DW:
    .accesskey = l
receipt-not-to-cc-label =
    .value = Jeśli w polu „Do” lub „Kopia” nie ma mojego adresu e-mail:
    .accesskey = J
receipt-send-never-label =
    .label = Nigdy nie wysyłaj
receipt-send-always-label =
    .label = Zawsze wysyłaj
receipt-send-ask-label =
    .label = Wyświetlaj pytanie
sender-outside-company-label =
    .value = Jeżeli nadawca jest spoza firmy lub domeny:
    .accesskey = d
sender-outside-domain-label =
    .value = Jeżeli nadawca jest spoza mojej domeny:
    .accesskey = t
other-cases-text-label =
    .value = W innych przypadkach:
    .accesskey = a
read-receipts-dialog-title = Potwierdzenia przeczytania
return-receipt-request-control =
    .label = Zawsze żądaj potwierdzenia odbioru wysyłanych wiadomości e-mail
    .accesskey = w
