# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Kommentar
calendar-item-summary-title = Tittel:
calendar-item-summary-calendar = Kalender:
calendar-item-summary-task-start = Startdato:
calendar-item-summary-event-start = Startdato:
calendar-item-summary-task-due = Innan:
calendar-item-summary-event-end = Sluttdato:
calendar-item-summary-repeat = Repeter:
calendar-item-summary-location = Stad:
calendar-item-summary-category = Kategori:
calendar-item-summary-organizer = Organisert av:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Påminning:
calendar-item-summary-attachments = Vedlegg:
calendar-item-summary-status-tentative = Med atterhald
calendar-item-summary-status-confirmed = Stadfesta
calendar-item-summary-event-status-cancelled = Avlyst
calendar-item-summary-todo-status-cancelled = Avlyst
calendar-item-summary-status-needs-action = Treng handling
calendar-item-summary-status-in-process = Under arbeid
calendar-item-summary-status-completed = Fullført
calendar-item-summary-reminder-none =
    .label = Inga påminning
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutt før
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutt før
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutt før
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutt før
calendar-item-summary-reminder-1-hour-before =
    .label = 1 time før
calendar-item-summary-reminder-2-hours-before =
    .label = 2 timar før
calendar-item-summary-reminder-12-hours-before =
    .label = 12 timar før
calendar-item-summary-reminder-1-day-before =
    .label = 1 dag før
calendar-item-summary-reminder-2-days-before =
    .label = 2 dagar før
calendar-item-summary-reminder-1-week-before =
    .label = 1 veke før
calendar-item-summary-reminder-custom =
    .label = Tilpassa…
calendar-item-summary-reminder-multiple =
    .value = Fleire påminningar…
calendar-item-summary-general =
    .value = Generelt
calendar-item-summary-attendees =
    .value = Deltakarar
calendar-item-summary-description =
    .value = Skildring
calendar-item-summary-link =
    .value = Relatert lenke
