# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Αναζήτηση…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Βρέθηκε #1 αντιστοιχία;Βρέθηκαν #1 αντιστοιχίες
noMatchesFound = Δεν βρέθηκαν ταιριάσματα
labelForStopButton = Διακοπή
labelForSearchButton = Αναζήτηση
labelForStopButton.accesskey = Δ
labelForSearchButton.accesskey = ζ
moreButtonTooltipText = Προσθήκη νέου κανόνα
lessButtonTooltipText = Αφαίρεση κανόνα
