# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Suchen…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 Übereinstimmung gefunden;#1 Übereinstimmungen gefunden
noMatchesFound = Keine Übereinstimmungen gefunden
labelForStopButton = Stopp
labelForSearchButton = Suchen
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = S
moreButtonTooltipText = Neue Bedingung hinzufügen
lessButtonTooltipText = Diese Bedingung entfernen
