# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espacio flexible
toolbar-write-message-label = Redactar
toolbar-write-message =
    .title = Crear nuevo mensaje
toolbar-unifinder-label = Buscar eventos
toolbar-unifinder =
    .title = Intercambiar vista de búsqueda de eventos
toolbar-folder-location-label = Dirección de la carpeta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar eventos o tareas seleccionadas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder al mensaje
toolbar-reply-all-label = Resp. a todos
toolbar-reply-all =
    .title = Responder al remitente y a todos los destinatarios
toolbar-reply-to-list-label = Responder a lista
toolbar-reply-to-list =
    .title = Responder a lista de correo
toolbar-redirect-label = Redirigir
toolbar-redirect =
    .title = Redirigir el mensaje seleccionado
toolbar-archive-label = Archivar
toolbar-archive =
    .title = Archivar mensajes seleccionados
toolbar-conversation-label = Conversación
toolbar-conversation =
    .title = Mostrar conversación del mensaje seleccionado
toolbar-previous-unread-label = Anterior sin leer
toolbar-previous-unread =
    .title = Ir al anterior mensaje no leído
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Ir al mensaje anterior
toolbar-next-unread-label = Siguiente sin leer
toolbar-next-unread =
    .title = Ir al siguiente mensaje no leído
toolbar-next-label = Siguiente
toolbar-next =
    .title = Ir al siguiente mensaje
toolbar-junk-label = Basura
toolbar-junk =
    .title = Marcar los mensajes seleccionados como basura
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Eliminar mensajes borrados de la carpeta actual
toolbar-add-as-event-label = Agregar como evento
toolbar-add-as-event =
    .title = Extraer información de calendario desde el mensaje y agregarlo como un evento
toolbar-add-as-task-label = Agregar como tarea
toolbar-add-as-task =
    .title = Extraer información de calendario desde el mensaje y agregarlo como una tarea
toolbar-tag-message-label = Etiquetar
toolbar-tag-message =
    .title = Etiquetar mensajes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar mensaje seleccionado como texto incorporado
toolbar-forward-attachment-label = Reenviar como adjunto
toolbar-forward-attachment =
    .title = Reenviar mensaje seleccionado como un adjunto
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensajes
toolbar-address-book =
    .title = Ir a la libreta de direcciones
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mostrar la pestaña de chat
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Cambiar a la pestaña calendario
toolbar-tasks-label = Tareas
toolbar-tasks =
    .title = Cambiar a la pestaña tareas
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir este mensaje
