# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espacio flexible
search-bar-label = Buscar
toolbar-write-message-label = Redactar
toolbar-write-message =
    .title = Crear nuevo mensaje
toolbar-move-to-label = Mover a
toolbar-move-to =
    .title = Mover mensaje seleccionado
toolbar-unifinder-label = Buscar eventos
toolbar-unifinder =
    .title = Intercambiar vista de búsqueda de eventos
toolbar-folder-location-label = Dirección de la carpeta
toolbar-folder-location =
    .title = Cambiar a carpeta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar eventos o tareas seleccionadas
toolbar-get-messages-label = Obtener mensajes
toolbar-get-messages =
    .title = Descargar nuevos mensajes para todas las cuentas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder al mensaje
toolbar-reply-all-label = Resp. a todos
toolbar-reply-all =
    .title = Responder al remitente y a todos los destinatarios
toolbar-reply-to-list-label = Responder a lista
toolbar-reply-to-list =
    .title = Responder a lista de correo
toolbar-redirect-label = Redirigir
toolbar-redirect =
    .title = Redirigir el mensaje seleccionado
toolbar-archive-label = Archivar
toolbar-archive =
    .title = Archivar mensajes seleccionados
toolbar-conversation-label = Conversación
toolbar-conversation =
    .title = Mostrar conversación del mensaje seleccionado
toolbar-previous-unread-label = Anterior sin leer
toolbar-previous-unread =
    .title = Ir al anterior mensaje no leído
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Ir al mensaje anterior
toolbar-next-unread-label = Siguiente sin leer
toolbar-next-unread =
    .title = Ir al siguiente mensaje no leído
toolbar-next-label = Siguiente
toolbar-next =
    .title = Ir al siguiente mensaje
toolbar-junk-label = Basura
toolbar-junk =
    .title = Marcar los mensajes seleccionados como basura
toolbar-delete-label = Borrar
toolbar-delete-title =
    .title = Eliminar los mensajes seleccionados
toolbar-undelete-label = Recuperar
toolbar-undelete =
    .title = Recuperar los mensajes seleccionados
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Eliminar mensajes borrados de la carpeta actual
toolbar-add-as-event-label = Agregar como evento
toolbar-add-as-event =
    .title = Extraer información de calendario desde el mensaje y agregarlo como un evento
toolbar-add-as-task-label = Agregar como tarea
toolbar-add-as-task =
    .title = Extraer información de calendario desde el mensaje y agregarlo como una tarea
toolbar-tag-message-label = Etiquetar
toolbar-tag-message =
    .title = Etiquetar mensajes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar mensaje seleccionado como texto incorporado
toolbar-forward-attachment-label = Reenviar como adjunto
toolbar-forward-attachment =
    .title = Reenviar mensaje seleccionado como un adjunto
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensajes
toolbar-view-picker-label = Ver
toolbar-view-picker =
    .title = Personalizar vista de la carpeta actual
toolbar-address-book-label = Libreta de direcciones
toolbar-address-book =
    .title = Ir a la libreta de direcciones
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mostrar la pestaña de chat
toolbar-add-ons-and-themes-label = Complementos y temas
toolbar-add-ons-and-themes =
    .title = Administrar los complementos
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Cambiar a la pestaña calendario
toolbar-tasks-label = Tareas
toolbar-tasks =
    .title = Cambiar a la pestaña tareas
toolbar-mail-label = Correo
toolbar-mail =
    .title = Cambiar a la pestaña de correo
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir este mensaje
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensajes
toolbar-synchronize-label = Sincronizar
toolbar-synchronize =
    .title = Recargar calendarios y sincronizar cambios
toolbar-delete-event-label = Borrar
toolbar-delete-event =
    .title = Borrar eventos o tareas seleccionadas
toolbar-go-to-today-label = Ir a hoy
toolbar-go-to-today =
    .title = Ir a hoy
toolbar-print-event-label = Imprimir
toolbar-print-event =
    .title = Imprimir eventos o tareas
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Crear un nuevo evento
toolbar-new-task-label = Tarea
toolbar-new-task =
    .title = Crear una nueva tarea
toolbar-go-back-label = Atrás
toolbar-go-back =
    .title = Retroceder un mensaje
toolbar-go-forward-label = Adelante
toolbar-go-forward =
    .title = Avanzar un mensaje
toolbar-stop-label = Detener
toolbar-stop =
    .title = Detener la transferencia actual
toolbar-throbber-label = Indicador de actividad
toolbar-throbber =
    .title = Indicador de actividad
toolbar-create-contact-label = Nuevo contacto
toolbar-create-contact =
    .title = Crear un nuevo contacto
toolbar-create-address-book-label = Nueva libreta de direcciones
toolbar-create-address-book =
    .title = Crear una nueva libreta de direcciones
toolbar-create-list-label = Nueva lista
toolbar-create-list =
    .title = Crear una nueva lista de correo
toolbar-import-contacts-label = Importar
toolbar-import-contacts =
    .title = Importar contactos desde un archivo

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Agregar libreta de direcciones local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Agregar libreta de direcciones CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Agregar libreta de direcciones LDAP
