# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Flexibelt mellanrum
toolbar-write-message-label = Skriv
toolbar-write-message =
    .title = Skapar ett nytt meddelande
toolbar-unifinder-label = Sök händelser
toolbar-unifinder =
    .title = Växla panelen sök händelser
toolbar-folder-location-label = Mappväljare
toolbar-edit-event-label = Redigera
toolbar-edit-event =
    .title = Redigera markerad händelse eller uppgift
toolbar-get-messages-label = Hämta meddelanden
toolbar-reply-label = Svara
toolbar-reply =
    .title = Svarar avsändaren
toolbar-reply-all-label = Svara alla
toolbar-reply-all =
    .title = Svarar avsändaren och även alla mottagare
toolbar-reply-to-list-label = Svara till listan
toolbar-reply-to-list =
    .title = Svara till e-postlistan
toolbar-redirect-label = Omdirigera
toolbar-redirect =
    .title = Omdirigera valt meddelande
toolbar-archive-label = Arkivera
toolbar-archive =
    .title = Arkiverar markerat meddelande
toolbar-conversation-label = Konversation
toolbar-conversation =
    .title = Visa konversation för valt meddelande
toolbar-previous-unread-label = Föregående olästa
toolbar-previous-unread =
    .title = Flytta till föregående olästa meddelande
toolbar-previous-label = Föregående
toolbar-previous =
    .title = Flytta till föregående meddelande
toolbar-next-unread-label = Nästa olästa
toolbar-next-unread =
    .title = Flytta till nästa olästa meddelande
toolbar-next-label = Nästa
toolbar-next =
    .title = Flytta till nästa meddelande
toolbar-junk-label = Skräppost
toolbar-junk =
    .title = Markera de valda meddelandena som skräp
toolbar-delete-label = Ta bort
toolbar-delete =
    .title = Ta bort markerade meddelanden eller mappar
toolbar-compact-label = Komprimera
toolbar-compact =
    .title = Rensa ut borttagna meddelanden från markerad mapp
toolbar-add-as-event-label = Lägg till som händelse
toolbar-add-as-event =
    .title = Plocka ut kalenderinformation från meddelandet och lägg till det i din kalender som en händelse
toolbar-add-as-task-label = Lägg till som uppgift
toolbar-add-as-task =
    .title = Plocka ut kalenderinformation från meddelandet och lägg till det i din kalender som en uppgift
toolbar-tag-message-label = Etikett
toolbar-tag-message =
    .title = Sätt etiketter på meddelanden
toolbar-forward-inline-label = Vidarebefordra
toolbar-forward-inline =
    .title = Vidarbefordra markerat meddelande som infogad text
toolbar-forward-attachment-label = Vidarbefordra som bilaga
toolbar-forward-attachment =
    .title = Vidarbefordra markerat meddelande som bilaga
toolbar-mark-as-label = Märk
toolbar-mark-as =
    .title = Märker meddelande
toolbar-address-book =
    .title = Gå till adressboken
toolbar-chat-label = Chatt
toolbar-chat =
    .title = Visa fliken chatt
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Växla till fliken kalender
toolbar-tasks-label = Uppgifter
toolbar-tasks =
    .title = Växla till fliken uppgifter
toolbar-print-label = Skriv ut
toolbar-print =
    .title = Skriv ut detta meddelande
