# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Flexibelt mellanrum
search-bar-label = Sök
toolbar-write-message-label = Skriv
toolbar-write-message =
    .title = Skapar ett nytt meddelande
toolbar-move-to-label = Flytta till
toolbar-move-to =
    .title = Flytta markerat meddelande
toolbar-unifinder-label = Sök händelser
toolbar-unifinder =
    .title = Växla panelen sök händelser
toolbar-folder-location-label = Mappväljare
toolbar-folder-location =
    .title = Växla till mapp
toolbar-edit-event-label = Redigera
toolbar-edit-event =
    .title = Redigera markerad händelse eller uppgift
toolbar-get-messages-label = Hämta meddelanden
toolbar-get-messages =
    .title = Hämta nya meddelanden för alla konton
toolbar-reply-label = Svara
toolbar-reply =
    .title = Svarar avsändaren
toolbar-reply-all-label = Svara alla
toolbar-reply-all =
    .title = Svarar avsändaren och även alla mottagare
toolbar-reply-to-list-label = Svara till listan
toolbar-reply-to-list =
    .title = Svara till e-postlistan
toolbar-redirect-label = Omdirigera
toolbar-redirect =
    .title = Omdirigera valt meddelande
toolbar-archive-label = Arkivera
toolbar-archive =
    .title = Arkiverar markerat meddelande
toolbar-conversation-label = Konversation
toolbar-conversation =
    .title = Visa konversation för valt meddelande
toolbar-previous-unread-label = Föregående olästa
toolbar-previous-unread =
    .title = Flytta till föregående olästa meddelande
toolbar-previous-label = Föregående
toolbar-previous =
    .title = Flytta till föregående meddelande
toolbar-next-unread-label = Nästa olästa
toolbar-next-unread =
    .title = Flytta till nästa olästa meddelande
toolbar-next-label = Nästa
toolbar-next =
    .title = Flytta till nästa meddelande
toolbar-junk-label = Skräppost
toolbar-junk =
    .title = Markera de valda meddelandena som skräp
toolbar-delete-label = Ta bort
toolbar-delete-title =
    .title = Ta bort de markerade meddelandena
toolbar-undelete-label = Ångra borttagning
toolbar-undelete =
    .title = Ångra borttagning av valda meddelanden
toolbar-compact-label = Komprimera
toolbar-compact =
    .title = Rensa ut borttagna meddelanden från markerad mapp
toolbar-add-as-event-label = Lägg till som händelse
toolbar-add-as-event =
    .title = Plocka ut kalenderinformation från meddelandet och lägg till det i din kalender som en händelse
toolbar-add-as-task-label = Lägg till som uppgift
toolbar-add-as-task =
    .title = Plocka ut kalenderinformation från meddelandet och lägg till det i din kalender som en uppgift
toolbar-tag-message-label = Etikett
toolbar-tag-message =
    .title = Sätt etiketter på meddelanden
toolbar-forward-inline-label = Vidarebefordra
toolbar-forward-inline =
    .title = Vidarbefordra markerat meddelande som infogad text
toolbar-forward-attachment-label = Vidarbefordra som bilaga
toolbar-forward-attachment =
    .title = Vidarbefordra markerat meddelande som bilaga
toolbar-mark-as-label = Märk
toolbar-mark-as =
    .title = Märker meddelande
toolbar-view-picker-label = Vy
toolbar-view-picker =
    .title = Anpassa vy för aktuell mapp
toolbar-address-book-label = Adressbok
toolbar-address-book =
    .title = Gå till adressboken
toolbar-chat-label = Chatt
toolbar-chat =
    .title = Visa fliken chatt
toolbar-add-ons-and-themes-label = Tillägg och teman
toolbar-add-ons-and-themes =
    .title = Hantera dina tillägg
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Växla till fliken kalender
toolbar-tasks-label = Uppgifter
toolbar-tasks =
    .title = Växla till fliken uppgifter
toolbar-mail-label = E-post
toolbar-mail =
    .title = Växla till e-postfliken
toolbar-print-label = Skriv ut
toolbar-print =
    .title = Skriv ut detta meddelande
toolbar-quick-filter-bar-label = Snabbfiltrering
toolbar-quick-filter-bar =
    .title = Filtrera meddelanden
toolbar-synchronize-label = Synkronisera
toolbar-synchronize =
    .title = Ladda om kalendrar och synkronisera ändringar
toolbar-delete-event-label = Radera
toolbar-delete-event =
    .title = Radera markerade händelser eller uppgifter
toolbar-go-to-today-label = Gå till Idag
toolbar-go-to-today =
    .title = Gå till idag
toolbar-print-event-label = Skriv ut
toolbar-print-event =
    .title = Skriv ut händelser eller uppgifter
toolbar-new-event-label = Händelse
toolbar-new-event =
    .title = Skapa en ny händelse
toolbar-new-task-label = Uppgift
toolbar-new-task =
    .title = Skapa en ny uppgift
toolbar-go-back-label = Bakåt
toolbar-go-back =
    .title = Gå bakåt ett meddelande
toolbar-go-forward-label = Framåt
toolbar-go-forward =
    .title = Gå framåt ett meddelande
toolbar-stop-label = Stopp
toolbar-stop =
    .title = Avbryter pågående överföring
toolbar-throbber-label = Aktivitetsindikator
toolbar-throbber =
    .title = Aktivitetsindikator
toolbar-create-contact-label = Ny kontakt
toolbar-create-contact =
    .title = Skapa en ny kontakt
toolbar-create-address-book-label = Ny adressbok
toolbar-create-address-book =
    .title = Skapa en ny adressbok
toolbar-create-list-label = Ny lista
toolbar-create-list =
    .title = Skapa en ny e-postlista
toolbar-import-contacts-label = Importera
toolbar-import-contacts =
    .title = Importera kontakter från en fil

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lägg till lokal adressbok
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Lägg till CardDAV-adressbok
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Lägg till LDAP-adressbok
