# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibilni razmak
toolbar-write-message-label = Piši
toolbar-write-message =
    .title = Stvori novu poruku
toolbar-unifinder-label = Pronađi događaje
toolbar-unifinder =
    .title = Uključi/isključi okno za traženje događaja
toolbar-folder-location-label = Lokacija direktorija
toolbar-edit-event-label = Uredi
toolbar-edit-event =
    .title = Uredi odabrani događaj ili zadatak
toolbar-get-messages-label = Dohvati poruke
toolbar-reply-label = Odgovori
toolbar-reply =
    .title = Odgovori na poruku
toolbar-reply-all-label = Odgovori svima
toolbar-reply-all =
    .title = Odgovori pošiljaocu i svim primaocima
toolbar-reply-to-list-label = Odgovori na listu
toolbar-reply-to-list =
    .title = Odgovori na popis primalaca
toolbar-archive-label = Arhiviraj
toolbar-archive =
    .title = Arhiviraj odabrane poruke
toolbar-conversation-label = Razgovor
toolbar-previous-unread-label = Prethodni nepročitani
toolbar-previous-unread =
    .title = Idi na prethodnu nepročitanu poruku
toolbar-previous-label = Prethodni
toolbar-previous =
    .title = Idi na prethodnu poruku
toolbar-next-unread-label = Sljedeći nepročitani
toolbar-next-unread =
    .title = Idi na sljedeću nepročitanu poruku
toolbar-next-label = Sljedeći
toolbar-next =
    .title = Idi na sljedeću poruku
toolbar-compact-label = Zbijena
toolbar-compact =
    .title = Ukloni izbrisane poruke iz odabranog direktorija
toolbar-add-as-event-label = Dodaj kao događaj
toolbar-add-as-event =
    .title = Izvezite kalendarske informacije iz poruke i dodajte ih u svoj kalendar kao događaj
toolbar-add-as-task-label = Dodaj kao zadatak
toolbar-add-as-task =
    .title = Izvezite kalendarske informacije iz poruke i dodajte ih u svoj kalendar kao zadatak
toolbar-tag-message-label = Oznaka
toolbar-tag-message =
    .title = Označi poruke
toolbar-forward-inline-label = Proslijedi
toolbar-forward-inline =
    .title = Proslijedite odabranu poruku kao umetnuti tekst
toolbar-forward-attachment-label = Proslijedi kao prilog
toolbar-forward-attachment =
    .title = Proslijedite odabranu poruku kao prilog
toolbar-mark-as-label = Označi
toolbar-mark-as =
    .title = Označi poruke
toolbar-address-book =
    .title = Idi u imenik
toolbar-chat-label = Razgovor
toolbar-chat =
    .title = Prikaži tab razgovora
toolbar-calendar-label = Kalendar
toolbar-calendar =
    .title = Prebaci na tab kalendara
toolbar-tasks-label = Zadaci
toolbar-tasks =
    .title = Prebaci na tab zadataka
toolbar-print-label = Štampaj
toolbar-print =
    .title = Štampaj ovu poruku
