# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = כותרת:
calendar-item-summary-calendar = לוח שנה:
calendar-item-summary-task-start = תאריך התחלה:
calendar-item-summary-event-start = תאריך התחלה:
calendar-item-summary-task-due = תאריך סיום:
calendar-item-summary-event-end = תאריך סיום:
calendar-item-summary-repeat = חזרה:
calendar-item-summary-location = מיקום:
calendar-item-summary-category = קטגוריה:
calendar-item-summary-organizer = מארגן:
calendar-item-summary-status = מצב:
calendar-item-summary-reminder = תזכורת:
calendar-item-summary-attachments = קבצים מצורפים:
calendar-item-summary-status-tentative = טנטטיבי
calendar-item-summary-status-confirmed = אושר
calendar-item-summary-event-status-cancelled = בוטל
calendar-item-summary-todo-status-cancelled = בוטל
calendar-item-summary-status-needs-action = דורש פעולה
calendar-item-summary-status-in-process = בביצוע
calendar-item-summary-status-completed = הסתיים בתאריך
calendar-item-summary-reminder-none =
    .label = אין תזכורת
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 דקות לפני
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 דקות לפני
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 דקות לפני
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 דקות לפני
calendar-item-summary-reminder-1-hour-before =
    .label = שעה לפני
calendar-item-summary-reminder-2-hours-before =
    .label = שעתיים לפני
calendar-item-summary-reminder-12-hours-before =
    .label = 12 שעות לפני
calendar-item-summary-reminder-1-day-before =
    .label = יום לפני
calendar-item-summary-reminder-2-days-before =
    .label = יומיים לפני
calendar-item-summary-reminder-1-week-before =
    .label = שבוע לפני
calendar-item-summary-reminder-custom =
    .label = מותאם אישית…
calendar-item-summary-reminder-multiple =
    .value = מספר תזכורות…
calendar-item-summary-general =
    .value = כללי
calendar-item-summary-attendees =
    .value = מוזמנים
calendar-item-summary-description =
    .value = תיאור
calendar-item-summary-link =
    .value = קישורים קשורים
