# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Параметры автономной работы
autodetect-connection-label =
    .label = Автоматически переключать режимы при обнаружении соединения с Интернетом
    .accesskey = d
offline-startup-label = При открытии { -brand-short-name }:
status-radio-last-used =
    .label = Использовать последний использованный режим соединения
    .accesskey = Г
status-radio-ask-connect =
    .label = Спрашивать, подключиться ли к сети
    .accesskey = k
status-radio-start-online =
    .label = Запустить онлайн
    .accesskey = Ш
status-radio-start-offline =
    .label = Запустить в автономном режиме
    .accesskey = f
going-online-prompt = Отправка сообщений, ожидающих в вашей папке «Исходящие»
going-online-send =
    .label = Да, отправлять автоматически
    .accesskey = Д
going-online-keep =
    .label = Нет, хранить в папке «Исходящие»
    .accesskey = Н
going-online-ask-send =
    .label = Спрашивать перед отправкой
    .accesskey = С
going-offline-prompt = Хотите загрузить сообщения для чтения в автономном режиме?
going-offline-download =
    .label = Да, загружать автоматически
    .accesskey = Д
going-offline-keep =
    .label = Нет, не загружать
    .accesskey = Н
going-offline-ask-download =
    .label = Спрашивать перед загрузкой
    .accesskey = С
autodetect-online-label =
    .label = Автоматически выбирать обнаруженное состояние подключения
    .accesskey = м
offline-preference-startup-label = Ручной выбор состояния при запуске:
status-radio-remember =
    .label = Использовать режим работы предыдущего сеанса
    .accesskey = ы
status-radio-ask =
    .label = Запросить состояние подключения
    .accesskey = о
status-radio-always-online =
    .label = Подключён к сети
    .accesskey = ю
status-radio-always-offline =
    .label = Автономная работа
    .accesskey = в
going-online-label = Отправить неотправленные сообщения при подключении?
going-online-auto =
    .label = Да
    .accesskey = Д
going-online-not =
    .label = Нет
    .accesskey = т
going-online-ask =
    .label = Спрашивать
    .accesskey = п
going-offline-label = Скачивать сообщения для использования в автономном режиме при отключении?
going-offline-auto =
    .label = Да
    .accesskey = а
going-offline-not =
    .label = Нет
    .accesskey = е
going-offline-ask =
    .label = Спрашивать
    .accesskey = ш
