# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Уведомления о прочтении
return-receipt-checkbox-control =
    .label = Всегда запрашивать уведомление о прочтении при отправке сообщений
    .accesskey = п
receipt-arrive-label = При получении уведомления о прочтении:
receipt-leave-inbox-control =
    .label = Оставить в папке «Входящие»
    .accesskey = ш
receipt-move-sent-control =
    .label = Переместить в папку «Отправленные»
    .accesskey = ь
receipt-sender-request-label = Когда отправитель запрашивает уведомление о прочтении:
receipt-leave-radio-control =
    .label = Оставлять его в папке «Входящие»
    .accesskey = х
receipt-move-radio-control =
    .label = Переместить его в папку «Отправленные»
    .accesskey = п
receipt-request-label = При получении запроса на уведомление о прочтении:
receipt-return-never-radio-control =
    .label = Никогда не отправлять уведомление о прочтении
    .accesskey = и
receipt-return-some-radio-control =
    .label = Отправлять уведомления о прочтении для некоторых сообщений
    .accesskey = е
receipt-not-listed-cc-label =
    .value = Если нет в списке «Кому» или «Копия»:
    .accesskey = а
receipt-not-to-cc-label =
    .value = Если я не в списке «Кому» или «Копия»:
    .accesskey = е
receipt-send-never-label =
    .label = Никогда не отправлять
receipt-send-always-label =
    .label = Отправлять
receipt-send-ask-label =
    .label = Спрашивать
sender-outside-company-label =
    .value = Если отправитель не находится в компании или домене:
    .accesskey = е
sender-outside-domain-label =
    .value = Если отправитель не в моём домене:
    .accesskey = м
other-cases-text-label =
    .value = В остальных случаях:
    .accesskey = а
read-receipts-dialog-title = Уведомления о прочтении
return-receipt-request-control =
    .label = Всегда запрашивать уведомление о прочтении при отправке электронных писем
    .accesskey = Ц
