# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Titl:
calendar-item-summary-calendar = Deiziataer:
calendar-item-summary-task-start = Eus:
calendar-item-summary-event-start = Eus:
calendar-item-summary-task-due = Termen:
calendar-item-summary-event-end = Betek:
calendar-item-summary-repeat = Arren:
calendar-item-summary-location = Lec'hiadur:
calendar-item-summary-category = Rummad:
calendar-item-summary-organizer = Aozer:
calendar-item-summary-status = Stad:
calendar-item-summary-reminder = Koun:
calendar-item-summary-attachments = Kenstagadurioù:
calendar-item-summary-status-tentative = Argeziad
calendar-item-summary-status-confirmed = Kadarnaet
calendar-item-summary-event-status-cancelled = Nullet
calendar-item-summary-todo-status-cancelled = Nullet
calendar-item-summary-status-needs-action = Dleet eo ober un dra bennak
calendar-item-summary-status-in-process = En ardreug
calendar-item-summary-status-completed = Echu
calendar-item-summary-reminder-none =
    .label = Koun ebet
calendar-item-summary-reminder-0-minutes-before =
    .label = munutenn ebet kent
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 munutenn kent
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 munutenn kent
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 munutenn kent
calendar-item-summary-reminder-1-hour-before =
    .label = 1 eurvezh kent
calendar-item-summary-reminder-2-hours-before =
    .label = 2 eurvezh kent
calendar-item-summary-reminder-12-hours-before =
    .label = 12 eurvezh kent
calendar-item-summary-reminder-1-day-before =
    .label = 1 devezh kent
calendar-item-summary-reminder-2-days-before =
    .label = 2 zevezh kent
calendar-item-summary-reminder-1-week-before =
    .label = 1 sizhunvezh kent
calendar-item-summary-reminder-custom =
    .label = Personelaet...
calendar-item-summary-reminder-multiple =
    .value = Meur a goun...
calendar-item-summary-general =
    .value = Hollek
calendar-item-summary-attendees =
    .value = Perzhidi
calendar-item-summary-description =
    .value = Deskrivadur
calendar-item-summary-link =
    .value = Ere kar
