# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibelt mellomrom
toolbar-write-message-label = Skriv
toolbar-write-message =
    .title = Skriv ny melding
toolbar-move-to-label = Flytt til
toolbar-move-to =
    .title = Flytt vald melding
toolbar-unifinder-label = Finn hendingar
toolbar-unifinder =
    .title = Slå søk i hendingar av eller på
toolbar-folder-location-label = Mappeplassering
toolbar-folder-location =
    .title = Byt til mappe
toolbar-edit-event-label = Rediger
toolbar-edit-event =
    .title = Rediger vald hending eller oppgåve
toolbar-get-messages-label = Hent meldingar
toolbar-reply-label = Svar
toolbar-reply =
    .title = Svar til avsendar
toolbar-reply-all-label = Svar alle
toolbar-reply-all =
    .title = Svar til avsendar og alle mottakarar
toolbar-reply-to-list-label = Svar til liste
toolbar-reply-to-list =
    .title = Svar til e-postliste
toolbar-redirect-label = Omdiriger
toolbar-redirect =
    .title = Omdiriger vald melding
toolbar-archive-label = Arkiv
toolbar-archive =
    .title = Arkiver valde meldingar
toolbar-conversation-label = Samtale
toolbar-conversation =
    .title = Vis samtale for vald melding
toolbar-previous-unread-label = Førre ulesne
toolbar-previous-unread =
    .title = Gå til førre ulesne melding
toolbar-previous-label = Førre
toolbar-previous =
    .title = Gå til førre melding
toolbar-next-unread-label = Neste ulesne
toolbar-next-unread =
    .title = Gå til neste ulesne melding
toolbar-next-label = Neste
toolbar-next =
    .title = Gå til neste melding
toolbar-junk-label = Uønskt
toolbar-junk =
    .title = Merk dei valde meldingane som uønskt e-post
toolbar-delete-label = Slett
toolbar-compact-label = Komprimer
toolbar-compact =
    .title = Fjern sletta meldingar frå vald mappe
toolbar-add-as-event-label = Legg til som hending
toolbar-add-as-event =
    .title = Hent ut kalenderinfo frå meldinga og legg til i kalenderen din som ei hending
toolbar-add-as-task-label = Legg til som oppgåve
toolbar-add-as-task =
    .title = Hent ut kalenderinfo frå meldinga og legg til i kalenderen din som ei oppgåve
toolbar-tag-message-label = Merkelapp-stikkord
toolbar-tag-message =
    .title = Merk melding
toolbar-forward-inline-label = Vidaresend
toolbar-forward-inline =
    .title = Vidaresend vald melding som innbunden tekst
toolbar-forward-attachment-label = Vidaresend som vedlegg
toolbar-forward-attachment =
    .title = Vidaresend vald melding som eit vedlegg
toolbar-mark-as-label = Merk
toolbar-mark-as =
    .title = Merk meldingar
toolbar-view-picker-label = Vis
toolbar-address-book-label = Adressebok
toolbar-address-book =
    .title = Opne adresseboka
toolbar-chat-label = Nettprat
toolbar-chat =
    .title = Vis nettprat-fana
toolbar-add-ons-and-themes-label = Tillegg og tema
toolbar-add-ons-and-themes =
    .title = Handter tillegga dine
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Byt til kalenderfana
toolbar-tasks-label = Oppgåver
toolbar-tasks =
    .title = Byt til oppgåvefana
toolbar-mail-label = E-post
toolbar-print-label = Skriv ut
toolbar-print =
    .title = Skriv ut denne meldinga
toolbar-quick-filter-bar-label = Snøggfilter
toolbar-quick-filter-bar =
    .title = Filtrer meldingar
toolbar-synchronize-label = Synkroniser
toolbar-synchronize =
    .title = Oppdater kalendrar og synkroniser endringar
toolbar-delete-event-label = Slett
toolbar-delete-event =
    .title = Slett valde hendingar eller oppgåver
toolbar-go-to-today-label = Gå til I dag
toolbar-go-to-today =
    .title = Gå til I dag
toolbar-print-event-label = Skriv ut
toolbar-print-event =
    .title = Skriv ut hendingar eller oppgåver
toolbar-new-event-label = Hending
toolbar-new-event =
    .title = Lag ei ny hending
toolbar-new-task-label = Oppgåve
toolbar-new-task =
    .title = Lag ei ny oppgåve
toolbar-go-back-label = Tilbake
toolbar-go-back =
    .title = Gå tilbake ei melding
toolbar-go-forward-label = Fram
toolbar-go-forward =
    .title = Gå fram ei melding
toolbar-stop-label = Stopp
toolbar-stop =
    .title = Stopp denne overføringa
toolbar-throbber-label = Aktivitetsindikator
toolbar-throbber =
    .title = Aktivitetsindikator
toolbar-create-contact-label = Ny kontakt
toolbar-create-address-book-label = Ny adressebok
toolbar-create-list-label = Ny liste
toolbar-import-contacts-label = Importer

## New Address Book popup items

