# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (start.prefix):
# datetimes with these in front are extracted as start times
# can be a list of values, separate variants by |
start.prefix =
# LOCALIZATION NOTE (start.suffix):
# datetimes followed by these are extracted as start times
start.suffix = bởi | cho đến khi | đến | - | đến | đến | và
# LOCALIZATION NOTE (end.prefix):
# datetimes with these in front are extracted as end times
end.prefix = bởi | cho đến khi | đến | - | đến | đến | và | đến hạn: | đến hạn | kết thúc | hạn chót là | hạn chót:
# LOCALIZATION NOTE (end.suffix):
# datetimes followed by these are extracted as end times
# can be a list of values, separate variants by |
end.suffix =
# LOCALIZATION NOTE (no.datetime.prefix):
# datetimes with these in front won't be used
# specify full words here
no.datetime.prefix = tuần trước | đã gửi | email | email | thay vì | > | thật không may | trong | không phải
# LOCALIZATION NOTE (no.datetime.suffix):
# datetimes followed by these won't be used
no.datetime.suffix = floor | flr | : | email | e-mail | > | % | usd | dollars | $
# LOCALIZATION NOTE (from.today):
# must not be empty!
from.today = hôm nay
from.tomorrow = ngày mai
# LOCALIZATION NOTE (until.*):
# can be a list of values, separate variants by |
until.tomorrow =
# LOCALIZATION NOTE (from.ordinal.date):
##1 = matches numbers 1-31 and number.x
# should not have "#1" as this would match any single number in email to a time
from.ordinal.date = #1 | #1 | #1 | #1
# LOCALIZATION NOTE (until.ordinal.date):
##1 = matches numbers 1-31 and number.x
until.ordinal.date =
from.noon = trưa
until.noon =
# LOCALIZATION NOTE (from.hour):
##1 = matches numbers 0-23 and number.0-number.23
# should not have "#1" as this would match any single number in email to a time
from.hour = lúc #1 | khoảng #1 | #1 - | #1 đến
# LOCALIZATION NOTE (until.hour):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour = - #1 | đến #1 | cho đến #1 | bởi #1
# LOCALIZATION NOTE (from.hour.am):
##1 = matches numbers 0-23 and number.0-number.23
from.hour.am = #1 sáng | #1 sáng
# LOCALIZATION NOTE (until.hour.am):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour.am =
# LOCALIZATION NOTE (from.hour.pm):
##1 = matches numbers 0-23 and number.0-number.23
from.hour.pm = #1 chiều | #1 chiều | #1 chiều
# LOCALIZATION NOTE (until.hour.pm):
##1 = matches numbers 0-23 and number.0-number.23
# should also list how to find end of a timeframe
until.hour.pm =
# LOCALIZATION NOTE (from.half.hour.before):
# denotes times 30 minutes before next full hour
from.half.hour.before = #1 giờ kém 30 phút
# LOCALIZATION NOTE (until.half.hour.before):
# denotes times 30 minutes before next full hour
until.half.hour.before =
# LOCALIZATION NOTE (from.half.hour.after):
# denotes times 30 minutes after last full hour
from.half.hour.after = #1 giờ rưỡi
# LOCALIZATION NOTE (until.half.hour.after):
# denotes times 30 minutes after last full hour
until.half.hour.after =
# LOCALIZATION NOTE (from.hour.minutes):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes = #1:#2 | lúc #1#2
# LOCALIZATION NOTE (until.hour.minutes):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes =
# LOCALIZATION NOTE (from.hour.minutes.am):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes.am = #1:#2 sáng | #1:#2 sáng
# LOCALIZATION NOTE (until.hour.minutes.am):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes.am =
# LOCALIZATION NOTE (from.hour.minutes.pm):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
from.hour.minutes.pm = #1:#2 chiều | #1:#2 chiều | #1:#2 chiều
# LOCALIZATION NOTE (until.hour.minutes.pm):
##1 = matches numbers 0-23
##2 = matches numbers 0-59
until.hour.minutes.pm =
# LOCALIZATION NOTE (from.monthname.day):
##1 = matches numbers 1-31 and number.x
##2 = matches monthname
from.monthname.day = ngày #1 #2
# LOCALIZATION NOTE (until.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
until.monthname.day =
# LOCALIZATION NOTE (from.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
from.month.day = #1/#2
# LOCALIZATION NOTE (until.month.day):
##1 = matches numbers 1-31 and number.x
##2 = matches numbers 1-12
until.month.day =
# LOCALIZATION NOTE (from.year.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
##3 = matches 2/4 numbers
from.year.month.day = #1/#2/#3 | #1/#2/#3 | #1-#2-#3
# LOCALIZATION NOTE (until.year.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
##3 = matches 2/4 numbers
until.year.month.day =
# LOCALIZATION NOTE (from.year.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
##3 = matches 2/4 numbers
from.year.monthname.day = ngày #1 #2 năm #3
# LOCALIZATION NOTE (until.year.monthname.day):
##1 = matches numbers 1-31
##2 = matches monthname
##3 = matches 2/4 numbers
until.year.monthname.day =
# LOCALIZATION NOTE (duration.minutes):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.minutes = #1 phút | #1 phút | #1 phút
# LOCALIZATION NOTE (duration.hours):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.hours = #1 giờ | #1 giờ
# LOCALIZATION NOTE (duration.days):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.days = #1 ngày
# LOCALIZATION NOTE (month.*):
# can be a list of values, separate variants by |
month.1 = tháng một | tg1
month.2 = tháng hai | tg2
month.3 = tháng ba | tg3
month.4 = tháng tư | tg4
month.5 = tháng năm | tg5
month.6 = tháng sáu | tg6
month.7 = tháng bảy | tg7
month.8 = tháng tám | tg8
month.9 = tháng chín | tg9
month.10 = tháng mười | tg10
month.11 = tháng mười một | tg11
month.12 = tháng mười hai | tg12
# LOCALIZATION NOTE (from.weekday.*):
# used to derive start date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (from.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
from.weekday.0 = chủ nhật | chủ nhật
from.weekday.1 = thứ hai | thứ hai
from.weekday.2 = thứ ba | thứ ba
from.weekday.3 = thứ tư | thứ tư
from.weekday.4 = thứ năm | thứ năm
from.weekday.5 = thứ sáu | thứ sáu
from.weekday.6 = thứ bảy | thứ bảy
# LOCALIZATION NOTE (until.weekday.*):
# used to derive end date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (until.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
until.weekday.0 =
until.weekday.1 =
until.weekday.2 =
until.weekday.3 =
until.weekday.4 =
until.weekday.5 =
until.weekday.6 =
# LOCALIZATION NOTE (number.*):
# used within other patterns to understand dates where day of month isn't written with digits
# can be a list of values, separate variants by |
number.0 = không
number.1 = một | đầu
number.2 = hai
number.3 = ba
number.4 = bốn
number.5 = năm
number.6 = sáu
number.7 = bảy
number.8 = tám
number.9 = chín
number.10 = mười
number.11 = mười một
number.12 = mười hai
number.13 = mười ba
number.14 = mười bốn
number.15 = mười lăm
number.16 = mười sáu
number.17 = mười bảy
number.18 = mười tám
number.19 = mười chín
number.20 = hai mươi
number.21 = hai mươi mốt
number.22 = hai mươi hai
number.23 = hai mươi ba
number.24 = hai mươi bốn
number.25 = hai mươi lăm
number.26 = hai mươi sáu
number.27 = hai mươi bảy
number.28 = hai mươi tám
number.29 = hai mươi chín
number.30 = ba mươi
number.31 = ba mươi mốt
# LOCALIZATION NOTE (alphabet):
# list all lower and uppercase letters if your language has an alphabet
# otherwise leave it empty
alphabet = aăâbcdđeêghiklmnopqrstuưvxyAĂÂBCDĐEÊGHIJKMNOPQRSTUƯVXY
