# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = ismétlődő esemény
header-isrepeating-task =
    .label = ismétlődő feladat
header-containsrepeating-event =
    .label = ismétlődő eseményeket tartalmaz
header-containsrepeating-task =
    .label = ismétlődő feladatokat tartalmaz
header-containsrepeating-mixed =
    .label = különböző típusú ismétlődő elemeket tartalmaz
windowtitle-event-copy = Ismétlődő esemény másolása
windowtitle-task-copy = Ismétlődő feladat másolása
windowtitle-mixed-copy = Ismétlődő elemek másolása
windowtitle-event-cut = Ismétlődő esemény kivágása
windowtitle-task-cut = Ismétlődő feladat kivágása
windowtitle-mixed-cut = Ismétlődő elemek kivágása
windowtitle-event-delete = Ismétlődő esemény törlése
windowtitle-task-delete = Ismétlődő feladat törlése
windowtitle-mixed-delete = Ismétlődő elemek törlése
windowtitle-event-edit = Ismétlődő esemény szerkesztése
windowtitle-task-edit = Ismétlődő feladat szerkesztése
windowtitle-mixed-edit = Ismétlődő elemek szerkesztése
windowtitle-multipleitems =
    .value = Kiválasztott elemek
button-single-occurrence-copy =
    .label = Csak ezen előfordulás másolása
    .accesskey = e
button-single-occurrence-cut =
    .label = Csak ezen előfordulás kivágása
    .accesskey = e
button-single-occurrence-delete =
    .label = Csak ezen előfordulás törlése
    .accesskey = e
button-single-occurrence-edit =
    .label = Csak ezen előfordulás szerkesztése
    .accesskey = e
button-multiple-occurrence-copy =
    .label = Csak a kiválasztott előfordulások másolása
    .accesskey = e
button-multiple-occurrence-cut =
    .label = Csak a kiválasztott előfordulások kivágása
    .accesskey = e
button-multiple-occurrence-delete =
    .label = Csak a kiválasztott előfordulások törlése
    .accesskey = e
button-multiple-occurrence-edit =
    .label = Csak a kiválasztott előfordulások szerkesztése
    .accesskey = e
button-single-allfollowing-copy =
    .label = Ennek és az összes jövőbeli előfordulásnak a másolása
    .accesskey = k
button-single-allfollowing-cut =
    .label = Ennek és az összes jövőbeli előfordulásnak a kivágása
    .accesskey = k
button-single-allfollowing-delete =
    .label = Ennek és az összes jövőbeli előfordulásnak a törlése
    .accesskey = k
button-single-allfollowing-edit =
    .label = Ennek és az összes jövőbeli előfordulásnak a szerkesztése
    .accesskey = k
button-multiple-allfollowing-copy =
    .label = A kiválasztottak és az összes jövőbeli előfordulás másolása
    .accesskey = k
button-multiple-allfollowing-cut =
    .label = A kiválasztottak és az összes jövőbeli előfordulás kivágása
    .accesskey = k
button-multiple-allfollowing-delete =
    .label = A kiválasztottak és az összes jövőbeli előfordulás törlése
    .accesskey = k
button-multiple-allfollowing-edit =
    .label = A kiválasztottak és az összes jövőbeli előfordulás szerkesztése
    .accesskey = k
button-single-parent-copy =
    .label = Minden előfordulás másolása
    .accesskey = s
button-single-parent-cut =
    .label = Minden előfordulás kivágása
    .accesskey = s
button-single-parent-delete =
    .label = Minden előfordulás törlése
    .accesskey = s
button-single-parent-edit =
    .label = Minden előfordulás szerkesztése
    .accesskey = s
button-multiple-parent-copy =
    .label = A kiválasztott elemek összes előfordulásának másolása
    .accesskey = s
button-multiple-parent-cut =
    .label = A kiválasztott elemek összes előfordulásának kivágása
    .accesskey = s
button-multiple-parent-delete =
    .label = A kiválasztott elemek összes előfordulásának törlése
    .accesskey = s
button-multiple-parent-edit =
    .label = A kiválasztott elemek összes előfordulásának szerkesztése
    .accesskey = s
buttons-single-occurrence-copy =
    .label = Csak ezen előfordulás másolása
buttons-single-occurrence-cut =
    .label = Csak ezen előfordulás kivágása
buttons-single-occurrence-delete =
    .label = Csak ezen előfordulás törlése
buttons-single-occurrence-edit =
    .label = Csak ezen előfordulás szerkesztése
buttons-multiple-occurrence-copy =
    .label = Csak a kiválasztott előfordulások másolása
buttons-multiple-occurrence-cut =
    .label = Csak a kiválasztott előfordulások kivágása
buttons-multiple-occurrence-delete =
    .label = Csak a kiválasztott előfordulások törlése
buttons-multiple-occurrence-edit =
    .label = Csak a kiválasztott előfordulások szerkesztése
buttons-single-allfollowing-copy =
    .label = Ennek és az összes jövőbeli előfordulásnak a másolása
buttons-single-allfollowing-cut =
    .label = Ennek és az összes jövőbeli előfordulásnak a kivágása
buttons-single-allfollowing-delete =
    .label = Ennek és az összes jövőbeli előfordulásnak a törlése
buttons-single-allfollowing-edit =
    .label = Ennek és az összes jövőbeli előfordulásnak a szerkesztése
buttons-multiple-allfollowing-copy =
    .label = A kiválasztottak és az összes jövőbeli előfordulás másolása
buttons-multiple-allfollowing-cut =
    .label = A kiválasztottak és az összes jövőbeli előfordulás kivágása
buttons-multiple-allfollowing-delete =
    .label = A kiválasztottak és az összes jövőbeli előfordulás törlése
buttons-multiple-allfollowing-edit =
    .label = A kiválasztottak és az összes jövőbeli előfordulás szerkesztése
buttons-single-parent-copy =
    .label = Minden előfordulás másolása
buttons-single-parent-cut =
    .label = Minden előfordulás kivágása
buttons-single-parent-delete =
    .label = Minden előfordulás törlése
buttons-single-parent-edit =
    .label = Minden előfordulás szerkesztése
buttons-multiple-parent-copy =
    .label = A kiválasztott elemek összes előfordulásának másolása
buttons-multiple-parent-cut =
    .label = A kiválasztott elemek összes előfordulásának kivágása
buttons-multiple-parent-delete =
    .label = A kiválasztott elemek összes előfordulásának törlése
buttons-multiple-parent-edit =
    .label = A kiválasztott elemek összes előfordulásának szerkesztése
