# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Összes kijelölése
select-none-calendars = Kijelölés megszüntetése
calendar-creation-wizard-title = Új naptár létrehozása
calendar-creation-initial-description = A naptár tárolható a saját számítógépén vagy egy kiszolgálón, hogy távolról is elérhető legyen, illetve megosztható legyen az ismerősökkel vagy munkatársakkal.
calendar-creation-initial-computer =
    .label = A saját számítógépen
calendar-creation-initial-network =
    .label = A hálózaton
calendar-creation-username =
    .value = Felhasználónév:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Naptár létrehozása
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Vissza
    .buttonaccesskeyextra2 = V
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Naptár létrehozása
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Vissza
    .buttonaccesskeyextra2 = V
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Naptárak keresése
    .buttonaccesskeyaccept = k
    .buttonlabelextra2 = Vissza
    .buttonaccesskeyextra2 = V
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Feliratkozás
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Vissza
    .buttonaccesskeyextra2 = V
calendar-creation-type =
    .value = Naptár típusa:
calendar-creation-location =
    .value = Hely:
calendar-creation-location-placeholder =
    .placeholder = A naptár-kiszolgáló webcíme vagy gépneve
    .default-placeholder = A naptár-kiszolgáló webcíme vagy gépneve
calendar-creation-network-nocredentials =
    .label = Ez a hely nem igényel hitelesítő adatokat
calendar-creation-network-loading = Várjon amíg a naptárai felfedezésre kerülnek.
calendar-creation-network-notfound = Ezen a helyen nem találhatóak naptárak. Ellenőrizze a beállításait.
calendar-creation-network-authfail = A megadott hitelesítő adatok nem lettek elfogadva. Ellenőrizze a beállításait.
calendar-creation-network-certerror = Tanúsítványhiba miatt nem találhatók naptárak ezen a helyen.
calendar-creation-network-subscribe-single = Válassza ki a naptárakat, amelyekre fel szeretne iratkozni.
calendar-creation-network-subscribe-multiple = Több naptártípus is elérhető ehhez a helyhez. Válasszon egy naptártípust, és jelölje meg a naptárakat, amelyekre fel akar iratkozni.
