# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Megjegyzés
calendar-item-summary-title = Cím:
calendar-item-summary-calendar = Naptár:
calendar-item-summary-task-start = Kezdési dátum:
calendar-item-summary-event-start = Kezdési dátum:
calendar-item-summary-task-due = Határidő:
calendar-item-summary-event-end = Befejezési dátum:
calendar-item-summary-repeat = Ismétlés:
calendar-item-summary-location = Hely:
calendar-item-summary-category = Kategória:
calendar-item-summary-organizer = Szervező:
calendar-item-summary-status = Állapot:
calendar-item-summary-reminder = Emlékeztető:
calendar-item-summary-attachments = Mellékletek:
calendar-item-summary-status-tentative = Feltételes
calendar-item-summary-status-confirmed = Megerősített
calendar-item-summary-event-status-cancelled = Lemondott
calendar-item-summary-todo-status-cancelled = Lemondott
calendar-item-summary-status-needs-action = Foglalkozni kell vele
calendar-item-summary-status-in-process = Folyamatban
calendar-item-summary-status-completed = Befejezve
calendar-item-summary-reminder-none =
    .label = Nincs emlékeztető
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 perccel előtte
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 perccel előtte
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 perccel előtte
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 perccel előtte
calendar-item-summary-reminder-1-hour-before =
    .label = 1 órával előtte
calendar-item-summary-reminder-2-hours-before =
    .label = 2 órával előtte
calendar-item-summary-reminder-12-hours-before =
    .label = 12 órával előtte
calendar-item-summary-reminder-1-day-before =
    .label = 1 nappal előtte
calendar-item-summary-reminder-2-days-before =
    .label = 2 nappal előtte
calendar-item-summary-reminder-1-week-before =
    .label = 1 héttel előtte
calendar-item-summary-reminder-custom =
    .label = Egyéni…
calendar-item-summary-reminder-multiple =
    .value = Több emlékeztető…
calendar-item-summary-general =
    .value = Általános
calendar-item-summary-attendees =
    .value = Résztvevők
calendar-item-summary-description =
    .value = Leírás
calendar-item-summary-link =
    .value = Kapcsolódó hivatkozás
