# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Желіден тыс режимінің баптаулары
autodetect-connection-label =
    .label = Интернет қосылымы табылған кезде режимдерді автоматты түрде ауыстыру
    .accesskey = б
offline-startup-label = { -brand-short-name } ашылған кезде:
status-radio-last-used =
    .label = Соңғы қолданылған қосылым режимін пайдалану
    .accesskey = й
status-radio-ask-connect =
    .label = Онлайн қосылу туралы сұрау
    .accesskey = О
status-radio-start-online =
    .label = Онлайн режимінде бастау
    .accesskey = й
status-radio-start-offline =
    .label = Офлайн режимінде бастау
    .accesskey = ф
going-offline-download =
    .label = Иә, автоматты түрде жүктеп алу
    .accesskey = И
going-offline-keep =
    .label = Жоқ, жүктеп алмау
    .accesskey = о
going-offline-ask-download =
    .label = Жүктеп алу алдында сұрау
    .accesskey = а
autodetect-online-label =
    .label = Табылған байланысу күйін автоқолдану
    .accesskey = б
offline-preference-startup-label = Іске қосылғандағы қолмен көрсетілген күйі:
status-radio-remember =
    .label = Алдыңғы онлайн күйін есте сақтау
    .accesskey = с
status-radio-ask =
    .label = Мені онлайн күйі жөнінде сұрау
    .accesskey = с
status-radio-always-online =
    .label = Желіде
    .accesskey = л
status-radio-always-offline =
    .label = Желіде емес
    .accesskey = м
going-online-label = Желіге байланысқан режимге өткен кезде жіберілмеген хабарламаларды жіберу керек пе?
going-online-auto =
    .label = Иә
    .accesskey = И
going-online-not =
    .label = Жоқ
    .accesskey = о
going-online-ask =
    .label = Мені сұрау
    .accesskey = с
going-offline-label = Желіден тыс режимге өту кезінде желіден тыс қолдану үшін хабарламаларды жүктеп алу керек пе?
going-offline-auto =
    .label = Иә
    .accesskey = И
going-offline-not =
    .label = Жоқ
    .accesskey = о
going-offline-ask =
    .label = Мені сұрау
    .accesskey = с
