# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = կրկնուող իրադարձութիւն է
header-isrepeating-task =
    .label = կրկնուող առաջադրանք է
header-containsrepeating-event =
    .label = պարունակում է կրկնուող իրադարձութիւններ
header-containsrepeating-task =
    .label = պարունակում է կրկնուող առաջադրանքներ
header-containsrepeating-mixed =
    .label = պարունակում է տարբեր կրկնուող տարրեր
windowtitle-event-copy = Պատճենել կրկնուող իրադարձութիւնը
windowtitle-task-copy = Պատճենել կրկնուող առաջադրանքը
windowtitle-mixed-copy = Պատճենել կրկնուող տարրերը
windowtitle-event-cut = Կտրել կրկնուող իրադարձութիւնը
windowtitle-task-cut = Կտրել կրկնուող առաջադրանքը
windowtitle-mixed-cut = Կտրել կրկնուող տարրերը
windowtitle-event-delete = Ջնջել կրկնուող իրադարձութիւնը
windowtitle-task-delete = Ջնջել կրկնուող առաջադրանքը
windowtitle-mixed-delete = Ջնջել կրկնուող տարրերը
windowtitle-event-edit = Խմբագրել կրկնուող իրադարձութիւնը
windowtitle-task-edit = Խմբագրել կրկնուող առաջադրանքը
windowtitle-mixed-edit = Խմագրել կրկնուող տարրերը
windowtitle-multipleitems =
    .value = Նշուած տարրեր
button-single-occurrence-copy =
    .label = Պատճենել միայն այս դէպքը
    .accesskey = t
button-single-occurrence-cut =
    .label = Կտրել միայն այս դէպքը
    .accesskey = t
button-single-occurrence-delete =
    .label = Ջնջել միայն այս դէպքը
    .accesskey = t
button-single-occurrence-edit =
    .label = Խմբագրել միայն այս դէպքը
    .accesskey = t
button-multiple-occurrence-copy =
    .label = Պատճենել միայն նշուած դէպքերը
    .accesskey = t
button-multiple-occurrence-cut =
    .label = Կտրել միայն նշուած դէպքերը
    .accesskey = t
button-multiple-occurrence-delete =
    .label = Ջնջել միայն նշուած դէպքերը
    .accesskey = t
button-multiple-occurrence-edit =
    .label = Խմբագրել միայն նշուած դէպքերը
    .accesskey = t
button-single-allfollowing-copy =
    .label = Պատճենել միայն նշուած դէպքերը
    .accesskey = f
button-single-allfollowing-cut =
    .label = Կտրել այս եւ ապագայ դէպքերը
    .accesskey = f
button-single-allfollowing-delete =
    .label = Ջնջել այս եւ ապագայ դէպքերը
    .accesskey = f
button-single-allfollowing-edit =
    .label = Խմբագրել այս եւ ապագայ դէպքերը
    .accesskey = f
button-multiple-allfollowing-copy =
    .label = Պատճենել այս եւ ապագայ դէպքերը
    .accesskey = f
button-multiple-allfollowing-cut =
    .label = Հատել ընտրուած եւ յետագայ դէպքերը
    .accesskey = f
button-multiple-allfollowing-delete =
    .label = Ջնջել այս եւ յետագայ դէպքերը
    .accesskey = f
button-multiple-allfollowing-edit =
    .label = Խմբագրել այս եւ յետագայ դէպքերը
    .accesskey = f
button-single-parent-copy =
    .label = Պատճենել բոլոր դէպքերը
    .accesskey = a
button-single-parent-cut =
    .label = Կտրել բոլոր դէպքերը
    .accesskey = a
button-single-parent-delete =
    .label = Ջնջել բոլոր դէպքերը
    .accesskey = a
button-single-parent-edit =
    .label = Խմբագրել բոլոր դէպքերը
    .accesskey = a
button-multiple-parent-copy =
    .label = Պատճենել նշուած տարրերի բոլոր դէպքերը
    .accesskey = a
button-multiple-parent-cut =
    .label = Կտրել նշուած տարրերի բոլոր դէպքերը
    .accesskey = a
button-multiple-parent-delete =
    .label = Ջնջել նշուած տարրերի բոլոր դէպքերը
    .accesskey = a
button-multiple-parent-edit =
    .label = Խմբագրել նշուած տարրերի բոլոր դէպքերը
    .accesskey = a
buttons-single-occurrence-copy =
    .label = Պատճենել միայն այս դէպքը
buttons-single-occurrence-cut =
    .label = Կտրել միայն այս դէպքը
buttons-single-occurrence-delete =
    .label = Ջնջել միայն այս դէպքը
buttons-single-occurrence-edit =
    .label = Խմբագրել միայն այս դէպքը
buttons-multiple-occurrence-copy =
    .label = Պատճենել միայն նշուած դէպքերը
buttons-multiple-occurrence-cut =
    .label = Կտրել միայն նշուած դէպքերը
buttons-multiple-occurrence-delete =
    .label = Ջնջել միայն նշուած դէպքերը
buttons-multiple-occurrence-edit =
    .label = Խմբագրել միայն նշուած դէպքերը
buttons-single-allfollowing-copy =
    .label = Պատճենել միայն նշուած դէպքերը
buttons-single-allfollowing-cut =
    .label = Կտրել այս եւ ապագայ դէպքերը
buttons-single-allfollowing-delete =
    .label = Ջնջել այս եւ ապագայ դէպքերը
buttons-single-allfollowing-edit =
    .label = Խմբագրել այս եւ ապագայ դէպքերը
buttons-multiple-allfollowing-copy =
    .label = Պատճենել այս եւ ապագայ դէպքերը
buttons-multiple-allfollowing-cut =
    .label = Հատել ընտրուած եւ յետագայ դէպքերը
buttons-multiple-allfollowing-delete =
    .label = Ջնջել այս եւ յետագայ դէպքերը
buttons-multiple-allfollowing-edit =
    .label = Խմբագրել այս եւ յետագայ դէպքերը
buttons-single-parent-copy =
    .label = Պատճենել բոլոր դէպքերը
buttons-single-parent-cut =
    .label = Կտրել բոլոր դէպքերը
buttons-single-parent-delete =
    .label = Ջնջել բոլոր դէպքերը
buttons-single-parent-edit =
    .label = Խմբագրել բոլոր դէպքերը
buttons-multiple-parent-copy =
    .label = Պատճենել նշուած տարրերի բոլոր դէպքերը
buttons-multiple-parent-cut =
    .label = Կտրել նշուած տարրերի բոլոր դէպքերը
buttons-multiple-parent-delete =
    .label = Ջնջել նշուած տարրերի բոլոր դէպքերը
buttons-multiple-parent-edit =
    .label = Խմբագրել նշուած տարրերի բոլոր դէպքերը
