# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Default name for new events
new-event =
    .placeholder = Նոր իրադարձութիւն
# Titles for the event/task dialog
new-event-dialog = Նոր իրադարձութիւն
edit-event-dialog = Խմբագրել իրադարձութիւնը
new-task-dialog = Նոր առաջադրանք
edit-task-dialog = Խմբագրել առաջադրանքը
# Remove attachments prompt.
prompt-remove-attachments-title = Հեռացնել կցորդները
# LOCALIZATION NOTE (prompt-remove-attachments-text):
#  $count will be replaced with number of attachments
prompt-remove-attachments-text = Արդեւք ցանկանում է՞ք հեռացնել { $count } կցորդը։Արդե՞ւք ցանկանում է՞ք հեռացնել  { $count } կցորդները։
# Do you want to save changes?
ask-save-title-event = Պահպանել իրադարձութիւն
ask-save-title-task = Պահպանել առաջադրանքը
ask-save-message-event = Իրադարձութիւնը չի պահպանուել։ Ցանկանու՞մ էք պահպանել այն։
ask-save-message-task = Առաջադրանքը չի պահպանուել։ Ցանկանու՞մ էք պահպանել այն։
# Event Dialog Warnings
warning-end-before-start = Ձեր մուտքագրած աւարտի ամսաթիւը տեղի է ունենում մեկնարկի ամսաթուից առաջ
warning-until-date-before-start = Ցուցադրել վերջնաժամկետը, մեկնարկի ամսաթուից առաջ
# The name of the calendar provided with the application by default
home-calendar-name = Տուն
# The name given to a calendar if an opened calendar has an empty filename
untitled-calendar-name = Անանուն աւրացոյց
# Event status: Tentative, Confirmed, Cancelled
# ToDo task status: NeedsAction, InProcess, Completed, Cancelled
status-tentative = Նախնական
status-confirmed = Հաստատուած
event-status-cancelled = Չեղարկուած
todo-status-cancelled = Չեղարկուած
status-needs-action = Անհրաժեշտ են գործողութիւններ
status-in-process = Ընթացքում է
status-completed = Կատարուած է
# Task priority, these should match the calendar-priority-* levels
high-priority = Բարձր
normal-priority = Միջին
low-priority = Ցածր
status-priority-img-high-priority =
    .alt = Բարձր
status-priority-img-normal-priority =
    .alt = Միջին
status-priority-img-low-priority =
    .alt = Ցածր
import-prompt = Ո՞ր աւրացոյցում էք ցանկանում աւելացնել տարրերը։
export-prompt = Ո՞ր աւրացոյցից էք ցանկանում արտածել։
publish-prompt = Ո՞ր աւրացոյցն էք ուզում հրապարակել։
# LOCALIZATION NOTE (paste-and-notify-label): button label used in calendar prompt
# of the pasted item has attendees
paste-and-notify-label = Տեղադրել եւ ուղարկել հիմա
# LOCALIZATION NOTE (paste-dont-notify-label): button label used in calendar prompt
# of the pasted item has attendees
paste-dont-notify-label = Տեղադրել առանց ուղարկելու
day-header-elem =
    .label = { day-header }
# Used in the main menu and contextual menus.
calendar-context-today-pane =
    .label = Այսաւրուայ փեղկ
    .accesskey = T
calendar-context-open-event =
    .label = Բացել
    .accesskey = Բ
calendar-context-open-task =
    .label = Բացել առաջադրանքը…
    .accesskey = Բ
calendar-context-new-event =
    .label = Նոր իրադարձութիւն…
    .accesskey = Ն
calendar-context-new-task =
    .label = Նոր առաջադրանք…
    .accesskey = ք
calendar-context-delete-task =
    .label = Ջնջել առաջադրանքը
    .accesskey = l
calendar-context-delete-event =
    .label = Ջնջել իրադարձութիւնը
    .accesskey = l
calendar-context-cut =
    .label = Կտրել
    .accesskey = t
calendar-context-copy =
    .label = Պատճէնել
    .accesskey = C
calendar-context-paste =
    .label = Դնել
    .accesskey = Դ
calendar-taskview-delete =
    .label = Ջնջել
    .tooltiptext = Ջնջել առաջադրանքը
calendar-context-attendance-menu =
    .label = Մասնակցութիւն
    .accesskey = d
calendar-context-attendance-occurrence =
    .label = Այս դէպքը
calendar-context-attendance-all-series =
    .label = Աւարտել շարքերը
calendar-context-attendance-send =
    .label = Ուղարկել ծանուցում հիմա
    .accesskey = S
calendar-context-attendance-dontsend =
    .label = Չուղարկել ծանուցում
    .accesskey = D
calendar-context-attendance-occ-accepted =
    .label = Ընդունուած
    .accesskey = A
calendar-context-attendance-occ-tentative =
    .label = Նախնական ընդունուած է
    .accesskey = y
calendar-context-attendance-occ-declined =
    .label = Մերժուած
    .accesskey = c
calendar-context-attendance-occ-delegated =
    .label = Պատուիրակուած
    .accesskey = g
calendar-context-attendance-occ-needs-action =
    .label = Գործողութեան սպասելիս
    .accesskey = S
calendar-context-attendance-occ-in-progress =
    .label = Ընթացքում
    .accesskey = I
calendar-context-attendance-occ-completed =
    .label = Կատարուած
    .accesskey = C
calendar-context-attendance-all-accepted =
    .label = Ընդունուած
    .accesskey = e
calendar-context-attendance-all-tentative =
    .label = Նախնական ընտրուած է
    .accesskey = v
calendar-context-attendance-all-declined =
    .label = Մերժուած
    .accesskey = d
calendar-context-attendance-all-delegated =
    .label = Պատուիրակուած
    .accesskey = l
calendar-context-attendance-all-needs-action =
    .label = Գործողութեան սպասելիս
    .accesskey = l
calendar-context-attendance-all-in-progress =
    .label = Ընթացքում
    .accesskey = p
calendar-context-attendance-all-completed =
    .label = Կատարուած
    .accesskey = m
calendar-context-progress =
    .label = Առաջընթաց
    .accesskey = P
calendar-context-postpone =
    .label = Յետաձգել առաջադրանքը
    .accesskey = s
calendar-context-postpone-1hour =
    .label = 1 Ժամ
    .accesskey = Բ
calendar-context-postpone-1day =
    .label = 1 Աւր
    .accesskey = D
calendar-context-postpone-1week =
    .label = 1 Շաբաթ
    .accesskey = W
calendar-context-new-server =
    .label = Նոր աւրացոյց…
    .accesskey = N
calendar-context-delete-server =
    .label = Ջնջել աւրացոյցը…
    .accesskey = D
calendar-context-remove-server =
    .label = Հեռացնել աւրացոյցը…
    .accesskey = R
calendar-context-unsubscribe-server =
    .label = Ապաբաժանորդագրուել աւրացոյցից…
    .accesskey = U
calendar-context-publish =
    .label = Հրապարակել աւրացոյցը…
    .accesskey = b
calendar-context-export =
    .label = Արտածել աւրացոյցը…
    .accesskey = E
calendar-context-properties =
    .label = Յատկութիւններ
    .accesskey = P
calendar-context-showall =
    .label = Ցուցադրել բոլոր աւրացոյցները
    .accesskey = A
calendar-context-convert-menu =
    .label = Փոխակերպել
    .accesskey = v
calendar-context-convert-to-event =
    .label = Իրադարձութիւն…
    .accesskey = E
calendar-context-convert-to-message =
    .label = Հաղորդագրութիւն…
    .accesskey = M
calendar-context-convert-to-task =
    .label = Առաջադրանք…
    .accesskey = T
calendar-task-filter-title = Ցուցադրել
calendar-task-filter-all =
    .label = Բոլորը
    .accesskey = A
calendar-task-filter-today =
    .label = Այսաւր
    .accesskey = T
calendar-task-filter-next7days =
    .label = Յաջորդ եւթ աւրերը
    .accesskey = N
calendar-task-filter-notstarted =
    .label = Չսկսուած առաջադրանքներ
    .accesskey = a
calendar-task-filter-overdue =
    .label = Ուշացած առաջադրանքներ
    .accesskey = O
calendar-task-filter-completed =
    .label = Կատարուած առաջադրանքներ
    .accesskey = C
calendar-task-filter-open =
    .label = Անաւարտ առաջադրանքներ
    .accesskey = m
# LOCALIZATION NOTE (calendar-task-filter-current):
# "Current Tasks" shows all tasks except those starting in the future.
calendar-task-filter-current =
    .label = Ընթացիկ առաջադրանքներ
    .accesskey = u
calendar-task-details-title = վերնագիր
calendar-task-details-organizer = ից
calendar-task-details-priority = առաջնահերթութիւն
calendar-task-details-priority-low = Ցածր
calendar-task-details-priority-normal = Միջին
calendar-task-details-priority-high = Բարձր
calendar-task-details-status = Կարգավիճակ
calendar-task-details-category = անուանակարգ
calendar-task-details-repeat = կրկնել
calendar-task-details-attachments = կցորդներ
calendar-task-details-start = մեկնարկի ամսաթիւ
calendar-task-details-due = վերջնաժամկէտ
calendar-task-mark-completed =
    .label = Նշել կատարուած
    .accesskey = o
    .tooltiptext = Նշել ընտրուած առաջադրանքները՝ որպէս աւարտուած
calendar-task-change-priority =
    .label = Առաջնահերթութիւն
    .accesskey = r
    .tooltiptext = Փոխել առաջնահերթութիւնը
calendar-task-text-filter-field =
    .emptytextbase = Զտել առաջադրանքերը #1
    .keylabelnonmac = <Ctrl+Shift+K>
    .keylabelmac = <⇧⌘K>
calendar-copylink =
    .label = Պատճէնել յղման հասցէն
    .accesskey = C
calendar-progress-level-0 =
    .label = 0 % Կատարուած
    .accesskey = 0
calendar-progress-level-25 =
    .label = 25 % Կատարուած
    .accesskey = 2
calendar-progress-level-50 =
    .label = 50 % Կատարուած
    .accesskey = 5
calendar-progress-level-75 =
    .label = 75% Կատարուած
    .accesskey = 7
calendar-progress-level-100 =
    .label = 100% Կատարուած
    .accesskey = 1
calendar-priority-none =
    .label = Յատկորոշուած չէ
    .accesskey = յ
calendar-priority-low =
    .label = Ցածր
    .accesskey = L
calendar-priority-normal =
    .label = Միջին
    .accesskey = Մ
calendar-priority-high =
    .label = Բարձր
    .accesskey = Բ
calendar-tasks-view-minimonth =
    .label = Փոքր֊ամիս
    .accesskey = M
calendar-tasks-view-calendarlist =
    .label = Աւրացոյցի ցուցակ
    .accesskey = L
calendar-tasks-view-filtertasks =
    .label = Զտել առաջադրանքները
    .accesskey = F
calendar-properties-color =
    .value = Գոյն՝
calendar-properties-location =
    .value = Տեղ՝
calendar-properties-refresh =
    .value = Թարմացնել Աւրացոյցը
calendar-properties-refresh-manual =
    .label = Ձեռքով
calendar-properties-read-only =
    .label = Read Only
calendar-properties-show-reminders =
    .label = Ցուցադրել յիշեցումները
calendar-properties-offline-support =
    .label = Անցանց աջակցութիւն
calendar-properties-enable-calendar =
    .label = Միացնել այս աւրացոյցը
calendar-properties-provider-missing = Այս աւրացոյցի համար մատակարար չի գտնուել։ Սա պատահում է, երբ Դուք անջատել կամ ապատեղակայել էք որոշ յաւելուածներ։
calendar-properties-unsubscribe =
    .label = Ապաբաժանորդագրուել
    .accesskey = Ա
    .buttonlabelextra1 = Ապաբաժանորդագրուել
    .buttonaccesskeyextra1 = Ա
calendar-alarm-dialog-title = Աւրացոյցի յիշեցումներ
calendar-alarm-details =
    .value = Մանրամասներ…
calendar-alarm-dismiss =
    .label = Բաց թողնել
calendar-alarm-dismiss-all =
    .label = Բաց թողնել բոլորը
calendar-alarm-snooze-for =
    .label = Ննջեցնել
calendar-alarm-snooze-all-for =
    .label = Ննջեցնել բոլորը
# LOCALIZATION NOTE (calendar-alarm-snooze-cancel):
# This string is not visible in the UI. It is read by screen readers when the
# user focuses the "Cancel" button in the "Snooze for..." popup of the alarm dialog.
calendar-alarm-snooze-cancel =
    .aria-label = Չեղարկել ննջեցումը
calendar-calendar =
    .label = Աւրացոյց
    .accesskey = C
calendar-newevent-button =
    .label = Նոր իրադարձութիւն
    .tooltiptext = Նոր իրադարձութիւն
calendar-newtask-button =
    .label = Նոր առաջադրանք
    .tooltiptext = Ստեղծել նոր առաջադրանք
calendar-unifinder-show-completed-todos =
    .label = Ցուցադրել կատարուած առաջադրանքները
calendar-display-todos-checkbox =
    .label = Առաջադրանքների դիտում
    .accesskey = k
calendar-completed-tasks-checkbox =
    .label = Ցուցադրել կատարուած առաջադրանքները
    .accesskey = c
calendar-only-workday-checkbox =
    .label = Միայն աշխատանքային աւրեր
    .accesskey = r
calendar-orientation =
    .label = Շրջել տեսքը
    .accesskey = o
calendar-search-options-searchfor =
    .value = Պարունակի
calendar-server-dialog-title-edit =
    .title = Խմբագրել Աւրացոյցը
calendar-server-dialog-name-label =
    .value = Աւրացոյցի Անունը՝
calendar-publish-dialog-title =
    .title = Հրապարակել Աւրացոյցը
calendar-publish-url-label = Հրապարակել ցանցամիջոցների համընդհանուր տեղորոշիչը
calendar-publish-publish-button = Հրապարակել
calendar-publish-close-button = Փակել
calendar-select-dialog-title = Ընտրել Աւրացոյցը
calendar-error-detail =
    .label = Մանրամասներ…
calendar-error-code =
    .value = Սխալի այլագիր՝
calendar-error-description =
    .value = Նկարագրութիւն
calendar-error-title =
    .title = Սխալ յայտնուեց
calendar-extract-event-button =
    .label = Աւելացնել որպէս իրադարձութիւն
    .tooltiptext = Հանէ՛ք աւրացոյցի տեղեկութիւնը հաղորդագրութիւնից եւ աւելացրէ՛ք այն ձեր աւրացոյցում`որպէս իրադարձութիւն
calendar-extract-task-button =
    .label = Աւելացնել որպէս առաջադրանք
    .tooltiptext = Հանէ՛ք աւրացոյցի տեղեկութիւնը հաղորդագրութիւնից եւ աւելացրէ՛ք այն ձեր աւրացոյցում որպէս առաջադրանք
