# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Վերնագիր
calendar-item-summary-calendar = Աւրացոյց
calendar-item-summary-task-start = Սկզբի ամսաթիւ՝
calendar-item-summary-event-start = Սկզբի ամսաթիւ՝
calendar-item-summary-task-due = Վերջնաժամկէտ՝
calendar-item-summary-event-end = Աւարտի ամսաթիւ՝
calendar-item-summary-repeat = Կրկնութիւն՝
calendar-item-summary-location = Տեղ՝
calendar-item-summary-category = Անուանակարգ՝
calendar-item-summary-organizer = Կազմակերպիչ՝
calendar-item-summary-status = Կարգավիճակ՝
calendar-item-summary-reminder = Յիշեցում՝
calendar-item-summary-attachments = Կցորդներ՝
calendar-item-summary-reminder-none =
    .label = Յիշեցում չկայ
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 րոպէ մինչ
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 րոպէ մինչ
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 րոպէ մինչ
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 րոպէ մինչ
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ժամ մինչ
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ժամ մինչ
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ժամ մինչ
calendar-item-summary-reminder-1-day-before =
    .label = 1 աւր մինչ
calendar-item-summary-reminder-2-days-before =
    .label = 2 աւր մինչ
calendar-item-summary-reminder-1-week-before =
    .label = 1 շաբաթ մինչ
calendar-item-summary-reminder-custom =
    .label = Ընտրել…
calendar-item-summary-reminder-multiple =
    .value = Բազմակի յիշեցումներ…
calendar-item-summary-general =
    .value = Գլխաւոր
calendar-item-summary-attendees =
    .value = Մասնակիցներ
calendar-item-summary-description =
    .value = Նկարագրութիւն
calendar-item-summary-link =
    .value = Առնչուող յղում
