# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentár
calendar-item-summary-title = Názov:
calendar-item-summary-calendar = Kalendár:
calendar-item-summary-task-start = Dátum začatia:
calendar-item-summary-event-start = Dátum začatia:
calendar-item-summary-task-due = Termín splnenia:
calendar-item-summary-event-end = Dátum ukončenia:
calendar-item-summary-repeat = Opakovanie:
calendar-item-summary-location = Miesto konania:
calendar-item-summary-category = Kategória:
calendar-item-summary-organizer = Organizátor:
calendar-item-summary-status = Stav:
calendar-item-summary-reminder = Pripomienka:
calendar-item-summary-attachments = Prílohy:
calendar-item-summary-status-tentative = Predbežná
calendar-item-summary-status-confirmed = Potvrdená
calendar-item-summary-event-status-cancelled = Zrušená
calendar-item-summary-todo-status-cancelled = Zrušená
calendar-item-summary-status-needs-action = Vyžaduje akciu
calendar-item-summary-status-in-process = Prebieha
calendar-item-summary-status-completed = Dokončená
calendar-item-summary-reminder-none =
    .label = Nepripomínať
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minút pred
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minút pred
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minút pred
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minút pred
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hodinu pred
calendar-item-summary-reminder-2-hours-before =
    .label = 2 hodiny pred
calendar-item-summary-reminder-12-hours-before =
    .label = 12 hodín pred
calendar-item-summary-reminder-1-day-before =
    .label = 1 deň pred
calendar-item-summary-reminder-2-days-before =
    .label = 2 dni pred
calendar-item-summary-reminder-1-week-before =
    .label = 1 týždeň pred
calendar-item-summary-reminder-custom =
    .label = Vlastné…
calendar-item-summary-reminder-multiple =
    .value = Viacnásobné pripomienky…
calendar-item-summary-general =
    .value = Všeobecné
calendar-item-summary-attendees =
    .value = Účastníci
calendar-item-summary-description =
    .value = Popis
calendar-item-summary-link =
    .value = Súvisiaci odkaz
