# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = 弹性空白
search-bar-label = 搜索
toolbar-write-message-label = 新建消息
toolbar-write-message =
    .title = 创建新消息
toolbar-move-to-label = 移动到
toolbar-move-to =
    .title = 移动选中的消息
toolbar-unifinder-label = 查找事件
toolbar-unifinder =
    .title = 切换查找事件窗格
toolbar-folder-location-label = 文件夹地址
toolbar-folder-location =
    .title = 切换到文件夹
toolbar-edit-event-label = 编辑
toolbar-edit-event =
    .title = 编辑选中的事件或任务
toolbar-get-messages-label = 收取邮件
toolbar-get-messages =
    .title = 收取所有账户的新消息
toolbar-reply-label = 回复
toolbar-reply =
    .title = 回复消息
toolbar-reply-all-label = 全部回复
toolbar-reply-all =
    .title = 回复发件人和所有收件人
toolbar-reply-to-list-label = 回复至列表
toolbar-reply-to-list =
    .title = 回复至邮件列表
toolbar-redirect-label = 重定向
toolbar-redirect =
    .title = 将选择的消息重定向
toolbar-archive-label = 归档
toolbar-archive =
    .title = 归档选中的消息
toolbar-conversation-label = 对话
toolbar-conversation =
    .title = 显示选定消息的对话
toolbar-previous-unread-label = 上一条未读
toolbar-previous-unread =
    .title = 转到上一条未读消息
toolbar-previous-label = 上一个
toolbar-previous =
    .title = 移动到上一条信息
toolbar-next-unread-label = 下一条未读
toolbar-next-unread =
    .title = 转至下一条未读消息
toolbar-next-label = 下一个
toolbar-next =
    .title = 移动到下一条信息
toolbar-junk-label = 是垃圾邮件
toolbar-junk =
    .title = 将选择的消息标记为垃圾邮件
toolbar-delete-label = 删除
toolbar-delete-title =
    .title = 删除选定的消息
toolbar-undelete-label = 撤消删除
toolbar-undelete =
    .title = 撤销删除选定的消息
toolbar-compact-label = 压缩
toolbar-compact =
    .title = 从选中文件夹移除已删除消息
toolbar-add-as-event-label = 作为事件添加
toolbar-add-as-event =
    .title = 从消息中提取日历信息并作为事件添加到你的日历中
toolbar-add-as-task-label = 作为任务添加
toolbar-add-as-task =
    .title = 从消息中提取日历信息并作为任务添加到你的日历中
toolbar-tag-message-label = 标签
toolbar-tag-message =
    .title = 为消息添加标签
toolbar-forward-inline-label = 转发
toolbar-forward-inline =
    .title = 作为内联文本转发选中的消息
toolbar-forward-attachment-label = 作为附件转发
toolbar-forward-attachment =
    .title = 作为附件转发选中的消息
toolbar-mark-as-label = 标记
toolbar-mark-as =
    .title = 标记消息
toolbar-view-picker-label = 视图
toolbar-view-picker =
    .title = 自定义当前文件夹的显示方式
toolbar-address-book-label = 通讯录
toolbar-address-book =
    .title = 转到通讯录
toolbar-chat-label = 聊天
toolbar-chat =
    .title = 显示聊天页
toolbar-add-ons-and-themes-label = 扩展和主题
toolbar-add-ons-and-themes =
    .title = 管理您的附加组件
toolbar-calendar-label = 日历
toolbar-calendar =
    .title = 切换到日历选项卡
toolbar-tasks-label = 任务
toolbar-tasks =
    .title = 切换到任务选项卡
toolbar-mail-label = 邮件
toolbar-mail =
    .title = 切换到邮件标签页
toolbar-print-label = 打印
toolbar-print =
    .title = 打印此消息
toolbar-quick-filter-bar-label = 快速筛选
toolbar-quick-filter-bar =
    .title = 筛选消息
toolbar-synchronize-label = 同步
toolbar-synchronize =
    .title = 重新加载日历并同步变更
toolbar-delete-event-label = 删除
toolbar-delete-event =
    .title = 删除选中的事件或任务
toolbar-go-to-today-label = 转至今日
toolbar-go-to-today =
    .title = 转至今天
toolbar-print-event-label = 打印
toolbar-print-event =
    .title = 打印事件或任务
toolbar-new-event-label = 事件
toolbar-new-event =
    .title = 创建新事件
toolbar-new-task-label = 任务
toolbar-new-task =
    .title = 创建新任务
toolbar-go-back-label = 后退
toolbar-go-back =
    .title = 后退至上一条消息
toolbar-go-forward-label = 前进
toolbar-go-forward =
    .title = 前进至下一条消息
toolbar-stop-label = 停止
toolbar-stop =
    .title = 停止当前的传输
toolbar-throbber-label = 活动指示器
toolbar-throbber =
    .title = 活动指示器
toolbar-create-contact-label = 新联系人
toolbar-create-contact =
    .title = 新建联系人
toolbar-create-address-book-label = 新通讯录
toolbar-create-address-book =
    .title = 新建通讯录
toolbar-create-list-label = 新列表
toolbar-create-list =
    .title = 新建邮件列表
toolbar-import-contacts-label = 导入
toolbar-import-contacts =
    .title = 从文件导入联系人

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = 添加本地通讯录
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = 添加 CardDAV 通讯录
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = 添加 LDAP 通讯录
