# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Søger…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 forekomst fundet;#1 forekomster fundet
noMatchesFound = Ingen forekomster fundet
labelForStopButton = Stop
labelForSearchButton = Søg
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = S
moreButtonTooltipText = Tilføj ny regel
lessButtonTooltipText = Fjern denne regel
