# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Tineɣremt
calendar-item-summary-calendar = Awitay:
calendar-item-summary-task-start = Azemz n tazwara:
calendar-item-summary-event-start = Azemz n tazwara:
calendar-item-summary-task-due = Azemz n tagara:
calendar-item-summary-event-end = Azemz n tagara
calendar-item-summary-repeat = Tisnilas:
calendar-item-summary-location = Adig
calendar-item-summary-category = Taggayt:
calendar-item-summary-organizer = Suddes
calendar-item-summary-status = Addad:
calendar-item-summary-reminder = Asmekti:
calendar-item-summary-attachments = Imeddayen:
calendar-item-summary-status-tentative = Askudan
calendar-item-summary-status-confirmed = Yettwasentem
calendar-item-summary-event-status-cancelled = Yettwasefsex
calendar-item-summary-todo-status-cancelled = Yettwasefsex
calendar-item-summary-status-needs-action = Isra tigawt
calendar-item-summary-status-in-process = Iteddu akka tura
calendar-item-summary-status-completed = Yemmed di
calendar-item-summary-reminder-none =
    .label = ulac asmekti
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 Dqiqa Uqbel
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 Dqayeq uqbel
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 Dqayeq uqbel
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 Dqayeq uqbel
calendar-item-summary-reminder-1-hour-before =
    .label = 1 asrag uqbel
calendar-item-summary-reminder-2-hours-before =
    .label = 2 n yesragen uqbel
calendar-item-summary-reminder-12-hours-before =
    .label = 12 n yesragen uqbel
calendar-item-summary-reminder-1-day-before =
    .label = 1 n wass uqbel
calendar-item-summary-reminder-2-days-before =
    .label = 2 n wussan uqbel
calendar-item-summary-reminder-1-week-before =
    .label = 1 n ddurt uqbel
calendar-item-summary-reminder-custom =
    .label = Sagen…
calendar-item-summary-reminder-multiple =
    .value = Deqs n ismektiyen…
calendar-item-summary-general =
    .value = Amatu
calendar-item-summary-attendees =
    .value = Imttekkiyen
calendar-item-summary-description =
    .value = Aglam
calendar-item-summary-link =
    .value = Aseɣwen i d-yettuɣalen
