# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Teygjanlegt bil
search-bar-label = Leita
toolbar-write-message-label = Skrifa
toolbar-write-message =
    .title = Búa til nýjan póst
toolbar-move-to-label = Færa í
toolbar-move-to =
    .title = Færa valin skilaboð
toolbar-unifinder-label = Finna atburði
toolbar-unifinder =
    .title = Víxla flipa fyrir leita að atburðum
toolbar-folder-location-label = Möppustaðsetning
toolbar-folder-location =
    .title = Skipta yfir í möppu
toolbar-edit-event-label = Breyta
toolbar-edit-event =
    .title = Breyta völdum atburðum eða verkefnum
toolbar-get-messages-label = Ná í póst
toolbar-get-messages =
    .title = Sækja ný skilaboð fyrir alla reikninga
toolbar-reply-label = Svara
toolbar-reply =
    .title = Svara pósti
toolbar-reply-all-label = Svara öllum
toolbar-reply-all =
    .title = Svara sendanda og öllum viðtakendum
toolbar-reply-to-list-label = Svara póstlista
toolbar-reply-to-list =
    .title = Svara póstlista
toolbar-redirect-label = Endurbeina
toolbar-redirect =
    .title = Endurbeina völdum skilaboðum
toolbar-archive-label = Skjalageymsla
toolbar-archive =
    .title = Setja valinn póst í skjalageymslu
toolbar-conversation-label = Samtal
toolbar-conversation =
    .title = Sýna samtal valinna skilaboða
toolbar-previous-unread-label = Fyrri ólesin
toolbar-previous-unread =
    .title = Fara til baka í fyrri ólesin póst
toolbar-previous-label = Fyrri
toolbar-previous =
    .title = Fara á fyrri skilaboð
toolbar-next-unread-label = Næsta ólesið
toolbar-next-unread =
    .title = Fara yfir á næsta ólesna póst
toolbar-next-label = Næsti
toolbar-next =
    .title = Fara á næstu skilaboð
toolbar-junk-label = Ruslpóstur
toolbar-junk =
    .title = Merkja valin skilaboð sem ruslpóst
toolbar-delete-label = Eyða
toolbar-delete-title =
    .title = Eyða völdum skilaboðum
toolbar-undelete-label = Afturkalla eyðingu
toolbar-undelete =
    .title = Afturkalla eyðingu á völdum skilaboðum
toolbar-compact-label = Þjappa
toolbar-compact =
    .title = Eyða eyddum póstum úr valinni möppu
toolbar-add-as-event-label = Bæta við sem nýjum atburð
toolbar-add-as-event =
    .title = Ná í dagsetningar úr póstinum og bæta við í dagatalið sem atburð
toolbar-add-as-task-label = Bæta við verkefni
toolbar-add-as-task =
    .title = Ná í dagsetningar úr póstinum og bæta við í dagatalið sem verkefni
toolbar-tag-message-label = Merki
toolbar-tag-message =
    .title = Merkja skilaboð
toolbar-forward-inline-label = Áfram
toolbar-forward-inline =
    .title = Áframsenda valda pósta sem innfelldan texta
toolbar-forward-attachment-label = Áframsenda sem viðhengi
toolbar-forward-attachment =
    .title = Áframsenda valda pósta sem viðhengi
toolbar-mark-as-label = Merkja
toolbar-mark-as =
    .title = Merkja póst
toolbar-view-picker-label = Skoða
toolbar-view-picker =
    .title = Sérsníða ásýn núverandi möppu
toolbar-address-book-label = Nafnaskrá
toolbar-address-book =
    .title = Fara í nafnaskrá
toolbar-chat-label = Spjall
toolbar-chat =
    .title = Sýna spjallflipann
toolbar-add-ons-and-themes-label = Viðbætur og þemu
toolbar-add-ons-and-themes =
    .title = Sýsla með viðbæturnar þínar
toolbar-calendar-label = Dagatal
toolbar-calendar =
    .title = Skipta yfir í dagatalsflipa
toolbar-tasks-label = Verkefni
toolbar-tasks =
    .title = Skipta yfir í verkefnaflipa
toolbar-mail-label = Póstur
toolbar-mail =
    .title = Skipta yfir í póstflipa
toolbar-print-label = Prenta
toolbar-print =
    .title = Prenta þennan póst
toolbar-quick-filter-bar-label = Flýtisía
toolbar-quick-filter-bar =
    .title = Sía skilaboð
toolbar-synchronize-label = Samstilla
toolbar-synchronize =
    .title = Endurnýja dagatöl og samstilla breytingar
toolbar-delete-event-label = Eyða
toolbar-delete-event =
    .title = Eyða völdum atburðum eða verkefnum
toolbar-go-to-today-label = Hoppa á daginn í dag
toolbar-go-to-today =
    .title = Hoppa á daginn í dag
toolbar-print-event-label = Prenta
toolbar-print-event =
    .title = Prenta atburði eða verkefni
toolbar-new-event-label = Atburður
toolbar-new-event =
    .title = Búa til nýjan atburð
toolbar-new-task-label = Verkefni
toolbar-new-task =
    .title = Búa til nýtt verkefni
toolbar-go-back-label = Til baka
toolbar-go-back =
    .title = Til baka um einn póst
toolbar-go-forward-label = Áfram
toolbar-go-forward =
    .title = Áfram um einn póst
toolbar-stop-label = Stöðva
toolbar-stop =
    .title = Stöðva núverandi sendingu
toolbar-throbber-label = Virknimælir
toolbar-throbber =
    .title = Virknimælir
toolbar-create-contact-label = Nýr tengiliður
toolbar-create-contact =
    .title = Búa til nýjan tengilið
toolbar-create-address-book-label = Ný nafnaskrá
toolbar-create-address-book =
    .title = Búa til nýja nafnaskrá
toolbar-create-list-label = Nýr listi
toolbar-create-list =
    .title = Búa til nýjan póstlista
toolbar-import-contacts-label = Flytja inn
toolbar-import-contacts =
    .title = Flytja tengiliði inn úr skrá

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Bæta við staðbundinni nafnaskrá
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Bæta við CardDAV-nafnaskrá
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Bæta við LDAP-nafnaskrá
