# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Spatio flexibile
search-bar-label = Cercar
toolbar-write-message-label = Scriber
toolbar-write-message =
    .title = Crear un nove message
toolbar-move-to-label = Mover a
toolbar-move-to =
    .title = Mover message seligite
toolbar-unifinder-label = Trovar eventos
toolbar-unifinder =
    .title = Mutar le quadro trova eventos
toolbar-folder-location-label = Loco del dossier
toolbar-folder-location =
    .title = Passar al plica
toolbar-edit-event-label = Rediger
toolbar-edit-event =
    .title = Rediger evento o activitate seligite
toolbar-get-messages-label = Reciper messages
toolbar-get-messages =
    .title = Reportar nove messages pro tote le contos
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder al message
toolbar-reply-all-label = Responder a totes
toolbar-reply-all =
    .title = Responder al expeditor e a tote le destinatarios
toolbar-reply-to-list-label = Responder al lista
toolbar-reply-to-list =
    .title = Responder al lista de diffusion
toolbar-redirect-label = Re-diriger
toolbar-redirect =
    .title = Re-dirige le message seligite
toolbar-archive-label = Archivo
toolbar-archive =
    .title = Archivar le messages seligite
toolbar-conversation-label = Conversatione
toolbar-conversation =
    .title = Monstrar conversation del message seligite
toolbar-previous-unread-label = Non legite precedente
toolbar-previous-unread =
    .title = Mover al message precedente non legite
toolbar-previous-label = Previe
toolbar-previous =
    .title = Mover al message precedente
toolbar-next-unread-label = Non legite sequente
toolbar-next-unread =
    .title = Mover al message sequente non legite
toolbar-next-label = Sequente
toolbar-next =
    .title = Mover al message sequente
toolbar-junk-label = Indesirate
toolbar-junk =
    .title = Marcar le messages sequente como indesiderate
toolbar-delete-label = Deler
toolbar-delete-title =
    .title = Deler le messages selecte
toolbar-undelete-label = Restabilir
toolbar-undelete =
    .title = Restaurar les messages seligite
toolbar-compact-label = Compacte
toolbar-compact =
    .title = Remover le messages delite del dossier seligite
toolbar-add-as-event-label = Adder como evento
toolbar-add-as-event =
    .title = Extraher informationes de agenda a partir del message e adder a tu agenda como evento
toolbar-add-as-task-label = Adder como activitate
toolbar-add-as-task =
    .title = Extraher informationes de agenda a partir del message e adder a tu agenda como activitate
toolbar-tag-message-label = Etiquetta
toolbar-tag-message =
    .title = Messages de tags
toolbar-forward-inline-label = Inviar ultra
toolbar-forward-inline =
    .title = Inviar ultra le message seligite como parte del texto del message
toolbar-forward-attachment-label = Inviar ultra como annexo
toolbar-forward-attachment =
    .title = Inviar ultra le message seligite como annexo
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar messages
toolbar-view-picker-label = Vider
toolbar-view-picker =
    .title = Personalisar vista del plica actual
toolbar-address-book-label = Libro del adresses
toolbar-address-book =
    .title = Va al libro del adresses
toolbar-chat-label = Chat
toolbar-chat =
    .title = Monstrar le scheda Chat
toolbar-add-ons-and-themes-label = Additivos e themas
toolbar-add-ons-and-themes =
    .title = Gere tu additivos
toolbar-calendar-label = Agenda
toolbar-calendar =
    .title = Mutar al scheda del agenda
toolbar-tasks-label = Activitates
toolbar-tasks =
    .title = Cambiar al scheda de activitates
toolbar-mail-label = Email
toolbar-mail =
    .title = Passar al scheda del posta
toolbar-print-label = Imprimer
toolbar-print =
    .title = Imprimer iste message
toolbar-quick-filter-bar-label = Filtro rapide
toolbar-quick-filter-bar =
    .title = Filtrar le messages
toolbar-synchronize-label = Synchronisar
toolbar-synchronize =
    .title = Recargar agendas e synchronisar le cambios
toolbar-delete-event-label = Deler
toolbar-delete-event =
    .title = Deler evento o activitate seligite
toolbar-go-to-today-label = Ir a hodie
toolbar-go-to-today =
    .title = Ir a hodie
toolbar-print-event-label = Imprimer
toolbar-print-event =
    .title = Imprimer eventos o activitates
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Crear un nove evento
toolbar-new-task-label = Activitate
toolbar-new-task =
    .title = Crear un nove activitate
toolbar-go-back-label = Retro
toolbar-go-back =
    .title = Receder de un message
toolbar-go-forward-label = Inviar ultra
toolbar-go-forward =
    .title = Inviar ultra un message
toolbar-stop-label = Stoppar
toolbar-stop =
    .title = Interrumper le transferentia actual
toolbar-throbber-label = Indicator de activitate
toolbar-throbber =
    .title = Indicator de activitate
toolbar-create-contact-label = Nove contacto
toolbar-create-contact =
    .title = Crear un nove contacto
toolbar-create-address-book-label = Nove libro del adresses
toolbar-create-address-book =
    .title = Crear un nove libro de adresses
toolbar-create-list-label = Nove lista
toolbar-import-contacts-label = Importar
toolbar-import-contacts =
    .title = Importar contactos ab un file

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Adde libro de adresses local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Adde le libro del adresses CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Adder le libro del adresses LDAP
