# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Liikuv tühimik
toolbar-write-message-label = Kirjuta
toolbar-write-message =
    .title = Loo uus kiri
toolbar-unifinder-label = Otsi sündmusi
toolbar-unifinder =
    .title = Lülita sündmuste otsingu paneeli
toolbar-folder-location-label = Kausta asukoht
toolbar-edit-event-label = Muuda
toolbar-edit-event =
    .title = Muuda valitud sündmust või ülesannet
toolbar-get-messages-label = Tõmba kirjad
toolbar-reply-label = Vasta
toolbar-reply =
    .title = Vasta kirjale
toolbar-reply-all-label = Vasta kõigile
toolbar-reply-all =
    .title = Vasta saatjale ja kõigile saajatele
toolbar-reply-to-list-label = Vasta listile
toolbar-reply-to-list =
    .title = Vasta meililistile
toolbar-redirect-label = Suuna ümber
toolbar-redirect =
    .title = Suuna valitud kiri ümber
toolbar-archive-label = Arhiveeri
toolbar-archive =
    .title = Arhiveeri valitud kirjad
toolbar-conversation-label = Vestlus
toolbar-conversation =
    .title = Kuva valitud kirja vestlust
toolbar-previous-unread-label = Eelmine lugemata
toolbar-previous-unread =
    .title = Kuva eelmist lugemata kirja
toolbar-previous-label = Eelmine
toolbar-previous =
    .title = Kuva eelmist kirja
toolbar-next-unread-label = Järgmine lugemata
toolbar-next-unread =
    .title = Kuva järgmist lugemata kirja
toolbar-next-label = Järgmine
toolbar-next =
    .title = Kuva järgmist kirja
toolbar-junk-label = Rämpspost
toolbar-junk =
    .title = R
toolbar-delete-label = Kustuta
toolbar-compact-label = Suru kokku
toolbar-compact =
    .title = Eemalda kustutatud kirjad valitud kaustast
toolbar-add-as-event-label = Lisa sündmusena
toolbar-add-as-event =
    .title = Lisab kirjas oleva info põhjal kalendrisse sündmuse
toolbar-add-as-task-label = Lisa ülesandena
toolbar-add-as-task =
    .title = Lisab kirjas oleva info põhjal kalendrisse ülesande
toolbar-tag-message-label = Sildista
toolbar-tag-message =
    .title = Sildista kirju
toolbar-forward-inline-label = Edasta
toolbar-forward-inline =
    .title = Edasta valitud kiri lihttekstina
toolbar-forward-attachment-label = Edasta manusena
toolbar-forward-attachment =
    .title = Edasta valitud kiri manusena
toolbar-mark-as-label = Märgista
toolbar-mark-as =
    .title = Märgi kiri
toolbar-view-picker-label = Vaade
toolbar-view-picker =
    .title = Kohanda praeguse kausta vaadet
toolbar-address-book =
    .title = Ava aadressiraamat
toolbar-chat-label = Kiirsuhtlus
toolbar-chat =
    .title = Kuva kiirsuhtluse kaarti
toolbar-add-ons-and-themes-label = Lisad ja teemad
toolbar-add-ons-and-themes =
    .title = Halda oma lisasid
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Lülitu kalendri kaardile
toolbar-tasks-label = Ülesanded
toolbar-tasks =
    .title = Lülitu ülesannete kaardile
toolbar-print-label = Prindi
toolbar-print =
    .title = Prindi valitud kiri
toolbar-quick-filter-bar-label = Kiirfilter
toolbar-quick-filter-bar =
    .title = Filtreeri kirju
toolbar-synchronize-label = Sünkroniseeri
toolbar-synchronize =
    .title = Laadi kalendrid uuesti ja sünkroniseeri muudatused
toolbar-delete-event-label = Kustuta
toolbar-delete-event =
    .title = Kustuta valitud sündmused või ülesanded
toolbar-go-to-today-label = Täna
toolbar-go-to-today =
    .title = Liigu tänasele päevale
toolbar-print-event-label = Prindi
toolbar-print-event =
    .title = Prindi sündmused või ülesanded
toolbar-new-event-label = Sündmus
toolbar-new-event =
    .title = Lisa uus sündmus
toolbar-new-task-label = Ülesanne
toolbar-new-task =
    .title = Lisa uus ülesanne
toolbar-go-back-label = Tagasi
toolbar-go-back =
    .title = Mine ühe kirja võrra tagasi
toolbar-go-forward-label = Edasi
toolbar-go-forward =
    .title = Mine ühe kirja võrra edasi
toolbar-stop-label = Peata
toolbar-stop =
    .title = Katkesta andmeedastus
toolbar-throbber-label = Aktiivsuse indikaator
toolbar-throbber =
    .title = Aktiivsuse indikaator
