# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = A pesquisar…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Encontrada #1 ocorrência;Encontradas #1 ocorrências
noMatchesFound = Nenhuma ocorrência encontrada
labelForStopButton = Parar
labelForSearchButton = Pesquisar
labelForStopButton.accesskey = P
labelForSearchButton.accesskey = P
moreButtonTooltipText = Adicionar uma regra
lessButtonTooltipText = Remover esta regra
