# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibelna prózdnota
search-bar-label = Pytać
toolbar-write-message-label = Pisać
toolbar-write-message =
    .title = Nowu powěsć spisać
toolbar-move-to-label = Přesunyć do
toolbar-move-to =
    .title = Wubranu powěsć přesunyć
toolbar-unifinder-label = Podawki namakać
toolbar-unifinder =
    .title = Wobłuk "Podawki namakać" přepinać
toolbar-folder-location-label = Městno rjadowaka
toolbar-folder-location =
    .title = K rjadowakej přeńć
toolbar-edit-event-label = Wobdźěłać
toolbar-edit-event =
    .title = Wubrany podawk abo nadawk wobdźěłać
toolbar-get-messages-label = Powěsće wobstarać
toolbar-get-messages =
    .title = Nowe powěsće za wšě konta wobstarać
toolbar-reply-label = Wotmołwić
toolbar-reply =
    .title = Na powěsć wotmołwić
toolbar-reply-all-label = Wšěm wotmołwić
toolbar-reply-all =
    .title = Wotpósłarjej a wšěm přijimarjam wotmołwić
toolbar-reply-to-list-label = Lisćinje wotmołwić
toolbar-reply-to-list =
    .title = Rozesyłanskej lisćinje wotmołwić
toolbar-redirect-label = Hinak wodźić
toolbar-redirect =
    .title = Wubranu powěsć hinak wodźić
toolbar-archive-label = Archiw
toolbar-archive =
    .title = Wubrane powěsće archiwować
toolbar-conversation-label = Rozmołwa
toolbar-conversation =
    .title = Konwersaciju wubraneje powěsće pokazać
toolbar-previous-unread-label = Předchadna njepřečitana
toolbar-previous-unread =
    .title = K předchadnej njepřečitanej powěsći
toolbar-previous-label = Předchadny
toolbar-previous =
    .title = K předchadnej powěsći přesunyć
toolbar-next-unread-label = Přichodna njepřečitana
toolbar-next-unread =
    .title = K přichodnej njepřečitanej powěsći
toolbar-next-label = Přichodny
toolbar-next =
    .title = K přichodnej powěsći přesunyć
toolbar-junk-label = Čapor
toolbar-junk =
    .title = Wubrane powěsće jako čapor markěrować
toolbar-delete-label = Zhašeć
toolbar-delete-title =
    .title = Wubrane powěsće zhašeć
toolbar-undelete-label = Wobnowić
toolbar-undelete =
    .title = Wubrane powěsće wobnowić
toolbar-compact-label = Zhusćić
toolbar-compact =
    .title = Zhašane powěsće z wubraneho rjadowaka wotstronić
toolbar-add-as-event-label = Jako podawk přidać
toolbar-add-as-event =
    .title = Protykowe informacije z powěsće ekstrahować a je wašej protyce jako podawk přidać
toolbar-add-as-task-label = Jako nadawk přidać
toolbar-add-as-task =
    .title = Protykowe informacije z powěsće ekstrahować a je wašej protyce jako nadawk přidać
toolbar-tag-message-label = Značka
toolbar-tag-message =
    .title = Powěsće markěrować
toolbar-forward-inline-label = Dale sposrědkować
toolbar-forward-inline =
    .title = Wubranu Powěsć jako zasadźeny tekst dale sposrědkować
toolbar-forward-attachment-label = Jako přiwěšk dale sposrědkować
toolbar-forward-attachment =
    .title = Wubranu Powěsć jako přiwěšk dale sposrědkować
toolbar-mark-as-label = Markěrować
toolbar-mark-as =
    .title = Powěsće markěrować
toolbar-view-picker-label = Napohlad
toolbar-view-picker =
    .title = Napohlad aktualneho rjadowaka přiměrić
toolbar-address-book-label = Adresnik
toolbar-address-book =
    .title = K adresnikej
toolbar-chat-label = Chat
toolbar-chat =
    .title = Chatowy rajtark pokazać
toolbar-add-ons-and-themes-label = Přidatki a drasty
toolbar-add-ons-and-themes =
    .title = Waše přidatki rjadować
toolbar-calendar-label = Protyka
toolbar-calendar =
    .title = K protykowemu rajtarkej přepinać
toolbar-tasks-label = Nadawki
toolbar-tasks =
    .title = K nadawkowemu rajtarkej přepinać
toolbar-mail-label = E-mejl
toolbar-mail =
    .title = K e-mejlowemu rajtarkej přeńć
toolbar-print-label = Ćišćeć
toolbar-print =
    .title = Tutu powěsć ćišćeć
toolbar-quick-filter-bar-label = Spěšny filter
toolbar-quick-filter-bar =
    .title = Powěsće filtrować
toolbar-synchronize-label = Synchronizować
toolbar-synchronize =
    .title = Protyki znowa začitać a změny synchronizować
toolbar-delete-event-label = Zhašeć
toolbar-delete-event =
    .title = Wubrane podawki abo nadawki zhašeć
toolbar-go-to-today-label = K dźensnišemu
toolbar-go-to-today =
    .title = K dźensnišemu
toolbar-print-event-label = Ćišćeć
toolbar-print-event =
    .title = Podawki abo nadawki ćišćeć
toolbar-new-event-label = Podawk
toolbar-new-event =
    .title = Nowy podawk wutworić
toolbar-new-task-label = Nadawk
toolbar-new-task =
    .title = Nowy nadawk wutworić
toolbar-go-back-label = Wróćo
toolbar-go-back =
    .title = Wo jednu powěsć wróćo
toolbar-go-forward-label = Dale
toolbar-go-forward =
    .title = Wo jednu powěsć doprědka
toolbar-stop-label = Stój
toolbar-stop =
    .title = Aktualne přenjesenje zastajić
toolbar-throbber-label = Pokazowar aktiwity
toolbar-throbber =
    .title = Pokazowar aktiwity
toolbar-create-contact-label = Nowy kontakt
toolbar-create-contact =
    .title = Nowy kontakt wutworić
toolbar-create-address-book-label = Nowy adresnik
toolbar-create-address-book =
    .title = Nowy adresnik załožić
toolbar-create-list-label = Nowa lisćina
toolbar-create-list =
    .title = Nowu rozesyłansku lisćinu załožić
toolbar-import-contacts-label = Importować
toolbar-import-contacts =
    .title = Kontakty z dataje importować

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lokalny adresnik přidać
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Adresnik CardDAV přidać
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Adresnik LDAP přidać
