# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Wšykne wubraś
select-none-calendars = Žeden njewubraś
calendar-creation-wizard-title = Nowy kalender napóraś
calendar-creation-initial-description = Waš kalender dajo se na wašom licadle abo na serweru składowaś, aby na njen zdaloka pśistup měł abo jen z wašymi pśijaśelami abo sobuźěłaśerjami źělił.
calendar-creation-initial-computer =
    .label = Na mójom licadle
calendar-creation-initial-network =
    .label = W seśi
calendar-creation-username =
    .value = Wužywaŕske mě:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Kalender napóraś
    .buttonaccesskeyaccept = l
    .buttonlabelextra2 = Slědk
    .buttonaccesskeyextra2 = S
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Kalender napóraś
    .buttonaccesskeyaccept = l
    .buttonlabelextra2 = Slědk
    .buttonaccesskeyextra2 = S
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Kalendery pytaś
    .buttonaccesskeyaccept = d
    .buttonlabelextra2 = Slědk
    .buttonaccesskeyextra2 = S
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Aboněrowaś
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Slědk
    .buttonaccesskeyextra2 = S
calendar-creation-type =
    .value = Kalenderowy typ:
calendar-creation-location =
    .value = Městno:
calendar-creation-location-placeholder =
    .placeholder = URL abo mě hosta kalenderowego serwera
    .default-placeholder = URL abo mě hosta kalenderowego serwera
calendar-creation-network-nocredentials =
    .label = Toś to městno pśizjawjeńske daty njetrjeba
calendar-creation-network-loading = Pšosym cakajśo, daniž waše kalendery njejsu namakane.
calendar-creation-network-notfound = Kalendery njejsu se dali na toś tom městnje namakaś. Pšosym pśeglědujśo swóje nastajenja.
calendar-creation-network-authfail = Pśizjawjeńske daty, kótarež sćo zapódał, njejsu se akceptěrowali. Pšosym pśeglědujśo swóje nastajenja.
calendar-creation-network-certerror = Problema z certifikatom dla njejsu se kalendarje na toś tom městnje namakaś.
calendar-creation-network-subscribe-single = Pšosym wubjeŕśo kalendery, kótarež wy by rady aboněrował.
calendar-creation-network-subscribe-multiple = Za toś to městno su někotare kalenderowe typy k dispoziciji. Pšosym wubjeŕśo kalenderowy typ a markěrujśo pón kalendery, kótarež cośo aboněrowaś.
