# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Setări pentru spam
dialog-header-title =
    .value = Setări pentru spam
training-description-spam = Dacă este activată, trebuie mai întâi să înveți { -brand-short-name } să identifice mesajele nedorite folosind butonul de Nedorit din bara de instrumente ca să marchezi mesajele ca nedorite sau nu. Trebuie să identifici atât mesajele nedorite, cât și cele care nu sunt nedorite. După aceea, { -brand-short-name } va putea marca automat ca mesaje nedorite.
spam-level-checkbox =
    .label = Activează controalele adaptive de spam pentru acest cont
    .accesskey = E
move-spam-message-menuitem =
    .label = Mută mesajele spam noi în:
    .accesskey = M
set-spam-folder-menuitem =
    .label = Dosar „Spam” din:
    .accesskey = S
move-message-other =
    .label = Altul:
    .accesskey = A
automatic-spam-purge-checkbox =
    .label = Șterge automat mesajele nedorite mai vechi de
    .accesskey = u
automatic-spam-purge-label =
    .value = zile
trust-addresses-header-label =
    .value = Ai încredere în adresele de e-mail din aceste agende de contacte:
    .accesskey = D
allowlist-header-label =
    .value = Nu marca automat mesajele ca nedorite dacă expeditorul este în:
    .accesskey = D
isp-headers-checkbox =
    .label = Ai încredere în anteturile de mesaje nedorite setate de:
    .accesskey = T
isp-warning-description = Dacă este activată, { -brand-short-name } va considera automat mesajele marcate de clasificarea externă ca nedorite.
spam-detecting-legend = Depistare mesaje nedorite
spam-storage-deletion-legend = Stocare și ștergere
spam-classification-legend = Selecție
spam-actions-legend = Destinație și păstrare
global-spam-preferences-button =
    .label = Setări globale pentru mesaje nedorite…
    .accesskey = G
manage-spam-title = Gestionează mesajele nedorite
manage-spam-header =
    .value = Gestionează mesajele nedorite
training-description-learns = Când este activat, { -brand-short-name } învață din mesajele pe care le marchezi ca dorite sau nedorite. Cu cât îi arăți mai multe, cu atât mai bun devine { -brand-short-name } la depistarea mesajelor nedorite.
spam-auto-detection-checkbox =
    .label = Activează depistarea automată a mesajelor nedorite pentru acest cont
    .accesskey = E
