# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Setări pentru lucrul offline
autodetect-connection-label =
    .label = Comută automat modurile când se găsește o conexiune la internet
    .accesskey = d
offline-startup-label = Când deschid { -brand-short-name }:
status-radio-last-used =
    .label = Folosește ultimul mod de conectare utilizat
    .accesskey = U
status-radio-ask-connect =
    .label = Întreabă dacă vreau să mă conectez online
    .accesskey = k
status-radio-start-online =
    .label = Deschide online
    .accesskey = I
status-radio-start-offline =
    .label = Deschide offline
    .accesskey = f
going-online-prompt = Trimite mesajele care așteaptă în căsuța de ieșire
going-online-send =
    .label = Da, trimite-le automat
    .accesskey = Y
going-online-keep =
    .label = Nu, ține-le în căsuța de ieșire
    .accesskey = N
going-online-ask-send =
    .label = Întreabă înainte de a trimite
    .accesskey = s
going-offline-prompt = Vrei să descarci mesajele ca să le citești offline?
going-offline-download =
    .label = Da, descarcă-le automat
    .accesskey = e
going-offline-keep =
    .label = Nu, nu le descărca
    .accesskey = o
going-offline-ask-download =
    .label = Întreabă înainte să le descarci
    .accesskey = a
autodetect-online-label =
    .label = Urmărește automat starea online detectată
    .accesskey = d
offline-preference-startup-label = Starea manuală la pornire:
status-radio-remember =
    .label = Memorează starea online precedentă
    .accesskey = r
status-radio-ask =
    .label = Întreabă-mă pentru starea online
    .accesskey = t
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Vrei să se expedieze mesajele netrimise când lucrezi online?
going-online-auto =
    .label = Da
    .accesskey = D
going-online-not =
    .label = Nu
    .accesskey = N
going-online-ask =
    .label = Întreabă-mă
    .accesskey = n
going-offline-label = Vrei să descarci mesajele pentru utilizare offline?
going-offline-auto =
    .label = Da
    .accesskey = D
going-offline-not =
    .label = Nu
    .accesskey = N
going-offline-ask =
    .label = Întreabă-mă
    .accesskey = a
