# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Confirmări de primire
return-receipt-checkbox-control =
    .label = La trimiterea unui mesaj, solicită întotdeauna confirmare de primire
    .accesskey = W
receipt-arrive-label = Când sosește o confirmare:
receipt-leave-inbox-control =
    .label = Lasă în inbox
    .accesskey = i
receipt-move-sent-control =
    .label = Mută în dosarul de mesaje trimise
    .accesskey = m
receipt-sender-request-label = Când un expeditor solicită o confirmare de primire:
receipt-leave-radio-control =
    .label = Lasă-l în căsuța poștală
    .accesskey = i
receipt-move-radio-control =
    .label = Mută-l în dosarul de „Trimise”
    .accesskey = m
receipt-request-label = Când mi se cere confirmare de primire:
receipt-return-never-radio-control =
    .label = Nu trimite niciodată confirmări de primire
    .accesskey = n
receipt-return-some-radio-control =
    .label = Permite confirmări de primire pentru anumite mesaje
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Dacă nu apare în câmpul Către sau CC:
    .accesskey = f
receipt-not-to-cc-label =
    .value = Dacă nu sunt în câmpul Către sau Cc al mesajului:
    .accesskey = f
receipt-send-never-label =
    .label = Nu trimite niciodată
receipt-send-always-label =
    .label = Trimite mereu
receipt-send-ask-label =
    .label = Întreabă-mă
sender-outside-company-label =
    .value = Dacă expeditorul este din afara companiei sau domeniului:
    .accesskey = t
sender-outside-domain-label =
    .value = Dacă expeditorul nu este în domeniul meu:
    .accesskey = t
other-cases-text-label =
    .value = În toate celelalte cazuri:
    .accesskey = a
read-receipts-dialog-title = Confirmări de citire
return-receipt-request-control =
    .label = Cere întotdeauna o confirmare de primire când trimit mesaje
    .accesskey = W
