# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Pavadinimas:
calendar-item-summary-calendar = Kalendorius:
calendar-item-summary-task-start = Pradžia:
calendar-item-summary-event-start = Pradžia:
calendar-item-summary-task-due = Terminas:
calendar-item-summary-event-end = Pabaiga:
calendar-item-summary-repeat = Pasikartojimas:
calendar-item-summary-location = Vieta:
calendar-item-summary-category = Kategorija:
calendar-item-summary-organizer = Organizuoja:
calendar-item-summary-status = Būsena:
calendar-item-summary-reminder = Priminimas:
calendar-item-summary-attachments = Priedai:
calendar-item-summary-status-tentative = Preliminarus
calendar-item-summary-status-confirmed = Patvirtintas
calendar-item-summary-event-status-cancelled = Atšauktas
calendar-item-summary-todo-status-cancelled = Atšauktas
calendar-item-summary-status-needs-action = Reikalingas veiksmas
calendar-item-summary-status-in-process = Vyksta
calendar-item-summary-status-completed = Užbaigtas
calendar-item-summary-reminder-none =
    .label = be priminimo
calendar-item-summary-reminder-0-minutes-before =
    .label = likus 0 minučių
calendar-item-summary-reminder-5-minutes-before =
    .label = likus 5 minutėms
calendar-item-summary-reminder-15-minutes-before =
    .label = likus 15 minučių
calendar-item-summary-reminder-30-minutes-before =
    .label = likus 30 minučių
calendar-item-summary-reminder-1-hour-before =
    .label = likus 1 valandai
calendar-item-summary-reminder-2-hours-before =
    .label = likus 2 valandoms
calendar-item-summary-reminder-12-hours-before =
    .label = likus 12 valandų
calendar-item-summary-reminder-1-day-before =
    .label = likus 1 dienai
calendar-item-summary-reminder-2-days-before =
    .label = likus 2 dienoms
calendar-item-summary-reminder-1-week-before =
    .label = likus 1 savaitei
calendar-item-summary-reminder-custom =
    .label = parinkti kitokį…
calendar-item-summary-reminder-multiple =
    .value = Keli priminimai…
calendar-item-summary-general =
    .value = Įvykis
calendar-item-summary-attendees =
    .value = Dalyviai
calendar-item-summary-description =
    .value = Aprašas
calendar-item-summary-link =
    .value = Saitas
