# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Swobodny odstęp
search-bar-label = Szukaj
toolbar-write-message-label = Napisz
toolbar-write-message =
    .title = Utwórz nową wiadomość
toolbar-move-to-label = Przenieś do
toolbar-move-to =
    .title = Przenieś zaznaczoną wiadomość
toolbar-unifinder-label = Znajdź wydarzenia
toolbar-unifinder =
    .title = Przełącz panel wyszukiwania wydarzeń
toolbar-folder-location-label = Położenie folderu
toolbar-folder-location =
    .title = Przejdź do folderu
toolbar-edit-event-label = Edytuj
toolbar-edit-event =
    .title = Edytuj zaznaczone zadanie lub wydarzenie
toolbar-get-messages-label = Pobierz
toolbar-get-messages =
    .title = Pobierz nowe wiadomości dla wszystkich kont
toolbar-reply-label = Odpowiedz
toolbar-reply =
    .title = Odpowiedz na wiadomość
toolbar-reply-all-label = Odp. wszystkim
toolbar-reply-all =
    .title = Odpowiedz nadawcy i wszystkim adresatom
toolbar-reply-to-list-label = Odp. liście
toolbar-reply-to-list =
    .title = Odpowiedz liście dyskusyjnej
toolbar-redirect-label = Przekieruj
toolbar-redirect =
    .title = Przekieruj zaznaczoną wiadomość
toolbar-archive-label = Archiwizuj
toolbar-archive =
    .title = Archiwizuj zaznaczone wiadomości
toolbar-conversation-label = Wątek
toolbar-conversation =
    .title = Wyświetl wątek zaznaczonej wiadomości
toolbar-previous-unread-label = Poprzednia nieprzeczytana
toolbar-previous-unread =
    .title = Przejdź do poprzedniej nieprzeczytanej wiadomości
toolbar-previous-label = Poprzednia
toolbar-previous =
    .title = Przejdź do poprzedniej wiadomości
toolbar-next-unread-label = Następna nieprzeczytana
toolbar-next-unread =
    .title = Przejdź do następnej nieprzeczytanej wiadomości
toolbar-next-label = Następna
toolbar-next =
    .title = Przejdź do następnej wiadomości
toolbar-junk-label = Niechciana
toolbar-junk =
    .title = Oznacz zaznaczoną wiadomość jako niechcianą
toolbar-delete-label = Usuń
toolbar-delete-title =
    .title = Usuń zaznaczone wiadomości
toolbar-undelete-label = Przywróć
toolbar-undelete =
    .title = Przywróć zaznaczone wiadomości
toolbar-compact-label = Porządkuj
toolbar-compact =
    .title = Porządkuj folder, aby wyczyścić pozostałości po usuniętych wiadomościach
toolbar-add-as-event-label = Dodaj jako wydarzenie
toolbar-add-as-event =
    .title = Wyodrębnij informacje o wydarzeniu z wiadomości i dodaj je do kalendarza
toolbar-add-as-task-label = Dodaj jako zadanie
toolbar-add-as-task =
    .title = Wyodrębnij informacje o zadaniu z wiadomości i dodaj je do kalendarza
toolbar-tag-message-label = Etykieta
toolbar-tag-message =
    .title = Oznacz wiadomości etykietą
toolbar-forward-inline-label = Przekaż
toolbar-forward-inline =
    .title = Przekaż zaznaczoną wiadomość bezpośrednio, jako tekst treści
toolbar-forward-attachment-label = Przekaż jako załącznik
toolbar-forward-attachment =
    .title = Przekaż zaznaczoną wiadomość jako załącznik
toolbar-mark-as-label = Oznacz
toolbar-mark-as =
    .title = Oznacz wiadomości
toolbar-view-picker-label = Widok
toolbar-view-picker =
    .title = Dostosuj widok obecnego folderu
toolbar-address-book-label = Książka adresowa
toolbar-address-book =
    .title = Wyświetl Książkę adresową
toolbar-chat-label = Komunikator
toolbar-chat =
    .title = Wyświetl kartę komunikatora
toolbar-add-ons-and-themes-label = Dodatki i motywy
toolbar-add-ons-and-themes =
    .title = Zarządzaj dodatkami
toolbar-calendar-label = Kalendarz
toolbar-calendar =
    .title = Przełącz na widok kalendarza
toolbar-tasks-label = Zadania
toolbar-tasks =
    .title = Przełącz na widok zadań
toolbar-mail-label = Poczta
toolbar-mail =
    .title = Przełącz na widok poczty
toolbar-print-label = Drukuj
toolbar-print =
    .title = Drukuj wiadomość
toolbar-quick-filter-bar-label = Szybkie filtrowanie
toolbar-quick-filter-bar =
    .title = Filtruj wiadomości
toolbar-synchronize-label = Synchronizuj
toolbar-synchronize =
    .title = Odśwież kalendarze i synchronizuj zmiany
toolbar-delete-event-label = Usuń
toolbar-delete-event =
    .title = Usuń zaznaczone zadania lub wydarzenia
toolbar-go-to-today-label = Dzisiaj
toolbar-go-to-today =
    .title = Przejdź do panelu bieżących spraw
toolbar-print-event-label = Drukuj
toolbar-print-event =
    .title = Drukuj zadania lub wydarzenia
toolbar-new-event-label = Wydarzenie
toolbar-new-event =
    .title = Utwórz nowe wydarzenie
toolbar-new-task-label = Zadanie
toolbar-new-task =
    .title = Utwórz nowe zadanie
toolbar-go-back-label = Wstecz
toolbar-go-back =
    .title = Przejdź o jedną wiadomość wstecz
toolbar-go-forward-label = Dalej
toolbar-go-forward =
    .title = Przejdź o jedną wiadomość do przodu
toolbar-stop-label = Zatrzymaj
toolbar-stop =
    .title = Zatrzymaj bieżący transfer
toolbar-throbber-label = Wskaźnik aktywności
toolbar-throbber =
    .title = Wskaźnik aktywności
toolbar-create-contact-label = Nowy kontakt
toolbar-create-contact =
    .title = Utwórz nowy kontakt
toolbar-create-address-book-label = Nowa książka adresowa
toolbar-create-address-book =
    .title = Utwórz nową książkę adresową
toolbar-create-list-label = Nowa lista
toolbar-create-list =
    .title = Utwórz nową listę dystrybucyjną
toolbar-import-contacts-label = Importuj
toolbar-import-contacts =
    .title = Importuj kontakty z pliku

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Dodaj lokalną książkę adresową
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Dodaj książkę adresową CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Dodaj książkę adresową LDAP
