# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Mencari…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 padanan ditemui
noMatchesFound = Tiada padanan ditemui
labelForStopButton = Berhenti
labelForSearchButton = Cari
labelForStopButton.accesskey = B
labelForSearchButton.accesskey = C
moreButtonTooltipText = Tambah peraturan baru
lessButtonTooltipText = Buang peraturan ini
