# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Seliger toto
select-none-calendars = Seliger nihil
calendar-creation-wizard-title = Crear nove agenda
calendar-creation-initial-description = Tu pote salvar tu agenda sur le computator o sur un servitor, pro acceder lo ab remote o compartir lo con amicos e collaboratores.
calendar-creation-initial-computer =
    .label = Sur mi computator
calendar-creation-initial-network =
    .label = Sur le rete
calendar-creation-username =
    .value = Nomine de usator:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Crear agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retro
    .buttonaccesskeyextra2 = R
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Crear agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retro
    .buttonaccesskeyextra2 = R
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Trovar agendas
    .buttonaccesskeyaccept = T
    .buttonlabelextra2 = Retro
    .buttonaccesskeyextra2 = R
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonar se
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Retro
    .buttonaccesskeyextra2 = R
calendar-creation-type =
    .value = Typo de agenda:
calendar-creation-location =
    .value = Position;
calendar-creation-location-placeholder =
    .placeholder = URL o nomine de hospite del servitor del agenda
    .default-placeholder = URL o nomine de hospite del servitor del agenda
calendar-creation-network-nocredentials =
    .label = Iste position non require credentiales
calendar-creation-network-loading = Attende dum tu agendas es discoperite.
calendar-creation-network-notfound = Impossibile trovar agendas in iste loco. Controla tu parametros.
calendar-creation-network-authfail = Le credentiales inserite non ha essite acceptate. Controla tu parametros.
calendar-creation-network-certerror = Impossibile trovar agendas in iste loco per un problema de certificato.
calendar-creation-network-subscribe-single = Selige le agendas al quales tu prefere abonar te.
calendar-creation-network-subscribe-multiple = A iste adresse es disponibile typos de agendas multiple. Ante selige le typo de agenda, pois marca los a subscriber.
