# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Commento
calendar-item-summary-title = Titulo:
calendar-item-summary-calendar = Agenda:
calendar-item-summary-task-start = Data de initio:
calendar-item-summary-event-start = Data de initio:
calendar-item-summary-task-due = Data de termino:
calendar-item-summary-event-end = Data de fin:
calendar-item-summary-repeat = Repeter:
calendar-item-summary-location = Adresse:
calendar-item-summary-category = Categoria:
calendar-item-summary-organizer = Organisator:
calendar-item-summary-status = Stato:
calendar-item-summary-reminder = Memento:
calendar-item-summary-attachments = Annexos:
calendar-item-summary-status-tentative = Provisori
calendar-item-summary-status-confirmed = Confirmate
calendar-item-summary-event-status-cancelled = Cancellate
calendar-item-summary-todo-status-cancelled = Cancellate
calendar-item-summary-status-needs-action = Require action
calendar-item-summary-status-in-process = In curso
calendar-item-summary-status-completed = Completate le
calendar-item-summary-reminder-none =
    .label = Nulle memento
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutas antea
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutas antea
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutas antea
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutas antea
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hora antea
calendar-item-summary-reminder-2-hours-before =
    .label = 2 horas antea
calendar-item-summary-reminder-12-hours-before =
    .label = 12 horas antea
calendar-item-summary-reminder-1-day-before =
    .label = 1 die antea
calendar-item-summary-reminder-2-days-before =
    .label = 2 dies antea
calendar-item-summary-reminder-1-week-before =
    .label = 1 septimana antea
calendar-item-summary-reminder-custom =
    .label = Personalisar…
calendar-item-summary-reminder-multiple =
    .value = Mementos multiple…
calendar-item-summary-general =
    .value = General
calendar-item-summary-attendees =
    .value = Participantes
calendar-item-summary-description =
    .value = Description
calendar-item-summary-link =
    .value = Ligamine associate
