# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espaço flexível
search-bar-label = Pesquisar
toolbar-write-message-label = Escrever
toolbar-write-message =
    .title = Nova mensagem
toolbar-move-to-label = Mover para
toolbar-move-to =
    .title = Mover mensagem selecionada
toolbar-unifinder-label = Procurar eventos
toolbar-unifinder =
    .title = Alternar o painel de procurar eventos
toolbar-folder-location-label = Local da pasta
toolbar-folder-location =
    .title = Mudar para pasta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar evento ou tarefa selecionada
toolbar-get-messages-label = Receber mensagens
toolbar-get-messages =
    .title = Buscar novas mensagens de todas as contas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder mensagem
toolbar-reply-all-label = Responder a todos
toolbar-reply-all =
    .title = Responder ao remetente e a todos os destinatários
toolbar-reply-to-list-label = Responder à lista
toolbar-reply-to-list =
    .title = Responder à lista de emails
toolbar-redirect-label = Redirecionar
toolbar-redirect =
    .title = Redirecionar mensagens selecionadas
toolbar-archive-label = Arquivar
toolbar-archive =
    .title = Arquivar mensagens selecionadas
toolbar-conversation-label = Conversa
toolbar-conversation =
    .title = Mostrar conversa da mensagem selecionada
toolbar-previous-unread-label = Anterior não lida
toolbar-previous-unread =
    .title = Mover para mensagem anterior não lida
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Mover para mensagem anterior
toolbar-next-unread-label = Próxima não lida
toolbar-next-unread =
    .title = Mover para próxima mensagem não lida
toolbar-next-label = Próxima
toolbar-next =
    .title = Mover para próxima mensagem
toolbar-junk-label = Spam
toolbar-junk =
    .title = Marcar as mensagens selecionadas como spam
toolbar-delete-label = Excluir
toolbar-delete-title =
    .title = Excluir as mensagens selecionadas
toolbar-undelete-label = Restaurar
toolbar-undelete =
    .title = Restaurar as mensagens selecionadas
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Remover as mensagens excluídas da pasta selecionada
toolbar-add-as-event-label = Adicionar como evento
toolbar-add-as-event =
    .title = Extrair informações de agenda a partir da mensagem e adicionar à sua agenda como um evento
toolbar-add-as-task-label = Adicionar como tarefa
toolbar-add-as-task =
    .title = Extrair informações de agenda a partir da mensagem e adicionar à sua agenda como uma tarefa
toolbar-tag-message-label = Etiquetas
toolbar-tag-message =
    .title = Aplicar etiquetas em mensagens
toolbar-forward-inline-label = Encaminhar
toolbar-forward-inline =
    .title = Reencaminhar mensagem selecionada como texto
toolbar-forward-attachment-label = Encaminhar como anexo
toolbar-forward-attachment =
    .title = Reencaminhar mensagem selecionada como anexo
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensagens
toolbar-view-picker-label = Exibição
toolbar-view-picker =
    .title = Personalizar exibição da pasta atual
toolbar-address-book-label = Catálogo de endereços
toolbar-address-book =
    .title = Catálogo de endereços
toolbar-chat-label = Conversa
toolbar-chat =
    .title = Mostrar a aba de conversa
toolbar-add-ons-and-themes-label = Extensões e temas
toolbar-add-ons-and-themes =
    .title = Gerenciar extensões e temas
toolbar-calendar-label = Agenda
toolbar-calendar =
    .title = Mudar para aba de agenda
toolbar-tasks-label = Tarefas
toolbar-tasks =
    .title = Mudar para aba de tarefas
toolbar-mail-label = Email
toolbar-mail =
    .title = Alternar para a aba de email
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir a mensagem
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensagens
toolbar-synchronize-label = Sincronizar
toolbar-synchronize =
    .title = Recarregar agendas e sincronizar alterações
toolbar-delete-event-label = Excluir
toolbar-delete-event =
    .title = Excluir eventos ou tarefas selecionadas
toolbar-go-to-today-label = Ir para hoje
toolbar-go-to-today =
    .title = Ir para hoje
toolbar-print-event-label = Imprimir
toolbar-print-event =
    .title = Imprimir eventos ou tarefas
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Criar novo evento
toolbar-new-task-label = Tarefa
toolbar-new-task =
    .title = Criar nova tarefa
toolbar-go-back-label = Voltar
toolbar-go-back =
    .title = Mensagem anterior
toolbar-go-forward-label = Avançar
toolbar-go-forward =
    .title = Próxima mensagem
toolbar-stop-label = Parar
toolbar-stop =
    .title = Interromper a transferência atual
toolbar-throbber-label = Indicador de atividade
toolbar-throbber =
    .title = Indicador de atividade
toolbar-create-contact-label = Novo contato
toolbar-create-contact =
    .title = Criar novo contato
toolbar-create-address-book-label = Novo catálogo de endereços
toolbar-create-address-book =
    .title = Criar novo catálogo de endereços
toolbar-create-list-label = Nova lista
toolbar-create-list =
    .title = Criar nova lista de emails
toolbar-import-contacts-label = Importar
toolbar-import-contacts =
    .title = Importar contatos de um arquivo

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Adicionar catálogo de endereços local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Adicionar catálogo de endereços CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Adicionar catálogo de endereços LDAP
