# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Aranıyor…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 eşleşme bulundu;#1 eşleşme bulundu
noMatchesFound = Eşleşme bulunamadı
labelForStopButton = Durdur
labelForSearchButton = Ara
labelForStopButton.accesskey = D
labelForSearchButton.accesskey = A
moreButtonTooltipText = Yeni bir kural ekle
lessButtonTooltipText = Bu kuralı sil
