# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Titel:
calendar-item-summary-calendar = Chalender:
calendar-item-summary-task-start = Data da cumenzament:
calendar-item-summary-event-start = Data da cumenzament:
calendar-item-summary-task-due = Data da scadenza:
calendar-item-summary-event-end = Data da finiziun:
calendar-item-summary-repeat = Repeter:
calendar-item-summary-location = Lieu:
calendar-item-summary-category = Categoria:
calendar-item-summary-organizer = Organisatur:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Promomoria:
calendar-item-summary-attachments = Agiuntas:
calendar-item-summary-status-tentative = Provisoric
calendar-item-summary-status-confirmed = Confermà
calendar-item-summary-event-status-cancelled = Annullà
calendar-item-summary-todo-status-cancelled = Annullà
calendar-item-summary-status-needs-action = Dovra acziun
calendar-item-summary-status-in-process = En progress
calendar-item-summary-status-completed = Cumplettà ils
calendar-item-summary-reminder-none =
    .label = Nagina promemoria
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutas avant
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutas avant
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutas avant
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutas avant
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ura avant
calendar-item-summary-reminder-2-hours-before =
    .label = 2 uras avant
calendar-item-summary-reminder-12-hours-before =
    .label = 12 uras avant
calendar-item-summary-reminder-1-day-before =
    .label = 1 di avant
calendar-item-summary-reminder-2-days-before =
    .label = 2 dis avant
calendar-item-summary-reminder-1-week-before =
    .label = 1 emna avant
calendar-item-summary-reminder-custom =
    .label = Persunalisà…
calendar-item-summary-reminder-multiple =
    .value = Pliras promemorias…
calendar-item-summary-general =
    .value = General
calendar-item-summary-attendees =
    .value = Participants
calendar-item-summary-description =
    .value = Descripziun
calendar-item-summary-link =
    .value = Colliaziun correspundenta
