# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

account-settings-color-label = Cor:
    .accesskey = C
account-settings-reset-color-button =
    .title = Repor cor
delete-account-button =
    .label = Eliminar
default-account-button =
    .label = Definir como predefinido
outgoing-server-name = Servidor de envio:
    .accesskey = v
outgoing-server-edit =
    .label = Editar servidor de envio…
    .accesskey = o
oauth2-use-custom-details =
    .label = Usar definições personalizadas de OAuth2
    .accesskey = c
oauth2-client-id-label =
    .value = ID do cliente:
    .accesskey = I
oauth2-authorization-endpoint-label =
    .value = Endpoint da Autorização:
    .accesskey = h
oauth2-token-endpoint-label =
    .value = Endpoint do token:
    .accesskey = t
ews-url-label =
    .value = URL do servidor:
    .accesskey = f
ews-override-oauth-details =
    .label = Substituir definições do Office365:
    .accesskey = O
ews-applicationid-label =
    .value = Id. da aplicação:
    .accesskey = a
ews-tenantid-label =
    .value = Id. do tenant:
    .accesskey = t
ews-redirecturi-label =
    .value = URl de redirecionamento:
    .accesskey = r
ews-endpointhost-label =
    .value = Servidor de endpoint:
    .accesskey = d
ews-oauthscopes-label =
    .value = Âmbitos de OAuth:
    .accesskey = s
