# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espaço flexível
search-bar-label = Pesquisar
toolbar-write-message-label = Escrever
toolbar-write-message =
    .title = Criar nova mensagem
toolbar-move-to-label = Mover para
toolbar-move-to =
    .title = Mover mensagem selecionada
toolbar-unifinder-label = Localizar eventos
toolbar-unifinder =
    .title = Alternar o painel de localizar eventos
toolbar-folder-location-label = Localização da pasta
toolbar-folder-location =
    .title = Mudar para a pasta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Apagar evento ou tarefa selecionada
toolbar-get-messages-label = Obter mensagens
toolbar-get-messages =
    .title = Obter as novas mensagens para todas as contas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder à mensagem
toolbar-reply-all-label = Responder a todos
toolbar-reply-all =
    .title = Responder ao remetente e a todos os destinatários
toolbar-reply-to-list-label = Responder à lista
toolbar-reply-to-list =
    .title = Responder à lista de correio
toolbar-redirect-label = Redirecionar
toolbar-redirect =
    .title = Redirecionar a mensagem selecionada
toolbar-archive-label = Arquivar
toolbar-archive =
    .title = Arquivar mensagens selecionadas
toolbar-conversation-label = Conversa
toolbar-conversation =
    .title = Mostrar a conversação da mensagem selecionada
toolbar-previous-unread-label = Anterior não lida
toolbar-previous-unread =
    .title = Ir para a mensagem anterior não lida
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Ir para a mensagem anterior
toolbar-next-unread-label = Seguinte não lida
toolbar-next-unread =
    .title = Ir para a mensagem seguinte não lida
toolbar-next-label = Seguinte
toolbar-next =
    .title = Ir para a mensagem seguinte
toolbar-spam-label = Lixo eletrónico
toolbar-spam =
    .title = Marcar as mensagens selecionadas como lixo eletrónico
toolbar-not-spam-label = Não é lixo eletrónico
toolbar-not-spam =
    .title = Marcar as mensagens selecionadas como não sendo lixo eletrónico
toolbar-junk-label = Spam
toolbar-junk =
    .title = Marcas as mensagens selecionadas como spam
toolbar-delete-label = Eliminar
toolbar-delete-title =
    .title = Eliminar as mensagens selecionadas
toolbar-undelete-label = Recuperar
toolbar-undelete =
    .title = Restaurar as mensagens selecionadas
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Remover mensagens apagadas da pasta selecionada
toolbar-add-as-event-label = Adicionar como evento
toolbar-add-as-event =
    .title = Extrair informações da mensagem e adicionar ao calendário como evento
toolbar-add-as-task-label = Adicionar como tarefa
toolbar-add-as-task =
    .title = Extrair informações da mensagem e adicionar ao calendário como evento
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Classificar mensagens
toolbar-forward-inline-label = Reencaminhar
toolbar-forward-inline =
    .title = Reencaminhar mensagem selecionada como texto inline
toolbar-forward-attachment-label = Reencaminhar como anexo
toolbar-forward-attachment =
    .title = Reencaminhar mensagem selecionada como anexo
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensagens
toolbar-view-picker-label = Ver
toolbar-view-picker =
    .title = Personalizar a visualização da pasta atual
toolbar-address-book-label = Livro de Endereços
toolbar-address-book =
    .title = Ir para o livro de endereços
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mostrar o separador de chat
toolbar-add-ons-and-themes-label = Extras e temas
toolbar-add-ons-and-themes =
    .title = Gerir os seus extras
toolbar-calendar-label = Calendário
toolbar-calendar =
    .title = Muda para o separador do calendário
toolbar-tasks-label = Tarefas
toolbar-tasks =
    .title = Muda para o separador de tarefas
toolbar-mail-label = Correio
toolbar-mail =
    .title = Mudar para o separador de correio
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir esta mensagem
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensagens
toolbar-synchronize-label = Sincronizar
toolbar-synchronize =
    .title = Recarregar calendários e sincronizar alterações
toolbar-delete-event-label = Apagar
toolbar-delete-event =
    .title = Apagar eventos ou tarefas selecionadas
toolbar-go-to-today-label = Ir para hoje
toolbar-go-to-today =
    .title = Ir para hoje
toolbar-print-event-label = Imprimir
toolbar-print-event =
    .title = Imprimir eventos ou tarefas
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Criar um novo evento
toolbar-new-task-label = Tarefa
toolbar-new-task =
    .title = Criar uma nova tarefa
toolbar-go-back-label = Recuar
toolbar-go-back =
    .title = Recuar uma mensagem
toolbar-go-forward-label = Avançar
toolbar-go-forward =
    .title = Avançar uma mensagem
toolbar-stop-label = Parar
toolbar-stop =
    .title = Parar descarga em curso
toolbar-throbber-label = Indicador de atividade
toolbar-throbber =
    .title = Indicador de atividade
toolbar-create-contact-label = Novo contacto
toolbar-create-contact =
    .title = Criar um novo contacto
toolbar-create-address-book-label = Novo Livro de Endereços
toolbar-create-address-book =
    .title = Criar um novo livro de endereços
toolbar-create-list-label = Nova lista
toolbar-create-list =
    .title = Criar uma nova lista de correio
toolbar-import-contacts-label = Importar
toolbar-import-contacts =
    .title = Importar contactos de um ficheiro

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Adicionar livro de endereços local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Adicionar livro de endereços CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Adicionar livro de endereços LDAP
