# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Título:
calendar-item-summary-calendar = Calendario:
calendar-item-summary-task-start = Data de inicio:
calendar-item-summary-event-start = Data de inicio:
calendar-item-summary-task-due = Data de vencemento:
calendar-item-summary-event-end = Data de remate:
calendar-item-summary-repeat = Repetir:
calendar-item-summary-location = Localización:
calendar-item-summary-category = Categoría:
calendar-item-summary-organizer = Organizador:
calendar-item-summary-status = Estado:
calendar-item-summary-reminder = Recordatorio:
calendar-item-summary-attachments = Anexos:
calendar-item-summary-status-tentative = Provisional
calendar-item-summary-status-confirmed = Confirmado
calendar-item-summary-event-status-cancelled = Cancelado
calendar-item-summary-todo-status-cancelled = Cancelado
calendar-item-summary-status-needs-action = Precisa dunha acción
calendar-item-summary-status-in-process = En proceso
calendar-item-summary-status-completed = Rematado o
calendar-item-summary-reminder-none =
    .label = Sen recordatorio
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutos antes
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutos antes
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutos antes
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutos antes
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hora antes
calendar-item-summary-reminder-2-hours-before =
    .label = 2 horas antes
calendar-item-summary-reminder-12-hours-before =
    .label = 12 horas antes
calendar-item-summary-reminder-1-day-before =
    .label = 1 día antes
calendar-item-summary-reminder-2-days-before =
    .label = 2 días antes
calendar-item-summary-reminder-1-week-before =
    .label = 1 semana antes
calendar-item-summary-reminder-custom =
    .label = Personalizar…
calendar-item-summary-reminder-multiple =
    .value = Varios recordatorios…
calendar-item-summary-general =
    .value = Xeral
calendar-item-summary-attendees =
    .value = Asistentes
calendar-item-summary-description =
    .value = Descrición
calendar-item-summary-link =
    .value = Ligazón relacionada
