# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Seleccionar todo
select-none-calendars = Non seleccionar nada
calendar-creation-wizard-title = Crear novo calendario
calendar-creation-initial-description = Pode almacenarse o calendario no seu computador ou nun servidor para acceder a el remotamente ou compartilo cos seus amigos ou compañeiros de traballo.
calendar-creation-initial-computer =
    .label = No meu computador
calendar-creation-initial-network =
    .label = Na rede
calendar-creation-username =
    .value = Nome de usuario:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Crear calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Atopar calendarios
    .buttonaccesskeyaccept = l
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Subscribir
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Atrás
    .buttonaccesskeyextra2 = A
calendar-creation-type =
    .value = Tipo de calendario:
calendar-creation-location =
    .value = Localización:
calendar-creation-location-placeholder =
    .placeholder = URL ou nome para o servidor do calendario
    .default-placeholder = URL ou nome para o servidor do calendario
calendar-creation-network-nocredentials =
    .label = Esta localización non require credenciais
calendar-creation-network-loading = Agarde mentres se buscan os seus calendarios.
calendar-creation-network-notfound = Non foi posíbel atopar calendarios nesta localización. Comprobe os axustes.
calendar-creation-network-authfail = As credenciais que introduciu non foron aceptadas. Comprobe os axustes.
calendar-creation-network-certerror = Non se puideron atopar os calendarios nesta localización por mor dun problema co certificado.
calendar-creation-network-subscribe-single = Seleccione os calendarios aos que desexa subscribirse.
calendar-creation-network-subscribe-multiple = Están dispoñíbeis varios tipos de calendarios nesta localización. Seleccione o tipo de calendario e despois marque os que desexa subscribir.
