# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Weergavenaam
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Type
vcard-entry-type-home = Thuis
vcard-entry-type-work = Werk
vcard-entry-type-none = Geen
vcard-entry-type-custom = Aangepast
vcard-name-header = Naam
vcard-n-prefix = Voorvoegsel
vcard-n-add-prefix =
    .title = Voorvoegsel toevoegen
vcard-n-firstname = Voornaam
vcard-n-add-firstname =
    .title = Voornaam toevoegen
vcard-n-middlename = Tweede naam
vcard-n-add-middlename =
    .title = Tweede naam toevoegen
vcard-n-lastname = Achternaam
vcard-n-add-lastname =
    .title = Achternaam toevoegen
vcard-n-suffix = Achtervoegsel
vcard-n-add-suffix =
    .title = Achtervoegsel toevoegen
vcard-nickname = Schermnaam
vcard-email-header = E-mailadressen
vcard-email-add = E-mailadres toevoegen
vcard-email-label = E-mailadres
vcard-primary-email-label = Standaard
vcard-url-header = Websites
vcard-url-add = Website toevoegen
vcard-url-label = Website
vcard-tel-header = Telefoonnummers
vcard-tel-add = Telefoonnummer toevoegen
vcard-tel-label = Telefoonnummer
# Or "Mobile"
vcard-entry-type-cell = Mobiel
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pieper
vcard-tz-header = Tijdzone
vcard-tz-add = Tijdzone toevoegen
vcard-impp2-header = Instant-berichten
vcard-impp-add = Chataccount toevoegen
vcard-impp-label = Chataccount
vcard-impp-select = Protocol
vcard-impp-option-other = Overig
vcard-impp-input-label = URI
vcard-impp-input-title = URI voor instant-berichten
vcard-bday-anniversary-header = Speciale data
vcard-bday-anniversary-add = Speciale datum toevoegen
vcard-bday-label = Verjaardag
vcard-anniversary-label = Jubileum
vcard-date-day = Dag
vcard-date-month = Maand
vcard-date-year = Jaar
vcard-adr-header = Adressen
vcard-adr-add = Adres toevoegen
vcard-adr-label = Adres
vcard-adr-delivery-label = Bezorgingslabel
vcard-adr-street = Adres
# Or "Locality"
vcard-adr-locality = Plaats
# Or "Region"
vcard-adr-region = Staat/provincie
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postcode:
vcard-adr-country = Land
vcard-note-header = Opmerkingen
vcard-note-add = Notitie toevoegen
vcard-org-header = Organisatie-eigenschappen
vcard-org-add = Organisatie-eigenschappen toevoegen
vcard-org-title = Titel
vcard-org-title-input =
    .placeholder = Functietitel
    .title = Positie of functie
vcard-org-role = Rol
vcard-org-role-input =
    .placeholder = Projectrol
    .title = Functie of rol in een bepaalde situatie
vcard-org-org = Organisatie
vcard-org-org-input =
    .placeholder = Bedrijfsnaam
    .title = Organisatienaam
vcard-org-org-unit = Afdeling
vcard-org-org-unit-input =
    .placeholder = Afdeling
    .title = Naam organisatorische eenheid
vcard-custom-header = Aangepaste eigenschappen
vcard-custom-add = Aangepaste eigenschappen toevoegen
vcard-remove-button-title =
    .title = Verwijderen
vcard-remove-button = Verwijderen
