# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = O klask…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 c'henglotadur kavet;#1 a genglotadurioù kavet
noMatchesFound = Kenglotadur ebet kavet
labelForStopButton = Paouez
labelForSearchButton = Klask
labelForStopButton.accesskey = a
labelForSearchButton.accesskey = s
moreButtonTooltipText = Ouzhpennañ ur reolenn nevez
lessButtonTooltipText = Lemel kuit ar reolenn-se
