# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = 标题：
calendar-item-summary-calendar = 日历：
calendar-item-summary-task-start = 开始日期：
calendar-item-summary-event-start = 开始日期：
calendar-item-summary-task-due = 截止时间：
calendar-item-summary-event-end = 截止日期：
calendar-item-summary-repeat = 重复：
calendar-item-summary-location = 位置：
calendar-item-summary-category = 分类：
calendar-item-summary-organizer = 组织：
calendar-item-summary-status = 状态
calendar-item-summary-reminder = 提醒：
calendar-item-summary-attachments = 附件：
calendar-item-summary-status-tentative = 暂定
calendar-item-summary-status-confirmed = 已确认
calendar-item-summary-event-status-cancelled = 已取消
calendar-item-summary-todo-status-cancelled = 已取消
calendar-item-summary-status-needs-action = 将处理
calendar-item-summary-status-in-process = 处理中
calendar-item-summary-status-completed = 已完成
calendar-item-summary-reminder-none =
    .label = 无提醒
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 分钟前
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 分钟之前
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 分钟之前
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 分钟之前
calendar-item-summary-reminder-1-hour-before =
    .label = 1 小时之前
calendar-item-summary-reminder-2-hours-before =
    .label = 2 小时之前
calendar-item-summary-reminder-12-hours-before =
    .label = 12 小时之前
calendar-item-summary-reminder-1-day-before =
    .label = 1 天之前
calendar-item-summary-reminder-2-days-before =
    .label = 2 天之前
calendar-item-summary-reminder-1-week-before =
    .label = 1 周之前
calendar-item-summary-reminder-custom =
    .label = 定制…
calendar-item-summary-reminder-multiple =
    .value = 多重提醒器…
calendar-item-summary-general =
    .value = 常规
calendar-item-summary-attendees =
    .value = 参与者
calendar-item-summary-description =
    .value = 描述
calendar-item-summary-link =
    .value = 相关链接
