# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = 全选
select-none-calendars = 全部取消
calendar-creation-wizard-title = 创建新日历
calendar-creation-initial-description = 您的日历可以保存在您的电脑上，或者是可远程访问的服务器上，或者是与朋友或合作者共享的服务器上。
calendar-creation-initial-computer =
    .label = 保存在我的电脑中
calendar-creation-initial-network =
    .label = 保存在网络上
calendar-creation-username =
    .value = 用户名：
calendar-creation-panel-local-settings =
    .buttonlabelaccept = 新建日历
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 返回
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = 新建日历
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 返回
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = 寻找日历
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = 返回
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = 订阅
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = 返回
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = 日历类型：
calendar-creation-location =
    .value = 位置：
calendar-creation-location-placeholder =
    .placeholder = 日历服务器的网址或主机名称
    .default-placeholder = 日历服务器的网址或主机名称
calendar-creation-network-nocredentials =
    .label = 此网址无须输入账号密码
calendar-creation-network-loading = 正在查找您的日历，请稍候。
calendar-creation-network-notfound = 未能在此位置找到日历。请检查设置。
calendar-creation-network-authfail = 您输入的账号密码未被接受。请检查设置。
calendar-creation-network-certerror = 由于证书问题，未能在此位置找到日历。
calendar-creation-network-subscribe-single = 请选择您要订阅的日历。
calendar-creation-network-subscribe-multiple = 此位置有几种不同类型的日历。请先选择要订阅的日历类型，再勾选要订阅的日历。
