# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Inställningar för nedkopplat läge
autodetect-connection-label =
    .label = Byt automatiskt läge när en internetanslutning hittas
    .accesskey = B
going-online-prompt = Skicka väntande meddelanden i Utkorgen
going-online-send =
    .label = Ja, skicka automatiskt
    .accesskey = J
going-online-keep =
    .label = Nej, behåll i Utkorgen
    .accesskey = N
going-online-ask-send =
    .label = Fråga innan du skickar
    .accesskey = F
going-offline-prompt = Vill du ladda ned meddelanden så att du kan läsa dem offline?
going-offline-download =
    .label = Ja, ladda ner automatiskt
    .accesskey = J
going-offline-keep =
    .label = Nej, ladda inte ner
    .accesskey = N
going-offline-ask-download =
    .label = Fråga före nedladdning
    .accesskey = F
autodetect-online-label =
    .label = Följ automatiskt detekterat uppkopplat tillstånd
    .accesskey = d
offline-preference-startup-label = Manuellt tillstånd vid uppstart:
status-radio-remember =
    .label = Kom ihåg tidigare uppkopplat tillstånd
    .accesskey = K
status-radio-ask =
    .label = Fråga mig om uppkopplat tillstånd
    .accesskey = F
status-radio-always-online =
    .label = Alltid uppkopplat
    .accesskey = u
status-radio-always-offline =
    .label = Alltid nedkopplat
    .accesskey = n
going-online-label = Skicka osända meddelanden vid uppkoppling?
going-online-auto =
    .label = Ja
    .accesskey = J
going-online-not =
    .label = Nej
    .accesskey = N
going-online-ask =
    .label = Fråga mig
    .accesskey = F
going-offline-label = Hämta meddelanden för nedkopplad användning vid nedkoppling?
going-offline-auto =
    .label = Ja
    .accesskey = a
going-offline-not =
    .label = Nej
    .accesskey = e
going-offline-ask =
    .label = Fråga mig
    .accesskey = m
