# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Elastīga atstarpe
toolbar-write-message-label = Rakstīt
toolbar-write-message =
    .title = Izveidot jaunu vēstuli
toolbar-folder-location-label = Mapes vieta
toolbar-get-messages-label = Saņemt vēstules
toolbar-reply-label = Atbildēt
toolbar-reply =
    .title = Atbildēt uz vēstuli
toolbar-reply-all-label = Atbildēt visiem
toolbar-reply-all =
    .title = Atbildēt sūtītājam un visiem saņēmējiem
toolbar-reply-to-list-label = Atbildēt sarakstam
toolbar-reply-to-list =
    .title = Atbildēt adresātu sarakstam
toolbar-archive-label = Arhivēt
toolbar-archive =
    .title = Arhivēt atlasītās vēstules
toolbar-conversation-label = Saruna
toolbar-conversation =
    .title = Rādīt atlasītās vēstules sarunu
toolbar-previous-unread-label = Iepriekšējā nelasītā
toolbar-previous-unread =
    .title = Pāriet uz iepriekšējo nelasīto vēstuli
toolbar-previous-label = Iepriekšējais
toolbar-previous =
    .title = Pāriet uz iepriekšējo vēstuli
toolbar-next-unread-label = Nākamā nelasītā
toolbar-next-unread =
    .title = Pāriet uz nākamo nelasīto vēstuli
toolbar-next-label = Nākošais
toolbar-next =
    .title = Pāriet uz nākamo vēstuli
toolbar-junk-label = Draza
toolbar-junk =
    .title = Atzīmēt atlasītās vēstules kā drazu
toolbar-delete-label = Dzēst
toolbar-delete =
    .title = Dzēst mapē atlasītās vēstules
toolbar-compact-label = Saspiest
toolbar-compact =
    .title = Noņemt dzēstās vēstules no atlasītās mapes
toolbar-tag-message-label = Atzīmēt
toolbar-tag-message =
    .title = Birkot vēstules
toolbar-forward-inline-label = Pārsūtīt
toolbar-forward-inline =
    .title = Pārsūtīt atlasīto vēstuli kā iekļautu tekstu
toolbar-forward-attachment-label = Pārsūtīt kā pielikumu
toolbar-forward-attachment =
    .title = Pārsūtīt atlasīto vēstuli kā pielikumu
toolbar-mark-as-label = Atzīmēt
toolbar-mark-as =
    .title = Atzīmēt vēstules
toolbar-address-book =
    .title = Doties uz adrešu grāmatu
toolbar-chat-label = Tērzēšana
toolbar-chat =
    .title = Rādīt Tērzēšana cilni
toolbar-print-label = Drukāt
toolbar-print =
    .title = Drukāt šo vēstuli
toolbar-go-back-label = Atpakaļ
toolbar-go-back =
    .title = Doties vienu vēstuli atpakaļ
toolbar-go-forward-label = Uz priekšu
toolbar-go-forward =
    .title = Doties vienu vēstuli uz priekšu
toolbar-stop-label = Apturēt
toolbar-stop =
    .title = Pārtraukt pašreizējo pārsūtīšanu
toolbar-throbber-label = Darbību rādītājs
toolbar-throbber =
    .title = Darbību rādītājs
