# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Nomine a monstrar
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Typo
vcard-entry-type-home = Initio
vcard-entry-type-work = Labor
vcard-entry-type-none = Nulle
vcard-entry-type-custom = Personalisate
vcard-name-header = Nomine
vcard-n-prefix = Prefixo
vcard-n-add-prefix =
    .title = Adder Firefox
vcard-n-firstname = Prenomine
vcard-n-add-firstname =
    .title = Adde prenomine
vcard-n-middlename = Nomine intermedie
vcard-n-add-middlename =
    .title = Adder nomine intermedie
vcard-n-lastname = Nomine de familia
vcard-n-add-lastname =
    .title = Adde nomine de familia
vcard-n-suffix = Suffixo
vcard-n-add-suffix =
    .title = Adder suffixo
vcard-nickname = Pseudonymo
vcard-email-header = Adresses email
vcard-email-add = Adder adresse email
vcard-email-label = Adresse email
vcard-primary-email-label = Predefinite
vcard-url-header = Sitos web
vcard-url-add = Adder un sito web
vcard-url-label = Sito web
vcard-tel-header = Numeros de telephono
vcard-tel-add = Adder un numero de telephono
vcard-tel-label = Numero de telephono
# Or "Mobile"
vcard-entry-type-cell = Cella
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Cerca-personas
vcard-tz-header = Fuso horari
vcard-tz-add = Adder fuso horari
vcard-impp2-header = Messages instantanee
vcard-impp-add = Adder conto chat
vcard-impp-label = Conto chat
vcard-impp-select = Protocollo
vcard-impp-option-other = Altere
vcard-impp-input-label = URI
vcard-impp-input-title = URI pro messages instantanee
vcard-bday-anniversary-header = Datas special
vcard-bday-anniversary-add = Adder data special
vcard-bday-label = Die natal
vcard-anniversary-label = Anniversario
vcard-date-day = Die
vcard-date-month = Mense
vcard-date-year = Anno
vcard-adr-header = Adresses
vcard-adr-add = Adder adresse
vcard-adr-label = Adresse
vcard-adr-delivery-label = Etiquetta de consignation
vcard-adr-street = Adresse del strata
# Or "Locality"
vcard-adr-locality = Citate
# Or "Region"
vcard-adr-region = Stato/provincia
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Codice postal
vcard-adr-country = Pais
vcard-note-header = Notas
vcard-note-add = Adder nota
vcard-org-header = Proprietates organisative
vcard-org-add = Adder proprietates organisative
vcard-org-title = Titulo
vcard-org-title-input =
    .placeholder = Titulo laborative
    .title = Position o labor
vcard-org-role = Rolo
vcard-org-role-input =
    .placeholder = Rolo in un projecto
    .title = Function o parte jocate in a particular situation
vcard-org-org = Organisation
vcard-org-org-input =
    .placeholder = Nomine del compania
    .title = Nomine organisative
vcard-org-org-unit = Departimento
vcard-org-org-unit-input =
    .placeholder = Departmento
    .title = Nomine del unitate organisative
vcard-custom-header = Proprietates personalisate
vcard-custom-add = Adder proprietates personalisate
vcard-remove-button-title =
    .title = Remover
vcard-remove-button = Remover
