# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Søkjer …
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 treff;#1 treff
noMatchesFound = Ingen treff
labelForStopButton = Stopp
labelForSearchButton = Søk
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = S
moreButtonTooltipText = Legg til ny regel
lessButtonTooltipText = Fjern denne regelen
