# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Se caută…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 rezultat găsit;#1 rezultate găsite
noMatchesFound = Niciun rezultat
labelForStopButton = Oprește
labelForSearchButton = Caută
labelForStopButton.accesskey = O
labelForSearchButton.accesskey = C
moreButtonTooltipText = Adaugă o nouă regulă
lessButtonTooltipText = Elimină această regulă
