# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Tiotal:
calendar-item-summary-calendar = Mìosachan:
calendar-item-summary-task-start = Latha tòiseachaidh:
calendar-item-summary-event-start = Latha tòiseachaidh:
calendar-item-summary-task-due = Ceann-ama:
calendar-item-summary-event-end = Latha crìochnachaidh:
calendar-item-summary-repeat = Dèan a-rithist:
calendar-item-summary-location = Àite:
calendar-item-summary-category = Roinn:
calendar-item-summary-organizer = Eagraiche:
calendar-item-summary-status = Cor:
calendar-item-summary-reminder = Cuimhnich:
calendar-item-summary-attachments = Ceanglachain:
calendar-item-summary-status-tentative = An dòchas
calendar-item-summary-status-confirmed = Air a dhearbhachadh
calendar-item-summary-event-status-cancelled = Air a sgur dheth
calendar-item-summary-todo-status-cancelled = Air a sgur dheth
calendar-item-summary-status-needs-action = Feumach air gnìomh
calendar-item-summary-status-in-process = 'Ga phròiseasadh
calendar-item-summary-status-completed = Air a choileanadh
calendar-item-summary-reminder-none =
    .label = Na cuir 'nam chuimhne
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 mionaid roimhe
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 mionaidean roimhe
calendar-item-summary-reminder-15-minutes-before =
    .label = Cairteal na h-uarach roimhe
calendar-item-summary-reminder-30-minutes-before =
    .label = Leth-uair a thìde roimhe
calendar-item-summary-reminder-1-hour-before =
    .label = 1 uair a thìde roimhe
calendar-item-summary-reminder-2-hours-before =
    .label = 2 uair a thìde roimhe
calendar-item-summary-reminder-12-hours-before =
    .label = 12 uair a thìde roimhe
calendar-item-summary-reminder-1-day-before =
    .label = 1 latha roimhe
calendar-item-summary-reminder-2-days-before =
    .label = 2 latha roimhe
calendar-item-summary-reminder-1-week-before =
    .label = 1 seachdain roimhe
calendar-item-summary-reminder-custom =
    .label = Gnàthaichte…
calendar-item-summary-reminder-multiple =
    .value = Cuir 'nam chuimhne iomadh turas…
calendar-item-summary-general =
    .value = Coitcheann
calendar-item-summary-attendees =
    .value = Freastalaichean
calendar-item-summary-description =
    .value = Tuairisgeul
calendar-item-summary-link =
    .value = Ceangal co-cheangailte
