# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Staðfesting á lestri
return-receipt-checkbox-control =
    .label = Þegar póstur er sendur skal alltaf krefjast staðfestingar á lestri
    .accesskey = p
receipt-arrive-label = Ef kvittun er móttekin:
receipt-leave-inbox-control =
    .label = Skilja eftir í innhólfinu
    .accesskey = i
receipt-move-sent-control =
    .label = Færa í Sent-möppuna
    .accesskey = m
receipt-sender-request-label = Þegar sendandi biður um um staðfestingu á lestri:
receipt-leave-radio-control =
    .label = Skildu það eftir í innhólfinu mínu
    .accesskey = i
receipt-move-radio-control =
    .label = Færa það í „Sent“ möppuna mína
    .accesskey = m
receipt-request-label = Þegar ég móttek beiðni um staðfestingu á lestri:
receipt-return-never-radio-control =
    .label = Aldrei senda staðfestingu á lestri
    .accesskey = d
receipt-return-some-radio-control =
    .label = Leyfa staðfestingu á lestri fyrir sum skilaboð
    .accesskey = y
receipt-not-listed-cc-label =
    .value = Ef það er ekki skráð í Til eða Afrit reitnum:
    .accesskey = f
receipt-not-to-cc-label =
    .value = Ef ég er ekki í Til eða Afrit skilaboðanna:
    .accesskey = E
receipt-send-never-label =
    .label = Aldrei senda
receipt-send-always-label =
    .label = Senda alltaf
receipt-send-ask-label =
    .label = Spyrja mig
sender-outside-company-label =
    .value = Ef sendandi er fyrir utan fyrirtæki eða lén:
    .accesskey = t
sender-outside-domain-label =
    .value = Ef sendandi er utan lénsins míns:
    .accesskey = t
other-cases-text-label =
    .value = Í öllum öðrum tilfellum:
    .accesskey = u
read-receipts-dialog-title = Viðtökusvör
return-receipt-request-control =
    .label = Alltaf óska eftir staðfestingu á lestri þegar þú sendir tölvupóst
    .accesskey = k
