# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (from.today):
# must not be empty!
from.today = ថ្ងៃនេះ
from.tomorrow = ថ្ងៃស្អែក
from.noon = ថ្ងៃត្រង់
# LOCALIZATION NOTE (duration.hours):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.hours = #1 ម៉ោង | #1 ម៉ោង
# LOCALIZATION NOTE (duration.days):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.days = #1 ថ្ងៃ
month.5 = ឧសភា
# LOCALIZATION NOTE (number.*):
# used within other patterns to understand dates where day of month isn't written with digits
# can be a list of values, separate variants by |
number.0 = សូន្យ
number.1 = មួយ | ដំបូង
number.2 = ពីរ | ទីពីរ
number.3 = បី | ទីបី
number.4 = បួន | ទីបួន
number.5 = ប្រាំ | ទីប្រាំ
number.6 = ប្រាំមួយ | ទីប្រាំមួយ
number.7 = ប្រាំពីរ | ទីប្រាំពីរ
number.8 = ប្រាំបី | ទីប្រាំបី
number.9 = ប្រាំបួន | ទីប្រាំបួន
number.10 = ដប់ | ទីដប់
number.11 = ទីដប់មួយ | ទីដប់មួយ
number.12 = ដប់ពីរ | ទីដប់ពីរ
number.13 = ដប់បី | ទីដប់បី
number.14 = ទីដប់បួន | ទីដប់បួន
number.15 = ទីដប់ប្រាំ | ទីដប់ប្រាំ
number.16 = ដប់ប្រាំមួយ | ទីដប់ប្រាំមួយ
number.17 = ដប់ប្រាំពីរ | ទីដប់ប្រាំពីរ
number.18 = ដប់ប្រាំបី | ទីដប់ប្រាំបី
number.19 = ដប់ប្រាំបួន | ដប់ប្រាំបួន
number.20 = ម្ភៃ | ទីម្ភៃ
number.21 = ម្ភៃមួយ | ទីម្ភៃមួយ
