# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Επιλογή όλων
select-none-calendars = Καμία επιλογή
calendar-creation-wizard-title = Δημιουργία νέου ημερολογίου
calendar-creation-initial-description = Το ημερολόγιό σας μπορεί να αποθηκευτεί στον υπολογιστή σας ή σε κάποιο διακομιστή, ώστε να έχετε πρόσβαση σε αυτό απομακρυσμένα ή να το μοιράζεστε με τους φίλους και τους συναδέλφους σας.
calendar-creation-initial-computer =
    .label = Στον υπολογιστή μου
calendar-creation-initial-network =
    .label = Στο δίκτυο
calendar-creation-username =
    .value = Όνομα χρήστη:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Δημιουργία ημερολογίου
    .buttonaccesskeyaccept = ρ
    .buttonlabelextra2 = Πίσω
    .buttonaccesskeyextra2 = Π
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Δημιουργία ημερολογίου
    .buttonaccesskeyaccept = ρ
    .buttonlabelextra2 = Πίσω
    .buttonaccesskeyextra2 = Π
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Εύρεση ημερολογίων
    .buttonaccesskeyaccept = Ε
    .buttonlabelextra2 = Πίσω
    .buttonaccesskeyextra2 = Π
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Εγγραφή
    .buttonaccesskeyaccept = γ
    .buttonlabelextra2 = Πίσω
    .buttonaccesskeyextra2 = Π
calendar-creation-type =
    .value = Τύπος ημερολογίου:
calendar-creation-location =
    .value = Τοποθεσία:
calendar-creation-location-placeholder =
    .placeholder = URL ή όνομα κεντρικού υπολογιστή του διακομιστή ημερολογίου
    .default-placeholder = URL ή όνομα κεντρικού υπολογιστή του διακομιστή ημερολογίου
calendar-creation-network-nocredentials =
    .label = Αυτή η τοποθεσία δεν απαιτεί διαπιστευτήρια
calendar-creation-network-loading = Περιμένετε όσο γίνεται εντοπισμός των ημερολογίων σας.
calendar-creation-network-notfound = Δεν ήταν δυνατή η εύρεση ημερολογίων σε αυτήν την τοποθεσία. Ελέγξτε τις ρυθμίσεις σας.
calendar-creation-network-authfail = Τα διαπιστευτήρια που έχετε εισαγάγει δεν έγιναν αποδεκτά. Ελέγξτε τις ρυθμίσεις σας.
calendar-creation-network-certerror = Δεν ήταν δυνατή η εύρεση ημερολογίων σε αυτήν την τοποθεσία λόγω προβλήματος με το πιστοποιητικό.
calendar-creation-network-subscribe-single = Επιλέξτε τα ημερολόγια στα οποία θέλετε να εγγραφείτε.
calendar-creation-network-subscribe-multiple = Διατίθενται πολλαπλοί τύποι ημερολογίων σε αυτήν την τοποθεσία. Επιλέξτε τον τύπο ημερολογίου και έπειτα, επιλέξτε τα ημερολόγια που θέλετε να εγγραφείτε.
