# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Σχόλιο
calendar-item-summary-title = Τίτλος:
calendar-item-summary-calendar = Ημερολόγιο:
calendar-item-summary-task-start = Ημερομηνία έναρξης:
calendar-item-summary-event-start = Ημερομηνία έναρξης:
calendar-item-summary-task-due = Προθεσμία:
calendar-item-summary-event-end = Ημερομηνία λήξης:
calendar-item-summary-repeat = Επανάληψη:
calendar-item-summary-location = Τοποθεσία:
calendar-item-summary-category = Κατηγορία:
calendar-item-summary-organizer = Διοργανωτής:
calendar-item-summary-status = Κατάσταση:
calendar-item-summary-reminder = Υπενθύμιση:
calendar-item-summary-attachments = Συνημμένα:
calendar-item-summary-status-tentative = Με επιφύλαξη
calendar-item-summary-status-confirmed = Επιβεβαιωμένο
calendar-item-summary-event-status-cancelled = Ακυρωμένο
calendar-item-summary-todo-status-cancelled = Ακυρωμένη
calendar-item-summary-status-needs-action = Απαιτείται ενέργεια
calendar-item-summary-status-in-process = Σε εξέλιξη
calendar-item-summary-status-completed = Ολοκληρώθηκε στις
calendar-item-summary-reminder-none =
    .label = Χωρίς υπενθύμιση{ " " }
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 λεπτά πριν
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 λεπτά πριν
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 λεπτά πριν
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 λεπτά πριν
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ώρα πριν
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ώρες πριν
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ώρες πριν
calendar-item-summary-reminder-1-day-before =
    .label = 1 ημέρα πριν
calendar-item-summary-reminder-2-days-before =
    .label = 2 ημέρες πριν
calendar-item-summary-reminder-1-week-before =
    .label = 1 εβδομάδα πριν
calendar-item-summary-reminder-custom =
    .label = Προσαρμογή…
calendar-item-summary-reminder-multiple =
    .value = Πολλαπλές υπενθυμίσεις…
calendar-item-summary-general =
    .value = Γενικά
calendar-item-summary-attendees =
    .value = Συμμετέχοντες
calendar-item-summary-description =
    .value = Περιγραφή
calendar-item-summary-link =
    .value = Σχετικός σύνδεσμος
