# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Buscando…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Se encontró #1 coincidencia;Se encontraron #1 coincidencias
noMatchesFound = No se encontraron coincidencias
labelForStopButton = Detener
labelForSearchButton = Buscar
labelForStopButton.accesskey = D
labelForSearchButton.accesskey = B
moreButtonTooltipText = Agregar una nueva regla
lessButtonTooltipText = Eliminar esta regla
