# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espacio flexible
search-bar-label = Buscar
toolbar-write-message-label = Redactar
toolbar-write-message =
    .title = Redactar nuevo mensaje
toolbar-move-to-label = Mover a
toolbar-move-to =
    .title = Mover mensaje seleccionado
toolbar-unifinder-label = Buscar eventos
toolbar-unifinder =
    .title = Activar/desactivar el panel Encontrar eventos
toolbar-folder-location-label = Ubicación de la carpeta
toolbar-folder-location =
    .title = Cambiar a carpeta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar evento o tarea seleccionada
toolbar-get-messages-label = Obtener mensajes
toolbar-get-messages =
    .title = Obtener nuevos mensajes para todas las cuentas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder al mensaje
toolbar-reply-all-label = Responder a todos
toolbar-reply-all =
    .title = Responder al remitente y todos los destinatarios
toolbar-reply-to-list-label = Responder a la lista
toolbar-reply-to-list =
    .title = Responder a lista de correos
toolbar-redirect-label = Redirigir
toolbar-redirect =
    .title = Redirigir mensaje seleccionado
toolbar-archive-label = Archivar
toolbar-archive =
    .title = Archivar mensajes seleccionados
toolbar-conversation-label = Conversación
toolbar-conversation =
    .title = Mostrar conversación del mensaje seleccionado
toolbar-previous-unread-label = Anterior no leído
toolbar-previous-unread =
    .title = Cambiar al mensaje previo no leído
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Cambiar al mensaje previo
toolbar-next-unread-label = Siguiente no leído
toolbar-next-unread =
    .title = Cambiar al siguiente mensaje no leído
toolbar-next-label = Siguiente
toolbar-next =
    .title = Cambiar al siguiente mensaje
toolbar-junk-label = Basura
toolbar-junk =
    .title = Marcar los mensajes seleccionados como basura
toolbar-delete-label = Eliminar
toolbar-delete =
    .title = Eliminar mensajes o carpetas seleccionadas
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Quitar mensajes borrados de la carpeta seleccionada
toolbar-add-as-event-label = Agregar como evento
toolbar-add-as-event =
    .title = Extraer información de calendario del mensaje y agregar a tu calendario como evento
toolbar-add-as-task-label = Agregar como tarea
toolbar-add-as-task =
    .title = Extraer información de calendario del mensaje y agregar a tu calendario como tarea
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Etiquetas de mensajes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar mensaje seleccionado como texto en línea
toolbar-forward-attachment-label = Reenviar como adjunto
toolbar-forward-attachment =
    .title = Reenviar mensaje seleccionado como adjunto
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensajes
toolbar-view-picker-label = Ver
toolbar-view-picker =
    .title = Personalizar vista de la carpeta actual
toolbar-address-book-label = Libreta de direcciones
toolbar-address-book =
    .title = Ir a la libreta de direcciones
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mostrar la pestaña de Chat
toolbar-add-ons-and-themes-label = Complementos y temas
toolbar-add-ons-and-themes =
    .title = Administra tus complementos
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Cambiar a la pestaña calendario
toolbar-tasks-label = Tareas
toolbar-tasks =
    .title = Cambiar a la pestaña tareas
toolbar-mail-label = Correo
toolbar-mail =
    .title = Cambiar a la pestaña de correo electronico
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir este mensaje
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensajes
toolbar-synchronize-label = Sincronizar
toolbar-synchronize =
    .title = Recargar calendario y sincronizar cambios
toolbar-delete-event-label = Eliminar
toolbar-delete-event =
    .title = Eliminar eventos o tareas seleccionados
toolbar-go-to-today-label = Ir al día de hoy
toolbar-go-to-today =
    .title = Ir al día de hoy
toolbar-print-event-label = Imprimir
toolbar-print-event =
    .title = Imprimir eventos o tareas
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Crear un nuevo evento
toolbar-new-task-label = Tarea
toolbar-new-task =
    .title = Crear una nueva tarea
toolbar-go-back-label = Atrás
toolbar-go-back =
    .title = Anterior
toolbar-go-forward-label = Avanzar
toolbar-go-forward =
    .title = Siguiente
toolbar-stop-label = Detener
toolbar-stop =
    .title = Detener la transferencia actual
toolbar-throbber-label = Indicador de actividad
toolbar-throbber =
    .title = Indicador de actividad
