# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Wrthi'n chwilio…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = wedi canfod #1 sy'n cydweddu;wedi canfod #1 sy'n cydweddu
noMatchesFound = Heb ganfod cydweddiad
labelForStopButton = Atal
labelForSearchButton = Chwilio
labelForStopButton.accesskey = A
labelForSearchButton.accesskey = C
moreButtonTooltipText = Ychwanegu rheol newydd
lessButtonTooltipText = Tynnu'r rheol
