# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Mencari…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Ditemukan #1 yang cocok;Ditemukan #1 yang cocok
noMatchesFound = Tidak ada yang cocok
labelForStopButton = Berhenti
labelForSearchButton = Cari
labelForStopButton.accesskey = i
labelForSearchButton.accesskey = C
moreButtonTooltipText = Tambahkan aturan baru
lessButtonTooltipText = Hapus aturan ini
