# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = ყველას მონიშვნა
select-none-calendars = არცერთის მონიშვნა
calendar-creation-wizard-title = ახალი კალენდრის შექმნა
calendar-creation-initial-description = თქვენი კალენდრის შენახვა შესაძლებელია როგორც თქვენს კომპიუტერში, ისე სერვერზე, რომ გარედან იყოს მისაწვდომი და მისი მეგობრებთან თუ თანამშრომლებთან გაზიარება შეძლოთ.
calendar-creation-initial-computer =
    .label = ჩემს კომპიუტერში
calendar-creation-initial-network =
    .label = ქსელში
calendar-creation-username =
    .value = მომხმარებელი:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = კალენდრის შექმნა
    .buttonaccesskeyaccept = ქ
    .buttonlabelextra2 = უკან
    .buttonaccesskeyextra2 = უ
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = კალენდრის შექმნა
    .buttonaccesskeyaccept = ქ
    .buttonlabelextra2 = უკან
    .buttonaccesskeyextra2 = უ
calendar-creation-panel-network-settings =
    .buttonlabelaccept = კალენდრის პოვნა
    .buttonaccesskeyaccept = პ
    .buttonlabelextra2 = უკან
    .buttonaccesskeyextra2 = უ
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = გამოწერა
    .buttonaccesskeyaccept = წ
    .buttonlabelextra2 = უკან
    .buttonaccesskeyextra2 = უ
calendar-creation-type =
    .value = კალენდრის სახეობა:
calendar-creation-location =
    .value = მდებარეობა:
calendar-creation-location-placeholder =
    .placeholder = კალენდრის სერვერის URL-ბმული ან კვანძის სახელი
    .default-placeholder = კალენდრის სერვერის URL-ბმული ან კვანძის სახელი
calendar-creation-network-nocredentials =
    .label = ეს მისამართი არ საჭიროებს ანგარიშის მონაცემებს
calendar-creation-network-loading = გთხოვთ მოითმინოთ, სანამ თქვენი კალენდრები მოინახება.
calendar-creation-network-notfound = ამ მისამართზე კალენდრები არ მოიძებნა. გთხოვთ, გადაამოწმოთ თქვენი პარამეტრები.
calendar-creation-network-authfail = თქვენ მიერ შეყვანილი ანგარიშის მონაცემები არაა მიღებული. გთხოვთ, გადაამოწმოთ თქვენი პარამეტრები.
calendar-creation-network-certerror = ამ მისამართზე კალენდრები ვერ მოიძებნა სერტიფიკატის ხარვეზის გამო.
calendar-creation-network-subscribe-single = გთხოვთ, მიუთითოთ კალენდრები, რომელთა გამოწერაც გსურთ.
calendar-creation-network-subscribe-multiple = ამ მისამართზე მრავალი სხვადასხვა სახის კალენდარია ხელმისაწვდომი. გთხოვთ, აირჩიოთ სასურველი სახის კალენდარი და შემდეგ მონიშნოთ ის კალენდრები, რომელთა გამოწერაც გსურთ.
