# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = სათაური:
calendar-item-summary-calendar = კალენდარი:
calendar-item-summary-task-start = დაწყება:
calendar-item-summary-event-start = დაწყების თარიღი:
calendar-item-summary-task-due = დასრულება:
calendar-item-summary-event-end = დასრულების თარიღი:
calendar-item-summary-repeat = გამეორება:
calendar-item-summary-location = ადგილი:
calendar-item-summary-category = კატეგორია:
calendar-item-summary-organizer = მოთავე:
calendar-item-summary-status = მდგომარეობა:
calendar-item-summary-reminder = შეხსენება:
calendar-item-summary-attachments = დანართები:
calendar-item-summary-status-tentative = სავარაუდო
calendar-item-summary-status-confirmed = დადასტურებული
calendar-item-summary-event-status-cancelled = გაუქმებული
calendar-item-summary-todo-status-cancelled = გაუქმდა
calendar-item-summary-status-needs-action = საჭიროებს მოქმედებას
calendar-item-summary-status-in-process = მიმდინარეობს
calendar-item-summary-status-completed = დასრულდა -
calendar-item-summary-reminder-none =
    .label = შეხსენების გარეშე
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 წუთით ადრე
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 წუთით ადრე
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 წუთით ადრე
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 წუთით ადრე
calendar-item-summary-reminder-1-hour-before =
    .label = 1 საათით ადრე
calendar-item-summary-reminder-2-hours-before =
    .label = 2 საათით ადრე
calendar-item-summary-reminder-12-hours-before =
    .label = 12 საათით ადრე
calendar-item-summary-reminder-1-day-before =
    .label = 1 დღით ადრე
calendar-item-summary-reminder-2-days-before =
    .label = 2 დღით ადრე
calendar-item-summary-reminder-1-week-before =
    .label = 1 კვირით ადრე
calendar-item-summary-reminder-custom =
    .label = მითითებული დროით…
calendar-item-summary-reminder-multiple =
    .value = მრავალჯერადი შეხსენებები…
calendar-item-summary-general =
    .value = ზოგადი
calendar-item-summary-attendees =
    .value = დამსწრეები
calendar-item-summary-description =
    .value = აღწერილობა
calendar-item-summary-link =
    .value = დაკავშირებული ბმა
