# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = განმეორებითი ღონისძიება
header-isrepeating-task =
    .label = განმეორებითი დავალებაა
header-containsrepeating-event =
    .label = შეიცავს განმეორებით ღონისძიებებს
header-containsrepeating-task =
    .label = შეიცავს განმეორებით დავალებებს
header-containsrepeating-mixed =
    .label = შეიცავს სხვადასხვა სახის განმეორებით ელემენტებს
windowtitle-event-copy = განმეორებითი ღონისძიების ასლი
windowtitle-task-copy = განმეორებითი დავალების ასლი
windowtitle-mixed-copy = განმეორებითი ელემენტების ასლი
windowtitle-event-cut = განმეორებითი ღონისძიების ამოჭრა
windowtitle-task-cut = განმეორებითი დავალების ამოჭრა
windowtitle-mixed-cut = განმეორებითი ელემენტების ამოჭრა
windowtitle-event-delete = განმეორებითი ღონისძიების წაშლა
windowtitle-task-delete = განმეორებითი დავალების წაშლა
windowtitle-mixed-delete = განმეორებითი ელემენტების წაშლა
windowtitle-event-edit = განმეორებითი ღონისძიების ჩასწორება
windowtitle-task-edit = განმეორებითი დავალების ჩასწორება
windowtitle-mixed-edit = განმეორებითი ელემენტების ჩასწორება
windowtitle-multipleitems =
    .value = შერჩეული ელემენტები
button-single-occurrence-copy =
    .label = მხოლოდ ამ ჩატარების თარიღის ასლი
    .accesskey = ბ
button-single-occurrence-cut =
    .label = მხოლოდ ამ ჩატარების თარიღის ამოჭრა
    .accesskey = ბ
button-single-occurrence-delete =
    .label = მხოლოდ ამ ჩატარების თარიღის წაშლა
    .accesskey = ბ
button-single-occurrence-edit =
    .label = მხოლოდ ამ ჩატარების თარიღის ჩასწორება
    .accesskey = ბ
button-multiple-occurrence-copy =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ასლი
    .accesskey = ბ
button-multiple-occurrence-cut =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ამოჭრა
    .accesskey = ბ
button-multiple-occurrence-delete =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების წაშლა
    .accesskey = ბ
button-multiple-occurrence-edit =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ჩასწორება
    .accesskey = ბ
button-single-allfollowing-copy =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ასლი
    .accesskey = f
button-single-allfollowing-cut =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ამოჭრა
    .accesskey = f
button-single-allfollowing-delete =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის წაშლა
    .accesskey = f
button-single-allfollowing-edit =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ჩასწორება
    .accesskey = f
button-multiple-allfollowing-copy =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ასლი
    .accesskey = f
button-multiple-allfollowing-cut =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ამოჭრა
    .accesskey = f
button-multiple-allfollowing-delete =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის წაშლა
    .accesskey = f
button-multiple-allfollowing-edit =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ჩასწორება
    .accesskey = f
button-single-parent-copy =
    .label = ყველა ჩატარების თარიღის ასლი
    .accesskey = a
button-single-parent-cut =
    .label = ყველა ჩატარების თარიღის ამოჭრა
    .accesskey = a
button-single-parent-delete =
    .label = ყველა ჩატარების თარიღის წაშლა
    .accesskey = a
button-single-parent-edit =
    .label = ყველა ჩატარების თარიღის ჩასწორება
    .accesskey = a
button-multiple-parent-copy =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ასლი
    .accesskey = a
button-multiple-parent-cut =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ამოჭრა
    .accesskey = a
button-multiple-parent-delete =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის წაშლა
    .accesskey = a
button-multiple-parent-edit =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ჩასწორება
    .accesskey = a
buttons-single-occurrence-copy =
    .label = მხოლოდ ამ ჩატარების თარიღის ასლი
buttons-single-occurrence-cut =
    .label = მხოლოდ ამ ჩატარების თარიღის ამოჭრა
buttons-single-occurrence-delete =
    .label = მხოლოდ ამ ჩატარების თარიღის წაშლა
buttons-single-occurrence-edit =
    .label = მხოლოდ ამ ჩატარების თარიღის ჩასწორება
buttons-multiple-occurrence-copy =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ასლი
buttons-multiple-occurrence-cut =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ამოჭრა
buttons-multiple-occurrence-delete =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების წაშლა
buttons-multiple-occurrence-edit =
    .label = მხოლოდ მონიშნული ჩატარების თარიღების ჩასწორება
buttons-single-allfollowing-copy =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ასლი
buttons-single-allfollowing-cut =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ამოჭრა
buttons-single-allfollowing-delete =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის წაშლა
buttons-single-allfollowing-edit =
    .label = ამ და ყველა მომავალი ჩატარების თარიღის ჩასწორება
buttons-multiple-allfollowing-copy =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ასლი
buttons-multiple-allfollowing-cut =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ამოჭრა
buttons-multiple-allfollowing-delete =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის წაშლა
buttons-multiple-allfollowing-edit =
    .label = მონიშნულების და ყველა მომავალი ჩატარების თარიღის ჩასწორება
buttons-single-parent-copy =
    .label = ყველა ჩატარების თარიღის ასლი
buttons-single-parent-cut =
    .label = ყველა ჩატარების თარიღის ამოჭრა
buttons-single-parent-delete =
    .label = ყველა ჩატარების თარიღის წაშლა
buttons-single-parent-edit =
    .label = ყველა ჩატარების თარიღის ჩასწორება
buttons-multiple-parent-copy =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ასლი
buttons-multiple-parent-cut =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ამოჭრა
buttons-multiple-parent-delete =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის წაშლა
buttons-multiple-parent-edit =
    .label = მონიშნული ელემენტების ყველა მომავალი ჩატარების თარიღის ჩასწორება
