# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Flexibele ruimte
search-bar-label = Zoeken
toolbar-write-message-label = Opstellen
toolbar-write-message =
    .title = Een nieuw bericht aanmaken
toolbar-move-to-label = Verplaatsen naar
toolbar-move-to =
    .title = Geselecteerde bericht verplaatsen
toolbar-unifinder-label = Gebeurtenissen zoeken
toolbar-unifinder =
    .title = Het paneel Gebeurtenissen zoeken in-/uitschakelen
toolbar-folder-location-label = Maplocatie
toolbar-folder-location =
    .title = Wisselen naar map
toolbar-edit-event-label = Bewerken
toolbar-edit-event =
    .title = Geselecteerde gebeurtenis of taak bewerken
toolbar-get-messages-label = Berichten ophalen
toolbar-get-messages =
    .title = Nieuwe berichten voor alle accounts ophalen
toolbar-reply-label = Beantwoorden
toolbar-reply =
    .title = Het geselecteerde bericht beantwoorden
toolbar-reply-all-label = Allen beantwoorden
toolbar-reply-all =
    .title = Afzender en alle ontvangers beantwoorden
toolbar-reply-to-list-label = Lijst beantwoorden
toolbar-reply-to-list =
    .title = Mailinglijst beantwoorden
toolbar-redirect-label = Omleiden
toolbar-redirect =
    .title = Geselecteerd bericht omleiden
toolbar-archive-label = Archiveren
toolbar-archive =
    .title = Geselecteerde berichten archiveren
toolbar-conversation-label = Conversatie
toolbar-conversation =
    .title = Conversatie van geselecteerde bericht tonen
toolbar-previous-unread-label = Vorige ongelezen
toolbar-previous-unread =
    .title = Naar het vorige ongelezen bericht gaan
toolbar-previous-label = Vorige
toolbar-previous =
    .title = Naar het vorige bericht gaan
toolbar-next-unread-label = Volgende ongelezen
toolbar-next-unread =
    .title = Naar het volgende ongelezen bericht gaan
toolbar-next-label = Volgende
toolbar-next =
    .title = Naar het volgende bericht gaan
toolbar-junk-label = Ongewenst
toolbar-junk =
    .title = De geselecteerde berichten als ongewenst markeren
toolbar-delete-label = Verwijderen
toolbar-delete-title =
    .title = De geselecteerde berichten verwijderen
toolbar-undelete-label = Verwijderen ongedaan maken
toolbar-undelete =
    .title = Verwijderen van de geselecteerde berichten ongedaan maken
toolbar-compact-label = Comprimeren
toolbar-compact =
    .title = Verwijderde berichten uit geselecteerde map verwijderen
toolbar-add-as-event-label = Toevoegen als gebeurtenis
toolbar-add-as-event =
    .title = Agendagegevens uit het bericht halen en deze aan uw agenda toevoegen als een gebeurtenis
toolbar-add-as-task-label = Toevoegen als taak
toolbar-add-as-task =
    .title = Agendagegevens uit het bericht halen en deze aan uw agenda toevoegen als een taak
toolbar-tag-message-label = Labelen
toolbar-tag-message =
    .title = Berichten labelen
toolbar-forward-inline-label = Doorsturen
toolbar-forward-inline =
    .title = Geselecteerde bericht doorsturen in het bericht
toolbar-forward-attachment-label = Doorsturen als bijlage
toolbar-forward-attachment =
    .title = Geselecteerde bericht doorsturen als bijlage
toolbar-mark-as-label = Markeren
toolbar-mark-as =
    .title = Berichten markeren
toolbar-view-picker-label = Beeld
toolbar-view-picker =
    .title = Weergave van huidige map aanpassen
toolbar-address-book-label = Adresboek
toolbar-address-book =
    .title = Naar het adresboek gaan
toolbar-chat-label = Chat
toolbar-chat =
    .title = Het chattabblad tonen
toolbar-add-ons-and-themes-label = Add-ons en thema’s
toolbar-add-ons-and-themes =
    .title = Uw add-ons beheren
toolbar-calendar-label = Agenda
toolbar-calendar =
    .title = Wisselen naar het agendatabblad
toolbar-tasks-label = Taken
toolbar-tasks =
    .title = Wisselen naar het takentabblad
toolbar-mail-label = E-mail
toolbar-mail =
    .title = Wisselen naar het e-mailtabblad
toolbar-print-label = Afdrukken
toolbar-print =
    .title = Dit bericht afdrukken
toolbar-quick-filter-bar-label = Snelfilter
toolbar-quick-filter-bar =
    .title = Berichten filteren
toolbar-synchronize-label = Synchroniseren
toolbar-synchronize =
    .title = Agenda’s opnieuw laden en wijzigingen synchroniseren
toolbar-delete-event-label = Verwijderen
toolbar-delete-event =
    .title = Geselecteerde gebeurtenissen of taken verwijderen
toolbar-go-to-today-label = Naar vandaag gaan
toolbar-go-to-today =
    .title = Naar vandaag gaan
toolbar-print-event-label = Afdrukken
toolbar-print-event =
    .title = Gebeurtenissen of taken afdrukken
toolbar-new-event-label = Gebeurtenis
toolbar-new-event =
    .title = Een nieuwe gebeurtenis maken
toolbar-new-task-label = Taak
toolbar-new-task =
    .title = Een nieuwe taak maken
toolbar-go-back-label = Terug
toolbar-go-back =
    .title = Een bericht terug gaan
toolbar-go-forward-label = Vooruit
toolbar-go-forward =
    .title = Een bericht vooruit gaan
toolbar-stop-label = Stoppen
toolbar-stop =
    .title = De huidige overdracht stoppen
toolbar-throbber-label = Activiteitsindicator
toolbar-throbber =
    .title = Activiteitsindicator
toolbar-create-contact-label = Nieuw contact
toolbar-create-contact =
    .title = Een nieuw contact aanmaken
toolbar-create-address-book-label = Nieuw adresboek
toolbar-create-address-book =
    .title = Een nieuw adresboek aanmaken
toolbar-create-list-label = Nieuwe lijst
toolbar-create-list =
    .title = Een nieuwe e-maillijst aanmaken
toolbar-import-contacts-label = Importeren
toolbar-import-contacts =
    .title = Contacten uit een bestand importeren

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lokaal adresboek toevoegen
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV-adresboek toevoegen
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP-adresboek toevoegen
