# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = S'està cercant…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = S'ha trobat #1 coincidència;S'han trobat #1 coincidències
noMatchesFound = No s'ha trobat cap coincidència
labelForStopButton = Atura
labelForSearchButton = Cerca
labelForStopButton.accesskey = u
labelForSearchButton.accesskey = C
moreButtonTooltipText = Afegeix una regla nova
lessButtonTooltipText = Suprimeix aquesta regla
