# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (from.today):
# must not be empty!
from.today = היום
from.tomorrow = מחר
# LOCALIZATION NOTE (from.half.hour.before):
# denotes times 30 minutes before next full hour
from.half.hour.before = חצי שעה לפני #1
# LOCALIZATION NOTE (from.half.hour.after):
# denotes times 30 minutes after last full hour
from.half.hour.after = #1 וחצי
# LOCALIZATION NOTE (from.month.day):
##1 = matches numbers 1-31
##2 = matches numbers 1-12
from.month.day = #2/#1
# LOCALIZATION NOTE (duration.days):
##1 = matches 1/2 numbers and number.0 - and number.31
duration.days = #1 ימים
# LOCALIZATION NOTE (month.*):
# can be a list of values, separate variants by |
month.1 = ינואר | ינו | ינו׳
month.2 = פברואר | פבר | פבר׳
month.3 = מרץ | מרס | מארס
month.4 = אפריל | אפר | אפר׳
month.5 = מאי
month.6 = יוני | יונ | יונ׳
month.7 = יולי | יול | יול׳
month.8 = אוגוסט | אוג | אוג׳
month.9 = ספטמבר | ספט | ספט׳
month.10 = אוקטובר | אוק | אוק׳
month.11 = נובמבר | נוב | נוב׳
month.12 = דצמבר | דצמ | דצמ׳
# LOCALIZATION NOTE (from.weekday.*):
# used to derive start date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (from.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
from.weekday.0 = ראשון | יום ראשון | יום א׳ | יום א | א׳ | א
from.weekday.1 = שני | יום שני | יום ב׳ | יום ב | ב
from.weekday.2 = יום שלישי | ימי שלישי
from.weekday.3 = יום רביעי | ימי רביעי
from.weekday.4 = יום חמישי | ימי חמישי
from.weekday.5 = יום שישי | ימי שישי
from.weekday.6 = שבת | שבתות
# LOCALIZATION NOTE (number.*):
# used within other patterns to understand dates where day of month isn't written with digits
# can be a list of values, separate variants by |
number.0 = אפס
number.1 = אחד | ראשון
number.2 = שתיים | שני | שניים
number.3 = שלוש | שלישי | שלושה
number.4 = ארבע | רביעי | ארבעה
number.5 = חמש | חמישי | חמישה
number.6 = שש | שישי | שישה
number.7 = שבע | שביעי | שבעה
number.8 = שמונה | שמיני
number.9 = תשע | תשיעי | תשעה
number.10 = עשר | עשירי | עשרה
number.11 = אחד עשר | אחת עשרה | האחד עשר | האחת עשרה | האחד עשרה | האחת עשר
number.12 = שניים עשר | השניים עשר | שתיים עשרה | השתיים עשרה | השניים עשרה | השתיים עשר
number.13 = שלושה עשר | שלוש עשרה | השלושה עשר | השלוש עשרה | שלושה עשרה | שלוש עשר
number.31 = עשרים ואחד | עשרים ואחת | העשרים ואחת | העשרים ואחד
# LOCALIZATION NOTE (alphabet):
# list all lower and uppercase letters if your language has an alphabet
# otherwise leave it empty
alphabet = אבגדהוזחטיכךלמםנןסעפףצץקרשת
