# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = yn ddigwyddiad sy'n ailadrodd
header-isrepeating-task =
    .label = yn dasg sy'n ailadrodd
header-containsrepeating-event =
    .label = yn cynnwys digwyddiadau sy'n ailadrodd
header-containsrepeating-task =
    .label = yn cynnwys tasgau sy'n ailadrodd
header-containsrepeating-mixed =
    .label = yn cynnwys eitemau o fathau gwahanol sy'n ailadrodd
windowtitle-event-copy = Copïo Digwyddid sy'n Ailadrodd
windowtitle-task-copy = Copïo Tasg sy'n Ailadrodd
windowtitle-mixed-copy = Copïo Eitemau sy'n Ailadrodd
windowtitle-event-cut = Torri Digwyddiad sy'n Ailadrodd
windowtitle-task-cut = Torri Tasgsy'n Ailadrodd
windowtitle-mixed-cut = Torri Eitemau sy'n Ailadrodd
windowtitle-event-delete = Dileu Tasg Ailadroddus
windowtitle-task-delete = Dileu Tasg Ailadroddus
windowtitle-mixed-delete = Dileu Eitemau sy'n Ailadrodd
windowtitle-event-edit = Golygu Tasg Ailadroddus
windowtitle-task-edit = Golygu Tasg Ailadroddus
windowtitle-mixed-edit = Golygu Eitemau Ailadroddus
windowtitle-multipleitems =
    .value = Eitemau dewisiwyd
button-single-occurrence-edit =
    .label = Golygu dim ond y digwyddiad yma
    .accesskey = y
button-multiple-occurrence-copy =
    .label = Copïo dim ond yr achlysuron hyn
    .accesskey = y
button-multiple-occurrence-cut =
    .label = Torri dim ond yr achlysuron hyn
    .accesskey = y
button-multiple-occurrence-delete =
    .label = Dileu dim ond yr achlysuron hyn
    .accesskey = y
button-multiple-occurrence-edit =
    .label = Golygu achlysuron penodol
    .accesskey = y
button-single-allfollowing-copy =
    .label = Copïo hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-single-allfollowing-cut =
    .label = Torri hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-single-allfollowing-delete =
    .label = Dileu hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-single-allfollowing-edit =
    .label = Golygu hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-multiple-allfollowing-copy =
    .label = Copïo hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-multiple-allfollowing-cut =
    .label = Torri hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-multiple-allfollowing-delete =
    .label = Dileu hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-multiple-allfollowing-edit =
    .label = Golygu hwn a phob achlysur i'r dyfodol
    .accesskey = f
button-single-parent-copy =
    .label = Copïo pob achlysur
    .accesskey = a
button-single-parent-cut =
    .label = Torri pob achlysur
    .accesskey = a
button-single-parent-delete =
    .label = Dileu pob achlysur
    .accesskey = a
button-single-parent-edit =
    .label = Golygu pob enghraifft
    .accesskey = a
button-multiple-parent-copy =
    .label = Copïo pob achlysur o'r eitemau hyn
    .accesskey = a
button-multiple-parent-cut =
    .label = Torri pob achlysur o'r eitemau hyn
    .accesskey = a
button-multiple-parent-delete =
    .label = Dileu pob achlysur o'r eitemau hyn
    .accesskey = a
button-multiple-parent-edit =
    .label = Golygu pob achlysur o'r eitemau hyn
    .accesskey = a
buttons-single-occurrence-copy =
    .label = Copïo dim ond y tro yma
buttons-single-occurrence-cut =
    .label = Torri dim ond yr achlysur yma
buttons-single-occurrence-delete =
    .label = Dileu dim ond yr achlysur yma
buttons-single-occurrence-edit =
    .label = Golygu dim ond y digwyddiad yma
buttons-multiple-occurrence-copy =
    .label = Copïo dim ond yr achlysuron hyn
buttons-multiple-occurrence-cut =
    .label = Torri dim ond yr achlysuron hyn
buttons-multiple-occurrence-delete =
    .label = Dileu dim ond yr achlysuron hyn
buttons-multiple-occurrence-edit =
    .label = Golygu achlysuron penodol
buttons-single-allfollowing-copy =
    .label = Copïo hwn a phob achlysur i'r dyfodol
buttons-single-allfollowing-cut =
    .label = Torri hwn a phob achlysur i'r dyfodol
buttons-single-allfollowing-delete =
    .label = Dileu hwn a phob achlysur i'r dyfodol
buttons-single-allfollowing-edit =
    .label = Golygu hwn a phob achlysur i'r dyfodol
buttons-multiple-allfollowing-copy =
    .label = Copïo hwn a phob achlysur i'r dyfodol
buttons-multiple-allfollowing-cut =
    .label = Torri hwn a phob achlysur i'r dyfodol
buttons-multiple-allfollowing-delete =
    .label = Dileu hwn a phob achlysur i'r dyfodol
buttons-multiple-allfollowing-edit =
    .label = Golygu hwn a phob achlysur i'r dyfodol
buttons-single-parent-copy =
    .label = Copïo pob achlysur
buttons-single-parent-cut =
    .label = Torri pob achlysur
buttons-single-parent-delete =
    .label = Dileu pob achlysur
buttons-single-parent-edit =
    .label = Golygu pob enghraifft
buttons-multiple-parent-copy =
    .label = Copïo pob achlysur o'r eitemau hyn
buttons-multiple-parent-cut =
    .label = Torri pob achlysur o'r eitemau hyn
buttons-multiple-parent-delete =
    .label = Dileu pob achlysur o'r eitemau hyn
buttons-multiple-parent-edit =
    .label = Golygu pob achlysur o'r eitemau hyn
