# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Sylw
calendar-item-summary-title = Teitl:
calendar-item-summary-calendar = Calendr:
calendar-item-summary-task-start = Dyddiad Cychwyn:
calendar-item-summary-event-start = Dyddiad Cychwyn:
calendar-item-summary-task-due = Dyddiad Gorffen:
calendar-item-summary-event-end = Dyddiad Gorffen:
calendar-item-summary-repeat = Ailadrodd:
calendar-item-summary-location = Lleoliad:
calendar-item-summary-category = Categori:
calendar-item-summary-organizer = Trefnydd:
calendar-item-summary-status = Statws:
calendar-item-summary-reminder = Atgoffwr:
calendar-item-summary-attachments = Atodiadau:
calendar-item-summary-status-tentative = Amodol
calendar-item-summary-status-confirmed = Cadarnhawyd
calendar-item-summary-event-status-cancelled = Diddymwyd
calendar-item-summary-todo-status-cancelled = Diddymwyd
calendar-item-summary-status-needs-action = Angen Gweithredu
calendar-item-summary-status-in-process = Ar Waith
calendar-item-summary-status-completed = Cwblhawyd
calendar-item-summary-reminder-none =
    .label = Dim atgoffwr
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 munud cyn hynny
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 munud cyn hynny
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 munud cyn hynny
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 munud cyn hynny
calendar-item-summary-reminder-1-hour-before =
    .label = 1 awr cyn hynny
calendar-item-summary-reminder-2-hours-before =
    .label = 2 awr cyn hynny
calendar-item-summary-reminder-12-hours-before =
    .label = 12 awr cyn hynny
calendar-item-summary-reminder-1-day-before =
    .label = 1 diwrnod cyn hynny
calendar-item-summary-reminder-2-days-before =
    .label = 2 diwrnod cyn hynny
calendar-item-summary-reminder-1-week-before =
    .label = 1 wythnos cyn hynny
calendar-item-summary-reminder-custom =
    .label = Cyfaddasu…
calendar-item-summary-reminder-multiple =
    .value = Atgoffwyr Niferus…
calendar-item-summary-general =
    .value = Cyffredinol
calendar-item-summary-attendees =
    .value = Mynychwyr
calendar-item-summary-description =
    .value = Disgrifiad
calendar-item-summary-link =
    .value = Dolenni Perthnasol
