# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-deactivated-notification-events = Mae pob calendr wedi'i analluogi ar hyn o bryd. Galluogwch galendr sy'n bodoli eisoes neu ychwanegu un newydd i greu a golygu digwyddiadau.
calendar-deactivated-notification-tasks = Mae pob calendr wedi'i analluogi ar hyn o bryd. Galluogwch galendr sy'n bodoli eisoes neu ychwanegu un newydd i greu a golygu tasgau.
calendar-notifications-label = Dangos hysbysiadau ar gyfer digwyddiadau sydd i ddod
calendar-add-notification-button =
    .label = Ychwanegu hysbysiad
calendar-import-new-calendar = Calendr Newydd…
    .title = Crëwch neu danysgrifio i galendr newydd
calendar-refresh-calendars =
    .title = Ail-lwytho pob calendr a chydweddu newidiadau
calendar-new-event-primary-button = Digwyddiad Newydd
calendar-new-task-primary-button = Tasg Newydd
calendar-nav-button-prev-tooltip-day =
    .title = Diwrnod Blaenorol
    .accesskey = B
calendar-nav-button-prev-tooltip-week =
    .title = Wythnos Flaenorol
    .accesskey = F
calendar-nav-button-prev-tooltip-multiweek =
    .title = Wythnos Flaenorol
    .accesskey = F
calendar-nav-button-prev-tooltip-month =
    .title = Mis Blaenorol
    .accesskey = B
calendar-nav-button-next-tooltip-day =
    .title = Diwrnod Nesaf
    .accesskey = N
calendar-nav-button-next-tooltip-week =
    .title = Wythnos Nesaf
    .accesskey = N
calendar-nav-button-next-tooltip-multiweek =
    .title = Wythnos Nesaf
    .accesskey = N
calendar-nav-button-next-tooltip-month =
    .title = Mis Nesaf
    .accesskey = N
calendar-today-button-tooltip =
    .title = Mynd i Heddiw
calendar-view-toggle-day = Diwrnod
    .title = Newid i golwg diwrnod
calendar-view-toggle-week = Wythnos
    .title = Newid i golwg wythnos
calendar-view-toggle-multiweek = Wythnosau
    .title = Newid i golwg wythnosol
calendar-view-toggle-month = Mis
    .title = Newid i golwg mis
