# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Dewis y cyfan
select-none-calendars = Dewis dim
calendar-creation-wizard-title = Creu Calendr Newydd
calendar-creation-initial-description = Mae modd gosod eich calendr ar eich cyfrifiadur neu ar weinydd fel bod modd i chi gael mynediad o bell neu ei rannu gyda'ch ffrindiau a'ch cydweithwyr.
calendar-creation-initial-computer =
    .label = Ar Fy Nghyfrifiadur
calendar-creation-initial-network =
    .label = Ar y Rhwydwaith
calendar-creation-username =
    .value = Enw Defnyddiwr:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Creu Calendr
    .buttonaccesskeyaccept = C
    .buttonlabelextra2 = Nôl
    .buttonaccesskeyextra2 = N
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Creu Calendr
    .buttonaccesskeyaccept = C
    .buttonlabelextra2 = Nôl
    .buttonaccesskeyextra2 = N
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Canfod Calendrau
    .buttonaccesskeyaccept = a
    .buttonlabelextra2 = Nôl
    .buttonaccesskeyextra2 = N
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Tanysgrifio
    .buttonaccesskeyaccept = T
    .buttonlabelextra2 = Nôl
    .buttonaccesskeyextra2 = N
calendar-creation-type =
    .value = Y Math o Galendr:
calendar-creation-location =
    .value = Lleoliad:
calendar-creation-location-placeholder =
    .placeholder = URL neu enw gwesteiwr gweinydd y calendr
    .default-placeholder = URL neu enw gwesteiwr gweinydd y calendr
calendar-creation-network-nocredentials =
    .label = Nid oes angen manylion y lleoliad hwn
calendar-creation-network-loading = Arhoswch tra bod eich calendrau yn cael eu darganfod.
calendar-creation-network-notfound = Heb ganfod calendrau yn y lleoliad hwn. Gwiriwch eich gosodiadau.
calendar-creation-network-authfail = Nid yw'r manylion rydych wedi'u cynnig wedi eu derbyn. Gwiriwch eich gosodiadau.
calendar-creation-network-certerror = Methu dod o hyd i galendrau yn y lleoliad hwn oherwydd problem tystysgrif.
calendar-creation-network-subscribe-single = Dewiswch y calendrau'r hoffech danysgrifio iddynt.
calendar-creation-network-subscribe-multiple = Mae mathau calendr lluosog ar gael; ar gyfer y lleoliad hwn. Dewiswch y math o galendr, yna mario'r calendrau yr hoffech chi danysgrifio iddyn nhw.
