# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Széthúzható hely
toolbar-write-message-label = Új üzenet
toolbar-write-message =
    .title = Új üzenet létrehozása
toolbar-unifinder-label = Események keresése
toolbar-unifinder =
    .title = Az események keresése ablaktábla be/ki
toolbar-folder-location-label = Mappa helye
toolbar-edit-event-label = Szerkesztés
toolbar-edit-event =
    .title = Kijelölt esemény vagy feladat szerkesztése
toolbar-get-messages-label = Üzenetek letöltése
toolbar-reply-label = Válasz
toolbar-reply =
    .title = Az üzenet megválaszolása
toolbar-reply-all-label = Válasz mindenkinek
toolbar-reply-all =
    .title = Válasz a feladónak és az összes címzettnek
toolbar-reply-to-list-label = Válasz a listára
toolbar-reply-to-list =
    .title = Válasz a levelezőlistára
toolbar-redirect-label = Átirányítás
toolbar-redirect =
    .title = Kiválasztott üzenet átirányítása
toolbar-archive-label = Archiválás
toolbar-archive =
    .title = Kijelölt üzenetek archiválása
toolbar-conversation-label = Beszélgetés
toolbar-conversation =
    .title = A kijelölt üzenet beszélgetésének megjelenítése
toolbar-previous-unread-label = Előző olvasatlan
toolbar-previous-unread =
    .title = Ugrás az előző olvasatlan üzenetre
toolbar-previous-label = Előző
toolbar-previous =
    .title = Ugrás az előző üzenetre
toolbar-next-unread-label = Következő olvasatlan
toolbar-next-unread =
    .title = Ugrás a következő olvasatlan üzenetre
toolbar-next-label = Következő
toolbar-next =
    .title = Ugrás a következő üzenetre
toolbar-junk-label = Levélszemét
toolbar-junk =
    .title = A kijelölt üzenetek megjelölése szemétként
toolbar-delete-label = Törlés
toolbar-delete =
    .title = Kijelölt üzenetek vagy mappa törlése
toolbar-compact-label = Tömörítés
toolbar-compact =
    .title = Törölt üzenetek eltávolítása a kijelölt mappából
toolbar-add-as-event-label = Felvétel eseményként
toolbar-add-as-event =
    .title = Naptár-információk kinyerése az üzenetből, és azok felvétele a naptárba eseményként
toolbar-add-as-task-label = Felvétel feladatként
toolbar-add-as-task =
    .title = Naptár-információk kinyerése az üzenetből, és azok felvétele a naptárba feladatként
toolbar-tag-message-label = Címke
toolbar-tag-message =
    .title = Üzenetek címkézése
toolbar-forward-inline-label = Továbbítás
toolbar-forward-inline =
    .title = A kijelölt üzenet továbbítása beágyazva
toolbar-forward-attachment-label = Továbbítás mellékletként
toolbar-forward-attachment =
    .title = A kijelölt üzenet továbbítása mellékletként
toolbar-mark-as-label = Megjelölés
toolbar-mark-as =
    .title = Az üzenet megjelölése
toolbar-address-book =
    .title = A címjegyzék megjelenítése
toolbar-chat-label = Csevegés
toolbar-chat =
    .title = A Csevegés lap megjelenítése
toolbar-calendar-label = Naptár
toolbar-calendar =
    .title = Átváltás a naptár lapra
toolbar-tasks-label = Feladatok
toolbar-tasks =
    .title = Átváltás a feladatok lapra
toolbar-print-label = Nyomtatás
toolbar-print =
    .title = Az üzenet kinyomtatása
