# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Széthúzható hely
search-bar-label = Keresés
toolbar-write-message-label = Új üzenet
toolbar-write-message =
    .title = Új üzenet létrehozása
toolbar-move-to-label = Áthelyezés
toolbar-move-to =
    .title = A kijelölt üzenet áthelyezése
toolbar-unifinder-label = Események keresése
toolbar-unifinder =
    .title = Az események keresése ablaktábla be/ki
toolbar-folder-location-label = Mappa helye
toolbar-folder-location =
    .title = Váltás mappára
toolbar-edit-event-label = Szerkesztés
toolbar-edit-event =
    .title = Kijelölt esemény vagy feladat szerkesztése
toolbar-get-messages-label = Üzenetek letöltése
toolbar-get-messages =
    .title = Új üzenetek lekérése az összes fiókhoz
toolbar-reply-label = Válasz
toolbar-reply =
    .title = Az üzenet megválaszolása
toolbar-reply-all-label = Válasz mindenkinek
toolbar-reply-all =
    .title = Válasz a feladónak és az összes címzettnek
toolbar-reply-to-list-label = Válasz a listára
toolbar-reply-to-list =
    .title = Válasz a levelezőlistára
toolbar-redirect-label = Átirányítás
toolbar-redirect =
    .title = Kiválasztott üzenet átirányítása
toolbar-archive-label = Archiválás
toolbar-archive =
    .title = Kijelölt üzenetek archiválása
toolbar-conversation-label = Beszélgetés
toolbar-conversation =
    .title = A kijelölt üzenet beszélgetésének megjelenítése
toolbar-previous-unread-label = Előző olvasatlan
toolbar-previous-unread =
    .title = Ugrás az előző olvasatlan üzenetre
toolbar-previous-label = Előző
toolbar-previous =
    .title = Ugrás az előző üzenetre
toolbar-next-unread-label = Következő olvasatlan
toolbar-next-unread =
    .title = Ugrás a következő olvasatlan üzenetre
toolbar-next-label = Következő
toolbar-next =
    .title = Ugrás a következő üzenetre
toolbar-junk-label = Levélszemét
toolbar-junk =
    .title = A kijelölt üzenetek megjelölése szemétként
toolbar-delete-label = Törlés
toolbar-delete-title =
    .title = A kijelölt üzenetek törlése
toolbar-undelete-label = Törlés visszavonása
toolbar-undelete =
    .title = A kijelölt üzenetek törlésének visszavonása
toolbar-compact-label = Tömörítés
toolbar-compact =
    .title = Törölt üzenetek eltávolítása a kijelölt mappából
toolbar-add-as-event-label = Felvétel eseményként
toolbar-add-as-event =
    .title = Naptár-információk kinyerése az üzenetből, és azok felvétele a naptárba eseményként
toolbar-add-as-task-label = Felvétel feladatként
toolbar-add-as-task =
    .title = Naptár-információk kinyerése az üzenetből, és azok felvétele a naptárba feladatként
toolbar-tag-message-label = Címke
toolbar-tag-message =
    .title = Üzenetek címkézése
toolbar-forward-inline-label = Továbbítás
toolbar-forward-inline =
    .title = A kijelölt üzenet továbbítása beágyazva
toolbar-forward-attachment-label = Továbbítás mellékletként
toolbar-forward-attachment =
    .title = A kijelölt üzenet továbbítása mellékletként
toolbar-mark-as-label = Megjelölés
toolbar-mark-as =
    .title = Az üzenet megjelölése
toolbar-view-picker-label = Nézet
toolbar-view-picker =
    .title = A jelenlegi mappa nézetének testreszabása
toolbar-address-book-label = Címjegyzék
toolbar-address-book =
    .title = A címjegyzék megjelenítése
toolbar-chat-label = Csevegés
toolbar-chat =
    .title = A Csevegés lap megjelenítése
toolbar-add-ons-and-themes-label = Kiegészítők és témák
toolbar-add-ons-and-themes =
    .title = Kiegészítők kezelése
toolbar-calendar-label = Naptár
toolbar-calendar =
    .title = Átváltás a naptár lapra
toolbar-tasks-label = Feladatok
toolbar-tasks =
    .title = Átváltás a feladatok lapra
toolbar-mail-label = Levelező
toolbar-mail =
    .title = Átváltás a levelezés lapra
toolbar-print-label = Nyomtatás
toolbar-print =
    .title = Az üzenet kinyomtatása
toolbar-quick-filter-bar-label = Gyorsszűrő
toolbar-quick-filter-bar =
    .title = Üzenetek szűrése
toolbar-synchronize-label = Szinkronizálás
toolbar-synchronize =
    .title = Naptárak újratöltése és módosítások szinkronizálása
toolbar-delete-event-label = Törlés
toolbar-delete-event =
    .title = Kijelölt események vagy feladatok törlése
toolbar-go-to-today-label = Ugrás a mai napra
toolbar-go-to-today =
    .title = Ugrás a mai napra
toolbar-print-event-label = Nyomtatás
toolbar-print-event =
    .title = Események vagy feladatok nyomtatása
toolbar-new-event-label = Esemény
toolbar-new-event =
    .title = Új elem létrehozása
toolbar-new-task-label = Feladat
toolbar-new-task =
    .title = Új feladat létrehozása
toolbar-go-back-label = Vissza
toolbar-go-back =
    .title = Ugrás egy üzenettel hátra
toolbar-go-forward-label = Előre
toolbar-go-forward =
    .title = Ugrás egy üzenettel előre
toolbar-stop-label = Leállítás
toolbar-stop =
    .title = Átvitel megszakítása
toolbar-throbber-label = Aktivitásjelző
toolbar-throbber =
    .title = Aktivitásjelző
toolbar-create-contact-label = Új névjegy
toolbar-create-contact =
    .title = Új névjegy létrehozása
toolbar-create-address-book-label = Új címjegyzék
toolbar-create-address-book =
    .title = Új címjegyzék létrehozása
toolbar-create-list-label = Új lista
toolbar-create-list =
    .title = Új levelezőlista létrehozása
toolbar-import-contacts-label = Importálás
toolbar-import-contacts =
    .title = Névjegyek importálása fájlból

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Helyi címjegyzék hozzáadása
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV-címjegyzék hozzáadása
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP-címjegyzék hozzáadása
