# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Strādāt nesaistē
desc = Tagad pārslēgties tiešsaistē?\n\n(Ja izvēlies darboties bezsaistē, pārslēgties tiešsaistē var vēlāk — izvēlnē `Datne' jāizvēlas `Bezsaiste', pēc tam jānoņem atzīme izvēles rūtiņā `Darboties bezsaistē'.)
workOnline = Strādāt nesaistē
workOffline = Strādāt nesaistē
