# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentarz
calendar-item-summary-title = Nazwa:
calendar-item-summary-calendar = Kalendarz:
calendar-item-summary-task-start = Początek:
calendar-item-summary-event-start = Początek:
calendar-item-summary-task-due = Koniec:
calendar-item-summary-event-end = Koniec:
calendar-item-summary-repeat = Powtarzaj:
calendar-item-summary-location = Miejsce:
calendar-item-summary-category = Kategoria:
calendar-item-summary-organizer = Organizator:
calendar-item-summary-status = Stan:
calendar-item-summary-reminder = Przypomnij:
calendar-item-summary-attachments = Załączniki:
calendar-item-summary-status-tentative = Wstępnie zaakceptowane
calendar-item-summary-status-confirmed = Potwierdzone
calendar-item-summary-event-status-cancelled = Odwołane
calendar-item-summary-todo-status-cancelled = Odwołane
calendar-item-summary-status-needs-action = Wymaga działania
calendar-item-summary-status-in-process = Trwa
calendar-item-summary-status-completed = Wykonane
calendar-item-summary-reminder-none =
    .label = Bez przypomnienia
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minut przed
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minut przed
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minut przed
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minut przed
calendar-item-summary-reminder-1-hour-before =
    .label = 1 godzinę przed
calendar-item-summary-reminder-2-hours-before =
    .label = 2 godziny przed
calendar-item-summary-reminder-12-hours-before =
    .label = 12 godzin przed
calendar-item-summary-reminder-1-day-before =
    .label = 1 dzień przed
calendar-item-summary-reminder-2-days-before =
    .label = 2 dni przed
calendar-item-summary-reminder-1-week-before =
    .label = 1 tydzień przed
calendar-item-summary-reminder-custom =
    .label = Ustaw…
calendar-item-summary-reminder-multiple =
    .value = Przypomnienia wielokrotne…
calendar-item-summary-general =
    .value = Główne
calendar-item-summary-attendees =
    .value = Uczestnicy
calendar-item-summary-description =
    .value = Opis
calendar-item-summary-link =
    .value = Powiązany odnośnik
