# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = 靈活空間
search-bar-label = 搜尋
toolbar-write-message-label = 寫信
toolbar-write-message =
    .title = 建立新郵件
toolbar-move-to-label = 移動到
toolbar-move-to =
    .title = 移動所選的訊息
toolbar-unifinder-label = 尋找事件
toolbar-unifinder =
    .title = 切換尋找事件窗格
toolbar-folder-location-label = 資料夾位置
toolbar-folder-location =
    .title = 切換到信件匣
toolbar-edit-event-label = 編輯
toolbar-edit-event =
    .title = 編輯選擇的事件或工作
toolbar-get-messages-label = 下載郵件
toolbar-get-messages =
    .title = 取回所有帳號的新訊息
toolbar-reply-label = 回覆
toolbar-reply =
    .title = 回覆此信
toolbar-reply-all-label = 回覆全部
toolbar-reply-all =
    .title = 回信給寄件者及所有收件者
toolbar-reply-to-list-label = 回覆給清單
toolbar-reply-to-list =
    .title = 回覆到郵件群組
toolbar-redirect-label = 重導
toolbar-redirect =
    .title = 將選擇的訊息重新導向
toolbar-archive-label = 備存
toolbar-archive =
    .title = 將選取的郵件備存
toolbar-conversation-label = 討論串
toolbar-conversation =
    .title = 顯示所選訊息當中的對話內容
toolbar-previous-unread-label = 上一封未讀
toolbar-previous-unread =
    .title = 移至上一封未讀郵件
toolbar-previous-label = 上一封
toolbar-previous =
    .title = 移動至上一封訊息
toolbar-next-unread-label = 下一封未讀
toolbar-next-unread =
    .title = 移至下一封未讀郵件
toolbar-next-label = 下一封
toolbar-next =
    .title = 移動至下一封訊息
toolbar-junk-label = 是垃圾郵件
toolbar-junk =
    .title = 標示所選訊息為垃圾信
toolbar-delete-label = 刪除
toolbar-delete-title =
    .title = 刪除選擇的郵件
toolbar-undelete-label = 反刪除
toolbar-undelete =
    .title = 還原選擇的訊息
toolbar-compact-label = 壓實重整
toolbar-compact =
    .title = 從指定資料夾移除已刪郵件
toolbar-add-as-event-label = 新增為事件
toolbar-add-as-event =
    .title = 從訊息中找出行事曆資訊，並新增為您的行事曆事件
toolbar-add-as-task-label = 新增為工作
toolbar-add-as-task =
    .title = 從訊息中找出行事曆資訊，並新增為您的行事曆工作
toolbar-tag-message-label = 標籤
toolbar-tag-message =
    .title = 將郵件加上標籤
toolbar-forward-inline-label = 轉寄
toolbar-forward-inline =
    .title = 將所選的文字作為行內文字轉寄
toolbar-forward-attachment-label = 以附件轉寄
toolbar-forward-attachment =
    .title = 將所選的訊息作為附件轉寄
toolbar-mark-as-label = 標記
toolbar-mark-as =
    .title = 標示訊息
toolbar-view-picker-label = 檢視
toolbar-view-picker =
    .title = 自訂目前信件匣的顯示方式
toolbar-address-book-label = 通訊錄
toolbar-address-book =
    .title = 前往通訊錄
toolbar-chat-label = 聊天
toolbar-chat =
    .title = 顯示聊天分頁
toolbar-add-ons-and-themes-label = 附加元件與佈景主題
toolbar-add-ons-and-themes =
    .title = 管理您的附加元件
toolbar-calendar-label = 行事曆
toolbar-calendar =
    .title = 切換到行事曆分頁
toolbar-tasks-label = 工作
toolbar-tasks =
    .title = 切換到工作分頁
toolbar-mail-label = 郵件
toolbar-mail =
    .title = 切換到郵件分頁
toolbar-print-label = 列印
toolbar-print =
    .title = 列印此訊息
toolbar-quick-filter-bar-label = 快速篩選
toolbar-quick-filter-bar =
    .title = 篩選訊息
toolbar-synchronize-label = 同步
toolbar-synchronize =
    .title = 重新載入行事曆並同步變更
toolbar-delete-event-label = 刪除
toolbar-delete-event =
    .title = 刪除選擇的事件或工作
toolbar-go-to-today-label = 前往今日
toolbar-go-to-today =
    .title = 前往今日
toolbar-print-event-label = 列印
toolbar-print-event =
    .title = 列印事件或工作
toolbar-new-event-label = 事件
toolbar-new-event =
    .title = 建立新事件
toolbar-new-task-label = 工作
toolbar-new-task =
    .title = 建立新工作
toolbar-go-back-label = 上一頁
toolbar-go-back =
    .title = 上一封郵件
toolbar-go-forward-label = 下一頁
toolbar-go-forward =
    .title = 下一封郵件
toolbar-stop-label = 停止
toolbar-stop =
    .title = 停止傳送
toolbar-throbber-label = 進度指示器
toolbar-throbber =
    .title = 進度指示器
toolbar-create-contact-label = 新增聯絡人
toolbar-create-contact =
    .title = 建立新聯絡人
toolbar-create-address-book-label = 新增通訊錄
toolbar-create-address-book =
    .title = 建立新通訊錄
toolbar-create-list-label = 新增群組名單
toolbar-create-list =
    .title = 建立新郵件群組
toolbar-import-contacts-label = 匯入
toolbar-import-contacts =
    .title = 從檔案匯入聯絡人

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = 新增本機通訊錄
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = 新增 CardDAV 通訊錄
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = 新增 LDAP 通訊錄
