# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Nama tampilan
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tipe
vcard-entry-type-home = Rumah
vcard-entry-type-work = Kantor
vcard-entry-type-none = Nihil
vcard-entry-type-custom = Ubahan
vcard-name-header = Nama
vcard-n-prefix = Prefiks
vcard-n-add-prefix =
    .title = Tambahkan prefiks
vcard-n-firstname = Nama depan
vcard-n-add-firstname =
    .title = Tambahkan nama depan
vcard-n-middlename = Nama tengah
vcard-n-add-middlename =
    .title = Tambahkan nama tengah
vcard-n-lastname = Nama keluarga
vcard-n-add-lastname =
    .title = Tambahkan nama keluarga
vcard-n-suffix = Sufiks
vcard-n-add-suffix =
    .title = Tambahkan akhiran
vcard-nickname = Nama panggilan
vcard-email-header = Alamat Surel
vcard-email-add = Tambahkan alamat surel
vcard-email-label = Alamat surel
vcard-primary-email-label = Baku
vcard-url-header = Situs Web
vcard-url-add = Tambahkan situs web
vcard-url-label = Situs web
vcard-tel-header = Nomor Telepon
vcard-tel-add = Tambahkan nomor telepon
vcard-tel-label = Nomor telepon
# Or "Mobile"
vcard-entry-type-cell = Seluler
vcard-entry-type-fax = Faks
vcard-entry-type-pager = Penyeranta
vcard-tz-header = Zona Waktu
vcard-tz-add = Tambahkan zona waktu
vcard-impp2-header = Pesan Instan
vcard-impp-add = Tambahkan akun obrolan
vcard-impp-label = Akun obrolan
vcard-impp-select = Protokol
vcard-impp-option-other = Lainnya
vcard-impp-input-label = URI
vcard-impp-input-title = URI untuk pesan instan
vcard-bday-anniversary-header = Tanggal Spesial
vcard-bday-anniversary-add = Tambahkan tanggal spesial
vcard-bday-label = Tanggal Lahir
vcard-anniversary-label = Hari Jadi
vcard-date-day = Tanggal
vcard-date-month = Bulan
vcard-date-year = Tahun
vcard-adr-header = Alamat
vcard-adr-add = Tambahkan alamat
vcard-adr-label = Alamat
vcard-adr-delivery-label = Label pengiriman
vcard-adr-street = Jalan
# Or "Locality"
vcard-adr-locality = Kota
# Or "Region"
vcard-adr-region = Negara Bagian/Provinsi
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Kode Pos:
vcard-adr-country = Negara
vcard-note-header = Catatan
vcard-note-add = Tambah catatan
vcard-org-header = Properti Organisasi
vcard-org-add = Tambahkan properti organisasi
vcard-org-title = Judul
vcard-org-title-input =
    .placeholder = Jabatan
    .title = Posisi atau pekerjaan
vcard-org-role = Peran
vcard-org-role-input =
    .placeholder = Peran dalam suatu proyek
    .title = Fungsi atau bagian yang dimainkan dalam situasi tertentu
vcard-org-org = Organisasi
vcard-org-org-input =
    .placeholder = Nama perusahaan
    .title = Nama organisasi
vcard-org-org-unit = Departemen
vcard-org-org-unit-input =
    .placeholder = Departmen
    .title = Nama unit organisasi
vcard-custom-header = Properti Ubahan
vcard-custom-add = Tambahkan properti ubahan
vcard-remove-button-title =
    .title = Singkirkan
vcard-remove-button = Singkirkan
