# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = 오프라인 설정
autodetect-connection-label =
    .label = 인터넷에 연결되면 자동으로 모드 전환
    .accesskey = d
status-radio-last-used =
    .label = 마지막으로 사용한 접속 모드 사용
    .accesskey = U
status-radio-ask-connect =
    .label = 온라인으로 연결할지 묻기
    .accesskey = k
status-radio-start-online =
    .label = 온라인으로 시작
    .accesskey = l
status-radio-start-offline =
    .label = 오프라인으로 시작
    .accesskey = f
going-online-send =
    .label = 예, 자동으로 전송합니다.
    .accesskey = Y
going-online-keep =
    .label = 아니오, 보낼 편지함에 보관
    .accesskey = N
going-online-ask-send =
    .label = 보내기 전에 묻기
    .accesskey = s
going-offline-download =
    .label = 예, 자동으로 다운로드합니다.
    .accesskey = e
going-offline-keep =
    .label = 아니요, 다운로드하지 않습니다.
    .accesskey = o
going-offline-ask-download =
    .label = 다운로드하기 전에 확인
    .accesskey = a
autodetect-online-label =
    .label = 자동으로 온라인 상태 탐지
    .accesskey = d
offline-preference-startup-label = 시작할 때 수동 상태:
status-radio-remember =
    .label = 이전의 온라인 상태 기억하기
    .accesskey = R
status-radio-ask =
    .label = 시작할 온라인 상태 묻기
    .accesskey = k
status-radio-always-online =
    .label = 시작할 때 항상 온라인
    .accesskey = l
status-radio-always-offline =
    .label = 시작할 때 항상 오프라인
    .accesskey = f
going-online-label = 온라인으로 전환 시에 보내지 않은 메시지를 보내겠습니까?
going-online-auto =
    .label = 예
    .accesskey = Y
going-online-not =
    .label = 아니오
    .accesskey = N
going-online-ask =
    .label = 물어 보기
    .accesskey = s
going-offline-label = 오프라인 전환 시에 오프라인 사용을 위하여 메시지들을 받으시겠습니까?
going-offline-auto =
    .label = 예
    .accesskey = e
going-offline-not =
    .label = 아니오
    .accesskey = o
going-offline-ask =
    .label = 물어 보기
    .accesskey = a
