# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentar
calendar-item-summary-title = Titul:
calendar-item-summary-calendar = Protyka:
calendar-item-summary-task-start = Spočatny datum:
calendar-item-summary-event-start = Spočatny datum:
calendar-item-summary-task-due = Termin:
calendar-item-summary-event-end = Kónčny datum:
calendar-item-summary-repeat = Wospjetować:
calendar-item-summary-location = Městno:
calendar-item-summary-category = Kategorija:
calendar-item-summary-organizer = Organizator:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Dopomnjeće:
calendar-item-summary-attachments = Přiwěški:
calendar-item-summary-status-tentative = Nachwilu
calendar-item-summary-status-confirmed = Wobkrućeny
calendar-item-summary-event-status-cancelled = Přetorhnjeny
calendar-item-summary-todo-status-cancelled = Přetorhnjeny
calendar-item-summary-status-needs-action = Trjeba akciju
calendar-item-summary-status-in-process = Běži
calendar-item-summary-status-completed = Skónčeny
calendar-item-summary-reminder-none =
    .label = Żane dopomnjeće
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 mjeńšin do toho
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 mjeńšin do toho
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 mjeńšin do toho
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 mjeńšin do toho
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hodźinu do toho
calendar-item-summary-reminder-2-hours-before =
    .label = 2 hodźinje do toho
calendar-item-summary-reminder-12-hours-before =
    .label = 12 hodźin do toho
calendar-item-summary-reminder-1-day-before =
    .label = 1 dźeń do toho
calendar-item-summary-reminder-2-days-before =
    .label = 2 dnjej do toho
calendar-item-summary-reminder-1-week-before =
    .label = 1 tydźeń do toho
calendar-item-summary-reminder-custom =
    .label = Swójske…
calendar-item-summary-reminder-multiple =
    .value = Wjacore dopomnjeća…
calendar-item-summary-general =
    .value = Powšitkowny
calendar-item-summary-attendees =
    .value = Wobdźělnicy
calendar-item-summary-description =
    .value = Wopisanje
calendar-item-summary-link =
    .value = Přiwuzny wotkaz
