# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Wšě wubrać
select-none-calendars = Žadyn njewubrać
calendar-creation-wizard-title = Nowu protyku wutworić
calendar-creation-initial-description = Waša protyka da so na wašim ličaku abo na serwerje składować, zo by na nju zdaloka přistup měł abo ju z wašimi přećelemi abo sobudźěłaćerjemi dźělił.
calendar-creation-initial-computer =
    .label = Na mojim ličaku
calendar-creation-initial-network =
    .label = W syći
calendar-creation-username =
    .value = Wužiwarske mjeno:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Protyku wutworić
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Wróćo
    .buttonaccesskeyextra2 = W
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Protyku wutworić
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Wróćo
    .buttonaccesskeyextra2 = W
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Protyki pytać
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Wróćo
    .buttonaccesskeyextra2 = W
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonować
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Wróćo
    .buttonaccesskeyextra2 = W
calendar-creation-type =
    .value = Protykowy typ:
calendar-creation-location =
    .value = Městno:
calendar-creation-location-placeholder =
    .placeholder = URL abo mjeno hosta protykoweho serwera
    .default-placeholder = URL abo mjeno hosta protykoweho serwera
calendar-creation-network-nocredentials =
    .label = Tute městno přizjewjenske daty njetrjeba
calendar-creation-network-loading = Prošu čakajće, doniž waše protyki namakane njejsu.
calendar-creation-network-notfound = Protyki njedachu so na tutym městnje namakać. Prošu přepruwujće swoje nastajenja.
calendar-creation-network-authfail = Přizjewjenske daty, kotrež sće zapodał, njebuchu akceptowane. Prošu přepruwujće swoje nastajenja.
calendar-creation-network-certerror = Problema z certifikatom dla njedachu so protyki na tutym městnje namakać.
calendar-creation-network-subscribe-single = Prošu wubjerće protyki, kotrež byšće rady abonował.
calendar-creation-network-subscribe-multiple = Za tute městno su wjacore protykowe typy k dispoziciji. Prošu wubjerće protykowy typ a markěrujće potom protyki, kotrež chceće abonować.
