# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Cài đặt thư rác
dialog-header-title =
    .value = Cài đặt thư rác
training-description-spam = Nếu được bật, trước tiên bạn phải đào tạo { -brand-short-name } để nhận dạng thư rác bằng cách sử dụng nút thanh công cụ Thư rác để đánh dấu thư là thư rác hay không. Bạn cần xác định cả thư rác và thư không phải thư rác. Sau đó, { -brand-short-name } sẽ có thể tự động đánh dấu thư rác.
spam-level-checkbox =
    .label = Bật chế độ kiểm soát thư rác thích ứng cho tài khoản này
    .accesskey = E
move-spam-message-menuitem =
    .label = Chuyển thư rác mới vào:
    .accesskey = M
set-spam-folder-menuitem =
    .label = Thư mục “Spam” hoặc “Thư rác” trên:
    .accesskey = S
move-message-other =
    .label = Khác:
    .accesskey = O
automatic-spam-purge-checkbox =
    .label = Tự động xóa thư rác sau
    .accesskey = u
automatic-spam-purge-label =
    .value = ngày
trust-addresses-header-label =
    .value = Tin tưởng các địa chỉ email trong những sổ địa chỉ này:
    .accesskey = D
allowlist-header-label =
    .value = Không tự động đánh dấu thư là rác nếu người gửi ở trong:
    .accesskey = D
isp-headers-checkbox =
    .label = Header thư rác đáng tin cậy được thiết lập bởi:
    .accesskey = T
isp-warning-description = Nếu được bật, { -brand-short-name } sẽ tự động coi các thư được bộ phân loại bên ngoài này đánh dấu là thư rác.
spam-detecting-legend = Đang phát hiện thư rác
spam-storage-deletion-legend = Lưu trữ và xoá
spam-classification-legend = Phần được chọn
spam-actions-legend = Đích đến và thời gian lưu trữ
global-spam-preferences-button =
    .label = Cài đặt chung thư rác…
    .accesskey = G
manage-spam-title = Quản lý thư rác
manage-spam-header =
    .value = Quản lý thư rác
training-description-learns = Khi được bật, { -brand-short-name } sẽ học hỏi từ những thư bạn đánh dấu là thư rác hoặc không phải thư rác. Bạn càng huấn luyện nó nhiều, { -brand-short-name } càng giỏi hơn trong việc phát hiện thư rác.
spam-auto-detection-checkbox =
    .label = Bật tính năng tự động phát hiện thư rác cho tài khoản này
    .accesskey = E
