# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Xác nhận đã nhận thư
return-receipt-checkbox-control =
    .label = Khi gửi thư, luôn luôn yêu cầu xác nhận đã nhận thư
    .accesskey = W
receipt-arrive-label = Khi một chứng nhận đến:
receipt-leave-inbox-control =
    .label = Để lại trong Hộp thư đến
    .accesskey = i
receipt-move-sent-control =
    .label = Chuyển sang thư mục Đã gửi
    .accesskey = m
receipt-sender-request-label = Khi người gửi yêu cầu xác nhận đã nhận thư:
receipt-leave-radio-control =
    .label = Để nó trong hộp thư đến của tôi
    .accesskey = i
receipt-move-radio-control =
    .label = Chuyển nó vào thư mục “Đã gửi” của tôi
    .accesskey = m
receipt-request-label = Khi tôi nhận được một yêu cầu xác nhận đã nhận thư:
receipt-return-never-radio-control =
    .label = Không bao giờ gửi xác nhận đã nhận thư
    .accesskey = n
receipt-return-some-radio-control =
    .label = Cho phép xác nhận đã nhận thư cho một số thư
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Nếu không được liệt kê trong mục Người nhận hoặc CC:
    .accesskey = f
receipt-not-to-cc-label =
    .value = Nếu tôi không ở mục Tới hoặc Cc của thư:
    .accesskey = f
receipt-send-never-label =
    .label = Không bao giờ gửi
receipt-send-always-label =
    .label = Luôn luôn gửi
receipt-send-ask-label =
    .label = Hỏi tôi
sender-outside-company-label =
    .value = Nếu người gửi không thuộc công ty hoặc domain:
    .accesskey = t
sender-outside-domain-label =
    .value = Nếu người gửi nằm ngoài tên miền của tôi:
    .accesskey = t
other-cases-text-label =
    .value = Trong mọi trường hợp khác:
    .accesskey = a
read-receipts-dialog-title = Xác nhận đã đọc
return-receipt-request-control =
    .label = Luôn yêu cầu xác nhận đã nhận thư khi gửi email
    .accesskey = W
