# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Претрага у току…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 подударање је нађено;#1 подударања је нађено
noMatchesFound = Нема подударања
labelForStopButton = Заустави
labelForSearchButton = Претражи
labelForStopButton.accesskey = З
labelForSearchButton.accesskey = П
moreButtonTooltipText = Додај ново правило
lessButtonTooltipText = Уклони ово правило
