# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = 離線模式設定
autodetect-connection-label =
    .label = 連上網路時自動切換模式
    .accesskey = d
offline-startup-label = 開啟 { -brand-short-name } 時：
status-radio-last-used =
    .label = 使用上次使用的連線模式
    .accesskey = U
status-radio-ask-connect =
    .label = 詢問要不要連線
    .accesskey = k
status-radio-start-online =
    .label = 以連線模式啟動
    .accesskey = l
status-radio-start-offline =
    .label = 以離線模式啟動
    .accesskey = f
going-online-prompt = 寄出「寄件匣」中等待寄出的郵件
going-online-send =
    .label = 是的，自動傳送
    .accesskey = Y
going-online-keep =
    .label = 不要，保留在「寄件匣」
    .accesskey = N
going-online-ask-send =
    .label = 傳送前先問我
    .accesskey = s
going-offline-prompt = 您想要下載郵件，於離線時閱讀嗎？
going-offline-download =
    .label = 是的，自動下載
    .accesskey = e
going-offline-keep =
    .label = 不要，不要下載
    .accesskey = o
going-offline-ask-download =
    .label = 下載前先問我
    .accesskey = a
autodetect-online-label =
    .label = 自動使用偵測到的連線狀態
    .accesskey = d
offline-preference-startup-label = 啟動時手動指定狀態：
status-radio-remember =
    .label = 記住之前的連線狀態
    .accesskey = R
status-radio-ask =
    .label = 詢問我的連線狀態
    .accesskey = k
status-radio-always-online =
    .label = 啟動時總是使用連線模式
    .accesskey = l
status-radio-always-offline =
    .label = 離線
    .accesskey = f
going-online-label = 當切換到連線模式時寄出未寄郵件？
going-online-auto =
    .label = 是
    .accesskey = Y
going-online-not =
    .label = 不使用
    .accesskey = N
going-online-ask =
    .label = 詢問我
    .accesskey = s
going-offline-label = 當切換到離線模式時自動下載郵件以供離線閱讀？
going-offline-auto =
    .label = 是
    .accesskey = e
going-offline-not =
    .label = 不使用
    .accesskey = o
going-offline-ask =
    .label = 詢問我
    .accesskey = A
