# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = 收件回執
return-receipt-checkbox-control =
    .label = 寄送郵件時一律要求收件回執
    .accesskey = W
receipt-arrive-label = 收到回執時：
receipt-leave-inbox-control =
    .label = 保留在收件匣
    .accesskey = i
receipt-move-sent-control =
    .label = 移動到寄件備份匣
    .accesskey = m
receipt-sender-request-label = 當寄件者要求回執時:
receipt-leave-radio-control =
    .label = 留在「收件匣」中
    .accesskey = i
receipt-move-radio-control =
    .label = 移到「寄件備份」匣
    .accesskey = m
receipt-request-label = 收到要求收件回執的郵件時：
receipt-return-never-radio-control =
    .label = 一律不寄出回執
    .accesskey = n
receipt-return-some-radio-control =
    .label = 依下列設定決定是否寄出回執
    .accesskey = r
receipt-not-listed-cc-label =
    .value = 若未列於「收件者」或「副本」欄位：
    .accesskey = f
receipt-not-to-cc-label =
    .value = 如果我不是郵件的收件者或副本收件者：
    .accesskey = r
receipt-send-never-label =
    .label = 不要寄出
receipt-send-always-label =
    .label = 一律寄出
receipt-send-ask-label =
    .label = 詢問我
sender-outside-company-label =
    .value = 若寄件者不是外部公司或網域:
    .accesskey = 若
sender-outside-domain-label =
    .value = 如果寄件者在我的網域以外：
    .accesskey = t
other-cases-text-label =
    .value = 其它情形：
    .accesskey = a
read-receipts-dialog-title = 已讀回執
return-receipt-request-control =
    .label = 寄送郵件時一定要要求回執
    .accesskey = 寄
