# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibelt mellemrum
search-bar-label = Søg
toolbar-write-message-label = Skriv
toolbar-write-message =
    .title = Skriv en ny meddelelse
toolbar-move-to-label = Flyt til
toolbar-move-to =
    .title = Flyt valgte meddelelser
toolbar-unifinder-label = Find begivenheder
toolbar-unifinder =
    .title = Slå søg i begivenheder til eller fra
toolbar-folder-location-label = Mappeplacering
toolbar-folder-location =
    .title = Skift til mappe
toolbar-edit-event-label = Rediger
toolbar-edit-event =
    .title = Rediger den valgte begivenhed eller opgaver
toolbar-get-messages-label = Hent meddelelser
toolbar-get-messages =
    .title = Hent nye meddelelser fra alle konti
toolbar-reply-label = Svar
toolbar-reply =
    .title = Svar på meddelelsen
toolbar-reply-all-label = Svar til alle
toolbar-reply-all =
    .title = Svar til afsenderen og alle modtagerne
toolbar-reply-to-list-label = Svar til liste
toolbar-reply-to-list =
    .title = Svar til mailingliste
toolbar-redirect-label = Omdiriger
toolbar-redirect =
    .title = Omdiriger valgte meddelelse
toolbar-archive-label = Arkiver
toolbar-archive =
    .title = Arkiver valgte meddelelser
toolbar-conversation-label = Samtale
toolbar-conversation =
    .title = Vis den valgte meddelelses samtale
toolbar-previous-unread-label = Forrige ulæste
toolbar-previous-unread =
    .title = Gå til forrige ulæste meddelelse
toolbar-previous-label = Forrige
toolbar-previous =
    .title = Gå til den forrige meddelelse
toolbar-next-unread-label = Næste ulæste
toolbar-next-unread =
    .title = Gå til næste ulæste meddelelse
toolbar-next-label = Næste
toolbar-next =
    .title = Gå til den næste meddelelse
toolbar-junk-label = Spam
toolbar-junk =
    .title = Marker den valgte meddelelse som spam
toolbar-delete-label = Slet
toolbar-delete-title =
    .title = Slet de valgte meddelelser
toolbar-undelete-label = Fortryd sletning
toolbar-undelete =
    .title = Fortryd sletning af de valgte meddelelser
toolbar-compact-label = Optimer
toolbar-compact =
    .title = Fjern slettede meddelelser fra valgte mappe
toolbar-add-as-event-label = Tilføj som begivenhed
toolbar-add-as-event =
    .title = Hent kalenderdata fra en meddelelse, og føj den til din kalender som en begivenhed
toolbar-add-as-task-label = Tilføj som opgave
toolbar-add-as-task =
    .title = Hent kalenderdata fra en meddelelse, og føj den til din kalender som en opgave
toolbar-tag-message-label = Mærkat
toolbar-tag-message =
    .title = Marker meddelelser
toolbar-forward-inline-label = Videresend
toolbar-forward-inline =
    .title = Videresend den valgte meddelelse som en del af selve meddelelsen
toolbar-forward-attachment-label = Videresend som vedhæftet fil
toolbar-forward-attachment =
    .title = Videresend den valgte meddelelse som en vedhæftet fil
toolbar-mark-as-label = Marker
toolbar-mark-as =
    .title = Marker meddelelser
toolbar-view-picker-label = Vis
toolbar-view-picker =
    .title = Tilpas udseendet på denne mappe
toolbar-address-book-label = Adressebog
toolbar-address-book =
    .title = Gå til adressebogen
toolbar-chat-label = Chat
toolbar-chat =
    .title = Vis fanebladet Chat
toolbar-add-ons-and-themes-label = Tilføjelser og temaer
toolbar-add-ons-and-themes =
    .title = Håndter dine tilføjelser
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Skift til fanebladet Kalender
toolbar-tasks-label = Opgaver
toolbar-tasks =
    .title = Skift til fanebladet Opgaver
toolbar-mail-label = Mail
toolbar-mail =
    .title = Skift til mail-fanebladet
toolbar-print-label = Udskriv
toolbar-print =
    .title = Udskriv denne meddelelse
toolbar-quick-filter-bar-label = Lynfilter
toolbar-quick-filter-bar =
    .title = Filtrer meddelelser
toolbar-synchronize-label = Synkroniser
toolbar-synchronize =
    .title = Genindlæs kalendere og synkroniser ændringer
toolbar-delete-event-label = Slet
toolbar-delete-event =
    .title = Slet de valgte begivenheder eller opgaver
toolbar-go-to-today-label = Gå til i dag
toolbar-go-to-today =
    .title = Gå til i dag
toolbar-print-event-label = Udskriv
toolbar-print-event =
    .title = Udskriv begivenheder eller opgaver
toolbar-new-event-label = Begivenhed
toolbar-new-event =
    .title = Opret en ny begivenhed
toolbar-new-task-label = Opgave
toolbar-new-task =
    .title = Opret en ny opgave
toolbar-go-back-label = Tilbage
toolbar-go-back =
    .title = Gå en meddelelse tilbage
toolbar-go-forward-label = Fremad
toolbar-go-forward =
    .title = Gå en meddelelse fremad
toolbar-stop-label = Stop
toolbar-stop =
    .title = Stop den aktuelle overførsel
toolbar-throbber-label = Aktivitetsindikator
toolbar-throbber =
    .title = Aktivitetsindikator
toolbar-create-contact-label = Ny kontakt
toolbar-create-contact =
    .title = Opret ny kontakt
toolbar-create-address-book-label = Ny adressebog
toolbar-create-address-book =
    .title = Opret ny adressebog
toolbar-create-list-label = Ny mailingliste
toolbar-create-list =
    .title = Opret ny mailingliste
toolbar-import-contacts-label = Importer
toolbar-import-contacts =
    .title = Importer kontakter fra en fil

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Tilføj lokal adressebog
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Tilføj CardDAV-adressebog
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Tilføj LDAP-adressebog
