# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Á Chuardach…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 toradh;#1 thoradh;#1 thoradh;#1 dtoradh;#1 toradh
noMatchesFound = Níor aimsíodh aon rud
labelForStopButton = Stad
labelForSearchButton = Cuardaigh
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = S
moreButtonTooltipText = Cuir riail nua leis
lessButtonTooltipText = Bain an riail seo
