# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Spazio flessibile
toolbar-write-message-label = Scrivi
toolbar-write-message =
    .title = Crea un nuovo messaggio
toolbar-unifinder-label = Trova eventi
toolbar-unifinder =
    .title = Attiva/disattiva il pannello Trova eventi
toolbar-folder-location-label = Posizione cartella
toolbar-edit-event-label = Modifica
toolbar-edit-event =
    .title = Modifica gli eventi o le attività selezionati
toolbar-get-messages-label = Scarica messaggi
toolbar-reply-label = Rispondi
toolbar-reply =
    .title = Rispondi al messaggio
toolbar-reply-all-label = Rispondi a tutti
toolbar-reply-all =
    .title = Rispondi al mittente e a tutti i destinatari
toolbar-reply-to-list-label = Rispondi alla lista
toolbar-reply-to-list =
    .title = Rispondi alla lista di distribuzione
toolbar-redirect-label = Reindirizza
toolbar-redirect =
    .title = Reindirizza il messaggio selezionato
toolbar-archive-label = Archivia
toolbar-archive =
    .title = Archivia i messaggi selezionati
toolbar-conversation-label = Conversazione
toolbar-conversation =
    .title = Mostra conversazione di questo messaggio
toolbar-previous-unread-label = Precedente non letto
toolbar-previous-unread =
    .title = Vai al precedente messaggio non letto
toolbar-previous-label = Precedente
toolbar-previous =
    .title = Vai al messaggio precedente
toolbar-next-unread-label = Successivo non letto
toolbar-next-unread =
    .title = Vai al messaggio successivo non letto
toolbar-next-label = Successivo
toolbar-next =
    .title = Passa al messaggio successivo
toolbar-junk-label = Indesiderata
toolbar-junk =
    .title = Segna i messaggi selezionati come posta indesiderata
toolbar-delete-label = Elimina
toolbar-delete =
    .title = Elimina i messaggi o la cartella selezionata
toolbar-compact-label = Compatta
toolbar-compact =
    .title = Compatta le cartelle
toolbar-add-as-event-label = Aggiungi come evento
toolbar-add-as-event =
    .title = Estrai le informazioni del calendario dal messaggio e aggiungile al calendario personale come evento
toolbar-add-as-task-label = Aggiungi come attività
toolbar-add-as-task =
    .title = Estrai le informazioni del calendario dal messaggio e aggiungile al calendario personale come attività
toolbar-tag-message-label = Etichetta
toolbar-tag-message =
    .title = Applica un’etichetta ai messaggi
toolbar-forward-inline-label = Inoltra
toolbar-forward-inline =
    .title = Inoltra i messaggi selezionati nel corpo del messaggio
toolbar-forward-attachment-label = Inoltra come allegato
toolbar-forward-attachment =
    .title = Inoltra i messaggi selezionati come allegato
toolbar-mark-as-label = Segna
toolbar-mark-as =
    .title = Segna i messaggi
toolbar-address-book =
    .title = Apri la rubrica
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mostra scheda della chat
toolbar-add-ons-and-themes-label = Componenti aggiuntivi e temi
toolbar-add-ons-and-themes =
    .title = Gestisci i tuoi componenti aggiuntivi
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Passa alla scheda del calendario
toolbar-tasks-label = Attività
toolbar-tasks =
    .title = Passa alla scheda delle attività
toolbar-print-label = Stampa
toolbar-print =
    .title = Stampa questo messaggio
toolbar-quick-filter-bar-label = Filtro veloce
toolbar-quick-filter-bar =
    .title = Filtra messaggi
