# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Variables:
# $count (Number) - Number of headers.
# $newsgroup (String) - The name of the newsgroup.
new-newsgroup-headers =
    { $count ->
        [zero] Yn llwytho i lawr { $count } penynnau { $newsgroup }…
        [one] Yn llwytho i lawr { $count } pennyn { $newsgroup }…
        [two] Yn llwytho i lawr { $count } bennyn  { $newsgroup }…
        [few] Yn llwytho i lawr { $count } pennyn { $newsgroup }…
        [many] Yn llwytho i lawr { $count } phennyn { $newsgroup }…
       *[other] Yn llwytho i lawr { $count } pennyn { $newsgroup }…
    }
# Variables:
# $newsgroup (String) - The name of the newsgroup.
no-new-messages = Does dim negeseuon newydd yn { $newsgroup }.
# Variables:
# $count (Number) - Number of articles.
# $newsgroup (String) - The name of the newsgroup.
downloading-articles-for-offline =
    { $count ->
        [zero] Yn llwytho i lawr { $count } erthyglau { $newsgroup }…
        [one] Yn llwytho i lawr { $count } erthygl { $newsgroup }…
        [two] Yn llwytho i lawr { $count } erthygl { $newsgroup }…
        [few] Yn llwytho i lawr { $count } erthygl { $newsgroup }…
        [many] Yn llwytho i lawr { $count } erthygl { $newsgroup }…
       *[other] Yn llwytho i lawr { $count } erthygl { $newsgroup }…
    }
# Variables:
# $newsgroup (String) - The name of the newsgroup.
no-articles-to-download = Does dim erthyglau gan { $newsgroup } i'w llwytho i lawr.
# Variables:
# $newsgroup (String) - The name of the newsgroup.
no-such-newsgroup = Nid yw'r grŵp newyddion { $newsgroup } ar gael ar y gweinydd.
