# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Bwlch Hyblyg
search-bar-label = Chwilio
toolbar-write-message-label = Ysgrifennu
toolbar-write-message =
    .title = Creu neges newydd
toolbar-move-to-label = Symud i
toolbar-move-to =
    .title = Symud y neges a ddewiswyd
toolbar-unifinder-label = Canfod Digwyddiadau
toolbar-unifinder =
    .title = Toglo'r paen canfod digwyddiadau
toolbar-folder-location-label = Lleoliad Ffolder
toolbar-folder-location =
    .title = Newid i ffolder
toolbar-edit-event-label = Golygu
toolbar-edit-event =
    .title = Golygu digwyddiadau neu dasgau penodol
toolbar-get-messages-label = Estyn Negeseuon
toolbar-get-messages =
    .title = Estyn negeseuon newydd ar gyfer pob cyfrif
toolbar-reply-label = Ateb
toolbar-reply =
    .title = Ateb y neges
toolbar-reply-all-label = Ateb Pawb
toolbar-reply-all =
    .title = Ateb yr anfonwr a phob derbyniwr
toolbar-reply-to-list-label = Ateb i'r Rhestr
toolbar-reply-to-list =
    .title = Ateb i'r rhestr e-bost
toolbar-redirect-label = Ailgyfeirio
toolbar-redirect =
    .title = Ailgyfeirio'r neges hon
toolbar-archive-label = Archifo
toolbar-archive =
    .title = Archifo'r negeseuon
toolbar-conversation-label = Sgwrs
toolbar-conversation =
    .title = Dangos sgwrs neges sydd wedi ei dewis
toolbar-previous-unread-label = Blaenorol Heb ei Darllen
toolbar-previous-unread =
    .title = Symud i'r neges heb ei darllen diwethaf
toolbar-previous-label = Blaenorol
toolbar-previous =
    .title = Symud i'r neges flaenorol
toolbar-next-unread-label = Nesaf Heb ei Darllen
toolbar-next-unread =
    .title = Symud i'r neges nesaf heb ei darllen
toolbar-next-label = Nesaf
toolbar-next =
    .title = Symud i'r neges nesaf
toolbar-junk-label = Sbam
toolbar-junk =
    .title = Marcio'r negeseuon hyn fel sbam
toolbar-delete-label = Dileu
toolbar-delete-title =
    .title = Dileu'r negeseuon a ddewiswyd
toolbar-undelete-label = Dad-ddileu
toolbar-undelete =
    .title = Dad-ddileu'r negeseuon a ddewiswyd
toolbar-compact-label = Cywasgu
toolbar-compact =
    .title = Tynnu negeseuon wedi'u dileu o'r ffolder
toolbar-add-as-event-label = Ychwanegu fel Digwyddiad
toolbar-add-as-event =
    .title = Tynnu gwybodaeth calendr o'r neges a'i hychwanegu i'ch calendr fel digwyddiad
toolbar-add-as-task-label = Ychwanegu fel tasg
toolbar-add-as-task =
    .title = Tynnu gwybodaeth calendr o'r neges a'i hychwanegu i'ch calendr fel tasg
toolbar-tag-message-label = Tagio
toolbar-tag-message =
    .title = Tagio negeseuon
toolbar-forward-inline-label = Ymlaen
toolbar-forward-inline =
    .title = Anfon neges dewiswyd ymlaen fel testun mewnlin
toolbar-forward-attachment-label = Anfon Ymlaen fel Atodiad
toolbar-forward-attachment =
    .title = Anfon neges dewiswyd ymlaen fel atodiad
toolbar-mark-as-label = Marcio
toolbar-mark-as =
    .title = Marcio negeseuon
toolbar-view-picker-label = Golwg
toolbar-view-picker =
    .title = Cyfaddasu golwg y ffolder gyfredol
toolbar-address-book-label = Llyfr Cyfeiriadau
toolbar-address-book =
    .title = Mynd i'r llyfr cyfeiriadau
toolbar-chat-label = Sgwrsio
toolbar-chat =
    .title = Dangos y tab Sgwrsio
toolbar-add-ons-and-themes-label = Ychwanegion a Themâu
toolbar-add-ons-and-themes =
    .title = Rheoli eich ychwanegion
toolbar-calendar-label = Calendr
toolbar-calendar =
    .title = Symud i'r tab calendr
toolbar-tasks-label = Tasgau
toolbar-tasks =
    .title = Symud i'r tab tasgau
toolbar-mail-label = E-bost
toolbar-mail =
    .title = Symud i'r tab e-bost
toolbar-print-label = Argraffu
toolbar-print =
    .title = Argraffu'r neges
toolbar-quick-filter-bar-label = Hidl Cyflym
toolbar-quick-filter-bar =
    .title = Hidlo negeseuon
toolbar-synchronize-label = Cydweddu
toolbar-synchronize =
    .title = Ail-lwytho calendrau a chydweddu newidiadau
toolbar-delete-event-label = Dileu
toolbar-delete-event =
    .title = Dileu digwyddiadau neu dasgau penodol
toolbar-go-to-today-label = Mynd i Heddiw
toolbar-go-to-today =
    .title = Mynd i Heddiw
toolbar-print-event-label = Argraffu
toolbar-print-event =
    .title = Argraffu digwyddiadau neu dasgau
toolbar-new-event-label = Digwyddiad
toolbar-new-event =
    .title = Creu digwyddiad newydd
toolbar-new-task-label = Tasg
toolbar-new-task =
    .title = Creu tasg newydd
toolbar-go-back-label = Nôl
toolbar-go-back =
    .title = Mynd nôl un neges
toolbar-go-forward-label = Ymlaen
toolbar-go-forward =
    .title = Mynd ymlaen un neges
toolbar-stop-label = Atal
toolbar-stop =
    .title = Atal y trosglwyddiad cyfredol
toolbar-throbber-label = Dangosydd Gweithgaredd
toolbar-throbber =
    .title = Dangosydd Gweithgaredd
toolbar-create-contact-label = Cysylltiad Newydd
toolbar-create-contact =
    .title = Creu cyswllt newydd
toolbar-create-address-book-label = Llyfr Cyfeiriadau Newydd
toolbar-create-address-book =
    .title = Creu llyfr cyfeiriadau newydd
toolbar-create-list-label = Rhestr Newydd
toolbar-create-list =
    .title = Creu rhestr e-bostio newydd
toolbar-import-contacts-label = Mewnforio
toolbar-import-contacts =
    .title = Mewnforio cysylltiadau o ffeil

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Ychwanegu Llyfr Cyfeiriadau Lleol
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Ychwanegu Llyfr Cyfeiriadau CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Ychwanegu Llyfr Cyfeiriadau LDAP
