# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibele romte
search-bar-label = Sykje
toolbar-write-message-label = Opstelle
toolbar-write-message =
    .title = Nij berjocht oanmeitsje
toolbar-move-to-label = Ferpleatse nei
toolbar-move-to =
    .title = Selektearre berjocht ferpleatse
toolbar-unifinder-label = Barren sykje
toolbar-unifinder =
    .title = It sykfinster foar barrens yn-/útskeakelje
toolbar-folder-location-label = Maplokaasje
toolbar-folder-location =
    .title = Wikselje nei map
toolbar-edit-event-label = Bewurkje
toolbar-edit-event =
    .title = Selektearre barren of taak bewurjke
toolbar-get-messages-label = E-mail ophelje
toolbar-get-messages =
    .title = Nije berjochten foar alle accounts ophelje
toolbar-reply-label = Beäntwurdzje
toolbar-reply =
    .title = Selektearre berjocht beäntwurdzje
toolbar-reply-all-label = Elk beäntwurdzje
toolbar-reply-all =
    .title = Ofstjoerder en alle adressearden beäntwurdzje
toolbar-reply-to-list-label = List beäntwurdzje
toolbar-reply-to-list =
    .title = Mailinglist beäntwurdzje
toolbar-redirect-label = Omliede
toolbar-redirect =
    .title = Selektearre berjocht omliede
toolbar-archive-label = Argivearje
toolbar-archive =
    .title = Selektearre berjocht argivearje
toolbar-conversation-label = Petear
toolbar-conversation =
    .title = Petear fan selektearre berjocht toane
toolbar-previous-unread-label = Foarige net lêzen
toolbar-previous-unread =
    .title = Nei it foarige net-lêzen berjocht gean
toolbar-previous-label = Foarige
toolbar-previous =
    .title = Nei it foarige berjocht gean
toolbar-next-unread-label = Folgjende net lêzen
toolbar-next-unread =
    .title = Nei it folgjende net-lêzen berjocht gean
toolbar-next-label = Folgjende
toolbar-next =
    .title = Nei it folgjende berjocht gean
toolbar-junk-label = Net-winske
toolbar-junk =
    .title = De selektearre berjochten as net-winske markearje
toolbar-delete-label = Fuortsmite
toolbar-delete-title =
    .title = De selektearre berjochten fuortsmite
toolbar-undelete-label = Fuortsmiten ûngedien meitsje
toolbar-undelete =
    .title = Fuortsmiten fan selektearre berjochten ûngedien meitsje
toolbar-compact-label = Komprimearje
toolbar-compact =
    .title = Fuortsmiten berjochten út de selektearre map definityf fuortsmite
toolbar-add-as-event-label = Tafoegje as barren
toolbar-add-as-event =
    .title = Helje aginda-ynformaasje út it berjocht en foegje it ta oan jo aginda as in barren
toolbar-add-as-task-label = Tafoegje as taak
toolbar-add-as-task =
    .title = Helje aginda-ynformaasje út it berjocht en foegje it ta oan jo aginda as in taak
toolbar-tag-message-label = Labelje
toolbar-tag-message =
    .title = Berjocht labelje
toolbar-forward-inline-label = Trochstjoere
toolbar-forward-inline =
    .title = Selektearre berjocht trochstjoere yn berjochttekst
toolbar-forward-attachment-label = Trochstjoere as bylage
toolbar-forward-attachment =
    .title = Selektearre berjocht trochstjoere as in bylage
toolbar-mark-as-label = Markearje
toolbar-mark-as =
    .title = Berjochten markearje
toolbar-view-picker-label = Byld
toolbar-view-picker =
    .title = Werjefte fan aktuele map oanpasse
toolbar-address-book-label = Adresboek
toolbar-address-book =
    .title = Adresboek iepenje
toolbar-chat-label = Chat
toolbar-chat =
    .title = Chatljepblêd toane
toolbar-add-ons-and-themes-label = Add-ons en tema’s
toolbar-add-ons-and-themes =
    .title = Jo add-ons beheare
toolbar-calendar-label = Aginda
toolbar-calendar =
    .title = Wikselje nei it agindaljepblêd
toolbar-tasks-label = Taken
toolbar-tasks =
    .title = Wikselje nei it takenljepblêd
toolbar-mail-label = E-mail
toolbar-mail =
    .title = Wikselje nei it e-mailljepblêd
toolbar-print-label = Ofdrukke
toolbar-print =
    .title = Dit berjocht ôfdrukke
toolbar-quick-filter-bar-label = Fluchfilter
toolbar-quick-filter-bar =
    .title = Berjochten filterje
toolbar-synchronize-label = Syngronisearje
toolbar-synchronize =
    .title = Aginda’s opnij lade en wizigingen syngronisearje
toolbar-delete-event-label = Fuortsmite
toolbar-delete-event =
    .title = Selektearre barrens of taken fuortsmite
toolbar-go-to-today-label = Nei hjoed gean
toolbar-go-to-today =
    .title = Nei hjoed gean
toolbar-print-event-label = Ofdrukke
toolbar-print-event =
    .title = Barren of taken ôfdrukke
toolbar-new-event-label = Barren
toolbar-new-event =
    .title = In nij barren meitsje
toolbar-new-task-label = Taak
toolbar-new-task =
    .title = In nije taak meitsje
toolbar-go-back-label = Tebek
toolbar-go-back =
    .title = Ien berjocht tebek gean
toolbar-go-forward-label = Foarút
toolbar-go-forward =
    .title = Ien berjocht foarút gean
toolbar-stop-label = Ophâlde
toolbar-stop =
    .title = Aktuele ferbining ferbrekke
toolbar-throbber-label = Aktiviteitsyndikator
toolbar-throbber =
    .title = Aktiviteitsyndikator
toolbar-create-contact-label = Nij kontakt
toolbar-create-contact =
    .title = In nij kontakt oanmeitsje
toolbar-create-address-book-label = Nij adresboek
toolbar-create-address-book =
    .title = In nij adresboek oanmeitsje
toolbar-create-list-label = Nije list
toolbar-create-list =
    .title = In nije e-maillist oanmeitsje
toolbar-import-contacts-label = Ymportearje
toolbar-import-contacts =
    .title = Kontakten út in bestân ymportearje

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lokaal adresboek tafoegje
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV-adresboek tafoegje
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP-adresboek tafoegje
