# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Zobrazované meno
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Typ
vcard-entry-type-home = Domov
vcard-entry-type-work = Práca
vcard-entry-type-none = Neurčené
vcard-entry-type-custom = Vlastné
vcard-name-header = Meno
vcard-n-prefix = Titul pred menom
vcard-n-add-prefix =
    .title = Pridať titul pred menom
vcard-n-firstname = Meno
vcard-n-add-firstname =
    .title = Pridať krstné meno
vcard-n-middlename = Stredné meno
vcard-n-add-middlename =
    .title = Pridať stredné meno
vcard-n-lastname = Priezvisko
vcard-n-add-lastname =
    .title = Pridať priezvisko
vcard-n-suffix = Titul za menom
vcard-n-add-suffix =
    .title = Pridať titul za menom
vcard-nickname = Prezývka
vcard-email-header = E‑mailové adresy
vcard-email-add = Pridať e‑mailovú adresu
vcard-email-label = E‑mailová adresa
vcard-primary-email-label = Predvolené
vcard-url-header = Webové stránky
vcard-url-add = Pridať webovú stránku
vcard-url-label = Webová stránka
vcard-tel-header = Telefónne čísla
vcard-tel-add = Pridať telefónne číslo
vcard-tel-label = Telefónne číslo
# Or "Mobile"
vcard-entry-type-cell = Mobil
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pager
vcard-tz-header = Časové pásmo
vcard-tz-add = Pridať časové pásmo
vcard-impp2-header = Okamžité správy
vcard-impp-add = Pridať účet pre konverzácie
vcard-impp-label = Účet pre konverzácie
vcard-impp-select = Protokol
vcard-impp-option-other = Iné
vcard-impp-input-label = URI
vcard-impp-input-title = URI pre okamžité správy
vcard-bday-anniversary-header = Špeciálne dátumy
vcard-bday-anniversary-add = Pridať špeciálny dátum
vcard-bday-label = Narodeniny
vcard-anniversary-label = Výročie
vcard-date-day = Deň
vcard-date-month = Mesiac
vcard-date-year = Rok
vcard-adr-header = Adresy
vcard-adr-add = Pridať adresu
vcard-adr-label = Adresa
vcard-adr-delivery-label = Doručovací štítok
vcard-adr-street = Ulica
# Or "Locality"
vcard-adr-locality = Mesto
# Or "Region"
vcard-adr-region = Štát alebo provincia
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = PSČ
vcard-adr-country = Krajina
vcard-note-header = Poznámky
vcard-note-add = Pridať poznámku
vcard-org-header = Pozícia vo firme
vcard-org-add = Pridať pozíciu vo firme
vcard-org-title = Titul
vcard-org-title-input =
    .placeholder = Funkcia
    .title = Pozícia alebo práca
vcard-org-role = Funkcia
vcard-org-role-input =
    .placeholder = Úloha v projekte
    .title = Funkcia alebo úloha v konkrétnej situácii
vcard-org-org = Organizácia
vcard-org-org-input =
    .placeholder = Názov spoločnosti
    .title = Názov organizácie
vcard-org-org-unit = Oddelenie
vcard-org-org-unit-input =
    .placeholder = Oddelenie
    .title = Názov organizačnej jednotky
vcard-custom-header = Vlastné údaje
vcard-custom-add = Pridať vlastné údaje
vcard-remove-button-title =
    .title = Odstrániť
vcard-remove-button = Odstrániť
