# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Esaouenn wevn
toolbar-write-message-label = Skridaozañ
toolbar-write-message =
    .title = Sevel ur gemennadenn nevez
toolbar-unifinder-label = Kavout darvoudoù
toolbar-unifinder =
    .title = Diskouez/Kuzhat panell ar c'hlask darvoudoù
toolbar-folder-location-label = Lec'hiadur an teuliad
toolbar-edit-event-label = Embann
toolbar-edit-event =
    .title = Embann an darvoud pe an trevell diuzet
toolbar-get-messages-label = Kerc'hat ar c'hemennadennoù
toolbar-reply-label = Respont
toolbar-reply =
    .title = Respont d'ar gemennadenn-mañ
toolbar-reply-all-label = Respont d'an holl
toolbar-reply-all =
    .title = Respont d'ar c'haser ha d'an holl zegemererien
toolbar-reply-to-list-label = Respont d'ar roll
toolbar-reply-to-list =
    .title = Respont d'ar roll posteloù
toolbar-archive-label = Diellaouiñ
toolbar-archive =
    .title = Diellaouiñ ar c'hemennadennoù diuzet
toolbar-conversation-label = Kaozeadenn
toolbar-conversation =
    .title = Diskouez kaozeadenn ar gemennadenn diuzet
toolbar-previous-unread-label = Anlennet kent
toolbar-previous-unread =
    .title = Mont d'ar gemennadenn anlennet kent
toolbar-previous-label = Kent
toolbar-previous =
    .title = Mont d'ar gemennadenn kent
toolbar-next-unread-label = Anlennet war-lerc'h
toolbar-next-unread =
    .title = Mont d'ar gemennadenn anlennet war-lerc'h
toolbar-next-label = War-lerc'h
toolbar-next =
    .title = Mont d'ar gemennadenn war-lerc'h
toolbar-compact-label = Koazhañ
toolbar-compact =
    .title = Lemel ar c'hemennadennoù dilamet diouzh an teuliad diuzet
toolbar-add-as-event-label = Ouzhpennañ e-giz un darvoud
toolbar-add-as-event =
    .title = Eztennañ titouroù deiziataer diouzh ar gemennadenn-mañ hag ouzhpennañ anezho d’ho teiziataer evel un darvoud
toolbar-add-as-task-label = Ouzhpennañ e-giz un trevell
toolbar-add-as-task =
    .title = Eztennañ titouroù deiziataer diouzh ar gemennadenn-mañ hag ouzhpennañ anezho d’ho teiziataer evel un trevell
toolbar-tag-message-label = Merk
toolbar-tag-message =
    .title = Merkañ kemennadennoù
toolbar-forward-inline-label = Treuzkas
toolbar-forward-inline =
    .title = Treuzkas ar gemennadenn diuzet evel testenn enkorfet
toolbar-forward-attachment-label = Treuzkas evel kenstagadur
toolbar-forward-attachment =
    .title = Treuzkas ar gemennadenn diuzet evel kenstagadur
toolbar-mark-as-label = Merk
toolbar-mark-as =
    .title = Merkañ kemennadennoù
toolbar-address-book =
    .title = Mont d'ar c'harned chomlec'hioù
toolbar-chat-label = Postelerezh prim
toolbar-chat =
    .title = Diskouez an ivinell postelerezh prim
toolbar-calendar-label = Deiziataer
toolbar-calendar =
    .title = Mont betek ivinell an deiziataer
toolbar-tasks-label = Trevelloù
toolbar-tasks =
    .title = Mont betek ivinell an trevelloù
toolbar-print-label = Moullañ
toolbar-print =
    .title = Moullañ ar gemennadenn-mañ
toolbar-quick-filter-bar =
    .title = Silañ ar c’hemennadennoù
toolbar-synchronize-label = Goubredañ
toolbar-synchronize =
    .title = Adkargañ an deiziataerioù ha goubredañ ar c'hemmadennoù
toolbar-delete-event-label = Dilemel
toolbar-delete-event =
    .title = Dilemel an darvoudoù hag an trevelloù diuzet
toolbar-go-to-today-label = Mont da hiziv
toolbar-go-to-today =
    .title = Mont da Hiziv
toolbar-print-event-label = Moullañ
toolbar-print-event =
    .title = Moullañ an darvoudoù pe an trevelloù
toolbar-new-event-label = Darvoud
toolbar-new-event =
    .title = Krouiñ un darvoud nevez
toolbar-new-task-label = Trevell
toolbar-new-task =
    .title = Krouiñ un drevell nevez
toolbar-go-back-label = Kent
toolbar-go-back =
    .title = Mont d'ar gemennadenn gent
toolbar-go-forward-label = War-lerc'h
toolbar-go-forward =
    .title = Mont d'ar gemennadenn war-lerc'h
toolbar-stop-label = Paouez
toolbar-stop =
    .title = Paouez gant an treuzkas bremanel
toolbar-throbber-label = Meneger oberiantiz
toolbar-throbber =
    .title = Meneger oberiantiz
