# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

connection-proxy-legend = Наладзіць проксі для доступу ў інтэрнэт
proxy-type-no =
    .label = Не выкарыстоўваць проксі
    .accesskey = Н
proxy-type-wpad =
    .label = Аўтаматычна выяўляць налады проксі для гэтай сеткі
    .accesskey = А
proxy-type-system =
    .label = Выкарыстоўваць сістэмныя налады проксі
    .accesskey = В
proxy-type-manual =
    .label = Ручная канфігурацыя проксі:
    .accesskey = Р
proxy-http-label =
    .value = HTTP-проксі:
    .accesskey = п
http-port-label =
    .value = Порт:
    .accesskey = п
ssl-port-label =
    .value = Порт:
    .accesskey = о
proxy-socks-label =
    .value = Трымальнік SOCKS:
    .accesskey = c
socks-port-label =
    .value = Порт:
    .accesskey = т
proxy-socks4-label =
    .label = SOCKS 4
    .accesskey = 4
proxy-socks5-label =
    .label = SOCKS 5
    .accesskey = 5
proxy-type-auto =
    .label = URL аўтаматычнай канфігурацыі проксі:
    .accesskey = ў
proxy-reload-label =
    .label = Абнавіць
    .accesskey = А
no-proxy-label =
    .value = Не выкарыстоўваць проксі для:
    .accesskey = Н
no-proxy-example = Прыклад: .mozilla.org, .net.nz, 192.168.1.0/24
proxy-password-prompt =
    .label = Не запытваць апазнаванне, калі ёсць захаваны пароль
    .accesskey = е
    .tooltiptext = Гэтая налада без запытаў выконвае апазнаванне вас на проксі, калі вы маеце захаваныя для іх уліковыя запісы. Запыт адбудзецца толькі падчас няўдачы апазнавання.
proxy-remote-dns =
    .label = Праксіраваць DNS-запыты пры выкарыстанні SOCKS 5
    .accesskey = d
