# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Display name
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Type
vcard-entry-type-home = Home
vcard-entry-type-work = Work
vcard-entry-type-none = None
vcard-entry-type-custom = Custom
vcard-name-header = Name
vcard-n-prefix = Prefix
vcard-n-add-prefix =
    .title = Add prefix
vcard-n-firstname = First name
vcard-n-add-firstname =
    .title = Add first name
vcard-n-middlename = Middle name
vcard-n-add-middlename =
    .title = Add middle name
vcard-n-lastname = Last name
vcard-n-add-lastname =
    .title = Add last name
vcard-n-suffix = Suffix
vcard-n-add-suffix =
    .title = Add suffix
vcard-nickname = Nickname
vcard-email-header = Email Addresses
vcard-email-add = Add email address
vcard-email-label = Email address
vcard-primary-email-label = Default
vcard-url-header = Web Sites
vcard-url-add = Add web site
vcard-url-label = Web Site
vcard-tel-header = Phone Numbers
vcard-tel-add = Add phone number
vcard-tel-label = Phone number
# Or "Mobile"
vcard-entry-type-cell = Mobile
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pager
vcard-tz-header = Time Zone
vcard-tz-add = Add time zone
vcard-impp2-header = Instant Messaging
vcard-impp-add = Add chat account
vcard-impp-label = Chat account
vcard-impp-select = Protocol
vcard-impp-option-other = Other
vcard-impp-input-label = URI
vcard-impp-input-title = URI for instant messaging
vcard-bday-anniversary-header = Special Dates
vcard-bday-anniversary-add = Add special date
vcard-bday-label = Birthday
vcard-anniversary-label = Anniversary
vcard-date-day = Day
vcard-date-month = Month
vcard-date-year = Year
vcard-adr-header = Addresses
vcard-adr-add = Add address
vcard-adr-label = Address
vcard-adr-delivery-label = Delivery label
vcard-adr-street = Street address
# Or "Locality"
vcard-adr-locality = City
# Or "Region"
vcard-adr-region = Region
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postcode
vcard-adr-country = Country
vcard-note-header = Notes
vcard-note-add = Add note
vcard-org-header = Organisational Properties
vcard-org-add = Add organisational properties
vcard-org-title = Title
vcard-org-title-input =
    .placeholder = Job title
    .title = Position or job
vcard-org-role = Role
vcard-org-role-input =
    .placeholder = Role in a project
    .title = Function or part played in a particular situation
vcard-org-org = Organisation
vcard-org-org-input =
    .placeholder = Company name
    .title = Organisational name
vcard-org-org-unit = Department
vcard-org-org-unit-input =
    .placeholder = Department
    .title = Organisational unit name
vcard-custom-header = Custom Properties
vcard-custom-add = Add custom properties
vcard-remove-button-title =
    .title = Remove
vcard-remove-button = Remove
