# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Commentaire
calendar-item-summary-title = Titre :
calendar-item-summary-calendar = Agenda :
calendar-item-summary-task-start = Date de début :
calendar-item-summary-event-start = Date de début :
calendar-item-summary-task-due = Fin prévue :
calendar-item-summary-event-end = Date de fin :
calendar-item-summary-repeat = Répétition :
calendar-item-summary-location = Lieu :
calendar-item-summary-category = Catégorie :
calendar-item-summary-organizer = Organisateur :
calendar-item-summary-status = Statut :
calendar-item-summary-reminder = Rappel :
calendar-item-summary-attachments = Pièces jointes :
calendar-item-summary-status-tentative = Provisoire
calendar-item-summary-status-confirmed = Confirmé
calendar-item-summary-event-status-cancelled = Annulé
calendar-item-summary-todo-status-cancelled = Annulé
calendar-item-summary-status-needs-action = Une action est requise
calendar-item-summary-status-in-process = En cours
calendar-item-summary-status-completed = Achevé le
calendar-item-summary-reminder-none =
    .label = Aucun
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutes avant
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutes avant
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutes avant
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutes avant
calendar-item-summary-reminder-1-hour-before =
    .label = 1 heure avant
calendar-item-summary-reminder-2-hours-before =
    .label = 2 heures avant
calendar-item-summary-reminder-12-hours-before =
    .label = 12 heures avant
calendar-item-summary-reminder-1-day-before =
    .label = 1 jour avant
calendar-item-summary-reminder-2-days-before =
    .label = 2 jours avant
calendar-item-summary-reminder-1-week-before =
    .label = 1 semaine avant
calendar-item-summary-reminder-custom =
    .label = Personnaliser…
calendar-item-summary-reminder-multiple =
    .value = Rappels multiples…
calendar-item-summary-general =
    .value = Général
calendar-item-summary-attendees =
    .value = Participants
calendar-item-summary-description =
    .value = Description
calendar-item-summary-link =
    .value = Lien
