# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Tout sélectionner
select-none-calendars = Ne rien sélectionner
calendar-creation-wizard-title = Créer un nouvel agenda
calendar-creation-initial-description = Votre agenda peut être stocké sur votre ordinateur ou sur un serveur afin d’y accéder à distance ou de le partager avec vos amis ou vos collègues de travail.
calendar-creation-initial-computer =
    .label = Sur mon ordinateur
calendar-creation-initial-network =
    .label = Sur le réseau
calendar-creation-username =
    .value = Nom d’utilisateur :
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Créer un agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retour
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Créer un agenda
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retour
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Rechercher des agendas
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Retour
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = S’abonner
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Retour
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = Type d’agenda :
calendar-creation-location =
    .value = Adresse :
calendar-creation-location-placeholder =
    .placeholder = Adresse web ou nom d’hôte du serveur de l’agenda
    .default-placeholder = Adresse web ou nom d’hôte du serveur de l’agenda
calendar-creation-network-nocredentials =
    .label = Cette adresse ne demande pas d’identifiants de connexion
calendar-creation-network-loading = Veuillez patienter pendant que vos agendas sont découverts.
calendar-creation-network-notfound = Aucun agenda à cette adresse. Veuillez vérifier les paramètres.
calendar-creation-network-authfail = Les identifiants de connexion saisis n’ont pas été acceptés. Veuillez vérifier les paramètres.
calendar-creation-network-certerror = Impossible de trouver un agenda à cet emplacement en raison d’un problème de certificat.
calendar-creation-network-subscribe-single = Sélectionnez les agendas auxquels vous souhaitez vous abonner.
calendar-creation-network-subscribe-multiple = Plusieurs types d’agendas sont disponibles pour cette adresse. Sélectionnez le type d’agenda, puis choisissez les agendas auxquels vous souhaitez vous abonner.
