# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

account-settings-color-label = Barwa:
    .accesskey = B
account-settings-reset-color-button =
    .title = Barwu slědk stajiś
delete-account-button =
    .label = Lašowaś
default-account-button =
    .label = Ako standard nastajiś
outgoing-server-name = Wuchadny serwer:
    .accesskey = u
outgoing-server-edit =
    .label = Wuchadny serwer wobźěłaś…
    .accesskey = c
oauth2-use-custom-details =
    .label = Swójske nastajenja OAuth2 wužywaś
    .accesskey = S
oauth2-client-id-label =
    .value = ID klienta:
    .accesskey = I
oauth2-authorization-endpoint-label =
    .value = Kóńcny dypk awtorizacije:
    .accesskey = c
oauth2-token-endpoint-label =
    .value = Kóńcny dypk tokena
    .accesskey = t
oauth2-scopes-label =
    .value = Wobceŕki:
    .accesskey = o
oauth2-redirection-endpoint-label =
    .value = URL dalejpósrědnjenja:
    .accesskey = D
oauth2-use-pkce =
    .label = PKCE wužywaś
    .accesskey = K
oauth2-use-system-browser =
    .label = Systemowy webwobglědowak wužywaś
    .accesskey = S
ews-url-label =
    .value = URL hosta:
    .accesskey = U
ews-override-oauth-details =
    .label = Nastajenja Office 365 pśepisaś:
    .accesskey = O
ews-applicationid-label =
    .value = ID nałoženja:
    .accesskey = n
ews-tenantid-label =
    .value = ID tenanta:
    .accesskey = t
ews-redirecturi-label =
    .value = Dalejpósrědnjański URL:
    .accesskey = D
ews-endpointhost-label =
    .value = Host kóńcnego dypka:
    .accesskey = k
ews-oauthscopes-label =
    .value = Wobceŕki OAuth:
    .accesskey = b
