# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibelna prozny rum
search-bar-label = Pytaś
toolbar-write-message-label = Pisaś
toolbar-write-message =
    .title = Nowu powěsć napóraś
toolbar-move-to-label = Pśesunuś do
toolbar-move-to =
    .title = Wubranu powěsć pśesunuś
toolbar-unifinder-label = Tšojenja pytaś
toolbar-unifinder =
    .title = Wobłuk "Tšojenja namakaś" pśešaltowaś
toolbar-folder-location-label = Městno zarědnika
toolbar-folder-location =
    .title = K zarědnikoju pśejś
toolbar-edit-event-label = Wobźěłaś
toolbar-edit-event =
    .title = Wubrane tšojenje abo wubrany nadawk wobźěłaś
toolbar-get-messages-label = Powěsći wobstaraś
toolbar-get-messages =
    .title = Nowe powěsći za wšykne konta wobstaraś
toolbar-reply-label = Wótegroniś
toolbar-reply =
    .title = Na powěsć wótegroniś
toolbar-reply-all-label = Wšym wótegroniś
toolbar-reply-all =
    .title = Wótpósłarjeju a wšym dostawarjam wótegroniś
toolbar-reply-to-list-label = Lisćinje wótegroniś
toolbar-reply-to-list =
    .title = Rozposłańska lisćina
toolbar-redirect-label = Dalej pósrědniś
toolbar-redirect =
    .title = Wubranu powěsć dalej pósrědniś
toolbar-archive-label = Archiw
toolbar-archive =
    .title = Wubrane powěsći archiwěrowaś
toolbar-conversation-label = Rozgrono
toolbar-conversation =
    .title = Rozgrono wubraneje powěsći pokazaś
toolbar-previous-unread-label = Pjerwjejšna njepśecytana
toolbar-previous-unread =
    .title = K pjerjwjejšnej njepśecytanej powěsći
toolbar-previous-label = Pjerwjejšna
toolbar-previous =
    .title = K pjerwjejšnej powěsći pśesunuś
toolbar-next-unread-label = Pśidujuca njepśecytana
toolbar-next-unread =
    .title = K pśidujucej njepśecytanej powěsći
toolbar-next-label = Dalej
toolbar-next =
    .title = K pśidujucej powěsći pśesunuś
toolbar-junk-label = Cajk
toolbar-junk =
    .title = Wubrane powěsći ako cajk markěrowaś
toolbar-delete-label = Lašowaś
toolbar-delete-title =
    .title = Wubrane powěsći lašowaś
toolbar-undelete-label = Wótnowiś
toolbar-undelete =
    .title = Wubrane powěsći wótnowiś
toolbar-compact-label = Kompaktny
toolbar-compact =
    .title = Wulašowane powěsći z wubranego zarědnika wótpóraś
toolbar-add-as-event-label = Ako tšojenje pśidaś
toolbar-add-as-event =
    .title = Tšojeńske informacije z powěsći ekstrahěrowaś a je wašomu kalenderoju ako tšojenje pśidaś
toolbar-add-as-task-label = Ako nadawk pśidaś
toolbar-add-as-task =
    .title = Tšojeńske informacije z powěsći ekstrahěrowaś a je wašomu kalenderoju ako nadawk pśidaś
toolbar-tag-message-label = Wobznamjenje
toolbar-tag-message =
    .title = Powěsći wóznamjeniś
toolbar-forward-inline-label = Dalej pósrědniś
toolbar-forward-inline =
    .title = Wubranu powěsć ako zasajźony tekst dalej pósrědniś
toolbar-forward-attachment-label = Ako pśidank dalej pósrědniś
toolbar-forward-attachment =
    .title = Wubranu powěsć ako pśidank dalej pósrědniś
toolbar-mark-as-label = Markěrowaś
toolbar-mark-as =
    .title = Powěsći markěrowaś
toolbar-view-picker-label = Naglěd
toolbar-view-picker =
    .title = Naglěd aktualnego zarědnika pśiměriś
toolbar-address-book-label = Adresnik
toolbar-address-book =
    .title = K adresnikoju
toolbar-chat-label = Chat
toolbar-chat =
    .title = Chatowy rejtarik pokazaś
toolbar-add-ons-and-themes-label = Dodanki a drastwy
toolbar-add-ons-and-themes =
    .title = Waše dodanki zastojaś
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Ku kalenderowemu rejtarikoju pśešaltowaś
toolbar-tasks-label = Nadawki
toolbar-tasks =
    .title = K nadawkowemu rejtarikoju pśešaltowaś
toolbar-mail-label = E-mail
toolbar-mail =
    .title = K e-mailowemu rejtarikoju pśejś
toolbar-print-label = Śišćaś
toolbar-print =
    .title = Toś tu powěsć śišćaś
toolbar-quick-filter-bar-label = Spěšny filter
toolbar-quick-filter-bar =
    .title = Powěsći filtrowaś
toolbar-synchronize-label = Synchronizěrowaś
toolbar-synchronize =
    .title = Kalendery znowego zacytaś a změny synchronizěrowaś
toolbar-delete-event-label = Wulašowaś
toolbar-delete-event =
    .title = Wubrane tšojenja abo nadawki wulašowaś
toolbar-go-to-today-label = K źinsajšnemu
toolbar-go-to-today =
    .title = K źinsajšnemu
toolbar-print-event-label = Śišćaś
toolbar-print-event =
    .title = Tšojenja abo nadawki śišćaś
toolbar-new-event-label = Tšojenje
toolbar-new-event =
    .title = Nowe tšojenje napóraś
toolbar-new-task-label = Nadawk
toolbar-new-task =
    .title = Nowy nadawk napóraś
toolbar-go-back-label = Slědk
toolbar-go-back =
    .title = Wó jadnu powěsć slědk
toolbar-go-forward-label = Doprědka
toolbar-go-forward =
    .title = Wó jadnu powěsć doprědka
toolbar-stop-label = Stoj
toolbar-stop =
    .title = Aktualne pśenjasenje zastajiś
toolbar-throbber-label = Indikator aktiwity
toolbar-throbber =
    .title = Indikator aktiwity
toolbar-create-contact-label = Nowy kontakt
toolbar-create-contact =
    .title = Nowy kontakt napóraś
toolbar-create-address-book-label = Nowy adresnik
toolbar-create-address-book =
    .title = Nowy adresnik załožyś
toolbar-create-list-label = Nowa lisćina
toolbar-create-list =
    .title = Nowu rozpósłańsku lisćinu załožyś
toolbar-import-contacts-label = Importěrowaś
toolbar-import-contacts =
    .title = Kontakty z dataje importěrowaś

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lokalny adresnik pśidaś
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Adresnik CardDAV pśidaś
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Adresnik LDAP pśidaś
