# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Избиране на всичко
select-none-calendars = Избиране на нищо
calendar-creation-wizard-title = Създаване на нов календар
calendar-creation-initial-description = Календарът може да бъде запазен на този компютър или на сървър, за да бъде достъпен отдалечено или за да го споделяте с приятели или колеги.
calendar-creation-initial-computer =
    .label = На този компютър
calendar-creation-initial-network =
    .label = На сървър
calendar-creation-username =
    .value = Потребителско име:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Създаване на календар
    .buttonaccesskeyaccept = к
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = н
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Създаване на календар
    .buttonaccesskeyaccept = к
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = н
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Намиране на календар
    .buttonaccesskeyaccept = м
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = н
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Абониране
    .buttonaccesskeyaccept = а
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = н
calendar-creation-type =
    .value = Тип календар:
calendar-creation-location =
    .value = Местоположение:
calendar-creation-location-placeholder =
    .placeholder = URL или име на хост на сървъра на календара
    .default-placeholder = URL или име на хост на сървъра на календара
calendar-creation-network-nocredentials =
    .label = Това местоположение не изисква идентификационни данни
calendar-creation-network-loading = Моля, изчакайте, докато вашите календари бъдат открити.
calendar-creation-network-notfound = Няма намерени календари на това място. Моля, проверете настройките си.
calendar-creation-network-authfail = Идентификационните данни, които сте въвели, не бяха приети. Моля, проверете настройките си.
calendar-creation-network-certerror = Календарите не могат да бъдат намерени на това място поради проблем със сертификата за сигурност.
calendar-creation-network-subscribe-single = Моля, изберете календарите, за които искате да се абонирате.
calendar-creation-network-subscribe-multiple = За това местоположение са налични множество типове календари. Моля, изберете типа календар, след което маркирайте календарите, за които искате да се абонирате.
