# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Заглавие:
calendar-item-summary-calendar = Календар:
calendar-item-summary-task-start = Начална дата:
calendar-item-summary-event-start = Начална дата:
calendar-item-summary-task-due = Краен срок:
calendar-item-summary-event-end = Крайна дата:
calendar-item-summary-repeat = Повторение:
calendar-item-summary-location = Местоположение:
calendar-item-summary-category = Категория:
calendar-item-summary-organizer = Организатор:
calendar-item-summary-status = Състояние:
calendar-item-summary-reminder = Напомняне:
calendar-item-summary-attachments = Прикачени файлове:
calendar-item-summary-status-tentative = Несигурен
calendar-item-summary-status-confirmed = Потвърдил
calendar-item-summary-event-status-cancelled = Отказано
calendar-item-summary-todo-status-cancelled = Отказано
calendar-item-summary-status-needs-action = Изисква действие
calendar-item-summary-status-in-process = В процес
calendar-item-summary-status-completed = Завършено на
calendar-item-summary-reminder-none =
    .label = Без напомняне
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 минути по-рано
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 минути по-рано
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 минути по-рано
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 минути по-рано
calendar-item-summary-reminder-1-hour-before =
    .label = 1 час по-рано
calendar-item-summary-reminder-2-hours-before =
    .label = 2 часа по-рано
calendar-item-summary-reminder-12-hours-before =
    .label = 12 часа по-рано
calendar-item-summary-reminder-1-day-before =
    .label = 1 ден по-рано
calendar-item-summary-reminder-2-days-before =
    .label = 2 дена по-рано
calendar-item-summary-reminder-1-week-before =
    .label = 1 седмица по-рано
calendar-item-summary-reminder-custom =
    .label = Приспособяване…
calendar-item-summary-reminder-multiple =
    .value = Много напомняния…
calendar-item-summary-general =
    .value = Основни
calendar-item-summary-attendees =
    .value = Участници
calendar-item-summary-description =
    .value = Описание
calendar-item-summary-link =
    .value = Сродни връзки
