# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Ρυθμίσεις εκτός σύνδεσης
offline-startup-label = Κατά το άνοιγμα του { -brand-short-name }:
status-radio-start-online =
    .label = Έναρξη εντός σύνδεσης
    .accesskey = η
status-radio-start-offline =
    .label = Έναρξη εκτός σύνδεσης
    .accesskey = ξ
going-online-send =
    .label = Ναι, αυτόματη αποστολή
    .accesskey = Ν
going-online-keep =
    .label = Όχι, διατήρηση στα Εξερχόμενα
    .accesskey = χ
going-online-ask-send =
    .label = Ερώτηση πριν από την αποστολή
    .accesskey = σ
going-offline-prompt = Θέλετε να κάνετε λήψη μηνυμάτων για ανάγνωση εκτός σύνδεσης;
going-offline-download =
    .label = Ναι, αυτόματη λήψη
    .accesskey = α
going-offline-keep =
    .label = Όχι, να μην γίνει λήψη
    .accesskey = ι
going-offline-ask-download =
    .label = Ερώτηση πριν από τη λήψη
    .accesskey = α
autodetect-online-label =
    .label = Αυτόματη χρήση ανιχνευμένης κατάστασης σύνδεσης
    .accesskey = ν
offline-preference-startup-label = Μη αυτόματη κατάσταση κατά την εκκίνηση:
status-radio-remember =
    .label = Διατήρηση προηγούμενης κατάστασης
    .accesskey = Δ
status-radio-ask =
    .label = Ερώτηση για την κατάσταση σύνδεσης
    .accesskey = ώ
status-radio-always-online =
    .label = Εντός σύνδεσης
    .accesskey = δ
status-radio-always-offline =
    .label = Εκτός σύνδεσης
    .accesskey = κ
going-online-label = Αποστολή μη απεσταλμένων μηνυμάτων κατά τη σύνδεση;
going-online-auto =
    .label = Ναι
    .accesskey = Ν
going-online-not =
    .label = Όχι
    .accesskey = Ό
going-online-ask =
    .label = Ερώτηση
    .accesskey = σ
going-offline-label = Λήψη μηνυμάτων για εργασία εκτός σύνδεσης κατά την αποσύνδεση;
going-offline-auto =
    .label = Ναι
    .accesskey = Ν
going-offline-not =
    .label = Όχι
    .accesskey = ι
going-offline-ask =
    .label = Ερώτηση
    .accesskey = ρ
