# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Αποδεικτικά ανάγνωσης
return-receipt-checkbox-control =
    .label = Κατά την αποστολή μηνυμάτων, να ζητείται πάντα αποδεικτικό προβολής
    .accesskey = Κ
receipt-arrive-label = Όταν φτάνει ένα αποδεικτικό:
receipt-leave-inbox-control =
    .label = Διατήρηση στα Εισερχόμενα
    .accesskey = ι
receipt-move-sent-control =
    .label = Μεταφορά στον φάκελο «Απεσταλμένα»
    .accesskey = μ
receipt-sender-request-label = Όταν ένας αποστολέας ζητά αποδεικτικό παραλαβής:
receipt-leave-radio-control =
    .label = Διατήρηση στα εισερχόμενα
    .accesskey = ρ
receipt-move-radio-control =
    .label = Μετακίνηση στον φάκελο «Απεσταλμένα»
    .accesskey = φ
receipt-request-label = Κατά τη λήψη αιτήματος για αποδεικτικό προβολής:
receipt-return-never-radio-control =
    .label = Να μην γίνεται ποτέ αποστολή αποδεικτικού προβολής
    .accesskey = ν
receipt-return-some-radio-control =
    .label = Αποδοχή αποδεικτικών προβολής για ορισμένα μηνύματα
    .accesskey = χ
receipt-not-listed-cc-label =
    .value = Εάν δεν αναγράφεται στο πεδίο «Προς» ή «Κοιν.»:
    .accesskey = φ
receipt-not-to-cc-label =
    .value = Αν δεν είμαι στα πεδία «Προς» ή «Κοιν.» του μηνύματος:
    .accesskey = π
receipt-send-never-label =
    .label = Ποτέ αποστολή
receipt-send-always-label =
    .label = Αποστολή πάντα
receipt-send-ask-label =
    .label = Ερώτηση
sender-outside-company-label =
    .value = Εάν ο αποστολέας είναι εκτός εταιρείας ή τομέα:
    .accesskey = τ
sender-outside-domain-label =
    .value = Αν ο αποστολέας είναι εκτός του τομέα μου:
    .accesskey = μ
other-cases-text-label =
    .value = Σε όλες τις άλλες περιπτώσεις:
    .accesskey = τ
read-receipts-dialog-title = Αποδεικτικά ανάγνωσης
