# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Pružná medzera
search-bar-label = Hľadať
toolbar-write-message-label = Nová
toolbar-write-message =
    .title = Napísať novú správu
toolbar-move-to-label = Presunúť do
toolbar-move-to =
    .title = Presunúť označenú správu
toolbar-unifinder-label = Hľadať udalosti
toolbar-unifinder =
    .title = Prepnúť panel Hľadať udalosti
toolbar-folder-location-label = Umiestnenie priečinka
toolbar-folder-location =
    .title = Prepnúť do priečinka
toolbar-edit-event-label = Upraviť
toolbar-edit-event =
    .title = Upraviť zvolenú udalosť alebo úlohu
toolbar-get-messages-label = Prijať správy
toolbar-get-messages =
    .title = Načítať nové správy pre všetky účty
toolbar-reply-label = Odpoveď
toolbar-reply =
    .title = Odpovedať na správu
toolbar-reply-all-label = Odpoveď Vš.
toolbar-reply-all =
    .title = Odpovedať odosielateľovi a všetkým adresátom
toolbar-reply-to-list-label = Odpovedať zoznamu
toolbar-reply-to-list =
    .title = Odpovedať členom rozosielacieho zoznamu
toolbar-redirect-label = Presmerovať
toolbar-redirect =
    .title = Presmerovať vybranú správu
toolbar-archive-label = Archivovať
toolbar-archive =
    .title = Presunúť označené správy do archívu
toolbar-conversation-label = Konverzácie
toolbar-conversation =
    .title = Zobraziť konverzáciu k vybranej správe
toolbar-previous-unread-label = Predchádzajúce vlákno
toolbar-previous-unread =
    .title = Presunúť sa na predchádzajúcu neprečítanú správu
toolbar-previous-label = Predchádzajúca
toolbar-previous =
    .title = Presunúť sa na predchádzajúcu správu
toolbar-next-unread-label = Ďalšie vlákno
toolbar-next-unread =
    .title = Presunúť sa na nasledujúcu neprečítanú správu
toolbar-next-label = Ďalšia
toolbar-next =
    .title = Presunúť sa na nasledujúcu správu
toolbar-junk-label = Spam
toolbar-junk =
    .title = Označiť vybrané správy ako nevyžiadané (SPAM)
toolbar-delete-label = Odstrániť
toolbar-delete-title =
    .title = Odstrániť označené správy
toolbar-undelete-label = Zrušiť odstránenie
toolbar-undelete =
    .title = Zrušiť odstránenie označených správ
toolbar-compact-label = Vykonať údržbu
toolbar-compact =
    .title = Odstráni vymazané správy z označeného priečinka
toolbar-add-as-event-label = Pridať ako udalosť
toolbar-add-as-event =
    .title = Extrahuje informácie o termínoch z e‑mailovej správy a pridá ich do kalendára ako udalosť
toolbar-add-as-task-label = Pridať ako úlohu
toolbar-add-as-task =
    .title = Extrahuje informácie o termínoch z e‑mailovej správy a pridá ich do kalendára ako úlohu
toolbar-tag-message-label = Štítky
toolbar-tag-message =
    .title = Priradí správe štítok
toolbar-forward-inline-label = Odoslať ďalej
toolbar-forward-inline =
    .title = Odoslať ďalej zvolenú správu v texte novej správy
toolbar-forward-attachment-label = Odoslať ďalej ako prílohu
toolbar-forward-attachment =
    .title = Odoslať ďalej zvolenú správu ako prílohu
toolbar-mark-as-label = Označiť
toolbar-mark-as =
    .title = Označiť správy
toolbar-view-picker-label = Zobraziť
toolbar-view-picker =
    .title = Prispôsobenie zobrazenia aktuálneho priečinka
toolbar-address-book-label = Adresár
toolbar-address-book =
    .title = Otvorí adresár
toolbar-chat-label = Konverzácie
toolbar-chat =
    .title = Zobrazí kartu Konverzácie
toolbar-add-ons-and-themes-label = Doplnky a témy
toolbar-add-ons-and-themes =
    .title = Správa doplnkov a tém
toolbar-calendar-label = Kalendár
toolbar-calendar =
    .title = Prepnúť na kartu Kalendár
toolbar-tasks-label = Úlohy
toolbar-tasks =
    .title = Prepnúť na kartu Úlohy
toolbar-mail-label = Pošta
toolbar-mail =
    .title = Prepnúť na kartu Pošta
toolbar-print-label = Tlačiť
toolbar-print =
    .title = Vytlačiť vybranú správu
toolbar-quick-filter-bar-label = Rýchly filter
toolbar-quick-filter-bar =
    .title = Umožní filtrovanie správ
toolbar-synchronize-label = Synchronizovať
toolbar-synchronize =
    .title = Znova načítať obsah kalendárov a synchronizovať zmeny
toolbar-delete-event-label = Odstrániť
toolbar-delete-event =
    .title = Odstrániť zvolené udalosti alebo úlohy
toolbar-go-to-today-label = Prejsť na dnešný deň
toolbar-go-to-today =
    .title = Prejsť na dnešný deň
toolbar-print-event-label = Tlačiť
toolbar-print-event =
    .title = Vytlačiť udalosti alebo úlohy
toolbar-new-event-label = Udalosť
toolbar-new-event =
    .title = Vytvoriť novú udalosť
toolbar-new-task-label = Úloha
toolbar-new-task =
    .title = Vytvoriť novú úlohu
toolbar-go-back-label = Prejsť naspäť
toolbar-go-back =
    .title = Prejsť o jednu správu naspäť
toolbar-go-forward-label = Prejsť dopredu
toolbar-go-forward =
    .title = Prejsť o jednu správu dopredu
toolbar-stop-label = Zastaviť
toolbar-stop =
    .title = Zastaviť aktuálny prenos
toolbar-throbber-label = Indikátor činnosti
toolbar-throbber =
    .title = Indikátor činnosti
toolbar-create-contact-label = Nový kontakt
toolbar-create-contact =
    .title = Vytvoriť nový kontakt
toolbar-create-address-book-label = Nový adresár
toolbar-create-address-book =
    .title = Vytvoriť nový adresár
toolbar-create-list-label = Nový zoznam
toolbar-create-list =
    .title = Vytvoriť nový rozosielací zoznam
toolbar-import-contacts-label = Importovať
toolbar-import-contacts =
    .title = Importovať kontakty zo súboru

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Pridať lokálny adresár
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Pridať adresár typu CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Pridať adresár LDAP
