# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Iruzkina
calendar-item-summary-title = Izenburua:
calendar-item-summary-calendar = Egutegia:
calendar-item-summary-task-start = Hasiera-data:
calendar-item-summary-event-start = Hasiera-data:
calendar-item-summary-task-due = Muga-data:
calendar-item-summary-event-end = Amaiera-data:
calendar-item-summary-repeat = Errepikatu:
calendar-item-summary-location = Kokalekua:
calendar-item-summary-category = Kategoria:
calendar-item-summary-organizer = Antolatzailea:
calendar-item-summary-status = Egoera:
calendar-item-summary-reminder = Gogoratu:
calendar-item-summary-attachments = Eranskinak:
calendar-item-summary-status-tentative = Saiakera
calendar-item-summary-status-confirmed = Berretsia
calendar-item-summary-event-status-cancelled = Utzia
calendar-item-summary-todo-status-cancelled = Utzia
calendar-item-summary-status-needs-action = Ekintza beharrean
calendar-item-summary-status-in-process = Prozesuan
calendar-item-summary-status-completed = Noiz osatuko
calendar-item-summary-reminder-none =
    .label = Ez gogoratu
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutu lehenago
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutu lehenago
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutu lehenago
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutu lehenago
calendar-item-summary-reminder-1-hour-before =
    .label = ordu 1 lehenago
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ordu lehenago
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ordu lehenago
calendar-item-summary-reminder-1-day-before =
    .label = egun 1 lehenago
calendar-item-summary-reminder-2-days-before =
    .label = 2 egun lehenago
calendar-item-summary-reminder-1-week-before =
    .label = aste 1 lehenago
calendar-item-summary-reminder-custom =
    .label = Pertsonalizatua…
calendar-item-summary-reminder-multiple =
    .value = Gogorarazle anitz…
calendar-item-summary-general =
    .value = Orokorra
calendar-item-summary-attendees =
    .value = Partaideak
calendar-item-summary-description =
    .value = Azalpena
calendar-item-summary-link =
    .value = Erlazionatutako lotura
