# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Num per mussar
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tip
vcard-entry-type-home = Privat
vcard-entry-type-work = Lavur
vcard-entry-type-none = Nagin
vcard-entry-type-custom = Persunalisà
vcard-name-header = Num
vcard-n-prefix = Prefix
vcard-n-add-prefix =
    .title = Agiuntar in prefix
vcard-n-firstname = Prenum
vcard-n-add-firstname =
    .title = Agiuntar in prenum
vcard-n-middlename = Segund prenum
vcard-n-add-middlename =
    .title = Agiuntar in segund prenum
vcard-n-lastname = Num
vcard-n-add-lastname =
    .title = Agiuntar in num da famiglia
vcard-n-suffix = Suffix
vcard-n-add-suffix =
    .title = Agiuntar in suffix
vcard-nickname = Surnum
vcard-email-header = Adressas dad e-mail
vcard-email-add = Agiuntar ina adressa dad e-mail
vcard-email-label = Adressa dad e-mail
vcard-primary-email-label = Standard
vcard-url-header = Websites
vcard-url-add = Agiuntar ina website
vcard-url-label = Website
vcard-tel-header = Numers da telefon
vcard-tel-add = Agiuntar in numer da telefon
vcard-tel-label = Numer da telefon
# Or "Mobile"
vcard-entry-type-cell = Telefonin
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pager
vcard-tz-header = Zona d'urari
vcard-tz-add = Agiuntar ina zona d'urari
vcard-impp2-header = Messadis immediats
vcard-impp-add = Agiuntar in conto da chat
vcard-impp-label = Conto da chat
vcard-impp-select = Protocol
vcard-impp-option-other = Auter
vcard-impp-input-label = URI
vcard-impp-input-title = URI per messadis immediats
vcard-bday-anniversary-header = Datas spezialas
vcard-bday-anniversary-add = Agiuntar ina data speziala
vcard-bday-label = Di da naschientscha
vcard-anniversary-label = Anniversari
vcard-date-day = Di
vcard-date-month = Mais
vcard-date-year = Onn
vcard-adr-header = Adressas
vcard-adr-add = Agiuntar ina adressa
vcard-adr-label = Adressa
vcard-adr-delivery-label = Etichetta da spediziun
vcard-adr-street = Adressa postala
# Or "Locality"
vcard-adr-locality = Lieu
# Or "Region"
vcard-adr-region = Stadi/provinza
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Numer postal
vcard-adr-country = Pajais
vcard-note-header = Notizias
vcard-note-add = Agiuntar ina notizia
vcard-org-header = Infurmaziuns da l'organisaziun
vcard-org-add = Agiuntar infurmaziuns da l'organisaziun
vcard-org-title = Titel
vcard-org-title-input =
    .placeholder = Designaziun da la professiun
    .title = Posiziun u lavur
vcard-org-role = Rolla
vcard-org-role-input =
    .placeholder = Rolla en in project
    .title = Funcziun u rolla en ina situaziun specifica
vcard-org-org = Organisaziun
vcard-org-org-input =
    .placeholder = Num da l'interpresa
    .title = Num da l'organisaziun
vcard-org-org-unit = Partiziun
vcard-org-org-unit-input =
    .placeholder = Partiziun
    .title = Num da l'unitad da l'organisaziun
vcard-custom-header = Caracteristicas persunalisadas
vcard-custom-add = Agiuntar caracteristicas persunalisadas
vcard-remove-button-title =
    .title = Allontanar
vcard-remove-button = Allontanar
