# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Emër në ekran
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Lloj
vcard-entry-type-home = Shtëpie
vcard-entry-type-work = Pune
vcard-entry-type-none = Asnjë
vcard-entry-type-custom = Vetjake
vcard-name-header = Emër
vcard-n-prefix = Parashtesë
vcard-n-add-prefix =
    .title = Shtoni parashtesë
vcard-n-firstname = Emër
vcard-n-add-firstname =
    .title = Shtoni emër
vcard-n-middlename = Emër i mesit
vcard-n-add-middlename =
    .title = Shtoni emër të mesit
vcard-n-lastname = Mbiemër
vcard-n-add-lastname =
    .title = Shtoni mbiemër
vcard-n-suffix = Prapashtesë
vcard-n-add-suffix =
    .title = Shtoni prapashtesë
vcard-nickname = Nofkë
vcard-email-header = Adresa Email
vcard-email-add = Shtoni adresë email
vcard-email-label = Adresë email
vcard-primary-email-label = Parazgjedhje
vcard-url-header = Sajte
vcard-url-add = Shtoni sajt
vcard-url-label = Sajt
vcard-tel-header = Numra Telefonash
vcard-tel-add = Shtoni numër telefoni
vcard-tel-label = Numër telefoni
# Or "Mobile"
vcard-entry-type-cell = Celular
vcard-entry-type-fax = Faks
vcard-entry-type-pager = Faques
vcard-tz-header = Zonë Kohore
vcard-tz-add = Shtoni zonë kohore
vcard-impp2-header = Shkëmbim Mesazhesh të Atypëratyshëm
vcard-impp-add = Shtoni llogari fjalosjeje
vcard-impp-label = Llogari fjalosjeje
vcard-impp-select = Protokoll
vcard-impp-option-other = Tjetër
vcard-impp-input-label = URI
vcard-impp-input-title = URI për shkëmbim mesazhesh të atypëratyshëm
vcard-bday-anniversary-header = Data të Veçanta
vcard-bday-anniversary-add = Shtoni një datë të veçantë
vcard-bday-label = Datëlindje
vcard-anniversary-label = Përvjetor
vcard-date-day = Ditë
vcard-date-month = Muaj
vcard-date-year = Vit
vcard-adr-header = Adresa
vcard-adr-add = Shtoni adresë
vcard-adr-label = Adresë
vcard-adr-delivery-label = Etiketë dërgim
vcard-adr-street = Rrugë
# Or "Locality"
vcard-adr-locality = Qytet
# Or "Region"
vcard-adr-region = Shtet/Provincë
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Kod ZIP/Postar
vcard-adr-country = Vend
vcard-note-header = Shënime
vcard-note-add = Shtoni shënim
vcard-org-header = Veti Në Organikë
vcard-org-add = Shtoni veti organike
vcard-org-title = Titull
vcard-org-title-input =
    .placeholder = Emër vendi pune
    .title = Post ose vend pune
vcard-org-role = Rol
vcard-org-role-input =
    .placeholder = Roli në një projekt
    .title = Funksion ose pjesë që luan në një situatë të dhënë
vcard-org-org = Ent
vcard-org-org-input =
    .placeholder = Emër shoqërie
    .title = Emër në organikë
vcard-org-org-unit = Degë
vcard-org-org-unit-input =
    .placeholder = Degë
    .title = Emër i njësisë në organikë
vcard-custom-header = Veti Vetjake
vcard-custom-add = Shtoni veti vetjake
vcard-remove-button-title =
    .title = Hiqe
vcard-remove-button = Hiqe
