# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Megjelenő név
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Típus
vcard-entry-type-home = Otthoni
vcard-entry-type-work = Munkahelyi
vcard-entry-type-none = Nincs
vcard-entry-type-custom = Egyéni
vcard-name-header = Név
vcard-n-prefix = Előtag
vcard-n-add-prefix =
    .title = Előtag hozzáadása
vcard-n-firstname = Utónév
vcard-n-add-firstname =
    .title = Utónév hozzáadása
vcard-n-middlename = Egyéb név
vcard-n-add-middlename =
    .title = Egyéb név hozzáadása
vcard-n-lastname = Vezetéknév
vcard-n-add-lastname =
    .title = Vezetéknév hozzáadása
vcard-n-suffix = Utótag
vcard-n-add-suffix =
    .title = Utótag hozzáadása
vcard-nickname = Becenév
vcard-email-header = E-mail-címek
vcard-email-add = E-mail-cím hozzáadása
vcard-email-label = E-mail-cím
vcard-primary-email-label = Alapértelmezett
vcard-url-header = Webhelyek
vcard-url-add = Webhely hozzáadása
vcard-url-label = Webhely
vcard-tel-header = Telefonszámok
vcard-tel-add = Telefonszám hozzáadása
vcard-tel-label = Telefonszám
# Or "Mobile"
vcard-entry-type-cell = Cella
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Személyhívó
vcard-tz-header = Időzóna
vcard-tz-add = Időzóna hozzáadása
vcard-impp2-header = Azonnali üzenetküldés
vcard-impp-add = Csevegőfiók hozzáadása
vcard-impp-label = Csevegőfiók
vcard-impp-select = Protokoll
vcard-impp-option-other = Egyéb
vcard-impp-input-label = URI
vcard-impp-input-title = Azonnali üzenetküldés URI-ja
vcard-bday-anniversary-header = Különleges dátumok
vcard-bday-anniversary-add = Különleges dátum hozzáadása
vcard-bday-label = Születésnap
vcard-anniversary-label = Évforduló
vcard-date-day = Nap
vcard-date-month = Hónap
vcard-date-year = Év
vcard-adr-header = Címek
vcard-adr-add = Cím hozzáadása
vcard-adr-label = Cím
vcard-adr-delivery-label = Szállítási címke
vcard-adr-street = Utca, házszám
# Or "Locality"
vcard-adr-locality = Város
# Or "Region"
vcard-adr-region = Állam/tartomány
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Irányítószám
vcard-adr-country = Ország
vcard-note-header = Megjegyzés
vcard-note-add = Megjegyzés hozzáadása
vcard-org-header = Szervezeti tulajdonságok
vcard-org-add = Szervezeti tulajdonságok hozzáadása
vcard-org-title = Beosztás
vcard-org-title-input =
    .placeholder = Munkakör neve
    .title = Beosztás vagy munkakör
vcard-org-role = Szerep
vcard-org-role-input =
    .placeholder = Szerepkör a projektben
    .title = Egy adott helyzetben játszott funkció vagy szerepkör
vcard-org-org = Szervezet
vcard-org-org-input =
    .placeholder = Cégnév
    .title = Szervezet neve
vcard-org-org-unit = Részleg
vcard-org-org-unit-input =
    .placeholder = Részleg
    .title = Szervezeti egység neve
vcard-custom-header = Egyéni tulajdonságok
vcard-custom-add = Egyéni tulajdonságok hozzáadása
vcard-remove-button-title =
    .title = Eltávolítás
vcard-remove-button = Eltávolítás
