# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Parametros offline
autodetect-connection-label =
    .label = Automaticamente cambiar modos quando un connexion a internet es trovate
    .accesskey = t
offline-startup-label = Aperiente { -brand-short-name }:
status-radio-last-used =
    .label = Usar le ultime modo de connexion usate
    .accesskey = U
status-radio-ask-connect =
    .label = Demandar si connecter al rete
    .accesskey = m
status-radio-start-online =
    .label = Initiar connexe al rete
    .accesskey = I
status-radio-start-offline =
    .label = Initiar sin connexion
    .accesskey = s
going-online-prompt = Inviar messages attendente in tu cassa de exito
going-online-send =
    .label = Si, inviar automaticamente
    .accesskey = S
going-online-keep =
    .label = No, mantener in cassa de exito
    .accesskey = N
going-online-ask-send =
    .label = Demandar ante inviar
    .accesskey = D
going-offline-prompt = Vole tu discargar messages a leger sin connexion?
going-offline-download =
    .label = Si, discargar automaticamente
    .accesskey = i
going-offline-keep =
    .label = No, non discargar
    .accesskey = o
going-offline-ask-download =
    .label = Demandar ante discargar
    .accesskey = e
autodetect-online-label =
    .label = Passar automaticamente al stato in linea
    .accesskey = P
offline-preference-startup-label = Stato manual al initio:
status-radio-remember =
    .label = Rememorar le stato in linea previe
    .accesskey = R
status-radio-ask =
    .label = Demandar me pro stato in linea
    .accesskey = D
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Foras de linea
    .accesskey = o
going-online-label = Inviar le messages non inviate quando se passa al modo in linea?
going-online-auto =
    .label = Si
    .accesskey = S
going-online-not =
    .label = No
    .accesskey = N
going-online-ask =
    .label = Demandar me
    .accesskey = D
going-offline-label = Discargar messages pro uso sin connexion al disconnexion?
going-offline-auto =
    .label = Si
    .accesskey = S
going-offline-not =
    .label = No
    .accesskey = N
going-offline-ask =
    .label = Demandar me
    .accesskey = D
