# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Receptas de retorno
return-receipt-checkbox-control =
    .label = Quando se invia messages, sempre demandar un recepta de retorno
    .accesskey = Q
receipt-arrive-label = Quando un recepta arriva:
receipt-leave-inbox-control =
    .label = Lassar in Cassa de entrata
    .accesskey = i
receipt-move-sent-control =
    .label = Mover verso le plica Inviate
    .accesskey = v
receipt-sender-request-label = Quando un expeditor require un quitantia de retorno:
receipt-leave-radio-control =
    .label = Lassar lo in mi cassa de entrata
    .accesskey = i
receipt-move-radio-control =
    .label = Displaciar lo a mi dossier “Inviate”
    .accesskey = m
receipt-request-label = Quando io recipe un demanda de recepta:
receipt-return-never-radio-control =
    .label = Nunquam retornar un recepta
    .accesskey = n
receipt-return-some-radio-control =
    .label = Permitter receptas de retorno pro alcun messages
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Si non listate in le campos A o CC:
    .accesskey = c
receipt-not-to-cc-label =
    .value = Si mi adresse non es in le campo A o CC del message:
    .accesskey = i
receipt-send-never-label =
    .label = Nunquam inviar
receipt-send-always-label =
    .label = Sempre inviar
receipt-send-ask-label =
    .label = Demandar me
sender-outside-company-label =
    .value = Si le expeditor es foras del compania o dominio:
    .accesskey = t
sender-outside-domain-label =
    .value = Si le mittente es externe a mi dominio:
    .accesskey = l
other-cases-text-label =
    .value = In tote le altere casos:
    .accesskey = t
read-receipts-dialog-title = Lege quitantias
return-receipt-request-control =
    .label = Sempre pete un quitantia de retorno inviante e-mails
    .accesskey = p
