# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Markera alla
select-none-calendars = Markera ingen
calendar-creation-wizard-title = Skapa ny kalender
calendar-creation-initial-description = Din kalender kan lagras på din dator eller på en server för att du ska kunna komma åt den på distans eller dela den med dina vänner eller kollegor.
calendar-creation-initial-computer =
    .label = På min dator
calendar-creation-initial-network =
    .label = På nätverket
calendar-creation-username =
    .value = Användarnamn:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Skapa kalender
    .buttonaccesskeyaccept = k
    .buttonlabelextra2 = Tillbaka
    .buttonaccesskeyextra2 = T
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Skapa kalender
    .buttonaccesskeyaccept = k
    .buttonlabelextra2 = Tillbaka
    .buttonaccesskeyextra2 = T
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Hitta kalendrar
    .buttonaccesskeyaccept = H
    .buttonlabelextra2 = Tillbaka
    .buttonaccesskeyextra2 = T
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Prenumerera
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Tillbaka
    .buttonaccesskeyextra2 = T
calendar-creation-type =
    .value = Kalendertyp:
calendar-creation-location =
    .value = Plats:
calendar-creation-location-placeholder =
    .placeholder = URL eller värdnamn för kalenderservern
    .default-placeholder = URL eller värdnamn för kalenderservern
calendar-creation-network-nocredentials =
    .label = Denna plats kräver inte inloggningsuppgifter
calendar-creation-network-loading = Var god vänta medan dina kalendrar undersöks.
calendar-creation-network-notfound = Kunde inte hitta kalendrar på den här platsen. Kontrollera dina inställningar.
calendar-creation-network-authfail = De inloggningsuppgifter du angav godkändes inte. Kontrollera dina inställningar.
calendar-creation-network-certerror = Det gick inte att hitta kalendrar på den här platsen på grund av ett certifikatproblem.
calendar-creation-network-subscribe-single = Välj de kalendrar du vill prenumerera på.
calendar-creation-network-subscribe-multiple = Flera kalendertyper är tillgängliga för den här platsen. Välj kalendertyp och markera sedan de kalendrar du vill prenumerera på.
