# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Kommentar
calendar-item-summary-title = Titel:
calendar-item-summary-calendar = Kalender:
calendar-item-summary-task-start = Start datum:
calendar-item-summary-event-start = Start datum:
calendar-item-summary-task-due = Förfallodatum:
calendar-item-summary-event-end = Slut datum:
calendar-item-summary-repeat = Repetera:
calendar-item-summary-location = Plats:
calendar-item-summary-category = Kategori:
calendar-item-summary-organizer = Organisatör:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Påminnelse:
calendar-item-summary-attachments = Bilagor:
calendar-item-summary-status-tentative = Preliminär
calendar-item-summary-status-confirmed = Bekräftad
calendar-item-summary-event-status-cancelled = Avbruten
calendar-item-summary-todo-status-cancelled = Avbruten
calendar-item-summary-status-needs-action = En åtgärd krävs
calendar-item-summary-status-in-process = Pågående
calendar-item-summary-status-completed = Avslutad
calendar-item-summary-reminder-none =
    .label = Ingen påminnelse
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuter före
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuter före
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuter före
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuter före
calendar-item-summary-reminder-1-hour-before =
    .label = 1 timme före
calendar-item-summary-reminder-2-hours-before =
    .label = 2 timme före
calendar-item-summary-reminder-12-hours-before =
    .label = 12 timmar före
calendar-item-summary-reminder-1-day-before =
    .label = 1 dag före
calendar-item-summary-reminder-2-days-before =
    .label = 2 dagar före
calendar-item-summary-reminder-1-week-before =
    .label = 1 vecka före
calendar-item-summary-reminder-custom =
    .label = Anpassad…
calendar-item-summary-reminder-multiple =
    .value = Flera påminnelser…
calendar-item-summary-general =
    .value = Allmänt
calendar-item-summary-attendees =
    .value = Deltagare
calendar-item-summary-description =
    .value = beskrivning
calendar-item-summary-link =
    .value = Liknande länk
