# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Bistaratzeko izena
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Mota
vcard-entry-type-home = Etxea
vcard-entry-type-work = Lana
vcard-entry-type-none = Bat ere ez
vcard-entry-type-custom = Pertsonalizatua
vcard-name-header = Izena
vcard-n-prefix = Aurrizkia
vcard-n-add-prefix =
    .title = Gehitu aurrizkia
vcard-n-firstname = Izena
vcard-n-add-firstname =
    .title = Gehitu izena
vcard-n-middlename = Bigarren izena
vcard-n-add-middlename =
    .title = Gehitu bigarren izena
vcard-n-lastname = Abizenak
vcard-n-add-lastname =
    .title = Gehitu abizenak
vcard-n-suffix = Atzizkia
vcard-n-add-suffix =
    .title = Gehitu atzizkia
vcard-nickname = Goitizena
vcard-email-header = Helbide elektronikoak
vcard-email-add = Gehitu helbide elektronikoa
vcard-email-label = Helbide elektronikoa
vcard-primary-email-label = Lehenetsia
vcard-url-header = Webguneak
vcard-url-add = Gehitu webgunea
vcard-url-label = Webgunea
vcard-tel-header = Telefono zenbakiak
vcard-tel-add = Gehitu telefono zenbakia
vcard-tel-label = Telefono zenbakia
# Or "Mobile"
vcard-entry-type-cell = Mugikorra
vcard-entry-type-fax = Faxa
vcard-entry-type-pager = Bilagailua
vcard-tz-header = Ordu-zona
vcard-tz-add = Gehitu ordu-zona
vcard-impp2-header = Berehalako mezularitza
vcard-impp-add = Gehitu txat-kontua
vcard-impp-label = Txat-kontua
vcard-impp-select = Protokoloa
vcard-impp-option-other = Bestelakoak
vcard-impp-input-label = URI
vcard-impp-input-title = URI berehalako mezularitzan
vcard-bday-anniversary-header = Data bereziak
vcard-bday-anniversary-add = Gehitu data berezia
vcard-bday-label = Urtebetetzea
vcard-anniversary-label = Urteurrena
vcard-date-day = Eguna
vcard-date-month = Hilabetea
vcard-date-year = Urtea
vcard-adr-header = Helbideak
vcard-adr-add = Gehitu helbidea
vcard-adr-label = Helbidea
vcard-adr-delivery-label = Entrega etiketa
vcard-adr-street = Helbideko kalea
# Or "Locality"
vcard-adr-locality = Hiria
# Or "Region"
vcard-adr-region = Estatua/probintzia
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = ZIP/Posta Kodea:
vcard-adr-country = Herrialdea
vcard-note-header = Oharrak
vcard-note-add = Gehitu oharra
vcard-org-header = Erakundearen propietateak
vcard-org-add = Gehitu erakundearen propietateak
vcard-org-title = Izenburua
vcard-org-title-input =
    .placeholder = Lan izendapena
    .title = Kargua edo lana
vcard-org-role = Rola
vcard-org-role-input =
    .placeholder = Funtzioa proiektuan
    .title = Funtzioa edo egoera berezian jokatutako papera
vcard-org-org = Erakundea
vcard-org-org-input =
    .placeholder = Konpainia izena
    .title = Erakundearen izena
vcard-org-org-unit = Saila
vcard-org-org-unit-input =
    .placeholder = Saila
    .title = Erakundearen atal izena
vcard-custom-header = Propietate pertsonalizatuak
vcard-custom-add = Gehitu propietate pertsonalizatuak
vcard-remove-button-title =
    .title = Kendu
vcard-remove-button = Kendu
