# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Nombre para mostrar
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tipo
vcard-entry-type-home = Casa
vcard-entry-type-work = Trabajo
vcard-entry-type-none = Ninguno
vcard-entry-type-custom = Personalizado
vcard-name-header = Nombre
vcard-n-prefix = Prefijo
vcard-n-add-prefix =
    .title = Agregar prefijo
vcard-n-firstname = Primer nombre
vcard-n-add-firstname =
    .title = Agregar primer nombre
vcard-n-middlename = Segundo nombre
vcard-n-add-middlename =
    .title = Agregar segundo nombre
vcard-n-lastname = Apellido
vcard-n-add-lastname =
    .title = Agregar apellido
vcard-n-suffix = Sufijo
vcard-n-add-suffix =
    .title = Agregar sufijo
vcard-nickname = Nombre de usuario
vcard-email-header = Direcciones de correo
vcard-email-add = Agregar dirección de correo
vcard-email-label = Dirección de correo
vcard-primary-email-label = Predeterminado
vcard-url-header = Sitios web
vcard-url-add = Agregar sitio web
vcard-url-label = Sitio web
vcard-tel-header = Números de teléfono
vcard-tel-add = Agregar número de teléfono
vcard-tel-label = Número de teléfono
# Or "Mobile"
vcard-entry-type-cell = Celda
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Localizador
vcard-tz-header = Zona horaria
vcard-tz-add = Agregar zona horaria
vcard-impp2-header = Mensajería instantánea
vcard-impp-add = Agregar cuenta de chat
vcard-impp-label = Cuenta de chat
vcard-impp-select = Protocolo
vcard-impp-option-other = Otros
vcard-impp-input-label = URI
vcard-impp-input-title = URI para mensajería instantánea
vcard-bday-anniversary-header = Fechas especiales
vcard-bday-anniversary-add = Agregar fecha especial
vcard-bday-label = Cumpleaños
vcard-anniversary-label = Aniversario
vcard-date-day = Día
vcard-date-month = Mes
vcard-date-year = Año
vcard-adr-header = Direcciones
vcard-adr-add = Agregar dirección
vcard-adr-label = Dirección
vcard-adr-delivery-label = Etiqueta de entrega
vcard-adr-street = Dirección de la calle
# Or "Locality"
vcard-adr-locality = Ciudad
# Or "Region"
vcard-adr-region = Estado/Provincia
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Código Postal
vcard-adr-country = País
vcard-note-header = Notas
vcard-note-add = Agregar nota
vcard-org-header = Propiedades de organización
vcard-org-add = Agregar propiedad de organización
vcard-org-title = Título
vcard-org-title-input =
    .placeholder = Titulo de trabajo
    .title = Puesto o trabajo
vcard-org-role = Rol
vcard-org-role-input =
    .placeholder = Rol en un proyecto
    .title = Función o papel que desempeñas en una situación particular
vcard-org-org = Organización
vcard-org-org-input =
    .placeholder = Nombre de la empresa
    .title = Nombre de la organización
vcard-org-org-unit = Departamento
vcard-org-org-unit-input =
    .placeholder = Departamento
    .title = Nombre Unidad Organizacional
vcard-custom-header = Propiedades personalizadas
vcard-custom-add = Agregar propiedades personalizadas
vcard-remove-button-title =
    .title = Eliminar
vcard-remove-button = Eliminar
