# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Jalel Rukojol
toolbar-write-message-label = Titz'ib'äx
toolbar-write-message =
    .title = Titz'uk jun k'ak'a' tzijol
toolbar-unifinder-label = Kekanöx taq Molojri'ïl
toolbar-unifinder =
    .title = Tijalwachij ri panel richin tikanoj molojri'ïl
toolbar-folder-location-label = Ruk'ojlib'al Yakwuj
toolbar-get-messages-label = Tik'ul Rutzijol
toolbar-reply-label = Titzolïx tzij
toolbar-reply =
    .title = Titzolïx tzij chi re ri rutzijol
toolbar-reply-all-label = Titzolïx tzij chi ke Konojel
toolbar-reply-all =
    .title = Titzolïx tzij chi re ri taqonel chuqa' chi ke konojel ri ruk'ulb'anela' tzij
toolbar-reply-to-list-label = Titzolïx tzij chi re ri Cholb'äl
toolbar-reply-to-list =
    .title = Titzolïx tzij chi re jun kicholb'al taqotz'ib'
toolbar-archive-label = Yakb'äl
toolbar-archive =
    .title = Keyak cha'on taq tzijol
toolbar-conversation-label = Tzijonem
toolbar-conversation =
    .title = Tik'ut rutzijonem cha'on tzijol
toolbar-previous-unread-label = Chuwäch Man Sik'in Ta
toolbar-previous-unread =
    .title = Tisilöx pa ri jun kan rutzijol man sik'in ta
toolbar-previous-label = Jun kan
toolbar-previous =
    .title = Tisilöx pa ri jun kan rutzijol
toolbar-next-unread-label = Jun chik Man Sik'in Ta
toolbar-next-unread =
    .title = Tisilöx pa ri jun chik rutzijol man sik'in ta
toolbar-next-label = Jun chik
toolbar-next =
    .title = Tisilöx pa ri jun chik rutzijol
toolbar-compact-label = Tz'aqatz'öj
toolbar-compact =
    .title = Keyuj yujun taq tzijol pa ri ruyakwuj xcha'
toolbar-add-as-event-label = Titz'aqatisäx achi'el nimaq'ij
toolbar-add-as-task-label = Titz'aqatisäx achi'el samaj
toolbar-tag-message-label = Etal
toolbar-tag-message =
    .title = Ketal taq rutzijol
toolbar-forward-inline-label = Jun chik
toolbar-forward-inline =
    .title = Titaq chik ri cha'on rutzijol achi'el tz'aqatisan cholan tzij
toolbar-forward-attachment-label = Titaq chik Achi'el Taqoj
toolbar-forward-attachment =
    .title = Titaq chik ri cha'on rutzijol achi'el jun taqoj
toolbar-mark-as-label = Tiya' retal
toolbar-mark-as =
    .title = Tiya' ketal taq tzijol
toolbar-address-book =
    .title = Tib'e pa ri kiwujil ochochib'äl
toolbar-chat-label = Chat
toolbar-chat =
    .title = Tik'ut ri Chat tab
toolbar-print-label = Titz'ajb'äx
toolbar-print =
    .title = Titz'ajb'äx re rutzijol re'
toolbar-go-back-label = Chi rij
toolbar-go-back =
    .title = Titzolïx jun rutzijol
toolbar-go-forward-label = Jun chik
toolbar-go-forward =
    .title = Jun chik rutzijol
toolbar-stop-label = Tiq'at
toolbar-stop =
    .title = Tiq'at ri q'axanïk wakami
toolbar-throbber-label = K'utunel Samaj
toolbar-throbber =
    .title = K'utunel Samaj
