# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Hapësirë e Lakueshme
search-bar-label = Kërko
toolbar-write-message-label = Shkruani
toolbar-write-message =
    .title = Krijoni mesazh të ri
toolbar-move-to-label = Shpjere te
toolbar-move-to =
    .title = Lëviz mesazhin e përzgjedhur
toolbar-unifinder-label = Gjeni Veprimtari
toolbar-unifinder =
    .title = Hapni/mbyllni kuadratin e gjetjes së veprimtarive
toolbar-folder-location-label = Vend Dosjeje
toolbar-folder-location =
    .title = Kalo në dosje
toolbar-edit-event-label = Përpunojeni
toolbar-edit-event =
    .title = Përpunoni veprimtari ose punë të përzgjedhura
toolbar-get-messages-label = Merr Mesazhet
toolbar-get-messages =
    .title = Sill mesazhe të rinj për krejt llogaritë
toolbar-reply-label = Përgjigju
toolbar-reply =
    .title = Përgjigjiuni mesazhit
toolbar-reply-all-label = Përgjigjiuni të Tërëve
toolbar-reply-all =
    .title = Përgjigjiuni dërguesit dhe tërë marrësve
toolbar-reply-to-list-label = Përgjigjuni te Lista
toolbar-reply-to-list =
    .title = Përgjigjuni te lista e postimeve
toolbar-redirect-label = Ridrejtoje
toolbar-redirect =
    .title = Ridrejto mesazhin e përzgjedhur
toolbar-archive-label = Arkivoje
toolbar-archive =
    .title = Mesazhe të përzgjedhur në arkiv
toolbar-conversation-label = Bisedë
toolbar-conversation =
    .title = Shfaq bisedën e mesazhit të përzgjedhur
toolbar-previous-unread-label = I palexuari i Mëparshëm
toolbar-previous-unread =
    .title = Kaloni te mesazhi i mëparshëm i palexuar
toolbar-previous-label = I mëparshmi
toolbar-previous =
    .title = Kaloni te mesazhi i mëparshëm
toolbar-next-unread-label = I palexuari Pasues
toolbar-next-unread =
    .title = Kaloni te mesazhi i palexuar pasues
toolbar-next-label = Pasuesi
toolbar-next =
    .title = Kaloni te mesazhi pasues
toolbar-junk-label = I pavlerë
toolbar-junk =
    .title = Vëri shenjë si i pavlerë mesazhit të përzgjedhur
toolbar-delete-label = Fshije
toolbar-delete-title =
    .title = Fshiji mesazhet e përzgjedhur
toolbar-undelete-label = Çfshije
toolbar-undelete =
    .title = Rikthe mesazhet e përzgjedhur
toolbar-compact-label = Ngjeshe
toolbar-compact =
    .title = Hiqini mesazhet e fshirë prej dosjes së përzgjedhur
toolbar-add-as-event-label = Shtoje si Veprimtari
toolbar-add-as-event =
    .title = Përftoni nga mesazhi të dhëna kalendarike dhe shtojini ato te kalendari juaj si një veprimtari
toolbar-add-as-task-label = Shtoje si Punë
toolbar-add-as-task =
    .title = Përftoni nga mesazhi të dhëna kalendarike dhe shtojini ato te kalendari juaj si një punë
toolbar-tag-message-label = Etiketë
toolbar-tag-message =
    .title = Etiketoni mesazhe
toolbar-forward-inline-label = Përcille
toolbar-forward-inline =
    .title = Përcille mesazhin e përzgjedhur si tekst brendazi
toolbar-forward-attachment-label = Përcille Si Bashkëngjitje
toolbar-forward-attachment =
    .title = Përcille mesazhin e përzgjedhur si një bashkëngjitje
toolbar-mark-as-label = Shënoje
toolbar-mark-as =
    .title = Shënoni mesazhe
toolbar-view-picker-label = Shisheni
toolbar-view-picker =
    .title = Përshtatni parjen e dosjes së tanishme
toolbar-address-book-label = Libër Adresash
toolbar-address-book =
    .title = Shkoni te libri i adresave
toolbar-chat-label = Fjalosje
toolbar-chat =
    .title = Shfaq skedën e Fjalosjeve
toolbar-add-ons-and-themes-label = Shtesa dhe Tema
toolbar-add-ons-and-themes =
    .title = Administroni shtesat tuaja
toolbar-calendar-label = Kalendar
toolbar-calendar =
    .title = Kaloni te skeda e kalendarit
toolbar-tasks-label = Punë
toolbar-tasks =
    .title = Kaloni te skeda e punëve
toolbar-mail-label = Postë
toolbar-mail =
    .title = Kalo te skeda e email-eve
toolbar-print-label = Shtype
toolbar-print =
    .title = Shtypeni këtë mesazh
toolbar-quick-filter-bar-label = Filtrim i Shpejtë
toolbar-quick-filter-bar =
    .title = Filtroni mesazhe
toolbar-synchronize-label = Njëkohësoje
toolbar-synchronize =
    .title = Ringarkoni kalendarë dhe njëkohësoni ndryshimet
toolbar-delete-event-label = Fshije
toolbar-delete-event =
    .title = Fshini veprimtari ose punë të përzgjedhura
toolbar-go-to-today-label = Shko te Sot
toolbar-go-to-today =
    .title = Shko te Sot
toolbar-print-event-label = Shtype
toolbar-print-event =
    .title = Shtypni veprimtari ose punë
toolbar-new-event-label = Veprimtari
toolbar-new-event =
    .title = Krijoni veprimtari të re
toolbar-new-task-label = Punë
toolbar-new-task =
    .title = Krijoni punë të re
toolbar-go-back-label = Mbrapsht
toolbar-go-back =
    .title = Kaloni një mesazh prapa
toolbar-go-forward-label = Përpara
toolbar-go-forward =
    .title = Kaloni një mesazh para
toolbar-stop-label = Ndale
toolbar-stop =
    .title = Ndalni shpërnguljen e tanishme
toolbar-throbber-label = Tregues Veprimtarie
toolbar-throbber =
    .title = Tregues Veprimtarie
toolbar-create-contact-label = Kontakt i Ri
toolbar-create-contact =
    .title = Krijoni kontakt të ri
toolbar-create-address-book-label = Libër i Ri Adresash
toolbar-create-address-book =
    .title = Krijoni libër të ri adresash
toolbar-create-list-label = Listë e Re
toolbar-create-list =
    .title = Krijoni një listë të re postimesh
toolbar-import-contacts-label = Importo
toolbar-import-contacts =
    .title = Importoni kontakte prej një kartele

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Shtoni Libër Vendor Adresash
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Shtoni Libër Adresash CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Shtoni Libër Adresash LDAP
