# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Alles selecteren
select-none-calendars = Niets selecteren
calendar-creation-wizard-title = Nieuwe agenda maken
calendar-creation-initial-description = Uw agenda kan op uw computer of op een server worden opgeslagen, zodat deze op afstand is te benaderen door vrienden of collega’s.
calendar-creation-initial-computer =
    .label = Op mijn computer
calendar-creation-initial-network =
    .label = Op het netwerk
calendar-creation-username =
    .value = Gebruikersnaam:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Agenda aanmaken
    .buttonaccesskeyaccept = m
    .buttonlabelextra2 = Terug
    .buttonaccesskeyextra2 = T
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Agenda aanmaken
    .buttonaccesskeyaccept = m
    .buttonlabelextra2 = Terug
    .buttonaccesskeyextra2 = T
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Agenda’s zoeken
    .buttonaccesskeyaccept = z
    .buttonlabelextra2 = Terug
    .buttonaccesskeyextra2 = T
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonneren
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Terug
    .buttonaccesskeyextra2 = T
calendar-creation-type =
    .value = Agendatype:
calendar-creation-location =
    .value = Locatie:
calendar-creation-location-placeholder =
    .placeholder = URL of hostnaam van de agendaserver
    .default-placeholder = URL of hostnaam van de agendaserver
calendar-creation-network-nocredentials =
    .label = Deze locatie vereist geen referenties
calendar-creation-network-loading = Even geduld, uw agenda’s worden gedetecteerd.
calendar-creation-network-notfound = Er zijn geen agenda’s op deze locatie gevonden. Controleer uw instellingen.
calendar-creation-network-authfail = De ingevoerde referenties werden niet geaccepteerd. Controleer uw instellingen.
calendar-creation-network-certerror = Kan geen agenda’s op deze locatie vinden, vanwege een certificaatprobleem.
calendar-creation-network-subscribe-single = Selecteer de agenda’s waarop u zich wilt abonneren.
calendar-creation-network-subscribe-multiple = Voor deze locatie zijn meerdere agendatypen beschikbaar. Selecteer het agendatype, en markeer daarna de agenda’s waarop u zich wilt abonneren.
