# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Opmerking
calendar-item-summary-title = Titel:
calendar-item-summary-calendar = Agenda:
calendar-item-summary-task-start = Begindatum:
calendar-item-summary-event-start = Begindatum:
calendar-item-summary-task-due = Einddatum:
calendar-item-summary-event-end = Einddatum:
calendar-item-summary-repeat = Herhalen:
calendar-item-summary-location = Locatie:
calendar-item-summary-category = Categorie:
calendar-item-summary-organizer = Organisator:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Herinnering:
calendar-item-summary-attachments = Bijlagen:
calendar-item-summary-status-tentative = Voorlopig
calendar-item-summary-status-confirmed = Bevestigd
calendar-item-summary-event-status-cancelled = Geannuleerd
calendar-item-summary-todo-status-cancelled = Geannuleerd
calendar-item-summary-status-needs-action = Handeling vereist
calendar-item-summary-status-in-process = Bezig
calendar-item-summary-status-completed = Voltooid op
calendar-item-summary-reminder-none =
    .label = Geen herinnering
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuten van tevoren
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuten van tevoren
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuten van tevoren
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuten van tevoren
calendar-item-summary-reminder-1-hour-before =
    .label = 1 uur van tevoren
calendar-item-summary-reminder-2-hours-before =
    .label = 2 uur van tevoren
calendar-item-summary-reminder-12-hours-before =
    .label = 12 uur van tevoren
calendar-item-summary-reminder-1-day-before =
    .label = 1 dag van tevoren
calendar-item-summary-reminder-2-days-before =
    .label = 2 dagen van tevoren
calendar-item-summary-reminder-1-week-before =
    .label = 1 week van tevoren
calendar-item-summary-reminder-custom =
    .label = Aangepast…
calendar-item-summary-reminder-multiple =
    .value = Meerdere herinneringen…
calendar-item-summary-general =
    .value = Algemeen
calendar-item-summary-attendees =
    .value = Genodigden
calendar-item-summary-description =
    .value = Beschrijving
calendar-item-summary-link =
    .value = Bijbehorende koppeling
