# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = is een herhalende gebeurtenis
header-isrepeating-task =
    .label = is een herhalende taak
header-containsrepeating-event =
    .label = bevat herhalende gebeurtenissen
header-containsrepeating-task =
    .label = bevat herhalende taken
header-containsrepeating-mixed =
    .label = bevat herhalende items van verschillend type
windowtitle-event-copy = Herhalende gebeurtenis kopiëren
windowtitle-task-copy = Herhalende taak kopiëren
windowtitle-mixed-copy = Herhalende items kopiëren
windowtitle-event-cut = Herhalende gebeurtenis knippen
windowtitle-task-cut = Herhalende taak knippen
windowtitle-mixed-cut = Herhalende items knippen
windowtitle-event-delete = Herhalende gebeurtenis verwijderen
windowtitle-task-delete = Herhalende taak verwijderen
windowtitle-mixed-delete = Herhalende items verwijderen
windowtitle-event-edit = Herhalende gebeurtenis bewerken
windowtitle-task-edit = Herhalende taak bewerken
windowtitle-mixed-edit = Herhalende items bewerken
windowtitle-multipleitems =
    .value = Geselecteerde items
button-single-occurrence-copy =
    .label = Alleen deze herhaling kopiëren
    .accesskey = d
button-single-occurrence-cut =
    .label = Alleen deze herhaling knippen
    .accesskey = d
button-single-occurrence-delete =
    .label = Alleen deze herhaling verwijderen
    .accesskey = d
button-single-occurrence-edit =
    .label = Alleen deze herhaling bewerken
    .accesskey = d
button-multiple-occurrence-copy =
    .label = Alleen geselecteerde herhalingen kopiëren
    .accesskey = d
button-multiple-occurrence-cut =
    .label = Alleen geselecteerde herhalingen knippen
    .accesskey = d
button-multiple-occurrence-delete =
    .label = Alleen geselecteerde herhalingen verwijderen
    .accesskey = d
button-multiple-occurrence-edit =
    .label = Alleen geselecteerde herhalingen bewerken
    .accesskey = d
button-single-allfollowing-copy =
    .label = Deze en alle volgende herhalingen kopiëren
    .accesskey = v
button-single-allfollowing-cut =
    .label = Deze en alle volgende herhalingen knippen
    .accesskey = v
button-single-allfollowing-delete =
    .label = Deze en alle volgende herhalingen verwijderen
    .accesskey = v
button-single-allfollowing-edit =
    .label = Deze en alle volgende herhalingen bewerken
    .accesskey = v
button-multiple-allfollowing-copy =
    .label = Geselecteerde en alle volgende herhalingen kopiëren
    .accesskey = v
button-multiple-allfollowing-cut =
    .label = Geselecteerde en alle volgende herhalingen knippen
    .accesskey = v
button-multiple-allfollowing-delete =
    .label = Geselecteerde en alle volgende herhalingen verwijderen
    .accesskey = v
button-multiple-allfollowing-edit =
    .label = Geselecteerde en alle volgende herhalingen bewerken
    .accesskey = v
button-single-parent-copy =
    .label = Alle herhalingen kopiëren
    .accesskey = A
button-single-parent-cut =
    .label = Alle herhalingen knippen
    .accesskey = A
button-single-parent-delete =
    .label = Alle herhalingen verwijderen
    .accesskey = A
button-single-parent-edit =
    .label = Alle herhalingen bewerken
    .accesskey = A
button-multiple-parent-copy =
    .label = Alle herhalingen van geselecteerde items kopiëren
    .accesskey = A
button-multiple-parent-cut =
    .label = Alle herhalingen van geselecteerde items knippen
    .accesskey = A
button-multiple-parent-delete =
    .label = Alle herhalingen van geselecteerde items verwijderen
    .accesskey = A
button-multiple-parent-edit =
    .label = Alle herhalingen van geselecteerde items bewerken
    .accesskey = A
buttons-single-occurrence-copy =
    .label = Alleen deze herhaling kopiëren
buttons-single-occurrence-cut =
    .label = Alleen deze herhaling knippen
buttons-single-occurrence-delete =
    .label = Alleen deze herhaling verwijderen
buttons-single-occurrence-edit =
    .label = Alleen deze herhaling bewerken
buttons-multiple-occurrence-copy =
    .label = Alleen geselecteerde herhalingen kopiëren
buttons-multiple-occurrence-cut =
    .label = Alleen geselecteerde herhalingen knippen
buttons-multiple-occurrence-delete =
    .label = Alleen geselecteerde herhalingen verwijderen
buttons-multiple-occurrence-edit =
    .label = Alleen geselecteerde herhalingen bewerken
buttons-single-allfollowing-copy =
    .label = Deze en alle volgende herhalingen kopiëren
buttons-single-allfollowing-cut =
    .label = Deze en alle volgende herhalingen knippen
buttons-single-allfollowing-delete =
    .label = Deze en alle volgende herhalingen verwijderen
buttons-single-allfollowing-edit =
    .label = Deze en alle volgende herhalingen bewerken
buttons-multiple-allfollowing-copy =
    .label = Geselecteerde en alle volgende herhalingen kopiëren
buttons-multiple-allfollowing-cut =
    .label = Geselecteerde en alle volgende herhalingen knippen
buttons-multiple-allfollowing-delete =
    .label = Geselecteerde en alle volgende herhalingen verwijderen
buttons-multiple-allfollowing-edit =
    .label = Geselecteerde en alle volgende herhalingen bewerken
buttons-single-parent-copy =
    .label = Alle herhalingen kopiëren
buttons-single-parent-cut =
    .label = Alle herhalingen knippen
buttons-single-parent-delete =
    .label = Alle herhalingen verwijderen
buttons-single-parent-edit =
    .label = Alle herhalingen bewerken
buttons-multiple-parent-copy =
    .label = Alle herhalingen van geselecteerde items kopiëren
buttons-multiple-parent-cut =
    .label = Alle herhalingen van geselecteerde items knippen
buttons-multiple-parent-delete =
    .label = Alle herhalingen van geselecteerde items verwijderen
buttons-multiple-parent-edit =
    .label = Alle herhalingen van geselecteerde items bewerken
