# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Näyttönimi
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Tyyppi
vcard-entry-type-home = Koti
vcard-entry-type-work = Työ
vcard-entry-type-none = Ei mitään
vcard-entry-type-custom = Mukautettu
vcard-name-header = Nimi
vcard-n-prefix = Etuliite
vcard-n-add-prefix =
    .title = Lisää etuliite
vcard-n-firstname = Etunimi
vcard-n-add-firstname =
    .title = Lisää etunimi
vcard-n-middlename = Toinen nimi
vcard-n-add-middlename =
    .title = Lisää toinen nimi
vcard-n-lastname = Sukunimi
vcard-n-add-lastname =
    .title = Lisää sukunimi
vcard-n-suffix = Jälkiliite
vcard-n-add-suffix =
    .title = Lisää jälkiliite
vcard-nickname = Kutsumanimi
vcard-email-header = Sähköpostiosoitteet
vcard-email-add = Lisää sähköpostiosoite
vcard-email-label = Sähköpostiosoite
vcard-primary-email-label = Oletus
vcard-url-header = Verkkosivustot
vcard-url-add = Lisää verkkosivusto
vcard-url-label = Verkkosivusto
vcard-tel-header = Puhelinnumerot
vcard-tel-add = Lisää puhelinnumero
vcard-tel-label = Puhelinnumero
# Or "Mobile"
vcard-entry-type-cell = Matkapuhelin
vcard-entry-type-fax = Faksi
vcard-entry-type-pager = Hakulaite
vcard-tz-header = Aikavyöhyke
vcard-tz-add = Lisää aikavyöhyke
vcard-impp2-header = Pikaviestintä
vcard-impp-add = Lisää pikaviestitili
vcard-impp-label = Pikaviestitili
vcard-impp-select = Yhteyskäytäntö
vcard-impp-option-other = Muu
vcard-impp-input-label = URI
vcard-impp-input-title = URI pikaviestintää varten
vcard-bday-anniversary-header = Erityiset päivät
vcard-bday-anniversary-add = Lisää erityinen päivä
vcard-bday-label = Syntymäpäivä
vcard-anniversary-label = Merkkipäivä
vcard-date-day = Päivä
vcard-date-month = Kuukausi
vcard-date-year = Vuosi
vcard-adr-header = Osoitteet
vcard-adr-add = Lisää osoite
vcard-adr-label = Osoite
vcard-adr-delivery-label = Toimitustarra
vcard-adr-street = Katuosoite
# Or "Locality"
vcard-adr-locality = Kaupunki
# Or "Region"
vcard-adr-region = Paikkakunta
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postinumero
vcard-adr-country = Maa
vcard-note-header = Huomautuksia
vcard-note-add = Lisää huomautus
vcard-org-header = Organisaation ominaisuudet
vcard-org-add = Lisää organisaation ominaisuuksia
vcard-org-title = Tehtävänimike
vcard-org-title-input =
    .placeholder = Tehtävänimike
    .title = Asema tai tehtävä
vcard-org-role = Rooli
vcard-org-role-input =
    .placeholder = Rooli projektissa
    .title = Tehtävä tai rooli tietyssä tilanteessa
vcard-org-org = Organisaatio
vcard-org-org-input =
    .placeholder = Yrityksen nimi
    .title = Organisaatioyksikön nimi
vcard-org-org-unit = Osasto
vcard-org-org-unit-input =
    .placeholder = Osasto
    .title = Organisaatioyksikön nimi
vcard-custom-header = Mukautetut ominaisuudet
vcard-custom-add = Lisää mukautettuja ominaisuuksia
vcard-remove-button-title =
    .title = Poista
vcard-remove-button = Poista
