# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = 유동 공간
toolbar-write-message-label = 쓰기
toolbar-write-message =
    .title = 새 메시지 쓰기
toolbar-unifinder-label = 이벤트 찾기
toolbar-unifinder =
    .title = 이벤트 찾기 창 표시
toolbar-folder-location-label = 폴더 위치
toolbar-edit-event-label = 편집
toolbar-edit-event =
    .title = 선택한 이벤트와 태스크를 편집
toolbar-get-messages-label = 받기
toolbar-reply-label = 회신
toolbar-reply =
    .title = 메시지 회신
toolbar-reply-all-label = 모두 회신
toolbar-reply-all =
    .title = 모든 받은 사람에게 회신
toolbar-reply-to-list-label = 리스트로 회신
toolbar-reply-to-list =
    .title = 메일링 리스트로 회신
toolbar-archive-label = 보관
toolbar-archive =
    .title = 선택한 메시지 보관
toolbar-conversation-label = 대화
toolbar-conversation =
    .title = 선택한 메시지의 대화 보기
toolbar-previous-unread-label = 이전 항목
toolbar-previous-unread =
    .title = 읽지 않은 이전 메시지로 이동
toolbar-previous-label = 이전
toolbar-previous =
    .title = 이전 메시지로 이동
toolbar-next-unread-label = 다음 항목
toolbar-next-unread =
    .title = 다음 읽지 않은 메일로 이동
toolbar-next-label = 다음 메시지
toolbar-next =
    .title = 다음 메시지로 이동
toolbar-junk-label = 스팸
toolbar-junk =
    .title = 스팸인 메세지를 골라 표시하세요
toolbar-delete-label = 삭제
toolbar-delete =
    .title = 선택한 메세지나 폴더를 삭제함
toolbar-compact-label = 비우기
toolbar-compact =
    .title = 선택한 폴더에서 삭제 표시된 메시지 지우기
toolbar-add-as-event-label = 이벤트 추가
toolbar-add-as-event =
    .title = 메시지에서 날짜 정보를 추출하여 캘린더에 이벤트로 추가
toolbar-add-as-task-label = 태스크 추가
toolbar-add-as-task =
    .title = 메시지에서 날짜 정보를 추출하여 캘린더에 태스크로 추가
toolbar-tag-message-label = 태그
toolbar-tag-message =
    .title = 태그 메시지
toolbar-forward-inline-label = 전달
toolbar-forward-inline =
    .title = 선탁한 메시지를 인라인으로 전달
toolbar-forward-attachment-label = 첨부 전달
toolbar-forward-attachment =
    .title = 선택한 메시지를 첨부로 전달
toolbar-mark-as-label = 표시
toolbar-mark-as =
    .title = 메시지 표시
toolbar-address-book =
    .title = 주소록 열기
toolbar-chat-label = 채팅
toolbar-chat =
    .title = 채팅 열기
toolbar-calendar-label = 캘린더
toolbar-calendar =
    .title = 캘린더 탭으로 전환
toolbar-tasks-label = 태스크
toolbar-tasks =
    .title = ToDo 탭으로 전환
toolbar-print-label = 인쇄
toolbar-print =
    .title = 메시지 인쇄
