# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title = Каляндар
calendar-title-reminder = Напаміны
calendar-title-notification = Абвесткі
calendar-title-category = Катэгорыі
dateformat-label =
    .value = Тэкставы фармат даты:
    .accesskey = Д
use-system-timezone-radio-button =
    .label = Выкарыстоўваць часавы пояс сістэмы
timezone-label =
    .value = Часавы пояс:
weekstart-label =
    .value = Першы дзень тыдня:
    .accesskey = р
day-1-name =
    .label = Нядзеля
day-2-name =
    .label = Панядзелак
day-3-name =
    .label = Аўторак
day-4-name =
    .label = Серада
day-5-name =
    .label = Чацвер
day-6-name =
    .label = Пятніца
day-7-name =
    .label = Субота
workdays-label =
    .value = Працоўныя дні:
midnight-label =
    .label = Поўнач
noon-label =
    .label = Поўдзень
week-1-label =
    .label = 1 тыдзень
week-2-label =
    .label = 2 тыдні
task-start-4-label =
    .label = Заўтра
task-start-5-label =
    .label = Наступны тыдзень
reminder-play-alarm-button =
    .label = Прайграць
    .accesskey = П
category-new-label = Новая катэгорыя
category-edit-label = Рэдагаваць катэгорыю
