# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title = Каляндар
calendar-title-reminder = Напамінкі
calendar-title-notification = Апавяшчэнні
calendar-title-category = Катэгорыі
dateformat-label =
    .value = Тэкставы фармат даты:
    .accesskey = Д
#   $date (String) - the formatted example date
dateformat-long =
    .label = Поўны: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Сціслы: { $date }
use-system-timezone-radio-button =
    .label = Выкарыстоўваць часавы пояс сістэмы
set-timezone-manually-radio-button =
    .label = Задаць часавы пояс уручную
timezone-label =
    .value = Часавы пояс:
weekstart-label =
    .value = Першы дзень тыдня:
    .accesskey = р
day-1-name =
    .label = Нядзеля
day-2-name =
    .label = Панядзелак
day-3-name =
    .label = Аўторак
day-4-name =
    .label = Серада
day-5-name =
    .label = Чацвер
day-6-name =
    .label = Пятніца
day-7-name =
    .label = Субота
workdays-label =
    .value = Працоўныя дні:
day-1-checkbox =
    .label = Няд
    .accesskey = Н
day-2-checkbox =
    .label = Пан
    .accesskey = П
day-3-checkbox =
    .label = Аўт
    .accesskey = А
day-4-checkbox =
    .label = Сер
    .accesskey = С
day-5-checkbox =
    .label = Чац
    .accesskey = Ч
day-6-checkbox =
    .label = Пят
    .accesskey = я
day-7-checkbox =
    .label = Суб
    .accesskey = у
visible-hours-label =
    .value = Паказваць:
    .accesskey = П
visible-hours-end-label =
    .value = гадзін адначасова
day-start-label =
    .value = Дзень пачынаецца ў:
    .accesskey = п
day-end-label =
    .value = Дзень заканчваецца ў:
    .accesskey = з
midnight-label =
    .label = Поўнач
noon-label =
    .label = Поўдзень
number-of-weeks-label =
    .value = Паказваць тыдняў (з улікам папярэдніх тыдняў):
    .accesskey = з
week-1-label =
    .label = 1 тыдзень
week-2-label =
    .label = 2 тыдні
week-3-label =
    .label = 3 тыдні
week-4-label =
    .label = 4 тыдні
week-5-label =
    .label = 5 тыдняў
week-6-label =
    .label = 6 тыдняў
previous-weeks-label =
    .value = Паказваць папярэдніх тыдняў:
    .accesskey = п
event-task-legend = Падзеі і задачы
default-length-label =
    .value = Стандартная працягласць падзей і задач:
    .accesskey = С
task-start-label =
    .value = Дата пачатку:
task-start-2-label =
    .label = У пачатку дня
task-start-3-label =
    .label = У канцы дня
task-start-4-label =
    .label = Заўтра
task-start-5-label =
    .label = У наступны тыдзень
task-start-6-label =
    .label = Адносна бягучага часу
task-start-7-label =
    .label = Адносна пачатку
task-start-8-label =
    .label = Адносна наступнай гадзіны
edit-intab-label =
    .label = Рэдагаваць падзеі і задачы на ўкладцы, а не ў дыялогавым акне.
    .accesskey = э
reminder-play-checkbox =
    .label = Прайграваць гук
    .accesskey = П
reminder-play-alarm-button =
    .label = Прайграць
    .accesskey = П
reminder-default-sound-label =
    .label = Выкарыстоўваць стандартны гук
    .accesskey = ы
reminder-custom-sound-label =
    .label = Выкарыстоўваць наступны гукавы файл
    .accesskey = В
reminder-browse-sound-label =
    .label = Агляд…
    .accesskey = А
reminder-dialog-label =
    .label = Паказваць акно напамінку
    .accesskey = П
event-alarm-label =
    .value = Дадаваць напамінак для новых падзей:
    .accesskey = Д
alarm-on-label =
    .label = Уключана
alarm-off-label =
    .label = Адключана
task-alarm-label =
    .value = Дадаваць напамінак для новых задач:
    .accesskey = а
calendar-notifications-customize-label = Апавяшчэнні для кожнага асобнага календара можна наладзіць ў акне яго ўласцівасцяў.
category-new-label = Новая катэгорыя
category-edit-label = Рэдагаваць катэгорыю
category-overwrite-title = Папярэджанне: дубліраванне імяў
category-overwrite = Катэгорыя з гэтым імем ужо існуе. Ці жадаеце яе перазапісаць?
category-blank-warning = Вы павінны ўвесці імя катэгорыі.
