# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title = Каляндар
calendar-title-reminder = Напаміны
calendar-title-notification = Апавяшчэнні
calendar-title-category = Катэгорыі
dateformat-label =
    .value = Тэкставы фармат даты:
    .accesskey = Д
#   $date (String) - the formatted example date
dateformat-long =
    .label = Поўны: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Сціслы: { $date }
use-system-timezone-radio-button =
    .label = Выкарыстоўваць часавы пояс сістэмы
set-timezone-manually-radio-button =
    .label = Задаць часавы пояс уручную
timezone-label =
    .value = Часавы пояс:
weekstart-label =
    .value = Першы дзень тыдня:
    .accesskey = р
day-1-name =
    .label = Нядзеля
day-2-name =
    .label = Панядзелак
day-3-name =
    .label = Аўторак
day-4-name =
    .label = Серада
day-5-name =
    .label = Чацвер
day-6-name =
    .label = Пятніца
day-7-name =
    .label = Субота
workdays-label =
    .value = Працоўныя дні:
day-1-checkbox =
    .label = Няд
    .accesskey = Н
day-2-checkbox =
    .label = Пан
    .accesskey = П
day-3-checkbox =
    .label = Аўт
    .accesskey = А
day-4-checkbox =
    .label = Сер
    .accesskey = С
day-5-checkbox =
    .label = Чац
    .accesskey = Ч
day-6-checkbox =
    .label = Пят
    .accesskey = я
day-7-checkbox =
    .label = Суб
    .accesskey = у
visible-hours-label =
    .value = Паказваць:
    .accesskey = П
visible-hours-end-label =
    .value = гадзін адначасова
day-start-label =
    .value = Дзень пачынаецца ў:
    .accesskey = п
day-end-label =
    .value = Дзень заканчваецца ў:
    .accesskey = з
midnight-label =
    .label = Поўнач
noon-label =
    .label = Поўдзень
week-1-label =
    .label = 1 тыдзень
week-2-label =
    .label = 2 тыдні
week-5-label =
    .label = 5 тыдняў
week-6-label =
    .label = 6 тыдняў
event-task-legend = Падзеі і задачы
task-start-4-label =
    .label = Заўтра
task-start-5-label =
    .label = Наступны тыдзень
task-start-6-label =
    .label = Адносна бягучага часу
task-start-7-label =
    .label = Адносна пачатку
task-start-8-label =
    .label = Адносна наступнай гадзіны
reminder-play-checkbox =
    .label = Прайграць гук
    .accesskey = П
reminder-play-alarm-button =
    .label = Прайграць
    .accesskey = П
alarm-on-label =
    .label = Уключыць
alarm-off-label =
    .label = Адключыць
category-new-label = Новая катэгорыя
category-edit-label = Рэдагаваць катэгорыю
category-overwrite = Катэгорыя з гэтым імем ужо існуе. Ці жадаеце яе перазапісаць?
category-blank-warning = Вы павінны ўвесці імя катэгорыі.
