# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = გამოსაჩენი სახელი
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = სახეობა
vcard-entry-type-home = სახლი
vcard-entry-type-work = სამსახური
vcard-entry-type-none = არცერთი
vcard-entry-type-custom = მითითებული
vcard-name-header = სახელი
vcard-n-prefix = წინსართი
vcard-n-add-prefix =
    .title = წინსართის დამატება
vcard-n-firstname = სახელი
vcard-n-add-firstname =
    .title = სახელის დამატება
vcard-n-middlename = მეორე სახელი
vcard-n-add-middlename =
    .title = მეორე სახელის დამატება
vcard-n-lastname = გვარი
vcard-n-add-lastname =
    .title = გვარის დამატება
vcard-n-suffix = ბოლოსართი
vcard-n-add-suffix =
    .title = ბოლოსართის დამატება
vcard-nickname = მეტსახელი
vcard-email-header = ელფოსტის მისამართები
vcard-email-add = ელფოსტის დამატება
vcard-email-label = ელფოსტის მისამართი
vcard-primary-email-label = ნაგულისხმევი
vcard-url-header = საიტები
vcard-url-add = საიტის დამატება
vcard-url-label = ვებსაიტი
vcard-tel-header = ტელეფონის ნომრები
vcard-tel-add = ტელეფონის ნომრის დამატება
vcard-tel-label = ტელეფონის ნომერი
# Or "Mobile"
vcard-entry-type-cell = მობილური
vcard-entry-type-fax = ფაქსი
vcard-entry-type-pager = პეიჯერი
vcard-tz-header = დროის სარტყელი
vcard-tz-add = დაამატეთ დროის სარტყელი
vcard-impp2-header = სწრაფი მიმოწერა
vcard-impp-add = სასაუბროს ანგარიშის დამატება
vcard-impp-label = სასაუბროს ანგარიში
vcard-impp-select = ოქმი
vcard-impp-option-other = სხვა
vcard-impp-input-label = URI
vcard-impp-input-title = URI სწრაფი მიმოწერისთვის
vcard-bday-anniversary-header = საგანგებო თარიღები
vcard-bday-anniversary-add = საგანგებო თარიღის დამატება
vcard-bday-label = დაბადების დღე
vcard-anniversary-label = იუბილე
vcard-date-day = დღე
vcard-date-month = თვე
vcard-date-year = წელი
vcard-adr-header = მისამართები
vcard-adr-add = მისამართის დამატება
vcard-adr-label = მისამართი
vcard-adr-delivery-label = მიწოდების ზედნადები
vcard-adr-street = ქუჩის მისამართი
# Or "Locality"
vcard-adr-locality = ქალაქი
# Or "Region"
vcard-adr-region = მხარე/რაიონი
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = ZIP/საფოსტო კოდი
vcard-adr-country = ქვეყანა
vcard-note-header = შენიშვნები
vcard-note-add = შენიშვნის დამატება
vcard-org-header = დაწესებულების მონაცემები
vcard-org-add = დაწესებულების მონაცემების დამატება
vcard-org-title = სათაური
vcard-org-title-input =
    .placeholder = სამსახურის დასახელება
    .title = თანამდებობა ან სამსახური
vcard-org-role = მოვალეობა
vcard-org-role-input =
    .placeholder = მოვალეობა საქმეში
    .title = მოვალეობა ან ნაწილობრივი მონაწილეობა ცალკეულ გარემოებებში
vcard-org-org = დაწესებულება
vcard-org-org-input =
    .placeholder = კომპანიის სახელი
    .title = დაწესებულების სახელი
vcard-org-org-unit = განყოფილება
vcard-org-org-unit-input =
    .placeholder = განყოფილება
    .title = დაწესებულების ერთეულის სახელი
vcard-custom-header = მითითებული მახასიათებლები
vcard-custom-add = სასურველი მახასიათებლის დამატება
vcard-remove-button-title =
    .title = მოცილება
vcard-remove-button = მოცილება
