# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Buscando…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Atopouse #1 coincidencia;Atopáronse #1 coincidencias
noMatchesFound = Non se atoparon coincidencias
labelForStopButton = Deter
labelForSearchButton = Buscar
labelForStopButton.accesskey = t
labelForSearchButton.accesskey = B
moreButtonTooltipText = Engadir unha nova regra
lessButtonTooltipText = Eliminar esta regra
