# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = 選擇全部
select-none-calendars = 全部不選
calendar-creation-wizard-title = 建立新的行事曆
calendar-creation-initial-description = 您的行事曆可以存放在電腦或伺服器上，便於從遠端存取或與親朋好友分享。
calendar-creation-initial-computer =
    .label = 存放於本機電腦
calendar-creation-initial-network =
    .label = 存放於網際網路
calendar-creation-username =
    .value = 使用者名稱：
calendar-creation-panel-local-settings =
    .buttonlabelaccept = 建立行事曆
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 上一頁
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = 建立行事曆
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = 上一頁
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = 尋找行事曆
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = 上一頁
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = 訂閱
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = 上一頁
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = 行事曆類型:
calendar-creation-location =
    .value = 位置:
calendar-creation-location-placeholder =
    .placeholder = 行事曆伺服器的網址或主機名稱
    .default-placeholder = 行事曆伺服器的網址或主機名稱
calendar-creation-network-nocredentials =
    .label = 此網址不需輸入帳號密碼
calendar-creation-network-loading = 請稍等，我們正在尋找您的行事曆。
calendar-creation-network-notfound = 無法在此位置找到行事曆，請檢查設定。
calendar-creation-network-authfail = 您輸入的帳號密碼未被接受，請檢查設定。
calendar-creation-network-certerror = 因憑證問題，無法在此位置找到行事曆。
calendar-creation-network-subscribe-single = 請選擇您要訂閱的行事曆。
calendar-creation-network-subscribe-multiple = 此位置有多種不同的行事曆。請先選擇要訂閱的類型，再勾選想要訂閱的行事曆。
