# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = 註解
calendar-item-summary-title = 標題：
calendar-item-summary-calendar = 行事曆:
calendar-item-summary-task-start = 開始日：
calendar-item-summary-event-start = 開始日：
calendar-item-summary-task-due = 到期日：
calendar-item-summary-event-end = 結束日期：
calendar-item-summary-repeat = 重複:
calendar-item-summary-location = 位置：
calendar-item-summary-category = 分類:
calendar-item-summary-organizer = 召集人：
calendar-item-summary-status = 狀態：
calendar-item-summary-reminder = 提醒:
calendar-item-summary-attachments = 附件:
calendar-item-summary-status-tentative = 暫定
calendar-item-summary-status-confirmed = 已確認
calendar-item-summary-event-status-cancelled = 已取消
calendar-item-summary-todo-status-cancelled = 已取消
calendar-item-summary-status-needs-action = 待處理
calendar-item-summary-status-in-process = 進行中
calendar-item-summary-status-completed = 完成於
calendar-item-summary-reminder-none =
    .label = 不提醒
calendar-item-summary-reminder-0-minutes-before =
    .label = 在 0 分鐘之前
calendar-item-summary-reminder-5-minutes-before =
    .label = 在 5 分鐘之前
calendar-item-summary-reminder-15-minutes-before =
    .label = 在 15 分鐘之前
calendar-item-summary-reminder-30-minutes-before =
    .label = 在 30 分鐘之前
calendar-item-summary-reminder-1-hour-before =
    .label = 在 1 小時之前
calendar-item-summary-reminder-2-hours-before =
    .label = 在 2 小時之前
calendar-item-summary-reminder-12-hours-before =
    .label = 在 12 小時之前
calendar-item-summary-reminder-1-day-before =
    .label = 在 1 天之前
calendar-item-summary-reminder-2-days-before =
    .label = 在 2 天之前
calendar-item-summary-reminder-1-week-before =
    .label = 在 1 星期之前
calendar-item-summary-reminder-custom =
    .label = 自訂…
calendar-item-summary-reminder-multiple =
    .value = 多次提醒…
calendar-item-summary-general =
    .value = 一般
calendar-item-summary-attendees =
    .value = 與會者
calendar-item-summary-description =
    .value = 描述
calendar-item-summary-link =
    .value = 相關鏈結
