# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Ճկուն բացատ
toolbar-write-message-label = Գրել
toolbar-write-message =
    .title = Ստեղծել նոր նամակ
toolbar-folder-location-label = Թղթապանակի տեղադրութիւնը
toolbar-get-messages-label = Ստանալ նամակները
toolbar-reply-label = Պատասխանել
toolbar-reply =
    .title = Պատասխանել նամակին
toolbar-reply-all-label = Պատասխանել բոլորին
toolbar-reply-all =
    .title = Պատասխանել ուղարկողին եւ մեւսներին
toolbar-reply-to-list-label = Պատասխանել ցուցակին
toolbar-reply-to-list =
    .title = Պատասխանել փոստային ցուցակին
toolbar-redirect-label = Վերայղում
toolbar-redirect =
    .title = Վերայղել ընտրուած հաղորդագրութիւնը
toolbar-archive-label = Արխիւ
toolbar-archive =
    .title = Արխիւացնել ընտրուած նամակները
toolbar-conversation-label = Զրոյց
toolbar-conversation =
    .title = Ցուցադրել ընտրուած հաղորդագրութեան զրոյցը
toolbar-previous-unread-label = Նախորդ չընթերցուածը
toolbar-previous-unread =
    .title = Տեղափոխուել դէպի նախորդ չընթերցուած նամակ
toolbar-previous-label = Նախորդը
toolbar-previous =
    .title = Տեղափոխուել դէպի նախորդ նամակ
toolbar-next-unread-label = Յաջորդ չընթերցուածը
toolbar-next-unread =
    .title = Տեղափոխուել դէպի յաջորդ չընթերցուած նամակ
toolbar-next-label = Յաջորդը
toolbar-next =
    .title = Տեղափոխուել դէպի յաջորդ նամակ
toolbar-junk-label = Թափաւն
toolbar-junk =
    .title = Նշել ընտրուած հաղորդագրութիւնները որպէս թափաւն
toolbar-delete-label = Ջնջել
toolbar-delete =
    .title = Ջնջել ընտրուած հաղորդագրութիւնները կամ պանակը
toolbar-compact-label = Սեղմել
toolbar-compact =
    .title = Հեռացնել ջնջուած նամակները ընտրուած թղթապանակից
toolbar-add-as-event-label = Աւելացնել որպէս իրադարձութիւն
toolbar-add-as-event =
    .title = Հանէ՛ք աւրացոյցի տեղեկութիւնը հաղորդագրութիւնից եւ աւելացրէ՛ք այն ձեր աւրացոյցում`որպէս իրադարձութիւն
toolbar-add-as-task-label = Աւելացնել որպէս առաջադրանք
toolbar-add-as-task =
    .title = Հանէ՛ք աւրացոյցի տեղեկութիւնը հաղորդագրութիւնից եւ աւելացրէ՛ք այն ձեր աւրացոյցում որպէս առաջադրանք
toolbar-tag-message-label = Պիտակ
toolbar-tag-message =
    .title = Պիտակաւորել նամակները
toolbar-forward-inline-label = Փոխանցել
toolbar-forward-inline =
    .title = Փոխանցել ընտրուած նամակները որպէս ներտող գրոյթ
toolbar-forward-attachment-label = Փոխանցել որպէս կցորդ
toolbar-forward-attachment =
    .title = Ընտրուած հաղորդագրութիւնը փոխանցել որպէս յաւելուած
toolbar-mark-as-label = Նշել
toolbar-mark-as =
    .title = Նշել նամակներ
toolbar-address-book =
    .title = Գնալ դէպի հասցէագիրք
toolbar-chat-label = Զրոյց
toolbar-chat =
    .title = Ցուցադրել զրոյցի ներդիրը
toolbar-add-ons-and-themes-label = Յաւելումներ եւ հիմնապատկերներ
toolbar-add-ons-and-themes =
    .title = Կառավարէք Ձեր յաւելումները
toolbar-print-label = Տպել
toolbar-print =
    .title = Տպել այս նամակը
toolbar-quick-filter-bar-label = Արագ զտում
toolbar-quick-filter-bar =
    .title = Հաղորդագրութեան զտում
toolbar-go-back-label = Յետ
toolbar-go-back =
    .title = Մեկ նամակ յետ
toolbar-go-forward-label = Փոխանցել
toolbar-go-forward =
    .title = Մեկ նամակ առաջ
toolbar-stop-label = Կանգնեցնել
toolbar-stop =
    .title = Կանգնեցնել փոխանցումը
toolbar-throbber-label = Ակտիւութեան ցուցիչ
toolbar-throbber =
    .title = Ակտիւութեան ցուցիչ
