# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# status feedback stuff
documentDone =
# separator for search date (e.g. "/", "-"), or empty when search_date_format is zero
mailnews.search_date_separator =
