# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = เลือกทั้งหมด
select-none-calendars = ไม่เลือกเลย
calendar-creation-wizard-title = สร้างปฏิทินใหม่
calendar-creation-initial-description = สามารถเก็บปฏิทินของคุณไว้ในคอมพิวเตอร์ของคุณหรือในเซิร์ฟเวอร์เพื่อให้สามารถเข้าถึงได้จากระยะไกลหรือแบ่งปันกับเพื่อนร่วมงานของคุณได้
calendar-creation-initial-computer =
    .label = ในคอมพิวเตอร์ของฉัน
calendar-creation-initial-network =
    .label = ในเครือข่าย
calendar-creation-username =
    .value = ชื่อผู้ใช้:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = สร้างปฏิทิน
    .buttonaccesskeyaccept = ส
    .buttonlabelextra2 = ย้อนกลับ
    .buttonaccesskeyextra2 = ย
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = สร้างปฏิทิน
    .buttonaccesskeyaccept = ส
    .buttonlabelextra2 = ย้อนกลับ
    .buttonaccesskeyextra2 = ย
calendar-creation-panel-network-settings =
    .buttonlabelaccept = ค้นหาปฏิทิน
    .buttonaccesskeyaccept = ค
    .buttonlabelextra2 = ย้อนกลับ
    .buttonaccesskeyextra2 = ย
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = บอกรับ
    .buttonaccesskeyaccept = บ
    .buttonlabelextra2 = ย้อนกลับ
    .buttonaccesskeyextra2 = ย
calendar-creation-type =
    .value = ชนิดปฏิทิน:
calendar-creation-location =
    .value = ตำแหน่งที่ตั้ง:
calendar-creation-location-placeholder =
    .placeholder = URL หรือชื่อโฮสต์ของเซิร์ฟเวอร์ปฏิทิน
    .default-placeholder = URL หรือชื่อโฮสต์ของเซิร์ฟเวอร์ปฏิทิน
calendar-creation-network-nocredentials =
    .label = ตำแหน่งที่ตั้งนี้ไม่ต้องการข้อมูลรับรอง
calendar-creation-network-loading = โปรดรอในขณะที่กำลังค้นพบปฏิทินของคุณ
calendar-creation-network-notfound = ไม่พบปฏิทินที่ตำแหน่งที่ตั้งนี้ โปรดตรวจสอบการตั้งค่าของคุณ
calendar-creation-network-authfail = ไม่ยอมรับข้อมูลรับรองที่คุณป้อน โปรดตรวจสอบการตั้งค่าของคุณ
calendar-creation-network-certerror = ไม่พบปฏิทินที่ตำแหน่งที่ตั้งนี้เนื่องจากปัญหาเกี่ยวกับใบรับรอง
calendar-creation-network-subscribe-single = โปรดเลือกปฏิทินที่คุณต้องการบอกรับ
calendar-creation-network-subscribe-multiple = มีปฏิทินหลายชนิดสำหรับตำแหน่งที่ตั้งนี้ โปรดเลือกชนิดปฏิทิน จากนั้นทำเครื่องหมายปฏิทินที่คุณต้องการบอกรับ
