# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = ชื่อเรื่อง:
calendar-item-summary-calendar = ปฏิทิน:
calendar-item-summary-task-start = วันที่เริ่ม:
calendar-item-summary-event-start = วันที่เริ่ม:
calendar-item-summary-task-due = วันที่ครบกำหนด:
calendar-item-summary-event-end = วันที่สิ้นสุด:
calendar-item-summary-repeat = ทำซ้ำ:
calendar-item-summary-location = ตำแหน่งที่ตั้ง:
calendar-item-summary-category = หมวดหมู่:
calendar-item-summary-organizer = ผู้จัด:
calendar-item-summary-status = สถานะ:
calendar-item-summary-reminder = การเตือนความจำ:
calendar-item-summary-attachments = ไฟล์แนบ:
calendar-item-summary-status-tentative = ไม่แน่นอน
calendar-item-summary-status-confirmed = ยืนยันแล้ว
calendar-item-summary-event-status-cancelled = ยกเลิกแล้ว
calendar-item-summary-todo-status-cancelled = ยกเลิกแล้ว
calendar-item-summary-status-needs-action = ต้องการการกระทำ
calendar-item-summary-status-in-process = อยู่ระหว่างดำเนินการ
calendar-item-summary-status-completed = เสร็จสมบูรณ์เมื่อ
calendar-item-summary-reminder-none =
    .label = ไม่มีการเตือนความจำ
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 นาทีก่อนหน้า
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 นาทีก่อนหน้า
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 นาทีก่อนหน้า
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 นาทีก่อนหน้า
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ชั่วโมงก่อนหน้า
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ชั่วโมงก่อนหน้า
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ชั่วโมงก่อนหน้า
calendar-item-summary-reminder-1-day-before =
    .label = 1 วันก่อนหน้า
calendar-item-summary-reminder-2-days-before =
    .label = 2 วันก่อนหน้า
calendar-item-summary-reminder-1-week-before =
    .label = 1 สัปดาห์ก่อนหน้า
calendar-item-summary-reminder-custom =
    .label = กำหนดเอง…
calendar-item-summary-reminder-multiple =
    .value = การเตือนความจำหลายรายการ…
calendar-item-summary-general =
    .value = ทั่วไป
calendar-item-summary-attendees =
    .value = ผู้เข้าร่วม
calendar-item-summary-description =
    .value = คำอธิบาย
calendar-item-summary-link =
    .value = ลิงก์ที่เกี่ยวข้อง
