# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Zuriune malgua
search-bar-label = Bilatu
toolbar-write-message-label = Idatzi
toolbar-write-message =
    .title = Sortu mezu berria
toolbar-move-to-label = Mugitu hona:
toolbar-move-to =
    .title = Mugitu hautatutako mezuak
toolbar-unifinder-label = Bilatu gertaerak
toolbar-unifinder =
    .title = Gertaera bilaketa panela txandakatu
toolbar-folder-location-label = Karpetaren kokapena
toolbar-folder-location =
    .title = Aldatu karpetara
toolbar-edit-event-label = Editatu
toolbar-edit-event =
    .title = Editatu aukeratutako gertaera edo zeregina
toolbar-get-messages-label = Eskuratu mezuak
toolbar-get-messages =
    .title = Eskuratu mezu berriak kontu guztietan
toolbar-reply-label = Erantzun
toolbar-reply =
    .title = Erantzun mezuari
toolbar-reply-all-label = Erantzun denei
toolbar-reply-all =
    .title = Erantzun bidaltzaileari eta hartzaile guztiei
toolbar-reply-to-list-label = Erantzun zerrendari
toolbar-reply-to-list =
    .title = Erantzun posta-zerrendari
toolbar-redirect-label = Birbideratzea
toolbar-redirect =
    .title = Birbideratu hautatutako mezua
toolbar-archive-label = Artxibatu
toolbar-archive =
    .title = Artxibatu hautatutako mezuak
toolbar-conversation-label = Elkarrizketa
toolbar-conversation =
    .title = Erakutsi aukeratutako mezuaren elkarrizketa
toolbar-previous-unread-label = Irakurri gabeko aurrekoa
toolbar-previous-unread =
    .title = Mugitu irakurri gabeko aurreko mezura
toolbar-previous-label = Aurrekoa
toolbar-previous =
    .title = Joan aurreko mezura
toolbar-next-unread-label = Irakurri gabeko hurrengoa
toolbar-next-unread =
    .title = Mugitu irakurri gabeko hurrengo mezura
toolbar-next-label = Hurrengoa
toolbar-next =
    .title = Joan hurrengo mezura
toolbar-junk-label = Zaborra
toolbar-junk =
    .title = Markatu aukeratutako mezua zabor bezala
toolbar-delete-label = Ezabatu
toolbar-delete-title =
    .title = Ezabatu hautatutako mezuak
toolbar-undelete-label = Desezabatu
toolbar-undelete =
    .title = Desezabatu hautatutako mezuak
toolbar-compact-label = Trinkoa
toolbar-compact =
    .title = Kendu ezabatutako mezuak hautatutako karpetatik
toolbar-add-as-event-label = Gehitu gertaera gisa
toolbar-add-as-event =
    .title = Erauzi egutegi-informazioa mezutik eta gehitu zure egutegian gertaera gisa
toolbar-add-as-task-label = Gehitu zeregin gisa
toolbar-add-as-task =
    .title = Erauzi egutegi-informazioa mezutik eta gehitu zure egutegian zeregin gisa
toolbar-tag-message-label = Etiketa
toolbar-tag-message =
    .title = Etiketatu mezuak
toolbar-forward-inline-label = Birbidali
toolbar-forward-inline =
    .title = Birbidali hautatutako mezua barneko testu gisa
toolbar-forward-attachment-label = Birbidali eranskin gisa
toolbar-forward-attachment =
    .title = Birbidali hautatutako mezua eranskin gisa
toolbar-mark-as-label = Markatu
toolbar-mark-as =
    .title = Markatu mezuak
toolbar-view-picker-label = Ikusi
toolbar-view-picker =
    .title = Pertsonalizatu uneko karpetaren ikuspegia
toolbar-address-book-label = Helbide-liburua
toolbar-address-book =
    .title = Joan helbide-liburura
toolbar-chat-label = Txata
toolbar-chat =
    .title = Erakutsi txataren fitxa
toolbar-add-ons-and-themes-label = Gehigarriak eta itxurak
toolbar-add-ons-and-themes =
    .title = Kudeatu zure gehigarriak
toolbar-calendar-label = Egutegia
toolbar-calendar =
    .title = Aldatu egutegiaren fitxara
toolbar-tasks-label = Zereginak
toolbar-tasks =
    .title = Aldatu zereginen fitxara
toolbar-mail-label = Posta
toolbar-mail =
    .title = Aldatu posten fitxara
toolbar-print-label = Inprimatu
toolbar-print =
    .title = Inprimatu mezu hau
toolbar-quick-filter-bar-label = Iragazki bizkorra
toolbar-quick-filter-bar =
    .title = Iragazi mezuak
toolbar-synchronize-label = Sinkronizatu
toolbar-synchronize =
    .title = Berritu egutegiak eta sinkronizatu aldaketak
toolbar-delete-event-label = Ezabatu
toolbar-delete-event =
    .title = Ezabatu aukeratutako gertaera edo zeregina
toolbar-go-to-today-label = Gaur kokatu
toolbar-go-to-today =
    .title = Gaur kokatu
toolbar-print-event-label = Inprimatu
toolbar-print-event =
    .title = Inprimatu gertaerak edo zereginak
toolbar-new-event-label = Gertaera
toolbar-new-event =
    .title = Sortu gertaera berria
toolbar-new-task-label = Zeregina
toolbar-new-task =
    .title = Sortu zeregin berria
toolbar-go-back-label = Atzera
toolbar-go-back =
    .title = Joan mezu bat atzera
toolbar-go-forward-label = Aurrera
toolbar-go-forward =
    .title = Joan mezu bat aurrera
toolbar-stop-label = Gelditu
toolbar-stop =
    .title = Gelditu uneko transferentzia
toolbar-throbber-label = Jarduera-adierazlea
toolbar-throbber =
    .title = Jarduera-adierazlea
toolbar-create-contact-label = Kontaktu berria
toolbar-create-contact =
    .title = Sortu kontaktu berria
toolbar-create-address-book-label = Helbide-liburu berria
toolbar-create-address-book =
    .title = Sortu helbide-liburu berria
toolbar-create-list-label = Zerrenda berria
toolbar-create-list =
    .title = Sortu posta-zerrenda berria
toolbar-import-contacts-label = Inportatu
toolbar-import-contacts =
    .title = Inportatu kontaktuak fitxategitik…

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Gehitu helbide-liburu lokala
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Gehitu CardDAV helbide-liburua
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Gehitu LDAP helbide-liburua
