# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Paramètres hors connexion
autodetect-connection-label =
    .label = Changer automatiquement de mode lorsqu’une connexion Internet est trouvée
    .accesskey = C
offline-startup-label = Lors de l’ouverture de { -brand-short-name } :
status-radio-last-used =
    .label = Utiliser le dernier mode de connexion utilisé
    .accesskey = U
status-radio-ask-connect =
    .label = Demander s’il faut se connecter
    .accesskey = D
status-radio-start-online =
    .label = Démarrer en ligne
    .accesskey = D
status-radio-start-offline =
    .label = Démarrer hors connexion
    .accesskey = D
going-online-prompt = Messages d’envoi en attente dans votre boîte d’envoi
going-online-send =
    .label = Oui, envoyer automatiquement
    .accesskey = O
going-online-keep =
    .label = Non, conserver dans la boîte d’envoi
    .accesskey = N
going-online-ask-send =
    .label = Demander avant d’envoyer
    .accesskey = D
going-offline-prompt = Voulez-vous télécharger les messages pour les lire hors connexion ?
going-offline-download =
    .label = Oui, télécharger automatiquement
    .accesskey = O
going-offline-keep =
    .label = Non, ne pas télécharger
    .accesskey = N
going-offline-ask-download =
    .label = Demander avant de télécharger
    .accesskey = D
autodetect-online-label =
    .label = Toujours passer en mode en ligne lorsque cela est possible
    .accesskey = T
offline-preference-startup-label = État manuel au démarrage :
status-radio-remember =
    .label = Se souvenir de l’état précédent
    .accesskey = S
status-radio-ask =
    .label = Demander à passer en mode en ligne
    .accesskey = D
status-radio-always-online =
    .label = Passer en mode en ligne
    .accesskey = P
status-radio-always-offline =
    .label = Passer en mode hors connexion
    .accesskey = a
going-online-label = Envoyer les messages en attente lors du passage en mode en ligne ?
going-online-auto =
    .label = Oui
    .accesskey = u
going-online-not =
    .label = Non
    .accesskey = N
going-online-ask =
    .label = Demander
    .accesskey = e
going-offline-label = À la déconnexion, télécharger les messages pour une utilisation hors connexion ?
going-offline-auto =
    .label = Oui
    .accesskey = i
going-offline-not =
    .label = Non
    .accesskey = o
going-offline-ask =
    .label = Demander
    .accesskey = m
