# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = يجري البحث…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = عُثر على تطابق واحد;عُثر على تطابقين;عُثر على #1 تطابقات;عُثر على #1 تطابقًا;عُثر على #1 تطابق;عُثر على #1 تطابق
noMatchesFound = لم يُعثر على أي تطابق
labelForStopButton = قف
labelForSearchButton = ابحث
labelForStopButton.accesskey = ق
labelForSearchButton.accesskey = ب
moreButtonTooltipText = أضِف قاعدة جديدة
lessButtonTooltipText = احذف هذه القاعدة
