# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Prilagodljiv prostor
search-bar-label = Išči
toolbar-write-message-label = Sestavi
toolbar-write-message =
    .title = Ustvari novo sporočilo
toolbar-move-to-label = Premakni v
toolbar-move-to =
    .title = Premakni izbrano sporočilo
toolbar-unifinder-label = Najdi dogodke
toolbar-unifinder =
    .title = Preklopi podokno za iskanje dogodkov
toolbar-folder-location-label = Mesto mape
toolbar-folder-location =
    .title = Preklopi na mapo
toolbar-edit-event-label = Uredi
toolbar-edit-event =
    .title = Uredi izbrani dogodek ali opravilo
toolbar-get-messages-label = Prejmi sporočila
toolbar-get-messages =
    .title = Prejmi nova sporočila za vse račune
toolbar-reply-label = Odgovori
toolbar-reply =
    .title = Odgovori na sporočilo
toolbar-reply-all-label = Odgovori vsem
toolbar-reply-all =
    .title = Odgovori pošiljatelju in vsem prejemnikom
toolbar-reply-to-list-label = Odgovori seznamu
toolbar-reply-to-list =
    .title = Odgovori dopisnemu seznamu
toolbar-redirect-label = Preusmeri
toolbar-redirect =
    .title = Preusmeri izbrano sporočilo
toolbar-archive-label = Arhiviraj
toolbar-archive =
    .title = Arhiviraj izbrana sporočila
toolbar-conversation-label = Pogovor
toolbar-conversation =
    .title = Prikaži pogovor izbranega sporočila
toolbar-previous-unread-label = Prejšnje neprebrano
toolbar-previous-unread =
    .title = Pojdi na prejšnje neprebrano sporočilo
toolbar-previous-label = Prejšnje
toolbar-previous =
    .title = Pojdi na prejšnje sporočilo
toolbar-next-unread-label = Naslednje neprebrano
toolbar-next-unread =
    .title = Pojdi na naslednje neprebrano sporočilo
toolbar-next-label = Naslednje
toolbar-next =
    .title = Pojdi na naslednje sporočilo
toolbar-junk-label = Neželeno
toolbar-junk =
    .title = Označi izbrana sporočila kot neželena
toolbar-delete-label = Izbriši
toolbar-delete-title =
    .title = Izbriši izbrana sporočila
toolbar-undelete-label = Razveljavi izbris
toolbar-undelete =
    .title = Razveljavi izbris izbranih sporočil
toolbar-compact-label = Strni
toolbar-compact =
    .title = Odstrani izbrisana sporočila iz izbrane mape
toolbar-add-as-event-label = Dodaj kot dogodek
toolbar-add-as-event =
    .title = Izvleci koledarske podatke iz sporočila in jih dodaj k svojemu koledarju kot dogodek
toolbar-add-as-task-label = Dodaj kot opravilo
toolbar-add-as-task =
    .title = Izvleci koledarske podatke iz sporočila in jih dodaj k svojemu koledarju kot opravilo
toolbar-tag-message-label = Oznaka
toolbar-tag-message =
    .title = Označi sporočila
toolbar-forward-inline-label = Posreduj
toolbar-forward-inline =
    .title = Posreduj izbrano sporočilo v besedilu
toolbar-forward-attachment-label = Posreduj kot priponko
toolbar-forward-attachment =
    .title = Posreduj izbrano sporočilo kot priponko
toolbar-mark-as-label = Označi
toolbar-mark-as =
    .title = Označi sporočila
toolbar-view-picker-label = Pogled
toolbar-view-picker =
    .title = Prilagodi prikaz trenutne mape
toolbar-address-book-label = Imenik
toolbar-address-book =
    .title = Pojdi v imenik
toolbar-chat-label = Klepet
toolbar-chat =
    .title = Pokaži zavihek za klepet
toolbar-add-ons-and-themes-label = Dodatki in teme
toolbar-add-ons-and-themes =
    .title = Upravljanje dodatkov
toolbar-calendar-label = Koledar
toolbar-calendar =
    .title = Preklopi na zavihek s koledarji
toolbar-tasks-label = Opravila
toolbar-tasks =
    .title = Preklopi na zavihek z opravili
toolbar-mail-label = Pošta
toolbar-mail =
    .title = Preklopi na zavihek s pošto
toolbar-print-label = Natisni
toolbar-print =
    .title = Natisni to sporočilo
toolbar-quick-filter-bar-label = Hitri filter
toolbar-quick-filter-bar =
    .title = Filtriraj sporočila
toolbar-synchronize-label = Sinhroniziraj
toolbar-synchronize =
    .title = Ponovno naloži koledarje in sinhroniziraj spremembe
toolbar-delete-event-label = Izbriši
toolbar-delete-event =
    .title = Izbriši izbrane dogodke in opravila
toolbar-go-to-today-label = Pojdi na današnji dan
toolbar-go-to-today =
    .title = Pojdi na današnji dan
toolbar-print-event-label = Natisni
toolbar-print-event =
    .title = Natisni dogodke ali opravila
toolbar-new-event-label = Dogodek
toolbar-new-event =
    .title = Ustvari nov dogodek
toolbar-new-task-label = Opravilo
toolbar-new-task =
    .title = Ustvari novo opravilo
toolbar-go-back-label = Nazaj
toolbar-go-back =
    .title = Pojdi nazaj za eno sporočilo
toolbar-go-forward-label = Naprej
toolbar-go-forward =
    .title = Pojdi naprej za eno sporočilo
toolbar-stop-label = Ustavi
toolbar-stop =
    .title = Ustavi trenutni prenos
toolbar-throbber-label = Merilnik dejavnosti
toolbar-throbber =
    .title = Merilnik dejavnosti
toolbar-create-contact-label = Nov stik
toolbar-create-contact =
    .title = Ustvari nov stik
toolbar-create-address-book-label = Nov imenik
toolbar-create-address-book =
    .title = Ustvari nov imenik
toolbar-create-list-label = Nov seznam
toolbar-create-list =
    .title = Ustvari nov poštni seznam
toolbar-import-contacts-label = Uvozi
toolbar-import-contacts =
    .title = Uvozi stike iz datoteke

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Dodaj krajevni imenik
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Dodaj imenik CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Dodaj imenik LDAP
