# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espazo flexíbel
toolbar-write-message-label = Escribir
toolbar-write-message =
    .title = Crear nova mensaxe
toolbar-unifinder-label = Atopar eventos
toolbar-unifinder =
    .title = Activar/desactivar o panel de atopar eventos
toolbar-folder-location-label = Localización do cartafol
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar o evento ou tarefa seleccionada
toolbar-get-messages-label = Recibir mensaxes
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder á mensaxe
toolbar-reply-all-label = Responder a todos
toolbar-reply-all =
    .title = Responder ao remitente e a todos os destinatarios
toolbar-reply-to-list-label = Responder á lista
toolbar-reply-to-list =
    .title = Responder á lista de correo
toolbar-redirect-label = Redirixir
toolbar-redirect =
    .title = Redirixir as mensaxes seleccionadas
toolbar-archive-label = Arquivar
toolbar-archive =
    .title = Arquivar mensaxes seleccionadas
toolbar-conversation-label = Conversa
toolbar-conversation =
    .title = Amosar a conversa da mensaxe seleccionada
toolbar-previous-unread-label = Anterior mensaxe non lida
toolbar-previous-unread =
    .title = Ir á anterior mensaxe non lida
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Ir á anterior mensaxe
toolbar-next-unread-label = Seguinte mensaxe non lida
toolbar-next-unread =
    .title = Ir á seguinte mensaxe non lida
toolbar-next-label = Seguinte
toolbar-next =
    .title = Ir á seguinte mensaxe
toolbar-junk-label = Correo lixo
toolbar-junk =
    .title = Marcar as mensaxes seleccionadas como correo lixo
toolbar-delete-label = Eliminar
toolbar-delete =
    .title = Eliminar as mensaxes ou cartafoles seleccionados
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Retira as mensaxes eliminadas do cartafol seleccionado
toolbar-add-as-event-label = Engadir como evento
toolbar-add-as-event =
    .title = Extrae a información temporal da mensaxe e engádea ao calendario como un evento
toolbar-add-as-task-label = Engadir como tarefa
toolbar-add-as-task =
    .title = Extrae a información temporal da mensaxe e engádea ao calendario como unha tarefa
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Etiquetar mensaxes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar a mensaxe seleccionada como texto inserido
toolbar-forward-attachment-label = Reenviar como un anexo
toolbar-forward-attachment =
    .title = Reenviar a mensaxe seleccionada como un anexo
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensaxes
toolbar-address-book =
    .title = Ir á axenda de enderezos
toolbar-chat-label = Conversas
toolbar-chat =
    .title = Amosa a lapela das conversas
toolbar-add-ons-and-themes-label = Complementos e temas
toolbar-add-ons-and-themes =
    .title = Xestionar os complementos e temas
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Cambiar á lapela calendario
toolbar-tasks-label = Tarefas
toolbar-tasks =
    .title = Cambiar á lapela tarefas
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir esta mensaxe
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensaxes
