# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espazo flexíbel
search-bar-label = Buscar
toolbar-write-message-label = Escribir
toolbar-write-message =
    .title = Crear nova mensaxe
toolbar-move-to-label = Mover a
toolbar-move-to =
    .title = Mover a mensaxe seleccionada
toolbar-unifinder-label = Atopar eventos
toolbar-unifinder =
    .title = Activar/desactivar o panel de atopar eventos
toolbar-folder-location-label = Localización do cartafol
toolbar-folder-location =
    .title = Cambiar ao cartafol
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar o evento ou tarefa seleccionada
toolbar-get-messages-label = Recibir mensaxes
toolbar-get-messages =
    .title = Obtér mensaxes novas de todas as contas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder á mensaxe
toolbar-reply-all-label = Responder a todos
toolbar-reply-all =
    .title = Responder ao remitente e a todos os destinatarios
toolbar-reply-to-list-label = Responder á lista
toolbar-reply-to-list =
    .title = Responder á lista de correo
toolbar-redirect-label = Redirixir
toolbar-redirect =
    .title = Redirixir as mensaxes seleccionadas
toolbar-archive-label = Arquivar
toolbar-archive =
    .title = Arquivar mensaxes seleccionadas
toolbar-conversation-label = Conversa
toolbar-conversation =
    .title = Amosar a conversa da mensaxe seleccionada
toolbar-previous-unread-label = Anterior mensaxe non lida
toolbar-previous-unread =
    .title = Ir á anterior mensaxe non lida
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Ir á anterior mensaxe
toolbar-next-unread-label = Seguinte mensaxe non lida
toolbar-next-unread =
    .title = Ir á seguinte mensaxe non lida
toolbar-next-label = Seguinte
toolbar-next =
    .title = Ir á seguinte mensaxe
toolbar-junk-label = Correo lixo
toolbar-junk =
    .title = Marcar as mensaxes seleccionadas como correo lixo
toolbar-delete-label = Eliminar
toolbar-delete-title =
    .title = Elimina as mensaxes seleccionadas
toolbar-undelete-label = Restaurar
toolbar-undelete =
    .title = Restaurar as mensaxes seleccionadas
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Retira as mensaxes eliminadas do cartafol seleccionado
toolbar-add-as-event-label = Engadir como evento
toolbar-add-as-event =
    .title = Extrae a información temporal da mensaxe e engádea ao calendario como un evento
toolbar-add-as-task-label = Engadir como tarefa
toolbar-add-as-task =
    .title = Extrae a información temporal da mensaxe e engádea ao calendario como unha tarefa
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Etiquetar mensaxes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar a mensaxe seleccionada como texto inserido
toolbar-forward-attachment-label = Reenviar como un anexo
toolbar-forward-attachment =
    .title = Reenviar a mensaxe seleccionada como un anexo
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensaxes
toolbar-view-picker-label = Vista
toolbar-view-picker =
    .title = Personalizar a vista do cartafol actual
toolbar-address-book-label = Axenda de enderezos
toolbar-address-book =
    .title = Ir á axenda de enderezos
toolbar-chat-label = Conversas
toolbar-chat =
    .title = Amosa a lapela das conversas
toolbar-add-ons-and-themes-label = Complementos e temas
toolbar-add-ons-and-themes =
    .title = Xestionar os complementos e temas
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Cambiar á lapela calendario
toolbar-tasks-label = Tarefas
toolbar-tasks =
    .title = Cambiar á lapela tarefas
toolbar-mail-label = Correo
toolbar-mail =
    .title = Cambiar á lapela de correo
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir esta mensaxe
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensaxes
toolbar-synchronize-label = Sincronizar
toolbar-synchronize =
    .title = Recargar os calendarios e sincronizar os cambios
toolbar-delete-event-label = Eliminar
toolbar-delete-event =
    .title = Eliminar os eventos ou tarefas seleccionadas
toolbar-go-to-today-label = Ir ao día actual
toolbar-go-to-today =
    .title = Ir ao día actual
toolbar-print-event-label = Imprimir
toolbar-print-event =
    .title = Imprimir eventos ou tarefas
toolbar-new-event-label = Evento
toolbar-new-event =
    .title = Crear un novo evento
toolbar-new-task-label = Tarefa
toolbar-new-task =
    .title = Crear unha nova tarefa
toolbar-go-back-label = Atrás
toolbar-go-back =
    .title = Retroceder unha mensaxe
toolbar-go-forward-label = Adiante
toolbar-go-forward =
    .title = Avanzar unha mensaxe
toolbar-stop-label = Deter
toolbar-stop =
    .title = Parar a transferencia actual
toolbar-throbber-label = Indicador de actividade
toolbar-throbber =
    .title = Indicador de actividade
toolbar-create-contact-label = Novo contacto
toolbar-create-contact =
    .title = Crear un novo contacto
toolbar-create-address-book-label = Nova axenda de enderezos
toolbar-create-address-book =
    .title = Crear unha nova axenda de enderezos
toolbar-create-list-label = Nova lista
toolbar-create-list =
    .title = Crear unha nova lista de correo
toolbar-import-contacts-label = Importar
toolbar-import-contacts =
    .title = Importar contactos dun ficheiro

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Engadir unha axenda de enderezos local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Engadir unha axenda de enderezos CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Engadir unha axenda de enderezos LDAP
