# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Ime za prikaz
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Vrsta
vcard-entry-type-home = Kuća
vcard-entry-type-work = Posao
vcard-entry-type-none = Ništa
vcard-entry-type-custom = Prilagođeno
vcard-name-header = Naziv
vcard-n-prefix = Prefiks
vcard-n-add-prefix =
    .title = Dodaj prefiks
vcard-n-firstname = Ime
vcard-n-add-firstname =
    .title = Dodaj ime
vcard-n-middlename = Srednje ime
vcard-n-add-middlename =
    .title = Dodaj srednje ime
vcard-n-lastname = Prezime
vcard-n-add-lastname =
    .title = Dodaj prezime
vcard-n-suffix = Sufiks
vcard-n-add-suffix =
    .title = Dodaj sufiks
vcard-nickname = Nadimak
vcard-email-header = Adrese e-pošte
vcard-email-add = Dodaj adrese e-pošte
vcard-email-label = Adresa e-pošte
vcard-primary-email-label = Zadano
vcard-url-header = Web stranice
vcard-url-add = Dodaj web stranice
vcard-url-label = Web stranica
vcard-tel-header = Brojevi telefona
vcard-tel-add = Dodaj broj telefona
vcard-tel-label = Broj telefona
# Or "Mobile"
vcard-entry-type-cell = Mobitel
vcard-entry-type-fax = Faks
vcard-entry-type-pager = Pager
vcard-tz-header = Vremenska zona
vcard-tz-add = Dodaj vremensku zonu
vcard-impp2-header = Instant poruke
vcard-impp-add = Dodaj račun razgovora
vcard-impp-label = Račun razgovora
vcard-impp-select = Protokol
vcard-impp-option-other = Ostalo
vcard-impp-input-label = URI
vcard-impp-input-title = URI za instant poruke
vcard-bday-anniversary-header = Posebni datumi
vcard-bday-anniversary-add = Dodaj poseban datum
vcard-bday-label = Rođendan
vcard-anniversary-label = Godišnjica
vcard-date-day = Dan
vcard-date-month = Mjesec
vcard-date-year = Godina
vcard-adr-header = Adrese
vcard-adr-add = Dodaj adresu
vcard-adr-label = Adresa
vcard-adr-delivery-label = Oznaka za isporuku
vcard-adr-street = Ulica
# Or "Locality"
vcard-adr-locality = Grad
# Or "Region"
vcard-adr-region = Država/pokrajina
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Poštanski broj
vcard-adr-country = Država
vcard-note-header = Bilješke
vcard-note-add = Dodaj bilješku
vcard-org-header = Svojstva organizacije
vcard-org-add = Dodaj svojstva organizacije
vcard-org-title = Naslov
vcard-org-title-input =
    .placeholder = Naziv posla
    .title = Pozicija ili posao
vcard-org-role = Uloga
vcard-org-role-input =
    .placeholder = Uloga u projektu
    .title = Funkcija ili uloga u određenoj situaciji
vcard-org-org = Organizacija
vcard-org-org-input =
    .placeholder = Naziv tvrtke
    .title = Naziv organizacije
vcard-org-org-unit = Odjel
vcard-org-org-unit-input =
    .placeholder = Odjel
    .title = Naziv organizacijske jedinice
vcard-custom-header = Prilagođene postavke
vcard-custom-add = Dodaj prilagođene postavke
vcard-remove-button-title =
    .title = Ukloni
vcard-remove-button = Ukloni
