# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

day-1-name =
    .label = អាទិត្យ
day-2-name =
    .label = ច័ន្ទ
day-3-name =
    .label = អង្គារ
day-4-name =
    .label = ពុធ
day-5-name =
    .label = ព្រហស្បតិ៍​
day-6-name =
    .label = សុក្រ
day-7-name =
    .label = សៅរ៍​
dayweek-legend = ទិដ្ឋភាពថ្ងៃ និងសប្តាហ៍
midnight-label =
    .label = អធ្រាត្រ
noon-label =
    .label = ថ្ងៃ​ត្រង់
week-0-label =
    .label = គ្មាន
week-1-label =
    .label = 1 សប្តាហ៍
week-2-label =
    .label = 2 សប្តាហ៍
week-3-label =
    .label = 3 សប្តាហ៍
week-4-label =
    .label = 4 សប្តាហ៍
week-5-label =
    .label = 5 សប្តាហ៍
week-6-label =
    .label = 6 សប្តាហ៍
todaypane-legend = ផ្ទាំងថ្ងៃនេះ
task-start-label =
    .value = ថ្ងៃផ្តើម៖
task-start-1-label =
    .label = គ្មាន
task-start-2-label =
    .label = ថ្ងៃ នៃចាប់ផ្តើម
task-start-3-label =
    .label = ថ្ងៃ នៃការបញ្ចប់
task-start-4-label =
    .label = ថ្ងៃស្អែក
task-start-5-label =
    .label = សប្តាហ៍ក្រោយ
task-start-6-label =
    .label = ទាក់ទងទៅនឹងពេលវេលាបច្ចុប្បន្ន
task-start-7-label =
    .label = ទាក់ទងទៅនឹងការចាប់ផ្តើម
category-new-label = ប្រភេទថ្មី
category-edit-label = កែសម្រួលប្រភេទ
category-overwrite-title = ការព្រមាន៖ ឈ្មោះស្ទួន
category-blank-warning = អ្នកត្រូវតែបញ្ចូលឈ្មោះប្រភេទ។
