# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Opmerking
calendar-item-summary-title = Titel:
calendar-item-summary-calendar = Aginda:
calendar-item-summary-task-start = Startdatum:
calendar-item-summary-event-start = Startdatum:
calendar-item-summary-task-due = Ferrindatum:
calendar-item-summary-event-end = Eindatum:
calendar-item-summary-repeat = Werhelje:
calendar-item-summary-location = Lokaasje:
calendar-item-summary-category = Kategory:
calendar-item-summary-organizer = Organisator:
calendar-item-summary-status = Steat:
calendar-item-summary-reminder = Omtinken:
calendar-item-summary-attachments = Bylagen:
calendar-item-summary-status-tentative = Foarlopich
calendar-item-summary-status-confirmed = Befêstige
calendar-item-summary-event-status-cancelled = Annulearre
calendar-item-summary-todo-status-cancelled = Annulearre
calendar-item-summary-status-needs-action = Hanneling fereaske
calendar-item-summary-status-in-process = Dwaande
calendar-item-summary-status-completed = Foltôge op
calendar-item-summary-reminder-none =
    .label = Gjin omtinken
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuten dêrfoar
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuten dêrfoar
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuten dêrfoar
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuten dêrfoar
calendar-item-summary-reminder-1-hour-before =
    .label = 1 oer dêrfoar
calendar-item-summary-reminder-2-hours-before =
    .label = 2 oer dêrfoar
calendar-item-summary-reminder-12-hours-before =
    .label = 12 oer dêrfoar
calendar-item-summary-reminder-1-day-before =
    .label = 1 dei dêrfoar
calendar-item-summary-reminder-2-days-before =
    .label = 2 dagen dêrfoar
calendar-item-summary-reminder-1-week-before =
    .label = 1 wike dêrfoar
calendar-item-summary-reminder-custom =
    .label = Oanpast…
calendar-item-summary-reminder-multiple =
    .value = Mear oantinkens…
calendar-item-summary-general =
    .value = Algemien
calendar-item-summary-attendees =
    .value = Dielnimmers
calendar-item-summary-description =
    .value = Beskriuwing
calendar-item-summary-link =
    .value = Byhearrende keppeling
