# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = is in werheljend barren
header-isrepeating-task =
    .label = is in werheljende taak
header-containsrepeating-event =
    .label = befettet werheljende barrens
header-containsrepeating-task =
    .label = befettet werheljende taken
header-containsrepeating-mixed =
    .label = befettet werheljend items fan ferskate typen
windowtitle-event-copy = Werheljend barren kopiearje
windowtitle-task-copy = Werheljende taak kopiearje
windowtitle-mixed-copy = Werheljende items kopiearje
windowtitle-event-cut = Werheljend barren knippe
windowtitle-task-cut = Werheljende taak knippe
windowtitle-mixed-cut = Werheljende items knippe
windowtitle-event-delete = Werheljend barren fuortsmite
windowtitle-task-delete = Werheljende taak fuortsmite
windowtitle-mixed-delete = Werheljende items fuortsmite
windowtitle-event-edit = Werheljend barren bewurkje
windowtitle-task-edit = Werheljende taak bewurkje
windowtitle-mixed-edit = Werheljende items bewurkje
windowtitle-multipleitems =
    .value = Selektearre items
button-single-occurrence-copy =
    .label = Allinnich dit eksimplaar kopiearje
    .accesskey = d
button-single-occurrence-cut =
    .label = Allinnich dit eksimplaar knippe
    .accesskey = d
button-single-occurrence-delete =
    .label = Allinnich dit eksimplaar fuortsmite
    .accesskey = d
button-single-occurrence-edit =
    .label = Allinnich dit eksimplaar bewurkje
    .accesskey = d
button-multiple-occurrence-copy =
    .label = Allinnich selektearre rige kopiearje
    .accesskey = d
button-multiple-occurrence-cut =
    .label = Allinnich selektearre rige knippe
    .accesskey = d
button-multiple-occurrence-delete =
    .label = Allinnich selektearre rige fuortsmite
    .accesskey = d
button-multiple-occurrence-edit =
    .label = Allinnich selektearre rige bewurkje
    .accesskey = d
button-single-allfollowing-copy =
    .label = Dizze en alle folgjende eksimplaren kopiearje
    .accesskey = v
button-single-allfollowing-cut =
    .label = Dizze en alle folgjende eksimplaren knippe
    .accesskey = v
button-single-allfollowing-delete =
    .label = Dizze en alle folgjende eksimplaren fuortsmite
    .accesskey = v
button-single-allfollowing-edit =
    .label = Dizze en alle folgjende eksimplaren bewurkje
    .accesskey = v
button-multiple-allfollowing-copy =
    .label = Selektearre en alle folgjende eksimplaren kopiearje
    .accesskey = v
button-multiple-allfollowing-cut =
    .label = Selektearre en alle folgjende eksimplaren knippe
    .accesskey = v
button-multiple-allfollowing-delete =
    .label = Selektearre en alle folgjende eksimplaren fuortsmite
    .accesskey = v
button-multiple-allfollowing-edit =
    .label = Selektearre en alle folgjende eksimplaren bewurkje
    .accesskey = v
button-single-parent-copy =
    .label = Alle eksimplaren kopiearje
    .accesskey = A
button-single-parent-cut =
    .label = Alle eksimplaren knippe
    .accesskey = A
button-single-parent-delete =
    .label = Alle eksimplaren fuortsmite
    .accesskey = A
button-single-parent-edit =
    .label = Alle eksimplaren bewurkje
    .accesskey = A
button-multiple-parent-copy =
    .label = Alle eksimplaren fan selektearre items kopiearje
    .accesskey = A
button-multiple-parent-cut =
    .label = Alle eksimplaren fan selektearre items knippe
    .accesskey = A
button-multiple-parent-delete =
    .label = Alle eksimplaren fan selektearre items fuortsmite
    .accesskey = A
button-multiple-parent-edit =
    .label = Alle eksimplaren fan selektearre items bewurkje
    .accesskey = A
buttons-single-occurrence-copy =
    .label = Allinnich dit eksimplaar kopiearje
buttons-single-occurrence-cut =
    .label = Allinnich dit eksimplaar knippe
buttons-single-occurrence-delete =
    .label = Allinnich dit eksimplaar fuortsmite
buttons-single-occurrence-edit =
    .label = Allinnich dit eksimplaar bewurkje
buttons-multiple-occurrence-copy =
    .label = Allinnich selektearre rige kopiearje
buttons-multiple-occurrence-cut =
    .label = Allinnich selektearre rige knippe
buttons-multiple-occurrence-delete =
    .label = Allinnich selektearre rige fuortsmite
buttons-multiple-occurrence-edit =
    .label = Allinnich selektearre rige bewurkje
buttons-single-allfollowing-copy =
    .label = Dizze en alle folgjende eksimplaren kopiearje
buttons-single-allfollowing-cut =
    .label = Dizze en alle folgjende eksimplaren knippe
buttons-single-allfollowing-delete =
    .label = Dizze en alle folgjende eksimplaren fuortsmite
buttons-single-allfollowing-edit =
    .label = Dizze en alle folgjende eksimplaren bewurkje
buttons-multiple-allfollowing-copy =
    .label = Selektearre en alle folgjende eksimplaren kopiearje
buttons-multiple-allfollowing-cut =
    .label = Selektearre en alle folgjende eksimplaren knippe
buttons-multiple-allfollowing-delete =
    .label = Selektearre en alle folgjende eksimplaren fuortsmite
buttons-multiple-allfollowing-edit =
    .label = Selektearre en alle folgjende eksimplaren bewurkje
buttons-single-parent-copy =
    .label = Alle eksimplaren kopiearje
buttons-single-parent-cut =
    .label = Alle eksimplaren knippe
buttons-single-parent-delete =
    .label = Alle eksimplaren fuortsmite
buttons-single-parent-edit =
    .label = Alle eksimplaren bewurkje
buttons-multiple-parent-copy =
    .label = Alle eksimplaren fan selektearre items kopiearje
buttons-multiple-parent-cut =
    .label = Alle eksimplaren fan selektearre items knippe
buttons-multiple-parent-delete =
    .label = Alle eksimplaren fan selektearre items fuortsmite
buttons-multiple-parent-edit =
    .label = Alle eksimplaren fan selektearre items bewurkje
