# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Alles selektearje
select-none-calendars = Neat selektearje
calendar-creation-wizard-title = Nije aginda meitsje
calendar-creation-initial-description = Jo aginda kin op jo kompjûter of op in server bewarre wurde, sadat dizze op ôfstân berikber is foar bygelyks freonen of kollega’s.
calendar-creation-initial-computer =
    .label = Op myn kompjûter
calendar-creation-initial-network =
    .label = Op it netwurk
calendar-creation-username =
    .value = Brûkersnamme:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Aginda oanmeitsje
    .buttonaccesskeyaccept = m
    .buttonlabelextra2 = Tebek
    .buttonaccesskeyextra2 = T
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Aginda oanmeitsje
    .buttonaccesskeyaccept = m
    .buttonlabelextra2 = Tebek
    .buttonaccesskeyextra2 = T
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Aginda’s sykje
    .buttonaccesskeyaccept = s
    .buttonlabelextra2 = Tebek
    .buttonaccesskeyextra2 = T
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonnearje
    .buttonaccesskeyaccept = A
    .buttonlabelextra2 = Tebek
    .buttonaccesskeyextra2 = T
calendar-creation-type =
    .value = Agindatype:
calendar-creation-location =
    .value = Lokaasje:
calendar-creation-location-placeholder =
    .placeholder = URL of hostnamme fan de agindaserver
    .default-placeholder = URL of hostnamme fan de agindaserver
calendar-creation-network-nocredentials =
    .label = Dizze lokaasje fereasket gjin ferifikaasje
calendar-creation-network-loading = Ien momint, jo aginda’s wurde detektearre.
calendar-creation-network-notfound = Der binne gjin aginda’s op dizze lokaasje fûn. Kontrolearje jo ynstellingen.
calendar-creation-network-authfail = De ynfierde referinsjes waarden net akseptearre. Kontrolearje jo ynstellingen.
calendar-creation-network-certerror = Kin gjin aginda’s op dizze lokaasje fine, fanwegen in sertifikaatprobleem.
calendar-creation-network-subscribe-single = Selektearje de aginda’s wêrop jo jo abonnearje wolle.
calendar-creation-network-subscribe-multiple = Foar dizze lokaasje binne mear agindatypen beskikber. Selektearje it agindatype, en markearje dêrnei de aginda’s wêrop jo jo abonnearje wolle.
