# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Khoảng cách linh động
search-bar-label = Tìm kiếm
toolbar-write-message-label = Viết thư
toolbar-write-message =
    .title = Tạo một thư mới
toolbar-move-to-label = Di chuyển tới
toolbar-move-to =
    .title = Di chuyển thư đã chọn
toolbar-unifinder-label = Tìm sự kiện
toolbar-unifinder =
    .title = Chuyển đến khung tìm sự kiện
toolbar-folder-location-label = Địa chỉ thư mục
toolbar-folder-location =
    .title = Chuyển sang thư mục
toolbar-edit-event-label = Chỉnh sửa
toolbar-edit-event =
    .title = Chỉnh sửa sự kiện hoặc nhiệm vụ được chọn
toolbar-get-messages-label = Nhận thư
toolbar-get-messages =
    .title = Tìm thư mới cho tất cả các tài khoản
toolbar-reply-label = Trả lời
toolbar-reply =
    .title = Trả lời thư
toolbar-reply-all-label = Trả lời tất cả
toolbar-reply-all =
    .title = Trả lời người gửi và tất cả người nhận
toolbar-reply-to-list-label = Trả lời danh sách
toolbar-reply-to-list =
    .title = Trả lời danh sách thư
toolbar-redirect-label = Chuyển hướng
toolbar-redirect =
    .title = Chuyển hướng tin nhắn đã chọn
toolbar-archive-label = Lưu trữ
toolbar-archive =
    .title = Lưu trữ các thư đã chọn
toolbar-conversation-label = Hội thoại
toolbar-conversation =
    .title = Hiển thị cuộc hội thoại của thư đã chọn
toolbar-previous-unread-label = Thư chưa đọc trước đó
toolbar-previous-unread =
    .title = Chuyển sang thư chưa đọc phía trước
toolbar-previous-label = Trước
toolbar-previous =
    .title = Di chuyển đến thư trước
toolbar-next-unread-label = Thư chưa đọc tiếp theo
toolbar-next-unread =
    .title = Chuyển sang thư chưa đọc tiếp theo
toolbar-next-label = Tiếp theo
toolbar-next =
    .title = Di chuyển đến thư kế tiếp
toolbar-junk-label = Thư rác
toolbar-junk =
    .title = Đánh dấu các thư đã chọn là thư rác
toolbar-delete-label = Xóa
toolbar-delete-title =
    .title = Xóa thư đã chọn
toolbar-undelete-label = Hoàn tác xóa
toolbar-undelete =
    .title = Hoàn tác xóa các thư đã chọn
toolbar-compact-label = Làm gọn
toolbar-compact =
    .title = Dọn các thư bị xóa ra khỏi thư mục đã chọn
toolbar-add-as-event-label = Thêm dưới dạng sự kiện
toolbar-add-as-event =
    .title = Trích xuất thông tin lịch từ tin nhắn và thêm nó vào lịch của bạn như một sự kiện
toolbar-add-as-task-label = Thêm dưới dạng nhiệm vụ
toolbar-add-as-task =
    .title = Trích xuất thông tin lịch từ tin nhắn và thêm nó vào lịch của bạn như là một nhiệm vụ
toolbar-tag-message-label = Nhãn
toolbar-tag-message =
    .title = Dán nhãn cho thư
toolbar-forward-inline-label = Chuyển tiếp
toolbar-forward-inline =
    .title = Chuyển tiếp thư được chọn dưới dạng văn bản ngay trong thư
toolbar-forward-attachment-label = Chuyển tiếp dưới dạng đính kèm
toolbar-forward-attachment =
    .title = Chuyển tiếp thư được chọn dưới dạng đính kèm
toolbar-mark-as-label = Đánh dấu
toolbar-mark-as =
    .title = Đánh dấu thư
toolbar-view-picker-label = Xem
toolbar-view-picker =
    .title = Tùy chỉnh chế độ xem thư mục hiện tại
toolbar-address-book-label = Sổ địa chỉ
toolbar-address-book =
    .title = Vào sổ địa chỉ
toolbar-chat-label = Trò chuyện
toolbar-chat =
    .title = Hiển thị thẻ trò chuyện
toolbar-add-ons-and-themes-label = Tiện ích mở rộng và chủ đề
toolbar-add-ons-and-themes =
    .title = Quản lý tiện ích của bạn
toolbar-calendar-label = Lịch
toolbar-calendar =
    .title = Chuyển sang thẻ lịch
toolbar-tasks-label = Nhiệm vụ
toolbar-tasks =
    .title = Chuyển sang thẻ nhiệm vụ
toolbar-mail-label = Thư
toolbar-mail =
    .title = Chuyển sang thẻ thư
toolbar-print-label = In
toolbar-print =
    .title = In thư này
toolbar-quick-filter-bar-label = Bộ lọc nhanh
toolbar-quick-filter-bar =
    .title = Lọc thư
toolbar-synchronize-label = Đồng bộ hoá
toolbar-synchronize =
    .title = Tải lại lịch và đồng bộ hóa các thay đổi
toolbar-delete-event-label = Xóa
toolbar-delete-event =
    .title = Xóa các sự kiện hoặc nhiệm vụ được chọn
toolbar-go-to-today-label = Đi đến hôm nay
toolbar-go-to-today =
    .title = Đi đến hôm nay
toolbar-print-event-label = In
toolbar-print-event =
    .title = In sự kiện hoặc nhiệm vụ
toolbar-new-event-label = Sự kiện
toolbar-new-event =
    .title = Tạo một sự kiện mới
toolbar-new-task-label = Nhiệm vụ
toolbar-new-task =
    .title = Tạo một nhiệm vụ mới
toolbar-go-back-label = Quay lại
toolbar-go-back =
    .title = Trở lại một thư
toolbar-go-forward-label = Tiến
toolbar-go-forward =
    .title = Đi tới một thư
toolbar-stop-label = Dừng
toolbar-stop =
    .title = Dừng việc truyền tải hiện tại
toolbar-throbber-label = Chỉ báo hoạt động
toolbar-throbber =
    .title = Chỉ báo hoạt động
toolbar-create-contact-label = Liên hệ mới
toolbar-create-contact =
    .title = Tạo một liên hệ mới
toolbar-create-address-book-label = Sổ địa chỉ mới
toolbar-create-address-book =
    .title = Tạo một sổ địa chỉ mới
toolbar-create-list-label = Danh sách mới
toolbar-create-list =
    .title = Tạo một danh sách gửi thư mới
toolbar-import-contacts-label = Nhập
toolbar-import-contacts =
    .title = Nhập liên hệ từ tập tin

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Thêm sổ địa chỉ cục bộ
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Thêm sổ địa chỉ CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Thêm sổ địa chỉ LDAP
