# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Valitse kaikki
select-none-calendars = Älä valitse mitään
calendar-creation-wizard-title = Luo uusi kalenteri
calendar-creation-initial-description = Kalenterin voi tallentaa joko tälle tietokoneelle tai palvelimelle, jolloin sitä voi käyttää verkossa. Voit myös jakaa jonkin kalenterin ystäviesi tai työtovereidesi kanssa.
calendar-creation-initial-computer =
    .label = Tällä tietokoneella
calendar-creation-initial-network =
    .label = Verkossa
calendar-creation-username =
    .value = Käyttäjätunnus:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Luo kalenteri
    .buttonaccesskeyaccept = L
    .buttonlabelextra2 = Takaisin
    .buttonaccesskeyextra2 = T
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Luo kalenteri
    .buttonaccesskeyaccept = L
    .buttonlabelextra2 = Takaisin
    .buttonaccesskeyextra2 = T
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Etsi kalentereita
    .buttonaccesskeyaccept = E
    .buttonlabelextra2 = Takaisin
    .buttonaccesskeyextra2 = T
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Tilaa
    .buttonaccesskeyaccept = i
    .buttonlabelextra2 = Takaisin
    .buttonaccesskeyextra2 = T
calendar-creation-type =
    .value = Kalenterin tyyppi:
calendar-creation-location =
    .value = Sijainti:
calendar-creation-location-placeholder =
    .placeholder = Kalenteripalvelimen URL tai palvelinnimi
    .default-placeholder = Kalenteripalvelimen URL tai palvelinnimi
calendar-creation-network-nocredentials =
    .label = Tämä sijainti ei vaadi kirjautumistietoja
calendar-creation-network-loading = Odota hetki, kalentereitasi etsitään.
calendar-creation-network-notfound = Tästä sijainnista ei löytynyt kalentereita. Tarkista asetukset.
calendar-creation-network-authfail = Syöttämiäsi kirjautumistietoja ei hyväksytty. Tarkista asetukset.
calendar-creation-network-certerror = Kalentereita ei löytynyt tästä sijainnista varmenneongelman vuoksi.
calendar-creation-network-subscribe-single = Valitse kalenterit, jotka haluat tilata.
calendar-creation-network-subscribe-multiple = Tässä sijainnissa on monen tyyppisiä kalentereita. Valitse ensin kalenterin tyyppi ja valitse sitten kalenterit, jotka haluat tilata.
