# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-deactivated-notification-events = Kaikki kalenterit ovat tällä hetkellä poissa käytöstä. Ota olemassa oleva kalenteri käyttöön tai lisää uusi luodaksesi ja muokataksesi tapahtumia.
calendar-deactivated-notification-tasks = Kaikki kalenterit ovat tällä hetkellä poissa käytöstä. Ota olemassa oleva kalenteri käyttöön tai lisää uusi luodaksesi ja muokataksesi tehtäviä.
calendar-notifications-label = Näytä ilmoitukset tulevista tapahtumista
calendar-add-notification-button =
    .label = Lisää ilmoitus
calendar-import-new-calendar = Uusi kalenteri…
    .title = Luo tai tilaa uusi kalenteri
calendar-refresh-calendars =
    .title = Lataa kaikki kalenterit uudelleen ja synkronoi muutokset
calendar-new-event-primary-button = Uusi tapahtuma
calendar-new-task-primary-button = Uusi tehtävä
calendar-nav-button-prev-tooltip-day =
    .title = Edellinen päivä
    .accesskey = E
calendar-nav-button-prev-tooltip-week =
    .title = Edellinen viikko
    .accesskey = E
calendar-nav-button-prev-tooltip-multiweek =
    .title = Edellinen viikko
    .accesskey = E
calendar-nav-button-prev-tooltip-month =
    .title = Edellinen kuukausi
    .accesskey = E
calendar-nav-button-next-tooltip-day =
    .title = Seuraava päivä
    .accesskey = U
calendar-nav-button-next-tooltip-week =
    .title = Seuraava viikko
    .accesskey = U
calendar-nav-button-next-tooltip-multiweek =
    .title = Seuraava viikko
    .accesskey = U
calendar-nav-button-next-tooltip-month =
    .title = Seuraava kuukausi
    .accesskey = U
calendar-today-button-tooltip =
    .title = Siirry tähän päivään
calendar-view-toggle-day = Päivä
    .title = Siirry päivänäkymään
calendar-view-toggle-week = Viikko
    .title = Siirry viikkonäkymään
calendar-view-toggle-multiweek = Moniviikko
    .title = Siirry moniviikkonäkymään
calendar-view-toggle-month = Kuukausi
    .title = Siirry kuukausinäkymään
