# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Kommentti
calendar-item-summary-title = Otsikko:
calendar-item-summary-calendar = Kalenteri:
calendar-item-summary-task-start = Aloitusaika:
calendar-item-summary-event-start = Aloitusaika:
calendar-item-summary-task-due = Valmis:
calendar-item-summary-event-end = Lopetusaika:
calendar-item-summary-repeat = Toista:
calendar-item-summary-location = Sijainti:
calendar-item-summary-category = Kategoria:
calendar-item-summary-organizer = Järjestäjä:
calendar-item-summary-status = Tila:
calendar-item-summary-reminder = Muistuta:
calendar-item-summary-attachments = Liitteet:
calendar-item-summary-status-tentative = Alustava
calendar-item-summary-status-confirmed = Vahvistettu
calendar-item-summary-event-status-cancelled = Peruttu
calendar-item-summary-todo-status-cancelled = Peruttu
calendar-item-summary-status-needs-action = Tarvitsee toimintaa
calendar-item-summary-status-in-process = Käynnissä
calendar-item-summary-status-completed = Valmistui
calendar-item-summary-reminder-none =
    .label = Ei muistutusta
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuuttia ennen
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuuttia ennen
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuuttia ennen
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuuttia ennen
calendar-item-summary-reminder-1-hour-before =
    .label = 1 tunti ennen
calendar-item-summary-reminder-2-hours-before =
    .label = 2 tuntia ennen
calendar-item-summary-reminder-12-hours-before =
    .label = 12 tuntia ennen
calendar-item-summary-reminder-1-day-before =
    .label = 1 päivä ennen
calendar-item-summary-reminder-2-days-before =
    .label = 2 päivää ennen
calendar-item-summary-reminder-1-week-before =
    .label = 1 viikko ennen
calendar-item-summary-reminder-custom =
    .label = Oma…
calendar-item-summary-reminder-multiple =
    .value = Useita muistutuksia…
calendar-item-summary-general =
    .value = Yleistiedot
calendar-item-summary-attendees =
    .value = Osallistujat
calendar-item-summary-description =
    .value = Kuvaus
calendar-item-summary-link =
    .value = Aiheeseen liittyvä linkki
