# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = დრეკადი არე
search-bar-label = ძიება
toolbar-write-message-label = მიწერა
toolbar-write-message =
    .title = ახალი წერილის შექმნა
toolbar-move-to-label = გადატანა
toolbar-move-to =
    .title = შერჩეული წერილის გადატანა
toolbar-unifinder-label = ღონისძიების მონახვა
toolbar-unifinder =
    .title = ღონისძიების საძიებო არის გახსნა/დახურვა
toolbar-folder-location-label = საქაღალდის მისამართი
toolbar-folder-location =
    .title = გადართვა საქაღალდეზე
toolbar-edit-event-label = ჩასწორება
toolbar-edit-event =
    .title = შერჩეული ღონისძიებების ან დავალებების ჩასწორება
toolbar-get-messages-label = წერილების მიღება
toolbar-get-messages =
    .title = ახალი წერილების მიღება ყველა ანგარიშისთვის
toolbar-reply-label = პასუხი
toolbar-reply =
    .title = პასუხი წერილს
toolbar-reply-all-label = პასუხი ყველას
toolbar-reply-all =
    .title = პასუხი გამომგზავნს და ყველა მიმღებს
toolbar-reply-to-list-label = პასუხი ჯგუფს
toolbar-reply-to-list =
    .title = პასუხი ჯგუფს
toolbar-redirect-label = გადამისამართება
toolbar-redirect =
    .title = გადაამისამართეთ შერჩეული წერილები
toolbar-archive-label = არქივი
toolbar-archive =
    .title = შერჩეული წერილის დაარქივება
toolbar-conversation-label = საუბარი
toolbar-conversation =
    .title = მითითებული შეტყობინების სრული საუბრის ჩვენება
toolbar-previous-unread-label = წინა წასაკითხი
toolbar-previous-unread =
    .title = გადასვლა წინა წასაკითხ წერილზე
toolbar-previous-label = წინა
toolbar-previous =
    .title = გადასვლა წინა წერილზე
toolbar-next-unread-label = შემდეგი წასაკითხი
toolbar-next-unread =
    .title = გადასვლა შემდეგ წასაკითხ წერილზე
toolbar-next-label = შემდეგი
toolbar-next =
    .title = გადასვლა შემდეგ წერილზე
toolbar-junk-label = ჯართი
toolbar-junk =
    .title = მონიშნეთ წერილი უსარგებლოდ
toolbar-delete-label = წაშლა
toolbar-delete-title =
    .title = შერჩეული წერილების წაშლა
toolbar-undelete-label = აღდგენა
toolbar-undelete =
    .title = შერჩეული წერილების აღდგენა
toolbar-compact-label = შეკუმშვა
toolbar-compact =
    .title = წაშლილი წერილების მოცილება შერჩეული საქაღალდიდან
toolbar-add-as-event-label = ღონისძიების სახით დამატება
toolbar-add-as-event =
    .title = კალენდარული მონაცემის ამოღება გზავნილიდან და თქვენს კალენდარში, ღონისძიების სახით, დამატება
toolbar-add-as-task-label = დავალების სახით დამატება
toolbar-add-as-task =
    .title = კალენდარული მონაცემის ამოღება გზავნილიდან და თქვენს კალენდარში, როგორც ამოცანის, დამატება
toolbar-tag-message-label = ჭდე
toolbar-tag-message =
    .title = წერილების დაჭდევება
toolbar-forward-inline-label = გადაგზავნა
toolbar-forward-inline =
    .title = შერჩეული წერილის გადაგზავნა შიდა ტექსტის სახით
toolbar-forward-attachment-label = გადაგზავნა დანართის სახით
toolbar-forward-attachment =
    .title = შერჩეული წერილის გადაგზავნა დანართის სახით
toolbar-mark-as-label = მონიშვნა
toolbar-mark-as =
    .title = წერილების მონიშვნა
toolbar-view-picker-label = ხედი
toolbar-view-picker =
    .title = მიმდინარე საქაღალდის ხედის მორგება
toolbar-address-book-label = წიგნაკი
toolbar-address-book =
    .title = წიგნაკზე გადასვლა
toolbar-chat-label = სასაუბრო
toolbar-chat =
    .title = სასაუბრო არეს ჩვენება
toolbar-add-ons-and-themes-label = დამატებები და თემები
toolbar-add-ons-and-themes =
    .title = მართეთ დამატებები
toolbar-calendar-label = კალენდარი
toolbar-calendar =
    .title = გადასვლა კალენდრის დაფაზე
toolbar-tasks-label = დავალებები
toolbar-tasks =
    .title = გადასვლა დავალებების დაფაზე
toolbar-mail-label = ფოსტა
toolbar-mail =
    .title = გადასვლა ფოსტის ჩანართზე
toolbar-print-label = ბეჭდვა
toolbar-print =
    .title = წერილის დაბეჭდვა
toolbar-quick-filter-bar-label = სწრაფი ფილტრი
toolbar-quick-filter-bar =
    .title = განარჩიეთ წერილები
toolbar-synchronize-label = სინქრონიზაცია
toolbar-synchronize =
    .title = კალენდრის ხელახლა ჩატვირთვა და ცვლილებების დასინქრონება
toolbar-delete-event-label = წაშლა
toolbar-delete-event =
    .title = შერჩეული ღონისძიებების ან დავალებების წაშლა
toolbar-go-to-today-label = დღევანდელზე გადასვლა
toolbar-go-to-today =
    .title = დღევანდელზე გადასვლა
toolbar-print-event-label = ამობეჭდვა
toolbar-print-event =
    .title = ღონისძიებების ან დავალებების ამობეჭდვა
toolbar-new-event-label = ღონისძიება
toolbar-new-event =
    .title = ახალი ღონისძიების შექმნა
toolbar-new-task-label = დავალება
toolbar-new-task =
    .title = ახალი დავალების შექმნა
toolbar-go-back-label = უკან დაბრუნება
toolbar-go-back =
    .title = წინა წერილზე დაბრუნება
toolbar-go-forward-label = წინ გადასვლა
toolbar-go-forward =
    .title = მომდევნო წერილზე გადასვლა
toolbar-stop-label = შეჩერება
toolbar-stop =
    .title = მიმდინარე გაგზავნის შეჩერება
toolbar-throbber-label = აქტიობის მაჩვენებელი
toolbar-throbber =
    .title = აქტიობის მაჩვენებელი
