# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Выбрать всё
select-none-calendars = Снять выделение
calendar-creation-wizard-title = Создание нового календаря
calendar-creation-initial-description = Ваш календарь может быть сохранён на вашем компьютере или на удалённом сервере для того, чтобы вы могли обратиться к нему из любого места или использовать его совместно с вашими друзьями или коллегами.
calendar-creation-initial-computer =
    .label = На моём компьютере
calendar-creation-initial-network =
    .label = В сети
calendar-creation-username =
    .value = Имя пользователя:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Создать календарь
    .buttonaccesskeyaccept = к
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = И
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Создать календарь
    .buttonaccesskeyaccept = к
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = И
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Найти календари
    .buttonaccesskeyaccept = А
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = И
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Подписаться
    .buttonaccesskeyaccept = Ы
    .buttonlabelextra2 = Назад
    .buttonaccesskeyextra2 = И
calendar-creation-type =
    .value = Тип календаря:
calendar-creation-location =
    .value = Расположение:
calendar-creation-location-placeholder =
    .placeholder = URL или имя хоста сервера календаря
    .default-placeholder = URL или имя хоста сервера календаря
calendar-creation-network-nocredentials =
    .label = Для этого адреса не требуются учётные данные
calendar-creation-network-loading = Пожалуйста, подождите, ваши календари обрабатываются.
calendar-creation-network-notfound = Не удалось найти календари по данному адресу. Пожалуйста, проверьте свои настройки.
calendar-creation-network-authfail = Введённые учётные данные не приняты. Пожалуйста, проверьте ваши настройки.
calendar-creation-network-certerror = Не удалось найти календари в этом расположении из-за проблемы с сертификатом.
calendar-creation-network-subscribe-single = Пожалуйста, выберите календари, на которые вы хотели бы подписаться.
calendar-creation-network-subscribe-multiple = По данному адресу доступно несколько типов календарей. Пожалуйста, выберите тип календаря, а затем отметьте календари, на которые вы бы хотели подписаться.
