# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = повторяющееся событие
header-isrepeating-task =
    .label = повторяющаяся задача
header-containsrepeating-event =
    .label = содержит повторяющиеся события
header-containsrepeating-task =
    .label = содержит повторяющиеся задачи
header-containsrepeating-mixed =
    .label = содержит повторяющиеся элементы различного вида
windowtitle-event-copy = Копировать повторяющееся событие
windowtitle-task-copy = Копировать повторяющуюся задачу
windowtitle-mixed-copy = Копировать повторяющиеся элементы
windowtitle-event-cut = Вырезать повторяющееся событие
windowtitle-task-cut = Вырезать повторяющуюся задачу
windowtitle-mixed-cut = Вырезать повторяющиеся элементы
windowtitle-event-delete = Удалить повторяющееся событие
windowtitle-task-delete = Удалить повторяющуюся задачу
windowtitle-mixed-delete = Удалить повторяющиеся элементы
windowtitle-event-edit = Изменить повторяющееся событие
windowtitle-task-edit = Изменить повторяющуюся задачу
windowtitle-mixed-edit = Изменить повторяющиеся элементы
windowtitle-multipleitems =
    .value = Выбранные элементы
button-single-occurrence-copy =
    .label = Копировать только этот повтор
    .accesskey = т
button-single-occurrence-cut =
    .label = Вырезать только этот повтор
    .accesskey = т
button-single-occurrence-delete =
    .label = Удалить только этот повтор
    .accesskey = т
button-single-occurrence-edit =
    .label = Изменить только этот повтор
    .accesskey = т
button-multiple-occurrence-copy =
    .label = Копировать только выбранные повторы
    .accesskey = т
button-multiple-occurrence-cut =
    .label = Вырезать только выбранные повторы
    .accesskey = т
button-multiple-occurrence-delete =
    .label = Удалить только выбранные повторы
    .accesskey = т
button-multiple-occurrence-edit =
    .label = Изменить только выбранные повторы
    .accesskey = т
button-single-allfollowing-copy =
    .label = Копировать этот и все будущие повторы
    .accesskey = о
button-single-allfollowing-cut =
    .label = Вырезать этот и все будущие повторы
    .accesskey = о
button-single-allfollowing-delete =
    .label = Удалить этот и все будущие повторы
    .accesskey = о
button-single-allfollowing-edit =
    .label = Изменить этот и все будущие повторы
    .accesskey = о
button-multiple-allfollowing-copy =
    .label = Копировать этот и все будущие повторы
    .accesskey = о
button-multiple-allfollowing-cut =
    .label = Вырезать этот и все будущие повторы
    .accesskey = о
button-multiple-allfollowing-delete =
    .label = Удалить этот и все будущие повторы
    .accesskey = о
button-multiple-allfollowing-edit =
    .label = Изменить этот и все будущие повторы
    .accesskey = о
button-single-parent-copy =
    .label = Копировать все повторы
    .accesskey = л
button-single-parent-cut =
    .label = Вырезать все повторы
    .accesskey = л
button-single-parent-delete =
    .label = Удалить все повторы
    .accesskey = л
button-single-parent-edit =
    .label = Изменить все повторы
    .accesskey = л
button-multiple-parent-copy =
    .label = Копировать все повторы выбранных элементов
    .accesskey = л
button-multiple-parent-cut =
    .label = Вырезать все повторы выбранных элементов
    .accesskey = л
button-multiple-parent-delete =
    .label = Удалить все повторы выбранных элементов
    .accesskey = л
button-multiple-parent-edit =
    .label = Изменить все повторы выбранных элементов
    .accesskey = л
buttons-single-occurrence-copy =
    .label = Копировать только этот повтор
buttons-single-occurrence-cut =
    .label = Вырезать только этот повтор
buttons-single-occurrence-delete =
    .label = Удалить только этот повтор
buttons-single-occurrence-edit =
    .label = Изменить только этот повтор
buttons-multiple-occurrence-copy =
    .label = Копировать только выбранные повторы
buttons-multiple-occurrence-cut =
    .label = Вырезать только выбранные повторы
buttons-multiple-occurrence-delete =
    .label = Удалить только выбранные повторы
buttons-multiple-occurrence-edit =
    .label = Изменить только выбранные повторы
buttons-single-allfollowing-copy =
    .label = Копировать этот и все будущие повторы
buttons-single-allfollowing-cut =
    .label = Вырезать этот и все будущие повторы
buttons-single-allfollowing-delete =
    .label = Удалить этот и все будущие повторы
buttons-single-allfollowing-edit =
    .label = Изменить этот и все будущие повторы
buttons-multiple-allfollowing-copy =
    .label = Копировать этот и все будущие повторы
buttons-multiple-allfollowing-cut =
    .label = Вырезать этот и все будущие повторы
buttons-multiple-allfollowing-delete =
    .label = Удалить этот и все будущие повторы
buttons-multiple-allfollowing-edit =
    .label = Изменить этот и все будущие повторы
buttons-single-parent-copy =
    .label = Копировать все повторы
buttons-single-parent-cut =
    .label = Вырезать все повторы
buttons-single-parent-delete =
    .label = Удалить все повторы
buttons-single-parent-edit =
    .label = Изменить все повторы
buttons-multiple-parent-copy =
    .label = Копировать все повторы выбранных элементов
buttons-multiple-parent-cut =
    .label = Вырезать все повторы выбранных элементов
buttons-multiple-parent-delete =
    .label = Удалить все повторы выбранных элементов
buttons-multiple-parent-edit =
    .label = Изменить все повторы выбранных элементов
