# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Комментарий
calendar-item-summary-title = Название:
calendar-item-summary-calendar = Календарь:
calendar-item-summary-task-start = Дата начала:
calendar-item-summary-event-start = Дата начала:
calendar-item-summary-task-due = Срок:
calendar-item-summary-event-end = Дата окончания:
calendar-item-summary-repeat = Повторение:
calendar-item-summary-location = Место:
calendar-item-summary-category = Категория:
calendar-item-summary-organizer = Организатор:
calendar-item-summary-status = Состояние:
calendar-item-summary-reminder = Напоминание:
calendar-item-summary-attachments = Вложения:
calendar-item-summary-status-tentative = Возможно
calendar-item-summary-status-confirmed = Подтверждено
calendar-item-summary-event-status-cancelled = Отменено
calendar-item-summary-todo-status-cancelled = Отменено
calendar-item-summary-status-needs-action = В ожидании
calendar-item-summary-status-in-process = Выполняется
calendar-item-summary-status-completed = Выполнено
calendar-item-summary-reminder-none =
    .label = Не напоминать
calendar-item-summary-reminder-0-minutes-before =
    .label = за 0 минут до
calendar-item-summary-reminder-5-minutes-before =
    .label = за 5 минут до
calendar-item-summary-reminder-15-minutes-before =
    .label = за 15 минут до
calendar-item-summary-reminder-30-minutes-before =
    .label = за 30 минут до
calendar-item-summary-reminder-1-hour-before =
    .label = за 1 час до
calendar-item-summary-reminder-2-hours-before =
    .label = за 2 час до
calendar-item-summary-reminder-12-hours-before =
    .label = за 12 час до
calendar-item-summary-reminder-1-day-before =
    .label = за 1 день до
calendar-item-summary-reminder-2-days-before =
    .label = за 2 дня до
calendar-item-summary-reminder-1-week-before =
    .label = за 1 неделю до
calendar-item-summary-reminder-custom =
    .label = Настроить…
calendar-item-summary-reminder-multiple =
    .value = Множественные напоминания…
calendar-item-summary-general =
    .value = Основные
calendar-item-summary-attendees =
    .value = Участники
calendar-item-summary-description =
    .value = Описание
calendar-item-summary-link =
    .value = Связанная ссылка
