# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Kommentar
calendar-item-summary-title = Tittel:
calendar-item-summary-calendar = Kalender:
calendar-item-summary-task-start = Startdato:
calendar-item-summary-event-start = Startdato:
calendar-item-summary-task-due = Innen:
calendar-item-summary-event-end = Sluttdato:
calendar-item-summary-repeat = Gjenta:
calendar-item-summary-location = Sted:
calendar-item-summary-category = Kategori:
calendar-item-summary-organizer = Organisert av:
calendar-item-summary-status = Status:
calendar-item-summary-reminder = Påminnelse:
calendar-item-summary-attachments = Vedlegg:
calendar-item-summary-status-tentative = Tentativ
calendar-item-summary-status-confirmed = Bekreftet
calendar-item-summary-event-status-cancelled = Avlyst
calendar-item-summary-todo-status-cancelled = Avlyst
calendar-item-summary-status-needs-action = Trenger handling
calendar-item-summary-status-in-process = Under arbeid
calendar-item-summary-status-completed = Fullført
calendar-item-summary-reminder-none =
    .label = Ingen påminnelse
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutter før
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutter før
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutter før
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutter før
calendar-item-summary-reminder-1-hour-before =
    .label = 1 time før
calendar-item-summary-reminder-2-hours-before =
    .label = 2 timer før
calendar-item-summary-reminder-12-hours-before =
    .label = 12 timer før
calendar-item-summary-reminder-1-day-before =
    .label = 1 dag før
calendar-item-summary-reminder-2-days-before =
    .label = 2 dager før
calendar-item-summary-reminder-1-week-before =
    .label = 1 uker før
calendar-item-summary-reminder-custom =
    .label = Annet …
calendar-item-summary-reminder-multiple =
    .value = Flere påminnelser …
calendar-item-summary-general =
    .value = Generelt
calendar-item-summary-attendees =
    .value = Deltakere
calendar-item-summary-description =
    .value = Beskrivelse
calendar-item-summary-link =
    .value = Relatert lenke
