# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Merk alle
select-none-calendars = Merk ingen
calendar-creation-wizard-title = Opprett ny kalender
calendar-creation-initial-description = Kalenderen kan enten lagres lokalt, eller på en server på nettverket slik at den er tilgjengelig for andre.
calendar-creation-initial-computer =
    .label = På min datamaskin
calendar-creation-initial-network =
    .label = På nettverket
calendar-creation-username =
    .value = Brukernavn:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Opprett kalender
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Tilbake
    .buttonaccesskeyextra2 = b
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Opprett kalender
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Tilbake
    .buttonaccesskeyextra2 = b
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Finn kalendere
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Tilbake
    .buttonaccesskeyextra2 = b
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Abonner
    .buttonaccesskeyaccept = b
    .buttonlabelextra2 = Tilbake
    .buttonaccesskeyextra2 = b
calendar-creation-type =
    .value = Kalendertype:
calendar-creation-location =
    .value = Adresse:
calendar-creation-location-placeholder =
    .placeholder = URL eller hostnavn på kalenderserveren
    .default-placeholder = URL eller hostnavn på kalenderserveren
calendar-creation-network-nocredentials =
    .label = Denne adressen krever ikke innlogging
calendar-creation-network-loading = Vent mens kalenderene dine blir oppdaget.
calendar-creation-network-notfound = Kan ikke finne noen kalender på denne adressen. Kontroller dine innstillinger.
calendar-creation-network-authfail = Innloggingen du spesifiserte fungerte ikke. Kontroller innstillingene dine.
calendar-creation-network-certerror = Finner ikke kalendere på denne plasseringen på grunn av et sertifikatproblem.
calendar-creation-network-subscribe-single = Velg kalendrene du vil abonnere på.
calendar-creation-network-subscribe-multiple = Flere kalendertyper er tilgjengelig på denne adressen. Velg en kalendertype og marker kalendrene du vil abonnere på.
