# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Definições de lixo eletrónico
dialog-header-title =
    .value = Definições de lixo eletrónico
training-description-spam = Se ativado, deve primeiro treinar o { -brand-short-name } para identificar spam, utilizando o botão de Spam da barra de ferramentas para marcar mensagens como spam ou não. Necessita de identificar tanto mensagens de spam como mensagens que não sejam spam. Depois disso, o { -brand-short-name } será capaz de marcar spam automaticamente.
spam-level-checkbox =
    .label = Ativar os controlos de lixo eletrónico adaptativos para esta conta
    .accesskey = A
move-spam-message-menuitem =
    .label = Mover novas mensagens de lixo eletrónico para:
    .accesskey = M
set-spam-folder-menuitem =
    .label = Pasta “Lixo eletrónico” em:
    .accesskey = L
move-message-other =
    .label = Outra:
    .accesskey = r
automatic-spam-purge-checkbox =
    .label = Eliminar automaticamente o lixo eletrónico com mais de
    .accesskey = u
automatic-spam-purge-label =
    .value = dias
trust-addresses-header-label =
    .value = Confiar nos endereços de e-mail nestes livros de endereços:
    .accesskey = d
allowlist-header-label =
    .value = Não marcar automaticamente o correio como spam se o remetente estiver em:
    .accesskey = N
isp-headers-checkbox =
    .label = Confiar nos cabeçalhos de spam definidos por:
    .accesskey = C
isp-warning-description = Se ativado, o { -brand-short-name } irá considerar automaticamente as mensagens marcadas por este classificador externo como spam.
spam-detecting-legend = Deteção de spam
spam-storage-deletion-legend = Armazenamento e eliminação
spam-classification-legend = Seleção
spam-actions-legend = Destino e retenção
global-spam-preferences-button =
    .label = Definições globais de spam…
    .accesskey = D
manage-spam-title = Gestão de spam
manage-spam-header =
    .value = Gerir spam
training-description-learns = Quando ligado, o { -brand-short-name } aprende com as mensagens que marcar como spam ou não spam. Quanto mais o treinar, melhor o { -brand-short-name } ficará a detetar spam.
spam-auto-detection-checkbox =
    .label = Ativar deteção automática de spam para esta conta
    .accesskey = e
