# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Definições do modo offline
autodetect-connection-label =
    .label = Mudar automaticamente de modos quando for detetada uma ligação à internet
    .accesskey = d
offline-startup-label = Quando abrir o { -brand-short-name }:
status-radio-last-used =
    .label = Usar o último modo de ligação utilizado
    .accesskey = U
status-radio-ask-connect =
    .label = Perguntar se pretende ligar à internet
    .accesskey = i
status-radio-start-online =
    .label = Começar online
    .accesskey = l
status-radio-start-offline =
    .label = Começar offline
    .accesskey = f
going-online-prompt = Enviar mensagens em espera na sua Caixa de Saída
going-online-send =
    .label = Sim, enviar automaticamente
    .accesskey = S
going-online-keep =
    .label = Não, manter na Caixa de Saída
    .accesskey = N
going-online-ask-send =
    .label = Perguntar antes de enviar
    .accesskey = s
going-offline-prompt = Quer transferir mensagens para ler offline?
going-offline-download =
    .label = Sim, transferir automaticamente
    .accesskey = e
going-offline-keep =
    .label = Não, não transferir
    .accesskey = o
going-offline-ask-download =
    .label = Perguntar antes de transferir
    .accesskey = a
autodetect-online-label =
    .label = Seguir automaticamente o estado online detetado
    .accesskey = d
offline-preference-startup-label = Estado manual ao inicializar:
status-radio-remember =
    .label = Memorizar o estado online anterior
    .accesskey = r
status-radio-ask =
    .label = Pergunte-me pelo estado online
    .accesskey = u
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Enviar mensagens não enviadas ao ficar online?
going-online-auto =
    .label = Sim
    .accesskey = S
going-online-not =
    .label = Não
    .accesskey = N
going-online-ask =
    .label = Perguntar
    .accesskey = P
going-offline-label = Descarregar mensagens para utilização offline?
going-offline-auto =
    .label = Sim
    .accesskey = i
going-offline-not =
    .label = Não
    .accesskey = o
going-offline-ask =
    .label = Perguntar-me
    .accesskey = e
