# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Recibos de leitura
return-receipt-checkbox-control =
    .label = Quando enviar mensagens, pedir sempre um recibo de leitura
    .accesskey = r
receipt-arrive-label = Ao receber um recibo:
receipt-leave-inbox-control =
    .label = Deixar na Caixa de Entrada
    .accesskey = i
receipt-move-sent-control =
    .label = Mover para a pasta Enviados
    .accesskey = M
receipt-sender-request-label = Quando um remetente solicitar um recibo de leitura:
receipt-leave-radio-control =
    .label = Deixar na minha caixa de entrada
    .accesskey = i
receipt-move-radio-control =
    .label = Mover para a minha pasta "Enviados"
    .accesskey = m
receipt-request-label = Ao receber um pedido de um recibo de leitura:
receipt-return-never-radio-control =
    .label = Nunca enviar um recibo de leitura
    .accesskey = n
receipt-return-some-radio-control =
    .label = Permitir recibos de leitura para algumas mensagens
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Se não listado no campo Para ou CC:
    .accesskey = n
receipt-not-to-cc-label =
    .value = Se eu não estiver no campo Para ou Cc da mensagem:
    .accesskey = p
receipt-send-never-label =
    .label = Nunca enviar
receipt-send-always-label =
    .label = Enviar sempre
receipt-send-ask-label =
    .label = Perguntar
sender-outside-company-label =
    .value = Se o remetente não estiver na empresa ou domínio:
    .accesskey = e
sender-outside-domain-label =
    .value = Se o remetente não estiver no meu domínio:
    .accesskey = t
other-cases-text-label =
    .value = Em todos os outros casos:
    .accesskey = a
read-receipts-dialog-title = Recibos de leitura
return-receipt-request-control =
    .label = Pedir sempre um recibo de leitura ao enviar emails
    .accesskey = r
