# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Recherche en cours…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 occurrence trouvée;#1 occurrences trouvées
noMatchesFound = Aucune occurrence trouvée
labelForStopButton = Arrêter
labelForSearchButton = Rechercher
labelForStopButton.accesskey = A
labelForSearchButton.accesskey = R
moreButtonTooltipText = Ajouter une nouvelle règle
lessButtonTooltipText = Supprimer cette règle
