# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (from.today):
# must not be empty!
from.today = сёння
from.tomorrow = заўтра
# LOCALIZATION NOTE (from.half.hour.before):
# denotes times 30 minutes before next full hour
from.half.hour.before = за паўгадзіну да #1
# LOCALIZATION NOTE (from.weekday.*):
# used to derive start date based on weekdays mentioned
# can be a list of values, separate variants by |
# LOCALIZATION NOTE (from.weekday.0):
# Regardless of what the first day of the week is in your country, 0 is Sunday here.
from.weekday.0 = нядзеля | нядзелі
from.weekday.1 = панядзелак | панядзелка
from.weekday.2 = аўторак | аўторка
from.weekday.3 = серада | серады
from.weekday.4 = чацвер | чацвярга
from.weekday.5 = пятніца | пятніцы
from.weekday.6 = субота | суботы
number.1 = першы | першага
number.2 = другі | другога
number.3 = трэці | трэцяга
