# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Wyświetlana nazwa
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Rodzaj
vcard-entry-type-home = Dom
vcard-entry-type-work = Praca
vcard-entry-type-none = Brak
vcard-entry-type-custom = Inne
vcard-name-header = Imię i nazwisko
vcard-n-prefix = Przedrostek
vcard-n-add-prefix =
    .title = Dodaj przedrostek
vcard-n-firstname = Imię
vcard-n-add-firstname =
    .title = Dodaj imię
vcard-n-middlename = Drugie imię
vcard-n-add-middlename =
    .title = Dodaj drugie imię
vcard-n-lastname = Nazwisko
vcard-n-add-lastname =
    .title = Dodaj nazwisko
vcard-n-suffix = Przyrostek
vcard-n-add-suffix =
    .title = Dodaj przyrostek
vcard-nickname = Pseudonim
vcard-email-header = Adresy e-mail
vcard-email-add = Dodaj adres e-mail
vcard-email-label = Adres e-mail
vcard-primary-email-label = Domyślny
vcard-url-header = Strony WWW
vcard-url-add = Dodaj stronę WWW
vcard-url-label = Strona WWW
vcard-tel-header = Numery telefonu
vcard-tel-add = Dodaj numer telefonu
vcard-tel-label = Numer telefonu
# Or "Mobile"
vcard-entry-type-cell = Telefon komórkowy
vcard-entry-type-fax = Faks
vcard-entry-type-pager = Pager
vcard-tz-header = Strefa czasowa
vcard-tz-add = Dodaj strefę czasową
vcard-impp2-header = Komunikatory
vcard-impp-add = Dodaj konto komunikatora
vcard-impp-label = Konto komunikatora
vcard-impp-select = Protokół
vcard-impp-option-other = Inne
vcard-impp-input-label = Adres URI
vcard-impp-input-title = Adres URI komunikatora
vcard-bday-anniversary-header = Specjalne daty
vcard-bday-anniversary-add = Dodaj specjalną datę
vcard-bday-label = Urodziny
vcard-anniversary-label = Rocznica
vcard-date-day = Dzień
vcard-date-month = Miesiąc
vcard-date-year = Rok
vcard-adr-header = Adresy
vcard-adr-add = Dodaj adres
vcard-adr-label = Adres
vcard-adr-delivery-label = Etykieta dostawy
vcard-adr-street = Adres
# Or "Locality"
vcard-adr-locality = Miasto
# Or "Region"
vcard-adr-region = Województwo
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Kod pocztowy
vcard-adr-country = Państwo
vcard-note-header = Notatki
vcard-note-add = Dodaj notatkę
vcard-org-header = Właściwości firmy/organizacji
vcard-org-add = Dodaj właściwości firmy/organizacji
vcard-org-title = Tytuł
vcard-org-title-input =
    .placeholder = Stanowisko
    .title = Stanowisko
vcard-org-role = Rola
vcard-org-role-input =
    .placeholder = Rola w projekcie
    .title = Funkcja lub rola odgrywana w konkretnej sytuacji
vcard-org-org = Firma/Organizacja
vcard-org-org-input =
    .placeholder = Nazwa firmy
    .title = Nazwa organizacyjna
vcard-org-org-unit = Dział
vcard-org-org-unit-input =
    .placeholder = Dział
    .title = Nazwa jednostki organizacyjnej
vcard-custom-header = Inne właściwości
vcard-custom-add = Dodaj inne właściwości
vcard-remove-button-title =
    .title = Usuń
vcard-remove-button = Usuń
