# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Растягивающийся интервал
search-bar-label = Поиск
toolbar-write-message-label = Создать
toolbar-write-message =
    .title = Создать сообщение
toolbar-move-to-label = Переместить в
toolbar-move-to =
    .title = Переместить выбранное сообщение
toolbar-unifinder-label = Найти события
toolbar-unifinder =
    .title = Переключение отображения панели поиска событий
toolbar-folder-location-label = Выбор папки
toolbar-folder-location =
    .title = Перейти в папку
toolbar-edit-event-label = Правка
toolbar-edit-event =
    .title = Редактировать выбранное событие или задачу
toolbar-get-messages-label = Получить
toolbar-get-messages =
    .title = Получить новые сообщения для всех учётных записей
toolbar-reply-label = Ответить
toolbar-reply =
    .title = Ответить на сообщение
toolbar-reply-all-label = Ответить всем
toolbar-reply-all =
    .title = Ответить отправителю и всем адресатам
toolbar-reply-to-list-label = Ответить в рассылку
toolbar-reply-to-list =
    .title = Ответить в список рассылки
toolbar-redirect-label = Перенаправить
toolbar-redirect =
    .title = Перенаправить выбранное сообщение
toolbar-archive-label = Архивировать
toolbar-archive =
    .title = Архивировать выделенные сообщения
toolbar-conversation-label = Разговор
toolbar-conversation =
    .title = Показать разговор для выделенного сообщения
toolbar-previous-unread-label = Предыдущее непрочитанное
toolbar-previous-unread =
    .title = Перейти к предыдущему непрочитанному сообщению
toolbar-previous-label = Предыдущее
toolbar-previous =
    .title = Перейти к предыдущему сообщению
toolbar-next-unread-label = Следующее непрочитанное
toolbar-next-unread =
    .title = Перейти к следующему непрочитанному сообщению
toolbar-next-label = Следующее
toolbar-next =
    .title = Перейти к следующему сообщению
toolbar-junk-label = Спам
toolbar-junk =
    .title = Отметить выбранные сообщения как спам
toolbar-delete-label = Удалить
toolbar-delete-title =
    .title = Удалить выбранные сообщения
toolbar-undelete-label = Восстановить
toolbar-undelete =
    .title = Восстановить выбранные сообщения
toolbar-compact-label = Сжать
toolbar-compact =
    .title = Убрать удалённые сообщения из выбранной папки
toolbar-add-as-event-label = Добавить как событие
toolbar-add-as-event =
    .title = Извлечь календарную информацию из сообщения и добавить в календарь как событие
toolbar-add-as-task-label = Добавить как задачу
toolbar-add-as-task =
    .title = Извлечь календарную информацию из сообщения и добавить в календарь как задачу
toolbar-tag-message-label = Метка
toolbar-tag-message =
    .title = Присвоить сообщению метку
toolbar-forward-inline-label = Переслать
toolbar-forward-inline =
    .title = Переслать выбранное сообщение внутри сообщения
toolbar-forward-attachment-label = Переслать как вложение
toolbar-forward-attachment =
    .title = Переслать выбранное сообщение как вложение
toolbar-mark-as-label = Отметить
toolbar-mark-as =
    .title = Отметить сообщения
toolbar-view-picker-label = Вид
toolbar-view-picker =
    .title = Настроить вид текущей папки
toolbar-address-book-label = Адресная книга
toolbar-address-book =
    .title = Открыть адресную книгу
toolbar-chat-label = Чат
toolbar-chat =
    .title = Показать вкладку чата
toolbar-add-ons-and-themes-label = Дополнения и темы
toolbar-add-ons-and-themes =
    .title = Управление своими дополнениями
toolbar-calendar-label = Календарь
toolbar-calendar =
    .title = Переключиться на вкладку календаря
toolbar-tasks-label = Задачи
toolbar-tasks =
    .title = Переключиться на вкладку задач
toolbar-mail-label = Почта
toolbar-mail =
    .title = Перейти на вкладку почты
toolbar-print-label = Печать
toolbar-print =
    .title = Распечатать это сообщение
toolbar-quick-filter-bar-label = Быстрый фильтр
toolbar-quick-filter-bar =
    .title = Фильтрация сообщений
toolbar-synchronize-label = Синхронизация
toolbar-synchronize =
    .title = Перезагрузить календари и синхронизировать изменения
toolbar-delete-event-label = Удалить
toolbar-delete-event =
    .title = Удалить выбранные события или задачи
toolbar-go-to-today-label = Сегодня
toolbar-go-to-today =
    .title = Перейти на сегодня
toolbar-print-event-label = Печать
toolbar-print-event =
    .title = Печать событий или задач
toolbar-new-event-label = Событие
toolbar-new-event =
    .title = Создать новое событие
toolbar-new-task-label = Задача
toolbar-new-task =
    .title = Создать новую задачу
toolbar-go-back-label = Назад
toolbar-go-back =
    .title = Перейти к предыдущему сообщению
toolbar-go-forward-label = Вперёд
toolbar-go-forward =
    .title = Перейти к следующему сообщению
toolbar-stop-label = Остановить
toolbar-stop =
    .title = Остановить текущую передачу данных
toolbar-throbber-label = Индикатор активности
toolbar-throbber =
    .title = Индикатор активности
toolbar-create-contact-label = Новый контакт
toolbar-create-contact =
    .title = Создать новый контакт
toolbar-create-address-book-label = Новая адресная книга
toolbar-create-address-book =
    .title = Создать новую адресную книгу
toolbar-create-list-label = Новый список
toolbar-create-list =
    .title = Создать новый список рассылки
toolbar-import-contacts-label = Импорт
toolbar-import-contacts =
    .title = Импорт контактов из файла

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Добавить локальную адресную книгу
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Добавить адресную книгу CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Добавить адресную книгу LDAP
