# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Растягивающийся интервал
toolbar-write-message-label = Создать
toolbar-write-message =
    .title = Создать сообщение
toolbar-unifinder-label = Найти события
toolbar-unifinder =
    .title = Переключение отображения панели поиска событий
toolbar-folder-location-label = Выбор папки
toolbar-edit-event-label = Правка
toolbar-edit-event =
    .title = Редактировать выбранное событие или задачу
toolbar-get-messages-label = Получить
toolbar-reply-label = Ответить
toolbar-reply =
    .title = Ответить на сообщение
toolbar-reply-all-label = Ответить всем
toolbar-reply-all =
    .title = Ответить отправителю и всем адресатам
toolbar-reply-to-list-label = Ответить в рассылку
toolbar-reply-to-list =
    .title = Ответить в список рассылки
toolbar-redirect-label = Перенаправить
toolbar-redirect =
    .title = Перенаправить выбранное сообщение
toolbar-archive-label = Архивировать
toolbar-archive =
    .title = Архивировать выделенные сообщения
toolbar-conversation-label = Разговор
toolbar-conversation =
    .title = Показать разговор для выделенного сообщения
toolbar-previous-unread-label = Предыдущее непрочитанное
toolbar-previous-unread =
    .title = Перейти к предыдущему непрочитанному сообщению
toolbar-previous-label = Предыдущее
toolbar-previous =
    .title = Перейти к предыдущему сообщению
toolbar-next-unread-label = Следующее непрочитанное
toolbar-next-unread =
    .title = Перейти к следующему непрочитанному сообщению
toolbar-next-label = Следующее
toolbar-next =
    .title = Перейти к следующему сообщению
toolbar-junk-label = Спам
toolbar-junk =
    .title = Отметить выбранные сообщения как спам
toolbar-delete-label = Удалить
toolbar-delete =
    .title = Удалить выбранные сообщения или папку
toolbar-compact-label = Сжать
toolbar-compact =
    .title = Убрать удалённые сообщения из выбранной папки
toolbar-add-as-event-label = Добавить как событие
toolbar-add-as-event =
    .title = Извлечь календарную информацию из сообщения и добавить в календарь как событие
toolbar-add-as-task-label = Добавить как задачу
toolbar-add-as-task =
    .title = Извлечь календарную информацию из сообщения и добавить в календарь как задачу
toolbar-tag-message-label = Метка
toolbar-tag-message =
    .title = Присвоить сообщению метку
toolbar-forward-inline-label = Переслать
toolbar-forward-inline =
    .title = Переслать выбранное сообщение внутри сообщения
toolbar-forward-attachment-label = Переслать как вложение
toolbar-forward-attachment =
    .title = Переслать выбранное сообщение как вложение
toolbar-mark-as-label = Отметить
toolbar-mark-as =
    .title = Отметить сообщения
toolbar-address-book =
    .title = Открыть адресную книгу
toolbar-chat-label = Чат
toolbar-chat =
    .title = Показать вкладку чата
toolbar-calendar-label = Календарь
toolbar-calendar =
    .title = Переключиться на вкладку календаря
toolbar-tasks-label = Задачи
toolbar-tasks =
    .title = Переключиться на вкладку задач
toolbar-print-label = Печать
toolbar-print =
    .title = Распечатать это сообщение
