# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Iskanje …
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Najden je bil #1 zadetek;Najdena sta bila #1 zadetka;Najdeni so bili #1 zadetki;Najdenih je bilo #1 zadetkov
noMatchesFound = Ni zadetkov
labelForStopButton = Ustavi
labelForSearchButton = Išči
labelForStopButton.accesskey = U
labelForSearchButton.accesskey = š
moreButtonTooltipText = Dodaj novo pravilo
lessButtonTooltipText = Odstrani to pravilo
