# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Tschertgar…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Chattà #1 congrugenza;Chattà #1 congrugenzas
noMatchesFound = Chattà naginas congruenzas
labelForStopButton = Fermar
labelForSearchButton = Tschertgar
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = S
moreButtonTooltipText = Agiuntar ina nova regla
lessButtonTooltipText = Allontanar questa regla
