# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = العنوان:
calendar-item-summary-calendar = التقويم:
calendar-item-summary-task-start = تاريخ البدء:
calendar-item-summary-event-start = تاريخ البدء:
calendar-item-summary-task-due = تاريخ الاستحقاق:
calendar-item-summary-event-end = تاريخ الانتهاء:
calendar-item-summary-repeat = التكرارية:
calendar-item-summary-location = المكان:
calendar-item-summary-category = الفئة:
calendar-item-summary-organizer = المنظّم:
calendar-item-summary-status = الحالة:
calendar-item-summary-reminder = التذكير:
calendar-item-summary-attachments = المرفقات:
calendar-item-summary-status-tentative = مبدئي
calendar-item-summary-status-confirmed = مُؤكّد
calendar-item-summary-event-status-cancelled = أُلغِيَ
calendar-item-summary-todo-status-cancelled = أُلغِيَ
calendar-item-summary-status-needs-action = يحتاج لإجراء
calendar-item-summary-status-in-process = يجري الآن
calendar-item-summary-status-completed = اكتمل في
calendar-item-summary-reminder-none =
    .label = لا تذكرني
calendar-item-summary-reminder-0-minutes-before =
    .label = مباشرة
calendar-item-summary-reminder-5-minutes-before =
    .label = قبل 5 دقائق
calendar-item-summary-reminder-15-minutes-before =
    .label = قبل 15 دقيقة
calendar-item-summary-reminder-30-minutes-before =
    .label = قبل 30 دقيقة
calendar-item-summary-reminder-1-hour-before =
    .label = قبل ساعة
calendar-item-summary-reminder-2-hours-before =
    .label = قبل ساعتين
calendar-item-summary-reminder-12-hours-before =
    .label = قبل 12 ساعة
calendar-item-summary-reminder-1-day-before =
    .label = قبل يوم واحد
calendar-item-summary-reminder-2-days-before =
    .label = قبل يومين
calendar-item-summary-reminder-1-week-before =
    .label = قبل أسبوع واحد
calendar-item-summary-reminder-custom =
    .label = مخصّص…
calendar-item-summary-reminder-multiple =
    .value = تذكيرات متعددة…
calendar-item-summary-general =
    .value = عام
calendar-item-summary-attendees =
    .value = الحضور
calendar-item-summary-description =
    .value = الوصف
calendar-item-summary-link =
    .value = رابط ذا صلة
