# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = هذا الحدث متكرر
header-isrepeating-task =
    .label = هذه المهمة متكررة
header-containsrepeating-event =
    .label = يحتوي أحداث متكررة
header-containsrepeating-task =
    .label = يحتوي مهام متكررة
header-containsrepeating-mixed =
    .label = يحتوي عناصر متكررة من نوع مختلف
windowtitle-event-copy = نسخ الحدث المتكرر
windowtitle-task-copy = نسخ المهمة المتكررة
windowtitle-mixed-copy = نسخ العناصر المتكررة
windowtitle-event-cut = قص الحدث المتكرر
windowtitle-task-cut = قص المهمة المتكررة
windowtitle-mixed-cut = قطع العناصر المتكررة
windowtitle-event-delete = حذف حدث متكرر
windowtitle-task-delete = حذف مهمة متكررة
windowtitle-mixed-delete = حذف العناصر المتكررة
windowtitle-event-edit = تحرير حدث متكرر
windowtitle-task-edit = تحرير مهمة متكررة
windowtitle-mixed-edit = تحرير العناصر المتكررة
windowtitle-multipleitems =
    .value = العناصر المحدّدة
button-single-occurrence-copy =
    .label = انسخ هذا التكرار فقط
    .accesskey = ط
button-single-occurrence-cut =
    .label = قصّ هذا التكرار فقط
    .accesskey = ط
button-single-occurrence-delete =
    .label = احذف هذا التكرار فقط
    .accesskey = ط
button-single-occurrence-edit =
    .label = حرّر هذا التكرار فقط
    .accesskey = ط
button-multiple-occurrence-copy =
    .label = انسخ التكرارات المحدّدة فقط
    .accesskey = ط
button-multiple-occurrence-cut =
    .label = قصّ التكرارات المحدّدة فقط
    .accesskey = ط
button-multiple-occurrence-delete =
    .label = احذف التكرارات المحدّدة فقط
    .accesskey = ط
button-multiple-occurrence-edit =
    .label = حرّر التكرارات المحدّدة فقط
    .accesskey = ط
button-single-allfollowing-copy =
    .label = انسخ هذا التكرار وما يليه من تكرارات
    .accesskey = ك
button-single-allfollowing-cut =
    .label = قصّ هذا التكرار وما يليه من تكرارات
    .accesskey = ك
button-single-allfollowing-delete =
    .label = احذف هذا التكرار وما يليه من تكرارات
    .accesskey = ك
button-single-allfollowing-edit =
    .label = حرّر هذا التكرار وما يليه من تكرارات
    .accesskey = ك
button-multiple-allfollowing-copy =
    .label = انسخ التكرار المحدّد وما يليه من تكرارات
    .accesskey = ك
button-multiple-allfollowing-cut =
    .label = قصّ التكرار المحدّد وما يليه من تكرارات
    .accesskey = ك
button-multiple-allfollowing-delete =
    .label = احذف التكرار المحدّد وما يليه من تكرارات
    .accesskey = ك
button-multiple-allfollowing-edit =
    .label = حرّر التكرار المحدّد وما يليه من تكرارات
    .accesskey = ك
button-single-parent-copy =
    .label = انسخ كل التكررات
    .accesskey = ت
button-single-parent-cut =
    .label = قصّ كل التكرارات
    .accesskey = ت
button-single-parent-delete =
    .label = احذف كل التكرارات
    .accesskey = ت
button-single-parent-edit =
    .label = حرر كل التكرارات
    .accesskey = ت
button-multiple-parent-copy =
    .label = انسخ كل التكرارات للعناصر المحدّدة
    .accesskey = ت
button-multiple-parent-cut =
    .label = قص كل التكرارات للعناصر المحدّدة
    .accesskey = ت
button-multiple-parent-delete =
    .label = احذف كل التكرارات للعناصر المحدّدة
    .accesskey = ت
button-multiple-parent-edit =
    .label = حرر كل التكرارات للعناصر المحدّدة
    .accesskey = ت
buttons-single-occurrence-copy =
    .label = انسخ هذا التكرار فقط
buttons-single-occurrence-cut =
    .label = قصّ هذا التكرار فقط
buttons-single-occurrence-delete =
    .label = احذف هذا التكرار فقط
buttons-single-occurrence-edit =
    .label = حرّر هذا التكرار فقط
buttons-multiple-occurrence-copy =
    .label = انسخ التكرارات المحدّدة فقط
buttons-multiple-occurrence-cut =
    .label = قصّ التكرارات المحدّدة فقط
buttons-multiple-occurrence-delete =
    .label = احذف التكرارات المحدّدة فقط
buttons-multiple-occurrence-edit =
    .label = حرّر التكرارات المحدّدة فقط
buttons-single-allfollowing-copy =
    .label = انسخ هذا التكرار وما يليه من تكرارات
buttons-single-allfollowing-cut =
    .label = قصّ هذا التكرار وما يليه من تكرارات
buttons-single-allfollowing-delete =
    .label = احذف هذا التكرار وما يليه من تكرارات
buttons-single-allfollowing-edit =
    .label = حرّر هذا التكرار وما يليه من تكرارات
buttons-multiple-allfollowing-copy =
    .label = انسخ التكرار المحدّد وما يليه من تكرارات
buttons-multiple-allfollowing-cut =
    .label = قصّ التكرار المحدّد وما يليه من تكرارات
buttons-multiple-allfollowing-delete =
    .label = احذف التكرار المحدّد وما يليه من تكرارات
buttons-multiple-allfollowing-edit =
    .label = حرّر التكرار المحدّد وما يليه من تكرارات
buttons-single-parent-copy =
    .label = انسخ كل التكررات
buttons-single-parent-cut =
    .label = قصّ كل التكرارات
buttons-single-parent-delete =
    .label = احذف كل التكرارات
buttons-single-parent-edit =
    .label = حرر كل التكرارات
buttons-multiple-parent-copy =
    .label = انسخ كل التكرارات للعناصر المحدّدة
buttons-multiple-parent-cut =
    .label = قص كل التكرارات للعناصر المحدّدة
buttons-multiple-parent-delete =
    .label = احذف كل التكرارات للعناصر المحدّدة
buttons-multiple-parent-edit =
    .label = حرر كل التكرارات للعناصر المحدّدة
