# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Títol:
calendar-item-summary-calendar = Calendari:
calendar-item-summary-task-start = Data d'inici:
calendar-item-summary-event-start = Data d'inici:
calendar-item-summary-task-due = Data de venciment:
calendar-item-summary-event-end = Data de fi:
calendar-item-summary-repeat = Repetició:
calendar-item-summary-location = Ubicació:
calendar-item-summary-category = Categoria:
calendar-item-summary-organizer = Organitzador:
calendar-item-summary-status = Estat:
calendar-item-summary-reminder = Recordatori:
calendar-item-summary-attachments = Adjuncions:
calendar-item-summary-status-tentative = Provisional
calendar-item-summary-status-confirmed = Confirmada
calendar-item-summary-event-status-cancelled = Cancel·lada
calendar-item-summary-todo-status-cancelled = Cancel·lada
calendar-item-summary-status-needs-action = Necessita una acció
calendar-item-summary-status-in-process = En curs
calendar-item-summary-status-completed = Acabada el dia
calendar-item-summary-reminder-none =
    .label = Cap recordatori
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuts abans
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuts abans
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuts abans
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuts abans
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hora abans
calendar-item-summary-reminder-2-hours-before =
    .label = 2 hores abans
calendar-item-summary-reminder-12-hours-before =
    .label = 12 hores abans
calendar-item-summary-reminder-1-day-before =
    .label = 1 dia abans
calendar-item-summary-reminder-2-days-before =
    .label = 2 dies abans
calendar-item-summary-reminder-1-week-before =
    .label = 1 setmana abans
calendar-item-summary-reminder-custom =
    .label = Personalitzat…
calendar-item-summary-reminder-multiple =
    .value = Recordatoris múltiples…
calendar-item-summary-general =
    .value = General
calendar-item-summary-attendees =
    .value = Assistents
calendar-item-summary-description =
    .value = Descripció
calendar-item-summary-link =
    .value = Enllaç relacionat
