# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Söker…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 träff;#1 träffar
noMatchesFound = Inga träffar hittades
labelForStopButton = Avbryt
labelForSearchButton = Sök
labelForStopButton.accesskey = A
labelForSearchButton.accesskey = S
moreButtonTooltipText = Lägg till en ny regel
lessButtonTooltipText = Ta bort en regel
