# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Spazi flexibel
toolbar-write-message-label = Scriver
toolbar-write-message =
    .title = Scriver in nov messadi
toolbar-unifinder-label = Chattar eveniments
toolbar-unifinder =
    .title = Mussar/zuppentar la lastra per chattar eveniments
toolbar-folder-location-label = Posiziun da l'ordinatur
toolbar-edit-event-label = Modifitgar
toolbar-edit-event =
    .title = Modifitgar l'incumbensa u l'eveniment tschernì
toolbar-get-messages-label = Retschaiver messadis
toolbar-reply-label = Respunder
toolbar-reply =
    .title = Respunder quest messadi
toolbar-reply-all-label = Respunder a tuts
toolbar-reply-all =
    .title = Respunder al speditur ed a tut ils destinaturs
toolbar-reply-to-list-label = Respunder a la glista
toolbar-reply-to-list =
    .title = Respunder a la glista dad e-mail
toolbar-redirect-label = Renviar
toolbar-redirect =
    .title = Renviar il messadi tschernì
toolbar-archive-label = Archivar
toolbar-archive =
    .title = Archivar ils messadis tschernids
toolbar-conversation-label = Conversaziun
toolbar-conversation =
    .title = Mussar la conversaziun dal messadi tschernì
toolbar-previous-unread-label = Nunlegì precedent
toolbar-previous-unread =
    .title = Ir al messadi nunlegì precedent
toolbar-previous-label = Enavos
toolbar-previous =
    .title = Ir al messadi precedent
toolbar-next-unread-label = Proxim nunlegì
toolbar-next-unread =
    .title = Ir al proxim messadi nunlegì
toolbar-next-label = Proxim
toolbar-next =
    .title = Ir al proxim messadi
toolbar-junk-label = Nungiavischà
toolbar-junk =
    .title = Marcar ils messadis tschernids sco nungiavischads
toolbar-delete-label = Stizzar
toolbar-delete =
    .title = Stizzar ils messadis tschernids u l'ordinatur
toolbar-compact-label = Cumprimer
toolbar-compact =
    .title = Eliminar definitivamain ils messadis stizzads da l'ordinatur tschernì
toolbar-add-as-event-label = Agiuntar sco eveniment
toolbar-add-as-event =
    .title = Extrair infurmaziuns da chalender ord il messadi e las agiuntar a tes chalender sco eveniment
toolbar-add-as-task-label = Agiuntar sco incumbensa
toolbar-add-as-task =
    .title = Extrair infurmaziuns da chalender ord il messadi e las agiuntar a tes chalender sco incumbensa
toolbar-tag-message-label = Etichetta
toolbar-tag-message =
    .title = (De)etichettar ils messadis
toolbar-forward-inline-label = Vinavant
toolbar-forward-inline =
    .title = Trametter vinavant il messadi selecziunà sco text integrà
toolbar-forward-attachment-label = Trametter vinavant sco agiunta
toolbar-forward-attachment =
    .title = Trametter vinavant il messadi selecziunà sco agiunta
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar il(s) messadi(s)
toolbar-address-book =
    .title = Avrir il cudeschet d'adressas
toolbar-chat-label = Chat
toolbar-chat =
    .title = Mussar il tab da chat
toolbar-add-ons-and-themes-label = Supplements e designs
toolbar-add-ons-and-themes =
    .title = Administrar tes supplements
toolbar-calendar-label = Chalender
toolbar-calendar =
    .title = Midar al tab dal chalender
toolbar-tasks-label = Incumbensas
toolbar-tasks =
    .title = Midar al tab dad incumbensas
toolbar-print-label = Stampar
toolbar-print =
    .title = Stampar quest messadi
toolbar-quick-filter-bar-label = Filtrar svelt
toolbar-quick-filter-bar =
    .title = Filtrar messadis
