# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Joustava väli
toolbar-write-message-label = Kirjoita
toolbar-write-message =
    .title = Luo uusi viesti
toolbar-unifinder-label = Etsi tapahtumia
toolbar-unifinder =
    .title = Näytä/piilota Etsi tapahtumia -paneeli
toolbar-folder-location-label = Kansion sijainti
toolbar-edit-event-label = Muokkaa
toolbar-edit-event =
    .title = Muokkaa valittua tapahtumaa tai tehtävää
toolbar-get-messages-label = Nouda viestit
toolbar-reply-label = Vastaa
toolbar-reply =
    .title = Vastaa viestiin
toolbar-reply-all-label = Vastaa kaikille
toolbar-reply-all =
    .title = Vastaa lähettäjälle ja kaikille vastaanottajille
toolbar-reply-to-list-label = Vastaa listalle
toolbar-reply-to-list =
    .title = Vastaa postituslistalle
toolbar-archive-label = Arkistoi
toolbar-archive =
    .title = Arkistoi valitut viestit
toolbar-conversation-label = Keskustelu
toolbar-conversation =
    .title = Näytä valitun viestin keskustelu
toolbar-previous-unread-label = Edellinen lukematon
toolbar-previous-unread =
    .title = Siirry edelliseen lukematta olevaan viestiin
toolbar-previous-label = Edellinen
toolbar-previous =
    .title = Siirry edelliseen viestiin
toolbar-next-unread-label = Seuraava lukematon
toolbar-next-unread =
    .title = Siirry seuraavaan lukematta olevaan viestiin
toolbar-next-label = Seuraava
toolbar-next =
    .title = Siirry seuraavaan viestiin
toolbar-junk-label = Roskapostia
toolbar-junk =
    .title = Merkitse valitut viestit roskapostiksi
toolbar-delete-label = Poista
toolbar-delete =
    .title = Poista valitut viestit tai kansio
toolbar-compact-label = Tiivistä
toolbar-compact =
    .title = Poista poistettu viesti valitusta kansiosta
toolbar-add-as-event-label = Lisää tapahtumaksi
toolbar-add-as-event =
    .title = Etsi aikataulutiedot viestistä ja lisää ne kalenteriin tapahtumaksi
toolbar-add-as-task-label = Lisää tehtäväksi
toolbar-add-as-task =
    .title = Etsi aikataulutiedot viestistä ja lisää ne kalenteriin tehtäväksi
toolbar-tag-message-label = Tunnus
toolbar-tag-message =
    .title = Aseta viesteihin tunnuksia
toolbar-forward-inline-label = Välitä
toolbar-forward-inline =
    .title = Välitä viesti viestirungossa
toolbar-forward-attachment-label = Välitä liitteenä
toolbar-forward-attachment =
    .title = Välitä viesti liitteenä
toolbar-mark-as-label = Merkitse
toolbar-mark-as =
    .title = Merkitse viestit
toolbar-address-book =
    .title = Siirry osoitekirjaan
toolbar-chat-label = Keskustele
toolbar-chat =
    .title = Näytä keskustelu-välilehti
toolbar-add-ons-and-themes-label = Lisäosat ja teemat
toolbar-calendar-label = Kalenteri
toolbar-calendar =
    .title = Siirry Kalenteri-välilehteen
toolbar-tasks-label = Tehtävät
toolbar-tasks =
    .title = Siirry Tehtävät-välilehteen
toolbar-print-label = Tulosta
toolbar-print =
    .title = Tulosta viesti
