# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Joustava väli
search-bar-label = Etsi
toolbar-write-message-label = Kirjoita
toolbar-write-message =
    .title = Luo uusi viesti
toolbar-move-to-label = Siirrä kansioon
toolbar-move-to =
    .title = Siirrä valittu viesti
toolbar-unifinder-label = Etsi tapahtumia
toolbar-unifinder =
    .title = Näytä/piilota Etsi tapahtumia -paneeli
toolbar-folder-location-label = Kansion sijainti
toolbar-folder-location =
    .title = Vaihda kansioon
toolbar-edit-event-label = Muokkaa
toolbar-edit-event =
    .title = Muokkaa valittua tapahtumaa tai tehtävää
toolbar-get-messages-label = Nouda viestit
toolbar-get-messages =
    .title = Hae uudet viestit kaikita tileiltä
toolbar-reply-label = Vastaa
toolbar-reply =
    .title = Vastaa viestiin
toolbar-reply-all-label = Vastaa kaikille
toolbar-reply-all =
    .title = Vastaa lähettäjälle ja kaikille vastaanottajille
toolbar-reply-to-list-label = Vastaa listalle
toolbar-reply-to-list =
    .title = Vastaa postituslistalle
toolbar-redirect-label = Uudelleenohjaa
toolbar-redirect =
    .title = Uudelleenohjaa valittu viesti
toolbar-archive-label = Arkistoi
toolbar-archive =
    .title = Arkistoi valitut viestit
toolbar-conversation-label = Keskustelu
toolbar-conversation =
    .title = Näytä valitun viestin keskustelu
toolbar-previous-unread-label = Edellinen lukematon
toolbar-previous-unread =
    .title = Siirry edelliseen lukematta olevaan viestiin
toolbar-previous-label = Edellinen
toolbar-previous =
    .title = Siirry edelliseen viestiin
toolbar-next-unread-label = Seuraava lukematon
toolbar-next-unread =
    .title = Siirry seuraavaan lukematta olevaan viestiin
toolbar-next-label = Seuraava
toolbar-next =
    .title = Siirry seuraavaan viestiin
toolbar-junk-label = Roskapostia
toolbar-junk =
    .title = Merkitse valitut viestit roskapostiksi
toolbar-delete-label = Poista
toolbar-delete-title =
    .title = Poista valitut viestit
toolbar-undelete-label = Peru poistaminen
toolbar-undelete =
    .title = Peru valittujen viestien poisto
toolbar-compact-label = Tiivistä
toolbar-compact =
    .title = Poista poistettu viesti valitusta kansiosta
toolbar-add-as-event-label = Lisää tapahtumaksi
toolbar-add-as-event =
    .title = Etsi aikataulutiedot viestistä ja lisää ne kalenteriin tapahtumaksi
toolbar-add-as-task-label = Lisää tehtäväksi
toolbar-add-as-task =
    .title = Etsi aikataulutiedot viestistä ja lisää ne kalenteriin tehtäväksi
toolbar-tag-message-label = Tunnus
toolbar-tag-message =
    .title = Aseta viesteihin tunnuksia
toolbar-forward-inline-label = Välitä
toolbar-forward-inline =
    .title = Välitä viesti viestirungossa
toolbar-forward-attachment-label = Välitä liitteenä
toolbar-forward-attachment =
    .title = Välitä viesti liitteenä
toolbar-mark-as-label = Merkitse
toolbar-mark-as =
    .title = Merkitse viestit
toolbar-view-picker-label = Näytä
toolbar-view-picker =
    .title = Mukauta nykyisen kansion näkymää
toolbar-address-book-label = Osoitekirja
toolbar-address-book =
    .title = Siirry osoitekirjaan
toolbar-chat-label = Keskustele
toolbar-chat =
    .title = Näytä keskustelu-välilehti
toolbar-add-ons-and-themes-label = Lisäosat ja teemat
toolbar-add-ons-and-themes =
    .title = Hallitse lisäosia
toolbar-calendar-label = Kalenteri
toolbar-calendar =
    .title = Siirry Kalenteri-välilehteen
toolbar-tasks-label = Tehtävät
toolbar-tasks =
    .title = Siirry Tehtävät-välilehteen
toolbar-mail-label = Sähköposti
toolbar-mail =
    .title = Siirry Sähköposti-välilehteen
toolbar-print-label = Tulosta
toolbar-print =
    .title = Tulosta viesti
toolbar-quick-filter-bar-label = Pikasuodatus
toolbar-quick-filter-bar =
    .title = Suodata viestejä
toolbar-synchronize-label = Synkronoi
toolbar-synchronize =
    .title = Lataa kalenterit uudelleen ja synkronoi muutokset
toolbar-delete-event-label = Poista
toolbar-delete-event =
    .title = Poista valitut tapahtumat tai tehtävät
toolbar-go-to-today-label = Siirry tähän päivään
toolbar-go-to-today =
    .title = Siirry tähän päivään
toolbar-print-event-label = Tulosta
toolbar-print-event =
    .title = Tulosta tapahtumat tai tehtävät
toolbar-new-event-label = Tapahtuma
toolbar-new-event =
    .title = Luo uusi tapahtuma
toolbar-new-task-label = Tehtävä
toolbar-new-task =
    .title = Luo uusi tehtävä
toolbar-go-back-label = Siirry edelliseen
toolbar-go-back =
    .title = Siirry edelliseen viestiin
toolbar-go-forward-label = Siirry seuraavaan
toolbar-go-forward =
    .title = Siirry seuraavaan viestiin
toolbar-stop-label = Pysäytä
toolbar-stop =
    .title = Keskeytä lataus
toolbar-throbber-label = Toimintaindikaattori
toolbar-throbber =
    .title = Toimintaindikaattori
toolbar-create-contact-label = Uusi yhteyshenkilö
toolbar-create-contact =
    .title = Luo uusi yhteyshenkilö
toolbar-create-address-book-label = Uusi osoitekirja
toolbar-create-address-book =
    .title = Luo uusi osoitekirja
toolbar-create-list-label = Uusi lista
toolbar-create-list =
    .title = Luo uusi postituslista
toolbar-import-contacts-label = Tuo
toolbar-import-contacts =
    .title = Tuo yhteystiedot tiedostosta

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lisää paikallinen osoitekirja
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Lisää CardDAV-osoitekirja
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Lisää LDAP-osoitekirja
