# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Título:
calendar-item-summary-calendar = Calendário:
calendar-item-summary-task-start = Data de início:
calendar-item-summary-event-start = Data de início:
calendar-item-summary-task-due = Data de fim:
calendar-item-summary-event-end = Data de fim:
calendar-item-summary-repeat = Repetir:
calendar-item-summary-location = Localização:
calendar-item-summary-category = Categoria:
calendar-item-summary-organizer = Agenda:
calendar-item-summary-status = Estado:
calendar-item-summary-reminder = Lembrete:
calendar-item-summary-attachments = Anexos:
calendar-item-summary-status-tentative = Tentativa
calendar-item-summary-status-confirmed = Confirmado
calendar-item-summary-event-status-cancelled = Cancelado
calendar-item-summary-todo-status-cancelled = Cancelado
calendar-item-summary-status-needs-action = Requer ação
calendar-item-summary-status-in-process = Em curso
calendar-item-summary-status-completed = Concluído a
calendar-item-summary-reminder-none =
    .label = Sem lembrete
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minutos antes
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minutos antes
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minutos antes
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minutos antes
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hora antes
calendar-item-summary-reminder-2-hours-before =
    .label = 2 horas antes
calendar-item-summary-reminder-12-hours-before =
    .label = 12 horas antes
calendar-item-summary-reminder-1-day-before =
    .label = 1 dia antes
calendar-item-summary-reminder-2-days-before =
    .label = 2 dias antes
calendar-item-summary-reminder-1-week-before =
    .label = 1 semana antes
calendar-item-summary-reminder-custom =
    .label = Personalizar…
calendar-item-summary-reminder-multiple =
    .value = Múltiplos lembretes…
calendar-item-summary-general =
    .value = Geral
calendar-item-summary-attendees =
    .value = Participantes
calendar-item-summary-description =
    .value = Descrição
calendar-item-summary-link =
    .value = Ligação relacionada
