# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Selecionar tudo
select-none-calendars = Selecionar nenhum
calendar-creation-wizard-title = Criar novo calendário
calendar-creation-initial-description = O seu calendário pode ser guardado no seu computador ou num servidor para acesso remoto ou partilha.
calendar-creation-initial-computer =
    .label = No meu computador
calendar-creation-initial-network =
    .label = Na rede
calendar-creation-username =
    .value = Nome de utilizador:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Criar calendário
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retroceder
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Criar calendário
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Retroceder
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Localizar calendários
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Retroceder
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Subscrever
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Retroceder
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = Tipo de calendário:
calendar-creation-location =
    .value = Localização:
calendar-creation-location-placeholder =
    .placeholder = URL ou nome do servidor para o servidor do calendário
    .default-placeholder = URL ou nome do servidor para o servidor do calendário
calendar-creation-network-nocredentials =
    .label = Esta localização não requer credenciais
calendar-creation-network-loading = Por favor, aguarde enquanto se está à procura dos seus calendários.
calendar-creation-network-notfound = Não foi possível encontrar os calendários nesta localização. Por favor, verifique as suas definições.
calendar-creation-network-authfail = As credenciais que introduziu não foram aceites. Por favor verifique as suas definições.
calendar-creation-network-certerror = Não foram encontrados calendários nesta localização devido a um problema com o certificado.
calendar-creation-network-subscribe-single = Por favor, selecione os calendários que gostaria de subscrever.
calendar-creation-network-subscribe-multiple = Estão disponíveis múltiplos tipos de calendários nesta localização. Por favor, selecione o tipo de calendário, depois marque os calendários que gostaria de subscrever.
