# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Pretraživanje…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 podudaranje pronađeno;#1 podudaranja pronađeno
noMatchesFound = Nema podudaranja
labelForStopButton = Stani
labelForSearchButton = Traži
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = T
moreButtonTooltipText = Dodaj novo pravilo
lessButtonTooltipText = Ukloni ovo pravilo
