# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Nastajenja offline
autodetect-connection-label =
    .label = Moduse awtomatiski wuměniś, gaž se internetny zwisk namakajo
    .accesskey = d
offline-startup-label = Gaž se { -brand-short-name } wócynja:
status-radio-last-used =
    .label = Zwiskowy modus wužywaś, kótarež jo se ako slědny wužywał
    .accesskey = Z
status-radio-ask-connect =
    .label = Pšašaś se, lěc se ma online zwězaś
    .accesskey = l
status-radio-start-online =
    .label = Online zachopiś
    .accesskey = n
status-radio-start-offline =
    .label = Offline zachopiś
    .accesskey = f
going-online-prompt = Powěsći słaś, kótarež we wašom postowem wuchaźe cakaju
going-online-send =
    .label = Jo, awtomatiski pósłaś
    .accesskey = J
going-online-keep =
    .label = No, we wuchaźe wobchowaś
    .accesskey = N
going-online-ask-send =
    .label = Pśed słanim se pšašaś
    .accesskey = P
going-offline-prompt = Cośo powěsći ześěgnuś, aby je offline cytał?
going-offline-download =
    .label = Jo, awtomatiski ześěgnuś
    .accesskey = o
going-offline-keep =
    .label = Ně, njeześěgnuś
    .accesskey = z
going-offline-ask-download =
    .label = Pśed ześěgowanim se pšašaś
    .accesskey = P
autodetect-online-label =
    .label = Namakanemu online-statusoju awtomatiski slědowaś
    .accesskey = o
offline-preference-startup-label = Manuelny status pśi startowanju:
status-radio-remember =
    .label = Se pjerwjejšny status online spomnjeś
    .accesskey = t
status-radio-ask =
    .label = Za online-statusom se pšašaś
    .accesskey = š
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Njepósłane powěsći wótesłaś, gaž źośo online?
going-online-auto =
    .label = Jo
    .accesskey = J
going-online-not =
    .label = Ně 1
    .accesskey = 1
going-online-ask =
    .label = Pšašaś se
    .accesskey = P
going-offline-label = Powěsći za wužywanje offline ześěgnuś, gaž źośo offline?
going-offline-auto =
    .label = Jo
    .accesskey = o
going-offline-not =
    .label = Ně 2
    .accesskey = 2
going-offline-ask =
    .label = Pšašaś se
    .accesskey = s
