# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Wobtwarźenja dostaśa
return-receipt-checkbox-control =
    .label = Pśi słanju powěsćow sebje pśecej wobtwarźenje dostaśa pominaś
    .accesskey = P
receipt-arrive-label = Gaž se wobtwarźenje dostaśa dojźo:
receipt-leave-inbox-control =
    .label = W dochaźe posta wóstajiś
    .accesskey = c
receipt-move-sent-control =
    .label = Do zarědnika Pósłany pśesunuś
    .accesskey = r
receipt-sender-request-label = Gaž wótpósłaŕ wobkšuśenje dostaś pomina:
receipt-leave-radio-control =
    .label = Jo w mójom postowem kašćiku wóstajiś
    .accesskey = k
receipt-move-radio-control =
    .label = Jo do mójogo zarědnika „Pósłany“ pśesunuś
    .accesskey = P
receipt-request-label = Gaž dostanjom pominanje za wobtwarźenim dostaśa:
receipt-return-never-radio-control =
    .label = Nigdy wobtwarźenje njesłaś
    .accesskey = N
receipt-return-some-radio-control =
    .label = Wobtwarźenja dostaśa za někotare powěsći dowóliś
    .accesskey = t
receipt-not-listed-cc-label =
    .value = Jolic w póli Komu abo Kopija njepódany:
    .accesskey = J
receipt-not-to-cc-label =
    .value = Jolic njejsom w póli Komu abo Kopija powěsći:
    .accesskey = l
receipt-send-never-label =
    .label = Nigdy njesłaś
receipt-send-always-label =
    .label = Pśecej pósłaś
receipt-send-ask-label =
    .label = Pšašaś se
sender-outside-company-label =
    .value = Jolic wótpósłaŕ k pśedewześeju abo domenje njesłuša:
    .accesskey = t
sender-outside-domain-label =
    .value = Jolic wótpósłaŕ jo zwenka mójeje domeny:
    .accesskey = o
other-cases-text-label =
    .value = We wšych drugich padach:
    .accesskey = u
read-receipts-dialog-title = Cytańske kwitowanki
