# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Hľadá sa…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 nájdený výsledok;#1 nájdené výsledky;#1 nájdených výsledkov
noMatchesFound = Neboli nájdené žiadne výsledky
labelForStopButton = Zastaviť
labelForSearchButton = Hľadať
labelForStopButton.accesskey = s
labelForSearchButton.accesskey = H
moreButtonTooltipText = Pridať nové pravidlo
lessButtonTooltipText = Odstrániť toto pravidlo
