# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentář
calendar-item-summary-title = Název:
calendar-item-summary-calendar = Kalendář:
calendar-item-summary-task-start = Začátek:
calendar-item-summary-event-start = Začátek:
calendar-item-summary-task-due = Splnit do:
calendar-item-summary-event-end = Konec:
calendar-item-summary-repeat = Opakovat:
calendar-item-summary-location = Místo:
calendar-item-summary-category = Kategorie:
calendar-item-summary-organizer = Organizátor:
calendar-item-summary-status = Stav:
calendar-item-summary-reminder = Připomenutí:
calendar-item-summary-attachments = Přílohy:
calendar-item-summary-status-tentative = Předběžně
calendar-item-summary-status-confirmed = Potvrzeno
calendar-item-summary-event-status-cancelled = Zrušeno
calendar-item-summary-todo-status-cancelled = Zrušeno
calendar-item-summary-status-needs-action = Vyžaduje akci
calendar-item-summary-status-in-process = Probíhá
calendar-item-summary-status-completed = Ukončeno
calendar-item-summary-reminder-none =
    .label = Bez připomenutí
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minut před
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minut před
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minut před
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minut před
calendar-item-summary-reminder-1-hour-before =
    .label = 1 hodinu před
calendar-item-summary-reminder-2-hours-before =
    .label = 2 hodiny před
calendar-item-summary-reminder-12-hours-before =
    .label = 12 hodin před
calendar-item-summary-reminder-1-day-before =
    .label = 1 den před
calendar-item-summary-reminder-2-days-before =
    .label = 2 dny před
calendar-item-summary-reminder-1-week-before =
    .label = 1 týden před
calendar-item-summary-reminder-custom =
    .label = Vlastní…
calendar-item-summary-reminder-multiple =
    .value = Vícenásobné připomenutí…
calendar-item-summary-general =
    .value = Obecné
calendar-item-summary-attendees =
    .value = Účastníci
calendar-item-summary-description =
    .value = Popis
calendar-item-summary-link =
    .value = Související odkaz
