# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Vybrat vše
select-none-calendars = Nic nevybrat
calendar-creation-wizard-title = Vytváření nového kalendáře
calendar-creation-initial-description = Kalendář může být vytvořen na tomto počítači nebo na serveru v síti, odkud k němu můžete přistupovat nebo ho sdílet se svými přáteli či spolupracovníky.
calendar-creation-initial-computer =
    .label = Na tomto počítači
calendar-creation-initial-network =
    .label = V síti
calendar-creation-username =
    .value = Uživatelské jméno:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Vytvořit kalendář
    .buttonaccesskeyaccept = V
    .buttonlabelextra2 = Zpět
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Vytvořit kalendář
    .buttonaccesskeyaccept = V
    .buttonlabelextra2 = Zpět
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Hledat kalendáře
    .buttonaccesskeyaccept = H
    .buttonlabelextra2 = Zpět
    .buttonaccesskeyextra2 = Z
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Přihlásit se
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Zpět
    .buttonaccesskeyextra2 = Z
calendar-creation-type =
    .value = Typ kalendáře:
calendar-creation-location =
    .value = Adresa:
calendar-creation-location-placeholder =
    .placeholder = Adresa URL nebo název hostitele kalendářového serveru
    .default-placeholder = Adresa URL nebo název hostitele kalendářového serveru
calendar-creation-network-nocredentials =
    .label = Toto umístění nevyžaduje přihlašovací údaje
calendar-creation-network-loading = Počkejte prosím než budou nalezeny vaše kalendáře.
calendar-creation-network-notfound = Kalendáře se v tomto umístění nepodařilo najít. Zkontrolujte prosím svá nastavení.
calendar-creation-network-authfail = Zadané přihlašovací údaje nebyly přijaty. Zkontrolujte prosím svá nastavení.
calendar-creation-network-certerror = V tomto umístění nebylo možné najít kalendáře kvůli problému s certifikátem.
calendar-creation-network-subscribe-single = Vyberte prosím kalendář, který chcete přidat.
calendar-creation-network-subscribe-multiple = V tomto umístění se nachází více typů kalendářů. Vyberte prosím typ kalendáře a pak označte ty, které chcete přidat.
