# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Offline-ynstellingen
autodetect-connection-label =
    .label = Automaysk wikselje fan modus wannear’t der in ynternetferbining fûn is
    .accesskey = d
offline-startup-label = By it iepenjen fan { -brand-short-name }:
status-radio-last-used =
    .label = Lêst brûkte ferbiningsmodus brûke
    .accesskey = g
status-radio-ask-connect =
    .label = Freegje oft jo online ferbine wolle
    .accesskey = F
status-radio-start-online =
    .label = Online starte
    .accesskey = l
status-radio-start-offline =
    .label = Offline starte
    .accesskey = f
going-online-prompt = Berjochten dy’t yn jo Postfek ÚT wachtsje ferstjoere
going-online-send =
    .label = Ja, automatysk ferstjoere
    .accesskey = J
going-online-keep =
    .label = Nee, yn Postfek ÚT litte
    .accesskey = N
going-online-ask-send =
    .label = Freegje foar ferstjoeren
    .accesskey = F
going-offline-prompt = Wolle jo berjochten downloade om offline te lêzen?
going-offline-download =
    .label = Ja, automatysk downloade
    .accesskey = J
going-offline-keep =
    .label = Nee, net downloade
    .accesskey = N
going-offline-ask-download =
    .label = Freegje foar downloade
    .accesskey = F
autodetect-online-label =
    .label = Automatysk detektearre onlinetastân folgje
    .accesskey = A
offline-preference-startup-label = Hânmjittige tastân by it opstarten:
status-radio-remember =
    .label = Foarige onlinetastân hantearje
    .accesskey = h
status-radio-ask =
    .label = My de onlinetastân freegje
    .accesskey = M
status-radio-always-online =
    .label = Online
    .accesskey = O
status-radio-always-offline =
    .label = Altyd offline opstarte
    .accesskey = f
going-online-label = Wolle jo net-ferstjoerde berjochten ferstjoere as jo online gean?
going-online-auto =
    .label = Ja
    .accesskey = J
going-online-not =
    .label = Nee
    .accesskey = N
going-online-ask =
    .label = My freegje
    .accesskey = f
going-offline-label = Wolle jo berjochten downloade foar offline gebrûk foardat jo offline gean?
going-offline-auto =
    .label = Ja
    .accesskey = a
going-offline-not =
    .label = Nee
    .accesskey = e
going-offline-ask =
    .label = My freegje
    .accesskey = r
