# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Bình luận
calendar-item-summary-title = Tiêu đề:
calendar-item-summary-calendar = Lịch:
calendar-item-summary-task-start = Ngày bắt đầu:
calendar-item-summary-event-start = Ngày bắt đầu:
calendar-item-summary-task-due = Ngày đến hạn:
calendar-item-summary-event-end = Ngày kết thúc:
calendar-item-summary-repeat = Lặp lại:
calendar-item-summary-location = Địa chỉ:
calendar-item-summary-category = Phân mục:
calendar-item-summary-organizer = Người tổ chức:
calendar-item-summary-status = Trạng thái:
calendar-item-summary-reminder = Nhắc việc:
calendar-item-summary-attachments = Đính kèm:
calendar-item-summary-status-tentative = Phân vân
calendar-item-summary-status-confirmed = Đã xác nhận
calendar-item-summary-event-status-cancelled = Đã hủy
calendar-item-summary-todo-status-cancelled = Đã hủy
calendar-item-summary-status-needs-action = Cần thao tác
calendar-item-summary-status-in-process = Đang xử lí
calendar-item-summary-status-completed = Xong vào
calendar-item-summary-reminder-none =
    .label = Không có lời nhắc
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 phút trước khi
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 phút trước khi
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 phút trước khi
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 phút trước khi
calendar-item-summary-reminder-1-hour-before =
    .label = 1 tiếng trước khi
calendar-item-summary-reminder-2-hours-before =
    .label = 2 tiếng trước khi
calendar-item-summary-reminder-12-hours-before =
    .label = 12 tiếng trước khi
calendar-item-summary-reminder-1-day-before =
    .label = 1 ngày trước khi
calendar-item-summary-reminder-2-days-before =
    .label = 2 ngày trước khi
calendar-item-summary-reminder-1-week-before =
    .label = 1 tuần trước khi
calendar-item-summary-reminder-custom =
    .label = Tùy biến…
calendar-item-summary-reminder-multiple =
    .value = Nhiều lời nhắc…
calendar-item-summary-general =
    .value = Tổng quát
calendar-item-summary-attendees =
    .value = Người tham dự
calendar-item-summary-description =
    .value = Mô tả
calendar-item-summary-link =
    .value = Liên kết liên quan
