# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Chọn tất cả
select-none-calendars = Bỏ chọn tất cả
calendar-creation-wizard-title = Tạo lịch mới
calendar-creation-initial-description = Bộ lịch của bạn có thể được lưu trữ trên máy tính hoặc trên một máy chủ để có thể truy cập nó từ xa hoặc chia sẻ nó với bạn bè hoặc đồng nghiệp.
calendar-creation-initial-computer =
    .label = Trên máy tính của tôi
calendar-creation-initial-network =
    .label = Trên mạng
calendar-creation-username =
    .value = Tên người dùng:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Tạo lịch
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Quay lại
    .buttonaccesskeyextra2 = B
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Tạo lịch
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Quay lại
    .buttonaccesskeyextra2 = B
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Tìm lịch
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Quay lại
    .buttonaccesskeyextra2 = B
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Đăng ký
    .buttonaccesskeyaccept = S
    .buttonlabelextra2 = Quay lại
    .buttonaccesskeyextra2 = B
calendar-creation-type =
    .value = Kiểu lịch:
calendar-creation-location =
    .value = Địa chỉ:
calendar-creation-location-placeholder =
    .placeholder = URL hoặc tên máy chủ của máy chủ lịch
    .default-placeholder = URL hoặc tên máy chủ của máy chủ lịch
calendar-creation-network-nocredentials =
    .label = Vị trí này không yêu cầu thông tin đăng nhập
calendar-creation-network-loading = Xin vui lòng chờ trong khi lịch của bạn đang được phát hiện.
calendar-creation-network-notfound = Không thể tìm thấy lịch tại địa chỉ này. Vui lòng kiểm tra cài đặt của bạn.
calendar-creation-network-authfail = Thông tin đăng nhập bạn đã nhập không được chấp nhận. Vui lòng kiểm tra cài đặt của bạn.
calendar-creation-network-certerror = Không tìm thấy lịch ở vị trí này vì có vấn đề về chứng chỉ.
calendar-creation-network-subscribe-single = Vui lòng chọn lịch bạn muốn đăng ký.
calendar-creation-network-subscribe-multiple = Nhiều loại lịch có sẵn cho địa chỉ này. Vui lòng chọn kiểu lịch, sau đó đánh dấu các lịch bạn muốn đăng ký.
