# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Offline-instellingen
autodetect-connection-label =
    .label = Automatisch wisselen van modus wanneer er een internetverbinding is gevonden
    .accesskey = d
offline-startup-label = Bij het openen van { -brand-short-name }:
status-radio-last-used =
    .label = Laatst gebruikte verbindingsmodus gebruiken
    .accesskey = g
status-radio-ask-connect =
    .label = Vragen of u online wilt verbinden
    .accesskey = V
status-radio-start-online =
    .label = Online starten
    .accesskey = l
status-radio-start-offline =
    .label = Offline starten
    .accesskey = f
going-online-prompt = Berichten die in uw Postvak UIT wachten verzenden
going-online-send =
    .label = Ja, automatisch verzenden
    .accesskey = J
going-online-keep =
    .label = Nee, in Postvak UIT laten
    .accesskey = N
going-online-ask-send =
    .label = Vragen voor verzenden
    .accesskey = r
going-offline-prompt = Wilt u berichten downloaden om offline te lezen?
going-offline-download =
    .label = Ja, automatisch downloaden
    .accesskey = a
going-offline-keep =
    .label = Nee, niet downloaden
    .accesskey = e
going-offline-ask-download =
    .label = Vragen voor downloaden
    .accesskey = a
autodetect-online-label =
    .label = Automatisch gedetecteerde onlinetoestand volgen
    .accesskey = A
offline-preference-startup-label = Handmatige toestand bij het opstarten:
status-radio-remember =
    .label = Vorige onlinetoestand hanteren
    .accesskey = h
status-radio-ask =
    .label = Mij de onlinetoestand vragen
    .accesskey = M
status-radio-always-online =
    .label = Online
    .accesskey = O
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Niet-verzonden berichten verzenden bij online gaan?
going-online-auto =
    .label = Ja
    .accesskey = J
going-online-not =
    .label = Nee
    .accesskey = N
going-online-ask =
    .label = Mij vragen
    .accesskey = v
going-offline-label = Berichten downloaden voor offlinegebruik bij offline gaan?
going-offline-auto =
    .label = Ja
    .accesskey = a
going-offline-not =
    .label = Nee
    .accesskey = e
going-offline-ask =
    .label = Mij vragen
    .accesskey = r
