# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Leesbevestigingen
return-receipt-checkbox-control =
    .label = Altijd een leesbevestiging vragen bij het verzenden van berichten
    .accesskey = A
receipt-arrive-label = Als een leesbevestiging binnenkomt:
receipt-leave-inbox-control =
    .label = In Postvak IN laten
    .accesskey = P
receipt-move-sent-control =
    .label = Verplaatsen naar map Verzonden
    .accesskey = m
receipt-sender-request-label = Als een afzender om een leesbevestiging vraagt:
receipt-leave-radio-control =
    .label = Deze in mijn Postvak IN laten staan
    .accesskey = i
receipt-move-radio-control =
    .label = Deze naar mijn map ‘Verzonden’ verplaatsen
    .accesskey = v
receipt-request-label = Als ik een verzoek voor een leesbevestiging ontvang:
receipt-return-never-radio-control =
    .label = Nooit een leesbevestiging sturen
    .accesskey = n
receipt-return-some-radio-control =
    .label = Leesbevestigingen bij sommige berichten toestaan
    .accesskey = r
receipt-not-listed-cc-label =
    .value = Indien niet vermeld in het Aan- of Cc-veld
    .accesskey = m
receipt-not-to-cc-label =
    .value = Als ik niet in de Aan of Cc van het bericht sta:
    .accesskey = l
receipt-send-never-label =
    .label = Nooit verzenden
receipt-send-always-label =
    .label = Altijd verzenden
receipt-send-ask-label =
    .label = Mij vragen
sender-outside-company-label =
    .value = Als de afzender zich buiten het bedrijf of domein bevindt:
    .accesskey = b
sender-outside-domain-label =
    .value = Als de afzender zich buiten mijn domein bevindt:
    .accesskey = t
other-cases-text-label =
    .value = In alle andere gevallen:
    .accesskey = a
read-receipts-dialog-title = Leesbevestigingen
return-receipt-request-control =
    .label = Altijd een leesbevestiging vragen bij het verzenden van e-mailberichten
    .accesskey = z
