# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = ช่องว่างแบบยืดหยุ่น
search-bar-label = ค้นหา
toolbar-write-message-label = เขียน
toolbar-write-message =
    .title = สร้างข้อความใหม่
toolbar-move-to-label = ย้ายไปยัง
toolbar-move-to =
    .title = ย้ายข้อความที่เลือก
toolbar-unifinder-label = ค้นหาเหตุการณ์
toolbar-unifinder =
    .title = เปิด/ปิดบานหน้าต่างการค้นหาเหตุการณ์
toolbar-folder-location-label = ตำแหน่งที่ตั้งโฟลเดอร์
toolbar-folder-location =
    .title = สลับไปยังโฟลเดอร์
toolbar-edit-event-label = แก้ไข
toolbar-edit-event =
    .title = แก้ไขเหตุการณ์หรืองานที่เลือก
toolbar-get-messages-label = รับข้อความ
toolbar-get-messages =
    .title = ดึงข้อความใหม่สำหรับทุกบัญชี
toolbar-reply-label = ตอบกลับ
toolbar-reply =
    .title = ตอบกลับถึงข้อความ
toolbar-reply-all-label = ตอบกลับทั้งหมด
toolbar-reply-all =
    .title = ตอบกลับถึงผู้ส่งและผู้รับทั้งหมด
toolbar-reply-to-list-label = ตอบกลับถึงรายการ
toolbar-reply-to-list =
    .title = ตอบกลับถึงรายชื่อผู้รับจดหมาย
toolbar-redirect-label = เปลี่ยนเส้นทาง
toolbar-redirect =
    .title = เปลี่ยนเส้นทางข้อความที่เลือก
toolbar-archive-label = เก็บถาวร
toolbar-archive =
    .title = เก็บถาวรข้อความที่เลือก
toolbar-conversation-label = การสนทนา
toolbar-conversation =
    .title = แสดงการสนทนาของข้อความที่เลือก
toolbar-previous-unread-label = ก่อนหน้าที่ยังไม่ได้อ่าน
toolbar-previous-unread =
    .title = ย้ายไปยังข้อความที่ยังไม่ได้อ่านก่อนหน้า
toolbar-previous-label = ก่อนหน้า
toolbar-previous =
    .title = ย้ายไปยังข้อความก่อนหน้า
toolbar-next-unread-label = ถัดไปที่ยังไม่ได้อ่าน
toolbar-next-unread =
    .title = ย้ายไปยังข้อความที่ยังไม่ได้อ่านถัดไป
toolbar-next-label = ถัดไป
toolbar-next =
    .title = ย้ายไปยังข้อความถัดไป
toolbar-junk-label = ขยะ
toolbar-junk =
    .title = ทำเครื่องหมายข้อความที่เลือกว่าเป็นขยะ
toolbar-delete-label = ลบ
toolbar-delete-title =
    .title = ลบข้อความที่เลือก
toolbar-undelete-label = เลิกลบ
toolbar-undelete =
    .title = เลิกลบข้อความที่เลือก
toolbar-compact-label = กระชับ
toolbar-compact =
    .title = เอาข้อความที่ถูกลบออกจากโฟลเดอร์ที่เลือก
toolbar-add-as-event-label = เพิ่มเป็นเหตุการณ์
toolbar-add-as-event =
    .title = แยกข้อมูลปฏิทินจากข้อความและเพิ่มลงในปฏิทินของคุณเป็นเหตุการณ์
toolbar-add-as-task-label = เพิ่มเป็นงาน
toolbar-add-as-task =
    .title = แยกข้อมูลปฏิทินจากข้อความและเพิ่มลงในปฏิทินของคุณเป็นงาน
toolbar-tag-message-label = ป้ายกำกับ
toolbar-tag-message =
    .title = ติดป้ายกำกับข้อความ
toolbar-forward-inline-label = ส่งต่อ
toolbar-forward-inline =
    .title = ส่งต่อข้อความที่เลือกเป็นข้อความแบบอินไลน์
toolbar-forward-attachment-label = ส่งต่อเป็นไฟล์แนบ
toolbar-forward-attachment =
    .title = ส่งต่อข้อความที่เลือกเป็นไฟล์แนบ
toolbar-mark-as-label = ทำเครื่องหมาย
toolbar-mark-as =
    .title = ทำเครื่องหมายข้อความ
toolbar-view-picker-label = มุมมอง
toolbar-view-picker =
    .title = ปรับแต่งมุมมองของโฟลเดอร์ปัจจุบัน
toolbar-address-book-label = สมุดรายชื่อ
toolbar-address-book =
    .title = ไปยังสมุดรายชื่อ
toolbar-chat-label = แชท
toolbar-chat =
    .title = แสดงแท็บแชท
toolbar-add-ons-and-themes-label = ส่วนเสริมและชุดรูปแบบ
toolbar-add-ons-and-themes =
    .title = จัดการส่วนเสริมของคุณ
toolbar-calendar-label = ปฏิทิน
toolbar-calendar =
    .title = สลับไปยังแท็บปฏิทิน
toolbar-tasks-label = งาน
toolbar-tasks =
    .title = สลับไปยังแท็บงาน
toolbar-mail-label = จดหมาย
toolbar-mail =
    .title = สลับไปยังแท็บจดหมาย
toolbar-print-label = พิมพ์
toolbar-print =
    .title = พิมพ์ข้อความนี้
toolbar-quick-filter-bar-label = ตัวกรองแบบเร็ว
toolbar-quick-filter-bar =
    .title = กรองข้อความ
toolbar-synchronize-label = ประสาน
toolbar-synchronize =
    .title = โหลดปฏิทินใหม่และประสานการเปลี่ยนแปลง
toolbar-delete-event-label = ลบ
toolbar-delete-event =
    .title = ลบเหตุการณ์หรืองานที่เลือก
toolbar-go-to-today-label = ไปยังวันนี้
toolbar-go-to-today =
    .title = ไปยังวันนี้
toolbar-print-event-label = พิมพ์
toolbar-print-event =
    .title = พิมพ์เหตุการณ์หรืองาน
toolbar-new-event-label = เหตุการณ์
toolbar-new-event =
    .title = สร้างเหตุการณ์ใหม่
toolbar-new-task-label = งาน
toolbar-new-task =
    .title = สร้างงานใหม่
toolbar-go-back-label = ย้อนกลับ
toolbar-go-back =
    .title = ย้อนกลับไปหนึ่งข้อความ
toolbar-go-forward-label = เดินหน้า
toolbar-go-forward =
    .title = เดินหน้าไปหนึ่งข้อความ
toolbar-stop-label = หยุด
toolbar-stop =
    .title = หยุดการถ่ายโอนปัจจุบัน
toolbar-throbber-label = ตัวบ่งชี้กิจกรรม
toolbar-throbber =
    .title = ตัวบ่งชี้กิจกรรม
toolbar-create-contact-label = ผู้ติดต่อใหม่
toolbar-create-contact =
    .title = สร้างผู้ติดต่อใหม่
toolbar-create-address-book-label = สมุดรายชื่อใหม่
toolbar-create-address-book =
    .title = สร้างสมุดรายชื่อใหม่
toolbar-create-list-label = รายชื่อใหม่
toolbar-create-list =
    .title = สร้างรายชื่อผู้รับจดหมายใหม่
toolbar-import-contacts-label = นำเข้า
toolbar-import-contacts =
    .title = นำเข้าผู้ติดต่อจากไฟล์

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = เพิ่มสมุดรายชื่อในเครื่อง
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = เพิ่มสมุดรายชื่อ CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = เพิ่มสมุดรายชื่อ LDAP
