# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Athugasemd
calendar-item-summary-title = Titill:
calendar-item-summary-calendar = Dagatal:
calendar-item-summary-task-start = Byrjunardagsetning:
calendar-item-summary-event-start = Byrjunardagsetning:
calendar-item-summary-task-due = Framkvæmist fyrir:
calendar-item-summary-event-end = Lokadagsetning:
calendar-item-summary-repeat = Endurtaka:
calendar-item-summary-location = Staðsetning:
calendar-item-summary-category = Flokkur:
calendar-item-summary-organizer = Fundarstjóri:
calendar-item-summary-status = Staða:
calendar-item-summary-reminder = Áminning:
calendar-item-summary-attachments = Viðhengi:
calendar-item-summary-status-tentative = Með fyrirvara
calendar-item-summary-status-confirmed = Samþykkt
calendar-item-summary-event-status-cancelled = Hætt við
calendar-item-summary-todo-status-cancelled = Hætt við
calendar-item-summary-status-needs-action = Þarfnast aðgerðar
calendar-item-summary-status-in-process = Í gangi
calendar-item-summary-status-completed = Lokið þann
calendar-item-summary-reminder-none =
    .label = Engin áminning
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 mínútur fyrir
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 mínútum fyrir
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 mínútum fyrir
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 mínútum fyrir
calendar-item-summary-reminder-1-hour-before =
    .label = 1 klukkustund fyrir
calendar-item-summary-reminder-2-hours-before =
    .label = 2 klukkustundum fyrir
calendar-item-summary-reminder-12-hours-before =
    .label = 12 klukkustundum fyrir
calendar-item-summary-reminder-1-day-before =
    .label = 1 degi fyrir
calendar-item-summary-reminder-2-days-before =
    .label = 2 dögum fyrir
calendar-item-summary-reminder-1-week-before =
    .label = 1 viku fyrir
calendar-item-summary-reminder-custom =
    .label = Sérsniðið…
calendar-item-summary-reminder-multiple =
    .value = Margar áminningar…
calendar-item-summary-general =
    .value = Almennt
calendar-item-summary-attendees =
    .value = Þátttakendur
calendar-item-summary-description =
    .value = Lýsing
calendar-item-summary-link =
    .value = Tengdur hlekkur
