# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Velja allt
select-none-calendars = Velja ekkert
calendar-creation-wizard-title = Búa til nýtt dagatal
calendar-creation-initial-description = Hægt er að geyma dagatalið þitt á tölvunni þinni eða geyma það á miðli svo hægt sé að deila því með vinum og vinnufélögum.
calendar-creation-initial-computer =
    .label = Á tölvunni minni
calendar-creation-initial-network =
    .label = Á netinu
calendar-creation-username =
    .value = Notandanafn:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Búa til dagatal
    .buttonaccesskeyaccept = d
    .buttonlabelextra2 = Til baka
    .buttonaccesskeyextra2 = b
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Búa til dagatal
    .buttonaccesskeyaccept = d
    .buttonlabelextra2 = Til baka
    .buttonaccesskeyextra2 = b
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Finna dagatöl
    .buttonaccesskeyaccept = F
    .buttonlabelextra2 = Til baka
    .buttonaccesskeyextra2 = b
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Gerast áskrifandi
    .buttonaccesskeyaccept = s
    .buttonlabelextra2 = Til baka
    .buttonaccesskeyextra2 = b
calendar-creation-type =
    .value = Tegund dagatals:
calendar-creation-location =
    .value = Staðsetning:
calendar-creation-location-placeholder =
    .placeholder = Vefslóð eða hýsingarheiti dagatalsþjónsins
    .default-placeholder = Vefslóð eða hýsingarheiti dagatalsþjónsins
calendar-creation-network-nocredentials =
    .label = Þessi staðsetning krefst ekki auðkenningar
calendar-creation-network-loading = Hinkraðu við á meðan verið er að finna dagatölin þín.
calendar-creation-network-notfound = Fann ekki nein dagatöl á þessum stað. Athugaðu stillingarnar þínar.
calendar-creation-network-authfail = Auðkennin sem þú settir inn voru ekki samþykkt. Athugaðu stillingarnar þínar.
calendar-creation-network-certerror = Ekki tókst að finna dagatöl á þessum stað vegna vandamáls með skilríki.
calendar-creation-network-subscribe-single = Veldu dagatölin sem þú vilt gerast áskrifandi að.
calendar-creation-network-subscribe-multiple = Margar gerðir dagatala eru tiltækar fyrir þessa staðsetningu. Veldu gerð dagatalsins og merktu síðan dagatölin sem þú vilt gerast áskrifandi að.
