# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espacio flexible
search-bar-label = Buscar
toolbar-write-message-label = Redactar
toolbar-write-message =
    .title = Crear nuevo mensaje
toolbar-move-to-label = Mover a
toolbar-move-to =
    .title = Mover el mensaje seleccionado
toolbar-unifinder-label = Buscar eventos
toolbar-unifinder =
    .title = Alternar el panel de búsqueda de eventos
toolbar-folder-location-label = Ubicación de la carpeta
toolbar-folder-location =
    .title = Cambiar a carpeta
toolbar-edit-event-label = Editar
toolbar-edit-event =
    .title = Editar tarea o evento seleccionado
toolbar-get-messages-label = Recibir mensajes
toolbar-get-messages =
    .title = Buscar nuevos mensajes en todas las cuentas
toolbar-reply-label = Responder
toolbar-reply =
    .title = Responder al mensaje
toolbar-reply-all-label = Resp. a todos
toolbar-reply-all =
    .title = Responder al remitente y a todos los destinatarios
toolbar-reply-to-list-label = Responder a la lista
toolbar-reply-to-list =
    .title = Responder a la lista de correo
toolbar-redirect-label = Redirigir
toolbar-redirect =
    .title = Redirige el mensaje seleccionado
toolbar-archive-label = Archivar
toolbar-archive =
    .title = Archivar mensajes seleccionados
toolbar-conversation-label = Conversación
toolbar-conversation =
    .title = Mostrar conversación del mensaje seleccionado
toolbar-previous-unread-label = Anterior no leído
toolbar-previous-unread =
    .title = Ir al anterior mensaje no leído
toolbar-previous-label = Anterior
toolbar-previous =
    .title = Moverse al mensaje anterior
toolbar-next-unread-label = Siguiente no leído
toolbar-next-unread =
    .title = Ir al siguiente mensaje no leído
toolbar-next-label = Siguiente
toolbar-next =
    .title = Moverse al mensaje siguiente
toolbar-junk-label = Basura
toolbar-junk =
    .title = Marcar los mensajes seleccionados como basura
toolbar-delete-label = Eliminar
toolbar-delete =
    .title = Eliminar mensajes o carpetas seleccionadas
toolbar-compact-label = Compactar
toolbar-compact =
    .title = Eliminar mensajes borrados de la carpeta seleccionada
toolbar-add-as-event-label = Añadir como evento
toolbar-add-as-event =
    .title = Extraer información de calendario del mensaje y añadirla a su calendario como un evento
toolbar-add-as-task-label = Añadir como tarea
toolbar-add-as-task =
    .title = Extraer información de calendario del mensaje y añadirla a su calendario como una tarea
toolbar-tag-message-label = Etiqueta
toolbar-tag-message =
    .title = Etiquetar mensajes
toolbar-forward-inline-label = Reenviar
toolbar-forward-inline =
    .title = Reenviar el mensaje seleccionado como texto en el cuerpo
toolbar-forward-attachment-label = Reenviar como adjunto
toolbar-forward-attachment =
    .title = Reenviar el mensaje seleccionado como un adjunto
toolbar-mark-as-label = Marcar
toolbar-mark-as =
    .title = Marcar mensajes
toolbar-view-picker-label = Vista
toolbar-view-picker =
    .title = Personalizar la vista de la carpeta actual
toolbar-address-book-label = Libreta de direcciones
toolbar-address-book =
    .title = Ir a la libreta de direcciones
toolbar-chat-label = Charlar
toolbar-chat =
    .title = Mostrar la pestaña de chat
toolbar-add-ons-and-themes-label = Complementos y temas
toolbar-add-ons-and-themes =
    .title = Administre sus complementos
toolbar-calendar-label = Calendario
toolbar-calendar =
    .title = Pasar a la pestaña del calendario
toolbar-tasks-label = Tareas
toolbar-tasks =
    .title = Pasar a la barra de herramientas de tareas
toolbar-mail-label = Correo
toolbar-mail =
    .title = Cambiar a la pestaña de correo
toolbar-print-label = Imprimir
toolbar-print =
    .title = Imprimir este mensaje
toolbar-quick-filter-bar-label = Filtro rápido
toolbar-quick-filter-bar =
    .title = Filtrar mensajes
