# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibelt mellomrom
search-bar-label = Søk
toolbar-write-message-label = Skriv
toolbar-write-message =
    .title = Skriv ny melding
toolbar-move-to-label = Flytt til
toolbar-move-to =
    .title = Flytt den valgte meldingen
toolbar-unifinder-label = Finn hendelser
toolbar-unifinder =
    .title = Slå av/på finn hendelser
toolbar-folder-location-label = Mappeplassering
toolbar-folder-location =
    .title = Bytt til mappe
toolbar-edit-event-label = Rediger
toolbar-edit-event =
    .title = Rediger valgte hendelser eller oppgaver
toolbar-get-messages-label = Hent meldinger
toolbar-get-messages =
    .title = Hent nye meldinger for alle kontoer
toolbar-reply-label = Svar
toolbar-reply =
    .title = Svar til avsender
toolbar-reply-all-label = Svar alle
toolbar-reply-all =
    .title = Svar til avsender og alle mottakere
toolbar-reply-to-list-label = Svar til liste
toolbar-reply-to-list =
    .title = Svar til e-postliste
toolbar-redirect-label = Omdiriger
toolbar-redirect =
    .title = Omdiriger den valgte meldingen
toolbar-archive-label = Arkiver
toolbar-archive =
    .title = Arkiver valgt melding
toolbar-conversation-label = Samtale
toolbar-conversation =
    .title = Vis samtalen for valgt melding
toolbar-previous-unread-label = Forrige uleste
toolbar-previous-unread =
    .title = Gå til forrige uleste melding
toolbar-previous-label = Forrige
toolbar-previous =
    .title = Gå til forrige melding
toolbar-next-unread-label = Neste uleste
toolbar-next-unread =
    .title = Gå til neste uleste melding
toolbar-next-label = Neste
toolbar-next =
    .title = Gå til neste melding
toolbar-spam-label = Søppelpost
toolbar-spam =
    .title = Merk de valgte meldingene som søppelpost
toolbar-not-spam-label = Ikke søppelpost
toolbar-not-spam =
    .title = Merk de valgte meldingene som ikke søppelpost
toolbar-junk-label = Uønsket
toolbar-junk =
    .title = Merk de valgte meldingene som uønsket e-post
toolbar-delete-label = Slett
toolbar-delete-title =
    .title = Slett de valgte meldingene
toolbar-undelete-label = Angre sletting
toolbar-undelete =
    .title = Angre sletting av valgte meldinger
toolbar-compact-label = Komprimer
toolbar-compact =
    .title = Fjern slettede meldinger fra valgt mappe
toolbar-add-as-event-label = Legg til som hendelse
toolbar-add-as-event =
    .title = Hent ut kalenderinfo fra meldingen og legg den til i kalenderen din som en hendelse
toolbar-add-as-task-label = Legg til som oppgave
toolbar-add-as-task =
    .title = Hent ut kalenderinfo fra meldingen og legg den til i kalenderen din som en oppgave
toolbar-tag-message-label = Etikett
toolbar-tag-message =
    .title = Merk melding
toolbar-forward-inline-label = Videresend
toolbar-forward-inline =
    .title = Videresend valgt melding som innbundet tekst
toolbar-forward-attachment-label = Videresend som vedlegg
toolbar-forward-attachment =
    .title = Videresend valgt melding som et vedlegg
toolbar-mark-as-label = Merk
toolbar-mark-as =
    .title = Merk meldinger
toolbar-view-picker-label = Vis
toolbar-view-picker =
    .title = Tilpass visning av gjeldende mappe
toolbar-address-book-label = Adressebok
toolbar-address-book =
    .title = Åpne adresseboken
toolbar-chat-label = Nettprat
toolbar-chat =
    .title = Vis nettprat-fanen
toolbar-add-ons-and-themes-label = Tillegg og temaer
toolbar-add-ons-and-themes =
    .title = T
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Bytt til kalenderfanen
toolbar-tasks-label = Oppgaver
toolbar-tasks =
    .title = Bytt til oppgavefanen
toolbar-mail-label = E-post
toolbar-mail =
    .title = Bytt til e-postfanen
toolbar-print-label = Skriv ut
toolbar-print =
    .title = Skriv ut denne meldingen
toolbar-quick-filter-bar-label = Hurtigfilter
toolbar-quick-filter-bar =
    .title = Filtrer meldinger
toolbar-synchronize-label = Synkroniser
toolbar-synchronize =
    .title = Oppdater kalendre og synkroniser endringer
toolbar-delete-event-label = Slett
toolbar-delete-event =
    .title = Slett valgte hendelser eller oppgaver
toolbar-go-to-today-label = Gå til i dag
toolbar-go-to-today =
    .title = Gå til i dag
toolbar-print-event-label = Skriv ut
toolbar-print-event =
    .title = Skriv ut hendelser eller oppgaver
toolbar-new-event-label = Hendelse
toolbar-new-event =
    .title = Lag en ny hendelse
toolbar-new-task-label = Oppgave
toolbar-new-task =
    .title = Lag en ny oppgave
toolbar-go-back-label = Tilbake
toolbar-go-back =
    .title = Gå tilbake en melding
toolbar-go-forward-label = Frem
toolbar-go-forward =
    .title = Gå frem en melding
toolbar-stop-label = Stopp
toolbar-stop =
    .title = Stopp denne overføringen
toolbar-throbber-label = Aktivitetsindikator
toolbar-throbber =
    .title = Aktivitetsindikator
toolbar-create-contact-label = Ny kontakt
toolbar-create-contact =
    .title = Opprett en ny kontakt
toolbar-create-address-book-label = Ny adressebok
toolbar-create-address-book =
    .title = Opprett en ny adressebok
toolbar-create-list-label = Ny liste
toolbar-create-list =
    .title = Opprett en ny e-postliste
toolbar-import-contacts-label = Importer
toolbar-import-contacts =
    .title = Importer kontakter fra en fil

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Legg til lokal adressebok
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Legg til CardDAV-adressebok
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Legg til LDAP-adressebok
