# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Anzeigename
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Typ
vcard-entry-type-home = Privat
vcard-entry-type-work = Dienstlich
vcard-entry-type-none = Unbekannt
vcard-entry-type-custom = Benutzerdefiniert
vcard-name-header = Name
vcard-n-prefix = Präfix
vcard-n-add-prefix =
    .title = Präfix
vcard-n-firstname = Vorname
vcard-n-add-firstname =
    .title = Vornamen hinzufügen
vcard-n-middlename = Zweiter Vorname
vcard-n-add-middlename =
    .title = Zweiten Vornamen hinzufügen
vcard-n-lastname = Nachname
vcard-n-add-lastname =
    .title = Nachnamen hinzufügen
vcard-n-suffix = Suffix
vcard-n-add-suffix =
    .title = Suffix hinzufügen
vcard-nickname = Spitzname
vcard-email-header = E-Mail-Adresse
vcard-email-add = E-Mail-Adresse hinzufügen
vcard-email-label = E-Mail-Adresse
vcard-primary-email-label = Standard
vcard-url-header = Websites
vcard-url-add = Website hinzufügen
vcard-url-label = Website
vcard-tel-header = Telefonnummern
vcard-tel-add = Telefonnummer hinzufügen
vcard-tel-label = Telefonnummer
# Or "Mobile"
vcard-entry-type-cell = Mobil
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pager
vcard-tz-header = Zeitzone
vcard-tz-add = Zeitzone hinzufügen
vcard-impp2-header = Instant Messaging
vcard-impp-add = Chat-Konto hinzufügen
vcard-impp-label = Chat-Konto
vcard-impp-select = Protokoll
vcard-impp-option-other = Sonstiges
vcard-impp-input-label = URI
vcard-impp-input-title = URI für Instant Messaging
vcard-bday-anniversary-header = Wichtige Tage
vcard-bday-anniversary-add = Wichtigen Tag hinzufügen
vcard-bday-label = Geburtstag
vcard-anniversary-label = Jubiläum
vcard-date-day = Tag
vcard-date-month = Monat
vcard-date-year = Jahr
vcard-adr-header = Adressen
vcard-adr-add = Adresse hinzufügen
vcard-adr-label = Adresse
vcard-adr-delivery-label = Lieferungsbeschriftung
vcard-adr-street = Straßenadresse
# Or "Locality"
vcard-adr-locality = Stadt
# Or "Region"
vcard-adr-region = Bundesland/Provinz
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postleitzahl
vcard-adr-country = Land
vcard-note-header = Notizen
vcard-note-add = Notiz hinzufügen
vcard-org-header = Organisationseigenschaften
vcard-org-add = Organisationseigenschaften hinzufügen
vcard-org-title = Titel
vcard-org-title-input =
    .placeholder = Berufsbezeichnung
    .title = Position oder Tätigkeit
vcard-org-role = Position
vcard-org-role-input =
    .placeholder = Funktion in einem Projekt
    .title = Funktion oder Rolle, die in einer bestimmten Situation gespielt wird
vcard-org-org = Organisation
vcard-org-org-input =
    .placeholder = Firmenname
    .title = Name der Organisation
vcard-org-org-unit = Abteilung
vcard-org-org-unit-input =
    .placeholder = Abteilung
    .title = Name der Organisationseinheit
vcard-custom-header = Benutzerdefinierte Eigenschaften
vcard-custom-add = Benutzerdefinierte Eigenschaften hinzufügen
vcard-remove-button-title =
    .title = Entfernen
vcard-remove-button = Entfernen
