# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Zwobraznjeńske mě
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Typ
vcard-entry-type-home = Priwatny
vcard-entry-type-work = Słužbny telefon
vcard-entry-type-none = Žeden
vcard-entry-type-custom = Swójski
vcard-name-header = Mě
vcard-n-prefix = Prefiks
vcard-n-add-prefix =
    .title = Prefiks pśidaś
vcard-n-firstname = Pśedmě
vcard-n-add-firstname =
    .title = Pśedmě pśidaś
vcard-n-middlename = Druge pśedmě
vcard-n-add-middlename =
    .title = Druge pśedmě pśidaś
vcard-n-lastname = Familijowe mě
vcard-n-add-lastname =
    .title = Familijowe mě pśidaś
vcard-n-suffix = Sufiks
vcard-n-add-suffix =
    .title = Sufiks pśidaś
vcard-nickname = Pśimě
vcard-email-header = E-mailowe adrese
vcard-email-add = E-mailowu adresu pśidaś
vcard-email-label = E-mailowa adresa
vcard-primary-email-label = Standard
vcard-url-header = Websedła
vcard-url-add = Websedło pśidaś
vcard-url-label = Websedło
vcard-tel-header = Telefonowe numery
vcard-tel-add = Telefonowy numer pśidaś
vcard-tel-label = Telefonowy numer
# Or "Mobile"
vcard-entry-type-cell = Cela
vcard-entry-type-fax = Faks
vcard-entry-type-pager = Pager
vcard-tz-header = Casowa cona
vcard-tz-add = Casowu conu pśidaś
vcard-impp2-header = Pósrědnjanje powěsćow ned
vcard-impp-add = Chatowe konto pśidaś
vcard-impp-label = Chatowe konto
vcard-impp-select = Protokol
vcard-impp-option-other = Druge
vcard-impp-input-label = URI
vcard-impp-input-title = URI za pósrědnjanje powěsćow ned
vcard-bday-anniversary-header = Specialne datumy
vcard-bday-anniversary-add = Specialny datum pśidaś
vcard-bday-label = Narodny źeń
vcard-anniversary-label = Wrośenica
vcard-date-day = Źeń
vcard-date-month = Mjasec
vcard-date-year = Lěto
vcard-adr-header = Adrese
vcard-adr-add = Adresu pśidaś
vcard-adr-label = Adresa
vcard-adr-delivery-label = Librowański etiket
vcard-adr-street = Drogowa adresa
# Or "Locality"
vcard-adr-locality = Město
# Or "Region"
vcard-adr-region = Zwězkowy kraj
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postowa licba
vcard-adr-country = Kraj
vcard-note-header = Pśipiski
vcard-note-add = Pśipisk pśidaś
vcard-org-header = Organizaciske kakosći
vcard-org-add = Organizaciske kakosći pśidaś
vcard-org-title = Titel
vcard-org-title-input =
    .placeholder = Titel joba
    .title = Pozicija abo job
vcard-org-role = Rola
vcard-org-role-input =
    .placeholder = Rola w projekśe
    .title = Funkcija abo rola, kótaraž se we wěstej situaciji grajo
vcard-org-org = Organizacija
vcard-org-org-input =
    .placeholder = Mě pśedewześa
    .title = Mě organizacije
vcard-org-org-unit = Wótźělenje
vcard-org-org-unit-input =
    .placeholder = Wótźělenje
    .title = Mě organizaciskeje jadnotki
vcard-custom-header = Swójske kakosći
vcard-custom-add = Swójske kakosći pśidaś
vcard-remove-button-title =
    .title = Wótwónoźeś
vcard-remove-button = Wótwónoźeś
