# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Seleziona tutto
select-none-calendars = Seleziona nessuno
calendar-creation-wizard-title = Creazione nuovo calendario
calendar-creation-initial-description = Il calendario può essere salvato sul proprio computer o essere salvato su un server in modo da potervi accedere in remoto o condividerlo con amici o collaboratori.
calendar-creation-initial-computer =
    .label = Sul computer in uso
calendar-creation-initial-network =
    .label = Sulla rete
calendar-creation-username =
    .value = Nome utente:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Crea calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Indietro
    .buttonaccesskeyextra2 = n
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Crea calendario
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Indietro
    .buttonaccesskeyextra2 = n
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Trova calendari
    .buttonaccesskeyaccept = T
    .buttonlabelextra2 = Indietro
    .buttonaccesskeyextra2 = n
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Iscriviti
    .buttonaccesskeyaccept = s
    .buttonlabelextra2 = Indietro
    .buttonaccesskeyextra2 = n
calendar-creation-type =
    .value = Tipo di calendario:
calendar-creation-location =
    .value = Indirizzo:
calendar-creation-location-placeholder =
    .placeholder = URL o nome host del server del calendario
    .default-placeholder = URL o nome host del server del calendario
calendar-creation-network-nocredentials =
    .label = Questa posizione non richiede credenziali
calendar-creation-network-loading = Attendere mentre vengono individuati i calendari.
calendar-creation-network-notfound = Impossibile trovare calendari a questo indirizzo. Controllare le impostazioni.
calendar-creation-network-authfail = Le credenziali inserite non sono state accettate. Controllare le impostazioni.
calendar-creation-network-certerror = Impossibile trovare i calendari in questa posizione a causa di un problema con il certificato.
calendar-creation-network-subscribe-single = Selezionare i calendari da sottoscrivere.
calendar-creation-network-subscribe-multiple = A questo indirizzo sono disponibili tipi di calendario multipli. Selezionare prima il tipo di calendario, poi i calendari da sottoscrivere.
