# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Commento
calendar-item-summary-title = Titolo:
calendar-item-summary-calendar = Calendario:
calendar-item-summary-task-start = Data di inizio:
calendar-item-summary-event-start = Data di inizio:
calendar-item-summary-task-due = Data di scadenza:
calendar-item-summary-event-end = Data di fine:
calendar-item-summary-repeat = Ripeti:
calendar-item-summary-location = Luogo:
calendar-item-summary-category = Categoria:
calendar-item-summary-organizer = Organizzatore:
calendar-item-summary-status = Stato:
calendar-item-summary-reminder = Promemoria:
calendar-item-summary-attachments = Allegati:
calendar-item-summary-status-tentative = Da confermare
calendar-item-summary-status-confirmed = Confermato
calendar-item-summary-event-status-cancelled = Cancellato
calendar-item-summary-todo-status-cancelled = Cancellata
calendar-item-summary-status-needs-action = Richiede un’azione
calendar-item-summary-status-in-process = In corso
calendar-item-summary-status-completed = Completata il
calendar-item-summary-reminder-none =
    .label = Nessun promemoria
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuti prima
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuti prima
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuti prima
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuti prima
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ora prima
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ore prima
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ore prima
calendar-item-summary-reminder-1-day-before =
    .label = 1 giorno prima
calendar-item-summary-reminder-2-days-before =
    .label = 2 giorni prima
calendar-item-summary-reminder-1-week-before =
    .label = 1 settimana prima
calendar-item-summary-reminder-custom =
    .label = Personalizzato…
calendar-item-summary-reminder-multiple =
    .value = Promemoria multipli…
calendar-item-summary-general =
    .value = Generale
calendar-item-summary-attendees =
    .value = Partecipanti
calendar-item-summary-description =
    .value = Descrizione
calendar-item-summary-link =
    .value = Collegamenti correlati
