# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = è un evento ricorrente
header-containsrepeating-event =
    .label = contiene eventi ricorrenti
header-containsrepeating-task =
    .label = contiene attività ricorrenti
header-containsrepeating-mixed =
    .label = contiene elementi ricorrenti di tipi diversi
windowtitle-event-copy = Copia eventi ricorrenti
windowtitle-task-copy = Copia attività ricorrenti
windowtitle-mixed-copy = Copia elementi ricorrenti
windowtitle-event-cut = Taglia eventi ricorrenti
windowtitle-task-cut = Taglia attività ricorrenti
windowtitle-mixed-cut = Taglia elementi ricorrenti
windowtitle-mixed-delete = Elimina elementi ricorrenti
windowtitle-mixed-edit = Modifica elementi ricorrenti
windowtitle-multipleitems =
    .value = Elementi selezionati
buttons-single-occurrence-copy =
    .label = Copia solo questa occorrenza
buttons-single-occurrence-cut =
    .label = Taglia solo questa occorrenza
buttons-single-occurrence-delete =
    .label = Elimina solo questa occorrenza
buttons-single-occurrence-edit =
    .label = Modifica solo questa occorrenza
buttons-multiple-occurrence-copy =
    .label = Copia solo occorrenze selezionate
buttons-multiple-occurrence-cut =
    .label = Taglia solo occorrenze selezionate
buttons-multiple-occurrence-delete =
    .label = Elimina solo occorrenze selezionate
buttons-multiple-occurrence-edit =
    .label = Modifica solo occorrenze selezionate
buttons-single-allfollowing-copy =
    .label = Copia questa occorrenza e tutte quelle future
buttons-single-allfollowing-cut =
    .label = Taglia questa occorrenza e tutte quelle future
buttons-single-allfollowing-delete =
    .label = Elimina questa occorrenza e tutte quelle future
buttons-single-allfollowing-edit =
    .label = Modifica questa occorrenza e tutte quelle future
buttons-single-parent-copy =
    .label = Copia tutte le occorrenze
buttons-single-parent-cut =
    .label = Taglia tutte le occorrenze
buttons-single-parent-delete =
    .label = Elimina tutte le occorrenze
buttons-single-parent-edit =
    .label = Modifica tutte le occorrenze
buttons-multiple-parent-copy =
    .label = Copia tutte le occorrenze degli elementi selezionati
buttons-multiple-parent-cut =
    .label = Taglia tutte le occorrenze degli elementi selezionati
buttons-multiple-parent-delete =
    .label = Elimina tutte le occorrenze degli elementi selezionati
buttons-multiple-parent-edit =
    .label = Modifica tutte le occorrenze degli elementi selezionati
