# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Beàrn sùbailte
toolbar-write-message-label = Sgrìobh
toolbar-write-message =
    .title = Cruthaich teachdaireachd ùr
toolbar-unifinder-label = Lorg tachartasan
toolbar-unifinder =
    .title = Toglaich an leòsan a lorgas tachartasan
toolbar-folder-location-label = Seòladh a' phasgain
toolbar-edit-event-label = Deasaich
toolbar-edit-event =
    .title = Deasaich an tachartas no saothair a thagh thu
toolbar-get-messages-label = Faigh am post
toolbar-reply-label = Freagair
toolbar-reply =
    .title = Freagair an teachdaireachd
toolbar-reply-all-label = Freagair a h-uile
toolbar-reply-all =
    .title = Freagair an seòladair 's a h-uile faightear
toolbar-reply-to-list-label = Freagair an liosta
toolbar-reply-to-list =
    .title = Freagair an liosta puist
toolbar-archive-label = Tasg-lann
toolbar-archive =
    .title = Cuir na teachdaireachdan a thagh thu san tasg-lann
toolbar-conversation-label = Còmhradh
toolbar-conversation =
    .title = Seall còmhradh na teachdaireachd a thagh thu
toolbar-previous-unread-label = An teachdaireachd roimhe gun leughadh
toolbar-previous-unread =
    .title = Gluais dhan teachdaireachd roimhe nach deach a leughadh
toolbar-previous-label = Air ais
toolbar-previous =
    .title = Gluais dhan teachdaireachd roimhe
toolbar-next-unread-label = An ath-theachdaireachd gun leughadh
toolbar-next-unread =
    .title = Gluais dhan ath-theachdaireachd nach deach a leughadh
toolbar-next-label = Air adhart
toolbar-next =
    .title = Gluais dhan ath-theachdaireachd
toolbar-compact-label = Dùmhlaich
toolbar-compact =
    .title = Thoir air falbh na teachdaireachdan a chaidh an sguabadh às on phasgan a thagh thu
toolbar-add-as-event-label = Cuir ris mar thachartas
toolbar-add-as-event =
    .title = Tog fiosrachadh mìosachain on teachdaireachd is cuir ris a' mhìosachan e mar thachartas
toolbar-add-as-task-label = Cuir ris mar shaothair
toolbar-add-as-task =
    .title = Tog fiosrachadh mìosachain on teachdaireachd is cuir ris a' mhìosachan e mar shaothair
toolbar-tag-message-label = Taga
toolbar-tag-message =
    .title = Cuir taga ris na teachdaireachdan
toolbar-forward-inline-label = Sìn air adhart
toolbar-forward-inline =
    .title = Sìn air adhart an teachdaireachd a thagh thu mar theacsa taobh a-staigh na loidhne
toolbar-forward-attachment-label = Sin air adhart mar cheanglachan
toolbar-forward-attachment =
    .title = Sìn air adhart an teachdaireachd a thagh thu mar cheanglachan
toolbar-mark-as-label = Cuir comharra
toolbar-mark-as =
    .title = Cuir comharra air na teachdaireachdan
toolbar-address-book =
    .title = Rach do leabhar nan seòladh
toolbar-chat-label = Cabadaich
toolbar-chat =
    .title = Seall taba na cabadaich
toolbar-calendar-label = Mìosachan
toolbar-calendar =
    .title = Leum gu taba a' mhìosachain
toolbar-tasks-label = Saothraichean
toolbar-tasks =
    .title = Leum gu taba nan saothraichean
toolbar-print-label = Clò-bhuail
toolbar-print =
    .title = Clò-bhuail an teachdaireachd seo
toolbar-synchronize-label = Sioncronaich
toolbar-synchronize =
    .title = Ath-luchdaich na mìosachain is sioncronaich na h-atharraichean
toolbar-delete-event-label = Sguab às
toolbar-delete-event =
    .title = Sguab às na tachartasan no saothraichean a thagh thu
toolbar-go-to-today-label = Rach gu an-diugh
toolbar-go-to-today =
    .title = Rach gu an-diugh
toolbar-print-event-label = Clò-bhuail
toolbar-print-event =
    .title = Clò-bhuail na tachartasan no saothraichean
toolbar-new-event-label = Tachartas
toolbar-new-event =
    .title = Cruthaich tachartas ùr
toolbar-new-task-label = Saothair
toolbar-new-task =
    .title = Cruthaich saothair ùr
toolbar-go-back-label = Air ais
toolbar-go-back =
    .title = Aon teachdaireachd air ais
toolbar-go-forward-label = Air adhart
toolbar-go-forward =
    .title = Aon teachdaireachd air adhart
toolbar-stop-label = Sguir dheth
toolbar-stop =
    .title = Sguir dhen tar-aiseag làithreach
toolbar-throbber-label = Tosgair gnìomhachd
toolbar-throbber =
    .title = Tosgair gnìomhachd
