# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Tallunt tafallaẓt
search-bar-label = Nadi
toolbar-write-message-label = Aru
toolbar-write-message =
    .title = Rnu izen amaynut
toolbar-move-to-label = Senkez ɣer
toolbar-move-to =
    .title = Senkez izen i yettwafernen
toolbar-unifinder-label = Aff-d tidyanin
toolbar-unifinder =
    .title = Snefli/Fneẓ agalis n unadu ɣef tedyanin
toolbar-folder-location-label = Tansa n ukaram
toolbar-edit-event-label = Ẓreg
toolbar-edit-event =
    .title = Ẓreg tadyant neɣ tawuri yettwafernen
toolbar-get-messages-label = Awid iznan
toolbar-reply-label = Err
toolbar-reply =
    .title = Err i yizen
toolbar-reply-all-label = Err-asen akk
toolbar-reply-all =
    .title = E&rr i wemazan d inarmasen
toolbar-reply-to-list-label = Err i tebdart
toolbar-reply-to-list =
    .title = Err i tabdart n tnezwit
toolbar-redirect-label = Abeddel n uwelleh
toolbar-redirect =
    .title = Abeddel n uwelleh i yizen yettufernen
toolbar-archive-label = Aɣbaṛ
toolbar-archive =
    .title = Ḥrez iznan yettwafernen
toolbar-conversation-label = Adiwenni
toolbar-conversation =
    .title = Sken adiwenni n yizen yettwafernen
toolbar-previous-unread-label = Ɣer deffir - Win ur nettwaɣri ara
toolbar-previous-unread =
    .title = Ddu ɣer yizen n deffir ur nettwaɣri ara
toolbar-previous-label = Ɣeṛ deffir
toolbar-previous =
    .title = Senkez ɣeṛ yizen azewwar
toolbar-next-unread-label = Ɣer zdat- Win ur nettwaɣri ara
toolbar-next-unread =
    .title = Ddu ɣer yizen ur nettwaɣri ara i d-iteddun
toolbar-next-label = Ɣeṛ zdat
toolbar-next =
    .title = Ddu ɣer yizen d-iteddun ur nettwaɣri ara
toolbar-junk-label = Aspam
toolbar-junk =
    .title = Creḍ iznan yettwafernen d ispamen
toolbar-delete-label = Kkes
toolbar-delete =
    .title = Kkes iznan neɣ ikaramen yettwafernen
toolbar-delete-title =
    .title = Kkes iznan yettwafernen
toolbar-undelete-label = Sefsex tukksa
toolbar-compact-label = Ssed
toolbar-compact =
    .title = Kkes iznan ittwaksen seg ukaram ifernen
toolbar-add-as-event-label = Rnu tadyant
toolbar-add-as-event =
    .title = Suffeɣ-d talɣut n uwitay seg izen sakin renu-tt d tadyant ɣer uwitay
toolbar-add-as-task-label = Rnu tawuri
toolbar-add-as-task =
    .title = Suffeɣ-d talɣut n uwitay seg izen sakin renu-tt d tawuri ɣer uwitay
toolbar-tag-message-label = Tabzimt
toolbar-tag-message =
    .title = Rnu tabzimt i yiznan
toolbar-forward-inline-label = Ɣer &zdat
toolbar-forward-inline =
    .title = Welleh izen yettwafernen am uḍris umniḍ
toolbar-forward-attachment-label = Welleh am umedday
toolbar-forward-attachment =
    .title = Welleh izen yettwafernen am umedday
toolbar-mark-as-label = Cṛeḍ
toolbar-mark-as =
    .title = Cṛeḍ iznan
toolbar-view-picker-label = Sken
toolbar-address-book-label = Imedlis n tensa
toolbar-address-book =
    .title = Ddu ɣeṛ imedlis n tensa
toolbar-chat-label = Adiwenni usrid
toolbar-chat =
    .title = Sken iccer n udiwenni usrid
toolbar-add-ons-and-themes-label = Izegrar d yisental
toolbar-add-ons-and-themes =
    .title = Sefrek izegrar-inek·inem
toolbar-calendar-label = Awitay
toolbar-calendar =
    .title = Ddu ɣer yiccer n uwitay
toolbar-tasks-label = Tiwuriwin
toolbar-tasks =
    .title = Ddu ɣer yiccer n twuriwin
toolbar-mail-label = Tirawt
toolbar-print-label = Siggez
toolbar-print =
    .title = Siggez izen-agi
toolbar-quick-filter-bar-label = Imzizdeg arurad
toolbar-quick-filter-bar =
    .title = Sizdeg iznan
toolbar-synchronize-label = Mtawi
toolbar-synchronize =
    .title = Sal-id tikelt nniḍen iwitayen u mtawi isnifal
toolbar-delete-event-label = Kkes
toolbar-delete-event =
    .title = Kkes tidyanin neɣ tiwuriwin yettwafernen
toolbar-go-to-today-label = Ddu ɣer Ass-a
toolbar-go-to-today =
    .title = Ddu ɣer Ass-a
toolbar-print-event-label = Siggez
toolbar-print-event =
    .title = Siggez tidyanin neɣ tiwuriwin
toolbar-new-event-label = Tadyant
toolbar-new-event =
    .title = Rnu tadyant tamaynut
toolbar-new-task-label = Tawuri
toolbar-new-task =
    .title = Rnu tawuri tamaynut
toolbar-go-back-label = ɣer deffir
toolbar-go-back =
    .title = Uɣal ɣeṛ deffir s yiwen n yizen
toolbar-go-forward-label = Ɣer zdat
toolbar-go-forward =
    .title = Ddu ɣeṛ zdat s yiwen n yizen
toolbar-stop-label = Rken
toolbar-stop =
    .title = Seḥbes asiweḍ amiran
toolbar-throbber-label = anamal n wermud
toolbar-throbber =
    .title = anamal n wermud
