# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Zobrazované jméno
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Typ
vcard-entry-type-home = Domů
vcard-entry-type-work = Práce
vcard-entry-type-none = Žádný
vcard-entry-type-custom = Vlastní
vcard-name-header = Jméno
vcard-n-prefix = Titul před jménem
vcard-n-add-prefix =
    .title = Přidat titul před jménem
vcard-n-firstname = Křestní jméno
vcard-n-add-firstname =
    .title = Přidat křestní jméno
vcard-n-middlename = Prostřední jméno
vcard-n-add-middlename =
    .title = Přidat prostřední jméno
vcard-n-lastname = Příjmení
vcard-n-add-lastname =
    .title = Přidat příjmení
vcard-n-suffix = Titul za jménem
vcard-n-add-suffix =
    .title = Přidat titul za jménem
vcard-nickname = Přezdívka
vcard-email-header = E-mailové adresy
vcard-email-add = Přidat e-mailové adresy
vcard-email-label = E-mailová adresa
vcard-primary-email-label = Výchozí
vcard-url-header = Webové stránky
vcard-url-add = Přidat webovou stránku
vcard-url-label = Webová stránka
vcard-tel-header = Telefonní čísla
vcard-tel-add = Přidat telefonní číslo
vcard-tel-label = Telefonní číslo
# Or "Mobile"
vcard-entry-type-cell = Mobil
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Pager
vcard-tz-header = Časové pásmo
vcard-tz-add = Přidat časové pásmo
vcard-impp2-header = Okamžité zprávy
vcard-impp-add = Přidat účet chatu
vcard-impp-label = Účet chatu
vcard-impp-select = Protokol
vcard-impp-option-other = Ostatní
vcard-impp-input-label = URI
vcard-impp-input-title = URI pro okamžité zprávy
vcard-bday-anniversary-header = Speciální data
vcard-bday-anniversary-add = Přidat speciální datum
vcard-bday-label = Narozeniny
vcard-anniversary-label = Výročí
vcard-date-day = Den
vcard-date-month = Měsíc
vcard-date-year = Rok
vcard-adr-header = Adresy
vcard-adr-add = Přidat adresu
vcard-adr-label = Adresa
vcard-adr-delivery-label = Doručovací štítek
vcard-adr-street = Ulice
# Or "Locality"
vcard-adr-locality = Město
# Or "Region"
vcard-adr-region = Stát/Kraj
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = PSČ
vcard-adr-country = Země
vcard-note-header = Poznámky
vcard-note-add = Přidat poznámku
vcard-org-header = Informace o společnosti
vcard-org-add = Přidat informace o společnosti
vcard-org-title = Pozice
vcard-org-title-input =
    .placeholder = Název práce
    .title = Pozice nebo práce
vcard-org-role = Role
vcard-org-role-input =
    .placeholder = Role v projektu
    .title = Funkce nebo úloha v konkrétní situaci
vcard-org-org = Společnost
vcard-org-org-input =
    .placeholder = Název společnosti
    .title = Název organizace
vcard-org-org-unit = Oddělení
vcard-org-org-unit-input =
    .placeholder = Oddělení
    .title = Název jednotky organizace
vcard-custom-header = Vlastní položky
vcard-custom-add = Přidat vlastní položky
vcard-remove-button-title =
    .title = Odebrat
vcard-remove-button = Odebrat
