# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Өзгертілетін аралық
search-bar-label = Іздеу
toolbar-write-message-label = Жазу
toolbar-write-message =
    .title = Жаңа хабарламаны жасау
toolbar-move-to-label = Келесі жерге жылжыту
toolbar-move-to =
    .title = Таңдалған хабарламаны жылжыту
toolbar-unifinder-label = Оқиғаларды табу
toolbar-unifinder =
    .title = Оқиғаны табу панелін көрсету/жасыру
toolbar-folder-location-label = Буманың орналасуы
toolbar-folder-location =
    .title = Бумаға ауысу
toolbar-edit-event-label = Түзету
toolbar-edit-event =
    .title = Таңдалған оқиғаны немесе тапсырманы түзету
toolbar-get-messages-label = Хабарламаларды алу
toolbar-get-messages =
    .title = Барлық тіркелгілер үшін жаңа хабарламаларды алу
toolbar-reply-label = Жауап беру
toolbar-reply =
    .title = Хабарламаға жауап беру
toolbar-reply-all-label = Барлығына жауап беру
toolbar-reply-all =
    .title = Жіберуші және барлық алушыларға жауап беру
toolbar-reply-to-list-label = Тізімге жауап беру
toolbar-reply-to-list =
    .title = Эл. поштаны тарату тізіміне жауап беру
toolbar-redirect-label = Қайта бағдарлау
toolbar-redirect =
    .title = Таңдалған хабарламаны қайта бағдарлау
toolbar-archive-label = Архивтеу
toolbar-archive =
    .title = Таңдалған хабарламаны архивтеу
toolbar-conversation-label = Сөйлесу
toolbar-conversation =
    .title = Таңдалған хабарламаның сөйлесуін көрсету
toolbar-previous-unread-label = Алдыңғы оқылмаған
toolbar-previous-unread =
    .title = Алдыңғы оқылмаған хабарламаға өту
toolbar-previous-label = Алдыңғы
toolbar-previous =
    .title = Алдыңғы хабарламаға өту
toolbar-next-unread-label = Келесі оқылмаған
toolbar-next-unread =
    .title = Келесі оқылмаған хабарламаға өту
toolbar-next-label = Келесі
toolbar-next =
    .title = Келесі хабарламаға өту
toolbar-junk-label = Спам
toolbar-junk =
    .title = Таңдалған хабарламаларды спам ретінде белгілеу
toolbar-delete-label = Өшіру
toolbar-delete-title =
    .title = Таңдалған хабарламаларды өшіру
toolbar-undelete-label = Өшірілгенді қалпына келтіру
toolbar-undelete =
    .title = Таңдалған өшірілген хабарламаларды қалпына келтіру
toolbar-compact-label = Ықшамдау
toolbar-compact =
    .title = Таңдалған бумадан өшірілген хабарламаларды жою
toolbar-add-as-event-label = Оқиға ретінде қосу
toolbar-add-as-event =
    .title = Хабарламадан күнтізбелік ақпаратты шығарып, оны күнтізбеңізге оқиға ретінде қосу
toolbar-add-as-task-label = Тапсырма ретінде қосу
toolbar-add-as-task =
    .title = Хабарламадан күнтізбелік ақпаратты шығарып, оны күнтізбеңізге тапсырма ретінде қосу
toolbar-tag-message-label = Тег
toolbar-tag-message =
    .title = Хабарламаларға тег қою
toolbar-forward-inline-label = Әрі қарай жіберу
toolbar-forward-inline =
    .title = Таңдалған хабарламаны құрамындағы мәтін ретінде қайта бағдарлау
toolbar-forward-attachment-label = Салыным ретінде әрі қарай жіберу
toolbar-forward-attachment =
    .title = Таңдалған хабарламаны салыным ретінде әрі қарай жіберу
toolbar-mark-as-label = Белгілеу
toolbar-mark-as =
    .title = Хабарламаларды белгілеу
toolbar-view-picker-label = Түрі
toolbar-view-picker =
    .title = Ағымдағы бума көрінісін баптау
toolbar-address-book-label = Адрестік кітапша
toolbar-address-book =
    .title = Адрестік кітапшаға өту
toolbar-chat-label = Чат
toolbar-chat =
    .title = Чат бетін көрсету
toolbar-add-ons-and-themes-label = Қосымшалар және темалар
toolbar-add-ons-and-themes =
    .title = Қосымшаларыңызды басқару
toolbar-calendar-label = Күнтізбе
toolbar-calendar =
    .title = Күнтізбе бетіне ауысу
toolbar-tasks-label = Тапсырмалар
toolbar-tasks =
    .title = Тапсырмалар бетіне ауысу
toolbar-mail-label = Эл. пошта
toolbar-mail =
    .title = Эл. пошта бетіне ауысу
toolbar-print-label = Баспаға шығару
toolbar-print =
    .title = Ағымдағы хабарламаны баспаға шығару
toolbar-quick-filter-bar-label = Жедел сүзгі
toolbar-quick-filter-bar =
    .title = Хабарламаларды сүзгілеу
toolbar-synchronize-label = Синхрондау
toolbar-synchronize =
    .title = Күнтізбелерді қайта жүктеу және өзгерістерді синхрондау
toolbar-delete-event-label = Өшіру
toolbar-delete-event =
    .title = Таңдалған оқиғалар немесе тапсырмаларды өшіру
toolbar-go-to-today-label = Бүгінге өту
toolbar-go-to-today =
    .title = Бүгінге өту
toolbar-print-event-label = Баспаға шығару
toolbar-print-event =
    .title = Оқиғалар немесе тапсырмаларды баспаға шығару
toolbar-new-event-label = Оқиға
toolbar-new-event =
    .title = Жаңа оқиғаны жасау
toolbar-new-task-label = Тапсырма
toolbar-new-task =
    .title = Жаңа тапсырманы жасау
toolbar-go-back-label = Артқа
toolbar-go-back =
    .title = Бір хабарламаға артқа өту
toolbar-go-forward-label = Алға
toolbar-go-forward =
    .title = Бір хабарламаға алға өту
toolbar-stop-label = Тоқтату
toolbar-stop =
    .title = Ағымдағы тасымалдауды тоқтату
toolbar-throbber-label = Активтілік айқындағышы
toolbar-throbber =
    .title = Активтілік айқындағышы
toolbar-create-contact-label = Жаңа контакт
toolbar-create-contact =
    .title = Жаңа контакт жасау
toolbar-create-address-book-label = Жаңа адрестік кітапша
toolbar-create-address-book =
    .title = Жаңа адрестік кітапшаны жасау
toolbar-create-list-label = Жаңа тізім
toolbar-create-list =
    .title = Жаңа хат тарату тізімін жасау
toolbar-import-contacts-label = Импорттау
toolbar-import-contacts =
    .title = Файлдан контакттарды импорттау

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Жергілікті адрестік кітапшаны қосу
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV адрестік кітапшасын қосу
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP адрестік кітапшасын қосу
