# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Εμφανιζόμενο όνομα
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Τύπος
vcard-entry-type-home = Οικία
vcard-entry-type-work = Εργασία
vcard-entry-type-none = Κανένα
vcard-entry-type-custom = Προσαρμοσμένο
vcard-name-header = Όνομα
vcard-n-prefix = Πρόθεμα
vcard-n-add-prefix =
    .title = Προσθήκη προθέματος
vcard-n-firstname = Όνομα
vcard-n-add-firstname =
    .title = Προσθήκη ονόματος
vcard-n-middlename = Μεσαίο όνομα
vcard-n-add-middlename =
    .title = Προσθήκη μεσαίου ονόματος
vcard-n-lastname = Επώνυμο
vcard-n-add-lastname =
    .title = Προσθήκη επωνύμου
vcard-n-suffix = Επίθεμα
vcard-n-add-suffix =
    .title = Προσθήκη επιθέματος
vcard-nickname = Ψευδώνυμο
vcard-email-header = Διευθύνσεις email
vcard-email-add = Προσθήκη διεύθυνσης email
vcard-email-label = Διεύθυνση email
vcard-primary-email-label = Προεπιλογή
vcard-url-header = Ιστότοποι
vcard-url-add = Προσθήκη ιστοτόπου
vcard-url-label = Ιστότοπος
vcard-tel-header = Αριθμοί τηλεφώνου
vcard-tel-add = Προσθήκη αριθμού τηλεφώνου
vcard-tel-label = Αριθμός τηλεφώνου
# Or "Mobile"
vcard-entry-type-cell = Κινητό
vcard-entry-type-fax = Φαξ
vcard-entry-type-pager = Βομβητής
vcard-tz-header = Ζώνη ώρας
vcard-tz-add = Προσθήκη ζώνης ώρας
vcard-impp2-header = Άμεσα μηνύματα
vcard-impp-add = Προσθήκη λογαριασμού συνομιλίας
vcard-impp-label = Λογαριασμός συνομιλίας
vcard-impp-select = Πρωτόκολλο
vcard-impp-option-other = Άλλο
vcard-impp-input-label = URI
vcard-impp-input-title = URI για ανταλλαγή άμεσων μηνυμάτων
vcard-bday-anniversary-header = Ειδικές ημερομηνίες
vcard-bday-anniversary-add = Προσθήκη ειδικής ημερομηνίας
vcard-bday-label = Γενέθλια
vcard-anniversary-label = Επέτειος
vcard-date-day = Ημέρα
vcard-date-month = Μήνας
vcard-date-year = Έτος
vcard-adr-header = Διευθύνσεις
vcard-adr-add = Προσθήκη διεύθυνσης
vcard-adr-label = Διεύθυνση
vcard-adr-delivery-label = Ετικέτα παράδοσης
vcard-adr-street = Διεύθυνση
# Or "Locality"
vcard-adr-locality = Πόλη
# Or "Region"
vcard-adr-region = Πολιτεία/περιφέρεια
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Ταχυδρομικός κώδικας
vcard-adr-country = Χώρα
vcard-note-header = Σημειώσεις
vcard-note-add = Προσθήκη σημείωσης
vcard-org-header = Ιδιότητες οργανισμού
vcard-org-add = Προσθήκη ιδιοτήτων οργανισμού
vcard-org-title = Τίτλος
vcard-org-title-input =
    .placeholder = Τίτλος εργασίας
    .title = Θέση ή εργασία
vcard-org-role = Ρόλος
vcard-org-role-input =
    .placeholder = Ρόλος σε ένα έργο
    .title = Λειτουργία ή ρόλος σε μια συγκεκριμένη κατάσταση
vcard-org-org = Οργανισμός
vcard-org-org-input =
    .placeholder = Όνομα εταιρείας
    .title = Όνομα οργανισμού
vcard-org-org-unit = Τμήμα
vcard-org-org-unit-input =
    .placeholder = Τμήμα
    .title = Όνομα μονάδας οργανισμού
vcard-custom-header = Προσαρμοσμένες ιδιότητες
vcard-custom-add = Προσθήκη προσαρμοσμένων ιδιοτήτων
vcard-remove-button-title =
    .title = Αφαίρεση
vcard-remove-button = Αφαίρεση
