# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = A' lorg…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 seise air a lorg;#1 sheise air a lorg;#1 seisean air a lorg;#1 seise air a lorg
noMatchesFound = Cha deach seise a lorg
labelForStopButton = Sguir dheth
labelForSearchButton = Lorg
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = L
moreButtonTooltipText = Cuir riaghailt ùr ris
lessButtonTooltipText = Thoir air falbh an riaghailt seo
