# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Levélszemét-beállítások
dialog-header-title =
    .value = Levélszemét-beállítások
training-description-spam = Ha engedélyezi, először be kell tanítania a { -brand-short-name }öt, hogy mely leveleket tartja szemétnek. A Levélszemét eszköztárgomb segítségével mind a szemét, mind a hasznos leveleket azonosítania kell. Ezután a { -brand-short-name } képes lesz a levélszemét automatikus felismerésére.
spam-level-checkbox =
    .label = Adaptív levélszemét-kezelés engedélyezése ehhez a postafiókhoz
    .accesskey = e
move-spam-message-menuitem =
    .label = Új levélszemét áthelyezése:
    .accesskey = h
set-spam-folder-menuitem =
    .label = „Levélszemét” mappa itt:
    .accesskey = L
move-message-other =
    .label = Másik:
    .accesskey = M
automatic-spam-purge-checkbox =
    .label = Ennél régebbi levélszemét automatikus törlése:
    .accesskey = E
automatic-spam-purge-label =
    .value = nap múlva
trust-addresses-header-label =
    .value = Megbízás az ezekben a címjegyzékekben lévő e-mail-címekben:
    .accesskey = b
allowlist-header-label =
    .value = Ne jelölje meg automatikusan levélszemétként az üzenetet, ha a feladója szerepel ebben:
    .accesskey = N
isp-headers-checkbox =
    .label = Megbízás a levélszemétfejlécekben:
    .accesskey = b
isp-warning-description = Ha engedélyezi, a { -brand-short-name } automatikusan levélszemétnek tekinti az ezen külső minősítő által megjelölt üzeneteket.
spam-detecting-legend = Levélszemét észlelése
spam-storage-deletion-legend = Tárolás és törlés
spam-classification-legend = Kijelölés
spam-actions-legend = Cél és megtartás
global-spam-preferences-button =
    .label = Globális levélszemét-beállítások…
    .accesskey = G
manage-spam-title = Levélszemét kezelése
manage-spam-header =
    .value = Levélszemét kezelése
training-description-learns = Ha bekapcsolja, a { -brand-short-name } tanul azokból az üzenetekből, amelyeket Ön levélszemétként (vagy nem akként) jelöl meg. Minél inkább betanítja, a { -brand-short-name } annál jobban észleli a levélszemetet.
spam-auto-detection-checkbox =
    .label = Az automatikus levélszemét-észlelés bekapcsolása ehhez a fiókhoz
    .accesskey = A
