# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Kapcsolat nélküli beállítások
autodetect-connection-label =
    .label = Automatikus módváltás internetkapcsolat észlelésekor
    .accesskey = A
offline-startup-label = A { -brand-short-name } megnyitásakor:
status-radio-last-used =
    .label = Az utoljára használt kapcsolati mód használata
    .accesskey = u
status-radio-start-online =
    .label = Kezdés online
    .accesskey = K
status-radio-start-offline =
    .label = Kapcsolat nélküli indítás
    .accesskey = n
going-online-prompt = Kimenő mappában várakozó üzenetek elküldése
going-online-send =
    .label = Igen, automatikus küldés
    .accesskey = I
going-online-keep =
    .label = Nem, megtartás a Kimenő mappában
    .accesskey = N
going-online-ask-send =
    .label = Rákérdezés küldés előtt
    .accesskey = R
going-offline-prompt = Szeretné letölteni az üzeneteket, hogy kapcsolat nélkül is elolvashassa őket?
going-offline-download =
    .label = Igen, automatikus letöltés
    .accesskey = I
going-offline-keep =
    .label = Nem, ne töltse le
    .accesskey = N
going-offline-ask-download =
    .label = Rákérdezés a letöltés előtt
    .accesskey = R
autodetect-online-label =
    .label = A felismert online állapot követése automatikusan
    .accesskey = f
offline-preference-startup-label = Kézi állapot indításkor:
status-radio-remember =
    .label = Előző online állapot megjegyzése
    .accesskey = E
status-radio-ask =
    .label = Kérdezzen az online állapotról
    .accesskey = o
status-radio-always-online =
    .label = Kapcsolatban
    .accesskey = p
status-radio-always-offline =
    .label = Kapcsolat nélkül
    .accesskey = n
going-online-label = Postázandó üzenetek elküldése a csatlakozáskor
going-online-auto =
    .label = Igen
    .accesskey = I
going-online-not =
    .label = Soha
    .accesskey = S
going-online-ask =
    .label = Kérdés
    .accesskey = K
going-offline-label = Üzenetek letöltése kapcsolat nélküli üzemmódra váltáskor
going-offline-auto =
    .label = Igen
    .accesskey = g
going-offline-not =
    .label = Soha
    .accesskey = o
going-offline-ask =
    .label = Kérdés
    .accesskey = d
