# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Tértivevények
return-receipt-checkbox-control =
    .label = Tértivevény kérése minden elküldött üzenethez
    .accesskey = T
receipt-arrive-label = Tértivevények érkezésekor:
receipt-leave-inbox-control =
    .label = Meghagyás a Beérkezett üzenetek mappában
    .accesskey = M
receipt-move-sent-control =
    .label = Áthelyezés az Elküldött elemek mappába
    .accesskey = h
receipt-sender-request-label = Ha a feladó tértivevényt kér:
receipt-leave-radio-control =
    .label = Megtartás a Beérkezett üzenetek mappában
    .accesskey = M
receipt-move-radio-control =
    .label = Áthelyezés az „Elküldött elemek” mappába
    .accesskey = h
receipt-request-label = Tértivevény küldésére vonatkozó kérés érkezésekor:
receipt-return-never-radio-control =
    .label = Sose küldjön tértivevényt
    .accesskey = S
receipt-return-some-radio-control =
    .label = Tértivevény küldése bizonyos üzeneteknél
    .accesskey = b
receipt-not-listed-cc-label =
    .value = Ha nem szerepel a Címzett vagy a Másolatot kap mezőben:
    .accesskey = C
receipt-not-to-cc-label =
    .value = Ha nem vagyok a címzettek vagy a másolatot kapók között:
    .accesskey = v
receipt-send-never-label =
    .label = Sose küldjön
receipt-send-always-label =
    .label = Mindig küldjön
receipt-send-ask-label =
    .label = Kérdés
sender-outside-company-label =
    .value = Ha a feladó a cégen vagy a tartományon kívül van:
    .accesskey = H
sender-outside-domain-label =
    .value = Ha a feladó a tartományomon kívül van:
    .accesskey = f
other-cases-text-label =
    .value = Minden más esetben:
    .accesskey = e
read-receipts-dialog-title = Olvasási tértivevények
return-receipt-request-control =
    .label = E-mail küldésekor mindig kérjen tértivevényt
    .accesskey = E
