# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Titull:
calendar-item-summary-calendar = Kalendar:
calendar-item-summary-task-start = Datë Fillimi:
calendar-item-summary-event-start = Datë Fillimi:
calendar-item-summary-task-due = Datë Afati:
calendar-item-summary-event-end = Datë Mbarimi:
calendar-item-summary-repeat = Përsëritje:
calendar-item-summary-location = Vendndodhje:
calendar-item-summary-category = Kategori:
calendar-item-summary-organizer = Organizues:
calendar-item-summary-status = Gjendje:
calendar-item-summary-reminder = Kujtues:
calendar-item-summary-attachments = Bashkëngjitje:
calendar-item-summary-status-tentative = Përpjekje
calendar-item-summary-status-confirmed = E konfirmuar
calendar-item-summary-event-status-cancelled = E anuluar
calendar-item-summary-todo-status-cancelled = E anuluar
calendar-item-summary-status-needs-action = Lyp Veprim
calendar-item-summary-status-in-process = Në Proces
calendar-item-summary-status-completed = Plotësuar më
calendar-item-summary-reminder-none =
    .label = Pa kujtues
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minuta para
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minuta para
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minuta para
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minuta para
calendar-item-summary-reminder-1-hour-before =
    .label = 1 orë para
calendar-item-summary-reminder-2-hours-before =
    .label = 2 orë para
calendar-item-summary-reminder-12-hours-before =
    .label = 12 orë para
calendar-item-summary-reminder-1-day-before =
    .label = 1 ditë para
calendar-item-summary-reminder-2-days-before =
    .label = 2 ditë para
calendar-item-summary-reminder-1-week-before =
    .label = 1 javë para
calendar-item-summary-reminder-custom =
    .label = Vetjake…
calendar-item-summary-reminder-multiple =
    .value = Kujtues të Shumëfishtë…
calendar-item-summary-general =
    .value = Të përgjithshme
calendar-item-summary-attendees =
    .value = Pjesëmarrës
calendar-item-summary-description =
    .value = Përshkrim
calendar-item-summary-link =
    .value = Lidhje e Afërt
