# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-deactivated-notification-events = Krejt kalendarët janë hëpërhë të çaktivizuar. Që të krijoni dhe përpunoni akte, aktivizoni një kalendar ekzistues, ose shtoni një të ri.
calendar-deactivated-notification-tasks = Krejt kalendarët janë hëpërhë të çaktivizuar. Që të krijoni dhe përpunoni punë, aktivizoni një kalendar ekzistues, ose shtoni një të ri.
calendar-notifications-label = Shfaq njoftime për veprimtari të ardhshme
calendar-add-notification-button =
    .label = Shtoni njoftim
calendar-import-new-calendar = Kalendar i Ri…
    .title = Krijoni, ose pajtohuni te një kalendar i ri
calendar-refresh-calendars =
    .title = Ringarkoni krejt kalendarët dhe njëkohësoni ndryshimet
calendar-new-event-primary-button = Veprimtari e Re
calendar-new-task-primary-button = Punë e Re
calendar-nav-button-prev-tooltip-day =
    .title = Dita e Mëparshme
    .accesskey = s
calendar-nav-button-prev-tooltip-week =
    .title = Java e Mëparshme
    .accesskey = s
calendar-nav-button-prev-tooltip-multiweek =
    .title = Java e Mëparshme
    .accesskey = s
calendar-nav-button-prev-tooltip-month =
    .title = Muaji i Mëparshëm
    .accesskey = s
calendar-nav-button-next-tooltip-day =
    .title = Dita Pasuese
    .accesskey = u
calendar-nav-button-next-tooltip-week =
    .title = Java Pasuese
    .accesskey = u
calendar-nav-button-next-tooltip-multiweek =
    .title = Java Pasuese
    .accesskey = u
calendar-nav-button-next-tooltip-month =
    .title = Muaji Pasues
    .accesskey = u
calendar-today-button-tooltip =
    .title = Shko te Sot
calendar-view-toggle-day = Ditë
    .title = Kaloni te pamje dite
calendar-view-toggle-week = Javë
    .title = Kaloni te pamje jave
calendar-view-toggle-multiweek = Shumëjavësh
    .title = Kaloni te pamje shumëjavëshe
calendar-view-toggle-month = Muaj
    .title = Kaloni te pamje muaji
