# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Përzgjidhe krejt
select-none-calendars = Mos përzgjidh gjë
calendar-creation-wizard-title = Krijoni Kalendar të Ri
calendar-creation-initial-description = Kalendari juaj mund të depozitohet te kompjuteri juaj, ose te një shërbyes që të mund ta përdorni së largëti ose ta ndani me shokë apo kolegë tuajt.
calendar-creation-initial-computer =
    .label = Në Kompjuterin Tim
calendar-creation-initial-network =
    .label = Në Rrjet
calendar-creation-username =
    .value = Emër përdoruesi:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Krijoje Kalendarin
    .buttonaccesskeyaccept = K
    .buttonlabelextra2 = Mbrapsht
    .buttonaccesskeyextra2 = b
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Krijoje Kalendarin
    .buttonaccesskeyaccept = K
    .buttonlabelextra2 = Mbrapsht
    .buttonaccesskeyextra2 = b
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Gjej Kalendarë
    .buttonaccesskeyaccept = G
    .buttonlabelextra2 = Mbrapsht
    .buttonaccesskeyextra2 = b
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Pajtohuni
    .buttonaccesskeyaccept = P
    .buttonlabelextra2 = Mbrapsht
    .buttonaccesskeyextra2 = b
calendar-creation-type =
    .value = Lloj Kalendari:
calendar-creation-location =
    .value = Vendndodhje:
calendar-creation-location-placeholder =
    .placeholder = URL, ose emër strehe e shërbyesit të kalendarit
    .default-placeholder = URL, ose emër strehe e shërbyesit të kalendarit
calendar-creation-network-nocredentials =
    .label = Kjo vendndodhje nuk lyp kredenciale
calendar-creation-network-loading = Ju lutemi, prisni teksa zbulohen kalendarët tuaj.
calendar-creation-network-notfound = S’u gjetën kalendarë në këtë vendndodhje. Ju lutemi, kontrolloni rregullimet tuaja.
calendar-creation-network-authfail = Kredencialet që keni dhënë nuk u pranuan. Ju lutemi, kontrolloni rregullimet tuaja.
calendar-creation-network-certerror = S’u gjetën dot kalendarë te kjo vendndodhje, për shkak të një problemi dëshmie.
calendar-creation-network-subscribe-single = Ju lutemi, përzgjidhni kalendarët te të cilët do të donit të pajtoheshit.
calendar-creation-network-subscribe-multiple = Ka disa lloje kalendarësh të gatshëm për këtë vend. Ju lutemi, përzgjidhni llojin e kalendarit, mandej vëruni shenjë kalendarëve te të cilët do të donit të pajtoheshit.
