# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = רווח גמיש
toolbar-write-message-label = כתיבה
toolbar-write-message =
    .title = צור הודעה חדשה
toolbar-unifinder-label = מצא אירועים
toolbar-unifinder =
    .title = החלפת מצב חלונית חיפוש אירועים
toolbar-folder-location-label = מיקום תיקייה
toolbar-edit-event-label = עריכה
toolbar-edit-event =
    .title = עריכת האירוע או המשימה הנבחר
toolbar-get-messages-label = קבלת הודעות
toolbar-reply-label = השב
toolbar-reply =
    .title = השב להודעה
toolbar-reply-all-label = השב לכולם
toolbar-reply-all =
    .title = השב לשולח ולכל הנמענים
toolbar-reply-to-list-label = השב לרשימה
toolbar-reply-to-list =
    .title = השב לרשימת תפוצה
toolbar-archive-label = העבר לארכיון
toolbar-archive =
    .title = העברה לארכיון של ההודעות הנבחרות
toolbar-conversation-label = שיחה
toolbar-previous-unread-label = הקודמת שלא נקראה
toolbar-previous-unread =
    .title = עבור אל ההודעה הקודמת שלא נקראה
toolbar-previous-label = קודם
toolbar-previous =
    .title = מעבר להודעה הקודמת
toolbar-next-unread-label = הבאה שלא נקראה
toolbar-next-unread =
    .title = עבור להודעה הבאה שלא נקראה
toolbar-next-label = הבאה
toolbar-next =
    .title = מעבר להודעה הבאה
toolbar-junk-label = זבל
toolbar-junk =
    .title = סימון ההודעות המסומנות כזבל
toolbar-delete-label = מחיקה
toolbar-delete =
    .title = מחיקת ההודעות או תיקייה המסומנים
toolbar-compact-label = כווץ
toolbar-compact =
    .title = הסר הודעות שנמחקו מתיקייה מסומנת
toolbar-add-as-event-label = הוספה כאירוע
toolbar-add-as-event =
    .title = חילוץ פרטי הצעת פגישה מההודעה והוספה ללוח השנה שלך כאירוע
toolbar-add-as-task-label = הוספה כמשימה
toolbar-add-as-task =
    .title = חילוץ פרטי הצעת פגישה מההודעה והוספה ללוח השנה שלך כמשימה
toolbar-tag-message-label = תווית
toolbar-tag-message =
    .title = סמן הודעות בתוויות
toolbar-forward-inline-label = העבר
toolbar-forward-inline =
    .title = העברת ההודעה הנבחרת בתוך גוף הודעה
toolbar-forward-attachment-label = העברה כקובץ מצורף
toolbar-forward-attachment =
    .title = העברת ההודעה הנבחרת כקובץ מצורף
toolbar-mark-as-label = סמן
toolbar-mark-as =
    .title = סמן הודעות
toolbar-address-book =
    .title = עבור לפנקס כתובות
toolbar-chat-label = צ׳אט
toolbar-chat =
    .title = הצגת לשונית הצ׳אט
toolbar-add-ons-and-themes-label = תוספות וערכות נושא
toolbar-add-ons-and-themes =
    .title = ניהול התוספות שלך
toolbar-calendar-label = לוח שנה
toolbar-calendar =
    .title = מעבר ללשונית לוח השנה
toolbar-tasks-label = משימות
toolbar-tasks =
    .title = מעבר ללשונית משימות
toolbar-print-label = הדפסה
toolbar-print =
    .title = הדפס הודעה זו
toolbar-quick-filter-bar-label = סינון מהיר
toolbar-quick-filter-bar =
    .title = סינון הודעות
toolbar-synchronize-label = סנכרון
toolbar-synchronize =
    .title = רענון היומנים וסנכרון השינויים
toolbar-delete-event-label = מחיקה
toolbar-delete-event =
    .title = מחיקת האירועים או המשימות הנבחרים
toolbar-go-to-today-label = מעבר להיום
toolbar-go-to-today =
    .title = מעבר להיום
toolbar-print-event-label = הדפסה
toolbar-print-event =
    .title = הדפסת אירועים או משימות
toolbar-new-event-label = אירוע
toolbar-new-event =
    .title = יצירת אירוע חדש
toolbar-new-task-label = משימה
toolbar-new-task =
    .title = יצירת משימה חדשה
toolbar-go-back-label = אחורה
toolbar-go-back =
    .title = עבור אחורה הודעה אחת
toolbar-go-forward-label = קדימה
toolbar-go-forward =
    .title = עבור קדימה הודעה אחת
toolbar-stop-label = עצור
toolbar-stop =
    .title = הפסק העברה נוכחית
toolbar-throbber-label = מחוון פעילות
toolbar-throbber =
    .title = מחוון פעילות
