# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

select-all-calendars = Izberi vse
select-none-calendars = Ne izberi ničesar
calendar-creation-wizard-title = Ustvari nov koledar
calendar-creation-initial-description = Koledar je lahko shranjen na vašem računalniku ali na strežniku, kar omogoča oddaljen dostop in deljenje s prijatelji ali sodelavci.
calendar-creation-initial-computer =
    .label = Na računalniku
calendar-creation-initial-network =
    .label = V omrežju
calendar-creation-username =
    .value = Uporabniško ime:
calendar-creation-panel-local-settings =
    .buttonlabelaccept = Ustvari koledar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Nazaj
    .buttonaccesskeyextra2 = N
calendar-creation-panel-addon-settings =
    .buttonlabelaccept = Ustvari koledar
    .buttonaccesskeyaccept = r
    .buttonlabelextra2 = Nazaj
    .buttonaccesskeyextra2 = N
calendar-creation-panel-network-settings =
    .buttonlabelaccept = Poišči koledarje
    .buttonaccesskeyaccept = i
    .buttonlabelextra2 = Nazaj
    .buttonaccesskeyextra2 = N
calendar-creation-panel-select-calendars =
    .buttonlabelaccept = Naroči se
    .buttonaccesskeyaccept = s
    .buttonlabelextra2 = Nazaj
    .buttonaccesskeyextra2 = N
calendar-creation-type =
    .value = Vrsta koledarja:
calendar-creation-location =
    .value = Mesto:
calendar-creation-location-placeholder =
    .placeholder = Spletni naslov ali ime gostitelja strežnika koledarja
    .default-placeholder = Spletni naslov ali ime gostitelja strežnika koledarja
calendar-creation-network-nocredentials =
    .label = To mesto ne zahteva poverilnic
calendar-creation-network-loading = Počakajte, medtem ko se vaši koledarji odkrivajo.
calendar-creation-network-notfound = Na tem mestu ni bilo mogoče najti koledarjev. Preverite svoje nastavitve.
calendar-creation-network-authfail = Poverilnice, ki ste jih vnesli, niso bile sprejete. Preverite svoje nastavitve.
calendar-creation-network-certerror = Na tem mestu ni bilo mogoče najti koledarjev zaradi težave z digitalnim potrdilom.
calendar-creation-network-subscribe-single = Izberite koledarje, na katere se želite naročiti.
calendar-creation-network-subscribe-multiple = Za to mesto je na voljo več vrst koledarjev. Izberite vrsto koledarja in nato označite koledarje, na katere se želite naročiti.
