# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Komentar
calendar-item-summary-title = Naziv:
calendar-item-summary-calendar = Koledar:
calendar-item-summary-task-start = Začetni datum:
calendar-item-summary-event-start = Začetni datum:
calendar-item-summary-task-due = Rok:
calendar-item-summary-event-end = Končni datum:
calendar-item-summary-repeat = Ponovitev:
calendar-item-summary-location = Kraj:
calendar-item-summary-category = Kategorija:
calendar-item-summary-organizer = Organizator:
calendar-item-summary-status = Stanje:
calendar-item-summary-reminder = Opomnik:
calendar-item-summary-attachments = Priponke:
calendar-item-summary-status-tentative = Predviden
calendar-item-summary-status-confirmed = Potrjen
calendar-item-summary-event-status-cancelled = Odpovedan
calendar-item-summary-todo-status-cancelled = Preklican
calendar-item-summary-status-needs-action = potrebuje poseg
calendar-item-summary-status-in-process = V teku
calendar-item-summary-status-completed = Dokončan
calendar-item-summary-reminder-none =
    .label = Brez opomnika
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 minut prej
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minut prej
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minut prej
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minut prej
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ura prej
calendar-item-summary-reminder-2-hours-before =
    .label = 2 uri prej
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ur prej
calendar-item-summary-reminder-1-day-before =
    .label = 1 dan prej
calendar-item-summary-reminder-2-days-before =
    .label = 2 dni prej
calendar-item-summary-reminder-1-week-before =
    .label = 1 teden prej
calendar-item-summary-reminder-custom =
    .label = Po meri …
calendar-item-summary-reminder-multiple =
    .value = Več opomnikov …
calendar-item-summary-general =
    .value = Splošno
calendar-item-summary-attendees =
    .value = Udeleženci
calendar-item-summary-description =
    .value = Opis
calendar-item-summary-link =
    .value = Sorodna povezava
