# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Yorum
calendar-item-summary-title = Başlık:
calendar-item-summary-calendar = Takvim:
calendar-item-summary-task-start = Başlangıç tarihi:
calendar-item-summary-event-start = Başlangıç tarihi:
calendar-item-summary-task-due = Bitiş tarihi:
calendar-item-summary-event-end = Bitiş tarihi:
calendar-item-summary-repeat = Tekrarla:
calendar-item-summary-location = Konum:
calendar-item-summary-category = Kategori:
calendar-item-summary-organizer = Düzenleyen:
calendar-item-summary-status = Durum:
calendar-item-summary-reminder = Anımsatıcı:
calendar-item-summary-attachments = Ekler:
calendar-item-summary-reminder-none =
    .label = Anımsatıcı yok
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 dakika önce
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 dakika önce
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 dakika önce
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 dakika önce
calendar-item-summary-reminder-1-hour-before =
    .label = 1 saat önce
calendar-item-summary-reminder-2-hours-before =
    .label = 2 saat önce
calendar-item-summary-reminder-12-hours-before =
    .label = 12 saat önce
calendar-item-summary-reminder-1-day-before =
    .label = 1 gün önce
calendar-item-summary-reminder-2-days-before =
    .label = 2 gün önce
calendar-item-summary-reminder-1-week-before =
    .label = 1 hafta önce
calendar-item-summary-reminder-custom =
    .label = Özelleştir…
calendar-item-summary-reminder-multiple =
    .value = Çoklu anımsatıcı…
calendar-item-summary-general =
    .value = Genel
calendar-item-summary-attendees =
    .value = Katılımcılar
calendar-item-summary-description =
    .value = Açıklama
calendar-item-summary-link =
    .value = İlgili bağlantı
