# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Visningsnavn
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Type
vcard-entry-type-home = Hjem
vcard-entry-type-work = Arbejde
vcard-entry-type-none = Ingen
vcard-entry-type-custom = Brugerdefineret
vcard-name-header = Navn
vcard-n-prefix = Præfiks
vcard-n-add-prefix =
    .title = Tilføj præfiks
vcard-n-firstname = Fornavn
vcard-n-add-firstname =
    .title = Tilføj fornavn
vcard-n-middlename = Mellemnavn
vcard-n-add-middlename =
    .title = Tilføj mellemnavn
vcard-n-lastname = Efternavn
vcard-n-add-lastname =
    .title = Tilføj efternavn
vcard-n-suffix = Suffiks
vcard-n-add-suffix =
    .title = Tilføj suffiks
vcard-nickname = Alias
vcard-email-header = Mailadresser
vcard-email-add = Tilføj mailadresse
vcard-email-label = Mailadresse
vcard-primary-email-label = Standard
vcard-url-header = Websteder
vcard-url-add = Tilføj websted
vcard-url-label = Websted
vcard-tel-header = Telefonnumre
vcard-tel-add = Tilføj telefonnummer
vcard-tel-label = Telefonnummer
# Or "Mobile"
vcard-entry-type-cell = Mobil
vcard-entry-type-fax = Fax
vcard-entry-type-pager = Personsøger
vcard-tz-header = Tidszone
vcard-tz-add = Tilføj tidszone
vcard-impp2-header = Chat
vcard-impp-add = Tilføj chat-konto
vcard-impp-label = Chat-konto
vcard-impp-select = Protokol
vcard-impp-option-other = Andet
vcard-impp-input-label = URI
vcard-impp-input-title = Chat-URI
vcard-bday-anniversary-header = Særlige datoer
vcard-bday-anniversary-add = Tilføj særlig dato
vcard-bday-label = Fødselsdag
vcard-anniversary-label = Jubilæum
vcard-date-day = Dag
vcard-date-month = Måned
vcard-date-year = År
vcard-adr-header = Adresser
vcard-adr-add = Tilføj adresse
vcard-adr-label = Adresse
vcard-adr-delivery-label = Leveringsetiket
vcard-adr-street = Postadresse
# Or "Locality"
vcard-adr-locality = By
# Or "Region"
vcard-adr-region = Stat/provins
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Postnummer
vcard-adr-country = Land
vcard-note-header = Noter
vcard-note-add = Tilføj note
vcard-org-header = Organisatoriske egenskaber
vcard-org-add = Tilføj organisatoriske egenskaber
vcard-org-title = Titel
vcard-org-title-input =
    .placeholder = Stillingsbetegnelse
    .title = Stilling eller job
vcard-org-role = Rolle
vcard-org-role-input =
    .placeholder = Rolle i et projekt
    .title = Funktion eller rolle i en given situation
vcard-org-org = Organisation
vcard-org-org-input =
    .placeholder = Virksomhedsnavn
    .title = Organisationsnavn
vcard-org-org-unit = Afdeling
vcard-org-org-unit-input =
    .placeholder = Afdeling
    .title = Organisationsafdelingsnavn
vcard-custom-header = Tilpassede egenskaber
vcard-custom-add = Tilføj tilpassede egenskaber
vcard-remove-button-title =
    .title = Fjern
vcard-remove-button = Fjern
