# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Fleksibilni razmak
search-bar-label = Traži
toolbar-write-message-label = Piši
toolbar-write-message =
    .title = Stvori novu poruku
toolbar-move-to-label = Premjesti u
toolbar-move-to =
    .title = Premjesti odabranu poruku
toolbar-unifinder-label = Pronađi događaje
toolbar-unifinder =
    .title = Uključi/isključi okno za traženje događaja
toolbar-folder-location-label = Lokacija mape
toolbar-folder-location =
    .title = Prijeđi na mapu
toolbar-edit-event-label = Uredi
toolbar-edit-event =
    .title = Uredi odabrani događaj ili zadatak
toolbar-get-messages-label = Dohvati poruke
toolbar-get-messages =
    .title = Dohvati nove poruke za sve račune
toolbar-reply-label = Odgovori
toolbar-reply =
    .title = Odgovori na poruku
toolbar-reply-all-label = Odgovori svima
toolbar-reply-all =
    .title = Odgovori pošiljatelju i svim primateljima
toolbar-reply-to-list-label = Odgovori na listu
toolbar-reply-to-list =
    .title = Odgovori na popis primatelja
toolbar-redirect-label = Preusmjeri
toolbar-redirect =
    .title = Preusmjeri odabrane poruke
toolbar-archive-label = Arhiviraj
toolbar-archive =
    .title = Arhiviraj odabrane poruke
toolbar-conversation-label = Razgovor
toolbar-conversation =
    .title = Prikaži razgovor odabrane poruke
toolbar-previous-unread-label = Prethodni nepročitani
toolbar-previous-unread =
    .title = Idi na prethodnu nepročitanu poruku
toolbar-previous-label = Prethodni
toolbar-previous =
    .title = Idi na prethodnu poruku
toolbar-next-unread-label = Sljedeći nepročitani
toolbar-next-unread =
    .title = Idi na sljedeću nepročitanu poruku
toolbar-next-label = Sljedeći
toolbar-next =
    .title = Idi na sljedeću poruku
toolbar-junk-label = Neželjena pošta
toolbar-junk =
    .title = Označi odabrane poruke kao neželjene
toolbar-delete-label = Obriši
toolbar-delete-title =
    .title = Obriši odabrane poruke
toolbar-undelete-label = Vrati obrisano
toolbar-undelete =
    .title = Vrati odabrane poruke
toolbar-compact-label = Sažmi
toolbar-compact =
    .title = Ukloni obrisane poruke iz odabrane mape
toolbar-add-as-event-label = Dodaj kao događaj
toolbar-add-as-event =
    .title = Izvezite kalendarske informacije iz poruke i dodajte ih u svoj kalendar kao događaj
toolbar-add-as-task-label = Dodaj kao zadatak
toolbar-add-as-task =
    .title = Izvezite kalendarske informacije iz poruke i dodajte ih u svoj kalendar kao zadatak
toolbar-tag-message-label = Oznaka
toolbar-tag-message =
    .title = Označi poruke
toolbar-forward-inline-label = Proslijedi
toolbar-forward-inline =
    .title = Proslijedi odabranu poruku kao ugrađeni tekst
toolbar-forward-attachment-label = Proslijedi kao privitak
toolbar-forward-attachment =
    .title = Proslijedite odabranu poruku kao privitak
toolbar-mark-as-label = Označi
toolbar-mark-as =
    .title = Označi poruke
toolbar-view-picker-label = Prikaži
toolbar-view-picker =
    .title = Prilagodi prikaz trenutne mape
toolbar-address-book-label = Adresar
toolbar-address-book =
    .title = Idi u adresar
toolbar-chat-label = Razgovor
toolbar-chat =
    .title = Prikaži karticu razgovora
toolbar-add-ons-and-themes-label = Dodaci i teme
toolbar-add-ons-and-themes =
    .title = Upravljajte svojim dodacima
toolbar-calendar-label = Kalendar
toolbar-calendar =
    .title = Prebaci na karticu kalendara
toolbar-tasks-label = Zadaci
toolbar-tasks =
    .title = Prebaci na karticu zadataka
toolbar-mail-label = E-pošta
toolbar-mail =
    .title = Prebaci na karticu poruka
toolbar-print-label = Ispis
toolbar-print =
    .title = Ispiši ovu poruku
toolbar-quick-filter-bar-label = Brzo filtriranje
toolbar-quick-filter-bar =
    .title = Filtriranje poruka
toolbar-synchronize-label = Sinkroniziraj
toolbar-synchronize =
    .title = Ponovno učitaj kalendare i sinkroniziraj promjene
toolbar-delete-event-label = Obriši
toolbar-delete-event =
    .title = Obriši odabrane događaje ili zadatke
toolbar-go-to-today-label = Idi na danas
toolbar-go-to-today =
    .title = Idi na danas
toolbar-print-event-label = Ispis
toolbar-print-event =
    .title = Ispiši događaje ili zadatke
toolbar-new-event-label = Događaj
toolbar-new-event =
    .title = Stvori novi događaj
toolbar-new-task-label = Zadatak
toolbar-new-task =
    .title = Stvori novi zadatak
toolbar-go-back-label = Natrag
toolbar-go-back =
    .title = Idi natrag jednu poruku
toolbar-go-forward-label = Naprijed
toolbar-go-forward =
    .title = Idi naprijed jednu poruku
toolbar-stop-label = Stani
toolbar-stop =
    .title = Zaustavi trenutni prijenos
toolbar-throbber-label = Indikator aktivnosti
toolbar-throbber =
    .title = Indikator aktivnosti
toolbar-create-contact-label = Novi kontakt
toolbar-create-contact =
    .title = Stvori novi kontakt
toolbar-create-address-book-label = Novi adresar
toolbar-create-address-book =
    .title = Stvori novi adresar
toolbar-create-list-label = Novi popis
toolbar-create-list =
    .title = Stvori novi popis primatelja
toolbar-import-contacts-label = Uvoz
toolbar-import-contacts =
    .title = Uvezi kontakte iz datoteke

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Dodaj lokalni adresar
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Dodaj CardDAV adresar
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Dodaj LDAP adresar
