# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Որոնում…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Գտնուել է #1 հանդիպում; գտնուել է #1 հանդիպում
noMatchesFound = Ոչինչ չի գտնուել
labelForStopButton = Դադարեցրեք
labelForSearchButton = Որոնել
labelForStopButton.accesskey = Ո
labelForSearchButton.accesskey = Ո
moreButtonTooltipText = Աւելացնել նոր կանոն
lessButtonTooltipText = Հեռացնել այս կանոնը
