# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Impostazioni spam
dialog-header-title =
    .value = Impostazioni spam
training-description-spam = Se attivata, è necessario addestrare { -brand-short-name } a identificare lo spam utilizzando il pulsante Spam nella barra degli strumenti per contrassegnare i messaggi come spam o meno. È necessario identificare sia i messaggi spam che quelli non spam. Dopodiché { -brand-short-name } sarà in grado di contrassegnare automaticamente lo spam.
spam-level-checkbox =
    .label = Attiva controlli antispam incrementali per questo account
    .accesskey = A
move-spam-message-menuitem =
    .label = Sposta i nuovi messaggi di spam in:
    .accesskey = S
set-spam-folder-menuitem =
    .label = Cartella “Spam” su:
    .accesskey = C
move-message-other =
    .label = Altra:
    .accesskey = r
automatic-spam-purge-checkbox =
    .label = Elimina automaticamente lo spam dopo
    .accesskey = E
automatic-spam-purge-label =
    .value = giorni
trust-addresses-header-label =
    .value = Non contrassegnare come spam gli indirizzi email presenti in queste rubriche:
    .accesskey = N
allowlist-header-label =
    .value = Non contrassegnare automaticamente la posta come spam se il mittente si trova in:
    .accesskey = N
isp-headers-checkbox =
    .label = Considera attendibili le intestazioni di spam impostate da:
    .accesskey = C
isp-warning-description = Se attivato { -brand-short-name } considererà automaticamente spam i messaggi contrassegnati da questo classificatore esterno.
spam-detecting-legend = Rilevamento spam
spam-storage-deletion-legend = Archiviazione ed eliminazione
spam-classification-legend = Selezione
spam-actions-legend = Destinazione e memorizzazione
global-spam-preferences-button =
    .label = Impostazioni antispam globali…
    .accesskey = I
manage-spam-title = Gestione dello spam
manage-spam-header =
    .value = Gestione dello spam
training-description-learns = Quando l’opzione è attivata, { -brand-short-name } apprende dai messaggi che contrassegni come spam o meno. Più { -brand-short-name } viene addestrata, migliore diventerà nel rilevamento dello spam.
spam-auto-detection-checkbox =
    .label = Attiva il rilevamento automatico dello spam per questo account
    .accesskey = A
