# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Impostazioni non in linea
autodetect-connection-label =
    .label = Cambia automaticamente modalità quando viene rilevata una connessione a Internet
    .accesskey = C
offline-startup-label = All’apertura di { -brand-short-name }:
status-radio-last-used =
    .label = Utilizza l’ultima modalità di connessione utilizzata
    .accesskey = m
status-radio-ask-connect =
    .label = Chiedi se collegarti a Internet
    .accesskey = C
status-radio-start-online =
    .label = Avvia con connessione attiva
    .accesskey = A
status-radio-start-offline =
    .label = Avvia non in linea
    .accesskey = n
going-online-prompt = Invia messaggi in attesa nella Posta in uscita
going-online-send =
    .label = Sì, invia automaticamente
    .accesskey = S
going-online-keep =
    .label = No, mantieni in Posta in uscita
    .accesskey = N
going-online-ask-send =
    .label = Chiedi prima di inviare
    .accesskey = C
going-offline-prompt = Scaricare i messaggi per leggerli non in linea?
going-offline-download =
    .label = Sì, scarica automaticamente
    .accesskey = a
going-offline-keep =
    .label = No, non scaricare
    .accesskey = N
going-offline-ask-download =
    .label = Chiedi prima di scaricare
    .accesskey = m
autodetect-online-label =
    .label = Passa automaticamente alla modalità in linea
    .accesskey = S
offline-preference-startup-label = Impostazione manuale all’avvio:
status-radio-remember =
    .label = Ricordarsi del precedente stato in linea
    .accesskey = R
status-radio-ask =
    .label = Chiedi per passare alla modalità in linea
    .accesskey = C
status-radio-always-online =
    .label = In linea
    .accesskey = l
status-radio-always-offline =
    .label = Non in linea
    .accesskey = N
going-online-label = Inviare i messaggi in attesa subito dopo essersi collegati?
going-online-auto =
    .label = Si
    .accesskey = S
going-online-not =
    .label = No
    .accesskey = N
going-online-ask =
    .label = Chiedi
    .accesskey = c
going-offline-label = Scaricare i messaggi per l’utilizzo non in linea quando ci si scollega?
going-offline-auto =
    .label = Si
    .accesskey = i
going-offline-not =
    .label = No
    .accesskey = o
going-offline-ask =
    .label = Chiedi
    .accesskey = h
