# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Pengaturan Spam
dialog-header-title =
    .value = Pengaturan Spam
training-description-spam = Jika diaktifkan, Anda harus terlebih dahulu melatih { -brand-short-name } untuk mengidentifikasi spam dengan menggunakan tombol bilah alat Spam untuk menandai pesan sebagai spam atau tidak. Anda perlu mengidentifikasi pesan spam dan non-spam. Setelah itu { -brand-short-name } akan dapat menandai spam secara otomatis.
spam-level-checkbox =
    .label = Fungsikan kontrol spam adaptif untuk akun ini
    .accesskey = F
move-spam-message-menuitem =
    .label = Pindahkan pesan spam baru ke:
    .accesskey = m
set-spam-folder-menuitem =
    .label = Folder “Spam” di:
    .accesskey = S
move-message-other =
    .label = Lainnya:
    .accesskey = L
automatic-spam-purge-checkbox =
    .label = Otomatis hapus spam yang lebih lama dari
    .accesskey = u
automatic-spam-purge-label =
    .value = hari
trust-addresses-header-label =
    .value = Percayai alamat surel dalam buku alamat berikut:
    .accesskey = d
allowlist-header-label =
    .value = Jangan tandai surel sebagai spam secara otomatis jika pengirim berada di:
    .accesskey = d
isp-headers-checkbox =
    .label = Percayai header spam yang disetel oleh:
    .accesskey = t
isp-warning-description = Jika diaktifkan, { -brand-short-name } akan secara otomatis menganggap pesan yang ditandai oleh pengklasifikasi eksternal ini sebagai spam.
spam-detecting-legend = Mendeteksi spam
spam-storage-deletion-legend = Penyimpanan dan penghapusan
spam-classification-legend = Pilihan
spam-actions-legend = Tujuan dan Retensi
global-spam-preferences-button =
    .label = Pengaturan Spam Global…
    .accesskey = G
manage-spam-title = Kelola spam
manage-spam-header =
    .value = Kelola spam
training-description-learns = Saat diaktifkan, { -brand-short-name } belajar dari pesan yang Anda tandai sebagai spam atau bukan spam. Semakin Anda melatihnya, semakin baik { -brand-short-name } dalam mendeteksi spam.
spam-auto-detection-checkbox =
    .label = Aktifkan deteksi spam otomatis untuk akun ini
    .accesskey = e
