# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Pengaturan Luring
status-radio-start-online =
    .label = Mulai daring
    .accesskey = l
status-radio-start-offline =
    .label = Mulai luring
    .accesskey = g
going-online-prompt = Kirim pesan yang menunggu di Kotak Keluar Anda
going-online-send =
    .label = Ya, kirim secara otomatis
    .accesskey = Y
going-online-keep =
    .label = Tidak, simpan di Kotak Keluar
    .accesskey = n
going-online-ask-send =
    .label = Tanyakan sebelum mengirim
    .accesskey = s
going-offline-prompt = Ingin mengunduh pesan untuk dibaca secara luring?
going-offline-download =
    .label = Ya, unduh secara otomatis
    .accesskey = e
going-offline-keep =
    .label = Tidak, jangan unduh
    .accesskey = a
autodetect-online-label =
    .label = Secara otomatis mengikuti keadaan daring yang terdeteksi
    .accesskey = d
offline-preference-startup-label = Keadaan manual saat memulai:
status-radio-remember =
    .label = Ingat Status Mode Daring Sebelumnya
    .accesskey = I
status-radio-ask =
    .label = Tanya saya untuk keadaan daring
    .accesskey = k
status-radio-always-online =
    .label = Selalu mulai dalam mode daring
    .accesskey = l
status-radio-always-offline =
    .label = Luring
    .accesskey = f
going-online-label = Kirim pesan belum terkirim saat mulai mode daring?
going-online-auto =
    .label = Ya
    .accesskey = Y
going-online-not =
    .label = Tidak
    .accesskey = T
going-online-ask =
    .label = Tanyakan saya
    .accesskey = s
going-offline-label = Unduh pesan untuk penggunaan luring saat akan pindah ke mode luring?
going-offline-auto =
    .label = Ya
    .accesskey = Y
going-offline-not =
    .label = Tidak
    .accesskey = T
going-offline-ask =
    .label = Tanyakan saya
    .accesskey = a
