# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Flexibler Zwischenraum
search-bar-label = Suchen
toolbar-write-message-label = Verfassen
toolbar-write-message =
    .title = Eine neue Nachricht schreiben
toolbar-move-to-label = Verschieben nach
toolbar-move-to =
    .title = Markierte Nachricht verschieben
toolbar-unifinder-label = Termine suchen
toolbar-unifinder =
    .title = Terminsuche anzeigen/ausblenden
toolbar-folder-location-label = Ordner wechseln
toolbar-folder-location =
    .title = Zu Ordner wechseln
toolbar-edit-event-label = Bearbeiten
toolbar-edit-event =
    .title = Ausgewählte(n) Termin oder Aufgabe bearbeiten
toolbar-get-messages-label = Abrufen
toolbar-get-messages =
    .title = Neue Nachrichten für alle Konten abrufen
toolbar-reply-label = Antworten
toolbar-reply =
    .title = Auf gewählte Nachricht(en) antworten
toolbar-reply-all-label = Allen antworten
toolbar-reply-all =
    .title = Auf gewählte Nachricht(en) an den Absender und alle Empfänger antworten
toolbar-reply-to-list-label = Liste antworten
toolbar-reply-to-list =
    .title = Auf gewählte Nachricht(en) an Liste antworten
toolbar-redirect-label = Umleiten
toolbar-redirect =
    .title = Umleiten der ausgewählten Nachricht
toolbar-archive-label = Archivieren
toolbar-archive =
    .title = Gewählte Nachricht(en) archivieren
toolbar-conversation-label = Themenbaum
toolbar-conversation =
    .title = Themenbaum für ausgewählte Nachrichten anzeigen
toolbar-previous-unread-label = Vorherige ungelesene
toolbar-previous-unread =
    .title = Gehe zur vorherigen ungelesenen Nachricht
toolbar-previous-label = Vorherige
toolbar-previous =
    .title = Gehe zur vorherigen Nachricht
toolbar-next-unread-label = Nächste ungelesene
toolbar-next-unread =
    .title = Gehe zur nächsten ungelesenen Nachricht
toolbar-next-label = Nächste
toolbar-next =
    .title = Gehe zur nächsten Nachricht
toolbar-junk-label = Junk
toolbar-junk =
    .title = Gewählte Nachricht(en) als Junk einstufen
toolbar-delete-label = Löschen
toolbar-delete-title =
    .title = Ausgewählte Nachrichten löschen
toolbar-undelete-label = Wiederherstellen
toolbar-undelete =
    .title = Ausgewählte Nachrichten wiederherstellen
toolbar-compact-label = Komprimieren
toolbar-compact =
    .title = Gelöschte Nachrichten endgültig aus dem gewählten Ordner entfernen
toolbar-add-as-event-label = Als Termin eintragen
toolbar-add-as-event =
    .title = Kalenderinformationen aus der Nachricht auslesen und als Termin zum Kalender hinzufügen
toolbar-add-as-task-label = Als Aufgabe eintragen
toolbar-add-as-task =
    .title = Kalenderinformationen aus der Nachricht auslesen und als Aufgabe zum Kalender hinzufügen
toolbar-tag-message-label = Schlagwörter
toolbar-tag-message =
    .title = Bei gewählten Nachrichten Schlagwörter hinzufügen/entfernen
toolbar-forward-inline-label = Weiterleiten
toolbar-forward-inline =
    .title = Ausgewählte Nachricht als eingebundenen Text weiterleiten
toolbar-forward-attachment-label = Als Anhang
toolbar-forward-attachment =
    .title = Ausgewählte Nachricht als Anhang weiterleiten
toolbar-mark-as-label = Markieren
toolbar-mark-as =
    .title = Gewählte Nachricht(en) markieren
toolbar-view-picker-label = Ansehen
toolbar-view-picker =
    .title = Ansicht des aktuellen Ordners anpassen
toolbar-address-book-label = Adressbuch
toolbar-address-book =
    .title = Adressbuch öffnen
toolbar-chat-label = Chat
toolbar-chat =
    .title = Chat-Tab öffnen
toolbar-add-ons-and-themes-label = Add-ons und Themes
toolbar-add-ons-and-themes =
    .title = Add-ons verwalten
toolbar-calendar-label = Kalender
toolbar-calendar =
    .title = Zum Kalender-Tab wechseln
toolbar-tasks-label = Aufgaben
toolbar-tasks =
    .title = Zum Aufgaben-Tab wechseln
toolbar-mail-label = E-Mail
toolbar-mail =
    .title = Zur E-Mail-Tab wechseln
toolbar-print-label = Drucken
toolbar-print =
    .title = Gewählte Nachricht(en) drucken
toolbar-quick-filter-bar-label = Schnellfilter
toolbar-quick-filter-bar =
    .title = Nachrichten filtern
toolbar-synchronize-label = Synchronisieren
toolbar-synchronize =
    .title = Kalender neu laden und Änderungen synchronisieren
toolbar-delete-event-label = Löschen
toolbar-delete-event =
    .title = Ausgewählte Termine oder Aufgaben löschen
toolbar-go-to-today-label = Heute
toolbar-go-to-today =
    .title = Zu Heute wechseln
toolbar-print-event-label = Drucken
toolbar-print-event =
    .title = Termine oder Aufgaben drucken
toolbar-new-event-label = Termin
toolbar-new-event =
    .title = Neuen Termin erstellen
toolbar-new-task-label = Aufgabe
toolbar-new-task =
    .title = Neue Aufgabe erstellen
toolbar-go-back-label = Zurück
toolbar-go-back =
    .title = Eine Nachricht zurück in der Chronik der angesehenen Nachrichten
toolbar-go-forward-label = Vor
toolbar-go-forward =
    .title = Eine Nachricht vorwärts in der Chronik der angesehenen Nachrichten
toolbar-stop-label = Stopp
toolbar-stop =
    .title = Aktuelle Übertragung stoppen
toolbar-throbber-label = Aktivitätsindikator
toolbar-throbber =
    .title = Aktivitätsindikator
toolbar-create-contact-label = Neuer Kontakt
toolbar-create-contact =
    .title = Neuen Kontakt anlegen
toolbar-create-address-book-label = Neues Adressbuch
toolbar-create-address-book =
    .title = Neues Adressbuch anlegen
toolbar-create-list-label = Neue Liste
toolbar-create-list =
    .title = Neue Mailingliste anlegen
toolbar-import-contacts-label = Importieren
toolbar-import-contacts =
    .title = Kontakte aus einer Datei importieren

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Lokales Adressbuch hinzufügen
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = CardDAV-Adressbuch hinzufügen
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = LDAP-Adressbuch hinzufügen
