# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Nastavenia nevyžiadanej pošty
dialog-header-title =
    .value = Nastavenia nevyžiadanej pošty
training-description-spam = Ak je táto funkcia povolená, musíte najskôr { -brand-short-name(case: "acc") } naučiť nevyžiadanú poštu identifikovať. Pomocou tlačidla Nevyžiadaná správa na paneli s nástrojmi označte doručené správy ako normálne alebo ako nevyžiadané. Následne bude { -brand-short-name } schopný automaticky označovať nevyžiadané správy.
spam-level-checkbox =
    .label = Povoliť rozpoznávanie nevyžiadanej pošty pre tento účet
    .accesskey = P
move-spam-message-menuitem =
    .label = Správy rozpoznané ako nevyžiadané automaticky presúvať do:
    .accesskey = S
set-spam-folder-menuitem =
    .label = Priečinok “Nevyžiadaná pošta” v účte:
    .accesskey = N
move-message-other =
    .label = inde:
    .accesskey = i
automatic-spam-purge-checkbox =
    .label = Automaticky odstraňovať správy označené ako nevyžiadané po
    .accesskey = u
automatic-spam-purge-label =
    .value = dňoch
trust-addresses-header-label =
    .value = Považovať e‑mailové adresy v týchto adresároch za dôveryhodné:
    .accesskey = e
allowlist-header-label =
    .value = Neoznačovať automaticky správy ako nevyžiadané, ak sa odosielateľ nachádza v:
    .accesskey = e
isp-headers-checkbox =
    .label = Dôverovať hlavičkám nevyžiadanej pošty nastaveným nástrojom:
    .accesskey = D
isp-warning-description = Ak je táto voľba zapnutá, { -brand-short-name } bude automaticky považovať správy označené touto externou kontrolou ako nevyžiadané.
spam-detecting-legend = Rozpoznávanie nevyžiadanej pošty
spam-storage-deletion-legend = Uchovávanie a odstraňovanie
spam-classification-legend = Rozpoznávanie nevyžiadanej pošty
spam-actions-legend = Presúvanie a odstraňovanie správ
global-spam-preferences-button =
    .label = Globálne nastavenia nevyžiadanej pošty…
    .accesskey = G
manage-spam-title = Správa nevyžiadanej pošty
manage-spam-header =
    .value = Správa nevyžiadanej pošty
training-description-learns = Keď je táto funkcia zapnutá, { -brand-short-name } sa učí zo správ, ktoré označíte ako nevyžiadané alebo legitímne. Čím viac ho trénujete, tým lepšie dokáže { -brand-short-name } rozpoznávať nevyžiadanú poštu.
spam-auto-detection-checkbox =
    .label = Povoliť automatické rozpoznávanie nevyžiadanej pošty v tomto účte
    .accesskey = o
