# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Nastavenie režimu offline
autodetect-connection-label =
    .label = Automaticky prepnúť režim po zistení internetového pripojenia
    .accesskey = A
offline-startup-label = Pri spustení { -brand-short-name(case: "gen") }:
status-radio-last-used =
    .label = Použiť naposledy použitý režim pripojenia
    .accesskey = u
status-radio-ask-connect =
    .label = Opýtať sa, či sa má pripojiť k internetu
    .accesskey = O
status-radio-start-online =
    .label = Spustiť s pripojením k internetu
    .accesskey = S
status-radio-start-offline =
    .label = Spustiť bez pripojenia k internetu
    .accesskey = u
going-online-prompt = Odoslať správy čakajúce v priečinku Na odoslanie
going-online-send =
    .label = Áno, odoslať automaticky
    .accesskey = a
going-online-keep =
    .label = Nie, ponechať v priečinku Na odoslanie
    .accesskey = N
going-online-ask-send =
    .label = Pred odoslaním sa opýtať
    .accesskey = r
going-offline-prompt = Chcete si stiahnuť správy, aby ste ich mohli čítať bez pripojenia?
going-offline-download =
    .label = Áno, sťahovať automaticky
    .accesskey = s
going-offline-keep =
    .label = Nie, nesťahovať
    .accesskey = i
going-offline-ask-download =
    .label = Pred stiahnutím sa opýtať
    .accesskey = e
autodetect-online-label =
    .label = Automaticky použiť zistený stav online/offline
    .accesskey = m
offline-preference-startup-label = Pri štarte použiť režim:
status-radio-remember =
    .label = Pamätať si predchádzajúci stav online/offline
    .accesskey = P
status-radio-ask =
    .label = Opýtať sa na stav online/offline
    .accesskey = O
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Odoslať neodoslanú poštu pri prechode do režimu online?
going-online-auto =
    .label = Áno, odoslať
    .accesskey = d
going-online-not =
    .label = Nie, neodoslať
    .accesskey = n
going-online-ask =
    .label = Vždy sa opýtať
    .accesskey = a
going-offline-label = Pri prechode do režimu offline stiahnuť správy na použitie v tomto režime?
going-offline-auto =
    .label = Áno, stiahnuť
    .accesskey = s
going-offline-not =
    .label = Nie, nesťahovať
    .accesskey = h
going-offline-ask =
    .label = Vždy sa opýtať
    .accesskey = t
