# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-isrepeating-event =
    .label = ir atkārtots notikums
header-isrepeating-task =
    .label = ir atkārtots uzdevums
header-containsrepeating-event =
    .label = satur atkārtotus notikumus
header-containsrepeating-task =
    .label = satur atkārtotus uzdevumus
header-containsrepeating-mixed =
    .label = satur atkārtotus dažāda veida vienumus
windowtitle-event-copy = Kopēt atkārtojošos notikumu
windowtitle-task-copy = Kopēt atkārtojošos uzdevumu
windowtitle-mixed-copy = Kopēt atkārtojošos vienumus
windowtitle-event-cut = Izgriezt atkārtotu notikumu
windowtitle-task-cut = Izgriezt atkārtotu uzdevumu
windowtitle-mixed-cut = Izgriezt atkārtojošos vienumus
windowtitle-event-delete = Izdzēst atkārtojošos notikumu
windowtitle-task-delete = Izdzēst atkārtojošos uzdevumu
windowtitle-mixed-delete = Izdzēst atkārtojošos vienumus
windowtitle-event-edit = Labot atkārtojošos notikumu
windowtitle-task-edit = Labot atkārtojošos uzdevumu
windowtitle-mixed-edit = Labot atkārtojošos vienumus
windowtitle-multipleitems =
    .value = Atlasītie vienumi
button-single-occurrence-copy =
    .label = Kopēt tikai šo gadījumu
    .accesskey = t
button-single-occurrence-cut =
    .label = Izgriezt tikai šo gadījumu
    .accesskey = t
button-single-occurrence-delete =
    .label = Izdzēst tikai šo gadījumu
    .accesskey = t
button-single-occurrence-edit =
    .label = Labot tikai šo gadījumu
    .accesskey = t
button-multiple-occurrence-copy =
    .label = Kopēt tikai atlasītos gadījumus
    .accesskey = t
button-multiple-occurrence-cut =
    .label = Izgriezt tikai atlasītos gadījumus
    .accesskey = t
button-multiple-occurrence-delete =
    .label = Izdzēst tikai atlasītos gadījumus
    .accesskey = t
button-multiple-occurrence-edit =
    .label = Labot tikai atlasītos gadījumus
    .accesskey = t
button-single-allfollowing-copy =
    .label = Kopēt šo un visus turpmākos gadījumus
    .accesskey = t
button-single-allfollowing-cut =
    .label = Izgriezt šo un visus turpmākos gadījumus
    .accesskey = t
button-single-allfollowing-delete =
    .label = Izdzēst šo un visus turpmākos gadījumus
    .accesskey = t
button-single-allfollowing-edit =
    .label = Labot šo un visus turpmākos gadījumus
    .accesskey = t
button-multiple-allfollowing-copy =
    .label = Kopēt atlasīto un visus turpmākos gadījumus
    .accesskey = t
button-multiple-allfollowing-cut =
    .label = Izgriezt atlasīto un visus turpmākos gadījumus
    .accesskey = p
button-multiple-allfollowing-delete =
    .label = Izdzēst atlasīto un visus turpmākos gadījumus
    .accesskey = p
button-multiple-allfollowing-edit =
    .label = Labot atlasīto un visus turpmākos gadījumus
    .accesskey = p
button-single-parent-copy =
    .label = Kopēt visus gadījumus
    .accesskey = v
button-single-parent-cut =
    .label = Izgriezt visus gadījumus
    .accesskey = v
button-single-parent-delete =
    .label = Izdzēst visus gadījumus
    .accesskey = v
button-single-parent-edit =
    .label = Labot visus gadījumus
    .accesskey = v
button-multiple-parent-copy =
    .label = Kopēt visus atlasīto vienumu gadījumus
    .accesskey = v
button-multiple-parent-cut =
    .label = Izgriezt visus atlasīto vienumu gadījumus
    .accesskey = v
button-multiple-parent-delete =
    .label = Izdzēst visus atlasīto vienumu gadījumus
    .accesskey = v
button-multiple-parent-edit =
    .label = Labot visus atlasīto vienumu gadījumus
    .accesskey = v
buttons-single-occurrence-copy =
    .label = Kopēt tikai šo gadījumu
buttons-single-occurrence-cut =
    .label = Izgriezt tikai šo gadījumu
buttons-single-occurrence-delete =
    .label = Izdzēst tikai šo gadījumu
buttons-single-occurrence-edit =
    .label = Labot tikai šo gadījumu
buttons-multiple-occurrence-copy =
    .label = Kopēt tikai atlasītos gadījumus
buttons-multiple-occurrence-cut =
    .label = Izgriezt tikai atlasītos gadījumus
buttons-multiple-occurrence-delete =
    .label = Izdzēst tikai atlasītos gadījumus
buttons-multiple-occurrence-edit =
    .label = Labot tikai atlasītos gadījumus
buttons-single-allfollowing-copy =
    .label = Kopēt šo un visus turpmākos gadījumus
buttons-single-allfollowing-cut =
    .label = Izgriezt šo un visus turpmākos gadījumus
buttons-single-allfollowing-delete =
    .label = Izdzēst šo un visus turpmākos gadījumus
buttons-single-allfollowing-edit =
    .label = Labot šo un visus turpmākos gadījumus
buttons-multiple-allfollowing-copy =
    .label = Kopēt atlasīto un visus turpmākos gadījumus
buttons-multiple-allfollowing-cut =
    .label = Izgriezt atlasīto un visus turpmākos gadījumus
buttons-multiple-allfollowing-delete =
    .label = Izdzēst atlasīto un visus turpmākos gadījumus
buttons-multiple-allfollowing-edit =
    .label = Labot atlasīto un visus turpmākos gadījumus
buttons-single-parent-copy =
    .label = Kopēt visus gadījumus
buttons-single-parent-cut =
    .label = Izgriezt visus gadījumus
buttons-single-parent-delete =
    .label = Izdzēst visus gadījumus
buttons-single-parent-edit =
    .label = Labot visus gadījumus
buttons-multiple-parent-copy =
    .label = Kopēt visus atlasīto vienumu gadījumus
buttons-multiple-parent-cut =
    .label = Izgriezt visus atlasīto vienumu gadījumus
buttons-multiple-parent-delete =
    .label = Izdzēst visus atlasīto vienumu gadījumus
buttons-multiple-parent-edit =
    .label = Labot visus atlasīto vienumu gadījumus
