# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

header-comment =
    .value = Piebilde
calendar-item-summary-calendar = Kalendārs:
calendar-item-summary-task-start = Sākuma datums:
calendar-item-summary-event-start = Sākuma datums:
calendar-item-summary-task-due = Beigu datums:
calendar-item-summary-event-end = Beigu datums:
calendar-item-summary-repeat = Atkārtot:
calendar-item-summary-location = Norises vieta:
calendar-item-summary-category = Kategorija:
calendar-item-summary-organizer = Rīkotājs:
calendar-item-summary-status = Stāvoklis:
calendar-item-summary-reminder = Atgādinājums:
calendar-item-summary-attachments = Pielikumi:
calendar-item-summary-status-tentative = Iespējami
calendar-item-summary-status-confirmed = Apstiprināts
calendar-item-summary-event-status-cancelled = Atcelts
calendar-item-summary-todo-status-cancelled = Atcelts
calendar-item-summary-status-needs-action = Nepieciešama rīcība
calendar-item-summary-status-in-process = Notiekošs
calendar-item-summary-status-completed = Pabeigts
calendar-item-summary-reminder-0-minutes-before =
    .label = Pirms mazāk nekā minūtes
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 minūtes pirms
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 minūtes pirms
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 minūtes pirms
calendar-item-summary-reminder-1-hour-before =
    .label = 1 stundu pirms
calendar-item-summary-reminder-2-hours-before =
    .label = 2 stundas pirms
calendar-item-summary-reminder-12-hours-before =
    .label = 12 stundas pirms
calendar-item-summary-reminder-1-day-before =
    .label = 1 dienu pirms
calendar-item-summary-reminder-2-days-before =
    .label = 2 dienas pirms
calendar-item-summary-reminder-1-week-before =
    .label = 1 nedēļu pirms
calendar-item-summary-reminder-custom =
    .label = Pielāgots...
calendar-item-summary-reminder-multiple =
    .value = Vairāki atgādinājumi…
calendar-item-summary-general =
    .value = Vispārīgi
calendar-item-summary-attendees =
    .value = Dalībnieki
calendar-item-summary-description =
    .value = Apraksts
calendar-item-summary-link =
    .value = Saistītā saite
