# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Espace flexible
search-bar-label = Rechercher
toolbar-write-message-label = Écrire
toolbar-write-message =
    .title = Créer un nouveau message
toolbar-move-to-label = Déplacer vers
toolbar-move-to =
    .title = Déplacer le message sélectionné
toolbar-unifinder-label = Recherche d’évènements
toolbar-unifinder =
    .title = Afficher/Masquer le panneau de recherche d’évènements
toolbar-folder-location-label = Emplacement du dossier
toolbar-folder-location =
    .title = Aller au dossier
toolbar-edit-event-label = Modifier
toolbar-edit-event =
    .title = Modifier la tâche ou l’évènement sélectionné
toolbar-get-messages-label = Relever
toolbar-get-messages =
    .title = Récupérer les nouveaux messages de tous les comptes
toolbar-reply-label = Répondre
toolbar-reply =
    .title = Répondre au message
toolbar-reply-all-label = Rép. à tous
toolbar-reply-all =
    .title = Répondre à l’expéditeur et à tous les destinataires
toolbar-reply-to-list-label = Rép. à la liste
toolbar-reply-to-list =
    .title = Répondre à la liste de diffusion
toolbar-redirect-label = Rediriger
toolbar-redirect =
    .title = Rediriger le message sélectionné
toolbar-archive-label = Archiver
toolbar-archive =
    .title = Archiver les messages sélectionnés
toolbar-conversation-label = Conversation
toolbar-conversation =
    .title = Afficher la conversation du message sélectionné
toolbar-previous-unread-label = Non lu précédent
toolbar-previous-unread =
    .title = Aller au précédent message non lu
toolbar-previous-label = Précédent
toolbar-previous =
    .title = Aller au précédent message
toolbar-next-unread-label = Non lu suivant
toolbar-next-unread =
    .title = Aller au prochain message non lu
toolbar-next-label = Suivant
toolbar-next =
    .title = Aller au prochain message
toolbar-junk-label = Indésirable
toolbar-junk =
    .title = Marquer le message sélectionné comme indésirable
toolbar-delete-label = Supprimer
toolbar-delete-title =
    .title = Supprimer les messages sélectionnés
toolbar-undelete-label = Restaurer
toolbar-undelete =
    .title = Restaurer les messages sélectionnés
toolbar-compact-label = Compacter
toolbar-compact =
    .title = Retirer les messages supprimés du dossier sélectionné
toolbar-add-as-event-label = Ajouter comme évènement
toolbar-add-as-event =
    .title = Extraire les informations temporelles du message et les ajouter à votre agenda en tant qu’évènement
toolbar-add-as-task-label = Ajouter comme tâche
toolbar-add-as-task =
    .title = Extraire les informations temporelles du message et les ajouter à votre agenda en tant que tâche
toolbar-tag-message-label = Étiquette
toolbar-tag-message =
    .title = Étiqueter les messages
toolbar-forward-inline-label = Transférer
toolbar-forward-inline =
    .title = Transférer le message sélectionné au format intégré
toolbar-forward-attachment-label = Transférer au format pièce jointe
toolbar-forward-attachment =
    .title = Transférer le message sélectionné au format pièce jointe
toolbar-mark-as-label = Marquer
toolbar-mark-as =
    .title = Marquer les messages
toolbar-view-picker-label = Affichage
toolbar-view-picker =
    .title = Personnaliser l’affichage du dossier courant
toolbar-address-book-label = Carnet d’adresses
toolbar-address-book =
    .title = Ouvrir le carnet d’adresses
toolbar-chat-label = Messagerie instantanée
toolbar-chat =
    .title = Afficher l’onglet de messagerie instantanée
toolbar-add-ons-and-themes-label = Modules complémentaires et thèmes
toolbar-add-ons-and-themes =
    .title = Gestion de vos modules complémentaires
toolbar-calendar-label = Agenda
toolbar-calendar =
    .title = Aller à l’onglet d’agenda
toolbar-tasks-label = Tâches
toolbar-tasks =
    .title = Aller à l’onglet des tâches
toolbar-mail-label = Courrier
toolbar-mail =
    .title = Aller à l’onglet Courrier
toolbar-print-label = Imprimer
toolbar-print =
    .title = Imprimer ce message
toolbar-quick-filter-bar-label = Filtre rapide
toolbar-quick-filter-bar =
    .title = Filtrer les messages
toolbar-synchronize-label = Synchroniser
toolbar-synchronize =
    .title = Actualiser les agendas et synchroniser les changements
toolbar-delete-event-label = Supprimer
toolbar-delete-event =
    .title = Supprimer les tâches ou évènements sélectionnés
toolbar-go-to-today-label = Aujourd’hui
toolbar-go-to-today =
    .title = Aller à la date d’aujourd’hui
toolbar-print-event-label = Imprimer
toolbar-print-event =
    .title = Imprimer des tâches ou des évènements
toolbar-new-event-label = Évènement
toolbar-new-event =
    .title = Créer un nouvel évènement
toolbar-new-task-label = Tâche
toolbar-new-task =
    .title = Créer une nouvelle tâche
toolbar-go-back-label = Reculer
toolbar-go-back =
    .title = Reculer d’un message
toolbar-go-forward-label = Avancer
toolbar-go-forward =
    .title = Avancer d’un message
toolbar-stop-label = Arrêter
toolbar-stop =
    .title = Arrêter le transfert courant
toolbar-throbber-label = Indicateur d’activité
toolbar-throbber =
    .title = Indicateur d’activité
toolbar-create-contact-label = Nouveau contact
toolbar-create-contact =
    .title = Créer un nouveau contact
toolbar-create-address-book-label = Nouveau carnet d’adresses
toolbar-create-address-book =
    .title = Créer un nouveau carnet d’adresses
toolbar-create-list-label = Nouvelle liste
toolbar-create-list =
    .title = Créer une nouvelle liste de diffusion
toolbar-import-contacts-label = Importer
toolbar-import-contacts =
    .title = Importer des contacts depuis un fichier

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Ajouter un carnet d’adresses local
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Ajouter un carnet d’adresses CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Ajouter un carnet d’adresses LDAP
