# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Pyta so…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 wotpowědnik namakany;#1 wotpowědnikaj namakanej;#1 wotpowědniki namakane;#1 wotpowědnikow namakanych
noMatchesFound = Žane wotpowědnikow njejsu namakane
labelForStopButton = Stój
labelForSearchButton = Pytać
labelForStopButton.accesskey = S
labelForSearchButton.accesskey = P
moreButtonTooltipText = Nowe prawidło přidać
lessButtonTooltipText = Tute prawidło wotstronić
