# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

spam-settings-title = Gosodiadau Sbam
dialog-header-title =
    .value = Gosodiadau Sbam
training-description-spam = Os yw wedi'i alluogi, yn gyntaf rhaid i chi hyfforddi { -brand-short-name } i adnabod sbam trwy ddefnyddio'r botwm bar offer Sbam i farcio negeseuon fel sbam neu beidio. Mae angen i chi adnabod negeseuon sbam a'r rhai sydd ddim. Ar ôl hynny bydd { -brand-short-name } yn gallu marcio sbam yn awtomatig.
spam-level-checkbox =
    .label = Galluogi rheolyddion sbam addasol ar gyfer y cyfrif hwn
    .accesskey = G
move-spam-message-menuitem =
    .label = Symud negeseuon sbam newydd i:
    .accesskey = S
set-spam-folder-menuitem =
    .label = Ffolder “Sbam” ar:
    .accesskey = F
move-message-other =
    .label = Arall:
    .accesskey = a
automatic-spam-purge-checkbox =
    .label = Yn awtomatig dileu sbam sy'n hŷn na
    .accesskey = D
automatic-spam-purge-label =
    .value = diwrnod
trust-addresses-header-label =
    .value = Ymddiriedwch gyfeiriadau e-bost yn y llyfrau cyfeiriadau hyn:
    .accesskey = Y
allowlist-header-label =
    .value = Peidio â marcio e-byst yn awtomatig fel sbam os yw'r anfonwr yn:
    .accesskey = P
isp-headers-checkbox =
    .label = Ymddiried mewn penynnau sbam wedi'u gosod gan:
    .accesskey = Y
isp-warning-description = Os wedi ei alluogi, bydd { -brand-short-name } yn ystyried yn awtomatig negeseuon sydd wedi'u marcio gan y dosbarthwr allanol hwn fel sbam.
spam-detecting-legend = Canfod sbam
spam-storage-deletion-legend = Storio a dileu
spam-classification-legend = Dewis
spam-actions-legend = Cyrchfan a Chadw
global-spam-preferences-button =
    .label = Gosodiadau Eang Sbam…
    .accesskey = E
manage-spam-title = Rheoli sbam
manage-spam-header =
    .value = Rheoli sbam
training-description-learns = Pan gaiff ei droi ymlaen, mae { -brand-short-name } yn dysgu o'r negeseuon rydych chi'n eu marcio fel sbam neu nid sbam. Po fwyaf y byddwch chi'n ei hyfforddi, y gorau y bydd { -brand-short-name } yn ei gael am ganfod sbam.
spam-auto-detection-checkbox =
    .label = Trowch canfod sbam awtomatig ymlaen ar gyfer y cyfrif hwn
    .accesskey = T
