# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Gosodiadau All-lein
autodetect-connection-label =
    .label = Newid moddau yn awtomatig ar ôl canfod cysylltiad rhyngrwyd
    .accesskey = N
offline-startup-label = Wrth agor { -brand-short-name }:
status-radio-last-used =
    .label = Defnyddio'r modd cysylltu defnyddiwyd diwethaf
    .accesskey = D
status-radio-ask-connect =
    .label = Gofyn os ydych am gysylltu ar-lein
    .accesskey = G
status-radio-start-online =
    .label = Cychwyn ar-lein
    .accesskey = C
status-radio-start-offline =
    .label = Cychwyn all-lein
    .accesskey = a
going-online-prompt = Anfon negeseuon sy'n aros yn eich Blwch Anfon
going-online-send =
    .label = Iawn, anfon yn awtomatig
    .accesskey = I
going-online-keep =
    .label = Na, eu cadw yn y Blwch Anfon
    .accesskey = N
going-online-ask-send =
    .label = Gofyn cyn anfon
    .accesskey = G
going-offline-prompt = Ydych chi am lwytho negeseuon i lawr i'w darllen all-lein?
going-offline-download =
    .label = Ydw, eu llwythi  lawr yn awtomatig
    .accesskey = Y
going-offline-keep =
    .label = Na, peidio'u llwytho i lawr
    .accesskey = N
going-offline-ask-download =
    .label = Gofyn cyn llwytho i lawr
    .accesskey = G
autodetect-online-label =
    .label = Dilyn y cyflwr ar-lein canfuwyd, yn awtomatig
    .accesskey = c
offline-preference-startup-label = Cyflwr â llaw wrth gychwyn:
status-radio-remember =
    .label = Cofio'r cyflwr ar-lein diwethaf
    .accesskey = o
status-radio-ask =
    .label = Gofyn i mi am y cyflwr ar-lein
    .accesskey = G
status-radio-always-online =
    .label = Ar-lein
    .accesskey = r
status-radio-always-offline =
    .label = All-lein
    .accesskey = l
going-online-label = Anfon negeseuon sydd heb eu hanfon wrth fynd ar-lein?
going-online-auto =
    .label = Iawn
    .accesskey = I
going-online-not =
    .label = Na
    .accesskey = N
going-online-ask =
    .label = Gofyn i mi
    .accesskey = G
going-offline-label = Llwytho negeseuon i lawr ar gyfer defnydd all-lein wrth fynd all-lein?
going-offline-auto =
    .label = Iawn
    .accesskey = w
going-offline-not =
    .label = Na
    .accesskey = a
going-offline-ask =
    .label = Gofyn i mi
    .accesskey = f
