# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = Derbynebau Dychwelyd
return-receipt-checkbox-control =
    .label = Wrth anfon negeseuon, gofyn bob tro am dderbynneb dychwelyd
    .accesskey = a
receipt-arrive-label = Pan fydd derbynneb yn cyrraedd:
receipt-leave-inbox-control =
    .label = Gadael yn y Mewnflwch
    .accesskey = G
receipt-move-sent-control =
    .label = Symud i'r ffolder Anfonwyd
    .accesskey = S
receipt-sender-request-label = Pan fydd anfonwr yn gofyn am dderbynneb dychwelyd:
receipt-leave-radio-control =
    .label = Gadael yn fy Mlwch Derbyn
    .accesskey = G
receipt-move-radio-control =
    .label = Symud i fy ffolder "Anfonwyd"
    .accesskey = S
receipt-request-label = Pan fyddaf yn derbyn cais am dderbynneb dychwelyd:
receipt-return-never-radio-control =
    .label = Peidio byth anfon derbynneb dychwelyd
    .accesskey = P
receipt-return-some-radio-control =
    .label = Caniatáu derbynebau dychwelyd ar gyfer rhai negeseuon
    .accesskey = C
receipt-not-listed-cc-label =
    .value = Os nad yw wedi'i restru ym maes To neu CC:
    .accesskey = O
receipt-not-to-cc-label =
    .value = Os nad wyf yn At neu Cc y neges:
    .accesskey = O
receipt-send-never-label =
    .label = Byth anfon
receipt-send-always-label =
    .label = Anfon pob tro
receipt-send-ask-label =
    .label = Gofyn i mi
sender-outside-company-label =
    .value = Os yw'r anfonwr y tu allan i gwmni neu barth:
    .accesskey = O
sender-outside-domain-label =
    .value = Os yw'r anfonwr o'r tu allan i'm parth:
    .accesskey = s
other-cases-text-label =
    .value = Ym mhob achos arall:
    .accesskey = Y
read-receipts-dialog-title = Darllen derbynebau
return-receipt-request-control =
    .label = Gofynnwch am dderbynneb dychwelyd bob amser wrth anfon e-byst
    .accesskey = G
