# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = კავშირგარეშე რეჟიმის პარამეტრები
autodetect-connection-label =
    .label = რეჟიმების თვითგადართვა ქსელთან კავშირის აღმოჩენისას
    .accesskey = რ
offline-startup-label = როცა გაიხსნება { -brand-short-name }:
status-radio-last-used =
    .label = კავშირის ბოლო რეჟიმის გამოყენება
    .accesskey = ყ
status-radio-ask-connect =
    .label = შეკითხვა, მიუერთდეს თუ არა ქსელს
    .accesskey = ხ
status-radio-start-online =
    .label = კავშირზე გასვლა
    .accesskey = ს
status-radio-start-offline =
    .label = კავშირგარეშე დატოვება
    .accesskey = ტ
going-online-prompt = მომლოდინე გამავალი წერილების გაგზავნა
going-online-send =
    .label = დიახ, გაიგზავნოს თავისით
    .accesskey = დ
going-online-keep =
    .label = არა, დარჩეს გამავალ წერილთა საქაღალდეში
    .accesskey = ა
going-online-ask-send =
    .label = კითხვა გაგზავნამდე
    .accesskey = კ
going-offline-prompt = გსურთ წერილების ჩამოტვირთვა კავშირგარეშედ წასაკითხად?
going-offline-download =
    .label = დიახ, ჩამოიტვირთოს თავისით
    .accesskey = ი
going-offline-keep =
    .label = არა, არ ჩამოიტვირთოს
    .accesskey = რ
going-offline-ask-download =
    .label = შეკითხვა ჩამოტვირთვამდე
    .accesskey = კ
autodetect-online-label =
    .label = ქსელის მდგომარეობის თვითდადგენა
    .accesskey = ვ
offline-preference-startup-label = მდგომარეობის ხელით დადგენა გაშვებისას:
status-radio-remember =
    .label = კავშირის წინა სტატუსის აღდგენა
    .accesskey = R
status-radio-ask =
    .label = შეკითხვა, კავშირის მდგომარეობის შესახებ
    .accesskey = კ
status-radio-always-online =
    .label = ხაზზე
    .accesskey = ხ
status-radio-always-offline =
    .label = ხაზგარეშე
    .accesskey = რ
going-online-label = გაიგზავნოს გასაგზავნი წერილები კავშირის რეჟიმში შესვლისას?
going-online-auto =
    .label = დიახ
    .accesskey = Y
going-online-not =
    .label = არა
    .accesskey = N
going-online-ask =
    .label = შეკითხვა ყოველ ჯერზე
    .accesskey = s
going-offline-label = ჩამოიტვირთოს წერილები კავშირგარეშე რეჟიმში გადასვლისას?
going-offline-auto =
    .label = დიახ
    .accesskey = e
going-offline-not =
    .label = არა
    .accesskey = o
going-offline-ask =
    .label = შეკითხვა ყოველ ჯერზე
    .accesskey = a
