# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

receipts-dialog-title = მიღების დასტური
return-receipt-checkbox-control =
    .label = წერილის გაგზავნისას მიღების დასტურის ყოველთვის მოთხოვნა
    .accesskey = ბ
receipt-arrive-label = მიღების დასტურის მოსვლისას:
receipt-leave-inbox-control =
    .label = დარჩეს მიღებულ წერილებში
    .accesskey = დ
receipt-move-sent-control =
    .label = გადავიდეს გაგზავნილების საქაღალდეში
    .accesskey = გ
receipt-sender-request-label = როცა გამომგზავნი ითხოვს დასტურის დაბრუნებას:
receipt-leave-radio-control =
    .label = დარჩეს მიღებულ წერილებში
    .accesskey = მ
receipt-move-radio-control =
    .label = გადავიდეს საქაღალდეში „გაგზავნილი“
    .accesskey = ზ
receipt-request-label = მიღების საპასუხო დასტურის მოთხოვნისას:
receipt-return-never-radio-control =
    .label = დასტურის დაბრუნების გარეშე
    .accesskey = უ
receipt-return-some-radio-control =
    .label = დასტურის დაბრუნება ზოგიერთ წერილზე
    .accesskey = ზ
receipt-not-listed-cc-label =
    .value = თუ არაა ჩამოთვლილი მიმღების ან ასლის ველებში:
    .accesskey = თ
receipt-not-to-cc-label =
    .value = თუ არ ვარ წერილის „მიმღების“ ან „ასლის“ ველებში:
    .accesskey = თ
receipt-send-never-label =
    .label = არასდროს გაიგზავნოს
receipt-send-always-label =
    .label = გაიგზავნოს ყოველთვის
receipt-send-ask-label =
    .label = შეკითხვა ყოველ ჯერზე
sender-outside-company-label =
    .value = თუ გამომგზავნი კომპანიის ან სახელთა სივრცის მიღმაა:
    .accesskey = ც
sender-outside-domain-label =
    .value = თუ გამომგზავნი ჩემი დომენიდან არაა:
    .accesskey = თ
other-cases-text-label =
    .value = ყველა სხვა შემთხვევაში:
    .accesskey = ვ
read-receipts-dialog-title = დასტურების წაკითხვა
return-receipt-request-control =
    .label = ელფოსტის გაგზავნისას საპასუხო დასტურის ყოველთვის მოთხოვნა
    .accesskey = პ
