# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Эластычны інтэрвал
search-bar-label = Пошук
toolbar-write-message-label = Стварыць
toolbar-write-message =
    .title = Стварыць новае паведамленне
toolbar-move-to-label = Перамясціць у
toolbar-move-to =
    .title = Перамясціць выбранае паведамленне
toolbar-unifinder-label = Знайсці падзеі
toolbar-unifinder =
    .title = Пераключыць адлюстраванне панэлі пошуку падзей
toolbar-folder-location-label = Месцазнаходжанне папкі
toolbar-folder-location =
    .title = Перайсці ў папку
toolbar-edit-event-label = Рэдагаваць
toolbar-edit-event =
    .title = Рэдагаваць выбраную падзею або задачу
toolbar-get-messages-label = Атрымаць паведамленні
toolbar-get-messages =
    .title = Атрымаць новыя паведамленні для ўсіх уліковых запісаў
toolbar-reply-label = Адказаць
toolbar-reply =
    .title = Адказаць на паведамленне
toolbar-reply-all-label = Адказаць усім
toolbar-reply-all =
    .title = Адказаць адпраўніку і ўсім атрымальнікам
toolbar-redirect-label = Перанакіраваць
toolbar-redirect =
    .title = Перанакіраваць выбранае паведамленне
toolbar-archive-label = Архіваваць
toolbar-archive =
    .title = Архіваваць вылучаныя паведамленні
toolbar-previous-unread-label = Папярэдняе непрачытанае
toolbar-previous-unread =
    .title = Перайсці да папярэдняга непрачытанага паведамлення
toolbar-previous-label = Папярэдняе
toolbar-previous =
    .title = Перайсці да папярэдняга паведамлення
toolbar-next-unread-label = Наступнае непрачытанае
toolbar-next-unread =
    .title = Перайсці да наступнага непрачытанага паведамлення
toolbar-next-label = Наступнае
toolbar-next =
    .title = Перайсці да наступнага паведамлення
toolbar-junk-label = Спам
toolbar-junk =
    .title = Пазначыць выбраныя паведамленні як спам
toolbar-delete-label = Выдаліць
toolbar-delete-title =
    .title = Выдаліць выбраныя паведамленні
toolbar-undelete-label = Аднавіць
toolbar-undelete =
    .title = Аднавіць выбраныя паведамленні
toolbar-compact-label = Сціснуць
toolbar-compact =
    .title = Прыбраць выдаленыя паведамленні з выбранай папкі
toolbar-add-as-event-label = Дадаць як падзею
toolbar-add-as-event =
    .title = Выцягнуць каляндарную інфармацыю з паведамлення і дадаць яе ў ваш каляндар як падзею
toolbar-add-as-task-label = Дадаць як задачу
toolbar-add-as-task =
    .title = Выцягнуць каляндарную інфармацыю з паведамлення і дадаць яе ў ваш каляндар як задачу
toolbar-tag-message-label = Метка
toolbar-tag-message =
    .title = Памеціць паведамленні
toolbar-forward-inline-label = Пераслаць
toolbar-forward-inline =
    .title = Пераслаць выбранае паведамленне ў целе паведамлення
toolbar-forward-attachment-label = Пераслаць як прымацаванне
toolbar-forward-attachment =
    .title = Пераслаць выбранае паведамленне як прымацаванне
toolbar-mark-as-label = Пазначыць
toolbar-mark-as =
    .title = Пазначыць лісты
toolbar-address-book-label = Адрасная кніга
toolbar-address-book =
    .title = Перайсці ў адрасную кнігу
toolbar-chat-label = Чат
toolbar-chat =
    .title = Паказаць укладку чата
toolbar-add-ons-and-themes-label = Дадаткі і тэмы
toolbar-add-ons-and-themes =
    .title = Кіраваць вашымі дадаткамі
toolbar-calendar-label = Каляндар
toolbar-calendar =
    .title = Пераключыцца на ўкладку календара
toolbar-tasks-label = Задачы
toolbar-tasks =
    .title = Пераключыцца на ўкладку задач
toolbar-mail-label = Пошта
toolbar-mail =
    .title = Пераключыцца на ўкладку пошты
toolbar-print-label = Друкаваць
toolbar-print =
    .title = Надрукаваць гэты ліст
toolbar-quick-filter-bar-label = Хуткі фільтр
toolbar-quick-filter-bar =
    .title = Фільтраваць паведамленні
toolbar-synchronize-label = Сінхранізаваць
toolbar-synchronize =
    .title = Перазагрузіць календары і сінхранізаваць змены
toolbar-delete-event-label = Выдаліць
toolbar-delete-event =
    .title = Выдаліць выбраныя падзеі або задачы
toolbar-go-to-today-label = Сёння
toolbar-go-to-today =
    .title = Перайсці да сённяшніх падзей
toolbar-print-event-label = Друкаваць
toolbar-print-event =
    .title = Друкаваць падзеі або задачы
toolbar-new-event-label = Падзея
toolbar-new-event =
    .title = Стварыць новую падзею
toolbar-new-task-label = Задача
toolbar-new-task =
    .title = Стварыць новую задачу
toolbar-go-back-label = Назад
toolbar-go-back =
    .title = Перамясціцца да папярэдняга ліста
toolbar-go-forward-label = Наперад
toolbar-go-forward =
    .title = Перамясціцца да наступнага ліста
toolbar-stop-label = Спыніць
toolbar-stop =
    .title = Прыпыніць цяперашні перанос
toolbar-throbber-label = Індыкатар актыўнасці
toolbar-throbber =
    .title = Індыкатар актыўнасці
toolbar-create-contact-label = Новы кантакт
toolbar-create-contact =
    .title = Стварыць новы кантакт
toolbar-create-address-book-label = Новая адрасная кніга
toolbar-create-address-book =
    .title = Стварыце новую адрасную кнігу
toolbar-import-contacts-label = Імпартаваць
toolbar-import-contacts =
    .title = Імпартаваць кантакты з файла

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Дадаць лакальную адрасную кнігу
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Дадаць адрасную кнігу CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Дадаць адрасную кнігу LDAP
