# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Unified Toolbar Item Label strings

spacer-label = Эластычны інтэрвал
search-bar-label = Пошук
toolbar-write-message-label = Стварыць
toolbar-write-message =
    .title = Стварыць новае паведамленне
toolbar-move-to-label = Перамясціць у
toolbar-move-to =
    .title = Перамясціць выбранае паведамленне
toolbar-unifinder-label = Знайсці падзеі
toolbar-unifinder =
    .title = Пераключыць адлюстраванне панэлі пошуку падзей
toolbar-folder-location-label = Месцазнаходжанне папкі
toolbar-edit-event-label = Рэдагаваць
toolbar-edit-event =
    .title = Рэдагаваць выбраную падзею або задачу
toolbar-get-messages-label = Атрымаць паведамленні
toolbar-get-messages =
    .title = Атрымаць новыя паведамленні для ўсіх уліковых запісаў
toolbar-reply-label = Адказаць
toolbar-reply =
    .title = Адказаць на паведамленне
toolbar-reply-all-label = Адказаць усім
toolbar-reply-all =
    .title = Адказаць адпраўніку і ўсім атрымальнікам
toolbar-redirect-label = Перанакіраваць
toolbar-redirect =
    .title = Перанакіраваць выбранае паведамленне
toolbar-archive-label = Архіваваць
toolbar-archive =
    .title = Архіваваць вылучаныя паведамленні
toolbar-previous-unread-label = Папярэдні непрачытаны
toolbar-previous-unread =
    .title = Перамясціцца да папярэдняга непрачытанага ліста
toolbar-previous-label = Папярэдні
toolbar-previous =
    .title = Перайсці да папаярэдняга ліста
toolbar-next-unread-label = Наступны непрачытаны
toolbar-next-unread =
    .title = Перамясціцца да наступнага непрачытанага ліста
toolbar-next-label = Наступны
toolbar-next =
    .title = Перайсці да наступнага ліста
toolbar-junk-label = Спам
toolbar-junk =
    .title = Пазначыць выбраныя паведамленні як спам
toolbar-delete-label = Выдаліць
toolbar-compact-label = Сціснуць
toolbar-compact =
    .title = Прыняць выдаленыя лісты з вылучанай папкі
toolbar-add-as-event-label = Дадаць як падзею
toolbar-add-as-event =
    .title = Выцягнуць каляндарную інфармацыю з паведамлення і дадаць яе ў ваш каляндар як падзею
toolbar-tag-message-label = Метка
toolbar-tag-message =
    .title = Меткі лістоў
toolbar-forward-inline-label = Пераслаць
toolbar-forward-inline =
    .title = Пераслаць вылучаны ліст як убудаваны тэкст
toolbar-forward-attachment-label = Пераслаць як далучэнне
toolbar-forward-attachment =
    .title = Пераслаць вылучаны ліст як далучэнне
toolbar-mark-as-label = Пазначыць
toolbar-mark-as =
    .title = Пазначыць лісты
toolbar-address-book-label = Адрасная кніга
toolbar-address-book =
    .title = Перайсці ў адрасную кнігу
toolbar-chat-label = Гутарка
toolbar-chat =
    .title = Паказаць укладку чата
toolbar-calendar-label = Каляндар
toolbar-print-label = Друкаваць
toolbar-print =
    .title = Надрукаваць гэты ліст
toolbar-synchronize-label = Сінхранізаваць
toolbar-synchronize =
    .title = Перазагрузіць календары і сінхранізаваць змены
toolbar-delete-event-label = Выдаліць
toolbar-delete-event =
    .title = Выдаліць выбраныя падзеі або задачы
toolbar-go-to-today-label = Сёння
toolbar-go-to-today =
    .title = Перайсці да сённяшніх падзей
toolbar-new-event-label = Падзея
toolbar-new-event =
    .title = Стварыць новую падзею
toolbar-go-back-label = Назад
toolbar-go-back =
    .title = Перамясціцца да папярэдняга ліста
toolbar-go-forward-label = Наперад
toolbar-go-forward =
    .title = Перамясціцца да наступнага ліста
toolbar-stop-label = Спыніць
toolbar-stop =
    .title = Прыпыніць цяперашні перанос
toolbar-throbber-label = Індыкатар актыўнасці
toolbar-throbber =
    .title = Індыкатар актыўнасці

## New Address Book popup items

toolbar-new-address-book-popup-add-js-address-book =
    .label = Дадаць лакальную адрасную кнігу
toolbar-new-address-book-popup-add-carddav-address-book =
    .label = Дадаць адрасную кнігу CardDAV
toolbar-new-address-book-popup-add-ldap-address-book =
    .label = Дадаць адрасную кнігу LDAP
