# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-item-summary-title = Վերնագիր՝
calendar-item-summary-calendar = Օրացույց՝
calendar-item-summary-task-start = Սկզբի ամսաթիվ՝
calendar-item-summary-event-start = Սկզբի ամսաթիվ՝
calendar-item-summary-task-due = Վերջնաժամկետ՝
calendar-item-summary-event-end = Ավարտի ամսաթիվ՝
calendar-item-summary-repeat = Կրկնություն՝
calendar-item-summary-location = Տեղ՝
calendar-item-summary-category = Անվանակարգ՝
calendar-item-summary-organizer = Կազմակերպիչ՝
calendar-item-summary-status = Վիճակ՝
calendar-item-summary-reminder = Հիշեցում՝
calendar-item-summary-attachments = Կցորդներ՝
calendar-item-summary-status-tentative = Նախնական
calendar-item-summary-status-confirmed = Հաստատված
calendar-item-summary-event-status-cancelled = Փակված
calendar-item-summary-todo-status-cancelled = Փակված
calendar-item-summary-status-needs-action = Գործողության կարիք ունի
calendar-item-summary-status-in-process = Ընթացքում
calendar-item-summary-status-completed = Ավարտված է
calendar-item-summary-reminder-none =
    .label = Հիշեցում չկա
calendar-item-summary-reminder-0-minutes-before =
    .label = 0 րոպե մինչ
calendar-item-summary-reminder-5-minutes-before =
    .label = 5 րոպե մինչ
calendar-item-summary-reminder-15-minutes-before =
    .label = 15 րոպե մինչ
calendar-item-summary-reminder-30-minutes-before =
    .label = 30 րոպե մինչ
calendar-item-summary-reminder-1-hour-before =
    .label = 1 ժամ մինչ
calendar-item-summary-reminder-2-hours-before =
    .label = 2 ժամ մինչ
calendar-item-summary-reminder-12-hours-before =
    .label = 12 ժամ մինչ
calendar-item-summary-reminder-1-day-before =
    .label = 1 օր մինչ
calendar-item-summary-reminder-2-days-before =
    .label = 2 օր մինչ
calendar-item-summary-reminder-1-week-before =
    .label = 1 շաբաթ մինչ
calendar-item-summary-reminder-custom =
    .label = Ընտրել…
calendar-item-summary-reminder-multiple =
    .value = Բազմակի հիշեցումներ…
calendar-item-summary-general =
    .value = Գլխավոր
calendar-item-summary-attendees =
    .value = Մասնակիցներ
calendar-item-summary-description =
    .value = Նկարագրություն
calendar-item-summary-link =
    .value = Կից հղում
