# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

vcard-displayname = Отображаемое имя
vcard-displayname-placeholder =
    .placeholder = { vcard-displayname }
vcard-entry-type-label = Тип
vcard-entry-type-home = Домашний
vcard-entry-type-work = Рабочий
vcard-entry-type-none = Нет
vcard-entry-type-custom = Персональный
vcard-name-header = Имя
vcard-n-prefix = Префикс
vcard-n-add-prefix =
    .title = Добавить префикс
vcard-n-firstname = Имя
vcard-n-add-firstname =
    .title = Добавить имя
vcard-n-middlename = Отчество
vcard-n-add-middlename =
    .title = Добавить отчество
vcard-n-lastname = Фамилия
vcard-n-add-lastname =
    .title = Добавить фамилию
vcard-n-suffix = Суффикс
vcard-n-add-suffix =
    .title = Добавить суффикс
vcard-nickname = Псевдоним
vcard-email-header = Адреса электронной почты
vcard-email-add = Добавить адрес электронной почты
vcard-email-label = Адрес электронной почты
vcard-primary-email-label = По умолчанию
vcard-url-header = Веб-сайты
vcard-url-add = Добавить веб-сайт
vcard-url-label = Веб-сайт
vcard-tel-header = Номера телефонов
vcard-tel-add = Добавить номер телефона
vcard-tel-label = Номер телефона
# Or "Mobile"
vcard-entry-type-cell = Мобильный телефон
vcard-entry-type-fax = Факс
vcard-entry-type-pager = Пейджер
vcard-tz-header = Часовой пояс
vcard-tz-add = Добавить часовой пояс
vcard-impp2-header = Мгновенные сообщения
vcard-impp-add = Добавить учётную запись чата
vcard-impp-label = Учётная запись чата
vcard-impp-select = Протокол
vcard-impp-option-other = Другое
vcard-impp-input-label = URI
vcard-impp-input-title = URI для обмена мгновенными сообщениями
vcard-bday-anniversary-header = Особые даты
vcard-bday-anniversary-add = Добавить особую дату
vcard-bday-label = День рождения
vcard-anniversary-label = Годовщина
vcard-date-day = День
vcard-date-month = Месяц
vcard-date-year = Год
vcard-adr-header = Адреса
vcard-adr-add = Добавить адрес
vcard-adr-label = Адрес
vcard-adr-delivery-label = Метка для доставки
vcard-adr-street = Улица
# Or "Locality"
vcard-adr-locality = Город
# Or "Region"
vcard-adr-region = Область/Регион
# The term "ZIP code" only applies in USA. Most locales should use "Postal code" only.
vcard-adr-code = Почтовый индекс
vcard-adr-country = Страна
vcard-note-header = Заметки
vcard-note-add = Добавить заметку
vcard-org-header = Организация
vcard-org-add = Добавить организацию
vcard-org-title = Должность
vcard-org-title-input =
    .placeholder = Должность
    .title = Должность или позиция
vcard-org-role = Роль
vcard-org-role-input =
    .placeholder = Роль в проекте
    .title = Функция или роль, выполняемая в конкретной ситуации
vcard-org-org = Организация
vcard-org-org-input =
    .placeholder = Наименование компании
    .title = Наименование организации
vcard-org-org-unit = Департамент
vcard-org-org-unit-input =
    .placeholder = Департамент
    .title = Наименование подразделения организации
vcard-custom-header = Пользовательские свойства
vcard-custom-add = Добавить пользовательские свойства
vcard-remove-button-title =
    .title = Удалить
vcard-remove-button = Удалить
