# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Nastajenja offline
autodetect-connection-label =
    .label = Modusy awtomatisce wuměnić, hdyž so internetny zwisk namaka
    .accesskey = d
offline-startup-label = Hdyž so { -brand-short-name } wočinja:
status-radio-last-used =
    .label = Zwiskowy modus wužiwać, kotrež je so jako posledni wužiwał
    .accesskey = Z
status-radio-ask-connect =
    .label = Prašeć so, hač so ma online zwjazać
    .accesskey = h
status-radio-start-online =
    .label = Online startować
    .accesskey = l
status-radio-start-offline =
    .label = Offline startować
    .accesskey = f
going-online-send =
    .label = Haj, awtomatisce pósłać
    .accesskey = H
going-online-keep =
    .label = No, we wuchadźe wobchować
    .accesskey = N
going-online-ask-send =
    .label = Před słanjom so prašeć
    .accesskey = P
going-offline-prompt = Chceće powěsće sćahnyć, zo byšće je offline čitał?
going-offline-download =
    .label = Haj, awtomatisce sćahnyć
    .accesskey = a
going-offline-keep =
    .label = Ně, njesćahnyć
    .accesskey = n
going-offline-ask-download =
    .label = Před sćehnjenjom so prašeć
    .accesskey = d
autodetect-online-label =
    .label = Wotkrytemu online-statusej awtomatisce slědować
    .accesskey = o
offline-preference-startup-label = Manuelny status při startowanju:
status-radio-remember =
    .label = Sej předchadny status online spomjatkować
    .accesskey = k
status-radio-ask =
    .label = Za online-statusom so prašeć
    .accesskey = r
status-radio-always-online =
    .label = Online
    .accesskey = l
status-radio-always-offline =
    .label = Offline
    .accesskey = f
going-online-label = Njepósłane powěsće wotesłać, hdyž online dźeće?
going-online-auto =
    .label = Haj
    .accesskey = H
going-online-not =
    .label = Ně 1
    .accesskey = 1
going-online-ask =
    .label = So prašeć
    .accesskey = p
going-offline-label = Powěsće za wužiće offline sćahnyć, hdyž offline dźeće?
going-offline-auto =
    .label = Haj
    .accesskey = a
going-offline-not =
    .label = Ně 2
    .accesskey = 2
going-offline-ask =
    .label = So prašeć
    .accesskey = o
