# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

offline-dialog-title = Frakoblet modus
autodetect-connection-label =
    .label = Bytt modus automatisk når en internettforbindelse blir funnet
    .accesskey = d
offline-startup-label = Når du åpner { -brand-short-name }:
status-radio-last-used =
    .label = Bruk den sist brukte tilkoblingsmodusen
    .accesskey = u
status-radio-ask-connect =
    .label = Spør om du vil koble til på nett
    .accesskey = p
status-radio-start-online =
    .label = Start tilkoblet
    .accesskey = t
status-radio-start-offline =
    .label = Start frakoblet
    .accesskey = f
going-online-prompt = Send meldinger som venter i utboksen
going-online-send =
    .label = Ja, send automatisk
    .accesskey = J
going-online-keep =
    .label = Nei, behold i utboksen
    .accesskey = N
going-online-ask-send =
    .label = Spør før sending
    .accesskey = S
going-offline-prompt = Vil du laste ned meldinger for å lese dem frakoblet?
going-offline-download =
    .label = Ja, last ned automatisk
    .accesskey = e
going-offline-keep =
    .label = Nei, ikke last ned
    .accesskey = k
going-offline-ask-download =
    .label = Spør før nedlasting
    .accesskey = r
autodetect-online-label =
    .label = Automatisk følg oppdaget tilkoblingstilstand
    .accesskey = A
offline-preference-startup-label = Manuell tilstand ved oppstart:
status-radio-remember =
    .label = Husk forrige tilkoblingstilstand
    .accesskey = H
status-radio-ask =
    .label = Spør meg om tilkoblingstilstanden
    .accesskey = r
status-radio-always-online =
    .label = Tilkoblet
    .accesskey = T
status-radio-always-offline =
    .label = Frakoblet
    .accesskey = F
going-online-label = Send usendte meldinger når jeg går til tilkoblet tilstand?
going-online-auto =
    .label = Ja
    .accesskey = J
going-online-not =
    .label = Nei
    .accesskey = N
going-online-ask =
    .label = Spør meg
    .accesskey = S
going-offline-label = Last ned meldinger for frakoblet bruk når jeg kobler fra?
going-offline-auto =
    .label = Ja
    .accesskey = a
going-offline-not =
    .label = Nei
    .accesskey = e
going-offline-ask =
    .label = Spør meg
    .accesskey = m
