# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Otsimine...
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = Leiti #1 vaste;Leiti #1 vastet
noMatchesFound = Vasteid ei leitud
labelForStopButton = Peata
labelForSearchButton = Otsi
labelForStopButton.accesskey = P
labelForSearchButton.accesskey = O
moreButtonTooltipText = Lisa uus reegel
lessButtonTooltipText = Eemalda see reegel
