# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

searchingMessage = Іздеу…
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound = #1 сәйкестік табылды;#1 сәйкестік табылды
noMatchesFound = Сәйкестіктер табылмады
labelForStopButton = Тоқтату
labelForSearchButton = Іздеу
labelForStopButton.accesskey = у
labelForSearchButton.accesskey = у
moreButtonTooltipText = Жаңа ережені қосу
lessButtonTooltipText = Бұл ережені өшіру
